Javolution 6.0.0 java: javolution.util.internal.table.sorted.FastSortedTableImpl< E > Class Template Reference
javolution.util.internal.table.sorted.FastSortedTableImpl< E > Class Template Reference
Public Member Functions
FastSortedTableImpl (Equality<? super E > comparator)
boolean add (E element)
boolean addIfAbsent (E element)
int indexOf (Object element)
int positionOf (E element)
SortedTableService< E > threadSafe ()
Equality<? super E > comparator ()
int size ()
void add (int index, E element)
void addFirst (E element)
void addLast (E element)
void clear ()
FastTableImpl< E > clone ()
E get (int index)
E getFirst ()
E getLast ()
Iterator< E > iterator ()
E remove (int index)
final E remove ()
final boolean remove (Object o)
E removeFirst ()
E removeLast ()
E set (int index, E element)
boolean addAll (int index, Collection<? extends E > c)
boolean addAll (Collection<? extends E > c)
FastCollection< E > addAll (E... elements)
FastCollection< E > addAll (FastCollection<? extends E > that)
final boolean contains (Object o)
Iterator< E > descendingIterator ()
final E element ()
final boolean isEmpty ()
int lastIndexOf (Object o)
final ListIterator< E > listIterator ()
ListIterator< E > listIterator (int index)
final boolean offer (E e)
final boolean offerFirst (E e)
final boolean offerLast (E e)
final E peek ()
E peekFirst ()
E peekLast ()
final E poll ()
E pollFirst ()
E pollLast ()
final E pop ()
final void push (E e)
boolean removeFirstOccurrence (Object o)
boolean removeLastOccurrence (Object o)
CollectionService< E >[] split (int n)
TableService< E > subList (int fromIndex, int toIndex)
boolean containsAll (Collection<?> c)
boolean equals (Object o)
int hashCode ()
void perform (Consumer< CollectionService< E >> action, CollectionService< E > view)
void perform (Consumer<? extends Collection< E >> action)
void perform (Consumer< T > action, T part)
boolean removeAll (Collection<?> c)
boolean retainAll (Collection<?> c)
Object[] toArray ()
void update (Consumer< CollectionService< E >> action, CollectionService< E > view)
void update (Consumer<? extends Collection< E >> action)
void update (Consumer< T > action, T part)
FastCollection< E > atomic ()
FastCollection< E > shared ()
FastCollection< E > parallel ()
FastCollection< E > sequential ()
FastCollection< E > unmodifiable ()
FastCollection< E > filtered (Predicate<? super E > filter)
FastCollection< E > sorted ()
FastCollection< E > sorted (Comparator<? super E > cmp)
FastCollection< E > reversed ()
FastCollection< E > distinct ()
void forEach (final Consumer<? super E > consumer)
boolean removeIf (final Predicate<? super E > filter)
E reduce (Reducer< E > reducer)
E min ()
E max ()
String toString ()
Protected Member Functions
void emptyError ()
void indexError (int index)
TableService< E > target ()
CollectionService< E > service ()
Static Protected Member Functions
static< E > CollectionService< E > serviceOf (FastCollection< E > collection)
Package Functions
public< T > T[] toArray (T[] a)
public< R > FastCollection< R > mapped (Function<? super E, ? extends R > function)
public< T extends E > T any (Class< T > type)
public< T extends Collection< E > > Immutable< T > toImmutable ()
Private Member Functions
int positionOf (E element, int start, int length)
void checkUpsize ()
void readObject (java.io.ObjectInputStream s) throws java.io.IOException, ClassNotFoundException
void upsize ()
void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
Private Attributes
transient int capacity
final Equality<? super E > comparator
transient FractalTableImpl fractal
transient int size
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
The default FastSortedTable implementation.
Definition at line 18 of file FastSortedTableImpl.java.
Constructor & Destructor Documentation
FastSortedTableImpl()
javolution.util.internal.table.sorted.FastSortedTableImpl< E >.FastSortedTableImpl (Equality<? super E > comparator)
Definition at line 23 of file FastSortedTableImpl.java.
{
         super(comparator);
     }
Member Function Documentation
add() [1/2]
boolean javolution.util.internal.table.sorted.FastSortedTableImpl< E >.add (E element)
Adds the specified element to this collection
Reimplemented from javolution.util.internal.table.FastTableImpl< E >.
Definition at line 28 of file FastSortedTableImpl.java.
{
         add(positionOf(element), element);
         return true;
     }
Referenced by javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.add(), javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.addIfAbsent(), and javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >.put().
add() [2/2]
void javolution.util.internal.table.FastTableImpl< E >.add (int index, E element) inherited
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 68 of file FastTableImpl.java.
{
         if ((index < 0) || (index > size)) indexError(index);
         checkUpsize();
         if (index >= (size >> 1)) {
             fractal.shiftRight(element, index, size - index);
         } else {
             fractal.shiftLeft(element, index - 1, index);
             fractal.offset--;
         }
         size++;
     }
References javolution.util.internal.table.FastTableImpl< E >.checkUpsize(), javolution.util.internal.table.TableView< E >.element(), javolution.util.internal.table.FastTableImpl< E >.fractal, javolution.util.internal.table.TableView< E >.indexError(), javolution.util.internal.table.FractalTableImpl.offset, javolution.util.internal.table.FractalTableImpl.shiftLeft(), javolution.util.internal.table.FractalTableImpl.shiftRight(), and javolution.util.internal.table.FastTableImpl< E >.size.
addAll() [1/4]
boolean javolution.util.internal.collection.CollectionView< E >.addAll (Collection<? extends E > that) inherited
Adds all the specified elements to this collection.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 46 of file CollectionView.java.
{
         boolean changed = false;
         Iterator<? extends E> it = c.iterator();
         while (it.hasNext()) {
             if (add(it.next())) changed = true;
         }
         return changed;
     }
addAll() [2/4]
FastCollection<E> javolution.util.FastCollection< E >.addAll (E... elements) inherited
Returns this collection with the specified element added.
Parameters
elements the elements to be added.
Returns
this
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSortedSet< E >, javolution.util.FastSet< E >, and javolution.util.FastSortedTable< E >.
Definition at line 552 of file FastCollection.java.
{
         for (E e : elements) {
             add(e);
         }
         return this;
     }
addAll() [3/4]
FastCollection<E> javolution.util.FastCollection< E >.addAll (FastCollection<? extends E > that) inherited
Returns this collection with the specified collection's elements added in sequence.
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSortedSet< E >, javolution.util.FastSet< E >, and javolution.util.FastSortedTable< E >.
Definition at line 564 of file FastCollection.java.
{
         addAll((Collection<? extends E>) that);
         return this;
     }
addAll() [4/4]
boolean javolution.util.internal.table.TableView< E >.addAll (int index, Collection<? extends E > c) inherited
Definition at line 40 of file TableView.java.
{
         return subList(index, index).addAll(c);
     }
References javolution.util.internal.table.TableView< E >.subList().
Referenced by javolution.util.internal.table.FastTableImpl< E >.clone().
addFirst()
void javolution.util.internal.table.FastTableImpl< E >.addFirst (E element) inherited
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 81 of file FastTableImpl.java.
{
         checkUpsize();
         fractal.offset--;
         fractal.set(0, element);
         size++;
     }
References javolution.util.internal.table.FastTableImpl< E >.checkUpsize(), javolution.util.internal.table.TableView< E >.element(), javolution.util.internal.table.FastTableImpl< E >.fractal, javolution.util.internal.table.FractalTableImpl.offset, javolution.util.internal.table.FractalTableImpl.set(), and javolution.util.internal.table.FastTableImpl< E >.size.
addIfAbsent()
boolean javolution.util.internal.table.sorted.FastSortedTableImpl< E >.addIfAbsent (E element)
Adds the specified element only if not already present.
Returns
true
if the element has been added;
false
otherwise.
Implements javolution.util.service.SortedTableService< E >.
Definition at line 34 of file FastSortedTableImpl.java.
{
         int i = positionOf(element);
         if ((i < size()) && comparator().areEqual(element, get(i))) return false; // Already there.
         add(i, element);
         return true;
     }
addLast()
void javolution.util.internal.table.FastTableImpl< E >.addLast (E element) inherited
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 89 of file FastTableImpl.java.
{
         checkUpsize();
         fractal.set(size++, element);
     }
References javolution.util.internal.table.FastTableImpl< E >.checkUpsize(), javolution.util.internal.table.TableView< E >.element(), javolution.util.internal.table.FastTableImpl< E >.fractal, javolution.util.internal.table.FractalTableImpl.set(), and javolution.util.internal.table.FastTableImpl< E >.size.
Referenced by javolution.util.internal.table.FastTableImpl< E >.add(), and javolution.util.internal.table.FastTableImpl< E >.readObject().
any()
public<T extends E> T javolution.util.FastCollection< E >.any (Class< T > type) package inherited
Returns any non-null element of the specified type (convenience method).
Parameters
type the element type searched for.
Returns
reduce(Reducers.any(type))
See also
Reducers::any
Definition at line 515 of file FastCollection.java.
{
         return (T) reduce((Reducer<E>) Reducers.any(type));
     }
References javolution.util.function.Reducers.any().
atomic()
FastCollection<E> javolution.util.FastCollection< E >.atomic () inherited
Returns an atomic view over this collection. All operations that write or access multiple elements in the collection (such as addAll(), retainAll()) are atomic. Iterators on atomic collections are thread-safe (no ConcurrentModificationException possible).
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSet< E >, javolution.util.FastSortedTable< E >, and javolution.util.FastSortedSet< E >.
Definition at line 187 of file FastCollection.java.
{
         return new AtomicCollectionImpl<E>(service());
     }
checkUpsize()
void javolution.util.internal.table.FastTableImpl< E >.checkUpsize () private inherited
Definition at line 182 of file FastTableImpl.java.
{
         if (size >= capacity) upsize();
     }
References javolution.util.internal.table.FastTableImpl< E >.capacity, javolution.util.internal.table.FastTableImpl< E >.size, and javolution.util.internal.table.FastTableImpl< E >.upsize().
Referenced by javolution.util.internal.table.FastTableImpl< E >.add(), javolution.util.internal.table.FastTableImpl< E >.addFirst(), and javolution.util.internal.table.FastTableImpl< E >.addLast().
clear()
void javolution.util.internal.table.FastTableImpl< E >.clear () inherited
Removes all elements from this collection.
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 95 of file FastTableImpl.java.
{
         fractal = null;
         capacity = 0;
         size = 0;
     }
References javolution.util.internal.table.FastTableImpl< E >.capacity, javolution.util.internal.table.FastTableImpl< E >.fractal, and javolution.util.internal.table.FastTableImpl< E >.size.
clone()
FastTableImpl<E> javolution.util.internal.table.FastTableImpl< E >.clone () inherited
Returns a copy of this collection; updates of the copy should not impact the original.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 102 of file FastTableImpl.java.
                                     { // Make a copy.
         FastTableImpl<E> copy = new FastTableImpl<E>(comparator());
         copy.addAll(this);
         return copy;
     }
References javolution.util.internal.table.TableView< E >.addAll(), and javolution.util.internal.table.FastTableImpl< E >.comparator.
comparator()
Equality<? super E> javolution.util.internal.table.FastTableImpl< E >.comparator () inherited
Returns the comparator uses by this collection for equality and/or ordering if this collection is sorted.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 109 of file FastTableImpl.java.
{
         return comparator;
     }
References javolution.util.internal.table.FastTableImpl< E >.comparator.
contains()
final boolean javolution.util.internal.table.TableView< E >.contains (Object searched) inherited
Indicates if this collection contains the specified element.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 58 of file TableView.java.
{
         return indexOf(o) >= 0;
     }
References javolution.util.internal.table.TableView< E >.indexOf().
Referenced by javolution.util.internal.table.sorted.SortedTableView< E >.addIfAbsent().
containsAll()
boolean javolution.util.internal.collection.CollectionView< E >.containsAll (Collection<?> that) inherited
Indicates if this collection contains all the specified elements.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 93 of file CollectionView.java.
{
         for (Object e : c) {
             if (!contains(e)) return false;
         }
         return true;
     }
Referenced by javolution.util.internal.collection.CollectionView< R >.equals().
descendingIterator()
Iterator<E> javolution.util.internal.table.TableView< E >.descendingIterator () inherited
Definition at line 63 of file TableView.java.
{
         return new ReversedTableImpl<E>(this).iterator();
     }
References javolution.util.internal.table.TableView< E >.iterator().
distinct()
FastCollection<E> javolution.util.FastCollection< E >.distinct () inherited
Returns a view exposing only distinct elements (it does not iterate twice over the same elements). Adding elements already in the collection through this view has no effect. If this collection is initially empty, using a distinct view to add new elements ensures that this collection has no duplicate.
Definition at line 293 of file FastCollection.java.
{
         return new DistinctCollectionImpl<E>(service());
     }
element()
final E javolution.util.internal.table.TableView< E >.element () inherited
Definition at line 68 of file TableView.java.
{
         return getFirst();
     }
References javolution.util.internal.table.TableView< E >.getFirst().
Referenced by javolution.util.internal.table.ReversedTableImpl< E >.add(), javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.add(), javolution.util.internal.table.SubTableImpl< E >.add(), javolution.util.internal.table.FastTableImpl< E >.add(), javolution.util.internal.table.TableView< E >.addFirst(), javolution.util.internal.table.FastTableImpl< E >.addFirst(), javolution.util.internal.table.sorted.SortedTableView< E >.addIfAbsent(), javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.addIfAbsent(), javolution.util.internal.table.TableView< E >.addLast(), javolution.util.internal.table.FastTableImpl< E >.addLast(), javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.indexOf(), javolution.util.internal.table.sorted.UnmodifiableSortedTableImpl< E >.positionOf(), javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.positionOf(), javolution.util.internal.table.ReversedTableImpl< E >.set(), javolution.util.internal.table.SubTableImpl< E >.set(), and javolution.util.internal.table.FastTableImpl< E >.set().
emptyError()
void javolution.util.internal.table.TableView< E >.emptyError () protected inherited
Throws NoSuchElementException
Definition at line 250 of file TableView.java.
{
         throw new NoSuchElementException("Empty Table");
     }
Referenced by javolution.util.internal.table.TableView< E >.getFirst(), javolution.util.internal.table.FastTableImpl< E >.getFirst(), javolution.util.internal.table.TableView< E >.getLast(), javolution.util.internal.table.FastTableImpl< E >.getLast(), javolution.util.internal.table.FastTableImpl< E >.removeFirst(), javolution.util.internal.table.TableView< E >.removeFirst(), javolution.util.internal.table.FastTableImpl< E >.removeLast(), and javolution.util.internal.table.TableView< E >.removeLast().
equals()
boolean javolution.util.internal.collection.CollectionView< E >.equals (Object obj) inherited
Compares the specified object with this collection for equality. This method follows the Collection#equals(Object) specification if this collection comparator is Equalities#STANDARD (default). Otherwise, only collections using the same comparator can be considered equals.
Parameters
obj the object to be compared for equality with this collection
Returns
true if both collections are considered equals; false otherwise.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 102 of file CollectionView.java.
{
         // Follow Collection.equals specification if this comparator is standard.
         if (this == o) return true;
         // Check comparators consistency.
         if (o instanceof CollectionService) {
             if (!comparator().equals(((CollectionService<E>) o).comparator())) return false; // Different comparators.
         } else {
             if (!comparator().equals(Equalities.STANDARD)) return false;
         }
         // Collection.equals contract.
         if (this instanceof Set) {
             if (!(o instanceof Set)) return false;
             Set<E> set = (Set<E>) o;
             return (size() == set.size()) && containsAll(set);
         } else if (this instanceof List) {
             if (!(o instanceof List)) return false;
             List<E> list = (List<E>) o;
             if (size() != list.size()) return false; // Short-cut.
             Equality<? super E> cmp = comparator();
             Iterator<E> it1 = this.iterator();
             Iterator<E> it2 = list.iterator();
             while (it1.hasNext()) {
                 if (!it2.hasNext()) return false;
                 if (!cmp.areEqual(it1.next(), it2.next())) return false;
             }
             if (it2.hasNext()) return false;
             return true;
         } else {
             return false;
         }
     }
Referenced by javolution.util.internal.collection.CollectionView< R >.equals().
filtered()
FastCollection<E> javolution.util.FastCollection< E >.filtered (Predicate<? super E > filter) inherited
Returns a view exposing only the elements matching the specified filter. Adding elements not matching the specified filter has no effect. If this collection is initially empty, using a filtered view to add new elements ensure that this collection has only elements satisfying the filter predicate.
Reimplemented in javolution.util.FastSet< E >.
Definition at line 250 of file FastCollection.java.
{
         return new FilteredCollectionImpl<E>(service(), filter);
     }
forEach()
void javolution.util.FastCollection< E >.forEach (final Consumer<? super E > consumer) inherited
Iterates over all this collection elements applying the specified consumer (convenience method). Iterations are performed concurrently if the collection is parallel.
Parameters
consumer the functional consumer applied to the collection elements.
Definition at line 346 of file FastCollection.java.
{
         perform(new Consumer<Collection<E>>() {
             public void accept(Collection<E> view) {
                 Iterator<E> it = view.iterator();
                 while (it.hasNext()) {
                     consumer.accept(it.next());
                 }
             }
         });
     }
References javolution.util.function.Consumer< T >.accept().
get()
E javolution.util.internal.table.FastTableImpl< E >.get (int index) inherited
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 115 of file FastTableImpl.java.
{
         if ((index < 0) && (index >= size)) indexError(index);
         return (E) fractal.get(index);
     }
References javolution.util.internal.table.FastTableImpl< E >.fractal, javolution.util.internal.table.FractalTableImpl.get(), javolution.util.internal.table.TableView< E >.indexError(), and javolution.util.internal.table.FastTableImpl< E >.size.
getFirst()
E javolution.util.internal.table.FastTableImpl< E >.getFirst () inherited
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 121 of file FastTableImpl.java.
{
         if (size == 0) emptyError();
         return get(0);
     }
References javolution.util.internal.table.TableView< E >.emptyError(), and javolution.util.internal.table.FastTableImpl< E >.size.
getLast()
E javolution.util.internal.table.FastTableImpl< E >.getLast () inherited
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 127 of file FastTableImpl.java.
{
         if (size == 0) emptyError();
         return get(size - 1);
     }
References javolution.util.internal.table.TableView< E >.emptyError(), and javolution.util.internal.table.FastTableImpl< E >.size.
hashCode()
int javolution.util.internal.collection.CollectionView< E >.hashCode () inherited
Returns the hash code of this collection. This method follows the Collection#hashCode() specification if this collection comparator is Equalities#STANDARD.
Returns
this collection hash code.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 135 of file CollectionView.java.
{
         // Follow Collection.equals specification if this comparator is standard.
         Equality<? super E> cmp = comparator();
         Iterator<E> it = this.iterator();
         int hash = 0;
         if (this instanceof Set) {
             while (it.hasNext()) {
                 hash += cmp.hashCodeOf(it.next());
             }
         } else if (this instanceof List) {
             while (it.hasNext()) {
                 hash += 31 * hash + cmp.hashCodeOf(it.next());
             }
         } else {
             hash = super.hashCode();
         }
         return hash;
     }
indexError()
void javolution.util.internal.table.TableView< E >.indexError (int index) protected inherited
Throws IndexOutOfBoundsException
Definition at line 255 of file TableView.java.
{
         throw new IndexOutOfBoundsException("index: " + index + ", size: "
                 + size());
     }
References javolution.util.internal.table.TableView< E >.size().
Referenced by javolution.util.internal.table.SubTableImpl< E >.add(), javolution.util.internal.table.FastTableImpl< E >.add(), javolution.util.internal.table.SubTableImpl< E >.get(), javolution.util.internal.table.FastTableImpl< E >.get(), javolution.util.internal.table.SubTableImpl< E >.remove(), javolution.util.internal.table.FastTableImpl< E >.remove(), javolution.util.internal.table.SubTableImpl< E >.set(), and javolution.util.internal.table.FastTableImpl< E >.set().
indexOf()
int javolution.util.internal.table.sorted.FastSortedTableImpl< E >.indexOf (Object element)
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 43 of file FastSortedTableImpl.java.
{
         int i = positionOf((E) element);
         if (i >= size() || !comparator().areEqual(get(i), (E) element)) return -1;
         return i;
     }
Referenced by javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >.get(), and javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >.remove().
isEmpty()
final boolean javolution.util.internal.table.TableView< E >.isEmpty () inherited
Indicates if this collection is empty.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 98 of file TableView.java.
{
         return size() == 0;
     }
References javolution.util.internal.table.TableView< E >.size().
iterator()
Iterator<E> javolution.util.internal.table.FastTableImpl< E >.iterator () inherited
Returns an iterator over this collection elements. For shared/atomic collections the iterator is immune to concurrent modifications. In other words the elements iterated over may or may not reflect the current state of the collection.
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 133 of file FastTableImpl.java.
{
         return new IteratorImpl();
     }
lastIndexOf()
int javolution.util.internal.table.TableView< E >.lastIndexOf (Object o) inherited
Reimplemented in javolution.util.internal.table.sorted.SortedTableView< E >, javolution.util.internal.table.UnmodifiableTableImpl< E >, and javolution.util.internal.table.ReversedTableImpl< E >.
Definition at line 109 of file TableView.java.
{
         Equality<Object> cmp = (Equality<Object>) this.comparator();
         for (int i = size() - 1; i >= 0; i--) {
             if (cmp.areEqual(o, get(i))) return i;
         }
         return -1;
     }
References javolution.util.function.Equality< T >.areEqual(), javolution.util.internal.collection.CollectionView< E >.comparator(), and javolution.util.internal.table.TableView< E >.size().
Referenced by javolution.util.internal.table.TableView< E >.removeLastOccurrence().
listIterator() [1/2]
final ListIterator<E> javolution.util.internal.table.TableView< E >.listIterator () inherited
Definition at line 118 of file TableView.java.
{
         return listIterator(0);
     }
Referenced by javolution.util.internal.table.TableView< E >.iterator().
listIterator() [2/2]
ListIterator<E> javolution.util.internal.table.TableView< E >.listIterator (int index) inherited
Definition at line 123 of file TableView.java.
{
         return new TableIteratorImpl<E>(this, index);
     }
mapped()
public<R> FastCollection<R> javolution.util.FastCollection< E >.mapped (Function<? super E, ? extends R > function) package inherited
Returns a view exposing elements through the specified mapping function. The returned view does not allow new elements to be added.
Definition at line 258 of file FastCollection.java.
{
         return new MappedCollectionImpl<E, R>(service(), function);
     }
Referenced by javolution.xml.internal.stream.EntitiesImpl.setEntitiesMapping().
max()
E javolution.util.FastCollection< E >.max () inherited
Returns the largest element of this collection using this collection comparator (convenience method). Returns
null
if this collection is empty.
Returns
reduce(Reducers.max(comparator()))
See also
Reducers::max
Definition at line 541 of file FastCollection.java.
                    {
         return reduce(Reducers.max(comparator()));
     }
References javolution.util.function.Reducers.max().
min()
E javolution.util.FastCollection< E >.min () inherited
Returns the smallest element of this collection using this collection comparator (convenience method). Returns
null
if this collection is empty.
Returns
reduce(Reducers.min(comparator()))
See also
Reducers::min
Definition at line 528 of file FastCollection.java.
                    {
         return reduce(Reducers.min(comparator()));
     }
References javolution.util.function.Reducers.min().
offer()
final boolean javolution.util.internal.table.TableView< E >.offer (E e) inherited
Definition at line 128 of file TableView.java.
{
         return offerLast(e);
     }
References javolution.util.internal.table.TableView< E >.offerLast().
offerFirst()
final boolean javolution.util.internal.table.TableView< E >.offerFirst (E e) inherited
Definition at line 133 of file TableView.java.
{
         addFirst(e);
         return true;
     }
References javolution.util.internal.table.TableView< E >.addFirst().
offerLast()
final boolean javolution.util.internal.table.TableView< E >.offerLast (E e) inherited
Definition at line 139 of file TableView.java.
{
         addLast(e);
         return true;
     }
References javolution.util.internal.table.TableView< E >.addLast().
Referenced by javolution.util.internal.table.TableView< E >.offer().
parallel()
FastCollection<E> javolution.util.FastCollection< E >.parallel () inherited
Returns a parallel collection. Parallel collections affect only closure-based operations, all others operations behaving the same. Parallel actions are performed concurrently using Javolution ConcurrentContext. The number of parallel views is derived from the context concurrency (
number of parallel views = concurrency + 1
). Parallel views do not require this collection to be thread-safe (internal synchronization).
See also
#perform(Consumer)
#update(Consumer)
#forEach(Consumer)
#removeIf(Predicate)
#reduce(Reducer)
Definition at line 222 of file FastCollection.java.
{
         return new ParallelCollectionImpl<E>(service());
     }
peek()
final E javolution.util.internal.table.TableView< E >.peek () inherited
Definition at line 145 of file TableView.java.
{
         return peekFirst();
     }
References javolution.util.internal.table.TableView< E >.peekFirst().
peekFirst()
E javolution.util.internal.table.TableView< E >.peekFirst () inherited
Definition at line 150 of file TableView.java.
{
         return (size() == 0) ? null : getFirst();
     }
References javolution.util.internal.table.TableView< E >.getFirst(), and javolution.util.internal.table.TableView< E >.size().
Referenced by javolution.util.internal.table.TableView< E >.peek().
peekLast()
E javolution.util.internal.table.TableView< E >.peekLast () inherited
Definition at line 155 of file TableView.java.
{
         return (size() == 0) ? null : getLast();
     }
References javolution.util.internal.table.TableView< E >.getLast(), and javolution.util.internal.table.TableView< E >.size().
perform() [1/3]
void javolution.util.internal.collection.CollectionView< E >.perform (Consumer< CollectionService< E >> action, CollectionService< E > view) inherited
Reimplemented in javolution.util.internal.collection.ParallelCollectionImpl< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Definition at line 163 of file CollectionView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
perform() [2/3]
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
perform() [3/3]
void javolution.util.FastCollection< E >.perform (Consumer<? extends Collection< E >> action) inherited
Executes the specified read-only action on this collection. That logic may be performed concurrently on sub-collections if this collection is parallel.
Parameters
action the read-only action.
Exceptions
UnsupportedOperationException if the action tries to update this collection and this collection is thread-safe.
ClassCastException if the action type is not compatible with this collection (e.g. action on set and this is a list).
See also
#update(Consumer)
Definition at line 315 of file FastCollection.java.
{
         service().perform((Consumer<CollectionService<E>>) action, service());
     }
poll()
final E javolution.util.internal.table.TableView< E >.poll () inherited
Definition at line 160 of file TableView.java.
{
         return pollFirst();
     }
References javolution.util.internal.table.TableView< E >.pollFirst().
pollFirst()
E javolution.util.internal.table.TableView< E >.pollFirst () inherited
Definition at line 165 of file TableView.java.
{
         return (size() == 0) ? null : removeFirst();
     }
References javolution.util.internal.table.TableView< E >.removeFirst(), and javolution.util.internal.table.TableView< E >.size().
Referenced by javolution.util.internal.table.TableView< E >.poll().
pollLast()
E javolution.util.internal.table.TableView< E >.pollLast () inherited
Definition at line 170 of file TableView.java.
{
         return (size() == 0) ? null : removeLast();
     }
References javolution.util.internal.table.TableView< E >.removeLast(), and javolution.util.internal.table.TableView< E >.size().
pop()
final E javolution.util.internal.table.TableView< E >.pop () inherited
Definition at line 175 of file TableView.java.
{
         return removeFirst();
     }
References javolution.util.internal.table.TableView< E >.removeFirst().
positionOf() [1/2]
int javolution.util.internal.table.sorted.FastSortedTableImpl< E >.positionOf (E element)
Returns what would be the index of the specified element if it were to be added or the index of the specified element if already present.
Implements javolution.util.service.SortedTableService< E >.
Definition at line 50 of file FastSortedTableImpl.java.
{
         return positionOf(element, 0, size());
     }
Referenced by javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.add(), javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.addIfAbsent(), javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.indexOf(), javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.positionOf(), and javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >.put().
positionOf() [2/2]
int javolution.util.internal.table.sorted.FastSortedTableImpl< E >.positionOf (E element, int start, int length) private
Definition at line 59 of file FastSortedTableImpl.java.
{
         if (length == 0) return start;
         int half = length >> 1;
         return (comparator().compare(element, get(start + half)) <= 0) ? positionOf(
                 element, start, half) : positionOf(element, start + half + 1,
                 length - half - 1);
     }
push()
final void javolution.util.internal.table.TableView< E >.push (E e) inherited
Definition at line 180 of file TableView.java.
{
         addFirst(e);
     }
References javolution.util.internal.table.TableView< E >.addFirst().
readObject()
void javolution.util.internal.table.FastTableImpl< E >.readObject (java.io.ObjectInputStream s) throws java.io.IOException, ClassNotFoundException private inherited
For serialization support
Definition at line 188 of file FastTableImpl.java.
{
         s.defaultReadObject(); // Deserialize comparator.
         int n = s.readInt();
         for (int i = 0; i < n; i++)
             addLast((E) s.readObject());
     }
References javolution.util.internal.table.FastTableImpl< E >.addLast().
reduce()
E javolution.util.FastCollection< E >.reduce (Reducer< E > reducer) inherited
Performs a reduction of the elements of this collection using the specified reducer. This may not involve iterating over all the collection elements, for example the reducers: Reducers#any, Reducers#and and Reducers#or may stop iterating early. Reduction is performed concurrently if this collection is parallel.
Parameters
reducer the collection reducer.
Returns
the reduction result.
Definition at line 396 of file FastCollection.java.
{
         perform(reducer);
         return reducer.get();
     }
remove() [1/3]
final E javolution.util.internal.table.TableView< E >.remove () inherited
Definition at line 185 of file TableView.java.
{
         return removeFirst();
     }
References javolution.util.internal.table.TableView< E >.removeFirst().
remove() [2/3]
E javolution.util.internal.table.FastTableImpl< E >.remove (int index) inherited
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 139 of file FastTableImpl.java.
{
         if ((index < 0) || (index >= size)) indexError(index);
         E removed = (E) fractal.get(index);
         if (index >= (size >> 1)) {
             fractal.shiftLeft(null, size - 1, size - index - 1);
         } else {
             fractal.shiftRight(null, 0, index);
             fractal.offset++;
         }
         size--;
         return removed;
     }
References javolution.util.internal.table.FastTableImpl< E >.fractal, javolution.util.internal.table.FractalTableImpl.get(), javolution.util.internal.table.TableView< E >.indexError(), javolution.util.internal.table.FractalTableImpl.offset, javolution.util.internal.table.FractalTableImpl.shiftLeft(), javolution.util.internal.table.FractalTableImpl.shiftRight(), and javolution.util.internal.table.FastTableImpl< E >.size.
Referenced by javolution.util.internal.table.FastTableImpl< E >.IteratorImpl.remove().
remove() [3/3]
final boolean javolution.util.internal.table.TableView< E >.remove (Object searched) inherited
Removes the specified element from this collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 193 of file TableView.java.
{
         int i = indexOf(o);
         if (i < 0) return false;
         remove(i);
         return true;
     }
References javolution.util.internal.table.TableView< E >.indexOf().
removeAll()
boolean javolution.util.internal.collection.CollectionView< E >.removeAll (Collection<?> that) inherited
Removes all the specified element from this collection.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 186 of file CollectionView.java.
{
         boolean changed = false;
         Iterator<? extends E> it = iterator();
         while (it.hasNext()) {
             if (c.contains(it.next())) {
                 it.remove();
                 changed = true;
             }
         }
         return changed;
     }
removeFirst()
E javolution.util.internal.table.FastTableImpl< E >.removeFirst () inherited
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 154 of file FastTableImpl.java.
{
         if (size == 0) emptyError();
         E first = (E) fractal.set(0, null);
         fractal.offset++;
         size--;
         return first;
     }
References javolution.util.internal.table.TableView< E >.emptyError(), javolution.util.internal.table.FastTableImpl< E >.fractal, javolution.util.internal.table.FractalTableImpl.offset, javolution.util.internal.table.FractalTableImpl.set(), and javolution.util.internal.table.FastTableImpl< E >.size.
removeFirstOccurrence()
boolean javolution.util.internal.table.TableView< E >.removeFirstOccurrence (Object o) inherited
Definition at line 207 of file TableView.java.
{
         int i = indexOf(o);
         if (i < 0) return false;
         remove(i);
         return true;
     }
References javolution.util.internal.table.TableView< E >.indexOf().
removeIf()
boolean javolution.util.FastCollection< E >.removeIf (final Predicate<? super E > filter) inherited
Removes from this collection all the elements matching the specified functional predicate (convenience method). Removals are performed concurrently if this collection is parallel and atomically if this collection is atomic.
Parameters
filter a predicate returning
true
for elements to be removed.
Returns
true
if at least one element has been removed;
false
otherwise.
Definition at line 368 of file FastCollection.java.
{
         final boolean[] removed = new boolean[1];
         update(new Consumer<Collection<E>>() {
             public void accept(Collection<E> view) {
                 Iterator<E> it = view.iterator();
                 while (it.hasNext()) {
                     if (filter.test(it.next())) {
                         it.remove(); // Ok mutable iteration.
                         removed[0] = true;
                     }
                 }
             }
         });
         return removed[0];
     }
removeLast()
E javolution.util.internal.table.FastTableImpl< E >.removeLast () inherited
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 164 of file FastTableImpl.java.
{
         if (size == 0) emptyError();
         E last = (E) fractal.set(--size, null);
         return last;
     }
References javolution.util.internal.table.TableView< E >.emptyError(), javolution.util.internal.table.FastTableImpl< E >.fractal, javolution.util.internal.table.FractalTableImpl.set(), and javolution.util.internal.table.FastTableImpl< E >.size.
removeLastOccurrence()
boolean javolution.util.internal.table.TableView< E >.removeLastOccurrence (Object o) inherited
Definition at line 221 of file TableView.java.
{
         int i = lastIndexOf(o);
         if (i < 0) return false;
         remove(i);
         return true;
     }
References javolution.util.internal.table.TableView< E >.lastIndexOf().
retainAll()
boolean javolution.util.internal.collection.CollectionView< E >.retainAll (Collection<?> that) inherited
Removes all the elements except those in the specified collection.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 199 of file CollectionView.java.
{
         boolean changed = false;
         Iterator<? extends E> it = iterator();
         while (it.hasNext()) {
             if (!c.contains(it.next())) {
                 it.remove();
                 changed = true;
             }
         }
         return changed;
     }
reversed()
FastCollection<E> javolution.util.FastCollection< E >.reversed () inherited
Returns a view exposing elements in reverse iterative order.
Reimplemented in javolution.util.FastTable< E >.
Definition at line 282 of file FastCollection.java.
{
         return new ReversedCollectionImpl<E>(service());
     }
sequential()
FastCollection<E> javolution.util.FastCollection< E >.sequential () inherited
Returns a sequential view of this collection. Using this view, all closure-based iterations are performed sequentially.
Definition at line 230 of file FastCollection.java.
{
         return new SequentialCollectionImpl<E>(service());
     }
service()
CollectionService<E> javolution.util.internal.collection.CollectionView< E >.service () protected inherited
Returns the service implementation of this collection (for sub-classes).
Reimplemented from javolution.util.FastCollection< E >.
Definition at line 274 of file CollectionView.java.
{
         return this;
     }
serviceOf()
static <E> CollectionService<E> javolution.util.FastCollection< E >.serviceOf (FastCollection< E > collection) static protected inherited
Returns the service implementation of any fast collection (for sub-classes).
Definition at line 647 of file FastCollection.java.
{
         return collection.service();
     }
References javolution.util.FastCollection< E >.service().
set()
E javolution.util.internal.table.FastTableImpl< E >.set (int index, E element) inherited
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 172 of file FastTableImpl.java.
{
         if ((index < 0) && (index >= size)) indexError(index);
         return (E) fractal.set(index, element);
     }
References javolution.util.internal.table.TableView< E >.element(), javolution.util.internal.table.FastTableImpl< E >.fractal, javolution.util.internal.table.TableView< E >.indexError(), javolution.util.internal.table.FractalTableImpl.set(), and javolution.util.internal.table.FastTableImpl< E >.size.
shared()
FastCollection<E> javolution.util.FastCollection< E >.shared () inherited
Returns a thread-safe view over this collection. The shared view allows for concurrent read as long as there is no writer. The default implementation is based on readers-writers locks giving priority to writers. Iterators on shared collections are thread-safe (no ConcurrentModificationException possible).
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSet< E >, javolution.util.FastSortedTable< E >, and javolution.util.FastSortedSet< E >.
Definition at line 201 of file FastCollection.java.
{
         return new SharedCollectionImpl<E>(service());
     }
size()
int javolution.util.internal.table.FastTableImpl< E >.size () inherited
Returns the size of this collection.
Reimplemented from javolution.util.internal.table.TableView< E >.
Definition at line 178 of file FastTableImpl.java.
                       {
         return size;
     }
References javolution.util.internal.table.FastTableImpl< E >.size.
sorted() [1/2]
FastCollection<E> javolution.util.FastCollection< E >.sorted () inherited
Returns a view exposing elements sorted according to the collection order.
Definition at line 267 of file FastCollection.java.
{
         return new SortedCollectionImpl<E>(service(), comparator());
     }
Referenced by javolution.util.internal.collection.SortedCollectionImpl< E >.IteratorImpl.IteratorImpl().
sorted() [2/2]
FastCollection<E> javolution.util.FastCollection< E >.sorted (Comparator<? super E > cmp) inherited
Returns a view exposing elements sorted according to the specified comparator.
Definition at line 275 of file FastCollection.java.
{
         return new SortedCollectionImpl<E>(service(), cmp);
     }
split()
CollectionService<E> [] javolution.util.internal.table.TableView< E >.split (int n) inherited
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 235 of file TableView.java.
{
         return SubTableImpl.splitOf(this, n); // Sub-views over this.
     }
References javolution.util.internal.table.SubTableImpl< E >.splitOf().
subList()
TableService<E> javolution.util.internal.table.TableView< E >.subList (int fromIndex, int toIndex) inherited
Implements javolution.util.service.TableService< E >.
Definition at line 240 of file TableView.java.
{
         return new SubTableImpl<E>(this, fromIndex, toIndex);
     }
Referenced by javolution.util.internal.table.TableView< E >.addAll().
target()
TableService<E> javolution.util.internal.table.TableView< E >.target () protected inherited
Returns the actual target
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Reimplemented in javolution.util.internal.table.sorted.SortedTableView< E >, and javolution.util.internal.table.sorted.UnmodifiableSortedTableImpl< E >.
Definition at line 262 of file TableView.java.
{
         return (TableService<E>) super.target();
     }
Referenced by javolution.util.internal.table.ReversedTableImpl< E >.add(), javolution.util.internal.table.SubTableImpl< E >.add(), javolution.util.internal.table.ReversedTableImpl< E >.clear(), javolution.util.internal.table.SubTableImpl< E >.clear(), javolution.util.internal.table.ReversedTableImpl< E >.comparator(), javolution.util.internal.table.UnmodifiableTableImpl< E >.comparator(), javolution.util.internal.table.SubTableImpl< E >.comparator(), javolution.util.internal.table.ReversedTableImpl< E >.get(), javolution.util.internal.table.UnmodifiableTableImpl< E >.get(), javolution.util.internal.table.SubTableImpl< E >.get(), javolution.util.internal.table.ReversedTableImpl< E >.indexOf(), javolution.util.internal.table.UnmodifiableTableImpl< E >.indexOf(), javolution.util.internal.table.ReversedTableImpl< E >.lastIndexOf(), javolution.util.internal.table.UnmodifiableTableImpl< E >.lastIndexOf(), javolution.util.internal.table.ReversedTableImpl< E >.remove(), javolution.util.internal.table.SubTableImpl< E >.remove(), javolution.util.internal.table.ReversedTableImpl< E >.set(), javolution.util.internal.table.SubTableImpl< E >.set(), javolution.util.internal.table.ReversedTableImpl< E >.size(), javolution.util.internal.table.UnmodifiableTableImpl< E >.size(), javolution.util.internal.table.SubTableImpl< E >.SubTableImpl(), javolution.util.internal.table.TableView< E >.TableView(), and javolution.util.internal.table.UnmodifiableTableImpl< E >.UnmodifiableTableImpl().
threadSafe()
SortedTableService<E> javolution.util.internal.table.sorted.FastSortedTableImpl< E >.threadSafe ()
Returns a thread-safe version of this service (used during parallel updates).
Implements javolution.util.service.SortedTableService< E >.
Definition at line 55 of file FastSortedTableImpl.java.
{
         return new SharedSortedTableImpl<E>(this);
     }
toArray() [1/2]
Object [] javolution.util.internal.collection.CollectionView< E >.toArray () inherited
Returns an array holding this collection elements.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 243 of file CollectionView.java.
{
         return toArray(new Object[size()]);
     }
Referenced by javolution.util.internal.collection.CollectionView< R >.toArray().
toArray() [2/2]
public<T> T [] javolution.util.internal.collection.CollectionView< E >.toArray (T[] array) package inherited
Returns the specified array holding this collection elements if enough capacity.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 249 of file CollectionView.java.
{
         final int size = size();
         final T[] result = (size <= a.length) ? a
                 : (T[]) java.lang.reflect.Array.newInstance(a.getClass()
                         .getComponentType(), size);
         int i = 0;
         Iterator<E> it = iterator();
         while (it.hasNext()) {
             result[i++] = (T) it.next();
         }
         if (result.length > size) {
             result[size] = null; // As per Collection contract.
         }
         return result;
     }
toImmutable()
public<T extends Collection<E> > Immutable<T> javolution.util.FastCollection< E >.toImmutable () package inherited
Returns an immutable reference over this collection. The immutable value is an unmodifiable view of this collection. The caller must guarantees that the original collection is never going to be updated (e.g. there is no reference left of the original collection).
Definition at line 585 of file FastCollection.java.
{
         return new Immutable<T>() {
             @SuppressWarnings("unchecked")
             final T value = (T) unmodifiable();
             @Override
             public T value() {
                 return value;
             }
         };
     }
toString()
String javolution.util.FastCollection< E >.toString () inherited
Returns the string representation of this collection using its default format.
Definition at line 634 of file FastCollection.java.
{
         return TextContext.getFormat(FastCollection.class).format(this);
     }
References javolution.text.TextContext.getFormat().
unmodifiable()
FastCollection<E> javolution.util.FastCollection< E >.unmodifiable () inherited
Returns an unmodifiable view over this collection. Any attempt to modify the collection through this view will result into a java.lang.UnsupportedOperationException being raised.
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSet< E >, javolution.util.FastSortedTable< E >, and javolution.util.FastSortedSet< E >.
Definition at line 239 of file FastCollection.java.
{
         return new UnmodifiableCollectionImpl<E>(service());
     }
update() [1/3]
void javolution.util.internal.collection.CollectionView< E >.update (Consumer< CollectionService< E >> action, CollectionService< E > view) inherited
Reimplemented in javolution.util.internal.collection.ParallelCollectionImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Definition at line 266 of file CollectionView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
update() [2/3]
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
update() [3/3]
void javolution.util.FastCollection< E >.update (Consumer<? extends Collection< E >> action) inherited
Executes the specified update action on this collection. That logic may be performed concurrently on sub-collections if this collection is parallel. For atomic collections the update is atomic (either concurrent readers see the full result of the action or nothing).
Parameters
action the update action.
Exceptions
ClassCastException if the action type is not compatible with this collection (e.g. action on set and this is a list).
See also
#perform(Consumer)
Definition at line 334 of file FastCollection.java.
{
         service().update((Consumer<CollectionService<E>>) action, service());
     }
Referenced by javolution.util.FastTable< javolution.xml.internal.stream.XMLStreamReaderImpl >.sort().
upsize()
void javolution.util.internal.table.FastTableImpl< E >.upsize () private inherited
Definition at line 196 of file FastTableImpl.java.
{
         fractal = (fractal == null) ? new FractalTableImpl() : fractal.upsize();
         capacity = fractal.capacity();
     }
References javolution.util.internal.table.FastTableImpl< E >.capacity, javolution.util.internal.table.FractalTableImpl.capacity(), javolution.util.internal.table.FastTableImpl< E >.fractal, and javolution.util.internal.table.FractalTableImpl.upsize().
Referenced by javolution.util.internal.table.FastTableImpl< E >.checkUpsize().
writeObject()
void javolution.util.internal.table.FastTableImpl< E >.writeObject (java.io.ObjectOutputStream s) throws java.io.IOException private inherited
For serialization support
Definition at line 202 of file FastTableImpl.java.
{
         s.defaultWriteObject(); // Serialize comparator.
         s.writeInt(size);
         for (int i = 0; i < size; i++)
             s.writeObject(fractal.get(i));
     }
References javolution.util.internal.table.FastTableImpl< E >.fractal, javolution.util.internal.table.FractalTableImpl.get(), and javolution.util.internal.table.FastTableImpl< E >.size.
Member Data Documentation
capacity
transient int javolution.util.internal.table.FastTableImpl< E >.capacity private inherited
Definition at line 51 of file FastTableImpl.java.
Referenced by javolution.util.internal.table.FastTableImpl< E >.checkUpsize(), javolution.util.internal.table.FastTableImpl< E >.clear(), and javolution.util.internal.table.FastTableImpl< E >.upsize().
comparator
final Equality<? super E> javolution.util.internal.table.FastTableImpl< E >.comparator private inherited
Definition at line 52 of file FastTableImpl.java.
Referenced by javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.addIfAbsent(), javolution.util.internal.table.FastTableImpl< E >.clone(), javolution.util.internal.table.FastTableImpl< E >.comparator(), javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.FastSortedTableImpl(), javolution.util.internal.table.FastTableImpl< E >.FastTableImpl(), javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.indexOf(), and javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.positionOf().
fractal
transient FractalTableImpl javolution.util.internal.table.FastTableImpl< E >.fractal private inherited
Definition at line 53 of file FastTableImpl.java.
Referenced by javolution.util.internal.table.FastTableImpl< E >.add(), javolution.util.internal.table.FastTableImpl< E >.addFirst(), javolution.util.internal.table.FastTableImpl< E >.addLast(), javolution.util.internal.table.FastTableImpl< E >.clear(), javolution.util.internal.table.FastTableImpl< E >.get(), javolution.util.internal.table.FastTableImpl< E >.IteratorImpl.next(), javolution.util.internal.table.FastTableImpl< E >.remove(), javolution.util.internal.table.FastTableImpl< E >.removeFirst(), javolution.util.internal.table.FastTableImpl< E >.removeLast(), javolution.util.internal.table.FastTableImpl< E >.set(), javolution.util.internal.table.FastTableImpl< E >.upsize(), and javolution.util.internal.table.FastTableImpl< E >.writeObject().
serialVersionUID
final long javolution.util.internal.table.sorted.FastSortedTableImpl< E >.serialVersionUID = 0x600L static private
Definition at line 21 of file FastSortedTableImpl.java.
size
transient int javolution.util.internal.table.FastTableImpl< E >.size private inherited
Definition at line 54 of file FastTableImpl.java.
Referenced by javolution.util.internal.table.FastTableImpl< E >.add(), javolution.util.internal.table.FastTableImpl< E >.addFirst(), javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.addIfAbsent(), javolution.util.internal.table.FastTableImpl< E >.addLast(), javolution.util.internal.table.FastTableImpl< E >.checkUpsize(), javolution.util.internal.table.FastTableImpl< E >.clear(), javolution.util.internal.table.FastTableImpl< E >.get(), javolution.util.internal.table.FastTableImpl< E >.getFirst(), javolution.util.internal.table.FastTableImpl< E >.getLast(), javolution.util.internal.table.FastTableImpl< E >.IteratorImpl.hasNext(), javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.indexOf(), javolution.util.internal.table.FastTableImpl< E >.IteratorImpl.next(), javolution.util.internal.table.sorted.FastSortedTableImpl< Entry< K, V > >.positionOf(), javolution.util.internal.table.FastTableImpl< E >.remove(), javolution.util.internal.table.FastTableImpl< E >.removeFirst(), javolution.util.internal.table.FastTableImpl< E >.removeLast(), javolution.util.internal.table.FastTableImpl< E >.set(), javolution.util.internal.table.FastTableImpl< E >.size(), and javolution.util.internal.table.FastTableImpl< E >.writeObject().
The documentation for this class was generated from the following file:
FastSortedTableImpl.java