Javolution 6.0.0 java: javolution.util.function.Consumer< T > Interface Template Reference
javolution.util.function.Consumer< T > Interface Template Reference
Public Member Functions
void accept (T param)
Detailed Description
A special type of function which does not return anything.
Note: In future version this interface may derive from
Function<P, Void>
.
Parameters
<T> The type of input parameter to accept.
Author
Jean-Marie Dautelle
Version
6.0, July 21, 2013
Definition at line 22 of file Consumer.java.
Member Function Documentation
accept()
void javolution.util.function.Consumer< T >.accept (T param)
Accepts an input value.
Referenced by javolution.util.FastCollection< E >.forEach(), javolution.util.internal.map.MapView< K, V >.EntrySet.perform(), and javolution.util.internal.map.MapView< K, V >.EntrySet.update().
The documentation for this interface was generated from the following file:
Consumer.java