Javolution 6.0.0 java: javolution.xml.XMLObjectWriter Class Reference
javolution.xml.XMLObjectWriter Class Reference
Public Member Functions
XMLObjectWriter ()
XMLStreamWriter getStreamWriter ()
XMLObjectWriter setOutput (OutputStream out) throws XMLStreamException
XMLObjectWriter setOutput (OutputStream out, String encoding) throws XMLStreamException
XMLObjectWriter setOutput (Writer out) throws XMLStreamException
XMLObjectWriter setBinding (XMLBinding binding)
XMLObjectWriter setIndentation (String indentation)
XMLObjectWriter setReferenceResolver (XMLReferenceResolver referenceResolver)
void write (Object obj) throws XMLStreamException
void write (Object obj, String name) throws XMLStreamException
void write (Object obj, String localName, String uri) throws XMLStreamException
void flush () throws XMLStreamException
void close () throws XMLStreamException
void reset ()
Static Public Member Functions
static XMLObjectWriter newInstance (OutputStream out) throws XMLStreamException
static XMLObjectWriter newInstance (OutputStream out, String encoding) throws XMLStreamException
static XMLObjectWriter newInstance (Writer out) throws XMLStreamException
Package Functions
public< T > void write (T obj, String name, Class< T > cls) throws XMLStreamException
public< T > void write (T obj, String localName, String uri, Class< T > cls) throws XMLStreamException
Private Attributes
final XMLFormat.OutputElement _xml = new XMLFormat.OutputElement()
Writer _writer
OutputStream _outputStream
Detailed Description
This class takes an object and formats it to XML; the resulting XML can be deserialized using a XMLObjectReader.
When an object is formatted, the XMLFormat of the object's class as identified by the XMLBinding is used to write its XML representation.
Multiple objects can be written to the same XML output. For example:[code] XMLObjectWriter writer = XMLObjectWriter.newInstance(outputStream); while (true)) { Message message = ... writer.write(message, "Message", Message.class); } writer.close(); // The underlying stream is closed. [/code]
Author
Jean-Marie Dautelle
Version
4.0, September 4, 2006
Definition at line 40 of file XMLObjectWriter.java.
Constructor & Destructor Documentation
XMLObjectWriter()
javolution.xml.XMLObjectWriter.XMLObjectWriter ()
Default constructor.
Definition at line 60 of file XMLObjectWriter.java.
 {}
Referenced by javolution.xml.XMLObjectWriter.newInstance().
Member Function Documentation
close()
void javolution.xml.XMLObjectWriter.close () throws XMLStreamException
Ends document writting, closes this writer and its underlying output then reset this Writer for potential reuse.
Definition at line 284 of file XMLObjectWriter.java.
{
         try {
             if (_outputStream != null) {
                 _xml._writer.writeEndDocument();
                 _xml._writer.close();
                 _outputStream.close();
                 reset();
             } else if (_writer != null) {
                 _xml._writer.writeEndDocument();
                 _xml._writer.close();
                 _writer.close();
                 reset();
             }
         } catch (IOException e) {
             throw new XMLStreamException(e);
         }
     }
References javolution.xml.XMLObjectWriter._outputStream, javolution.xml.XMLObjectWriter._writer, javolution.xml.XMLObjectWriter._xml, and javolution.xml.XMLObjectWriter.reset().
Referenced by javolution.xml.ws.WebServiceClient.invoke().
flush()
void javolution.xml.XMLObjectWriter.flush () throws XMLStreamException
Flushes the output stream of this writer (automatically done when closing).
Definition at line 276 of file XMLObjectWriter.java.
{
         _xml._writer.flush();
     }
References javolution.xml.XMLObjectWriter._xml.
getStreamWriter()
XMLStreamWriter javolution.xml.XMLObjectWriter.getStreamWriter ()
Returns the stream writer used by this object writer (it can be used to write prolog, write namespaces, etc). The stream writer is setup to automatically repair namespaces and to automatically output empty elements when a start element is immediately followed by matching end element.
Returns
the stream writer.
Definition at line 111 of file XMLObjectWriter.java.
{
         return _xml._writer;
     }
References javolution.xml.XMLObjectWriter._xml.
Referenced by javolution.xml.ws.WebServiceClient.invoke().
newInstance() [1/3]
static XMLObjectWriter javolution.xml.XMLObjectWriter.newInstance (OutputStream out) throws XMLStreamException static
Returns a XML object writer (potentially recycled) having the specified output stream as output.
Parameters
out the output stream.
Definition at line 68 of file XMLObjectWriter.java.
{
         XMLObjectWriter writer = new XMLObjectWriter();
         writer.setOutput(out);
         return writer;
     }
References javolution.xml.XMLObjectWriter.setOutput(), and javolution.xml.XMLObjectWriter.XMLObjectWriter().
newInstance() [2/3]
static XMLObjectWriter javolution.xml.XMLObjectWriter.newInstance (OutputStream out, String encoding) throws XMLStreamException static
Returns a XML object writer (potentially recycled) having the specified output stream/encoding as output.
Parameters
out the output stream.
encoding the output stream encoding.
Definition at line 82 of file XMLObjectWriter.java.
{
         XMLObjectWriter writer = new XMLObjectWriter();
         writer.setOutput(out, encoding);
         return writer;
     }
References javolution.xml.XMLObjectWriter.setOutput(), and javolution.xml.XMLObjectWriter.XMLObjectWriter().
newInstance() [3/3]
static XMLObjectWriter javolution.xml.XMLObjectWriter.newInstance (Writer out) throws XMLStreamException static
Returns a XML object writer (potentially recycled) having the specified writer as output.
Parameters
out the writer output.
Definition at line 95 of file XMLObjectWriter.java.
{
         XMLObjectWriter writer = new XMLObjectWriter();
         writer.setOutput(out);
         return writer;
     }
References javolution.xml.XMLObjectWriter.setOutput(), and javolution.xml.XMLObjectWriter.XMLObjectWriter().
reset()
void javolution.xml.XMLObjectWriter.reset ()
Resets this object writer for reuse.
Definition at line 306 of file XMLObjectWriter.java.
{
         _xml.reset();
         _outputStream = null;
         _writer = null;
     }
References javolution.xml.XMLObjectWriter._outputStream, javolution.xml.XMLObjectWriter._writer, and javolution.xml.XMLObjectWriter._xml.
Referenced by javolution.xml.XMLObjectWriter.close(), and javolution.xml.ws.WebServiceClient.invoke().
setBinding()
XMLObjectWriter javolution.xml.XMLObjectWriter.setBinding (XMLBinding binding)
Sets the XML binding to use with this object writer.
Parameters
binding the XML binding to use.
Returns
this
Definition at line 172 of file XMLObjectWriter.java.
{
         _xml.setBinding(binding);
         return this;
     }
References javolution.xml.XMLObjectWriter._xml.
setIndentation()
XMLObjectWriter javolution.xml.XMLObjectWriter.setIndentation (String indentation)
Sets the indentation to be used by this writer (no indentation by default).
Parameters
indentation the indentation string.
Returns
this
Definition at line 184 of file XMLObjectWriter.java.
{
         _xml._writer.setIndentation(indentation);
         return this;
     }
References javolution.xml.XMLObjectWriter._xml.
setOutput() [1/3]
XMLObjectWriter javolution.xml.XMLObjectWriter.setOutput (OutputStream out) throws XMLStreamException
Sets the output stream for this XML object writer.
Parameters
out the output stream destination.
Returns
this
See also
XMLStreamWriterImpl::setOutput(OutputStream)
Definition at line 122 of file XMLObjectWriter.java.
{
         if ((_outputStream != null) || (_writer != null))
             throw new IllegalStateException("Writer not closed or reset");
         _xml._writer.setOutput(out);
         _outputStream = out;
         _xml._writer.writeStartDocument();
         return this;
     }
References javolution.xml.XMLObjectWriter._outputStream, javolution.xml.XMLObjectWriter._writer, and javolution.xml.XMLObjectWriter._xml.
Referenced by javolution.xml.ws.WebServiceClient.invoke(), and javolution.xml.XMLObjectWriter.newInstance().
setOutput() [2/3]
XMLObjectWriter javolution.xml.XMLObjectWriter.setOutput (OutputStream out, String encoding) throws XMLStreamException
Sets the output stream and encoding for this XML object writer.
Parameters
out the output stream destination.
encoding the stream encoding.
Returns
this
See also
XMLStreamWriterImpl::setOutput(OutputStream, String)
Definition at line 140 of file XMLObjectWriter.java.
{
         if ((_outputStream != null) || (_writer != null))
             throw new IllegalStateException("Writer not closed or reset");
         _xml._writer.setOutput(out, encoding);
         _outputStream = out;
         _xml._writer.writeStartDocument();
         return this;
     }
References javolution.xml.XMLObjectWriter._outputStream, javolution.xml.XMLObjectWriter._writer, and javolution.xml.XMLObjectWriter._xml.
setOutput() [3/3]
XMLObjectWriter javolution.xml.XMLObjectWriter.setOutput (Writer out) throws XMLStreamException
Sets the output writer for this XML object writer.
Parameters
out the writer destination.
Returns
this
See also
XMLStreamWriterImpl::setOutput(Writer)
Definition at line 157 of file XMLObjectWriter.java.
{
         if ((_outputStream != null) || (_writer != null))
             throw new IllegalStateException("Writer not closed or reset");
         _xml._writer.setOutput(out);
         _writer = out;
         _xml._writer.writeStartDocument();
         return this;
     }
References javolution.xml.XMLObjectWriter._outputStream, javolution.xml.XMLObjectWriter._writer, and javolution.xml.XMLObjectWriter._xml.
setReferenceResolver()
XMLObjectWriter javolution.xml.XMLObjectWriter.setReferenceResolver (XMLReferenceResolver referenceResolver)
Sets the XML reference resolver to use with this object writer (the same reference resolver can be used accross multiple writers).
Parameters
referenceResolver the XML reference resolver.
Returns
this
Definition at line 196 of file XMLObjectWriter.java.
{
         _xml.setReferenceResolver(referenceResolver);
         return this;
     }
References javolution.xml.XMLObjectWriter._xml.
write() [1/5]
void javolution.xml.XMLObjectWriter.write (Object obj) throws XMLStreamException
Writes the specified object as an anonymous nested element of unknown type. This result in the actual type of the object being identified by the element name.
Parameters
obj the object written as nested element or null.
See also
XMLFormat.OutputElement::add(Object)
Definition at line 210 of file XMLObjectWriter.java.
{
         _xml.add(obj);
     }
References javolution.xml.XMLObjectWriter._xml.
write() [2/5]
void javolution.xml.XMLObjectWriter.write (Object obj, String localName, String uri) throws XMLStreamException
Writes the specified object as a fully qualified nested element of unknown type (null objects are ignored). The nested XML element may contain a class attribute identifying the object type.
Parameters
obj the object added as nested element or null.
localName the local name of the nested element.
uri the namespace URI of the nested element.
See also
XMLFormat.OutputElement::add(Object, String, String)
Definition at line 238 of file XMLObjectWriter.java.
{
         _xml.add(obj, localName, uri);
     }
References javolution.xml.XMLObjectWriter._xml.
write() [3/5]
void javolution.xml.XMLObjectWriter.write (Object obj, String name) throws XMLStreamException
Writes the specified object as a named nested element of unknown type (null objects are ignored). The nested XML element may contain a class attribute identifying the object type.
Parameters
obj the object added as nested element or null.
name the name of the nested element.
See also
XMLFormat.OutputElement::add(Object, String)
Definition at line 223 of file XMLObjectWriter.java.
{
         _xml.add(obj, name);
     }
References javolution.xml.XMLObjectWriter._xml.
write() [4/5]
public<T> void javolution.xml.XMLObjectWriter.write (T obj, String localName, String uri, Class< T > cls) throws XMLStreamException package
Writes the specified object as a fully qualified nested element of actual type known (null objects are ignored).
Parameters
obj the object added as nested element or null.
localName the local name of the nested element.
uri the namespace URI of the nested element.
cls the class identifying the XML format to use.
See also
XMLFormat.OutputElement::add(Object, String, String, Class)
Definition at line 267 of file XMLObjectWriter.java.
{
         _xml.add(obj, localName, uri, cls);
     }
References javolution.xml.XMLObjectWriter._xml.
write() [5/5]
public<T> void javolution.xml.XMLObjectWriter.write (T obj, String name, Class< T > cls) throws XMLStreamException package
Writes the specified object as a named nested element of actual type known (null objects are ignored).
Parameters
obj the object added as nested element or null.
name the name of the nested element.
cls the non-abstract class identifying the XML format to use.
See also
XMLFormat.OutputElement::add(Object, String, Class)
Definition at line 252 of file XMLObjectWriter.java.
{
         _xml.add(obj, name, cls);
     }
References javolution.xml.XMLObjectWriter._xml.
Member Data Documentation
_outputStream
OutputStream javolution.xml.XMLObjectWriter._outputStream private
Holds input stream if any.
Definition at line 55 of file XMLObjectWriter.java.
Referenced by javolution.xml.XMLObjectWriter.close(), javolution.xml.XMLObjectWriter.reset(), and javolution.xml.XMLObjectWriter.setOutput().
_writer
Writer javolution.xml.XMLObjectWriter._writer private
Holds writer if any.
Definition at line 50 of file XMLObjectWriter.java.
Referenced by javolution.xml.XMLObjectWriter.close(), javolution.xml.XMLObjectWriter.reset(), and javolution.xml.XMLObjectWriter.setOutput().
_xml
final XMLFormat.OutputElement javolution.xml.XMLObjectWriter._xml = new XMLFormat.OutputElement() private
Hold the xml element used when formatting.
Definition at line 45 of file XMLObjectWriter.java.
Referenced by javolution.xml.XMLObjectWriter.close(), javolution.xml.XMLObjectWriter.flush(), javolution.xml.XMLObjectWriter.getStreamWriter(), javolution.xml.XMLObjectWriter.reset(), javolution.xml.XMLObjectWriter.setBinding(), javolution.xml.XMLObjectWriter.setIndentation(), javolution.xml.XMLObjectWriter.setOutput(), javolution.xml.XMLObjectWriter.setReferenceResolver(), and javolution.xml.XMLObjectWriter.write().
The documentation for this class was generated from the following file:
XMLObjectWriter.java