Javolution 6.0.0 java: javolution.util.internal.comparator.LexicalFastComparatorImpl Class Reference
javolution.util.internal.comparator.LexicalFastComparatorImpl Class Reference
Public Member Functions
int hashCodeOf (CharSequence csq)
int hashCodeOf (T object)
boolean areEqual (CharSequence csq1, CharSequence csq2)
boolean areEqual (T left, T right)
int compare (CharSequence left, CharSequence right)
int compare (T left, T right)
Static Private Attributes
static final long serialVersionUID = -1449702752185594025L
Detailed Description
The high-performance lexical comparator.
Definition at line 14 of file LexicalFastComparatorImpl.java.
Member Function Documentation
areEqual() [1/2]
boolean javolution.util.internal.comparator.LexicalComparatorImpl.areEqual (CharSequence csq1, CharSequence csq2) inherited
Definition at line 38 of file LexicalComparatorImpl.java.
{
         if (csq1 == csq2)
             return true;
         if ((csq1 == null) || (csq2 == null))
             return false;
         if (csq1 instanceof String) { // Optimization.
             if (csq2 instanceof String)
                 return csq1.equals(csq2);
             return ((String) csq1).contentEquals(csq2);
         } else if (csq2 instanceof String) { return ((String) csq2)
                 .contentEquals(csq1); }
         // None of the CharSequence is a String.
         int n = csq1.length();
         if (csq2.length() != n)
             return false;
         for (int i = 0; i < n;) {
             if (csq1.charAt(i) != csq2.charAt(i++))
                 return false;
         }
         return true;
     }
areEqual() [2/2]
boolean javolution.util.function.Equality< T >.areEqual (T left, T right) inherited
Indicates if the specified objects can be considered equal. This methods is equivalent to
(compare(o1, o2) == 0)
but usually faster.
Parameters
left the first object (or null).
right the second object (or null).
Returns
true if both objects are considered equal; false otherwise.
Referenced by javolution.util.internal.map.MapView< K, V >.EntryComparator.areEqual(), javolution.util.internal.collection.CollectionView< R >.contains(), javolution.util.internal.collection.CollectionView< R >.equals(), javolution.util.internal.table.TableView< E >.indexOf(), javolution.util.internal.table.TableView< E >.lastIndexOf(), javolution.util.internal.map.FastMapImpl< K, V >.remove(), javolution.util.internal.collection.CollectionView< R >.remove(), and javolution.util.internal.map.FastMapImpl< K, V >.replace().
compare() [1/2]
int javolution.util.internal.comparator.LexicalComparatorImpl.compare (CharSequence left, CharSequence right) inherited
Definition at line 62 of file LexicalComparatorImpl.java.
{
         if (left == null)
             return -1;
         if (right == null)
             return 1;
         if ((left instanceof String) && (right instanceof String)) // Optimization.
             return ((String) left).compareTo((String) right);
         int i = 0;
         int n = MathLib.min(left.length(), right.length());
         while (n-- != 0) {
             char c1 = left.charAt(i);
             char c2 = right.charAt(i++);
             if (c1 != c2)
                 return c1 - c2;
         }
         return left.length() - right.length();
     }
References javolution.lang.MathLib.min().
compare() [2/2]
int javolution.util.function.Equality< T >.compare (T left, T right) inherited
Compares the specified objects for order. Returns a negative integer, zero, or a positive integer as the first argument is less than, possibly equal to, or greater than the second. Implementation classes should ensure that comparisons with
null
is supported.
Parameters
left the first object.
right the second object.
Returns
a negative integer, zero, or a positive integer as the first argument is less than, possibly equal to, or greater than the second.
Referenced by javolution.util.internal.set.sorted.SubSortedSetImpl< E >.add(), javolution.util.internal.map.MapView< K, V >.EntryComparator.compare(), javolution.text.CharArray.compareTo(), javolution.text.Text.compareTo(), javolution.util.internal.set.sorted.SubSortedSetImpl< E >.contains(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.containsKey(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.get(), javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.hasNext(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.hasNext(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.put(), javolution.util.internal.set.sorted.SubSortedSetImpl< E >.remove(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.remove().
hashCodeOf() [1/2]
int javolution.util.internal.comparator.LexicalFastComparatorImpl.hashCodeOf (CharSequence csq)
Reimplemented from javolution.util.internal.comparator.LexicalComparatorImpl.
Definition at line 19 of file LexicalFastComparatorImpl.java.
{
         if (csq == null)
             return 0;
         int n = csq.length();
         if (n == 0)
             return 0;
         // Hash based on 5 characters only.
         return csq.charAt(0) + csq.charAt(n - 1) * 31 + csq.charAt(n >> 1)
                 * 1009 + csq.charAt(n >> 2) * 27583
                 + csq.charAt(n - 1 - (n >> 2)) * 73408859;
     }
hashCodeOf() [2/2]
int javolution.util.function.Equality< T >.hashCodeOf (T object) inherited
Returns the hash code for the specified object (consistent with areEqual). Two objects considered equal have the same hash code. The hash code of null is always 0.
Parameters
object the object to return the hashcode for.
Returns
the hashcode for the specified object.
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.containsKey(), javolution.util.internal.map.FastMapImpl< K, V >.get(), javolution.util.internal.collection.CollectionView< R >.hashCode(), javolution.util.internal.map.MapView< K, V >.EntryComparator.hashCodeOf(), javolution.util.internal.map.FastMapImpl< K, V >.put(), javolution.util.internal.map.FastMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.FastMapImpl< K, V >.remove(), and javolution.util.internal.map.FastMapImpl< K, V >.replace().
Member Data Documentation
serialVersionUID
final long javolution.util.internal.comparator.LexicalFastComparatorImpl.serialVersionUID = -1449702752185594025L static private
Definition at line 16 of file LexicalFastComparatorImpl.java.
The documentation for this class was generated from the following file:
LexicalFastComparatorImpl.java