Javolution 6.0.0 java: javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl Class Reference
javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl Class Reference
Public Member Functions
boolean hasNext ()
Entry< K, V > next ()
void remove ()
Private Attributes
Entry< K, V > current
final Iterator< Entry< K, V > > targetIterator = targetView().iterator()
Detailed Description
Thread-Safe Iterator.
Definition at line 24 of file AtomicMapImpl.java.
Member Function Documentation
hasNext()
boolean javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.hasNext ()
Definition at line 29 of file AtomicMapImpl.java.
{
             return targetIterator.hasNext();
         }
References javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.targetIterator.
next()
Entry<K, V> javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.next ()
Definition at line 34 of file AtomicMapImpl.java.
{
             current = targetIterator.next();
             return current;
         }
References javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.current, and javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.targetIterator.
remove()
void javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.remove ()
Definition at line 40 of file AtomicMapImpl.java.
{
             if (current == null) throw new IllegalStateException();
             AtomicMapImpl.this.remove(current.getKey());
             current = null;
         }
References javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.current, and javolution.util.internal.map.AtomicMapImpl< K, V >.remove().
Member Data Documentation
current
Entry<K, V> javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.current private
Definition at line 25 of file AtomicMapImpl.java.
Referenced by javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.next(), and javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.remove().
targetIterator
final Iterator<Entry<K, V> > javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.targetIterator = targetView().iterator() private
Definition at line 26 of file AtomicMapImpl.java.
Referenced by javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.hasNext(), and javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.next().
The documentation for this class was generated from the following file:
AtomicMapImpl.java