Javolution 6.0.0 java: javolution.xml.XMLFormat< T >.Default Class Reference
javolution.xml.XMLFormat< T >.Default Class Reference
Public Member Functions
Default ()
boolean isReferenceable ()
Object newInstance (Class<?> cls, javolution.xml.XMLFormat.InputElement xml) throws XMLStreamException
void read (XMLFormat.InputElement xml, Object obj) throws XMLStreamException
void write (Object obj, XMLFormat.OutputElement xml) throws XMLStreamException
T newInstance (Class<? extends T > cls, InputElement xml) throws XMLStreamException
abstract void write (T obj, OutputElement xml) throws XMLStreamException
abstract void read (InputElement xml, T obj) throws XMLStreamException
Static Private Attributes
static final String NULL
Detailed Description
Returns the default XML format for any object having a plain text format; this XML representation consists of the plain text representation of the object as a "value" attribute.
Definition at line 986 of file XMLFormat.java.
Constructor & Destructor Documentation
Default()
javolution.xml.XMLFormat< T >.Default.Default ()
Default constructor.
Definition at line 991 of file XMLFormat.java.
 {}
Member Function Documentation
isReferenceable()
boolean javolution.xml.XMLFormat< T >.Default.isReferenceable ()
Definition at line 994 of file XMLFormat.java.
{
             return false; // Always by value (immutable).
         }
newInstance() [1/2]
T javolution.xml.XMLFormat< T >.newInstance (Class<? extends T > cls, InputElement xml) throws XMLStreamException inherited
Allocates a new object of the specified class from the specified XML input element. By default, this method returns an object created using the public no-arg constructor of the specified class. XML formats may override this method in order to use private/multi-arg constructors.
Parameters
cls the class of the object to return.
xml the XML input element.
Returns
the object corresponding to the specified XML element.
Definition at line 152 of file XMLFormat.java.
{
         try {
             return cls.newInstance();
         } catch (InstantiationException e) {
             throw new XMLStreamException(e);
         } catch (IllegalAccessException e) {
             throw new XMLStreamException(e);
         }
     }
newInstance() [2/2]
Object javolution.xml.XMLFormat< T >.Default.newInstance (Class<?> cls, javolution.xml.XMLFormat.InputElement xml) throws XMLStreamException
Definition at line 999 of file XMLFormat.java.
{
             TextFormat<?> format = TextContext.getFormat(cls);
             if (format == null)
                 throw new XMLStreamException(
                         "No TextFormat defined to parse instances of " + cls);
             CharArray value = xml.getAttribute("value");
             if (value == null)
                 throw new XMLStreamException(
                         "Missing value attribute (to be able to parse the instance of "
                                 + cls + ")");
             return format.parse(value);
         }
References javolution.text.TextContext.getFormat(), and javolution.text.TextFormat< T >.parse().
read() [1/2]
abstract void javolution.xml.XMLFormat< T >.read (InputElement xml, T obj) throws XMLStreamException abstract inherited
Parses an XML input element into the specified object.
Parameters
xml the XML element to parse.
obj the object created through newInstance and to setup from the specified XML element.
read() [2/2]
void javolution.xml.XMLFormat< T >.Default.read (XMLFormat.InputElement xml, Object obj) throws XMLStreamException
Definition at line 1014 of file XMLFormat.java.
{
             // Do nothing.
         }
write() [1/2]
void javolution.xml.XMLFormat< T >.Default.write (Object obj, XMLFormat.OutputElement xml) throws XMLStreamException
Definition at line 1020 of file XMLFormat.java.
{
             TextBuilder tmp = new TextBuilder();
             TextFormat<?> tf = TextContext.getFormat(obj.getClass());
             ((TextFormat<Object>) tf).format(obj, tmp);
             xml.setAttribute("value", tmp);
         }
References javolution.text.TextContext.getFormat().
write() [2/2]
abstract void javolution.xml.XMLFormat< T >.write (T obj, OutputElement xml) throws XMLStreamException abstract inherited
Formats an object into the specified XML output element.
Parameters
obj the object to format.
xml the XMLElement destination.
Member Data Documentation
NULL
final String javolution.xml.XMLFormat< T >.NULL static private inherited
Holds null representation.
Definition at line 121 of file XMLFormat.java.
The documentation for this class was generated from the following file:
XMLFormat.java