Javolution 6.0.0 java: javolution.context.internal.SecurityContextImpl Class Reference
javolution.context.internal.SecurityContextImpl Class Reference
Classes
class Action
Public Member Functions
boolean isGranted (Permission<?> permission)
void grant (Permission<?> permission, Object certificate) throws SecurityException
void revoke (Permission<?> permission, Object certificate) throws SecurityException
final void grant (Permission<?> permission)
final void revoke (Permission<?> permission)
void exit ()
Static Public Member Functions
static SecurityContext enter ()
static< T extends AbstractContext > T enter (Class< T > custom)
static void check (Permission<?> permission)
static AbstractContext current ()
static void inherit (AbstractContext ctx)
Protected Member Functions
SecurityContext inner ()
AbstractContext enterInner ()
AbstractContext getOuter ()
Static Protected Member Functions
static< T extends AbstractContext > T current (Class< T > type)
Static Private Member Functions
static SecurityContext currentSecurityContext ()
Private Attributes
FastTable< Action > actions = new FastTable<Action>()
AbstractContext outer
Static Private Attributes
static final ThreadLocal< AbstractContext > CURRENT = new ThreadLocal<AbstractContext>()
Detailed Description
Holds the default implementation of SecurityContext.
Definition at line 17 of file SecurityContextImpl.java.
Member Function Documentation
check()
static void javolution.context.SecurityContext.check (Permission<?> permission) static inherited
Checks if the specified permission is granted.
Parameters
permission the permission to check.
Exceptions
SecurityException if the specified permission is not granted.
Definition at line 195 of file SecurityContext.java.
{
         if (!currentSecurityContext().isGranted(permission))
             throw new SecurityException(permission + " is not granted.");
     }
References javolution.context.SecurityContext.currentSecurityContext(), and javolution.context.SecurityContext.isGranted().
Referenced by javolution.context.AbstractContext.enter(), and javolution.lang.Configurable< javolution.context.LogContext.Level >.reconfigure().
current() [1/2]
static AbstractContext javolution.context.AbstractContext.current () static inherited
Returns the current context for the current thread or
null
if this thread has no context (default).
Definition at line 61 of file AbstractContext.java.
{
         return AbstractContext.CURRENT.get();
     }
References javolution.context.AbstractContext.CURRENT.
Referenced by javolution.context.LogContext.currentLogContext(), javolution.context.SecurityContext.currentSecurityContext(), javolution.text.TextContext.currentTextContext(), javolution.xml.XMLContext.currentXMLContext(), javolution.context.LocalContext.enter(), javolution.context.ConcurrentContext.enter(), and javolution.context.LocalContext.Parameter< T >.get().
current() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.current (Class< T > type) static protected inherited
Returns the current context of specified type or
null
if none.
Definition at line 69 of file AbstractContext.java.
{
         AbstractContext ctx = AbstractContext.CURRENT.get();
         while (ctx != null) {
             if (type.isInstance(ctx))
                 return (T) ctx;
             ctx = ctx.outer;
         }
         return null;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
currentSecurityContext()
static SecurityContext javolution.context.SecurityContext.currentSecurityContext () static private inherited
Returns the current security context.
Definition at line 250 of file SecurityContext.java.
{
         SecurityContext ctx = current(SecurityContext.class);
         if (ctx != null)
             return ctx;
         return OSGiServices.getSecurityContext();
     }
References javolution.context.AbstractContext.current(), and javolution.osgi.internal.OSGiServices.getSecurityContext().
Referenced by javolution.context.SecurityContext.check(), and javolution.context.SecurityContext.enter().
enter() [1/2]
static SecurityContext javolution.context.SecurityContext.enter () static inherited
Enters and returns a new security context instance.
Returns
the new security context implementation entered.
Definition at line 185 of file SecurityContext.java.
{
         return (SecurityContext) currentSecurityContext().enterInner();
     }
References javolution.context.SecurityContext.currentSecurityContext(), and javolution.context.AbstractContext.enterInner().
enter() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.enter (Class< T > custom) static inherited
Enters the scope of a custom context. This method raises a SecurityException if the permission to enter contexts of the specified class is not granted. For example, the following disallow entering any custom context. [code] SecurityContext ctx = SecurityContext.enter(); try { ctx.revoke(new SecurityContext.Permission(AbstractContext.class, "enter")); ... // Cannot enter any custom context. } finally { ctx.exit(); // Back to previous security settings. }[/code]
Parameters
custom the custom context to enter.
Exceptions
IllegalArgumentException if the specified class default constructor cannot be instantiated.
SecurityException if
SecurityContext.Permission(custom, "enter")
is not granted.
See also
SecurityContext.Permission
Definition at line 101 of file AbstractContext.java.
{
         SecurityContext.check(new Permission<T>(custom, "enter"));
         try {
             return (T) custom.newInstance().enterInner();
         } catch (InstantiationException e) {
             throw new IllegalArgumentException(
                     "Cannot instantiate instance of " + custom, e);
         } catch (IllegalAccessException e) {
             throw new IllegalArgumentException("Cannot access " + custom, e);
         }
     }
References javolution.context.SecurityContext.check().
enterInner()
AbstractContext javolution.context.AbstractContext.enterInner () protected inherited
Enters the scope of an inner context which becomes the current context; the previous current context becomes the outer of this context.
Returns
the inner context entered.
Definition at line 141 of file AbstractContext.java.
{
         AbstractContext inner = inner();
         inner.outer = AbstractContext.CURRENT.get();
         AbstractContext.CURRENT.set(inner);
         return inner;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
Referenced by javolution.xml.XMLContext.enter(), javolution.text.TextContext.enter(), javolution.context.LogContext.enter(), javolution.context.LocalContext.enter(), javolution.context.SecurityContext.enter(), and javolution.context.ConcurrentContext.enter().
exit()
void javolution.context.AbstractContext.exit () inherited
Exits the scope of this context; the outer of this context becomes
the current context.
Exceptions
IllegalStateException if this context is not the current context.
Reimplemented in javolution.context.ConcurrentContext, and javolution.context.internal.ConcurrentContextImpl.
Definition at line 155 of file AbstractContext.java.
{
         if (this != AbstractContext.CURRENT.get())
             throw new IllegalStateException(
                     "This context is not the current context");
         AbstractContext.CURRENT.set(outer);
         outer = null;
     }
References javolution.context.AbstractContext.CURRENT.
getOuter()
AbstractContext javolution.context.AbstractContext.getOuter () protected inherited
Returns the outer context of this context or
null
if this context has no outer context.
Definition at line 167 of file AbstractContext.java.
{
         return outer;
     }
grant() [1/2]
final void javolution.context.SecurityContext.grant (Permission<?> permission) inherited
Grants the specified permission (convenience method).
Parameters
permission the permission to grant.
Exceptions
SecurityException if the specified permission cannot be granted.
Definition at line 233 of file SecurityContext.java.
{
         grant(permission, null);
     }
References javolution.context.SecurityContext.grant().
grant() [2/2]
void javolution.context.internal.SecurityContextImpl.grant (Permission<?> permission, Object certificate) throws SecurityException
Grants the specified permission.
Parameters
permission the permission to grant.
certificate the certificate used to grant that permission or null if none.
Exceptions
SecurityException if the specified permission cannot be granted.
Reimplemented from javolution.context.SecurityContext.
Definition at line 32 of file SecurityContextImpl.java.
{
         Action a = new Action();
         a.grant = true;
         a.permission = permission;
         actions.add(a);
     }
References javolution.context.internal.SecurityContextImpl.actions, javolution.context.internal.SecurityContextImpl.Action.grant, and javolution.context.internal.SecurityContextImpl.Action.permission.
inherit()
static void javolution.context.AbstractContext.inherit (AbstractContext ctx) static inherited
Inherits the specified context which becomes the context of the current thread. This method is particularly useful when creating new threads to make them inherits from the context stack of the parent thread. [code] //Spawns a new thread inheriting the context of the current thread. MyThread myThread = new MyThread(); myThread.inherited = AbstractContext.current(); myThread.start(); ... class MyThread extends Thread { AbstractContext inherited; public void run() { AbstractContext.inherit(inherited); // Sets current context. ... } }[/code]
Definition at line 131 of file AbstractContext.java.
{
         CURRENT.set(ctx);
     }
Referenced by javolution.context.internal.ConcurrentThreadImpl.run().
inner()
SecurityContext javolution.context.internal.SecurityContextImpl.inner () protected
Returns a new inner instance of this context inheriting the properties of this context. The new instance can be configured independently from its parent.
Reimplemented from javolution.context.AbstractContext.
Definition at line 50 of file SecurityContextImpl.java.
{
         SecurityContextImpl ctx = new SecurityContextImpl();
         ctx.actions.addAll(actions);
         return ctx;
     }
References javolution.context.internal.SecurityContextImpl.actions.
isGranted()
boolean javolution.context.internal.SecurityContextImpl.isGranted (Permission<?> permission)
Indicates if the specified permission is granted.
Parameters
permission the permission to check.
Reimplemented from javolution.context.SecurityContext.
Definition at line 22 of file SecurityContextImpl.java.
{
         boolean isGranted = true;
         for (Action a : actions) {
             if (a.permission.implies(permission))
                 isGranted = a.grant;
         }
         return isGranted;
     }
References javolution.context.internal.SecurityContextImpl.actions.
revoke() [1/2]
final void javolution.context.SecurityContext.revoke (Permission<?> permission) inherited
Revokes the specified permission (convenience method).
Parameters
permission the permission to grant.
Exceptions
SecurityException if the specified permission cannot be revoked.
Definition at line 243 of file SecurityContext.java.
{
         revoke(permission, null);
     }
References javolution.context.SecurityContext.revoke().
revoke() [2/2]
void javolution.context.internal.SecurityContextImpl.revoke (Permission<?> permission, Object certificate) throws SecurityException
Revokes the specified permission.
Parameters
permission the permission to grant.
certificate the certificate used to grant that permission or null if none.
Exceptions
SecurityException if the specified permission cannot be revoked.
Reimplemented from javolution.context.SecurityContext.
Definition at line 41 of file SecurityContextImpl.java.
{
         Action a = new Action();
         a.grant = false;
         a.permission = permission;
         actions.add(a);
     }
References javolution.context.internal.SecurityContextImpl.actions, javolution.context.internal.SecurityContextImpl.Action.grant, and javolution.context.internal.SecurityContextImpl.Action.permission.
Member Data Documentation
actions
FastTable<Action> javolution.context.internal.SecurityContextImpl.actions = new FastTable<Action>() private
Definition at line 19 of file SecurityContextImpl.java.
Referenced by javolution.context.internal.SecurityContextImpl.grant(), javolution.context.internal.SecurityContextImpl.inner(), javolution.context.internal.SecurityContextImpl.isGranted(), and javolution.context.internal.SecurityContextImpl.revoke().
CURRENT
final ThreadLocal<AbstractContext> javolution.context.AbstractContext.CURRENT = new ThreadLocal<AbstractContext>() static private inherited
Holds the last context entered (thread-local).
Definition at line 45 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), javolution.context.AbstractContext.enterInner(), and javolution.context.AbstractContext.exit().
outer
AbstractContext javolution.context.AbstractContext.outer private inherited
Holds the outer context or
null
if none (top context).
Definition at line 50 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), and javolution.context.AbstractContext.enterInner().
The documentation for this class was generated from the following file:
SecurityContextImpl.java