Javolution 6.0.0 java: javolution.util.service.MapService< K, V > Interface Template Reference
javolution.util.service.MapService< K, V > Interface Template Reference
Public Member Functions
MapService< K, V > clone () throws CloneNotSupportedException
SetService< Map.Entry< K, V > > entrySet ()
Iterator< Entry< K, V > > iterator ()
Equality<? super K > keyComparator ()
SetService< K > keySet ()
MapService< K, V > threadSafe ()
Equality<? super V > valueComparator ()
CollectionService< V > values ()
void perform (Consumer< T > action, T part)
T[] split (int n)
void update (Consumer< T > action, T part)
Detailed Description
The set of related map functionalities required to implement fast maps.
Author
Jean-Marie Dautelle
Version
6.0, July 21, 2013
See also
javolution.util.FastMap::FastMap()
Definition at line 26 of file MapService.java.
Member Function Documentation
clone()
MapService<K, V> javolution.util.service.MapService< K, V >.clone () throws CloneNotSupportedException
Returns a copy of this map; updates of the copy should not impact the original.
Implemented in javolution.util.internal.map.MapView< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, and javolution.util.internal.map.FastMapImpl< K, V >.
entrySet()
SetService<Map.Entry<K, V> > javolution.util.service.MapService< K, V >.entrySet ()
Returns a set view over the entries of this map. The set support adding/removing entries. Two entries are considered equals if they have the same key regardless of their values.
Implemented in javolution.util.internal.map.MapView< K, V >, javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >, and javolution.util.service.SortedMapService< K, V >.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.split().
iterator()
Iterator<Entry<K, V> > javolution.util.service.MapService< K, V >.iterator ()
Returns an iterator over this map entries.
Implemented in javolution.util.internal.map.MapView< K, V >, javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >, javolution.util.internal.map.ParallelMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
keyComparator()
Equality<? super K> javolution.util.service.MapService< K, V >.keyComparator ()
Returns the key comparator used for key equality or order if the map is sorted.
Implemented in javolution.util.internal.map.MapView< K, V >, javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >, javolution.util.internal.map.ParallelMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
keySet()
SetService<K> javolution.util.service.MapService< K, V >.keySet ()
Returns a set view over the key of this map, the set support adding new key for which the value is automatically
null
.
Implemented in javolution.util.internal.map.MapView< K, V >, javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >, and javolution.util.service.SortedMapService< K, V >.
perform()
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
split()
T [] javolution.util.function.Splittable< T >.split (int n) inherited
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Implemented in javolution.util.internal.map.MapView< K, V >, javolution.util.internal.table.SharedTableImpl< E >, javolution.util.internal.table.TableView< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.CollectionView< E >, javolution.util.internal.table.AtomicTableImpl< E >, javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.collection.AtomicCollectionImpl< E >, and javolution.util.internal.map.MapView< K, V >.EntrySet.
Referenced by javolution.util.internal.map.ParallelMapImpl< K, V >.perform(), and javolution.util.internal.collection.ParallelCollectionImpl< E >.perform().
threadSafe()
MapService<K,V> javolution.util.service.MapService< K, V >.threadSafe ()
Returns a thread-safe version of this service (used during parallel updates).
Implemented in javolution.util.internal.map.MapView< K, V >, javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >, and javolution.util.service.SortedMapService< K, V >.
Referenced by javolution.util.internal.map.ParallelMapImpl< K, V >.update().
update()
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
valueComparator()
Equality<? super V> javolution.util.service.MapService< K, V >.valueComparator ()
Returns the value comparator used for value equality.
Implemented in javolution.util.internal.map.MapView< K, V >, javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >, javolution.util.internal.map.ParallelMapImpl< K, V >, javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
values()
CollectionService<V> javolution.util.service.MapService< K, V >.values ()
Returns a collection view over the values of this map, the collection support value/entry removal but not adding new values.
Implemented in javolution.util.internal.map.MapView< K, V >.
The documentation for this interface was generated from the following file:
MapService.java