Javolution 6.0.0 java: javolution.osgi.internal.JavolutionActivator Class Reference
javolution.osgi.internal.JavolutionActivator Class Reference
Public Member Functions
void start (BundleContext bc) throws Exception
void stop (BundleContext bc) throws Exception
Private Attributes
ServiceRegistration< XMLInputFactory > xmlInputFactoryRegistration
ServiceRegistration< XMLOutputFactory > xmlOutputFactoryRegistration
Detailed Description
Javolution OSGi bundle activator.
Author
Jean-Marie Dautelle
Version
6.0, July 21, 2013
Definition at line 24 of file JavolutionActivator.java.
Member Function Documentation
start()
void javolution.osgi.internal.JavolutionActivator.start (BundleContext bc) throws Exception
Definition at line 31 of file JavolutionActivator.java.
{
         // Activate services trackers.
         OSGiServices.CONCURRENT_CONTEXT_TRACKER.activate(bc);
         OSGiServices.CONFIGURABLE_LISTENER_TRACKER.activate(bc);
         OSGiServices.LOCAL_CONTEXT_TRACKER.activate(bc);
         OSGiServices.LOG_CONTEXT_TRACKER.activate(bc);
         OSGiServices.LOG_SERVICE_TRACKER.activate(bc);
         OSGiServices.SECURITY_CONTEXT_TRACKER.activate(bc);
         OSGiServices.TEXT_CONTEXT_TRACKER.activate(bc);
         OSGiServices.XML_CONTEXT_TRACKER.activate(bc);
         OSGiServices.XML_INPUT_FACTORY_TRACKER.activate(bc);
         OSGiServices.XML_OUTPUT_FACTORY_TRACKER.activate(bc);
         // Publish XMLInputFactory/XMLOutputFactory services.
         xmlInputFactoryRegistration = (ServiceRegistration<XMLInputFactory>) bc
                 .registerService(XMLInputFactory.class.getName(),
                         new XMLInputFactoryProvider(), null);
         xmlOutputFactoryRegistration = (ServiceRegistration<XMLOutputFactory>) bc
                 .registerService(XMLOutputFactory.class.getName(),
                         new XMLOutputFactoryProvider(), null);
         // Ensures low latency for real-time classes.
         OSGiServices.initializeRealtimeClasses();
     }
References javolution.osgi.internal.ServiceTrackerImpl< C >.activate(), javolution.osgi.internal.OSGiServices.CONCURRENT_CONTEXT_TRACKER, javolution.osgi.internal.OSGiServices.CONFIGURABLE_LISTENER_TRACKER, javolution.osgi.internal.OSGiServices.initializeRealtimeClasses(), javolution.osgi.internal.OSGiServices.LOCAL_CONTEXT_TRACKER, javolution.osgi.internal.OSGiServices.LOG_CONTEXT_TRACKER, javolution.osgi.internal.OSGiServices.LOG_SERVICE_TRACKER, javolution.osgi.internal.OSGiServices.SECURITY_CONTEXT_TRACKER, javolution.osgi.internal.OSGiServices.TEXT_CONTEXT_TRACKER, javolution.osgi.internal.OSGiServices.XML_CONTEXT_TRACKER, javolution.osgi.internal.OSGiServices.XML_INPUT_FACTORY_TRACKER, javolution.osgi.internal.OSGiServices.XML_OUTPUT_FACTORY_TRACKER, javolution.osgi.internal.JavolutionActivator.xmlInputFactoryRegistration, and javolution.osgi.internal.JavolutionActivator.xmlOutputFactoryRegistration.
stop()
void javolution.osgi.internal.JavolutionActivator.stop (BundleContext bc) throws Exception
Definition at line 57 of file JavolutionActivator.java.
{
         OSGiServices.CONCURRENT_CONTEXT_TRACKER.deactivate(bc);
         OSGiServices.CONFIGURABLE_LISTENER_TRACKER.deactivate(bc);
         OSGiServices.LOCAL_CONTEXT_TRACKER.deactivate(bc);
         OSGiServices.LOG_CONTEXT_TRACKER.deactivate(bc);
         OSGiServices.LOG_SERVICE_TRACKER.deactivate(bc);
         OSGiServices.SECURITY_CONTEXT_TRACKER.deactivate(bc);
         OSGiServices.TEXT_CONTEXT_TRACKER.deactivate(bc);
         OSGiServices.XML_CONTEXT_TRACKER.deactivate(bc);
         OSGiServices.XML_INPUT_FACTORY_TRACKER.deactivate(bc);
         OSGiServices.XML_OUTPUT_FACTORY_TRACKER.deactivate(bc);
         xmlInputFactoryRegistration.unregister();
         xmlOutputFactoryRegistration.unregister();
     }
References javolution.osgi.internal.OSGiServices.CONCURRENT_CONTEXT_TRACKER, javolution.osgi.internal.OSGiServices.CONFIGURABLE_LISTENER_TRACKER, javolution.osgi.internal.ServiceTrackerImpl< C >.deactivate(), javolution.osgi.internal.OSGiServices.LOCAL_CONTEXT_TRACKER, javolution.osgi.internal.OSGiServices.LOG_CONTEXT_TRACKER, javolution.osgi.internal.OSGiServices.LOG_SERVICE_TRACKER, javolution.osgi.internal.OSGiServices.SECURITY_CONTEXT_TRACKER, javolution.osgi.internal.OSGiServices.TEXT_CONTEXT_TRACKER, javolution.osgi.internal.OSGiServices.XML_CONTEXT_TRACKER, javolution.osgi.internal.OSGiServices.XML_INPUT_FACTORY_TRACKER, javolution.osgi.internal.OSGiServices.XML_OUTPUT_FACTORY_TRACKER, javolution.osgi.internal.JavolutionActivator.xmlInputFactoryRegistration, and javolution.osgi.internal.JavolutionActivator.xmlOutputFactoryRegistration.
Member Data Documentation
xmlInputFactoryRegistration
ServiceRegistration<XMLInputFactory> javolution.osgi.internal.JavolutionActivator.xmlInputFactoryRegistration private
Definition at line 27 of file JavolutionActivator.java.
Referenced by javolution.osgi.internal.JavolutionActivator.start(), and javolution.osgi.internal.JavolutionActivator.stop().
xmlOutputFactoryRegistration
ServiceRegistration<XMLOutputFactory> javolution.osgi.internal.JavolutionActivator.xmlOutputFactoryRegistration private
Definition at line 28 of file JavolutionActivator.java.
Referenced by javolution.osgi.internal.JavolutionActivator.start(), and javolution.osgi.internal.JavolutionActivator.stop().
The documentation for this class was generated from the following file:
JavolutionActivator.java