Javolution 6.0.0 java: javolution.io.Struct.Unsigned16 Class Reference
javolution.io.Struct.Unsigned16 Class Reference
Public Member Functions
Unsigned16 ()
Unsigned16 (int nbrOfBits)
int get ()
void set (int value)
String toString ()
final Struct struct ()
final int offset ()
final int bitIndex ()
final int bitLength ()
Package Functions
final int get (int wordSize, int word)
final long get (int wordSize, long word)
final int set (int value, int wordSize, int word)
final long set (long value, int wordSize, long word)
Private Attributes
final int _offset
final int _bitIndex
final int _bitLength
Detailed Description
This class represents a 16 bits unsigned integer.
Definition at line 1269 of file Struct.java.
Constructor & Destructor Documentation
Unsigned16() [1/2]
javolution.io.Struct.Unsigned16.Unsigned16 ()
Definition at line 1271 of file Struct.java.
{
             super(16, 2);
         }
Unsigned16() [2/2]
javolution.io.Struct.Unsigned16.Unsigned16 (int nbrOfBits)
Definition at line 1275 of file Struct.java.
{
             super(nbrOfBits, 2);
         }
Member Function Documentation
bitIndex()
final int javolution.io.Struct.Member.bitIndex () inherited
Holds the bit offset of this member (if any). The actual position of the bits data depends upon the endianess and the word size.
Definition at line 998 of file Struct.java.
{
             return _bitIndex;
         }
References javolution.io.Struct.Member._bitIndex.
Referenced by javolution.io.Struct.Member.get(), javolution.io.Struct.BitField.longValue(), javolution.io.Struct.Member.set(), and javolution.io.Struct.BitField.set().
bitLength()
final int javolution.io.Struct.Member.bitLength () inherited
Returns the number of bits in this member. Can be zero if this member is used to force the next member to the next word boundary.
Returns
the number of bits in the member.
Definition at line 1008 of file Struct.java.
{
             return _bitLength;
         }
References javolution.io.Struct.Member._bitLength.
Referenced by javolution.io.Struct.Member.get(), javolution.io.Struct.Bool.get(), javolution.io.Struct.Signed8.get(), javolution.io.Struct.Unsigned8.get(), javolution.io.Struct.Signed16.get(), javolution.io.Struct.Unsigned16.get(), javolution.io.Struct.Signed32.get(), javolution.io.Struct.Unsigned32.get(), javolution.io.Struct.Signed64.get(), javolution.io.Struct.BitField.longValue(), javolution.io.Struct.Member.Member(), javolution.io.Struct.Member.set(), javolution.io.Struct.Bool.set(), javolution.io.Struct.Signed8.set(), javolution.io.Struct.Unsigned8.set(), javolution.io.Struct.Signed16.set(), javolution.io.Struct.Unsigned16.set(), javolution.io.Struct.Signed32.set(), javolution.io.Struct.Unsigned32.set(), javolution.io.Struct.Signed64.set(), and javolution.io.Struct.BitField.set().
get() [1/3]
int javolution.io.Struct.Unsigned16.get ()
Definition at line 1279 of file Struct.java.
{
             final int index = getByteBufferPosition() + offset();
             int word = getByteBuffer().getShort(index);
             return 0xFFFF & ((bitLength() == 16) ? word : get(2, word));
         }
References javolution.io.Struct.Member.bitLength(), javolution.io.Struct.getByteBuffer(), javolution.io.Struct.getByteBufferPosition(), and javolution.io.Struct.Member.offset().
get() [2/3]
final int javolution.io.Struct.Member.get (int wordSize, int word) package inherited
Definition at line 1013 of file Struct.java.
{
             final int shift = (byteOrder() == ByteOrder.BIG_ENDIAN) ? (wordSize << 3)
                     - bitIndex() - bitLength()
                     : bitIndex();
             word >>= shift;
             int mask = 0xFFFFFFFF >>> (32 - bitLength());
             return word & mask;
         }
References javolution.io.Struct.Member.bitIndex(), javolution.io.Struct.Member.bitLength(), and javolution.io.Struct.byteOrder().
get() [3/3]
final long javolution.io.Struct.Member.get (int wordSize, long word) package inherited
Definition at line 1034 of file Struct.java.
{
             final int shift = (byteOrder() == ByteOrder.BIG_ENDIAN) ? (wordSize << 3)
                     - bitIndex() - bitLength()
                     : bitIndex();
             word >>= shift;
             long mask = 0xFFFFFFFFFFFFFFFFL >>> (64 - bitLength());
             return word & mask;
         }
References javolution.io.Struct.Member.bitIndex(), javolution.io.Struct.Member.bitLength(), and javolution.io.Struct.byteOrder().
offset()
final int javolution.io.Struct.Member.offset () inherited
Returns the byte offset of this member in its struct. Equivalent to C/C++ offsetof(struct(), this)
Returns
the offset of this member in the Struct.
Definition at line 989 of file Struct.java.
{
             return _offset;
         }
References javolution.io.Struct.Member._offset.
Referenced by javolution.io.Struct.UTF8String.get(), javolution.io.Struct.Bool.get(), javolution.io.Struct.Signed8.get(), javolution.io.Struct.Unsigned8.get(), javolution.io.Struct.Signed16.get(), javolution.io.Struct.Unsigned16.get(), javolution.io.Struct.Signed32.get(), javolution.io.Struct.Unsigned32.get(), javolution.io.Struct.Signed64.get(), javolution.io.Struct.Float32.get(), javolution.io.Struct.Float64.get(), javolution.io.Struct.Enum8< T extends Enum< T >.get(), javolution.io.Struct.Enum16< T extends Enum< T >.get(), javolution.io.Struct.Enum32< T extends Enum< T >.get(), javolution.io.Struct.Enum64< T extends Enum< T >.get(), javolution.io.Struct.Reference32< S extends Struct >.isUpToDate(), javolution.io.Struct.Reference64< S extends Struct >.isUpToDate(), javolution.io.Struct.BitField.longValue(), javolution.io.Struct.UTF8String.set(), javolution.io.Struct.Bool.set(), javolution.io.Struct.Signed8.set(), javolution.io.Struct.Unsigned8.set(), javolution.io.Struct.Signed16.set(), javolution.io.Struct.Unsigned16.set(), javolution.io.Struct.Signed32.set(), javolution.io.Struct.Unsigned32.set(), javolution.io.Struct.Signed64.set(), javolution.io.Struct.BitField.set(), javolution.io.Struct.Float32.set(), javolution.io.Struct.Float64.set(), javolution.io.Struct.Reference32< S extends Struct >.set(), javolution.io.Struct.Reference64< S extends Struct >.set(), javolution.io.Struct.Enum8< T extends Enum< T >.set(), javolution.io.Struct.Enum16< T extends Enum< T >.set(), javolution.io.Struct.Enum32< T extends Enum< T >.set(), javolution.io.Struct.Enum64< T extends Enum< T >.set(), javolution.io.Struct.Reference32< S extends Struct >.value(), and javolution.io.Struct.Reference64< S extends Struct >.value().
set() [1/3]
void javolution.io.Struct.Unsigned16.set (int value)
Definition at line 1285 of file Struct.java.
{
             final int index = getByteBufferPosition() + offset();
             if (bitLength() == 16) {
                 getByteBuffer().putShort(index, (short) value);
             } else {
                 getByteBuffer().putShort(index,
                         (short) set(value, 2, getByteBuffer().getShort(index)));
             }
         }
References javolution.io.Struct.Member.bitLength(), javolution.io.Struct.getByteBuffer(), javolution.io.Struct.getByteBufferPosition(), and javolution.io.Struct.Member.offset().
set() [2/3]
final int javolution.io.Struct.Member.set (int value, int wordSize, int word) package inherited
Definition at line 1023 of file Struct.java.
{
             final int shift = (byteOrder() == ByteOrder.BIG_ENDIAN) ? (wordSize << 3)
                     - bitIndex() - bitLength()
                     : bitIndex();
             int mask = 0xFFFFFFFF >>> (32 - bitLength());
             mask <<= shift;
             value <<= shift;
             return (word & ~mask) | (value & mask);
         }
References javolution.io.Struct.Member.bitIndex(), javolution.io.Struct.Member.bitLength(), and javolution.io.Struct.byteOrder().
set() [3/3]
final long javolution.io.Struct.Member.set (long value, int wordSize, long word) package inherited
Definition at line 1044 of file Struct.java.
{
             final int shift = (byteOrder() == ByteOrder.BIG_ENDIAN) ? (wordSize << 3)
                     - bitIndex() - bitLength()
                     : bitIndex();
             long mask = 0xFFFFFFFFFFFFFFFFL >>> (64 - bitLength());
             mask <<= shift;
             value <<= shift;
             return (word & ~mask) | (value & mask);
         }
References javolution.io.Struct.Member.bitIndex(), javolution.io.Struct.Member.bitLength(), and javolution.io.Struct.byteOrder().
struct()
final Struct javolution.io.Struct.Member.struct () inherited
Returns the outer struct container.
Returns
the outer struct.
Definition at line 979 of file Struct.java.
{
             return Struct.this;
         }
toString()
String javolution.io.Struct.Unsigned16.toString ()
Definition at line 1295 of file Struct.java.
{
             return String.valueOf(this.get());
         }
Member Data Documentation
_bitIndex
final int javolution.io.Struct.Member._bitIndex private inherited
Holds the relative bit offset of this member to its struct offset.
Definition at line 903 of file Struct.java.
Referenced by javolution.io.Struct.Member.bitIndex(), and javolution.io.Struct.Member.Member().
_bitLength
final int javolution.io.Struct.Member._bitLength private inherited
Holds the bit length of this member.
Definition at line 907 of file Struct.java.
Referenced by javolution.io.Struct.Member.bitLength(), and javolution.io.Struct.Member.Member().
_offset
final int javolution.io.Struct.Member._offset private inherited
Holds the relative offset (in bytes) of this member within its struct.
Definition at line 899 of file Struct.java.
Referenced by javolution.io.Struct.Member.Member(), and javolution.io.Struct.Member.offset().
The documentation for this class was generated from the following file:
Struct.java