Javolution 6.0.0 java: javolution.util.internal.map.ParallelMapImpl< K, V > Class Template Reference
javolution.util.internal.map.ParallelMapImpl< K, V > Class Template Reference
Public Member Functions
ParallelMapImpl (MapService< K, V > target)
boolean containsKey (Object key)
V get (Object key)
Iterator< java.util.Map.Entry< K, V > > iterator ()
Equality<? super K > keyComparator ()
void perform (final Consumer< MapService< K, V >> action, MapService< K, V > view)
V put (K key, V value)
V remove (Object key)
void update (final Consumer< MapService< K, V >> action, MapService< K, V > view)
Equality<? super V > valueComparator ()
void clear ()
MapView< K, V > clone ()
boolean containsValue (Object value)
SetService< Entry< K, V > > entrySet ()
boolean isEmpty ()
SetService< K > keySet ()
void perform (Consumer< T > action, T part)
void putAll (Map<? extends K, ? extends V > m)
V putIfAbsent (K key, V value)
boolean remove (Object key, Object value)
V replace (K key, V value)
boolean replace (K key, V oldValue, V newValue)
int size ()
MapService< K, V >[] split (int n)
MapService< K, V > threadSafe ()
void update (Consumer< T > action, T part)
CollectionService< V > values ()
Protected Member Functions
MapService< K, V > target ()
Private Attributes
MapService< K, V > target
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
A parallel view over a map.
Definition at line 21 of file ParallelMapImpl.java.
Constructor & Destructor Documentation
ParallelMapImpl()
javolution.util.internal.map.ParallelMapImpl< K, V >.ParallelMapImpl (MapService< K, V > target)
Definition at line 25 of file ParallelMapImpl.java.
{
         super(target);
     }
References javolution.util.internal.map.MapView< K, V >.target.
Member Function Documentation
clear()
void javolution.util.internal.map.MapView< K, V >.clear () inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, and javolution.util.internal.map.FastMapImpl< K, V >.
Definition at line 223 of file MapView.java.
{
         Iterator<Entry<K, V>> it = iterator();
         while (it.hasNext()) {
             it.remove();
         }
     }
References javolution.util.internal.map.MapView< K, V >.iterator().
clone()
MapView<K, V> javolution.util.internal.map.MapView< K, V >.clone () inherited
Returns a copy of this map; updates of the copy should not impact the original.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.AtomicMapImpl< K, V >, and javolution.util.internal.map.FastMapImpl< K, V >.
Definition at line 232 of file MapView.java.
{
         try {
             MapView<K, V> copy = (MapView<K, V>) super.clone();
             if (target != null) { // Not a root class.
                 copy.target = target.clone();
             }
             return copy;
         } catch (CloneNotSupportedException e) {
             throw new Error("Should not happen since target is cloneable");
         }
     }
References javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.split().
containsKey()
boolean javolution.util.internal.map.ParallelMapImpl< K, V >.containsKey (Object key)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 30 of file ParallelMapImpl.java.
{
         return target().containsKey(key);
     }
References javolution.util.internal.map.MapView< K, V >.target.
containsValue()
boolean javolution.util.internal.map.MapView< K, V >.containsValue (Object value) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 248 of file MapView.java.
{
         return values().contains(value);
     }
References javolution.util.internal.map.MapView< K, V >.values().
entrySet()
SetService<Entry<K, V> > javolution.util.internal.map.MapView< K, V >.entrySet () inherited
Returns a set view over the entries of this map. The set support adding/removing entries. Two entries are considered equals if they have the same key regardless of their values.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 253 of file MapView.java.
{
         return new EntrySet();
     }
Referenced by javolution.util.internal.map.MapView< K, V >.KeySet.KeySet(), and javolution.util.internal.map.MapView< K, V >.Values.Values().
get()
V javolution.util.internal.map.ParallelMapImpl< K, V >.get (Object key)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 35 of file ParallelMapImpl.java.
{
         return target().get(key);
     }
References javolution.util.internal.map.MapView< K, V >.target.
isEmpty()
boolean javolution.util.internal.map.MapView< K, V >.isEmpty () inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 261 of file MapView.java.
{
         return iterator().hasNext();
     }
References javolution.util.internal.map.MapView< K, V >.iterator().
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.isEmpty().
iterator()
Iterator<java.util.Map.Entry<K, V> > javolution.util.internal.map.ParallelMapImpl< K, V >.iterator ()
Returns an iterator over this map entries.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 40 of file ParallelMapImpl.java.
{
         return target().iterator();
     }
References javolution.util.internal.map.MapView< K, V >.target.
keyComparator()
Equality<? super K> javolution.util.internal.map.ParallelMapImpl< K, V >.keyComparator ()
Returns the key comparator used for key equality or order if the map is sorted.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 45 of file ParallelMapImpl.java.
{
         return target().keyComparator();
     }
References javolution.util.internal.map.MapView< K, V >.target.
keySet()
SetService<K> javolution.util.internal.map.MapView< K, V >.keySet () inherited
Returns a set view over the key of this map, the set support adding new key for which the value is automatically
null
.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 272 of file MapView.java.
{
         return new KeySet();
     }
Referenced by javolution.util.FastSet< Index >.FastSet().
perform() [1/2]
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
perform() [2/2]
void javolution.util.internal.map.ParallelMapImpl< K, V >.perform (final Consumer< MapService< K, V >> action, MapService< K, V > view)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 50 of file ParallelMapImpl.java.
{
         ConcurrentContext ctx = ConcurrentContext.enter();
         try {
             int concurrency = ctx.getConcurrency();
             MapService<K, V>[] subViews = view.split(concurrency + 1);
             for (int i = 1; i < subViews.length; i++) {
                 final MapService<K, V> subView = subViews[i];
                 ctx.execute(new Runnable() {
                     @Override
                     public void run() {
                         target().perform(action, subView);
                     }
                 });
             }
             target().perform(action, subViews[0]); // This thread works too !
         } finally {
             // Any exception raised during parallel iterations will be re-raised here.
             ctx.exit();
         }
     }
References javolution.context.ConcurrentContext.enter(), javolution.context.ConcurrentContext.execute(), javolution.context.ConcurrentContext.exit(), javolution.context.ConcurrentContext.getConcurrency(), javolution.util.function.Splittable< T >.split(), and javolution.util.internal.map.MapView< K, V >.target.
put()
V javolution.util.internal.map.ParallelMapImpl< K, V >.put (K key, V value)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 73 of file ParallelMapImpl.java.
{
         return target().put(key, value);
     }
References javolution.util.internal.map.MapView< K, V >.target.
putAll()
void javolution.util.internal.map.MapView< K, V >.putAll (Map<? extends K, ? extends V > m) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 290 of file MapView.java.
{
         Iterator<?> it = m.entrySet().iterator();
         while (it.hasNext()) {
             Entry<K, V> e = (Entry<K, V>) it.next();
             put(e.getKey(), e.getValue());
         }
     }
References javolution.util.internal.map.MapView< K, V >.put().
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.clone().
putIfAbsent()
V javolution.util.internal.map.MapView< K, V >.putIfAbsent (K key, V value) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 299 of file MapView.java.
{
         if (!containsKey(key)) return put(key, value);
         else return get(key);
     }
References javolution.util.internal.map.MapView< K, V >.containsKey(), and javolution.util.internal.map.MapView< K, V >.put().
remove() [1/2]
V javolution.util.internal.map.ParallelMapImpl< K, V >.remove (Object key)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 78 of file ParallelMapImpl.java.
{
         return target().remove(key);
     }
References javolution.util.internal.map.MapView< K, V >.target.
remove() [2/2]
boolean javolution.util.internal.map.MapView< K, V >.remove (Object key, Object value) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 308 of file MapView.java.
{
         if (containsKey(key) && get(key).equals(value)) {
             remove(key);
             return true;
         } else return false;
     }
References javolution.util.internal.map.MapView< K, V >.containsKey().
replace() [1/2]
boolean javolution.util.internal.map.MapView< K, V >.replace (K key, V oldValue, V newValue) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 323 of file MapView.java.
{
         if (containsKey(key) && get(key).equals(oldValue)) {
             put(key, newValue);
             return true;
         } else return false;
     }
References javolution.util.internal.map.MapView< K, V >.containsKey(), and javolution.util.internal.map.MapView< K, V >.put().
replace() [2/2]
V javolution.util.internal.map.MapView< K, V >.replace (K key, V value) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 316 of file MapView.java.
{
         if (containsKey(key)) {
             return put(key, value);
         } else return null;
     }
References javolution.util.internal.map.MapView< K, V >.containsKey(), and javolution.util.internal.map.MapView< K, V >.put().
size()
int javolution.util.internal.map.MapView< K, V >.size () inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 331 of file MapView.java.
                       {
         int count = 0;
         Iterator<Entry<K, V>> it = iterator();
         while (it.hasNext()) {
             count++;
             it.next();
         }
         return count;
     }
References javolution.util.internal.map.MapView< K, V >.iterator().
Referenced by javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >.put(), and javolution.util.internal.map.MapView< K, V >.EntrySet.size().
split()
MapService<K, V> [] javolution.util.internal.map.MapView< K, V >.split (int n) inherited
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Implements javolution.util.function.Splittable< T >.
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 343 of file MapView.java.
{
         if (target == null) return new MapService[] { this }; // No split.
         MapService<K, V>[] subTargets = target.split(n);
         MapService<K, V>[] result = new MapService[subTargets.length];
         for (int i = 0; i < subTargets.length; i++) {
             MapView<K, V> copy = this.clone();
             copy.target = subTargets[i];
             result[i] = copy;
         }
         return result;
     }
References javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.split().
target()
MapService<K, V> javolution.util.internal.map.MapView< K, V >.target () protected inherited
Returns the actual target
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 378 of file MapView.java.
{
         return target;
     }
References javolution.util.internal.map.MapView< K, V >.target.
threadSafe()
MapService<K, V> javolution.util.internal.map.MapView< K, V >.threadSafe () inherited
Returns a thread-safe version of this service (used during parallel updates).
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 356 of file MapView.java.
{
         return new SharedMapImpl<K, V>(this);
     }
update() [1/2]
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
update() [2/2]
void javolution.util.internal.map.ParallelMapImpl< K, V >.update (final Consumer< MapService< K, V >> action, MapService< K, V > view)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 83 of file ParallelMapImpl.java.
{
         ConcurrentContext ctx = ConcurrentContext.enter();
         try {
             int concurrency = ctx.getConcurrency();
             MapService<K, V>[] subViews = view.threadSafe().split(
                     concurrency + 1);
             for (int i = 1; i < subViews.length; i++) {
                 final MapService<K, V> subView = subViews[i];
                 ctx.execute(new Runnable() {
                     @Override
                     public void run() {
                         target().update(action, subView);
                     }
                 });
             }
             target().perform(action, subViews[0]); // This thread works too !
         } finally {
             // Any exception raised during parallel iterations will be re-raised here.
             ctx.exit();
         }
     }
References javolution.context.ConcurrentContext.enter(), javolution.context.ConcurrentContext.execute(), javolution.context.ConcurrentContext.exit(), javolution.context.ConcurrentContext.getConcurrency(), javolution.util.internal.map.MapView< K, V >.target, and javolution.util.service.MapService< K, V >.threadSafe().
valueComparator()
Equality<? super V> javolution.util.internal.map.ParallelMapImpl< K, V >.valueComparator ()
Returns the value comparator used for value equality.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 107 of file ParallelMapImpl.java.
{
         return target().valueComparator();
     }
References javolution.util.internal.map.MapView< K, V >.target.
values()
CollectionService<V> javolution.util.internal.map.MapView< K, V >.values () inherited
Returns a collection view over the values of this map, the collection support value/entry removal but not adding new values.
Implements javolution.util.service.MapService< K, V >.
Definition at line 373 of file MapView.java.
{
         return new Values();
     }
Referenced by javolution.util.internal.map.MapView< K, V >.containsValue().
Member Data Documentation
serialVersionUID
final long javolution.util.internal.map.ParallelMapImpl< K, V >.serialVersionUID = 0x600L static private
Definition at line 23 of file ParallelMapImpl.java.
target
MapService<K, V> javolution.util.internal.map.MapView< K, V >.target private inherited
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 213 of file MapView.java.
Referenced by javolution.util.internal.map.AtomicMapImpl< K, V >.AtomicMapImpl(), javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >.AtomicSortedMapImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.clear(), javolution.util.internal.map.MapView< K, V >.clone(), javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.SharedMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >.comparator(), javolution.util.internal.map.SequentialMapImpl< K, V >.containsKey(), javolution.util.internal.map.ParallelMapImpl< K, V >.containsKey(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.containsKey(), javolution.util.internal.map.SharedMapImpl< K, V >.containsKey(), javolution.util.internal.map.SharedMapImpl< K, V >.containsValue(), javolution.util.internal.map.SequentialMapImpl< K, V >.get(), javolution.util.internal.map.ParallelMapImpl< K, V >.get(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.get(), javolution.util.internal.map.SharedMapImpl< K, V >.get(), javolution.util.internal.map.SharedMapImpl< K, V >.isEmpty(), javolution.util.internal.map.SequentialMapImpl< K, V >.iterator(), javolution.util.internal.map.ParallelMapImpl< K, V >.iterator(), javolution.util.internal.map.SequentialMapImpl< K, V >.keyComparator(), javolution.util.internal.map.ParallelMapImpl< K, V >.keyComparator(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.keyComparator(), javolution.util.internal.map.SharedMapImpl< K, V >.keyComparator(), javolution.util.internal.map.MapView< K, V >.MapView(), javolution.util.internal.map.ParallelMapImpl< K, V >.ParallelMapImpl(), javolution.util.internal.map.ParallelMapImpl< K, V >.perform(), javolution.util.internal.map.MapView< K, V >.perform(), javolution.util.internal.map.SequentialMapImpl< K, V >.put(), javolution.util.internal.map.ParallelMapImpl< K, V >.put(), javolution.util.internal.map.AtomicMapImpl< K, V >.put(), javolution.util.internal.map.SharedMapImpl< K, V >.put(), javolution.util.internal.map.AtomicMapImpl< K, V >.putAll(), javolution.util.internal.map.SharedMapImpl< K, V >.putAll(), javolution.util.internal.map.AtomicMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.SharedMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.SequentialMapImpl< K, V >.remove(), javolution.util.internal.map.ParallelMapImpl< K, V >.remove(), javolution.util.internal.map.AtomicMapImpl< K, V >.remove(), javolution.util.internal.map.SharedMapImpl< K, V >.remove(), javolution.util.internal.map.AtomicMapImpl< K, V >.replace(), javolution.util.internal.map.SharedMapImpl< K, V >.replace(), javolution.util.internal.map.SequentialMapImpl< K, V >.SequentialMapImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.SharedMapImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.size(), javolution.util.internal.map.SharedMapImpl< K, V >.split(), javolution.util.internal.map.MapView< K, V >.split(), javolution.util.internal.map.MapView< K, V >.target(), javolution.util.internal.map.AtomicMapImpl< K, V >.targetView(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.UnmodifiableMapImpl(), javolution.util.internal.map.ParallelMapImpl< K, V >.update(), javolution.util.internal.map.AtomicMapImpl< K, V >.update(), javolution.util.internal.map.MapView< K, V >.update(), javolution.util.internal.map.SequentialMapImpl< K, V >.valueComparator(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.valueComparator(), javolution.util.internal.map.ParallelMapImpl< K, V >.valueComparator(), and javolution.util.internal.map.SharedMapImpl< K, V >.valueComparator().
The documentation for this class was generated from the following file:
ParallelMapImpl.java