Javolution 6.0.0 java: javolution.text.Text Class Reference
javolution.text.Text Class Reference
Public Member Functions
Text (String str)
int length ()
Text plus (Object obj)
Text plus (String str)
Text concat (Text that)
Text subtext (int start)
Text insert (int index, Text txt)
Text delete (int start, int end)
Text replace (java.lang.CharSequence target, java.lang.CharSequence replacement)
Text replace (CharSet charSet, java.lang.CharSequence replacement)
java.lang.CharSequence subSequence (int start, int end)
int indexOf (java.lang.CharSequence csq)
int indexOf (java.lang.CharSequence csq, int fromIndex)
int lastIndexOf (java.lang.CharSequence csq)
int lastIndexOf (java.lang.CharSequence csq, int fromIndex)
boolean startsWith (java.lang.CharSequence prefix)
boolean endsWith (java.lang.CharSequence suffix)
boolean startsWith (java.lang.CharSequence prefix, int index)
Text trim ()
Text intern ()
boolean contentEquals (java.lang.CharSequence csq)
boolean contentEqualsIgnoreCase (java.lang.CharSequence csq)
boolean equals (Object obj)
int hashCode ()
int compareTo (CharSequence csq)
Text toText ()
void printStatistics (PrintStream out)
Text toLowerCase ()
Text toUpperCase ()
char charAt (int index)
int indexOf (char c)
int indexOf (char c, int fromIndex)
int lastIndexOf (char c, int fromIndex)
Text subtext (int start, int end)
void getChars (int start, int end, char dest[], int destPos)
String toString ()
Text copy ()
boolean isBlank ()
boolean isBlank (int start, int length)
Text trimStart ()
Text trimEnd ()
Text padLeft (int len)
Text padLeft (int len, char c)
Text padRight (int len)
Text padRight (int len, char c)
int indexOfAny (CharSet charSet)
int indexOfAny (CharSet charSet, int start)
int indexOfAny (CharSet charSet, int start, int length)
int lastIndexOfAny (CharSet charSet)
int lastIndexOfAny (CharSet charSet, int start)
int lastIndexOfAny (CharSet charSet, int start, int length)
Text value ()
Static Public Member Functions
static Text valueOf (Object obj)
static Text valueOf (char[] chars)
static Text valueOf (char[] chars, int offset, int length)
static Text valueOf (boolean b)
static Text valueOf (char c)
static Text valueOf (int i)
static Text valueOf (int i, int radix)
static Text valueOf (long l)
static Text valueOf (long l, int radix)
static Text valueOf (float f)
static Text valueOf (double d)
static Text valueOf (double d, int digits, boolean scientific, boolean showZero)
static Text valueOf (char c, int length)
Static Public Attributes
static final Text EMPTY = new Text("").intern()
Static Package Functions
static Text valueOf (TextBuilder tb, int start, int end)
Private Member Functions
Text (boolean isPrimitive)
Text append (String str)
Text rightRotation ()
Text leftRotation ()
int getDepth ()
int getNbrOfBranches ()
int getNbrOfLeaves ()
Static Private Member Functions
static Text valueOf (String str)
static Text valueOf (String str, int start, int end)
static Text newPrimitive (int length)
static Text newComposite (Text head, Text tail)
Private Attributes
final char[] _data
int _count
Text _head
Text _tail
Static Private Attributes
static final long serialVersionUID = 0x600L
static final int BLOCK_SIZE = 1 << 5
static final int BLOCK_MASK = ~(BLOCK_SIZE - 1)
static final FastMap< Text, Text > INTERN
static final Text TRUE = new Text("true").intern()
static final Text FALSE = new Text("false").intern()
Detailed Description
An immutable character sequence with fast concatenation, insertion and deletion capabilities (O[Log(n)]) instead of O[n] for StringBuffer/StringBuilder).
This class has the same methods as Java String and .NET String with the following benefits:
No need for an intermediate StringBuffer/StringBuilder in order to manipulate textual documents (insertion, deletion or concatenation).
Bug free. They are not plagued by the String#substring memory leak bug (when small substrings prevent memory from larger string from being garbage collected).
More flexible as they allows for search and comparison with any java.lang.String or CharSequence.
Text literals should be explicitly interned. Unlike strings literals and strings-value constant expressions, interning is not implicit. For example:[code] final static Text TRUE = new Text("true").intern(); final static Text FALSE = new Text("true").intern("false"); [/code]
Implementation Note: To avoid expensive copy operations , Text instances are broken down into smaller immutable sequences, they form a minimal-depth binary tree. The tree is maintained balanced automatically through tree rotations. Insertion/deletions are performed in O[Log(n)] instead of O[n] for StringBuffer/StringBuilder.
Author
Jean-Marie Dautelle
Wilfried Middleton
Version
6.0, July 21, 2013
Definition at line 61 of file Text.java.
Constructor & Destructor Documentation
Text() [1/2]
javolution.text.Text.Text (boolean isPrimitive) private
Creates a new text instance.
Parameters
isPrimitive indicates if primitive or composite.
Definition at line 112 of file Text.java.
{
         _data = isPrimitive ? new char[BLOCK_SIZE] : null;
     }
References javolution.text.Text._data, and javolution.text.Text.BLOCK_SIZE.
Referenced by javolution.text.Text.equals(), javolution.text.Text.newComposite(), javolution.text.Text.newPrimitive(), and javolution.text.Text.Text().
Text() [2/2]
javolution.text.Text.Text (String str)
Creates a text holding the characters from the specified String .
Parameters
str the string holding the character content.
Definition at line 122 of file Text.java.
{
         this(str.length() <= BLOCK_SIZE);
         _count = str.length();
         if (_data != null) { // Primitive.
             str.getChars(0, _count, _data, 0);
         } else { // Composite, splits on a block boundary.
             int half = ((_count + BLOCK_SIZE) >> 1) & BLOCK_MASK;
             _head = new Text(str.substring(0, half));
             _tail = new Text(str.substring(half, _count));
         }
     }
References javolution.text.Text._count, javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, javolution.text.Text.BLOCK_MASK, javolution.text.Text.BLOCK_SIZE, and javolution.text.Text.Text().
Member Function Documentation
append()
Text javolution.text.Text.append (String str) private
Definition at line 374 of file Text.java.
                                     { // Try to append, returns null if cannot.
         int length = str.length();
         if (_data == null) {
             Text merge = _tail.append(str);
             return merge != null ? Text.newComposite(_head, merge) : null;
         } else { // Primitive.
             if (_count + length > BLOCK_SIZE)
                 return null; // Cannot merge.
             Text text = Text.newPrimitive(_count + length);
             System.arraycopy(_data, 0, text._data, 0, _count);
             str.getChars(0, length, text._data, _count);
             return text;
         }
     }
References javolution.text.Text._count, javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, javolution.text.Text.append(), javolution.text.Text.BLOCK_SIZE, javolution.text.Text.getChars(), javolution.text.Text.length(), javolution.text.Text.newComposite(), and javolution.text.Text.newPrimitive().
Referenced by javolution.text.Text.append(), and javolution.text.Text.plus().
charAt()
char javolution.text.Text.charAt (int index)
Returns the character at the specified index.
Parameters
index the index of the character.
Returns
the character at the specified index.
Exceptions
IndexOutOfBoundsException if (index < 0) || (index >= this.length())
Definition at line 897 of file Text.java.
{
         if (index >= _count)
             throw new IndexOutOfBoundsException();
         return (_data != null) ? _data[index] : (index < _head._count) ? _head
                 .charAt(index) : _tail.charAt(index - _head._count);
     }
References javolution.text.Text._count, javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, and javolution.text.Text.charAt().
Referenced by javolution.text.Text.charAt(), javolution.text.Text.contentEquals(), javolution.text.Text.contentEqualsIgnoreCase(), javolution.text.Text.equals(), javolution.text.Text.hashCode(), javolution.text.Text.indexOf(), javolution.text.Text.indexOfAny(), javolution.text.Text.isBlank(), javolution.text.Text.lastIndexOf(), javolution.text.Text.lastIndexOfAny(), javolution.text.Text.trim(), javolution.text.Text.trimEnd(), and javolution.text.Text.trimStart().
compareTo()
int javolution.text.Text.compareTo (CharSequence csq)
Compares this text to another character sequence or string lexicographically.
Parameters
csq the character sequence to be compared.
Returns
TypeFormat.LEXICAL_COMPARATOR.compare(this, csq)
Exceptions
ClassCastException if the specifed object is not a CharSequence or a String.
Definition at line 808 of file Text.java.
{
         return Equalities.LEXICAL.compare(this, csq);
     }
References javolution.util.function.Equality< T >.compare(), and javolution.util.function.Equalities.LEXICAL.
concat()
Text javolution.text.Text.concat (Text that)
Concatenates the specified text to the end of this text. This method is very fast (faster even than StringBuffer.append(String)) and still returns a text instance with an internal binary tree of minimal depth!
Parameters
that the text that is concatenated.
Returns
this + that
Definition at line 398 of file Text.java.
{
         // All Text instances are maintained balanced:
         //   (head < tail * 2) & (tail < head * 2)
         final int length = this._count + that._count;
         if (length <= BLOCK_SIZE) { // Merges to primitive.
             Text text = Text.newPrimitive(length);
             this.getChars(0, this._count, text._data, 0);
             that.getChars(0, that._count, text._data, this._count);
             return text;
         } else { // Returns a composite.
             Text head = this;
             Text tail = that;
             if (((head._count << 1) < tail._count) && (tail._data == null)) { // tail is composite
                 // head too small, returns (head + tail/2) + (tail/2)
                 if (tail._head._count > tail._tail._count) {
                     // Rotates to concatenate with smaller part.
                     tail = tail.rightRotation();
                 }
                 head = head.concat(tail._head);
                 tail = tail._tail;
             } else if (((tail._count << 1) < head._count)
                     && (head._data == null)) { // head is composite.
                 // tail too small, returns (head/2) + (head/2 concat tail)
                 if (head._tail._count > head._head._count) {
                     // Rotates to concatenate with smaller part.
                     head = head.leftRotation();
                 }
                 tail = head._tail.concat(tail);
                 head = head._head;
             }
             return Text.newComposite(head, tail);
         }
     }
References javolution.text.Text._count, javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, javolution.text.Text.BLOCK_SIZE, javolution.text.Text.concat(), javolution.text.Text.getChars(), javolution.text.Text.leftRotation(), javolution.text.Text.length(), javolution.text.Text.newComposite(), javolution.text.Text.newPrimitive(), and javolution.text.Text.rightRotation().
Referenced by javolution.text.Text.concat(), javolution.text.Text.delete(), javolution.text.Text.insert(), javolution.text.Text.padRight(), javolution.text.Text.plus(), javolution.text.Text.replace(), and javolution.text.Text.subtext().
contentEquals()
boolean javolution.text.Text.contentEquals (java.lang.CharSequence csq)
Indicates if this text has the same character content as the specified character sequence.
Parameters
csq the character sequence to compare with.
Returns
true if the specified character sequence has the same character content as this text; false otherwise.
Definition at line 720 of file Text.java.
{
         if (csq.length() != _count)
             return false;
         for (int i = 0; i < _count;) {
             if (this.charAt(i) != csq.charAt(i++))
                 return false;
         }
         return true;
     }
References javolution.text.Text._count, and javolution.text.Text.charAt().
contentEqualsIgnoreCase()
boolean javolution.text.Text.contentEqualsIgnoreCase (java.lang.CharSequence csq)
Indicates if this text has the same character contend as the specified character sequence ignoring case considerations.
Parameters
csq the CharSequence to compare this text against.
Returns
true if the argument and this text are equal, ignoring case; false otherwise.
Definition at line 738 of file Text.java.
{
         if (this._count != csq.length())
             return false;
         for (int i = 0; i < _count;) {
             char u1 = this.charAt(i);
             char u2 = csq.charAt(i++);
             if (u1 != u2) {
                 u1 = Character.toUpperCase(u1);
                 u2 = Character.toUpperCase(u2);
                 if ((u1 != u2)
                         && (Character.toLowerCase(u1) != Character
                                 .toLowerCase(u2)))
                     return false;
             }
         }
         return true;
     }
References javolution.text.Text._count, and javolution.text.Text.charAt().
copy()
Text javolution.text.Text.copy ()
Definition at line 1056 of file Text.java.
{
         if (_data != null) { // Primitive.
             Text text = Text.newPrimitive(_count);
             System.arraycopy(_data, 0, text._data, 0, _count);
             return text;
         } else { // Composite.
             return Text.newComposite((Text) _head.copy(), (Text) _tail.copy());
         }
     }
References javolution.text.Text._count, javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, javolution.text.Text.copy(), javolution.text.Text.newComposite(), and javolution.text.Text.newPrimitive().
Referenced by javolution.text.Text.copy().
delete()
Text javolution.text.Text.delete (int start, int end)
Returns the text without the characters between the specified indexes.
Parameters
start the beginning index, inclusive.
end the ending index, exclusive.
Returns
subtext(0, start).concat(subtext(end))
Exceptions
IndexOutOfBoundsException if (start < 0) || (end < 0) || (start > end) || (end > this.length()
Definition at line 493 of file Text.java.
{
         if (start > end)
             throw new IndexOutOfBoundsException();
         return subtext(0, start).concat(subtext(end));
     }
References javolution.text.Text.concat(), and javolution.text.Text.subtext().
endsWith()
boolean javolution.text.Text.endsWith (java.lang.CharSequence suffix)
Indicates if this text ends with the specified suffix.
Parameters
suffix the suffix.
Returns
true if the character sequence represented by the argument is a suffix of the character sequence represented by this text; false otherwise.
Definition at line 657 of file Text.java.
{
         return startsWith(suffix, length() - suffix.length());
     }
References javolution.text.Text.length(), and javolution.text.Text.startsWith().
equals()
boolean javolution.text.Text.equals (Object obj)
Compares this text against the specified object for equality. Returns true if the specified object is a text having the same character sequence as this text. For generic comparaison with any character sequence the contentEquals(CharSequence) should be used.
Parameters
obj the object to compare with or null.
Returns
true if that is a text with the same character sequence as this text; false otherwise.
Definition at line 769 of file Text.java.
{
         if (this == obj)
             return true;
         if (!(obj instanceof Text))
             return false;
         final Text that = (Text) obj;
         if (this._count != that._count)
             return false;
         for (int i = 0; i < _count;) {
             if (this.charAt(i) != that.charAt(i++))
                 return false;
         }
         return true;
     }
References javolution.text.Text._count, javolution.text.Text.charAt(), and javolution.text.Text.Text().
getChars()
void javolution.text.Text.getChars (int start, int end, char dest[], int destPos)
Copies the characters from this text into the destination character array.
Parameters
start the index of the first character to copy.
end the index after the last character to copy.
dest the destination array.
destPos the start offset in the destination array.
Exceptions
IndexOutOfBoundsException if (start < 0) || (end < 0) || (start > end) || (end > this.length())
Definition at line 1022 of file Text.java.
{
         if (_data != null) { // Primitive.
             if ((start < 0) || (end > _count) || (start > end))
                 throw new IndexOutOfBoundsException();
             System.arraycopy(_data, start, dest, destPos, end - start);
         } else { // Composite.
             final int cesure = _head._count;
             if (end <= cesure) {
                 _head.getChars(start, end, dest, destPos);
             } else if (start >= cesure) {
                 _tail.getChars(start - cesure, end - cesure, dest, destPos);
             } else { // Overlaps head and tail.
                 _head.getChars(start, cesure, dest, destPos);
                 _tail.getChars(0, end - cesure, dest, destPos + cesure - start);
             }
         }
     }
References javolution.text.Text._count, javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, and javolution.text.Text.getChars().
Referenced by javolution.text.TextBuilder.append(), javolution.text.Text.append(), javolution.text.Text.concat(), javolution.text.Text.getChars(), javolution.io.CharSequenceReader.read(), and javolution.text.Text.toString().
getDepth()
int javolution.text.Text.getDepth () private
Definition at line 841 of file Text.java.
{
         if (_data != null) // Primitive.
             return 0;
         return MathLib.max(_head.getDepth(), _tail.getDepth()) + 1;
     }
References javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, javolution.text.Text.getDepth(), and javolution.lang.MathLib.max().
Referenced by javolution.text.Text.getDepth(), and javolution.text.Text.printStatistics().
getNbrOfBranches()
int javolution.text.Text.getNbrOfBranches () private
Definition at line 847 of file Text.java.
{
         return (_data == null) ? _head.getNbrOfBranches()
                 + _tail.getNbrOfBranches() + 1 : 0;
     }
References javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, and javolution.text.Text.getNbrOfBranches().
Referenced by javolution.text.Text.getNbrOfBranches(), and javolution.text.Text.printStatistics().
getNbrOfLeaves()
int javolution.text.Text.getNbrOfLeaves () private
Definition at line 852 of file Text.java.
{
         return (_data == null) ? _head.getNbrOfLeaves()
                 + _tail.getNbrOfLeaves() : 1;
     }
References javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, and javolution.text.Text.getNbrOfLeaves().
Referenced by javolution.text.Text.getNbrOfLeaves(), and javolution.text.Text.printStatistics().
hashCode()
int javolution.text.Text.hashCode ()
Returns the hash code for this text.
Returns
the hash code value.
Definition at line 790 of file Text.java.
{
         int h = 0;
         final int length = this.length();
         for (int i = 0; i < length;) {
             h = 31 * h + charAt(i++);
         }
         return h;
     }
References javolution.text.Text.charAt(), and javolution.text.Text.length().
indexOf() [1/4]
int javolution.text.Text.indexOf (char c)
Returns the index within this text of the first occurrence of the specified character, starting the search at the beginning.
Parameters
c the character to search for.
Returns
the index of the first occurrence of the character in this text that is greater than or equal to 0, or -1 if the character does not occur.
Definition at line 913 of file Text.java.
{
         return indexOf(c, 0);
     }
References javolution.text.Text.indexOf().
indexOf() [2/4]
int javolution.text.Text.indexOf (char c, int fromIndex)
Returns the index within this text of the first occurrence of the specified character, starting the search at the specified index.
Parameters
c the character to search for.
fromIndex the index to start the search from.
Returns
the index of the first occurrence of the character in this text that is greater than or equal to fromIndex, or -1 if the character does not occur.
Definition at line 927 of file Text.java.
{
         if (_data != null) { // Primitive.
             for (int i = MathLib.max(fromIndex, 0); i < _count; i++) {
                 if (_data[i] == c)
                     return i;
             }
             return -1;
         } else { // Composite.
             final int cesure = _head._count;
             if (fromIndex < cesure) {
                 final int headIndex = _head.indexOf(c, fromIndex);
                 if (headIndex >= 0)
                     return headIndex; // Found in head.
             }
             final int tailIndex = _tail.indexOf(c, fromIndex - cesure);
             return (tailIndex >= 0) ? tailIndex + cesure : -1;
         }
     }
References javolution.text.Text._count, javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, javolution.text.Text.indexOf(), and javolution.lang.MathLib.max().
indexOf() [3/4]
int javolution.text.Text.indexOf (java.lang.CharSequence csq)
Returns the index within this text of the first occurrence of the specified character sequence searching forward.
Parameters
csq a character sequence.
Returns
the index of the first character of the character sequence found; or -1 if the character sequence is not found.
Definition at line 552 of file Text.java.
{
         return indexOf(csq, 0);
     }
Referenced by javolution.text.Text.indexOf(), and javolution.text.Text.replace().
indexOf() [4/4]
int javolution.text.Text.indexOf (java.lang.CharSequence csq, int fromIndex)
Returns the index within this text of the first occurrence of the specified characters sequence searching forward from the specified index.
Parameters
csq a character sequence.
fromIndex the index to start the search from.
Returns
the index in the range [fromIndex, length() - csq.length()] or -1 if the character sequence is not found.
Definition at line 567 of file Text.java.
{
         // Limit cases.
         final int csqLength = csq.length();
         final int min = Math.max(0, fromIndex);
         final int max = _count - csqLength;
         if (csqLength == 0) { return (min > max) ? -1 : min; }
         // Searches for csq.
         final char c = csq.charAt(0);
         for (int i = indexOf(c, min); (i >= 0) && (i <= max); i = indexOf(c,
                 ++i)) {
             boolean match = true;
             for (int j = 1; j < csqLength; j++) {
                 if (this.charAt(i + j) != csq.charAt(j)) {
                     match = false;
                     break;
                 }
             }
             if (match) { return i; }
         }
         return -1;
     }
References javolution.text.Text._count, javolution.text.Text.charAt(), and javolution.text.Text.indexOf().
indexOfAny() [1/3]
int javolution.text.Text.indexOfAny (CharSet charSet)
Returns the index within this text of the first occurrence of any character in the specified character set.
Parameters
charSet the character set.
Returns
the index of the first character that matches one of the characters in the supplied set; or -1 if none.
Definition at line 1220 of file Text.java.
{
         return indexOfAny(charSet, 0, length());
     }
References javolution.text.Text.length().
Referenced by javolution.text.Text.indexOfAny(), and javolution.text.Text.replace().
indexOfAny() [2/3]
int javolution.text.Text.indexOfAny (CharSet charSet, int start)
Returns the index within a region of this text of the first occurrence of any character in the specified character set.
Parameters
charSet the character set.
start the index of the start of the search region in this text.
Returns
the index of the first character that matches one of the characters in the supplied set; or -1 if none.
Definition at line 1233 of file Text.java.
{
         return indexOfAny(charSet, start, length() - start);
     }
References javolution.text.Text.indexOfAny(), and javolution.text.Text.length().
indexOfAny() [3/3]
int javolution.text.Text.indexOfAny (CharSet charSet, int start, int length)
Returns the index within a region of this text of the first occurrence of any character in the specified character set.
Parameters
charSet the character set.
start the index of the start of the search region in this text.
length the length of the region to search.
Returns
the index of the first character that matches one of the characters in the supplied array; or -1 if none.
Definition at line 1247 of file Text.java.
{
         final int stop = start + length;
         for (int i = start; i < stop; i++) {
             if (charSet.contains(charAt(i)))
                 return i;
         }
         return -1;
     }
References javolution.text.Text.charAt(), javolution.text.CharSet.contains(), and javolution.text.Text.length().
insert()
Text javolution.text.Text.insert (int index, Text txt)
Returns the text having the specified text inserted at the specified location.
Parameters
index the insertion position.
txt the text being inserted.
Returns
subtext(0, index).concat(txt).concat(subtext(index))
Exceptions
IndexOutOfBoundsException if (index < 0) || (index > this.length())
Definition at line 480 of file Text.java.
{
         return subtext(0, index).concat(txt).concat(subtext(index));
     }
References javolution.text.Text.concat(), and javolution.text.Text.subtext().
Referenced by javolution.text.Text.padLeft().
intern()
Text javolution.text.Text.intern ()
Returns a text equals to this one from a pool of unique text instances.
Returns
an unique text instance allocated in permanent memory.
Definition at line 707 of file Text.java.
{
         Text txt = INTERN.putIfAbsent(this, this);
         return txt == null ? this : txt;
     }
References javolution.text.Text.INTERN.
isBlank() [1/2]
boolean javolution.text.Text.isBlank ()
Indicates if all characters of this text are whitespaces (no characters greater than the space character).
Returns
true if this text contains only whitespace.
Definition at line 1100 of file Text.java.
{
         return isBlank(0, length());
     }
References javolution.text.Text.length().
isBlank() [2/2]
boolean javolution.text.Text.isBlank (int start, int length)
Indicates if the specified sub-range of characters of this text are whitespaces (no characters greater than the space character).
Parameters
start the start index.
length the number of characters to inspect.
Definition at line 1111 of file Text.java.
{
         for (; start < length; start++) {
             if (charAt(start) > ' ')
                 return false;
         }
         return true;
     }
References javolution.text.Text.charAt(), and javolution.text.Text.length().
lastIndexOf() [1/3]
int javolution.text.Text.lastIndexOf (char c, int fromIndex)
Returns the index within this text of the first occurrence of the specified character, searching backward and starting at the specified index.
Parameters
c the character to search for.
fromIndex the index to start the search backward from.
Returns
the index of the first occurrence of the character in this text that is less than or equal to fromIndex, or -1 if the character does not occur.
Definition at line 957 of file Text.java.
{
         if (_data != null) { // Primitive.
             for (int i = MathLib.min(fromIndex, _count - 1); i >= 0; i--) {
                 if (_data[i] == c)
                     return i;
             }
             return -1;
         } else { // Composite.
             final int cesure = _head._count;
             if (fromIndex >= cesure) {
                 final int tailIndex = _tail.lastIndexOf(c, fromIndex - cesure);
                 if (tailIndex >= 0)
                     return tailIndex + cesure; // Found in tail.
             }
             return _head.lastIndexOf(c, fromIndex);
         }
     }
References javolution.text.Text._count, javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, javolution.text.Text.lastIndexOf(), and javolution.lang.MathLib.min().
lastIndexOf() [2/3]
int javolution.text.Text.lastIndexOf (java.lang.CharSequence csq)
Returns the index within this text of the last occurrence of the specified characters sequence searching backward.
Parameters
csq a character sequence.
Returns
the index of the first character of the character sequence found; or -1 if the character sequence is not found.
Definition at line 599 of file Text.java.
{
         return lastIndexOf(csq, _count);
     }
References javolution.text.Text._count.
Referenced by javolution.text.Text.lastIndexOf().
lastIndexOf() [3/3]
int javolution.text.Text.lastIndexOf (java.lang.CharSequence csq, int fromIndex)
Returns the index within this text of the last occurrence of the specified character sequence searching backward from the specified index.
Parameters
csq a character sequence.
fromIndex the index to start the backward search from.
Returns
the index in the range [0, fromIndex] or -1 if the character sequence is not found.
Definition at line 613 of file Text.java.
{
         // Limit cases.
         final int csqLength = csq.length();
         final int min = 0;
         final int max = Math.min(fromIndex, _count - csqLength);
         if (csqLength == 0) { return (min > max) ? -1 : max; }
         // Searches for csq.
         final char c = csq.charAt(0);
         for (int i = lastIndexOf(c, max); (i >= 0); i = lastIndexOf(c, --i)) {
             boolean match = true;
             for (int j = 1; j < csqLength; j++) {
                 if (this.charAt(i + j) != csq.charAt(j)) {
                     match = false;
                     break;
                 }
             }
             if (match) { return i; }
         }
         return -1;
     }
References javolution.text.Text._count, javolution.text.Text.charAt(), and javolution.text.Text.lastIndexOf().
lastIndexOfAny() [1/3]
int javolution.text.Text.lastIndexOfAny (CharSet charSet)
Returns the index within this text of the last occurrence of any character in the specified character set.
Parameters
charSet the character set.
Returns
the index of the last character that matches one of the characters in the supplied array; or -1 if none.
Definition at line 1264 of file Text.java.
{
         return lastIndexOfAny(charSet, 0, length());
     }
References javolution.text.Text.length().
Referenced by javolution.text.Text.lastIndexOfAny().
lastIndexOfAny() [2/3]
int javolution.text.Text.lastIndexOfAny (CharSet charSet, int start)
Returns the index within a region of this text of the last occurrence of any character in the specified character set.
Parameters
charSet the character set.
start the index of the start of the search region in this text.
Returns
the index of the last character that matches one of the characters in the supplied array; or -1 if none.
Definition at line 1277 of file Text.java.
{
         return lastIndexOfAny(charSet, start, length() - start);
     }
References javolution.text.Text.lastIndexOfAny(), and javolution.text.Text.length().
lastIndexOfAny() [3/3]
int javolution.text.Text.lastIndexOfAny (CharSet charSet, int start, int length)
Returns the index within a region of this text of the last occurrence of any character in the specified character set.
Parameters
charSet the character set.
start the index of the start of the search region in this text.
length the length of the region to search.
Returns
the index of the last character that matches one of the characters in the supplied array; or -1 if none.
Definition at line 1291 of file Text.java.
{
         for (int i = start + length; --i >= start;) {
             if (charSet.contains(charAt(i)))
                 return i;
         }
         return -1;
     }
References javolution.text.Text.charAt(), javolution.text.CharSet.contains(), and javolution.text.Text.length().
leftRotation()
Text javolution.text.Text.leftRotation () private
Definition at line 447 of file Text.java.
{
         // See: http://en.wikipedia.org/wiki/Tree_rotation
         Text Q = this._tail;
         if (Q._data != null)
             return this; // Tail not a composite, cannot rotate.
         Text B = Q._head;
         Text C = Q._tail;
         Text A = this._head;
         return Text.newComposite(Text.newComposite(A, B), C);
     }
References javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, and javolution.text.Text.newComposite().
Referenced by javolution.text.Text.concat().
length()
int javolution.text.Text.length ()
Returns the length of this text.
Returns
the number of characters (16-bits Unicode) composing this text.
Definition at line 346 of file Text.java.
{
         return _count;
     }
References javolution.text.Text._count.
Referenced by javolution.text.TextBuilder.append(), javolution.text.Text.append(), javolution.text.Text.concat(), javolution.text.Text.endsWith(), javolution.text.Text.hashCode(), javolution.text.Text.indexOfAny(), javolution.text.Text.isBlank(), javolution.text.Text.lastIndexOfAny(), javolution.text.Text.newPrimitive(), javolution.text.Text.padLeft(), javolution.text.Text.padRight(), javolution.text.Text.printStatistics(), javolution.text.Text.startsWith(), javolution.text.Text.subtext(), javolution.text.Text.trim(), javolution.text.Text.trimEnd(), javolution.text.Text.trimStart(), and javolution.text.Text.valueOf().
newComposite()
static Text javolution.text.Text.newComposite (Text head, Text tail) static private
Returns a context allocated composite text instance.
Parameters
head the composite head.
tail the composite tail.
Definition at line 1320 of file Text.java.
{
         Text text = new Text(false);
         text._count = head._count + tail._count;
         text._head = head;
         text._tail = tail;
         return text;
     }
References javolution.text.Text._count, javolution.text.Text._head, javolution.text.Text._tail, and javolution.text.Text.Text().
Referenced by javolution.text.Text.append(), javolution.text.Text.concat(), javolution.text.Text.copy(), javolution.text.Text.leftRotation(), javolution.text.Text.rightRotation(), javolution.text.Text.toLowerCase(), javolution.text.Text.toUpperCase(), and javolution.text.Text.valueOf().
newPrimitive()
static Text javolution.text.Text.newPrimitive (int length) static private
Returns a context allocated primitive text instance.
Parameters
length the primitive length.
Definition at line 1307 of file Text.java.
{
         Text text = new Text(true);
         text._count = length;
         return text;
     }
References javolution.text.Text._count, javolution.text.Text.length(), and javolution.text.Text.Text().
Referenced by javolution.text.Text.append(), javolution.text.Text.concat(), javolution.text.Text.copy(), javolution.text.Text.subtext(), javolution.text.Text.toLowerCase(), javolution.text.Text.toUpperCase(), and javolution.text.Text.valueOf().
padLeft() [1/2]
Text javolution.text.Text.padLeft (int len)
Pads this text on the left with spaces to make the minimum total length as specified. The new length of the new text is equal to the original length plus (length()-len) spaces.
Parameters
len the total number of characters to make this text equal to.
Returns
a new text or the same text if no padding required.
Exceptions
an IllegalArgumentException if the (len<0).
Definition at line 1160 of file Text.java.
{
         return padLeft(len, ' ');
     }
padLeft() [2/2]
Text javolution.text.Text.padLeft (int len, char c)
Pads this text on the left to make the minimum total length as specified. Spaces or the given Unicode character are used to pad with.
The new length of the new text is equal to the original length plus (length()-len) pad characters.
Parameters
len the total number of characters to make this text equal to.
c the character to pad using.
Returns
a new text or the same text if no padding required.
Exceptions
an IllegalArgumentException if the (len<0).
Definition at line 1176 of file Text.java.
{
         final int padSize = (len <= length()) ? 0 : len - length();
         return insert(0, Text.valueOf(c, padSize));
     }
References javolution.text.Text.insert(), javolution.text.Text.length(), and javolution.text.Text.valueOf().
padRight() [1/2]
Text javolution.text.Text.padRight (int len)
Pads this text on the right with spaces to make the minimum total length as specified. The new length of the new text is equal to the original length plus (length()-len) spaces.
Parameters
len the total number of characters to make this text equal to.
Returns
a new text or the same text if no padding required.
Exceptions
an IllegalArgumentException if the (len<0).
Definition at line 1191 of file Text.java.
{
         return padRight(len, ' ');
     }
padRight() [2/2]
Text javolution.text.Text.padRight (int len, char c)
Pads this text on the right to make the minimum total length as specified. Spaces or the given Unicode character are used to pad with.
The new length of the new text is equal to the original length plus (length()-len) pad characters.
Parameters
len the total number of characters to make this text equal to.
c the character to pad using.
Returns
a new text or the same text if no padding required.
Exceptions
an IllegalArgumentException if the (len<0).
Definition at line 1207 of file Text.java.
{
         final int padSize = (len <= length()) ? 0 : len - length();
         return concat(Text.valueOf(c, padSize));
     }
References javolution.text.Text.concat(), javolution.text.Text.length(), and javolution.text.Text.valueOf().
plus() [1/2]
Text javolution.text.Text.plus (Object obj)
Returns the concatenation of this text and the textual representation of the specified object.
Parameters
obj the object whose textual representation is concatenated.
Returns
this.concat(Text.valueOf(obj))
Definition at line 357 of file Text.java.
{
         return this.concat(Text.valueOf(obj));
     }
References javolution.text.Text.concat(), and javolution.text.Text.valueOf().
plus() [2/2]
Text javolution.text.Text.plus (String str)
Returns the concatenation of this text and the specified String (optimization).
Parameters
str the string whose characters are concatenated.
Returns
this.concat(Text.valueOf(obj))
Definition at line 368 of file Text.java.
{
         Text merge = this.append(str);
         return merge != null ? merge : concat(Text.valueOf(str));
     }
References javolution.text.Text.append(), javolution.text.Text.concat(), and javolution.text.Text.valueOf().
printStatistics()
void javolution.text.Text.printStatistics (PrintStream out)
Prints the current statistics on this text tree structure.
Parameters
out the stream to use for output (e.g. System.out)
Definition at line 827 of file Text.java.
{
         int length = this.length();
         int leaves = getNbrOfLeaves();
         synchronized (out) {
             out.print("LENGTH: " + length());
             out.print(", MAX DEPTH: " + getDepth());
             out.print(", NBR OF BRANCHES: " + getNbrOfBranches());
             out.print(", NBR OF LEAVES: " + leaves);
             out.print(", AVG LEAVE LENGTH: " + (length + (leaves >> 1))
                     / leaves);
             out.println();
         }
     }
References javolution.text.Text.getDepth(), javolution.text.Text.getNbrOfBranches(), javolution.text.Text.getNbrOfLeaves(), and javolution.text.Text.length().
replace() [1/2]
Text javolution.text.Text.replace (CharSet charSet, java.lang.CharSequence replacement)
Replaces the specified characters in this text with the specified replacement sequence.
Parameters
charSet the set of characters to be replaced.
replacement the replacement sequence.
Returns
the resulting text.
Definition at line 524 of file Text.java.
{
         int i = indexOfAny(charSet);
         return (i < 0) ? this : // No character to replace.
                 subtext(0, i).concat(Text.valueOf(replacement)).concat(
                         subtext(i + 1).replace(charSet, replacement));
     }
References javolution.text.Text.concat(), javolution.text.Text.indexOfAny(), javolution.text.Text.replace(), javolution.text.Text.subtext(), and javolution.text.Text.valueOf().
replace() [2/2]
Text javolution.text.Text.replace (java.lang.CharSequence target, java.lang.CharSequence replacement)
Replaces each character sequence of this text that matches the specified target sequence with the specified replacement sequence.
Parameters
target the character sequence to be replaced.
replacement the replacement sequence.
Returns
the resulting text.
Definition at line 507 of file Text.java.
{
         int i = indexOf(target);
         return (i < 0) ? this : // No target sequence found.
                 subtext(0, i).concat(Text.valueOf(replacement)).concat(
                         subtext(i + target.length()).replace(target,
                                 replacement));
     }
References javolution.text.Text.concat(), javolution.text.Text.indexOf(), javolution.text.Text.replace(), javolution.text.Text.subtext(), and javolution.text.Text.valueOf().
Referenced by javolution.text.Text.replace().
rightRotation()
Text javolution.text.Text.rightRotation () private
Definition at line 436 of file Text.java.
{
         // See: http://en.wikipedia.org/wiki/Tree_rotation
         Text P = this._head;
         if (P._data != null)
             return this; // Head not a composite, cannot rotate.
         Text A = P._head;
         Text B = P._tail;
         Text C = this._tail;
         return Text.newComposite(A, Text.newComposite(B, C));
     }
References javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, and javolution.text.Text.newComposite().
Referenced by javolution.text.Text.concat().
startsWith() [1/2]
boolean javolution.text.Text.startsWith (java.lang.CharSequence prefix)
Indicates if this text starts with the specified prefix.
Parameters
prefix the prefix.
Returns
true if the character sequence represented by the argument is a prefix of the character sequence represented by this text; false otherwise.
Definition at line 645 of file Text.java.
{
         return startsWith(prefix, 0);
     }
Referenced by javolution.text.Text.endsWith().
startsWith() [2/2]
boolean javolution.text.Text.startsWith (java.lang.CharSequence prefix, int index)
Indicates if this text starts with the specified prefix at the specified index.
Parameters
prefix the prefix.
index the index of the prefix location in this string.
Returns
this.substring(index).startsWith(prefix)
Definition at line 669 of file Text.java.
{
         final int prefixLength = prefix.length();
         if ((index >= 0) && (index <= (this.length() - prefixLength))) {
             for (int i = 0, j = index; i < prefixLength;) {
                 if (prefix.charAt(i++) != this.charAt(j++)) { return false; }
             }
             return true;
         } else {
             return false;
         }
     }
References javolution.text.Text.length().
subSequence()
java.lang.CharSequence javolution.text.Text.subSequence (int start, int end)
Returns subtext(start, end).
Parameters
start the index of the first character inclusive.
end the index of the last character exclusive.
Returns
this.subtext(start, end)
Exceptions
IndexOutOfBoundsException if (start < 0) || (end < 0) || (start > end) || (end > this.length())
Definition at line 540 of file Text.java.
{
         return subtext(start, end);
     }
References javolution.text.Text.subtext().
subtext() [1/2]
Text javolution.text.Text.subtext (int start)
Returns a portion of this text.
Parameters
start the index of the first character inclusive.
Returns
the sub-text starting at the specified position.
Exceptions
IndexOutOfBoundsException if (start < 0) || (start > this.length())
Definition at line 466 of file Text.java.
{
         return subtext(start, length());
     }
References javolution.text.Text.length().
Referenced by javolution.text.Text.delete(), javolution.text.Text.insert(), javolution.text.Text.replace(), javolution.text.Text.subSequence(), javolution.text.Text.subtext(), javolution.text.Text.trim(), javolution.text.Text.trimEnd(), and javolution.text.Text.trimStart().
subtext() [2/2]
Text javolution.text.Text.subtext (int start, int end)
Returns a portion of this text.
Parameters
start the index of the first character inclusive.
end the index of the last character exclusive.
Returns
the sub-text starting at the specified start position and ending just before the specified end position.
Exceptions
IndexOutOfBoundsException if (start < 0) || (end < 0) || (start > end) || (end > this.length())
Definition at line 985 of file Text.java.
{
         if (_data != null) { // Primitive.
             if ((start < 0) || (start > end) || (end > _count))
                 throw new IndexOutOfBoundsException();
             if ((start == 0) && (end == _count))
                 return this;
             if (start == end)
                 return Text.EMPTY;
             int length = end - start;
             Text text = Text.newPrimitive(length);
             System.arraycopy(_data, start, text._data, 0, length);
             return text;
         } else { // Composite.
             final int cesure = _head._count;
             if (end <= cesure)
                 return _head.subtext(start, end);
             if (start >= cesure)
                 return _tail.subtext(start - cesure, end - cesure);
             if ((start == 0) && (end == _count))
                 return this;
             // Overlaps head and tail.
             return _head.subtext(start, cesure).concat(
                     _tail.subtext(0, end - cesure));
         }
     }
References javolution.text.Text._count, javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, javolution.text.Text.concat(), javolution.text.Text.EMPTY, javolution.text.Text.length(), javolution.text.Text.newPrimitive(), and javolution.text.Text.subtext().
toLowerCase()
Text javolution.text.Text.toLowerCase ()
Converts the characters of this text to lower case.
Returns
the text in lower case.
See also
Character::toLowerCase(char)
Definition at line 863 of file Text.java.
{
         if (_data == null) // Composite.
             return Text.newComposite(_head.toLowerCase(), _tail.toLowerCase());
         Text text = Text.newPrimitive(_count);
         for (int i = 0; i < _count;) {
             text._data[i] = Character.toLowerCase(_data[i++]);
         }
         return text;
     }
References javolution.text.Text._count, javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, javolution.text.Text.newComposite(), javolution.text.Text.newPrimitive(), and javolution.text.Text.toLowerCase().
Referenced by javolution.text.Text.toLowerCase().
toString()
String javolution.text.Text.toString ()
Returns the String representation of this text.
Returns
the java.lang.String for this text.
Definition at line 1045 of file Text.java.
{
         if (_data != null) { // Primitive.
             return new String(_data, 0, _count);
         } else { // Composite.
             char[] data = new char[_count];
             this.getChars(0, _count, data, 0);
             return new String(data, 0, _count);
         }
     }
References javolution.text.Text._count, javolution.text.Text._data, and javolution.text.Text.getChars().
toText()
Text javolution.text.Text.toText ()
Returns this (implements Realtime interface).
Returns
this
Definition at line 818 of file Text.java.
{
         return this;
     }
toUpperCase()
Text javolution.text.Text.toUpperCase ()
Converts the characters of this text to upper case.
Returns
the text in lower case.
See also
Character::toUpperCase(char)
Definition at line 879 of file Text.java.
{
         if (_data == null) // Composite.
             return newComposite(_head.toUpperCase(), _tail.toUpperCase());
         Text text = Text.newPrimitive(_count);
         for (int i = 0; i < _count;) {
             text._data[i] = Character.toUpperCase(_data[i++]);
         }
         return text;
     }
References javolution.text.Text._count, javolution.text.Text._data, javolution.text.Text._head, javolution.text.Text._tail, javolution.text.Text.newComposite(), javolution.text.Text.newPrimitive(), and javolution.text.Text.toUpperCase().
Referenced by javolution.text.Text.toUpperCase().
trim()
Text javolution.text.Text.trim ()
Returns a copy of this text, with leading and trailing whitespace omitted.
Returns
a copy of this text with leading and trailing white space removed, or this text if it has no leading or trailing white space.
Definition at line 689 of file Text.java.
{
         int first = 0; // First character index.
         int last = length() - 1; // Last character index.
         while ((first <= last) && (charAt(first) <= ' ')) {
             first++;
         }
         while ((last >= first) && (charAt(last) <= ' ')) {
             last--;
         }
         return subtext(first, last + 1);
     }
References javolution.text.Text.charAt(), javolution.text.Text.length(), and javolution.text.Text.subtext().
trimEnd()
Text javolution.text.Text.trimEnd ()
Returns a copy of this text, with trailing whitespace omitted.
Returns
a copy of this text with trailing white space removed, or this text if it has no trailing white space.
Definition at line 1141 of file Text.java.
{
         int first = 0; // First character index.
         int last = length() - 1; // Last character index.
         while ((last >= first) && (charAt(last) <= ' ')) {
             last--;
         }
         return subtext(first, last + 1);
     }
References javolution.text.Text.charAt(), javolution.text.Text.length(), and javolution.text.Text.subtext().
trimStart()
Text javolution.text.Text.trimStart ()
Returns a copy of this text, with leading whitespace omitted.
Returns
a copy of this text with leading white space removed, or this text if it has no leading white space.
Definition at line 1125 of file Text.java.
{
         int first = 0; // First character index.
         int last = length() - 1; // Last character index.
         while ((first <= last) && (charAt(first) <= ' ')) {
             first++;
         }
         return subtext(first, last + 1);
     }
References javolution.text.Text.charAt(), javolution.text.Text.length(), and javolution.text.Text.subtext().
value()
Text javolution.text.Text.value ()
Returns
this
.
Implements javolution.lang.ValueType< T >.
Definition at line 1329 of file Text.java.
{
         return this;
     }
valueOf() [1/16]
static Text javolution.text.Text.valueOf (boolean b) static
Returns the text representation of the boolean argument.
Parameters
b a boolean.
Returns
if the argument is true, the text "true" is returned; otherwise, the text "false" is returned.
Definition at line 226 of file Text.java.
{
         return b ? TRUE : FALSE;
     }
References javolution.text.Text.FALSE, and javolution.text.Text.TRUE.
valueOf() [2/16]
static Text javolution.text.Text.valueOf (char c) static
Returns the text instance corresponding to the specified character.
Parameters
c a character.
Returns
a text of length 1 containing 'c'.
Definition at line 240 of file Text.java.
{
         Text text = Text.newPrimitive(1);
         text._data[0] = c;
         return text;
     }
References javolution.text.Text._data, and javolution.text.Text.newPrimitive().
valueOf() [3/16]
static Text javolution.text.Text.valueOf (char c, int length) static
Returns the text that contains a specific length sequence of the character specified.
Parameters
c the character to fill this text with.
length the length of the text returned.
Returns
the corresponding instance.
Exceptions
IndexOutOfBoundsException if (length < 0)
Definition at line 1078 of file Text.java.
{
         if (length < 0)
             throw new IndexOutOfBoundsException();
         if (length <= BLOCK_SIZE) {
             Text text = Text.newPrimitive(length);
             for (int i = 0; i < length;) {
                 text._data[i++] = c;
             }
             return text;
         } else {
             final int middle = (length >> 1);
             return Text.newComposite(Text.valueOf(c, middle),
                     Text.valueOf(c, length - middle));
         }
     }
References javolution.text.Text._data, javolution.text.Text.BLOCK_SIZE, javolution.text.Text.length(), javolution.text.Text.newComposite(), javolution.text.Text.newPrimitive(), and javolution.text.Text.valueOf().
valueOf() [4/16]
static Text javolution.text.Text.valueOf (char[] chars) static
Returns the text that contains the characters from the specified array.
Parameters
chars the array source of the characters.
Returns
the corresponding instance.
Definition at line 168 of file Text.java.
{
         return Text.valueOf(chars, 0, chars.length);
     }
References javolution.text.Text.valueOf().
valueOf() [5/16]
static Text javolution.text.Text.valueOf (char[] chars, int offset, int length) static
Returns the text that contains the characters from the specified subarray of characters.
Parameters
chars the source of the characters.
offset the index of the first character in the data soure.
length the length of the text returned.
Returns
the corresponding instance.
Exceptions
IndexOutOfBoundsException if (offset < 0) || (length < 0) || ((offset + length) > chars.length)
Definition at line 183 of file Text.java.
{
         if ((offset < 0) || (length < 0) || ((offset + length) > chars.length))
             throw new IndexOutOfBoundsException();
         if (length <= BLOCK_SIZE) {
             Text text = Text.newPrimitive(length);
             System.arraycopy(chars, offset, text._data, 0, length);
             return text;
         } else { // Splits on a block boundary.
             int half = ((length + BLOCK_SIZE) >> 1) & BLOCK_MASK;
             return Text.newComposite(Text.valueOf(chars, offset, half),
                     Text.valueOf(chars, offset + half, length - half));
         }
     }
References javolution.text.Text._data, javolution.text.Text.BLOCK_MASK, javolution.text.Text.BLOCK_SIZE, javolution.text.Text.length(), javolution.text.Text.newComposite(), javolution.text.Text.newPrimitive(), and javolution.text.Text.valueOf().
valueOf() [6/16]
static Text javolution.text.Text.valueOf (double d) static
Returns the textual representation of the specified double argument.
Parameters
d the double to format.
Returns
the corresponding text instance.
Definition at line 315 of file Text.java.
{
         TextBuilder tb = new TextBuilder();
         return tb.append(d).toText();
     }
References javolution.text.TextBuilder.append(), and javolution.text.TextBuilder.toText().
valueOf() [7/16]
static Text javolution.text.Text.valueOf (double d, int digits, boolean scientific, boolean showZero) static
Returns the textual representation of the specified double argument formatted as specified.
Parameters
d the double to format.
digits the number of significative digits (excludes exponent) or -1 to mimic the standard library (16 or 17 digits).
scientific true to forces the use of the scientific notation (e.g. 1.23E3); false otherwise.
showZero true if trailing fractional zeros are represented; false otherwise.
Returns
the corresponding text instance.
Exceptions
IllegalArgumentException if (digits > 19))
Definition at line 335 of file Text.java.
{
         TextBuilder tb = new TextBuilder();
         return tb.append(d, digits, scientific, showZero).toText();
     }
References javolution.text.TextBuilder.append(), and javolution.text.TextBuilder.toText().
valueOf() [8/16]
static Text javolution.text.Text.valueOf (float f) static
Returns the textual representation of the specified float instance.
Parameters
f the float to format.
Returns
the corresponding text instance.
Definition at line 303 of file Text.java.
{
         TextBuilder tb = new TextBuilder();
         return tb.append(f).toText();
     }
References javolution.text.TextBuilder.append(), and javolution.text.TextBuilder.toText().
valueOf() [9/16]
static Text javolution.text.Text.valueOf (int i) static
Returns the decimal representation of the specified int argument.
Parameters
i the int to format.
Returns
the corresponding text instance.
Definition at line 253 of file Text.java.
{
         TextBuilder tb = new TextBuilder();
         return tb.append(i).toText();
     }
References javolution.text.TextBuilder.append(), and javolution.text.TextBuilder.toText().
valueOf() [10/16]
static Text javolution.text.Text.valueOf (int i, int radix) static
Returns the radix representation of the specified int argument.
Parameters
i the int to format.
radix the radix (e.g. 16 for hexadecimal).
Returns
the corresponding text instance.
Definition at line 266 of file Text.java.
{
         TextBuilder tb = new TextBuilder();
         return tb.append(i, radix).toText();
     }
References javolution.text.TextBuilder.append(), and javolution.text.TextBuilder.toText().
valueOf() [11/16]
static Text javolution.text.Text.valueOf (long l) static
Returns the decimal representation of the specified long argument.
Parameters
l the long to format.
Returns
the corresponding text instance.
Definition at line 278 of file Text.java.
{
         TextBuilder tb = new TextBuilder();
         return tb.append(l).toText();
     }
References javolution.text.TextBuilder.append(), and javolution.text.TextBuilder.toText().
valueOf() [12/16]
static Text javolution.text.Text.valueOf (long l, int radix) static
Returns the radix representation of the specified long argument.
Parameters
l the long to format.
radix the radix (e.g. 16 for hexadecimal).
Returns
the corresponding text instance.
Definition at line 291 of file Text.java.
{
         TextBuilder tb = new TextBuilder();
         return tb.append(l, radix).toText();
     }
References javolution.text.TextBuilder.append(), and javolution.text.TextBuilder.toText().
valueOf() [13/16]
static Text javolution.text.Text.valueOf (Object obj) static
Returns the text representing the specified object.
Parameters
obj the object to represent as text.
Returns
new TextBuilder().append(obj).toText()
Definition at line 140 of file Text.java.
{
         return new TextBuilder().append(obj).toText();
     }
References javolution.text.TextBuilder.append(), and javolution.text.TextBuilder.toText().
Referenced by javolution.text.Text.padLeft(), javolution.text.Text.padRight(), javolution.text.Text.plus(), javolution.text.Text.replace(), javolution.text.TextBuilder.subSequence(), javolution.text.TextBuilder.toText(), javolution.text.Text.valueOf(), and javolution.io.AppendableWriter.write().
valueOf() [14/16]
static Text javolution.text.Text.valueOf (String str) static private
Definition at line 144 of file Text.java.
{
         return Text.valueOf(str, 0, str.length());
     }
References javolution.text.Text.valueOf().
valueOf() [15/16]
static Text javolution.text.Text.valueOf (String str, int start, int end) static private
Definition at line 148 of file Text.java.
{
         int length = end - start;
         if (length <= BLOCK_SIZE) {
             Text text = newPrimitive(length);
             str.getChars(start, end, text._data, 0);
             return text;
         } else { // Splits on a block boundary.
             int half = ((length + BLOCK_SIZE) >> 1) & BLOCK_MASK;
             return newComposite(Text.valueOf(str, start, start + half),
                     Text.valueOf(str, start + half, end));
         }
     }
References javolution.text.Text._data, javolution.text.Text.BLOCK_MASK, javolution.text.Text.BLOCK_SIZE, javolution.text.Text.length(), javolution.text.Text.newComposite(), javolution.text.Text.newPrimitive(), and javolution.text.Text.valueOf().
valueOf() [16/16]
static Text javolution.text.Text.valueOf (TextBuilder tb, int start, int end) static package
Converts a text builder to a text instance (optimization for TextBuilder.toText()).
Parameters
start the index of the first character inclusive.
end the index of the last character exclusive.
Returns
the corresponding text instance.
Definition at line 205 of file Text.java.
{
         int length = end - start;
         if (length <= BLOCK_SIZE) {
             Text text = Text.newPrimitive(length);
             tb.getChars(start, end, text._data, 0);
             return text;
         } else { // Splits on a block boundary.
             int half = ((length + BLOCK_SIZE) >> 1) & BLOCK_MASK;
             return Text.newComposite(Text.valueOf(tb, start, start + half),
                     Text.valueOf(tb, start + half, end));
         }
     }
References javolution.text.Text._data, javolution.text.Text.BLOCK_MASK, javolution.text.Text.BLOCK_SIZE, javolution.text.TextBuilder.getChars(), javolution.text.Text.length(), javolution.text.Text.newComposite(), javolution.text.Text.newPrimitive(), and javolution.text.Text.valueOf().
Member Data Documentation
_count
int javolution.text.Text._count private
Holds the total number of characters.
Definition at line 95 of file Text.java.
Referenced by javolution.text.Text.append(), javolution.text.Text.charAt(), javolution.text.Text.concat(), javolution.text.Text.contentEquals(), javolution.text.Text.contentEqualsIgnoreCase(), javolution.text.Text.copy(), javolution.text.Text.equals(), javolution.text.Text.getChars(), javolution.text.Text.indexOf(), javolution.text.Text.lastIndexOf(), javolution.text.Text.length(), javolution.text.Text.newComposite(), javolution.text.Text.newPrimitive(), javolution.text.Text.subtext(), javolution.text.Text.Text(), javolution.text.Text.toLowerCase(), javolution.text.Text.toString(), and javolution.text.Text.toUpperCase().
_data
final char [] javolution.text.Text._data private
Holds the raw data (primitive) or null (composite).
Definition at line 90 of file Text.java.
Referenced by javolution.text.Text.append(), javolution.text.Text.charAt(), javolution.text.Text.concat(), javolution.text.Text.copy(), javolution.text.Text.getChars(), javolution.text.Text.getDepth(), javolution.text.Text.getNbrOfBranches(), javolution.text.Text.getNbrOfLeaves(), javolution.text.Text.indexOf(), javolution.text.Text.lastIndexOf(), javolution.text.Text.leftRotation(), javolution.text.Text.rightRotation(), javolution.text.Text.subtext(), javolution.text.Text.Text(), javolution.text.Text.toLowerCase(), javolution.text.Text.toString(), javolution.text.Text.toUpperCase(), and javolution.text.Text.valueOf().
_head
Text javolution.text.Text._head private
Holds the head block of character (composite).
Definition at line 100 of file Text.java.
Referenced by javolution.text.Text.append(), javolution.text.Text.charAt(), javolution.text.Text.concat(), javolution.text.Text.copy(), javolution.text.Text.getChars(), javolution.text.Text.getDepth(), javolution.text.Text.getNbrOfBranches(), javolution.text.Text.getNbrOfLeaves(), javolution.text.Text.indexOf(), javolution.text.Text.lastIndexOf(), javolution.text.Text.leftRotation(), javolution.text.Text.newComposite(), javolution.text.Text.rightRotation(), javolution.text.Text.subtext(), javolution.text.Text.Text(), javolution.text.Text.toLowerCase(), and javolution.text.Text.toUpperCase().
_tail
Text javolution.text.Text._tail private
Holds the tail block of character (composite).
Definition at line 105 of file Text.java.
Referenced by javolution.text.Text.append(), javolution.text.Text.charAt(), javolution.text.Text.concat(), javolution.text.Text.copy(), javolution.text.Text.getChars(), javolution.text.Text.getDepth(), javolution.text.Text.getNbrOfBranches(), javolution.text.Text.getNbrOfLeaves(), javolution.text.Text.indexOf(), javolution.text.Text.lastIndexOf(), javolution.text.Text.leftRotation(), javolution.text.Text.newComposite(), javolution.text.Text.rightRotation(), javolution.text.Text.subtext(), javolution.text.Text.Text(), javolution.text.Text.toLowerCase(), and javolution.text.Text.toUpperCase().
BLOCK_MASK
final int javolution.text.Text.BLOCK_MASK = ~(BLOCK_SIZE - 1) static private
Holds the mask used to ensure a block boundary cesures.
Definition at line 74 of file Text.java.
Referenced by javolution.text.Text.Text(), and javolution.text.Text.valueOf().
BLOCK_SIZE
final int javolution.text.Text.BLOCK_SIZE = 1 << 5 static private
Holds the default size for primitive blocks of characters.
Definition at line 69 of file Text.java.
Referenced by javolution.text.Text.append(), javolution.text.Text.concat(), javolution.text.Text.Text(), and javolution.text.Text.valueOf().
EMPTY
final Text javolution.text.Text.EMPTY = new Text("").intern() static
Holds an empty character sequence.
Definition at line 85 of file Text.java.
Referenced by javolution.text.Text.subtext().
FALSE
final Text javolution.text.Text.FALSE = new Text("false").intern() static private
Definition at line 232 of file Text.java.
Referenced by javolution.text.Text.valueOf().
INTERN
final FastMap<Text, Text> javolution.text.Text.INTERN static private
Initial value:
= new FastMap<Text, Text>()
            .shared()
Holds the texts interned in immortal memory.
Definition at line 79 of file Text.java.
Referenced by javolution.text.Text.intern().
serialVersionUID
final long javolution.text.Text.serialVersionUID = 0x600L static private
Definition at line 64 of file Text.java.
TRUE
final Text javolution.text.Text.TRUE = new Text("true").intern() static private
Definition at line 230 of file Text.java.
Referenced by javolution.text.Text.valueOf().
The documentation for this class was generated from the following file:
Text.java