Javolution 6.0.0 java: javolution.xml.ws.WebServiceClient Class Reference
javolution.xml.ws.WebServiceClient Class Reference abstract
Public Member Functions
WebServiceClient ()
WebServiceClient setAddress (String address)
void invoke () throws IOException, XMLStreamException
Static Public Attributes
static final String ENVELOPE_PREFIX = "env"
static final String ENVELOPE_URI = "http://schemas.xmlsoap.org/soap/envelope/"
Protected Member Functions
abstract void writeRequest (XMLObjectWriter out) throws XMLStreamException
void readResponse (XMLObjectReader in) throws XMLStreamException
Package Attributes
Object _url
Static Private Member Functions
static final CharSequence csq (Object string)
Private Attributes
final TextBuilder _buffer = new TextBuilder()
final AppendableWriter _out = new AppendableWriter()
final XMLObjectWriter _writer = new XMLObjectWriter()
final UTF8StreamWriter _utf8Writer = new UTF8StreamWriter()
final XMLObjectReader _reader = new XMLObjectReader()
Detailed Description
This class provides a simple web service client capable of leveraging
Javolution XML marshalling/unmarshalling.
Sub-classes may work from WSDL files, XMLFormat or directly with the XML streams (StAX). For example:[code] private static class HelloWorld extends WebServiceClient { protected void writeRequest(XMLObjectWriter out) throws XMLStreamException { XMLStreamWriter xml = out.getStreamWriter(); xml.writeDefaultNamespace("http://www.openuri.org/"); xml.writeEmptyElement("helloWorld"); // Operation name. } protected void readResponse(XMLObjectReader in) throws XMLStreamException { XMLStreamReader xml = in.getStreamReader(); xml.require(START_ELEMENT, "http://www.openuri.org/", "string"); xml.next(); // Move to character content. System.out.println(xml.getText()); } } WebServiceClient ws = new HelloWorld().setAddress("http://acme.com:80/HelloWorld.jws"); ws.invoke();
> Hello World! [/code]
Author
Jean-Marie Dautelle
Version
5.2, September 16, 2007
Definition at line 50 of file WebServiceClient.java.
Constructor & Destructor Documentation
WebServiceClient()
javolution.xml.ws.WebServiceClient.WebServiceClient ()
Default constructor (address not set).
Definition at line 70 of file WebServiceClient.java.
 {}
Member Function Documentation
csq()
static final CharSequence javolution.xml.ws.WebServiceClient.csq (Object string) static private
Definition at line 218 of file WebServiceClient.java.
{
         return (string instanceof CharSequence) ? (CharSequence) string : Text
                 .valueOf(string);
     }
Referenced by javolution.xml.ws.WebServiceClient.invoke().
invoke()
void javolution.xml.ws.WebServiceClient.invoke () throws IOException, XMLStreamException
Invokes the web service.
Definition at line 89 of file WebServiceClient.java.
{
         try {
             // Formats the request message (we cannot write directly to
             // the output stream because the http request requires the length.
             _out.setOutput(_buffer);
             _writer.setOutput(_out);
             final XMLStreamWriter xmlOut = _writer.getStreamWriter();
             xmlOut.setPrefix(csq(ENVELOPE_PREFIX), csq(ENVELOPE_URI));
             xmlOut.writeStartElement(csq(ENVELOPE_URI), csq("Envelope"));
             xmlOut.writeNamespace(csq(ENVELOPE_PREFIX), csq(ENVELOPE_URI));
             xmlOut.writeStartElement(csq(ENVELOPE_URI), csq("Header"));
             xmlOut.writeEndElement();
             xmlOut.writeStartElement(csq(ENVELOPE_URI), csq("Body"));
             writeRequest(_writer);
             _writer.close();
             // Sends the request.
             if (_url == null)
                 throw new IOException("URL not set");
             java.net.HttpURLConnection http = (java.net.HttpURLConnection) ((java.net.URL) _url)
                     .openConnection();
             http.setRequestProperty("Content-Length",
                     String.valueOf(_buffer.length()));
             http.setRequestProperty("Content-Type", "text/xml; charset=utf-8");
             // httpConn.setRequestProperty("SOAPAction", "");
             http.setRequestMethod("POST");
             http.setDoOutput(true);
             http.setDoInput(true);
             _utf8Writer.setOutput(http.getOutputStream());
             _utf8Writer.append(_buffer);
             _utf8Writer.close();
             // Reads the response.
             _reader.setInput(http.getInputStream());
             final XMLStreamReader xmlIn = _reader.getStreamReader();
             while (xmlIn.hasNext()) {
                 if ((xmlIn.next() == XMLStreamReader.START_ELEMENT)
                         && xmlIn.getLocalName().equals("Body")
                         && xmlIn.getNamespaceURI().equals(ENVELOPE_URI)) {
                     // Found body, position reader to next element.
                     xmlIn.next();
                     readResponse(_reader);
                     break;
                 }
             }
         } finally {
             _reader.close();
             _writer.reset();
             _out.reset();
             _buffer.clear();
             _utf8Writer.reset();
             _reader.reset();
         }
     }
References javolution.xml.ws.WebServiceClient._buffer, javolution.xml.ws.WebServiceClient._out, javolution.xml.ws.WebServiceClient._reader, javolution.xml.ws.WebServiceClient._url, javolution.xml.ws.WebServiceClient._utf8Writer, javolution.xml.ws.WebServiceClient._writer, javolution.text.TextBuilder.clear(), javolution.xml.XMLObjectReader.close(), javolution.xml.XMLObjectWriter.close(), javolution.io.UTF8StreamWriter.close(), javolution.xml.ws.WebServiceClient.csq(), javolution.xml.ws.WebServiceClient.ENVELOPE_PREFIX, javolution.xml.ws.WebServiceClient.ENVELOPE_URI, javolution.text.CharArray.equals(), javolution.xml.stream.XMLStreamReader.getLocalName(), javolution.xml.stream.XMLStreamReader.getNamespaceURI(), javolution.xml.XMLObjectReader.getStreamReader(), javolution.xml.XMLObjectWriter.getStreamWriter(), javolution.xml.stream.XMLStreamReader.hasNext(), javolution.text.TextBuilder.length(), javolution.xml.stream.XMLStreamReader.next(), javolution.xml.ws.WebServiceClient.readResponse(), javolution.io.AppendableWriter.reset(), javolution.xml.XMLObjectReader.reset(), javolution.xml.XMLObjectWriter.reset(), javolution.io.UTF8StreamWriter.reset(), javolution.xml.XMLObjectReader.setInput(), javolution.io.AppendableWriter.setOutput(), javolution.io.UTF8StreamWriter.setOutput(), javolution.xml.XMLObjectWriter.setOutput(), javolution.xml.stream.XMLStreamWriter.setPrefix(), javolution.xml.stream.XMLStreamConstants.START_ELEMENT, javolution.xml.stream.XMLStreamWriter.writeEndElement(), javolution.xml.stream.XMLStreamWriter.writeNamespace(), javolution.xml.ws.WebServiceClient.writeRequest(), and javolution.xml.stream.XMLStreamWriter.writeStartElement().
readResponse()
void javolution.xml.ws.WebServiceClient.readResponse (XMLObjectReader in) throws XMLStreamException protected
Reads the web service response (SOAP body). The default implementation writes the body XML events to System.out.
Parameters
in the XML object reader.
Definition at line 171 of file WebServiceClient.java.
{
         final XMLStreamReader xml = in.getStreamReader();
         while (xml.hasNext()) {
             switch (xml.next()) {
                 case XMLStreamReader.START_DOCUMENT:
                     System.out.println("Start Document");
                     break;
                 case XMLStreamReader.END_DOCUMENT:
                     System.out.println("End Document.");
                     break;
                 case XMLStreamReader.START_ELEMENT:
                     System.out.println("Start Element: " + xml.getLocalName()
                             + "(" + xml.getNamespaceURI() + ")");
                     for (int i = 0, n = xml.getAttributeCount(); i < n; i++) {
                         System.out.println("   Attribute: "
                                 + xml.getAttributeLocalName(i) + "("
                                 + xml.getAttributeNamespace(i) + "), Value: "
                                 + xml.getAttributeValue(i));
                     }
                     break;
                 case XMLStreamReader.END_ELEMENT:
                     if (xml.getLocalName().equals("Body")
                             && xml.getNamespaceURI().equals(ENVELOPE_URI))
                         return; // End body.
                     System.out.println("End Element: " + xml.getLocalName()
                             + "(" + xml.getNamespaceURI() + ")");
                     break;
                 case XMLStreamReader.CHARACTERS:
                     System.out.println("Characters: " + xml.getText());
                     break;
                 case XMLStreamReader.CDATA:
                     System.out.println("CDATA: " + xml.getText());
                     break;
                 case XMLStreamReader.COMMENT:
                     System.out.println("Comment: " + xml.getText());
                     break;
                 case XMLStreamReader.SPACE:
                     System.out.println("Space");
                     break;
                 default:
                     System.out.println(xml);
             }
         }
     }
References javolution.xml.stream.XMLStreamConstants.CDATA, javolution.xml.stream.XMLStreamConstants.CHARACTERS, javolution.xml.stream.XMLStreamConstants.COMMENT, javolution.xml.stream.XMLStreamConstants.END_DOCUMENT, javolution.xml.stream.XMLStreamConstants.END_ELEMENT, javolution.xml.ws.WebServiceClient.ENVELOPE_URI, javolution.text.CharArray.equals(), javolution.xml.stream.XMLStreamReader.getAttributeCount(), javolution.xml.stream.XMLStreamReader.getAttributeLocalName(), javolution.xml.stream.XMLStreamReader.getAttributeNamespace(), javolution.xml.stream.XMLStreamReader.getAttributeValue(), javolution.xml.stream.XMLStreamReader.getLocalName(), javolution.xml.stream.XMLStreamReader.getNamespaceURI(), javolution.xml.stream.XMLStreamReader.getText(), javolution.xml.stream.XMLStreamReader.hasNext(), javolution.xml.stream.XMLStreamReader.next(), javolution.xml.stream.XMLStreamConstants.SPACE, javolution.xml.stream.XMLStreamConstants.START_DOCUMENT, and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
Referenced by javolution.xml.ws.WebServiceClient.invoke().
setAddress()
WebServiceClient javolution.xml.ws.WebServiceClient.setAddress (String address)
Sets the address of this web service.
Parameters
address the service full address.
Definition at line 77 of file WebServiceClient.java.
{
         try {
             _url = new java.net.URL(address);
         } catch (java.net.MalformedURLException e) {
             throw new IllegalArgumentException("Malformed URL: " + address);
         }
         return this;
     }
References javolution.xml.ws.WebServiceClient._url.
writeRequest()
abstract void javolution.xml.ws.WebServiceClient.writeRequest (XMLObjectWriter out) throws XMLStreamException abstract protected
Writes the web service request (SOAP body).
Parameters
out the XML object writer.
Referenced by javolution.xml.ws.WebServiceClient.invoke().
Member Data Documentation
_buffer
final TextBuilder javolution.xml.ws.WebServiceClient._buffer = new TextBuilder() private
Definition at line 149 of file WebServiceClient.java.
Referenced by javolution.xml.ws.WebServiceClient.invoke().
_out
final AppendableWriter javolution.xml.ws.WebServiceClient._out = new AppendableWriter() private
Definition at line 150 of file WebServiceClient.java.
Referenced by javolution.xml.ws.WebServiceClient.invoke().
_reader
final XMLObjectReader javolution.xml.ws.WebServiceClient._reader = new XMLObjectReader() private
Definition at line 153 of file WebServiceClient.java.
Referenced by javolution.xml.ws.WebServiceClient.invoke().
_url
Object javolution.xml.ws.WebServiceClient._url package
Holds the URL (J2SE).
Definition at line 65 of file WebServiceClient.java.
Referenced by javolution.xml.ws.WebServiceClient.invoke(), and javolution.xml.ws.WebServiceClient.setAddress().
_utf8Writer
final UTF8StreamWriter javolution.xml.ws.WebServiceClient._utf8Writer = new UTF8StreamWriter() private
Definition at line 152 of file WebServiceClient.java.
Referenced by javolution.xml.ws.WebServiceClient.invoke().
_writer
final XMLObjectWriter javolution.xml.ws.WebServiceClient._writer = new XMLObjectWriter() private
Definition at line 151 of file WebServiceClient.java.
Referenced by javolution.xml.ws.WebServiceClient.invoke().
ENVELOPE_PREFIX
final String javolution.xml.ws.WebServiceClient.ENVELOPE_PREFIX = "env" static
Holds standard SOAP envelope prefix.
Definition at line 55 of file WebServiceClient.java.
Referenced by javolution.xml.ws.WebServiceClient.invoke().
ENVELOPE_URI
final String javolution.xml.ws.WebServiceClient.ENVELOPE_URI = "http://schemas.xmlsoap.org/soap/envelope/" static
Holds standard SOAP envelope namespace.
Definition at line 60 of file WebServiceClient.java.
Referenced by javolution.xml.ws.WebServiceClient.invoke(), and javolution.xml.ws.WebServiceClient.readResponse().
The documentation for this class was generated from the following file:
WebServiceClient.java