Javolution 6.0.0 java: javolution.util.internal.collection.ReadWriteLockImpl.WriteLock Class Reference
javolution.util.internal.collection.ReadWriteLockImpl.WriteLock Class Reference
Public Member Functions
void lock ()
void lockInterruptibly () throws InterruptedException
Condition newCondition ()
boolean tryLock ()
boolean tryLock (long time, TimeUnit unit) throws InterruptedException
void unlock ()
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
Write-Lock Implementation.
Definition at line 75 of file ReadWriteLockImpl.java.
Member Function Documentation
lock()
void javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.lock ()
Definition at line 79 of file ReadWriteLockImpl.java.
{
             try {
                 lockInterruptibly();
             } catch (java.lang.InterruptedException e) {}
         }
References javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.lockInterruptibly().
Referenced by javolution.util.internal.table.SharedTableImpl< E >.add(), javolution.util.internal.collection.SharedCollectionImpl< E >.add(), javolution.util.internal.table.SharedTableImpl< E >.addAll(), javolution.util.internal.collection.SharedCollectionImpl< E >.addAll(), javolution.util.internal.table.SharedTableImpl< E >.addFirst(), javolution.util.internal.table.sorted.SharedSortedTableImpl< E >.addIfAbsent(), javolution.util.internal.table.SharedTableImpl< E >.addLast(), javolution.util.internal.map.SharedMapImpl< K, V >.clear(), javolution.util.internal.collection.SharedCollectionImpl< E >.clear(), javolution.util.internal.table.SharedTableImpl< E >.offerFirst(), javolution.util.internal.table.SharedTableImpl< E >.offerLast(), javolution.util.internal.table.SharedTableImpl< E >.pollFirst(), javolution.util.internal.table.SharedTableImpl< E >.pollLast(), javolution.util.internal.map.SharedMapImpl< K, V >.put(), javolution.util.internal.map.SharedMapImpl< K, V >.putAll(), javolution.util.internal.map.SharedMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.SharedMapImpl< K, V >.remove(), javolution.util.internal.collection.SharedCollectionImpl< E >.remove(), javolution.util.internal.table.SharedTableImpl< E >.remove(), javolution.util.internal.collection.SharedCollectionImpl< E >.removeAll(), javolution.util.internal.table.SharedTableImpl< E >.removeFirst(), javolution.util.internal.table.SharedTableImpl< E >.removeFirstOccurrence(), javolution.util.internal.table.SharedTableImpl< E >.removeLast(), javolution.util.internal.table.SharedTableImpl< E >.removeLastOccurrence(), javolution.util.internal.map.SharedMapImpl< K, V >.replace(), javolution.util.internal.collection.SharedCollectionImpl< E >.retainAll(), and javolution.util.internal.table.SharedTableImpl< E >.set().
lockInterruptibly()
void javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.lockInterruptibly () throws InterruptedException
Definition at line 86 of file ReadWriteLockImpl.java.
{
             synchronized (ReadWriteLockImpl.this) {
                 waitingWriters++;
                 while (givenLocks != 0) {
                     ReadWriteLockImpl.this.wait();
                 }
                 waitingWriters--;
                 writerThread = Thread.currentThread();
             }
         }
References javolution.util.internal.collection.ReadWriteLockImpl.givenLocks, javolution.util.internal.collection.ReadWriteLockImpl.waitingWriters, and javolution.util.internal.collection.ReadWriteLockImpl.writerThread.
Referenced by javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.lock().
newCondition()
Condition javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.newCondition ()
Definition at line 98 of file ReadWriteLockImpl.java.
{
             throw new UnsupportedOperationException();
         }
tryLock() [1/2]
boolean javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.tryLock ()
Definition at line 103 of file ReadWriteLockImpl.java.
{
             throw new UnsupportedOperationException();
         }
tryLock() [2/2]
boolean javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.tryLock (long time, TimeUnit unit) throws InterruptedException
Definition at line 108 of file ReadWriteLockImpl.java.
{
             throw new UnsupportedOperationException();
         }
unlock()
void javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.unlock ()
Definition at line 114 of file ReadWriteLockImpl.java.
{
             synchronized (ReadWriteLockImpl.this) {
                 writerThread = null;
                 ReadWriteLockImpl.this.notifyAll();
             }
         }
References javolution.util.internal.collection.ReadWriteLockImpl.writerThread.
Referenced by javolution.util.internal.table.SharedTableImpl< E >.add(), javolution.util.internal.collection.SharedCollectionImpl< E >.add(), javolution.util.internal.table.SharedTableImpl< E >.addAll(), javolution.util.internal.collection.SharedCollectionImpl< E >.addAll(), javolution.util.internal.table.SharedTableImpl< E >.addFirst(), javolution.util.internal.table.sorted.SharedSortedTableImpl< E >.addIfAbsent(), javolution.util.internal.table.SharedTableImpl< E >.addLast(), javolution.util.internal.map.SharedMapImpl< K, V >.clear(), javolution.util.internal.collection.SharedCollectionImpl< E >.clear(), javolution.util.internal.table.SharedTableImpl< E >.offerFirst(), javolution.util.internal.table.SharedTableImpl< E >.offerLast(), javolution.util.internal.table.SharedTableImpl< E >.pollFirst(), javolution.util.internal.table.SharedTableImpl< E >.pollLast(), javolution.util.internal.map.SharedMapImpl< K, V >.put(), javolution.util.internal.map.SharedMapImpl< K, V >.putAll(), javolution.util.internal.map.SharedMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.SharedMapImpl< K, V >.remove(), javolution.util.internal.collection.SharedCollectionImpl< E >.remove(), javolution.util.internal.table.SharedTableImpl< E >.remove(), javolution.util.internal.collection.SharedCollectionImpl< E >.removeAll(), javolution.util.internal.table.SharedTableImpl< E >.removeFirst(), javolution.util.internal.table.SharedTableImpl< E >.removeFirstOccurrence(), javolution.util.internal.table.SharedTableImpl< E >.removeLast(), javolution.util.internal.table.SharedTableImpl< E >.removeLastOccurrence(), javolution.util.internal.map.SharedMapImpl< K, V >.replace(), javolution.util.internal.collection.SharedCollectionImpl< E >.retainAll(), and javolution.util.internal.table.SharedTableImpl< E >.set().
Member Data Documentation
serialVersionUID
final long javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.serialVersionUID = 0x600L static private
Definition at line 76 of file ReadWriteLockImpl.java.
The documentation for this class was generated from the following file:
ReadWriteLockImpl.java