Javolution 6.0.0 java: javolution.util.internal.set.sorted.SortedSetView< E > Class Template Reference
javolution.util.internal.set.sorted.SortedSetView< E > Class Template Reference abstract
Public Member Functions
SortedSetView (SortedSetService< E > target)
abstract E first ()
SortedSetService< E > headSet (E toElement)
abstract E last ()
SortedSetService< E > subSet (E fromElement, E toElement)
SortedSetService< E > tailSet (E fromElement)
SortedSetService< E > threadSafe ()
abstract int size ()
abstract boolean contains (Object o)
abstract boolean remove (Object o)
abstract boolean add (E element)
boolean addAll (Collection<? extends E > c)
FastCollection< E > addAll (E... elements)
FastCollection< E > addAll (FastCollection<? extends E > that)
void clear ()
CollectionView< E > clone ()
abstract Equality<? super E > comparator ()
boolean containsAll (Collection<?> c)
boolean equals (Object o)
int hashCode ()
boolean isEmpty ()
abstract Iterator< E > iterator ()
void perform (Consumer< CollectionService< E >> action, CollectionService< E > view)
void perform (Consumer<? extends Collection< E >> action)
void perform (Consumer< T > action, T part)
boolean removeAll (Collection<?> c)
boolean retainAll (Collection<?> c)
CollectionService< E >[] split (int n)
Object[] toArray ()
void update (Consumer< CollectionService< E >> action, CollectionService< E > view)
void update (Consumer<? extends Collection< E >> action)
void update (Consumer< T > action, T part)
FastCollection< E > atomic ()
FastCollection< E > shared ()
FastCollection< E > parallel ()
FastCollection< E > sequential ()
FastCollection< E > unmodifiable ()
FastCollection< E > filtered (Predicate<? super E > filter)
FastCollection< E > sorted ()
FastCollection< E > sorted (Comparator<? super E > cmp)
FastCollection< E > reversed ()
FastCollection< E > distinct ()
void forEach (final Consumer<? super E > consumer)
boolean removeIf (final Predicate<? super E > filter)
E reduce (Reducer< E > reducer)
E min ()
E max ()
String toString ()
Protected Member Functions
SortedSetService< E > target ()
CollectionService< E > service ()
Static Protected Member Functions
static< E > CollectionService< E > serviceOf (FastCollection< E > collection)
Package Functions
public< T > T[] toArray (T[] a)
public< R > FastCollection< R > mapped (Function<? super E, ? extends R > function)
public< T extends E > T any (Class< T > type)
public< T extends Collection< E > > Immutable< T > toImmutable ()
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
Sorted Set view implementation; can be used as root class for implementations if target is
null
.
Definition at line 18 of file SortedSetView.java.
Constructor & Destructor Documentation
SortedSetView()
javolution.util.internal.set.sorted.SortedSetView< E >.SortedSetView (SortedSetService< E > target)
The view constructor or root class constructor if target is
null
.
Definition at line 25 of file SortedSetView.java.
{
         super(target);
     }
References javolution.util.internal.set.sorted.SortedSetView< E >.target().
Member Function Documentation
add()
abstract boolean javolution.util.internal.collection.CollectionView< E >.add (E element) abstract inherited
Adds the specified element to this collection
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.FilteredCollectionImpl< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.DistinctCollectionImpl< E >, javolution.util.internal.table.FastTableImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, javolution.util.internal.table.SubTableImpl< E >, javolution.util.internal.collection.UnmodifiableCollectionImpl< E >, javolution.util.internal.table.sorted.FastSortedTableImpl< E >, javolution.util.internal.table.UnmodifiableTableImpl< E >, javolution.util.internal.collection.SortedCollectionImpl< E >, javolution.util.internal.set.sorted.SubSortedSetImpl< E >, javolution.util.internal.table.ReversedTableImpl< E >, javolution.util.internal.collection.ReversedCollectionImpl< E >, javolution.util.internal.collection.ParallelCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Referenced by javolution.util.internal.collection.CollectionView< R >.addAll().
addAll() [1/3]
boolean javolution.util.internal.collection.CollectionView< E >.addAll (Collection<? extends E > that) inherited
Adds all the specified elements to this collection.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 46 of file CollectionView.java.
{
         boolean changed = false;
         Iterator<? extends E> it = c.iterator();
         while (it.hasNext()) {
             if (add(it.next())) changed = true;
         }
         return changed;
     }
addAll() [2/3]
FastCollection<E> javolution.util.FastCollection< E >.addAll (E... elements) inherited
Returns this collection with the specified element added.
Parameters
elements the elements to be added.
Returns
this
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSortedSet< E >, javolution.util.FastSet< E >, and javolution.util.FastSortedTable< E >.
Definition at line 552 of file FastCollection.java.
{
         for (E e : elements) {
             add(e);
         }
         return this;
     }
addAll() [3/3]
FastCollection<E> javolution.util.FastCollection< E >.addAll (FastCollection<? extends E > that) inherited
Returns this collection with the specified collection's elements added in sequence.
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSortedSet< E >, javolution.util.FastSet< E >, and javolution.util.FastSortedTable< E >.
Definition at line 564 of file FastCollection.java.
{
         addAll((Collection<? extends E>) that);
         return this;
     }
any()
public<T extends E> T javolution.util.FastCollection< E >.any (Class< T > type) package inherited
Returns any non-null element of the specified type (convenience method).
Parameters
type the element type searched for.
Returns
reduce(Reducers.any(type))
See also
Reducers::any
Definition at line 515 of file FastCollection.java.
{
         return (T) reduce((Reducer<E>) Reducers.any(type));
     }
References javolution.util.function.Reducers.any().
atomic()
FastCollection<E> javolution.util.FastCollection< E >.atomic () inherited
Returns an atomic view over this collection. All operations that write or access multiple elements in the collection (such as addAll(), retainAll()) are atomic. Iterators on atomic collections are thread-safe (no ConcurrentModificationException possible).
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSet< E >, javolution.util.FastSortedTable< E >, and javolution.util.FastSortedSet< E >.
Definition at line 187 of file FastCollection.java.
{
         return new AtomicCollectionImpl<E>(service());
     }
clear()
void javolution.util.internal.collection.CollectionView< E >.clear () inherited
Removes all elements from this collection.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.table.FastTableImpl< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.bitset.BitSetServiceImpl, javolution.util.internal.collection.AtomicCollectionImpl< E >, javolution.util.internal.collection.SortedCollectionImpl< E >, javolution.util.internal.collection.DistinctCollectionImpl< E >, javolution.util.internal.table.SubTableImpl< E >, javolution.util.internal.collection.ReversedCollectionImpl< E >, javolution.util.internal.table.ReversedTableImpl< E >, javolution.util.internal.table.TableView< E >, javolution.util.internal.collection.UnmodifiableCollectionImpl< E >, javolution.util.internal.table.UnmodifiableTableImpl< E >, javolution.util.internal.collection.ParallelCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Definition at line 56 of file CollectionView.java.
{
         Iterator<? extends E> it = iterator();
         while (it.hasNext()) {
             it.next();
             it.remove();
         }
     }
clone()
CollectionView<E> javolution.util.internal.collection.CollectionView< E >.clone () inherited
Returns a copy of this collection; updates of the copy should not impact the original.
Implements javolution.util.service.CollectionService< E >.
Reimplemented in javolution.util.internal.table.FastTableImpl< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 66 of file CollectionView.java.
{
         try {
             CollectionView<E> copy = (CollectionView<E>) super.clone();
             if (target != null) { // Not a root class.
                 copy.target = target.clone();
             }
             return copy;
         } catch (CloneNotSupportedException e) {
             throw new Error("Should not happen since target is cloneable");
         }
     }
Referenced by javolution.util.internal.collection.CollectionView< R >.clone(), and javolution.util.internal.collection.CollectionView< R >.split().
comparator()
abstract Equality<? super E> javolution.util.internal.collection.CollectionView< E >.comparator () abstract inherited
Returns the comparator uses by this collection for equality and/or ordering if this collection is sorted.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.bitset.BitSetServiceImpl, javolution.util.internal.table.FastTableImpl< E >, javolution.util.internal.table.SubTableImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, javolution.util.internal.collection.SortedCollectionImpl< E >, javolution.util.internal.set.sorted.SubSortedSetImpl< E >, javolution.util.internal.collection.FilteredCollectionImpl< E >, javolution.util.internal.table.UnmodifiableTableImpl< E >, javolution.util.internal.collection.DistinctCollectionImpl< E >, javolution.util.internal.map.MapView< K, V >.EntrySet, javolution.util.internal.table.ReversedTableImpl< E >, javolution.util.internal.collection.ReversedCollectionImpl< E >, javolution.util.internal.collection.UnmodifiableCollectionImpl< E >, javolution.util.internal.collection.ParallelCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Referenced by javolution.util.internal.collection.CollectionView< R >.contains(), javolution.util.internal.collection.CollectionView< R >.equals(), javolution.util.internal.collection.CollectionView< R >.hashCode(), javolution.util.internal.table.sorted.SortedTableView< E >.indexOf(), javolution.util.internal.table.TableView< E >.indexOf(), javolution.util.internal.table.sorted.SortedTableView< E >.lastIndexOf(), javolution.util.internal.table.TableView< E >.lastIndexOf(), and javolution.util.internal.collection.CollectionView< R >.remove().
contains()
abstract boolean javolution.util.internal.set.SetView< E >.contains (Object searched) abstract inherited
Indicates if this collection contains the specified element.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Reimplemented in javolution.util.internal.set.sorted.SubSortedSetImpl< E >, javolution.util.internal.map.MapView< K, V >.EntrySet, and javolution.util.internal.bitset.BitSetServiceImpl.
containsAll()
boolean javolution.util.internal.collection.CollectionView< E >.containsAll (Collection<?> that) inherited
Indicates if this collection contains all the specified elements.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 93 of file CollectionView.java.
{
         for (Object e : c) {
             if (!contains(e)) return false;
         }
         return true;
     }
Referenced by javolution.util.internal.collection.CollectionView< R >.equals().
distinct()
FastCollection<E> javolution.util.FastCollection< E >.distinct () inherited
Returns a view exposing only distinct elements (it does not iterate twice over the same elements). Adding elements already in the collection through this view has no effect. If this collection is initially empty, using a distinct view to add new elements ensures that this collection has no duplicate.
Definition at line 293 of file FastCollection.java.
{
         return new DistinctCollectionImpl<E>(service());
     }
equals()
boolean javolution.util.internal.collection.CollectionView< E >.equals (Object obj) inherited
Compares the specified object with this collection for equality. This method follows the Collection#equals(Object) specification if this collection comparator is Equalities#STANDARD (default). Otherwise, only collections using the same comparator can be considered equals.
Parameters
obj the object to be compared for equality with this collection
Returns
true if both collections are considered equals; false otherwise.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 102 of file CollectionView.java.
{
         // Follow Collection.equals specification if this comparator is standard.
         if (this == o) return true;
         // Check comparators consistency.
         if (o instanceof CollectionService) {
             if (!comparator().equals(((CollectionService<E>) o).comparator())) return false; // Different comparators.
         } else {
             if (!comparator().equals(Equalities.STANDARD)) return false;
         }
         // Collection.equals contract.
         if (this instanceof Set) {
             if (!(o instanceof Set)) return false;
             Set<E> set = (Set<E>) o;
             return (size() == set.size()) && containsAll(set);
         } else if (this instanceof List) {
             if (!(o instanceof List)) return false;
             List<E> list = (List<E>) o;
             if (size() != list.size()) return false; // Short-cut.
             Equality<? super E> cmp = comparator();
             Iterator<E> it1 = this.iterator();
             Iterator<E> it2 = list.iterator();
             while (it1.hasNext()) {
                 if (!it2.hasNext()) return false;
                 if (!cmp.areEqual(it1.next(), it2.next())) return false;
             }
             if (it2.hasNext()) return false;
             return true;
         } else {
             return false;
         }
     }
Referenced by javolution.util.internal.collection.CollectionView< R >.equals().
filtered()
FastCollection<E> javolution.util.FastCollection< E >.filtered (Predicate<? super E > filter) inherited
Returns a view exposing only the elements matching the specified filter. Adding elements not matching the specified filter has no effect. If this collection is initially empty, using a filtered view to add new elements ensure that this collection has only elements satisfying the filter predicate.
Reimplemented in javolution.util.FastSet< E >.
Definition at line 250 of file FastCollection.java.
{
         return new FilteredCollectionImpl<E>(service(), filter);
     }
first()
abstract E javolution.util.internal.set.sorted.SortedSetView< E >.first () abstract
Reimplemented in javolution.util.internal.set.sorted.SubSortedSetImpl< E >.
forEach()
void javolution.util.FastCollection< E >.forEach (final Consumer<? super E > consumer) inherited
Iterates over all this collection elements applying the specified consumer (convenience method). Iterations are performed concurrently if the collection is parallel.
Parameters
consumer the functional consumer applied to the collection elements.
Definition at line 346 of file FastCollection.java.
{
         perform(new Consumer<Collection<E>>() {
             public void accept(Collection<E> view) {
                 Iterator<E> it = view.iterator();
                 while (it.hasNext()) {
                     consumer.accept(it.next());
                 }
             }
         });
     }
References javolution.util.function.Consumer< T >.accept().
hashCode()
int javolution.util.internal.collection.CollectionView< E >.hashCode () inherited
Returns the hash code of this collection. This method follows the Collection#hashCode() specification if this collection comparator is Equalities#STANDARD.
Returns
this collection hash code.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 135 of file CollectionView.java.
{
         // Follow Collection.equals specification if this comparator is standard.
         Equality<? super E> cmp = comparator();
         Iterator<E> it = this.iterator();
         int hash = 0;
         if (this instanceof Set) {
             while (it.hasNext()) {
                 hash += cmp.hashCodeOf(it.next());
             }
         } else if (this instanceof List) {
             while (it.hasNext()) {
                 hash += 31 * hash + cmp.hashCodeOf(it.next());
             }
         } else {
             hash = super.hashCode();
         }
         return hash;
     }
headSet()
SortedSetService<E> javolution.util.internal.set.sorted.SortedSetView< E >.headSet (E toElement)
Implements javolution.util.service.SortedSetService< E >.
Definition at line 33 of file SortedSetView.java.
{
         return new SubSortedSetImpl<E>(this, null, toElement);
     }
isEmpty()
boolean javolution.util.internal.collection.CollectionView< E >.isEmpty () inherited
Indicates if this collection is empty.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, javolution.util.internal.set.sorted.SubSortedSetImpl< E >, javolution.util.internal.table.TableView< E >, javolution.util.internal.collection.SortedCollectionImpl< E >, javolution.util.internal.map.MapView< K, V >.EntrySet, javolution.util.internal.collection.DistinctCollectionImpl< E >, javolution.util.internal.collection.ReversedCollectionImpl< E >, javolution.util.internal.collection.UnmodifiableCollectionImpl< E >, javolution.util.internal.collection.ParallelCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Definition at line 155 of file CollectionView.java.
{
         return iterator().hasNext();
     }
iterator()
abstract Iterator<E> javolution.util.internal.collection.CollectionView< E >.iterator () abstract inherited
Returns an iterator over this collection elements. For shared/atomic collections the iterator is immune to concurrent modifications. In other words the elements iterated over may or may not reflect the current state of the collection.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.bitset.BitSetServiceImpl, javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.table.FastTableImpl< E >, javolution.util.internal.table.SharedTableImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, javolution.util.internal.set.sorted.SubSortedSetImpl< E >, javolution.util.internal.table.TableView< E >, javolution.util.internal.collection.SortedCollectionImpl< E >, javolution.util.internal.map.MapView< K, V >.EntrySet, javolution.util.internal.collection.DistinctCollectionImpl< E >, javolution.util.internal.collection.FilteredCollectionImpl< E >, javolution.util.internal.table.AtomicTableImpl< E >, javolution.util.internal.collection.ReversedCollectionImpl< E >, javolution.util.internal.collection.UnmodifiableCollectionImpl< E >, javolution.util.internal.collection.ParallelCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Referenced by javolution.util.internal.collection.CollectionView< R >.clear(), javolution.util.internal.collection.CollectionView< R >.contains(), javolution.util.internal.collection.CollectionView< R >.equals(), javolution.util.internal.collection.CollectionView< R >.hashCode(), javolution.util.internal.collection.CollectionView< R >.isEmpty(), javolution.util.internal.collection.CollectionView< R >.remove(), javolution.util.internal.collection.CollectionView< R >.removeAll(), javolution.util.internal.collection.CollectionView< R >.retainAll(), javolution.util.internal.collection.CollectionView< R >.size(), and javolution.util.internal.collection.CollectionView< R >.toArray().
last()
abstract E javolution.util.internal.set.sorted.SortedSetView< E >.last () abstract
Reimplemented in javolution.util.internal.set.sorted.SubSortedSetImpl< E >.
mapped()
public<R> FastCollection<R> javolution.util.FastCollection< E >.mapped (Function<? super E, ? extends R > function) package inherited
Returns a view exposing elements through the specified mapping function. The returned view does not allow new elements to be added.
Definition at line 258 of file FastCollection.java.
{
         return new MappedCollectionImpl<E, R>(service(), function);
     }
Referenced by javolution.xml.internal.stream.EntitiesImpl.setEntitiesMapping().
max()
E javolution.util.FastCollection< E >.max () inherited
Returns the largest element of this collection using this collection comparator (convenience method). Returns
null
if this collection is empty.
Returns
reduce(Reducers.max(comparator()))
See also
Reducers::max
Definition at line 541 of file FastCollection.java.
                    {
         return reduce(Reducers.max(comparator()));
     }
References javolution.util.function.Reducers.max().
min()
E javolution.util.FastCollection< E >.min () inherited
Returns the smallest element of this collection using this collection comparator (convenience method). Returns
null
if this collection is empty.
Returns
reduce(Reducers.min(comparator()))
See also
Reducers::min
Definition at line 528 of file FastCollection.java.
                    {
         return reduce(Reducers.min(comparator()));
     }
References javolution.util.function.Reducers.min().
parallel()
FastCollection<E> javolution.util.FastCollection< E >.parallel () inherited
Returns a parallel collection. Parallel collections affect only closure-based operations, all others operations behaving the same. Parallel actions are performed concurrently using Javolution ConcurrentContext. The number of parallel views is derived from the context concurrency (
number of parallel views = concurrency + 1
). Parallel views do not require this collection to be thread-safe (internal synchronization).
See also
#perform(Consumer)
#update(Consumer)
#forEach(Consumer)
#removeIf(Predicate)
#reduce(Reducer)
Definition at line 222 of file FastCollection.java.
{
         return new ParallelCollectionImpl<E>(service());
     }
perform() [1/3]
void javolution.util.internal.collection.CollectionView< E >.perform (Consumer< CollectionService< E >> action, CollectionService< E > view) inherited
Reimplemented in javolution.util.internal.collection.ParallelCollectionImpl< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Definition at line 163 of file CollectionView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
perform() [2/3]
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
perform() [3/3]
void javolution.util.FastCollection< E >.perform (Consumer<? extends Collection< E >> action) inherited
Executes the specified read-only action on this collection. That logic may be performed concurrently on sub-collections if this collection is parallel.
Parameters
action the read-only action.
Exceptions
UnsupportedOperationException if the action tries to update this collection and this collection is thread-safe.
ClassCastException if the action type is not compatible with this collection (e.g. action on set and this is a list).
See also
#update(Consumer)
Definition at line 315 of file FastCollection.java.
{
         service().perform((Consumer<CollectionService<E>>) action, service());
     }
reduce()
E javolution.util.FastCollection< E >.reduce (Reducer< E > reducer) inherited
Performs a reduction of the elements of this collection using the specified reducer. This may not involve iterating over all the collection elements, for example the reducers: Reducers#any, Reducers#and and Reducers#or may stop iterating early. Reduction is performed concurrently if this collection is parallel.
Parameters
reducer the collection reducer.
Returns
the reduction result.
Definition at line 396 of file FastCollection.java.
{
         perform(reducer);
         return reducer.get();
     }
remove()
abstract boolean javolution.util.internal.set.SetView< E >.remove (Object searched) abstract inherited
Removes the specified element from this collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Reimplemented in javolution.util.internal.set.sorted.SubSortedSetImpl< E >, javolution.util.internal.map.MapView< K, V >.EntrySet, and javolution.util.internal.bitset.BitSetServiceImpl.
removeAll()
boolean javolution.util.internal.collection.CollectionView< E >.removeAll (Collection<?> that) inherited
Removes all the specified element from this collection.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 186 of file CollectionView.java.
{
         boolean changed = false;
         Iterator<? extends E> it = iterator();
         while (it.hasNext()) {
             if (c.contains(it.next())) {
                 it.remove();
                 changed = true;
             }
         }
         return changed;
     }
removeIf()
boolean javolution.util.FastCollection< E >.removeIf (final Predicate<? super E > filter) inherited
Removes from this collection all the elements matching the specified functional predicate (convenience method). Removals are performed concurrently if this collection is parallel and atomically if this collection is atomic.
Parameters
filter a predicate returning
true
for elements to be removed.
Returns
true
if at least one element has been removed;
false
otherwise.
Definition at line 368 of file FastCollection.java.
{
         final boolean[] removed = new boolean[1];
         update(new Consumer<Collection<E>>() {
             public void accept(Collection<E> view) {
                 Iterator<E> it = view.iterator();
                 while (it.hasNext()) {
                     if (filter.test(it.next())) {
                         it.remove(); // Ok mutable iteration.
                         removed[0] = true;
                     }
                 }
             }
         });
         return removed[0];
     }
retainAll()
boolean javolution.util.internal.collection.CollectionView< E >.retainAll (Collection<?> that) inherited
Removes all the elements except those in the specified collection.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 199 of file CollectionView.java.
{
         boolean changed = false;
         Iterator<? extends E> it = iterator();
         while (it.hasNext()) {
             if (!c.contains(it.next())) {
                 it.remove();
                 changed = true;
             }
         }
         return changed;
     }
reversed()
FastCollection<E> javolution.util.FastCollection< E >.reversed () inherited
Returns a view exposing elements in reverse iterative order.
Reimplemented in javolution.util.FastTable< E >.
Definition at line 282 of file FastCollection.java.
{
         return new ReversedCollectionImpl<E>(service());
     }
sequential()
FastCollection<E> javolution.util.FastCollection< E >.sequential () inherited
Returns a sequential view of this collection. Using this view, all closure-based iterations are performed sequentially.
Definition at line 230 of file FastCollection.java.
{
         return new SequentialCollectionImpl<E>(service());
     }
service()
CollectionService<E> javolution.util.internal.collection.CollectionView< E >.service () protected inherited
Returns the service implementation of this collection (for sub-classes).
Reimplemented from javolution.util.FastCollection< E >.
Definition at line 274 of file CollectionView.java.
{
         return this;
     }
serviceOf()
static <E> CollectionService<E> javolution.util.FastCollection< E >.serviceOf (FastCollection< E > collection) static protected inherited
Returns the service implementation of any fast collection (for sub-classes).
Definition at line 647 of file FastCollection.java.
{
         return collection.service();
     }
References javolution.util.FastCollection< E >.service().
shared()
FastCollection<E> javolution.util.FastCollection< E >.shared () inherited
Returns a thread-safe view over this collection. The shared view allows for concurrent read as long as there is no writer. The default implementation is based on readers-writers locks giving priority to writers. Iterators on shared collections are thread-safe (no ConcurrentModificationException possible).
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSet< E >, javolution.util.FastSortedTable< E >, and javolution.util.FastSortedSet< E >.
Definition at line 201 of file FastCollection.java.
{
         return new SharedCollectionImpl<E>(service());
     }
size()
abstract int javolution.util.internal.set.SetView< E >.size () abstract inherited
Returns the size of this collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Reimplemented in javolution.util.internal.bitset.BitSetServiceImpl, javolution.util.internal.set.sorted.SubSortedSetImpl< E >, and javolution.util.internal.map.MapView< K, V >.EntrySet.
sorted() [1/2]
FastCollection<E> javolution.util.FastCollection< E >.sorted () inherited
Returns a view exposing elements sorted according to the collection order.
Definition at line 267 of file FastCollection.java.
{
         return new SortedCollectionImpl<E>(service(), comparator());
     }
Referenced by javolution.util.internal.collection.SortedCollectionImpl< E >.IteratorImpl.IteratorImpl().
sorted() [2/2]
FastCollection<E> javolution.util.FastCollection< E >.sorted (Comparator<? super E > cmp) inherited
Returns a view exposing elements sorted according to the specified comparator.
Definition at line 275 of file FastCollection.java.
{
         return new SortedCollectionImpl<E>(service(), cmp);
     }
split()
CollectionService<E> [] javolution.util.internal.collection.CollectionView< E >.split (int n) inherited
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Implements javolution.util.function.Splittable< T >.
Reimplemented in javolution.util.internal.table.SharedTableImpl< E >, javolution.util.internal.table.TableView< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.table.AtomicTableImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, and javolution.util.internal.map.MapView< K, V >.EntrySet.
Definition at line 224 of file CollectionView.java.
{
         if (target == null) return new CollectionService[] { this }; // No split.
         CollectionService<E>[] subTargets = target.split(n);
         CollectionService<E>[] result = new CollectionService[subTargets.length];
         for (int i = 0; i < subTargets.length; i++) {
             CollectionView<E> copy = this.clone();
             copy.target = subTargets[i];
             result[i] = copy;
         }
         return result;
     }
subSet()
SortedSetService<E> javolution.util.internal.set.sorted.SortedSetView< E >.subSet (E fromElement, E toElement)
Implements javolution.util.service.SortedSetService< E >.
Definition at line 41 of file SortedSetView.java.
{
         return new SubSortedSetImpl<E>(this, fromElement, toElement);
     }
tailSet()
SortedSetService<E> javolution.util.internal.set.sorted.SortedSetView< E >.tailSet (E fromElement)
Implements javolution.util.service.SortedSetService< E >.
Definition at line 46 of file SortedSetView.java.
{
         return new SubSortedSetImpl<E>(this, fromElement, null);
     }
target()
SortedSetService<E> javolution.util.internal.set.sorted.SortedSetView< E >.target () protected
Returns the actual target
Reimplemented from javolution.util.internal.set.SetView< E >.
Definition at line 56 of file SortedSetView.java.
{
         return (SortedSetService<E>) super.target();
     }
Referenced by javolution.util.internal.set.sorted.SubSortedSetImpl< E >.add(), javolution.util.internal.set.sorted.SubSortedSetImpl< E >.comparator(), javolution.util.internal.set.sorted.SubSortedSetImpl< E >.contains(), javolution.util.internal.set.sorted.SubSortedSetImpl< E >.first(), javolution.util.internal.set.sorted.SubSortedSetImpl< E >.last(), javolution.util.internal.set.sorted.SubSortedSetImpl< E >.remove(), javolution.util.internal.set.sorted.SortedSetView< E >.SortedSetView(), and javolution.util.internal.set.sorted.SubSortedSetImpl< E >.SubSortedSetImpl().
threadSafe()
SortedSetService<E> javolution.util.internal.set.sorted.SortedSetView< E >.threadSafe ()
Returns a thread-safe version of this service (used during parallel updates).
Reimplemented from javolution.util.internal.set.SetView< E >.
Definition at line 51 of file SortedSetView.java.
{
         return new SharedSortedSetImpl<E>(this);
     }
toArray() [1/2]
Object [] javolution.util.internal.collection.CollectionView< E >.toArray () inherited
Returns an array holding this collection elements.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 243 of file CollectionView.java.
{
         return toArray(new Object[size()]);
     }
Referenced by javolution.util.internal.collection.CollectionView< R >.toArray().
toArray() [2/2]
public<T> T [] javolution.util.internal.collection.CollectionView< E >.toArray (T[] array) package inherited
Returns the specified array holding this collection elements if enough capacity.
Reimplemented from javolution.util.FastCollection< E >.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 249 of file CollectionView.java.
{
         final int size = size();
         final T[] result = (size <= a.length) ? a
                 : (T[]) java.lang.reflect.Array.newInstance(a.getClass()
                         .getComponentType(), size);
         int i = 0;
         Iterator<E> it = iterator();
         while (it.hasNext()) {
             result[i++] = (T) it.next();
         }
         if (result.length > size) {
             result[size] = null; // As per Collection contract.
         }
         return result;
     }
toImmutable()
public<T extends Collection<E> > Immutable<T> javolution.util.FastCollection< E >.toImmutable () package inherited
Returns an immutable reference over this collection. The immutable value is an unmodifiable view of this collection. The caller must guarantees that the original collection is never going to be updated (e.g. there is no reference left of the original collection).
Definition at line 585 of file FastCollection.java.
{
         return new Immutable<T>() {
             @SuppressWarnings("unchecked")
             final T value = (T) unmodifiable();
             @Override
             public T value() {
                 return value;
             }
         };
     }
toString()
String javolution.util.FastCollection< E >.toString () inherited
Returns the string representation of this collection using its default format.
Definition at line 634 of file FastCollection.java.
{
         return TextContext.getFormat(FastCollection.class).format(this);
     }
References javolution.text.TextContext.getFormat().
unmodifiable()
FastCollection<E> javolution.util.FastCollection< E >.unmodifiable () inherited
Returns an unmodifiable view over this collection. Any attempt to modify the collection through this view will result into a java.lang.UnsupportedOperationException being raised.
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSet< E >, javolution.util.FastSortedTable< E >, and javolution.util.FastSortedSet< E >.
Definition at line 239 of file FastCollection.java.
{
         return new UnmodifiableCollectionImpl<E>(service());
     }
update() [1/3]
void javolution.util.internal.collection.CollectionView< E >.update (Consumer< CollectionService< E >> action, CollectionService< E > view) inherited
Reimplemented in javolution.util.internal.collection.ParallelCollectionImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Definition at line 266 of file CollectionView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
update() [2/3]
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
update() [3/3]
void javolution.util.FastCollection< E >.update (Consumer<? extends Collection< E >> action) inherited
Executes the specified update action on this collection. That logic may be performed concurrently on sub-collections if this collection is parallel. For atomic collections the update is atomic (either concurrent readers see the full result of the action or nothing).
Parameters
action the update action.
Exceptions
ClassCastException if the action type is not compatible with this collection (e.g. action on set and this is a list).
See also
#perform(Consumer)
Definition at line 334 of file FastCollection.java.
{
         service().update((Consumer<CollectionService<E>>) action, service());
     }
Referenced by javolution.util.FastTable< javolution.xml.internal.stream.XMLStreamReaderImpl >.sort().
Member Data Documentation
serialVersionUID
final long javolution.util.internal.set.sorted.SortedSetView< E >.serialVersionUID = 0x600L static private
Definition at line 20 of file SortedSetView.java.
The documentation for this class was generated from the following file:
SortedSetView.java