Javolution 6.0.0 java: javolution.test.Perfometer< T > Class Template Reference
javolution.test.Perfometer< T > Class Template Reference abstract
Public Member Functions
Perfometer (String description)
double getAvgTimeInSeconds ()
String getDescription ()
T getInput ()
int getNbrOfIterations ()
double[] getTimesInSeconds ()
Perfometer< T > measure (T input, int nbrOfIterations)
void print ()
void printDetails ()
double getWCETinSeconds ()
int getWorstCaseNumber ()
Static Public Attributes
static final Configurable< Integer > DURATION_MS
static final Configurable< Boolean > SKIP
Protected Member Functions
abstract void initialize () throws Exception
abstract void run (boolean measure) throws Exception
void validate ()
Private Member Functions
long[] longArray (int length, long initialValue)
Private Attributes
final String description
T input
long[] times
Detailed Description
Utility class to measure the worst case execution time and average execution time with high precision. Here an example measuring the worst case execution time of java.util.List#add(int, Object) for diverse list implementations.
[code] Perfometer<Class<? extends List>> insertPerf = new Perfometer<>("java.util.List#add(int, Object)") { List<Object> list; Random random; protected void initialize() throws Exception { list = getInput().newInstance(); random = new Random(-1); // Use seed to ensure same execution path. } protected void run(boolean measure) { Object obj = new Object(); int i = random.nextInt(list.size() + 1); if (measure) list.add(i, obj); } protected void validate() { // Optional. assert list.size() == getNbrOfIterations(); } } ... public void testExecutionTime() { insertPerf.measure(java.util.ArrayList.class, 10000).print(); insertPerf.measure(java.util.LinkedList.class, 10000).print(); insertPerf.measure(javolution.util.FastTable.class, 10000).print(); } ...
[INFO] java.util.List::add(int, Object) (10000) for java.util.ArrayList: 590.21450 ns (avg), 8443.0000 ns (wcet#9369) [INFO] java.util.List::add(int, Object) (10000) for java.util.LinkedList: 4849.8313 ns (avg), 26536.000 ns (wcet#9863) [INFO] java.util.List::add(int, Object) (10000) for javolution.util.FastTable: 217.26300 ns (avg), 534.00000 ns (wcet#8864)
[/code]
Parameters
<T> the perfometer input type.
Definition at line 53 of file Perfometer.java.
Constructor & Destructor Documentation
Perfometer()
javolution.test.Perfometer< T >.Perfometer (String description)
Creates a perfometer having the specified description.
Parameters
description the description of the code being measured.
Definition at line 100 of file Perfometer.java.
{
         this.description = description;
     }
References javolution.test.Perfometer< T >.description.
Member Function Documentation
getAvgTimeInSeconds()
double javolution.test.Perfometer< T >.getAvgTimeInSeconds ()
Returns the average execution time in seconds.
Definition at line 107 of file Perfometer.java.
{
         if (times == null) return Double.NaN;
         long sum = 0;
         for (long time : times) {
             sum += time;
         }
         return sum / 1e9 / times.length;
     }
References javolution.test.Perfometer< T >.times.
Referenced by javolution.test.Perfometer< T >.print().
getDescription()
String javolution.test.Perfometer< T >.getDescription ()
Returns this perfometer description.
Definition at line 119 of file Perfometer.java.
{
         return description;
     }
References javolution.test.Perfometer< T >.description.
getInput()
T javolution.test.Perfometer< T >.getInput ()
Returns this perfometer current inputs.
Definition at line 126 of file Perfometer.java.
{
         return input;
     }
References javolution.test.Perfometer< T >.input.
getNbrOfIterations()
int javolution.test.Perfometer< T >.getNbrOfIterations ()
Returns this perfometer current number of iterations performed.
Definition at line 133 of file Perfometer.java.
{
         return (times != null) ? times.length : 0;
     }
References javolution.test.Perfometer< T >.times.
Referenced by javolution.test.Perfometer< T >.print().
getTimesInSeconds()
double [] javolution.test.Perfometer< T >.getTimesInSeconds ()
Returns the execution times in seconds.
Definition at line 140 of file Perfometer.java.
{
         if (times == null) return new double[0];
         double[] timesSec = new double[times.length];
         for (int i=0; i < times.length; i++) {
             timesSec[i] = times[i] / 1e9;
         }
         return timesSec;
     }
References javolution.test.Perfometer< T >.times.
getWCETinSeconds()
double javolution.test.Perfometer< T >.getWCETinSeconds ()
Returns the worst case execution time in seconds.
Definition at line 222 of file Perfometer.java.
{
         if (times == null) return Double.NaN;
         long wcet = 0;
         for (long time : times) {
             if (time > wcet) wcet = time;
         }
         return wcet / 1e9;
     }
References javolution.test.Perfometer< T >.times.
Referenced by javolution.test.Perfometer< T >.print().
getWorstCaseNumber()
int javolution.test.Perfometer< T >.getWorstCaseNumber ()
Returns the iteration number having the slowest execution time.
Definition at line 234 of file Perfometer.java.
{
         if (times == null) return -1;
         long wcet = 0;
         int j = -1;
         for (int i=0; i < times.length; i++) {
             if (times[i] > wcet) {
                 wcet = times[i];
                 j = i;
             }
         }
         return j;
     }
References javolution.test.Perfometer< T >.times.
Referenced by javolution.test.Perfometer< T >.print().
initialize()
abstract void javolution.test.Perfometer< T >.initialize () throws Exception abstract protected
Performs the initialization.
Referenced by javolution.test.Perfometer< T >.measure().
longArray()
long [] javolution.test.Perfometer< T >.longArray (int length, long initialValue) private
Definition at line 265 of file Perfometer.java.
{
         long[] array = new long[length];
         for (int i = 0; i < length; i++)
             array[i] = initialValue;
         return array;
     }
Referenced by javolution.test.Perfometer< T >.measure().
measure()
Perfometer<T> javolution.test.Perfometer< T >.measure (T input, int nbrOfIterations)
Measures the worst case execution time and average execution time.
Parameters
input the test input.
nbrOfIterations the number of iterations performed on which the average will be calculated.
Definition at line 156 of file Perfometer.java.
{
         if (SKIP.get()) return this; // Skip.
         this.input = input;
         this.times = new long[nbrOfIterations];
         long[] calibrations = longArray(nbrOfIterations, Long.MAX_VALUE);
         long[] measures = longArray(nbrOfIterations, Long.MAX_VALUE);
         try {
             long exitTime = System.currentTimeMillis() + DURATION_MS.get();
             do {
                 // Calibration.
                 initialize();
                 for (int i = 0; i < nbrOfIterations; i++) {
                     long start = System.nanoTime();
                     run(false);
                     long time = System.nanoTime() - start;
                     calibrations[i] = MathLib.min(calibrations[i], time);
                 }
                 // Measurement.
                 initialize();
                 for (int i = 0; i < nbrOfIterations; i++) {
                     long start = System.nanoTime();
                     run(true);
                     long time = System.nanoTime() - start;
                     measures[i] = MathLib.min(measures[i], time);
                 }
             } while (System.currentTimeMillis() < exitTime);
             for (int i = 0; i < nbrOfIterations; i++) {
                 times[i] = measures[i] - calibrations[i];
             }
             return this;
         } catch (Exception error) {
             throw new RuntimeException("Perfometer Exception", error);
         }
     }
References javolution.test.Perfometer< T >.DURATION_MS, javolution.lang.Configurable< T >.get(), javolution.test.Perfometer< T >.initialize(), javolution.test.Perfometer< T >.input, javolution.test.Perfometer< T >.longArray(), javolution.lang.MathLib.min(), javolution.test.Perfometer< T >.run(), javolution.test.Perfometer< T >.SKIP, and javolution.test.Perfometer< T >.times.
print()
void javolution.test.Perfometer< T >.print ()
Outputs the result.
Definition at line 194 of file Perfometer.java.
{
         if (Perfometer.SKIP.get()) return;
         TextBuilder txt = new TextBuilder();
         txt.append(description).append(" (").append(getNbrOfIterations())
                 .append(") for ").append(input).append(": ");
         while (txt.length() < 80)
             txt.append(' ');
         txt.append(getAvgTimeInSeconds() * 1E9, 8, false, true); // Nano-Seconds.
         txt.append(" ns (avg), ");
         txt.append(getWCETinSeconds() * 1E9, 8, false, true); // Nano-Seconds.
         txt.append(" ns (wcet#").append(getWorstCaseNumber()).append(")");
         LogContext.info(txt);
     }
References javolution.text.TextBuilder.append(), javolution.test.Perfometer< T >.description, javolution.lang.Configurable< T >.get(), javolution.test.Perfometer< T >.getAvgTimeInSeconds(), javolution.test.Perfometer< T >.getNbrOfIterations(), javolution.test.Perfometer< T >.getWCETinSeconds(), javolution.test.Perfometer< T >.getWorstCaseNumber(), javolution.context.LogContext.info(), javolution.test.Perfometer< T >.input, javolution.text.TextBuilder.length(), and javolution.test.Perfometer< T >.SKIP.
printDetails()
void javolution.test.Perfometer< T >.printDetails ()
Outputs the measurements in nanoseconds.
Definition at line 211 of file Perfometer.java.
{
         if (Perfometer.SKIP.get()) return;
         FastTable<Long> measurements = new FastTable<Long>();
         for (long time : times)
             measurements.add(time);
         LogContext.debug(measurements);
     }
References javolution.util.FastTable< E >.add(), javolution.context.LogContext.debug(), javolution.lang.Configurable< T >.get(), javolution.test.Perfometer< T >.SKIP, and javolution.test.Perfometer< T >.times.
run()
abstract void javolution.test.Perfometer< T >.run (boolean measure) throws Exception abstract protected
Runs the code being benchmarked.
Parameters
measure
Referenced by javolution.test.Perfometer< T >.measure().
validate()
void javolution.test.Perfometer< T >.validate () protected
Validates the final result (after all iterations are completed).
Definition at line 263 of file Perfometer.java.
 {}
Member Data Documentation
description
final String javolution.test.Perfometer< T >.description private
Definition at line 91 of file Perfometer.java.
Referenced by javolution.test.Perfometer< T >.getDescription(), javolution.test.Perfometer< T >.Perfometer(), and javolution.test.Perfometer< T >.print().
DURATION_MS
final Configurable<Integer> javolution.test.Perfometer< T >.DURATION_MS static
Initial value:
= new Configurable<Integer>() {
        @Override
        public String getName() {
            return this.getClass().getEnclosingClass().getName()
                    + "#DURATION_MS";
        }
        @Override
        protected Integer getDefault() {
            return 1000;
        }
    }
Hold the measurement duration in milliseconds (default 1000 ms).
Definition at line 58 of file Perfometer.java.
Referenced by javolution.test.Perfometer< T >.measure().
input
T javolution.test.Perfometer< T >.input private
Definition at line 92 of file Perfometer.java.
Referenced by javolution.test.Perfometer< T >.getInput(), javolution.test.Perfometer< T >.measure(), and javolution.test.Perfometer< T >.print().
SKIP
final Configurable<Boolean> javolution.test.Perfometer< T >.SKIP static
Initial value:
= new Configurable<Boolean>() {
        @Override
        public String getName() {
            return this.getClass().getEnclosingClass().getName() + "#SKIP";
        }
        @Override
        protected Boolean getDefault() {
            return false;
        }
    }
Indicates if perfometer measurements should be skipped (e.g.
-Djavolution.test.Perfometer#SKIP=true
to skip performance measurements). When skipped, measure and print don't do anything.
Definition at line 78 of file Perfometer.java.
Referenced by javolution.test.Perfometer< T >.measure(), javolution.test.Perfometer< T >.print(), and javolution.test.Perfometer< T >.printDetails().
times
long [] javolution.test.Perfometer< T >.times private
Definition at line 93 of file Perfometer.java.
Referenced by javolution.test.Perfometer< T >.getAvgTimeInSeconds(), javolution.test.Perfometer< T >.getNbrOfIterations(), javolution.test.Perfometer< T >.getTimesInSeconds(), javolution.test.Perfometer< T >.getWCETinSeconds(), javolution.test.Perfometer< T >.getWorstCaseNumber(), javolution.test.Perfometer< T >.measure(), and javolution.test.Perfometer< T >.printDetails().
The documentation for this class was generated from the following file:
Perfometer.java