Javolution 6.0.0 java: javolution.io.UTF8ByteBufferReader Class Reference
javolution.io.UTF8ByteBufferReader Class Reference
Public Member Functions
UTF8ByteBufferReader ()
UTF8ByteBufferReader setInput (ByteBuffer byteBuffer)
boolean ready () throws IOException
void close () throws IOException
int read () throws IOException
int read (char cbuf[], int off, int len) throws IOException
void read (Appendable dest) throws IOException
void reset ()
UTF8ByteBufferReader setByteBuffer (ByteBuffer byteBuffer)
Private Member Functions
int read2 (byte b) throws IOException
Private Attributes
ByteBuffer _byteBuffer
int _code
int _moreBytes
Detailed Description
A UTF-8 java.nio.ByteBuffer reader.
This reader can be used for efficient decoding of native byte buffers (e.g. MappedByteBuffer), high-performance messaging (no intermediate buffer), etc.
This reader supports surrogate char pairs (representing characters in the range [U+10000 .. U+10FFFF]). It can also be used to read characters unicodes (31 bits) directly (ref. read()).
Each invocation of one of the read() methods may cause one or more bytes to be read from the underlying byte buffer. The end of stream is reached when the byte buffer position and limit coincide.
Author
Jean-Marie Dautelle
Version
2.0, December 9, 2004
See also
UTF8ByteBufferWriter
Definition at line 39 of file UTF8ByteBufferReader.java.
Constructor & Destructor Documentation
UTF8ByteBufferReader()
javolution.io.UTF8ByteBufferReader.UTF8ByteBufferReader ()
Default constructor.
Definition at line 49 of file UTF8ByteBufferReader.java.
 {}
Member Function Documentation
close()
void javolution.io.UTF8ByteBufferReader.close () throws IOException
Closes and resets this reader for reuse.
Exceptions
IOException if an I/O error occurs.
Definition at line 87 of file UTF8ByteBufferReader.java.
{
         if (_byteBuffer != null) {
             reset();
         }
     }
References javolution.io.UTF8ByteBufferReader._byteBuffer, and javolution.io.UTF8ByteBufferReader.reset().
read() [1/3]
int javolution.io.UTF8ByteBufferReader.read () throws IOException
Reads a single character. This method does not block, -1 is returned if the buffer's limit has been reached.
Returns
the 31-bits Unicode of the character read, or -1 if there is no more remaining bytes to be read.
Exceptions
IOException if an I/O error occurs (e.g. incomplete character sequence being read).
Definition at line 102 of file UTF8ByteBufferReader.java.
{
         if (_byteBuffer != null) {
             if (_byteBuffer.hasRemaining()) {
                 byte b = _byteBuffer.get();
                 return (b >= 0) ? b : read2(b);
             } else {
                 return -1;
             }
         } else {
             throw new IOException("Reader closed");
         }
     }
References javolution.io.UTF8ByteBufferReader._byteBuffer, and javolution.io.UTF8ByteBufferReader.read2().
Referenced by javolution.io.Struct.UTF8String.get().
read() [2/3]
void javolution.io.UTF8ByteBufferReader.read (Appendable dest) throws IOException
Reads characters into the specified appendable. This method does not block.
Note: Characters between U+10000 and U+10FFFF are represented by surrogate pairs (two char).
Parameters
dest the destination buffer.
Exceptions
IOException if an I/O error occurs.
Definition at line 231 of file UTF8ByteBufferReader.java.
{
         if (_byteBuffer == null)
             throw new IOException("Reader closed");
         while (_byteBuffer.hasRemaining()) {
             byte b = _byteBuffer.get();
             if (b >= 0) {
                 dest.append((char) b); // Most common case.
             } else {
                 int code = read2(b);
                 if (code < 0x10000) {
                     dest.append((char) code);
                 } else if (code <= 0x10ffff) { // Surrogates.
                     dest.append((char) (((code - 0x10000) >> 10) + 0xd800));
                     dest.append((char) (((code - 0x10000) & 0x3ff) + 0xdc00));
                 } else {
                     throw new CharConversionException("Cannot convert U+"
                             + Integer.toHexString(code)
                             + " to char (code greater than U+10FFFF)");
                 }
             }
         }
     }
References javolution.io.UTF8ByteBufferReader._byteBuffer, and javolution.io.UTF8ByteBufferReader.read2().
read() [3/3]
int javolution.io.UTF8ByteBufferReader.read (char cbuf[], int off, int len) throws IOException
Reads characters into a portion of an array. This method does not block.
Note: Characters between U+10000 and U+10FFFF are represented by surrogate pairs (two char).
Parameters
cbuf the destination buffer.
off the offset at which to start storing characters.
len the maximum number of characters to read
Returns
the number of characters read, or -1 if there is no more byte remaining.
Exceptions
IOException if an I/O error occurs.
Definition at line 181 of file UTF8ByteBufferReader.java.
{
         if (_byteBuffer == null)
             throw new IOException("Reader closed");
         final int off_plus_len = off + len;
         int remaining = _byteBuffer.remaining();
         if (remaining <= 0)
             return -1;
         for (int i = off; i < off_plus_len;) {
             if (remaining-- > 0) {
                 byte b = _byteBuffer.get();
                 if (b >= 0) {
                     cbuf[i++] = (char) b; // Most common case.
                 } else {
                     if (i < off_plus_len - 1) { // Up to two 'char' can be read.
                         int code = read2(b);
                         remaining = _byteBuffer.remaining(); // Recalculates.
                         if (code < 0x10000) {
                             cbuf[i++] = (char) code;
                         } else if (code <= 0x10ffff) { // Surrogates.
                             cbuf[i++] = (char) (((code - 0x10000) >> 10) + 0xd800);
                             cbuf[i++] = (char) (((code - 0x10000) & 0x3ff) + 0xdc00);
                         } else {
                             throw new CharConversionException(
                                     "Cannot convert U+"
                                             + Integer.toHexString(code)
                                             + " to char (code greater than U+10FFFF)");
                         }
                     } else { // Not enough space in destination (go back).
                         _byteBuffer.position(_byteBuffer.position() - 1);
                         remaining++;
                         return i - off;
                     }
                 }
             } else {
                 return i - off;
             }
         }
         return len;
     }
References javolution.io.UTF8ByteBufferReader._byteBuffer, and javolution.io.UTF8ByteBufferReader.read2().
read2()
int javolution.io.UTF8ByteBufferReader.read2 (byte b) throws IOException private
Definition at line 116 of file UTF8ByteBufferReader.java.
{
         try {
             // Decodes UTF-8.
             if ((b >= 0) && (_moreBytes == 0)) {
                 // 0xxxxxxx
                 return b;
             } else if (((b & 0xc0) == 0x80) && (_moreBytes != 0)) {
                 // 10xxxxxx (continuation byte)
                 _code = (_code << 6) | (b & 0x3f); // Adds 6 bits to code.
                 if (--_moreBytes == 0) {
                     return _code;
                 } else {
                     return read2(_byteBuffer.get());
                 }
             } else if (((b & 0xe0) == 0xc0) && (_moreBytes == 0)) {
                 // 110xxxxx
                 _code = b & 0x1f;
                 _moreBytes = 1;
                 return read2(_byteBuffer.get());
             } else if (((b & 0xf0) == 0xe0) && (_moreBytes == 0)) {
                 // 1110xxxx
                 _code = b & 0x0f;
                 _moreBytes = 2;
                 return read2(_byteBuffer.get());
             } else if (((b & 0xf8) == 0xf0) && (_moreBytes == 0)) {
                 // 11110xxx
                 _code = b & 0x07;
                 _moreBytes = 3;
                 return read2(_byteBuffer.get());
             } else if (((b & 0xfc) == 0xf8) && (_moreBytes == 0)) {
                 // 111110xx
                 _code = b & 0x03;
                 _moreBytes = 4;
                 return read2(_byteBuffer.get());
             } else if (((b & 0xfe) == 0xfc) && (_moreBytes == 0)) {
                 // 1111110x
                 _code = b & 0x01;
                 _moreBytes = 5;
                 return read2(_byteBuffer.get());
             } else {
                 throw new CharConversionException("Invalid UTF-8 Encoding");
             }
         } catch (BufferUnderflowException e) {
             throw new CharConversionException("Incomplete Sequence");
         }
     }
References javolution.io.UTF8ByteBufferReader._byteBuffer, javolution.io.UTF8ByteBufferReader._code, and javolution.io.UTF8ByteBufferReader._moreBytes.
Referenced by javolution.io.UTF8ByteBufferReader.read().
ready()
boolean javolution.io.UTF8ByteBufferReader.ready () throws IOException
Indicates if this stream is ready to be read.
Returns
true if the byte buffer has remaining bytes to read; false otherwise.
Exceptions
IOException if an I/O error occurs.
Definition at line 74 of file UTF8ByteBufferReader.java.
{
         if (_byteBuffer != null) {
             return _byteBuffer.hasRemaining();
         } else {
             throw new IOException("Reader closed");
         }
     }
References javolution.io.UTF8ByteBufferReader._byteBuffer.
reset()
void javolution.io.UTF8ByteBufferReader.reset ()
Definition at line 254 of file UTF8ByteBufferReader.java.
{
         _byteBuffer = null;
         _code = 0;
         _moreBytes = 0;
     }
References javolution.io.UTF8ByteBufferReader._byteBuffer, javolution.io.UTF8ByteBufferReader._code, and javolution.io.UTF8ByteBufferReader._moreBytes.
Referenced by javolution.io.UTF8ByteBufferReader.close(), and javolution.io.Struct.UTF8String.get().
setByteBuffer()
UTF8ByteBufferReader javolution.io.UTF8ByteBufferReader.setByteBuffer (ByteBuffer byteBuffer)
Deprecated:
Replaced by setInput(ByteBuffer)
Definition at line 263 of file UTF8ByteBufferReader.java.
{
         return this.setInput(byteBuffer);
     }
References javolution.io.UTF8ByteBufferReader.setInput().
setInput()
UTF8ByteBufferReader javolution.io.UTF8ByteBufferReader.setInput (ByteBuffer byteBuffer)
Sets the ByteBuffer to use for reading available bytes from current buffer position.
Parameters
byteBuffer the ByteBuffer source.
Returns
this UTF-8 reader.
Exceptions
IllegalStateException if this reader is being reused and it has not been closed or reset.
Definition at line 60 of file UTF8ByteBufferReader.java.
{
         if (_byteBuffer != null)
             throw new IllegalStateException("Reader not closed or reset");
         _byteBuffer = byteBuffer;
         return this;
     }
References javolution.io.UTF8ByteBufferReader._byteBuffer.
Referenced by javolution.io.Struct.UTF8String.get(), and javolution.io.UTF8ByteBufferReader.setByteBuffer().
Member Data Documentation
_byteBuffer
ByteBuffer javolution.io.UTF8ByteBufferReader._byteBuffer private
Holds the byte buffer source.
Definition at line 44 of file UTF8ByteBufferReader.java.
Referenced by javolution.io.UTF8ByteBufferReader.close(), javolution.io.UTF8ByteBufferReader.read(), javolution.io.UTF8ByteBufferReader.read2(), javolution.io.UTF8ByteBufferReader.ready(), javolution.io.UTF8ByteBufferReader.reset(), and javolution.io.UTF8ByteBufferReader.setInput().
_code
int javolution.io.UTF8ByteBufferReader._code private
Definition at line 163 of file UTF8ByteBufferReader.java.
Referenced by javolution.io.UTF8ByteBufferReader.read2(), and javolution.io.UTF8ByteBufferReader.reset().
_moreBytes
int javolution.io.UTF8ByteBufferReader._moreBytes private
Definition at line 165 of file UTF8ByteBufferReader.java.
Referenced by javolution.io.UTF8ByteBufferReader.read2(), and javolution.io.UTF8ByteBufferReader.reset().
The documentation for this class was generated from the following file:
UTF8ByteBufferReader.java