Javolution 6.0.0 java: javolution.util.FastCollection< E >.Format Class Reference
javolution.util.FastCollection< E >.Format Class Reference
Public Member Functions
FastCollection< Object > parse (CharSequence csq, Cursor cursor) throws IllegalArgumentException
Appendable format (FastCollection<?> that, final Appendable dest) throws IOException
T parse (CharSequence csq) throws IllegalArgumentException
abstract Appendable format (T obj, Appendable dest) throws IOException
TextBuilder format (T obj, TextBuilder dest)
String format (T obj)
Detailed Description
Default text format for fast collections (parsing not supported). It is the format used when printing standard
java.util.Collection
instances except that the elements themselves are written using their TextContext format.
Definition at line 663 of file FastCollection.java.
Member Function Documentation
format() [1/4]
Appendable javolution.util.FastCollection< E >.Format.format (FastCollection<?> that, final Appendable dest) throws IOException
Definition at line 672 of file FastCollection.java.
{
             dest.append('[');
             Class<?> elementType = null;
             TextFormat<Object> format = null;
             for (Object element : that) {
                 if (elementType == null) elementType = Void.class;
                 else dest.append(", "); // Not the first.
                 if (element == null) {
                     dest.append("null");
                     continue;
                 }
                 Class<?> cls = element.getClass();
                 if (elementType.equals(cls)) {
                     format.format(element, dest);
                     continue;
                 }
                 elementType = cls;
                 format = TextContext.getFormat(cls);
                 format.format(element, dest);
             }
             return dest.append(']');
         }
References javolution.text.TextFormat< T >.format(), and javolution.text.TextContext.getFormat().
format() [2/4]
String javolution.text.TextFormat< T >.format (T obj) inherited
Convenience method to format the specified object to a String.
Parameters
obj the object to format.
Returns
the formatting result as a string.
Definition at line 121 of file TextFormat.java.
{
         return this.format(obj, new TextBuilder()).toString();
     }
format() [3/4]
abstract Appendable javolution.text.TextFormat< T >.format (T obj, Appendable dest) throws IOException abstract inherited
Formats the specified object into an Appendable
Parameters
obj the object to format.
dest the appendable destination.
Returns
the specified Appendable.
Referenced by javolution.text.TextBuilder.append(), javolution.text.TextFormat< FastCollection<?> >.format(), and javolution.util.FastCollection< E >.Format.format().
format() [4/4]
TextBuilder javolution.text.TextFormat< T >.format (T obj, TextBuilder dest) inherited
Convenience method to format the specified object to a TextBuilder; unlike the abstract format method, this method does not throw IOException.
Parameters
obj the object to format.
dest the appendable destination.
Returns
the specified TextBuilder.
Definition at line 106 of file TextFormat.java.
{
         try {
             this.format(obj, (Appendable) dest);
             return dest;
         } catch (IOException e) {
             throw new Error(e); // Cannot happens.
         }
     }
parse() [1/2]
T javolution.text.TextFormat< T >.parse (CharSequence csq) throws IllegalArgumentException inherited
Convenience method to parse the whole character sequence; if there are unread extraneous characters after parsing then an exception is raised.
Parameters
csq the CharSequence to parse from the first character to the last.
Exceptions
IllegalArgumentException if the syntax of the specified character sequence is incorrect or if there are extraneous characters at the end not parsed.
Definition at line 89 of file TextFormat.java.
{
         Cursor cursor = new Cursor();
         T obj = parse(csq, cursor);
         if (!cursor.atEnd(csq))
             throw new IllegalArgumentException("Extraneous character(s) \""
                     + cursor.tail(csq) + "\"");
         return obj;
     }
parse() [2/2]
FastCollection<Object> javolution.util.FastCollection< E >.Format.parse (CharSequence csq, Cursor cursor) throws IllegalArgumentException
Reads a portion of the specified CharSequence from the specified cursor position to produce an object. If parsing succeeds, then the index of the cursor argument is updated to the index after the last character used.
Parameters
csq the character sequence to parse.
cursor the cursor holding the current parsing index.
Returns
the object parsed.
Exceptions
IllegalArgumentException if the syntax of the specified character sequence is incorrect.
UnsupportedOperationException if parsing is not supported.
Reimplemented from javolution.text.TextFormat< T >.
Definition at line 666 of file FastCollection.java.
{
             throw new UnsupportedOperationException();
         }
The documentation for this class was generated from the following file:
FastCollection.java