Javolution 6.0.0 java: javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl Class Reference
javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl Class Reference
Public Member Functions
boolean hasNext ()
E next ()
void remove ()
Private Attributes
boolean ahead
final Equality<? super E > cmp = comparator()
E next
final Iterator< E > targetIterator = target().iterator()
Detailed Description
Peeking ahead iterator.
Definition at line 23 of file SubSortedSetImpl.java.
Member Function Documentation
hasNext()
boolean javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.hasNext ()
Definition at line 31 of file SubSortedSetImpl.java.
{
             if (ahead) return true;
             while (targetIterator.hasNext()) {
                 next = targetIterator.next();
                 if ((from != null) && (cmp.compare(next, from) < 0)) continue;
                 if ((to != null) && (cmp.compare(next, to) >= 0)) break;
                 ahead = true;
                 return true;
             }
             return false;
         }
References javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.ahead, javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.cmp, javolution.util.function.Equality< T >.compare(), javolution.util.internal.set.sorted.SubSortedSetImpl< E >.from, javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.next, javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.targetIterator, and javolution.util.internal.set.sorted.SubSortedSetImpl< E >.to.
Referenced by javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.next().
next()
E javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.next ()
Definition at line 44 of file SubSortedSetImpl.java.
{
             hasNext(); // Moves ahead.
             ahead = false;
             return next;
         }
References javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.ahead, javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.hasNext(), and javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.next.
remove()
void javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.remove ()
Definition at line 51 of file SubSortedSetImpl.java.
{
             targetIterator.remove();
         }
References javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.targetIterator.
Member Data Documentation
ahead
boolean javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.ahead private
Definition at line 25 of file SubSortedSetImpl.java.
Referenced by javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.hasNext(), and javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.next().
cmp
final Equality<? super E> javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.cmp = comparator() private
Definition at line 26 of file SubSortedSetImpl.java.
Referenced by javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.hasNext().
next
E javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.next private
Definition at line 27 of file SubSortedSetImpl.java.
Referenced by javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.hasNext(), and javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.next().
targetIterator
final Iterator<E> javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.targetIterator = target().iterator() private
Definition at line 28 of file SubSortedSetImpl.java.
Referenced by javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.hasNext(), and javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.remove().
The documentation for this class was generated from the following file:
SubSortedSetImpl.java