Javolution 6.0.0 java: javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl Class Reference
javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl Class Reference
Public Member Functions
IteratorImpl ()
boolean hasNext ()
Entry< K, V > next ()
void remove ()
Private Attributes
Entry< K, V > next
final Iterator< Entry< K, V > > targetIterator
Detailed Description
Thread-Safe Iterator.
Definition at line 24 of file SharedMapImpl.java.
Constructor & Destructor Documentation
IteratorImpl()
javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.IteratorImpl ()
Definition at line 28 of file SharedMapImpl.java.
{
             lock.readLock.lock();
             try {
                 targetIterator = cloneTarget().entrySet().iterator(); // Copy.
             } finally {
                 lock.readLock.unlock();
             }
         }
References javolution.util.internal.map.SharedMapImpl< K, V >.cloneTarget(), javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lock(), javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.readLock, javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.targetIterator, and javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.unlock().
Member Function Documentation
hasNext()
boolean javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.hasNext ()
Definition at line 38 of file SharedMapImpl.java.
{
             return targetIterator.hasNext();
         }
References javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.targetIterator.
next()
Entry<K, V> javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.next ()
Definition at line 43 of file SharedMapImpl.java.
{
             next = targetIterator.next();
             return next;
         }
References javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.next, and javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.targetIterator.
remove()
void javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.remove ()
Definition at line 49 of file SharedMapImpl.java.
{
             if (next == null) throw new IllegalStateException();
             SharedMapImpl.this.remove(next.getKey());
             next = null;
         }
References javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.next, and javolution.util.internal.map.SharedMapImpl< K, V >.remove().
Member Data Documentation
next
Entry<K, V> javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.next private
Definition at line 25 of file SharedMapImpl.java.
Referenced by javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.next(), and javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.remove().
targetIterator
final Iterator<Entry<K, V> > javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.targetIterator private
Definition at line 26 of file SharedMapImpl.java.
Referenced by javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.hasNext(), javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.IteratorImpl(), and javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.next().
The documentation for this class was generated from the following file:
SharedMapImpl.java