Javolution 6.0.0 java: javolution.io.UTF8ByteBufferWriter Class Reference
javolution.io.UTF8ByteBufferWriter Class Reference
Public Member Functions
UTF8ByteBufferWriter ()
UTF8ByteBufferWriter setOutput (ByteBuffer byteBuffer)
void write (char c) throws IOException
void write (int code) throws IOException
void write (char cbuf[], int off, int len) throws IOException
void write (String str, int off, int len) throws IOException
void write (CharSequence csq) throws IOException
void flush () throws IOException
void close () throws IOException
void reset ()
UTF8ByteBufferWriter setByteBuffer (ByteBuffer byteBuffer)
Private Member Functions
void write2 (int c) throws IOException
Private Attributes
ByteBuffer _byteBuffer
char _highSurrogate
Detailed Description
A UTF-8 java.nio.ByteBuffer writer.
This writer supports surrogate char pairs (representing characters in the range [U+10000 .. U+10FFFF]). It can also be used to write characters from their unicodes (31 bits) directly (ref. write(int)).
Instances of this class can be reused for different output streams and can be part of a higher level component (e.g. serializer) in order to avoid dynamic buffer allocation when the destination output changes. Also wrapping using a java.io.BufferedWriter is unnescessary as instances of this class embed their own data buffers.
Note: This writer is unsynchronized and always produces well-formed UTF-8 sequences.
Author
Jean-Marie Dautelle
Version
2.0, December 9, 2004
See also
UTF8ByteBufferReader
Definition at line 37 of file UTF8ByteBufferWriter.java.
Constructor & Destructor Documentation
UTF8ByteBufferWriter()
javolution.io.UTF8ByteBufferWriter.UTF8ByteBufferWriter ()
Default constructor.
Definition at line 47 of file UTF8ByteBufferWriter.java.
 {}
Member Function Documentation
close()
void javolution.io.UTF8ByteBufferWriter.close () throws IOException
Closes and resets this writer for reuse.
Exceptions
IOException if an I/O error occurs
Definition at line 205 of file UTF8ByteBufferWriter.java.
{
         if (_byteBuffer != null) {
             reset();
         }
     }
References javolution.io.UTF8ByteBufferWriter._byteBuffer, and javolution.io.UTF8ByteBufferWriter.reset().
flush()
void javolution.io.UTF8ByteBufferWriter.flush () throws IOException
Flushes the stream (this method has no effect, the data is always directly written to the ByteBuffer).
Exceptions
IOException if an I/O error occurs.
Definition at line 196 of file UTF8ByteBufferWriter.java.
{
         if (_byteBuffer == null) { throw new IOException("Writer closed"); }
     }
References javolution.io.UTF8ByteBufferWriter._byteBuffer.
reset()
void javolution.io.UTF8ByteBufferWriter.reset ()
Definition at line 212 of file UTF8ByteBufferWriter.java.
{
         _byteBuffer = null;
         _highSurrogate = 0;
     }
References javolution.io.UTF8ByteBufferWriter._byteBuffer, and javolution.io.UTF8ByteBufferWriter._highSurrogate.
Referenced by javolution.io.UTF8ByteBufferWriter.close(), and javolution.io.Struct.UTF8String.set().
setByteBuffer()
UTF8ByteBufferWriter javolution.io.UTF8ByteBufferWriter.setByteBuffer (ByteBuffer byteBuffer)
Deprecated:
Replaced by setOutput(ByteBuffer)
Definition at line 220 of file UTF8ByteBufferWriter.java.
{
         return this.setOutput(byteBuffer);
     }
References javolution.io.UTF8ByteBufferWriter.setOutput().
setOutput()
UTF8ByteBufferWriter javolution.io.UTF8ByteBufferWriter.setOutput (ByteBuffer byteBuffer)
Sets the byte buffer to use for writing until this writer is closed.
Parameters
byteBuffer the destination byte buffer.
Returns
this UTF-8 writer.
Exceptions
IllegalStateException if this writer is being reused and it has not been closed or reset.
Definition at line 57 of file UTF8ByteBufferWriter.java.
{
         if (_byteBuffer != null)
             throw new IllegalStateException("Writer not closed or reset");
         _byteBuffer = byteBuffer;
         return this;
     }
References javolution.io.UTF8ByteBufferWriter._byteBuffer.
Referenced by javolution.io.Struct.UTF8String.set(), and javolution.io.UTF8ByteBufferWriter.setByteBuffer().
write() [1/5]
void javolution.io.UTF8ByteBufferWriter.write (char c) throws IOException
Writes a single character. This method supports 16-bits character surrogates.
Parameters
c char the character to be written (possibly a surrogate).
Exceptions
IOException if an I/O error occurs.
Definition at line 72 of file UTF8ByteBufferWriter.java.
{
         if ((c < 0xd800) || (c > 0xdfff)) {
             write((int) c);
         } else if (c < 0xdc00) { // High surrogate.
             _highSurrogate = c;
         } else { // Low surrogate.
             int code = ((_highSurrogate - 0xd800) << 10) + (c - 0xdc00)
                     + 0x10000;
             write(code);
         }
     }
References javolution.io.UTF8ByteBufferWriter._highSurrogate.
Referenced by javolution.io.Struct.UTF8String.set(), and javolution.io.UTF8ByteBufferWriter.write().
write() [2/5]
void javolution.io.UTF8ByteBufferWriter.write (char cbuf[], int off, int len) throws IOException
Writes a portion of an array of characters.
Parameters
cbuf the array of characters.
off the offset from which to start writing characters.
len the number of characters to write.
Exceptions
IOException if an I/O error occurs.
Definition at line 140 of file UTF8ByteBufferWriter.java.
{
         final int off_plus_len = off + len;
         for (int i = off; i < off_plus_len;) {
             char c = cbuf[i++];
             if (c < 0x80) {
                 _byteBuffer.put((byte) c);
             } else {
                 write(c);
             }
         }
     }
References javolution.io.UTF8ByteBufferWriter._byteBuffer, and javolution.io.UTF8ByteBufferWriter.write().
write() [3/5]
void javolution.io.UTF8ByteBufferWriter.write (CharSequence csq) throws IOException
Writes the specified character sequence.
Parameters
csq the character sequence.
Exceptions
IOException if an I/O error occurs
Definition at line 178 of file UTF8ByteBufferWriter.java.
{
         final int length = csq.length();
         for (int i = 0; i < length;) {
             char c = csq.charAt(i++);
             if (c < 0x80) {
                 _byteBuffer.put((byte) c);
             } else {
                 write(c);
             }
         }
     }
References javolution.io.UTF8ByteBufferWriter._byteBuffer, and javolution.io.UTF8ByteBufferWriter.write().
write() [4/5]
void javolution.io.UTF8ByteBufferWriter.write (int code) throws IOException
Writes a character given its 31-bits Unicode.
Parameters
code the 31 bits Unicode of the character to be written.
Exceptions
IOException if an I/O error occurs.
Definition at line 92 of file UTF8ByteBufferWriter.java.
{
         if ((code & 0xffffff80) == 0) {
             _byteBuffer.put((byte) code);
         } else { // Writes more than one byte.
             write2(code);
         }
     }
References javolution.io.UTF8ByteBufferWriter._byteBuffer, and javolution.io.UTF8ByteBufferWriter.write2().
write() [5/5]
void javolution.io.UTF8ByteBufferWriter.write (String str, int off, int len) throws IOException
Writes a portion of a string.
Parameters
str a String.
off the offset from which to start writing characters.
len the number of characters to write.
Exceptions
IOException if an I/O error occurs
Definition at line 160 of file UTF8ByteBufferWriter.java.
{
         final int off_plus_len = off + len;
         for (int i = off; i < off_plus_len;) {
             char c = str.charAt(i++);
             if (c < 0x80) {
                 _byteBuffer.put((byte) c);
             } else {
                 write(c);
             }
         }
     }
References javolution.io.UTF8ByteBufferWriter._byteBuffer, and javolution.io.UTF8ByteBufferWriter.write().
write2()
void javolution.io.UTF8ByteBufferWriter.write2 (int c) throws IOException private
Definition at line 100 of file UTF8ByteBufferWriter.java.
{
         if ((c & 0xfffff800) == 0) { // 2 bytes.
             _byteBuffer.put((byte) (0xc0 | (c >> 6)));
             _byteBuffer.put((byte) (0x80 | (c & 0x3f)));
         } else if ((c & 0xffff0000) == 0) { // 3 bytes.
             _byteBuffer.put((byte) (0xe0 | (c >> 12)));
             _byteBuffer.put((byte) (0x80 | ((c >> 6) & 0x3f)));
             _byteBuffer.put((byte) (0x80 | (c & 0x3f)));
         } else if ((c & 0xff200000) == 0) { // 4 bytes.
             _byteBuffer.put((byte) (0xf0 | (c >> 18)));
             _byteBuffer.put((byte) (0x80 | ((c >> 12) & 0x3f)));
             _byteBuffer.put((byte) (0x80 | ((c >> 6) & 0x3f)));
             _byteBuffer.put((byte) (0x80 | (c & 0x3f)));
         } else if ((c & 0xf4000000) == 0) { // 5 bytes.
             _byteBuffer.put((byte) (0xf8 | (c >> 24)));
             _byteBuffer.put((byte) (0x80 | ((c >> 18) & 0x3f)));
             _byteBuffer.put((byte) (0x80 | ((c >> 12) & 0x3f)));
             _byteBuffer.put((byte) (0x80 | ((c >> 6) & 0x3f)));
             _byteBuffer.put((byte) (0x80 | (c & 0x3f)));
         } else if ((c & 0x80000000) == 0) { // 6 bytes.
             _byteBuffer.put((byte) (0xfc | (c >> 30)));
             _byteBuffer.put((byte) (0x80 | ((c >> 24) & 0x3f)));
             _byteBuffer.put((byte) (0x80 | ((c >> 18) & 0x3f)));
             _byteBuffer.put((byte) (0x80 | ((c >> 12) & 0x3F)));
             _byteBuffer.put((byte) (0x80 | ((c >> 6) & 0x3F)));
             _byteBuffer.put((byte) (0x80 | (c & 0x3F)));
         } else {
             throw new CharConversionException("Illegal character U+"
                     + Integer.toHexString(c));
         }
     }
References javolution.io.UTF8ByteBufferWriter._byteBuffer.
Referenced by javolution.io.UTF8ByteBufferWriter.write().
Member Data Documentation
_byteBuffer
ByteBuffer javolution.io.UTF8ByteBufferWriter._byteBuffer private
Holds the byte buffer destination.
Definition at line 42 of file UTF8ByteBufferWriter.java.
Referenced by javolution.io.UTF8ByteBufferWriter.close(), javolution.io.UTF8ByteBufferWriter.flush(), javolution.io.UTF8ByteBufferWriter.reset(), javolution.io.UTF8ByteBufferWriter.setOutput(), javolution.io.UTF8ByteBufferWriter.write(), and javolution.io.UTF8ByteBufferWriter.write2().
_highSurrogate
char javolution.io.UTF8ByteBufferWriter._highSurrogate private
Definition at line 84 of file UTF8ByteBufferWriter.java.
Referenced by javolution.io.UTF8ByteBufferWriter.reset(), and javolution.io.UTF8ByteBufferWriter.write().
The documentation for this class was generated from the following file:
UTF8ByteBufferWriter.java