Javolution 6.0.0 java: javolution.xml.XMLObjectReader Class Reference
javolution.xml.XMLObjectReader Class Reference
Public Member Functions
XMLObjectReader ()
XMLStreamReader getStreamReader ()
XMLObjectReader setInput (InputStream in) throws XMLStreamException
XMLObjectReader setInput (InputStream in, String encoding) throws XMLStreamException
XMLObjectReader setInput (Reader in) throws XMLStreamException
XMLObjectReader setBinding (XMLBinding binding)
XMLObjectReader setReferenceResolver (XMLReferenceResolver referenceResolver)
boolean hasNext () throws XMLStreamException
void close () throws XMLStreamException
void reset ()
Static Public Member Functions
static XMLObjectReader newInstance (InputStream in) throws XMLStreamException
static XMLObjectReader newInstance (InputStream in, String encoding) throws XMLStreamException
static XMLObjectReader newInstance (Reader in) throws XMLStreamException
Package Functions
public< T > T read () throws XMLStreamException
public< T > T read (String name) throws XMLStreamException
public< T > T read (String localName, String uri) throws XMLStreamException
public< T > T read (String name, Class< T > cls) throws XMLStreamException
public< T > T read (String localName, String uri, Class< T > cls) throws XMLStreamException
Private Attributes
final XMLFormat.InputElement _xml = new XMLFormat.InputElement()
Reader _reader
InputStream _inputStream
Detailed Description
This class restores objects which have been serialized in XML format using an XMLObjectWriter.
When the XML document is parsed, each elements are recursively processed and Java objects are created using the XMLFormat of the class as identified by the XMLBinding.
Multiple objects can be read from the same XML input. For example:[code] XMLObjectReader reader = XMLObjectReader.newInstance(inputStream); while (reader.hasNext()) { Message message = reader.read("Message", Message.class); } reader.close(); // The underlying stream is closed. [/code]
Author
Jean-Marie Dautelle
Version
4.0, September 4, 2006
Definition at line 39 of file XMLObjectReader.java.
Constructor & Destructor Documentation
XMLObjectReader()
javolution.xml.XMLObjectReader.XMLObjectReader ()
Default constructor.
Definition at line 99 of file XMLObjectReader.java.
 {}
Referenced by javolution.xml.XMLObjectReader.newInstance().
Member Function Documentation
close()
void javolution.xml.XMLObjectReader.close () throws XMLStreamException
Closes this reader and its underlying input then reset this reader for potential reuse.
Definition at line 269 of file XMLObjectReader.java.
{
         try {
             if (_inputStream != null) {
                 _inputStream.close();
                 reset();
             } else if (_reader != null) {
                 _reader.close();
                 reset();
             }
         } catch (IOException e) {
             throw new XMLStreamException(e);
         }
     }
References javolution.xml.XMLObjectReader._inputStream, javolution.xml.XMLObjectReader._reader, and javolution.xml.XMLObjectReader.reset().
Referenced by javolution.xml.ws.WebServiceClient.invoke().
getStreamReader()
XMLStreamReader javolution.xml.XMLObjectReader.getStreamReader ()
Returns the stream reader being used by this reader (it can be used to set prefix, read prologs, etc).
Returns
the stream reader.
Definition at line 107 of file XMLObjectReader.java.
{
         return _xml._reader;
     }
References javolution.xml.XMLObjectReader._xml.
Referenced by javolution.xml.ws.WebServiceClient.invoke().
hasNext()
boolean javolution.xml.XMLObjectReader.hasNext () throws XMLStreamException
Indicates if more elements can be read. This method positions the reader at the start of the next element to be read (if any).
Returns
true if more element/data to be read; false otherwise.
See also
XMLFormat.InputElement::hasNext()
Definition at line 192 of file XMLObjectReader.java.
{
         return _xml.hasNext();
     }
References javolution.xml.XMLObjectReader._xml.
newInstance() [1/3]
static XMLObjectReader javolution.xml.XMLObjectReader.newInstance (InputStream in) throws XMLStreamException static
Returns a XML object reader having the specified input stream as input.
Parameters
in the input stream.
Definition at line 62 of file XMLObjectReader.java.
{
         XMLObjectReader reader = new XMLObjectReader();
         reader.setInput(in);
         return reader;
     }
References javolution.xml.XMLObjectReader.setInput(), and javolution.xml.XMLObjectReader.XMLObjectReader().
newInstance() [2/3]
static XMLObjectReader javolution.xml.XMLObjectReader.newInstance (InputStream in, String encoding) throws XMLStreamException static
Returns a XML object reader (potentially recycled) having the specified input stream/encoding as input.
Parameters
in the input stream.
encoding the input stream encoding
Definition at line 76 of file XMLObjectReader.java.
{
         XMLObjectReader reader = new XMLObjectReader();
         reader.setInput(in, encoding);
         return reader;
     }
References javolution.xml.XMLObjectReader.setInput(), and javolution.xml.XMLObjectReader.XMLObjectReader().
newInstance() [3/3]
static XMLObjectReader javolution.xml.XMLObjectReader.newInstance (Reader in) throws XMLStreamException static
Returns a XML object reader (potentially recycled) having the specified reader as input.
Parameters
in the reader source.
Definition at line 89 of file XMLObjectReader.java.
{
         XMLObjectReader reader = new XMLObjectReader();
         reader.setInput(in);
         return reader;
     }
References javolution.xml.XMLObjectReader.setInput(), and javolution.xml.XMLObjectReader.XMLObjectReader().
read() [1/5]
public<T> T javolution.xml.XMLObjectReader.read () throws XMLStreamException package
Returns the object corresponding to the next element/data.
Returns
the next nested object (can be null)
Exceptions
XMLStreamException if hasNext() == false
See also
XMLFormat.InputElement::getNext()
Definition at line 204 of file XMLObjectReader.java.
{
         return (T) _xml.getNext();
     }
References javolution.xml.XMLObjectReader._xml.
read() [2/5]
public<T> T javolution.xml.XMLObjectReader.read (String localName, String uri) throws XMLStreamException package
Returns the object corresponding to the next nested element only if it has the specified local name and namespace URI.
Parameters
localName the local name.
uri the namespace URI.
Returns
the next content object or null if the name/uri does not match.
See also
XMLFormat.InputElement::get(String, String)
Definition at line 233 of file XMLObjectReader.java.
{
         return (T) _xml.get(localName, uri);
     }
References javolution.xml.XMLObjectReader._xml.
read() [3/5]
public<T> T javolution.xml.XMLObjectReader.read (String localName, String uri, Class< T > cls) throws XMLStreamException package
Returns the object corresponding to the next nested element only if it has the specified local name and namespace URI; the actual object type is identified by the specified class parameter.
Parameters
localName the local name.
uri the namespace URI.
cls the non-abstract class identifying the object to return.
Returns
the next content object or null if no match.
Definition at line 260 of file XMLObjectReader.java.
{
         return _xml.get(localName, uri, cls);
     }
References javolution.xml.XMLObjectReader._xml.
read() [4/5]
public<T> T javolution.xml.XMLObjectReader.read (String name) throws XMLStreamException package
Returns the object corresponding to the next nested element only if it has the specified local name.
Parameters
name the local name of the next element.
Returns
the next content object or null if the local name does not match.
See also
XMLFormat.InputElement::get(String)
Definition at line 218 of file XMLObjectReader.java.
{
         return (T) _xml.get(name);
     }
References javolution.xml.XMLObjectReader._xml.
read() [5/5]
public<T> T javolution.xml.XMLObjectReader.read (String name, Class< T > cls) throws XMLStreamException package
Returns the object corresponding to the next nested element only if it has the specified local name; the actual object type is identified by the specified class parameter.
Parameters
name the name of the element to match.
cls the non-abstract class identifying the object to return.
Returns
read(name, null, cls)
Definition at line 246 of file XMLObjectReader.java.
{
         return _xml.get(name, cls);
     }
References javolution.xml.XMLObjectReader._xml.
reset()
void javolution.xml.XMLObjectReader.reset ()
Resets this object reader for reuse.
Definition at line 286 of file XMLObjectReader.java.
{
         _xml.reset();
         _reader = null;
         _inputStream = null;
     }
References javolution.xml.XMLObjectReader._inputStream, javolution.xml.XMLObjectReader._reader, and javolution.xml.XMLObjectReader._xml.
Referenced by javolution.xml.XMLObjectReader.close(), and javolution.xml.ws.WebServiceClient.invoke().
setBinding()
XMLObjectReader javolution.xml.XMLObjectReader.setBinding (XMLBinding binding)
Sets the XML binding to use with this object reader.
Parameters
binding the XML binding to use.
Returns
this
Definition at line 165 of file XMLObjectReader.java.
{
         _xml.setBinding(binding);
         return this;
     }
References javolution.xml.XMLObjectReader._xml.
setInput() [1/3]
XMLObjectReader javolution.xml.XMLObjectReader.setInput (InputStream in) throws XMLStreamException
Sets the input stream source for this XML object reader (encoding retrieved from XML prolog if any).
Parameters
in the source input stream.
Returns
this
See also
XMLStreamReaderImpl::setInput(InputStream)
Definition at line 119 of file XMLObjectReader.java.
{
         if ((_inputStream != null) || (_reader != null))
             throw new IllegalStateException("Reader not closed or reset");
         _xml._reader.setInput(in);
         _inputStream = in;
         return this;
     }
References javolution.xml.XMLObjectReader._inputStream, javolution.xml.XMLObjectReader._reader, and javolution.xml.XMLObjectReader._xml.
Referenced by javolution.xml.ws.WebServiceClient.invoke(), and javolution.xml.XMLObjectReader.newInstance().
setInput() [2/3]
XMLObjectReader javolution.xml.XMLObjectReader.setInput (InputStream in, String encoding) throws XMLStreamException
Sets the input stream source and encoding for this XML object reader.
Parameters
in the input source.
encoding the associated encoding.
Returns
this
See also
XMLStreamReaderImpl::setInput(InputStream, String)
Definition at line 135 of file XMLObjectReader.java.
{
         if ((_inputStream != null) || (_reader != null))
             throw new IllegalStateException("Reader not closed or reset");
         _xml._reader.setInput(in, encoding);
         _inputStream = in;
         return this;
     }
References javolution.xml.XMLObjectReader._inputStream, javolution.xml.XMLObjectReader._reader, and javolution.xml.XMLObjectReader._xml.
setInput() [3/3]
XMLObjectReader javolution.xml.XMLObjectReader.setInput (Reader in) throws XMLStreamException
Sets the reader input source for this XML stream reader.
Parameters
in the source reader.
Returns
this
See also
XMLStreamReaderImpl::setInput(Reader)
Definition at line 151 of file XMLObjectReader.java.
{
         if ((_inputStream != null) || (_reader != null))
             throw new IllegalStateException("Reader not closed or reset");
         _xml._reader.setInput(in);
         _reader = in;
         return this;
     }
References javolution.xml.XMLObjectReader._inputStream, javolution.xml.XMLObjectReader._reader, and javolution.xml.XMLObjectReader._xml.
setReferenceResolver()
XMLObjectReader javolution.xml.XMLObjectReader.setReferenceResolver (XMLReferenceResolver referenceResolver)
Sets the XML reference resolver to use with this object reader (the same resolver can be used accross multiple readers).
Parameters
referenceResolver the XML reference resolver.
Returns
this
Definition at line 177 of file XMLObjectReader.java.
{
         _xml.setReferenceResolver(referenceResolver);
         return this;
     }
References javolution.xml.XMLObjectReader._xml.
Member Data Documentation
_inputStream
InputStream javolution.xml.XMLObjectReader._inputStream private
Holds input stream if any.
Definition at line 54 of file XMLObjectReader.java.
Referenced by javolution.xml.XMLObjectReader.close(), javolution.xml.XMLObjectReader.reset(), and javolution.xml.XMLObjectReader.setInput().
_reader
Reader javolution.xml.XMLObjectReader._reader private
Holds reader if any.
Definition at line 49 of file XMLObjectReader.java.
Referenced by javolution.xml.XMLObjectReader.close(), javolution.xml.XMLObjectReader.reset(), and javolution.xml.XMLObjectReader.setInput().
_xml
final XMLFormat.InputElement javolution.xml.XMLObjectReader._xml = new XMLFormat.InputElement() private
Hold the xml element used when parsing.
Definition at line 44 of file XMLObjectReader.java.
Referenced by javolution.xml.XMLObjectReader.getStreamReader(), javolution.xml.XMLObjectReader.hasNext(), javolution.xml.XMLObjectReader.read(), javolution.xml.XMLObjectReader.reset(), javolution.xml.XMLObjectReader.setBinding(), javolution.xml.XMLObjectReader.setInput(), and javolution.xml.XMLObjectReader.setReferenceResolver().
The documentation for this class was generated from the following file:
XMLObjectReader.java