Javolution 6.0.0 java: javolution.util.internal.map.FastMapImpl< K, V > Class Template Reference
javolution.util.internal.map.FastMapImpl< K, V > Class Template Reference
Public Member Functions
FastMapImpl (Equality<? super K > keyComparator, final Equality<? super V > valueComparator)
void clear ()
FastMapImpl< K, V > clone ()
boolean containsKey (Object key)
V get (Object key)
Iterator< Entry< K, V > > iterator ()
Equality<? super K > keyComparator ()
V put (K key, V value)
V putIfAbsent (K key, V value)
V remove (Object key)
boolean remove (Object key, Object value)
V replace (K key, V value)
boolean replace (K key, V oldValue, V newValue)
int size ()
MapService< K, V >[] split (int n)
Equality<? super V > valueComparator ()
boolean containsValue (Object value)
SetService< Entry< K, V > > entrySet ()
boolean isEmpty ()
SetService< K > keySet ()
void perform (Consumer< MapService< K, V >> action, MapService< K, V > view)
void perform (Consumer< T > action, T part)
void putAll (Map<? extends K, ? extends V > m)
MapService< K, V > threadSafe ()
void update (Consumer< MapService< K, V >> action, MapService< K, V > view)
void update (Consumer< T > action, T part)
CollectionService< V > values ()
Protected Member Functions
MapService< K, V > target ()
Package Attributes
transient MapEntryImpl< K, V > firstEntry = null
transient FractalMapImpl fractal = new FractalMapImpl()
transient MapEntryImpl< K, V > freeEntry = new MapEntryImpl<K, V>()
final Equality<? super K > keyComparator
transient MapEntryImpl< K, V > lastEntry = null
transient int size
final Equality<? super V > valueComparator
Private Member Functions
void attachEntry (MapEntryImpl< K, V > entry)
void detachEntry (MapEntryImpl< K, V > entry)
void readObject (java.io.ObjectInputStream s) throws java.io.IOException, ClassNotFoundException
void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
Private Attributes
MapService< K, V > target
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
The default FastMap implementation based on fractal maps. This implementation ensures that no more than 3/4 of the map capacity is ever wasted.
Definition at line 23 of file FastMapImpl.java.
Constructor & Destructor Documentation
FastMapImpl()
javolution.util.internal.map.FastMapImpl< K, V >.FastMapImpl (Equality<? super K > keyComparator, final Equality<? super V > valueComparator)
Definition at line 34 of file FastMapImpl.java.
{
         super(null); // Root.
         this.keyComparator = keyComparator;
         this.valueComparator = valueComparator;
     }
References javolution.util.internal.map.FastMapImpl< K, V >.keyComparator, and javolution.util.internal.map.FastMapImpl< K, V >.valueComparator.
Member Function Documentation
attachEntry()
void javolution.util.internal.map.FastMapImpl< K, V >.attachEntry (MapEntryImpl< K, V > entry) private
Definition at line 203 of file FastMapImpl.java.
{
         if (lastEntry != null) {
             lastEntry.next = entry;
             entry.previous = lastEntry;
         }
         lastEntry = entry;
         if (firstEntry == null) {
             firstEntry = entry;
         }
     }
References javolution.util.internal.map.FastMapImpl< K, V >.firstEntry, javolution.util.internal.map.FastMapImpl< K, V >.lastEntry, and javolution.util.internal.map.MapEntryImpl< K, V >.previous.
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.put(), and javolution.util.internal.map.FastMapImpl< K, V >.putIfAbsent().
clear()
void javolution.util.internal.map.FastMapImpl< K, V >.clear ()
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 42 of file FastMapImpl.java.
{
         firstEntry = null;
         lastEntry = null;
         fractal = new FractalMapImpl();
         size = 0;
     }
References javolution.util.internal.map.FastMapImpl< K, V >.firstEntry, javolution.util.internal.map.FastMapImpl< K, V >.fractal, javolution.util.internal.map.FastMapImpl< K, V >.lastEntry, and javolution.util.internal.map.FastMapImpl< K, V >.size.
clone()
FastMapImpl<K, V> javolution.util.internal.map.FastMapImpl< K, V >.clone ()
Returns a copy of this map; updates of the copy should not impact the original.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 50 of file FastMapImpl.java.
                                      { // Makes a copy.
         FastMapImpl<K, V> copy = new FastMapImpl<K, V>(keyComparator(),
                 valueComparator());
         copy.putAll(this);
         return copy;
     }
References javolution.util.internal.map.FastMapImpl< K, V >.keyComparator, javolution.util.internal.map.MapView< K, V >.putAll(), and javolution.util.internal.map.FastMapImpl< K, V >.valueComparator.
containsKey()
boolean javolution.util.internal.map.FastMapImpl< K, V >.containsKey (Object key)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 59 of file FastMapImpl.java.
{
         return fractal.getEntry(key, keyComparator.hashCodeOf((K) key)) != null;
     }
References javolution.util.internal.map.FastMapImpl< K, V >.fractal, javolution.util.internal.map.FractalMapImpl.getEntry(), javolution.util.function.Equality< T >.hashCodeOf(), and javolution.util.internal.map.FastMapImpl< K, V >.keyComparator.
containsValue()
boolean javolution.util.internal.map.MapView< K, V >.containsValue (Object value) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 248 of file MapView.java.
{
         return values().contains(value);
     }
References javolution.util.internal.map.MapView< K, V >.values().
detachEntry()
void javolution.util.internal.map.FastMapImpl< K, V >.detachEntry (MapEntryImpl< K, V > entry) private
Definition at line 214 of file FastMapImpl.java.
{
         if (entry == firstEntry) {
             firstEntry = entry.next;
         }
         if (entry == lastEntry) {
             lastEntry = entry.previous;
         }
         MapEntryImpl<K, V> previous = entry.previous;
         MapEntryImpl<K, V> next = entry.next;
         if (previous != null) {
             previous.next = next;
         }
         if (next != null) {
             next.previous = previous;
         }
     }
References javolution.util.internal.map.FastMapImpl< K, V >.firstEntry, javolution.util.internal.map.FastMapImpl< K, V >.lastEntry, javolution.util.internal.map.MapEntryImpl< K, V >.next, and javolution.util.internal.map.MapEntryImpl< K, V >.previous.
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.iterator(), and javolution.util.internal.map.FastMapImpl< K, V >.remove().
entrySet()
SetService<Entry<K, V> > javolution.util.internal.map.MapView< K, V >.entrySet () inherited
Returns a set view over the entries of this map. The set support adding/removing entries. Two entries are considered equals if they have the same key regardless of their values.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 253 of file MapView.java.
{
         return new EntrySet();
     }
Referenced by javolution.util.internal.map.MapView< K, V >.KeySet.KeySet(), and javolution.util.internal.map.MapView< K, V >.Values.Values().
get()
V javolution.util.internal.map.FastMapImpl< K, V >.get (Object key)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 65 of file FastMapImpl.java.
{
         MapEntryImpl<K, V> entry = fractal.getEntry(key,
                 keyComparator.hashCodeOf((K) key));
         if (entry == null) return null;
         return entry.value;
     }
References javolution.util.internal.map.FastMapImpl< K, V >.fractal, javolution.util.internal.map.FractalMapImpl.getEntry(), javolution.util.function.Equality< T >.hashCodeOf(), javolution.util.internal.map.FastMapImpl< K, V >.keyComparator, and javolution.util.internal.map.MapEntryImpl< K, V >.value.
isEmpty()
boolean javolution.util.internal.map.MapView< K, V >.isEmpty () inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 261 of file MapView.java.
{
         return iterator().hasNext();
     }
References javolution.util.internal.map.MapView< K, V >.iterator().
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.isEmpty().
iterator()
Iterator<Entry<K, V> > javolution.util.internal.map.FastMapImpl< K, V >.iterator ()
Returns an iterator over this map entries.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 73 of file FastMapImpl.java.
{
         return new Iterator<Entry<K, V>>() {
             MapEntryImpl<K, V> current;
             MapEntryImpl<K, V> next = firstEntry;
             @Override
             public boolean hasNext() {
                 return (next != null);
             }
             @Override
             public java.util.Map.Entry<K, V> next() {
                 if (next == null) throw new NoSuchElementException();
                 current = next;
                 next = next.next;
                 return current;
             }
             @Override
             public void remove() {
                 if (current == null) throw new IllegalStateException();
                 fractal.removeEntry(current.key, current.hash);
                 detachEntry(current); // Entry is not referenced anymore and will be gc.
                 size--;
             }
         };
     }
References javolution.util.internal.map.FastMapImpl< K, V >.detachEntry(), javolution.util.internal.map.FastMapImpl< K, V >.firstEntry, javolution.util.internal.map.FastMapImpl< K, V >.fractal, javolution.util.internal.map.MapEntryImpl< K, V >.hash, javolution.util.internal.map.MapEntryImpl< K, V >.key, javolution.util.internal.map.MapEntryImpl< K, V >.next, javolution.util.internal.map.FractalMapImpl.removeEntry(), and javolution.util.internal.map.FastMapImpl< K, V >.size.
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.writeObject().
keyComparator()
Equality<? super K> javolution.util.internal.map.FastMapImpl< K, V >.keyComparator ()
Returns the key comparator used for key equality or order if the map is sorted.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 103 of file FastMapImpl.java.
{
         return keyComparator;
     }
References javolution.util.internal.map.FastMapImpl< K, V >.keyComparator.
keySet()
SetService<K> javolution.util.internal.map.MapView< K, V >.keySet () inherited
Returns a set view over the key of this map, the set support adding new key for which the value is automatically
null
.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 272 of file MapView.java.
{
         return new KeySet();
     }
Referenced by javolution.util.FastSet< Index >.FastSet().
perform() [1/2]
void javolution.util.internal.map.MapView< K, V >.perform (Consumer< MapService< K, V >> action, MapService< K, V > view) inherited
Reimplemented in javolution.util.internal.map.ParallelMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Definition at line 277 of file MapView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
References javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.perform().
perform() [2/2]
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
put()
V javolution.util.internal.map.FastMapImpl< K, V >.put (K key, V value)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 109 of file FastMapImpl.java.
{
         int hash = keyComparator.hashCodeOf(key);
         MapEntryImpl<K, V> tmp = fractal.addEntry(freeEntry, key, hash);
         if (tmp == freeEntry) { // New entry.
             freeEntry = new MapEntryImpl<K, V>();
             attachEntry(tmp);
             size++;
             tmp.value = value;
             return null;
         } else { // Existing entry.
             V oldValue = (V) tmp.value;
             tmp.value = value;
             return oldValue;
         }
     }
References javolution.util.internal.map.FractalMapImpl.addEntry(), javolution.util.internal.map.FastMapImpl< K, V >.attachEntry(), javolution.util.internal.map.FastMapImpl< K, V >.fractal, javolution.util.internal.map.FastMapImpl< K, V >.freeEntry, javolution.util.function.Equality< T >.hashCodeOf(), javolution.util.internal.map.FastMapImpl< K, V >.keyComparator, javolution.util.internal.map.FastMapImpl< K, V >.size, and javolution.util.internal.map.MapEntryImpl< K, V >.value.
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.readObject().
putAll()
void javolution.util.internal.map.MapView< K, V >.putAll (Map<? extends K, ? extends V > m) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 290 of file MapView.java.
{
         Iterator<?> it = m.entrySet().iterator();
         while (it.hasNext()) {
             Entry<K, V> e = (Entry<K, V>) it.next();
             put(e.getKey(), e.getValue());
         }
     }
References javolution.util.internal.map.MapView< K, V >.put().
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.clone().
putIfAbsent()
V javolution.util.internal.map.FastMapImpl< K, V >.putIfAbsent (K key, V value)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 127 of file FastMapImpl.java.
{
         int hash = keyComparator.hashCodeOf(key);
         MapEntryImpl<K, V> tmp = fractal.addEntry(freeEntry, key, hash);
         if (tmp == freeEntry) { // New entry.
             freeEntry = new MapEntryImpl<K, V>();
             attachEntry(tmp);
             size++;
             tmp.value = value;
             return null;
         } else { // Existing entry.
             return (V) tmp.value;
         }
     }
References javolution.util.internal.map.FractalMapImpl.addEntry(), javolution.util.internal.map.FastMapImpl< K, V >.attachEntry(), javolution.util.internal.map.FastMapImpl< K, V >.fractal, javolution.util.internal.map.FastMapImpl< K, V >.freeEntry, javolution.util.function.Equality< T >.hashCodeOf(), javolution.util.internal.map.FastMapImpl< K, V >.keyComparator, javolution.util.internal.map.FastMapImpl< K, V >.size, and javolution.util.internal.map.MapEntryImpl< K, V >.value.
readObject()
void javolution.util.internal.map.FastMapImpl< K, V >.readObject (java.io.ObjectInputStream s) throws java.io.IOException, ClassNotFoundException private
For serialization support
Definition at line 233 of file FastMapImpl.java.
{
         s.defaultReadObject(); // Deserialize comparator.
         fractal = new FractalMapImpl();
         freeEntry = new MapEntryImpl<K, V>();
         int n = s.readInt();
         for (int i = 0; i < n; i++) {
             put((K) s.readObject(), (V) s.readObject());
         }
     }
References javolution.util.internal.map.FastMapImpl< K, V >.fractal, javolution.util.internal.map.FastMapImpl< K, V >.freeEntry, and javolution.util.internal.map.FastMapImpl< K, V >.put().
remove() [1/2]
V javolution.util.internal.map.FastMapImpl< K, V >.remove (Object key)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 143 of file FastMapImpl.java.
{
         MapEntryImpl<K, V> entry = fractal.removeEntry(key,
                 keyComparator.hashCodeOf((K) key));
         if (entry == null) return null;
         detachEntry(entry); // Entry is not referenced anymore and will be gc.
         size--;
         return entry.value;
     }
References javolution.util.internal.map.FastMapImpl< K, V >.detachEntry(), javolution.util.internal.map.FastMapImpl< K, V >.fractal, javolution.util.function.Equality< T >.hashCodeOf(), javolution.util.internal.map.FastMapImpl< K, V >.keyComparator, javolution.util.internal.map.FractalMapImpl.removeEntry(), javolution.util.internal.map.FastMapImpl< K, V >.size, and javolution.util.internal.map.MapEntryImpl< K, V >.value.
remove() [2/2]
boolean javolution.util.internal.map.FastMapImpl< K, V >.remove (Object key, Object value)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 154 of file FastMapImpl.java.
{
         int hash = keyComparator.hashCodeOf((K) key);
         MapEntryImpl<K, V> entry = fractal.getEntry(key, hash);
         if (entry == null) return false;
         if (!valueComparator.areEqual((V) entry.value, (V) value)) return false;
         fractal.removeEntry(key, hash);
         detachEntry(entry); // Entry is not referenced anymore and will be gc.
         size--;
         return true;
     }
References javolution.util.function.Equality< T >.areEqual(), javolution.util.internal.map.FastMapImpl< K, V >.detachEntry(), javolution.util.internal.map.FastMapImpl< K, V >.fractal, javolution.util.internal.map.FractalMapImpl.getEntry(), javolution.util.function.Equality< T >.hashCodeOf(), javolution.util.internal.map.FastMapImpl< K, V >.keyComparator, javolution.util.internal.map.FractalMapImpl.removeEntry(), javolution.util.internal.map.FastMapImpl< K, V >.size, javolution.util.internal.map.MapEntryImpl< K, V >.value, and javolution.util.internal.map.FastMapImpl< K, V >.valueComparator.
replace() [1/2]
boolean javolution.util.internal.map.FastMapImpl< K, V >.replace (K key, V oldValue, V newValue)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 178 of file FastMapImpl.java.
{
         MapEntryImpl<K, V> entry = fractal.getEntry(key,
                 keyComparator.hashCodeOf(key));
         if (entry == null) return false;
         if (!valueComparator.areEqual(entry.value, oldValue)) return false;
         entry.value = newValue;
         return true;
     }
References javolution.util.function.Equality< T >.areEqual(), javolution.util.internal.map.FastMapImpl< K, V >.fractal, javolution.util.internal.map.FractalMapImpl.getEntry(), javolution.util.function.Equality< T >.hashCodeOf(), javolution.util.internal.map.FastMapImpl< K, V >.keyComparator, javolution.util.internal.map.MapEntryImpl< K, V >.value, and javolution.util.internal.map.FastMapImpl< K, V >.valueComparator.
replace() [2/2]
V javolution.util.internal.map.FastMapImpl< K, V >.replace (K key, V value)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 167 of file FastMapImpl.java.
{
         MapEntryImpl<K, V> entry = fractal.getEntry(key,
                 keyComparator.hashCodeOf(key));
         if (entry == null) return null;
         V oldValue = entry.value;
         entry.value = value;
         return oldValue;
     }
References javolution.util.internal.map.FastMapImpl< K, V >.fractal, javolution.util.internal.map.FractalMapImpl.getEntry(), javolution.util.function.Equality< T >.hashCodeOf(), javolution.util.internal.map.FastMapImpl< K, V >.keyComparator, and javolution.util.internal.map.MapEntryImpl< K, V >.value.
size()
int javolution.util.internal.map.FastMapImpl< K, V >.size ()
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 188 of file FastMapImpl.java.
                       {
         return size;
     }
References javolution.util.internal.map.FastMapImpl< K, V >.size.
split()
MapService<K, V> [] javolution.util.internal.map.FastMapImpl< K, V >.split (int n)
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 194 of file FastMapImpl.java.
{
         return new MapService[] { this }; // No splitting supported yet.
     }
target()
MapService<K, V> javolution.util.internal.map.MapView< K, V >.target () protected inherited
Returns the actual target
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 378 of file MapView.java.
{
         return target;
     }
References javolution.util.internal.map.MapView< K, V >.target.
threadSafe()
MapService<K, V> javolution.util.internal.map.MapView< K, V >.threadSafe () inherited
Returns a thread-safe version of this service (used during parallel updates).
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 356 of file MapView.java.
{
         return new SharedMapImpl<K, V>(this);
     }
update() [1/2]
void javolution.util.internal.map.MapView< K, V >.update (Consumer< MapService< K, V >> action, MapService< K, V > view) inherited
Reimplemented in javolution.util.internal.map.ParallelMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Definition at line 361 of file MapView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.update(action, view);
         }
     }
References javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.update().
update() [2/2]
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
valueComparator()
Equality<? super V> javolution.util.internal.map.FastMapImpl< K, V >.valueComparator ()
Returns the value comparator used for value equality.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 199 of file FastMapImpl.java.
{
         return valueComparator;
     }
References javolution.util.internal.map.FastMapImpl< K, V >.valueComparator.
values()
CollectionService<V> javolution.util.internal.map.MapView< K, V >.values () inherited
Returns a collection view over the values of this map, the collection support value/entry removal but not adding new values.
Implements javolution.util.service.MapService< K, V >.
Definition at line 373 of file MapView.java.
{
         return new Values();
     }
Referenced by javolution.util.internal.map.MapView< K, V >.containsValue().
writeObject()
void javolution.util.internal.map.FastMapImpl< K, V >.writeObject (java.io.ObjectOutputStream s) throws java.io.IOException private
For serialization support
Definition at line 245 of file FastMapImpl.java.
{
         s.defaultWriteObject(); // Serialize comparators.
         s.writeInt(size);
         Iterator<Entry<K, V>> it = iterator();
         while (it.hasNext()) {
             Entry<K, V> e = it.next();
             s.writeObject(e.getKey());
             s.writeObject(e.getValue());
         }
     }
References javolution.util.internal.map.FastMapImpl< K, V >.iterator(), and javolution.util.internal.map.FastMapImpl< K, V >.size.
Member Data Documentation
firstEntry
transient MapEntryImpl<K, V> javolution.util.internal.map.FastMapImpl< K, V >.firstEntry = null package
Definition at line 26 of file FastMapImpl.java.
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.attachEntry(), javolution.util.internal.map.FastMapImpl< K, V >.clear(), javolution.util.internal.map.FastMapImpl< K, V >.detachEntry(), and javolution.util.internal.map.FastMapImpl< K, V >.iterator().
fractal
transient FractalMapImpl javolution.util.internal.map.FastMapImpl< K, V >.fractal = new FractalMapImpl() package
Definition at line 27 of file FastMapImpl.java.
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.clear(), javolution.util.internal.map.FastMapImpl< K, V >.containsKey(), javolution.util.internal.map.FastMapImpl< K, V >.get(), javolution.util.internal.map.FastMapImpl< K, V >.iterator(), javolution.util.internal.map.FastMapImpl< K, V >.put(), javolution.util.internal.map.FastMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.FastMapImpl< K, V >.readObject(), javolution.util.internal.map.FastMapImpl< K, V >.remove(), and javolution.util.internal.map.FastMapImpl< K, V >.replace().
freeEntry
transient MapEntryImpl<K, V> javolution.util.internal.map.FastMapImpl< K, V >.freeEntry = new MapEntryImpl<K, V>() package
Definition at line 28 of file FastMapImpl.java.
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.put(), javolution.util.internal.map.FastMapImpl< K, V >.putIfAbsent(), and javolution.util.internal.map.FastMapImpl< K, V >.readObject().
keyComparator
final Equality<? super K> javolution.util.internal.map.FastMapImpl< K, V >.keyComparator package
Definition at line 29 of file FastMapImpl.java.
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.clone(), javolution.util.internal.map.FastMapImpl< K, V >.containsKey(), javolution.util.internal.map.FastMapImpl< K, V >.FastMapImpl(), javolution.util.internal.map.FastMapImpl< K, V >.get(), javolution.util.internal.map.FastMapImpl< K, V >.keyComparator(), javolution.util.internal.map.FastMapImpl< K, V >.put(), javolution.util.internal.map.FastMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.FastMapImpl< K, V >.remove(), and javolution.util.internal.map.FastMapImpl< K, V >.replace().
lastEntry
transient MapEntryImpl<K, V> javolution.util.internal.map.FastMapImpl< K, V >.lastEntry = null package
Definition at line 30 of file FastMapImpl.java.
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.attachEntry(), javolution.util.internal.map.FastMapImpl< K, V >.clear(), and javolution.util.internal.map.FastMapImpl< K, V >.detachEntry().
serialVersionUID
final long javolution.util.internal.map.FastMapImpl< K, V >.serialVersionUID = 0x600L static private
Definition at line 25 of file FastMapImpl.java.
size
transient int javolution.util.internal.map.FastMapImpl< K, V >.size package
Definition at line 31 of file FastMapImpl.java.
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.clear(), javolution.util.internal.map.FastMapImpl< K, V >.iterator(), javolution.util.internal.map.FastMapImpl< K, V >.put(), javolution.util.internal.map.FastMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.FastMapImpl< K, V >.remove(), javolution.util.internal.map.FastMapImpl< K, V >.size(), and javolution.util.internal.map.FastMapImpl< K, V >.writeObject().
target
MapService<K, V> javolution.util.internal.map.MapView< K, V >.target private inherited
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 213 of file MapView.java.
Referenced by javolution.util.internal.map.AtomicMapImpl< K, V >.AtomicMapImpl(), javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >.AtomicSortedMapImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.clear(), javolution.util.internal.map.MapView< K, V >.clone(), javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.SharedMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >.comparator(), javolution.util.internal.map.SequentialMapImpl< K, V >.containsKey(), javolution.util.internal.map.ParallelMapImpl< K, V >.containsKey(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.containsKey(), javolution.util.internal.map.SharedMapImpl< K, V >.containsKey(), javolution.util.internal.map.SharedMapImpl< K, V >.containsValue(), javolution.util.internal.map.SequentialMapImpl< K, V >.get(), javolution.util.internal.map.ParallelMapImpl< K, V >.get(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.get(), javolution.util.internal.map.SharedMapImpl< K, V >.get(), javolution.util.internal.map.SharedMapImpl< K, V >.isEmpty(), javolution.util.internal.map.SequentialMapImpl< K, V >.iterator(), javolution.util.internal.map.ParallelMapImpl< K, V >.iterator(), javolution.util.internal.map.SequentialMapImpl< K, V >.keyComparator(), javolution.util.internal.map.ParallelMapImpl< K, V >.keyComparator(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.keyComparator(), javolution.util.internal.map.SharedMapImpl< K, V >.keyComparator(), javolution.util.internal.map.MapView< K, V >.MapView(), javolution.util.internal.map.ParallelMapImpl< K, V >.ParallelMapImpl(), javolution.util.internal.map.ParallelMapImpl< K, V >.perform(), javolution.util.internal.map.MapView< K, V >.perform(), javolution.util.internal.map.SequentialMapImpl< K, V >.put(), javolution.util.internal.map.ParallelMapImpl< K, V >.put(), javolution.util.internal.map.AtomicMapImpl< K, V >.put(), javolution.util.internal.map.SharedMapImpl< K, V >.put(), javolution.util.internal.map.AtomicMapImpl< K, V >.putAll(), javolution.util.internal.map.SharedMapImpl< K, V >.putAll(), javolution.util.internal.map.AtomicMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.SharedMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.SequentialMapImpl< K, V >.remove(), javolution.util.internal.map.ParallelMapImpl< K, V >.remove(), javolution.util.internal.map.AtomicMapImpl< K, V >.remove(), javolution.util.internal.map.SharedMapImpl< K, V >.remove(), javolution.util.internal.map.AtomicMapImpl< K, V >.replace(), javolution.util.internal.map.SharedMapImpl< K, V >.replace(), javolution.util.internal.map.SequentialMapImpl< K, V >.SequentialMapImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.SharedMapImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.size(), javolution.util.internal.map.SharedMapImpl< K, V >.split(), javolution.util.internal.map.MapView< K, V >.split(), javolution.util.internal.map.MapView< K, V >.target(), javolution.util.internal.map.AtomicMapImpl< K, V >.targetView(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.UnmodifiableMapImpl(), javolution.util.internal.map.ParallelMapImpl< K, V >.update(), javolution.util.internal.map.AtomicMapImpl< K, V >.update(), javolution.util.internal.map.MapView< K, V >.update(), javolution.util.internal.map.SequentialMapImpl< K, V >.valueComparator(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.valueComparator(), javolution.util.internal.map.ParallelMapImpl< K, V >.valueComparator(), and javolution.util.internal.map.SharedMapImpl< K, V >.valueComparator().
valueComparator
final Equality<? super V> javolution.util.internal.map.FastMapImpl< K, V >.valueComparator package
Definition at line 32 of file FastMapImpl.java.
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.clone(), javolution.util.internal.map.FastMapImpl< K, V >.FastMapImpl(), javolution.util.internal.map.FastMapImpl< K, V >.remove(), javolution.util.internal.map.FastMapImpl< K, V >.replace(), and javolution.util.internal.map.FastMapImpl< K, V >.valueComparator().
The documentation for this class was generated from the following file:
FastMapImpl.java