Javolution 6.0.0 java: javolution.xml.sax.SAX2ReaderImpl.Proxy Class Reference
javolution.xml.sax.SAX2ReaderImpl.Proxy Class Reference
Public Member Functions
Proxy ()
void setDocumentLocator (Locator locator)
void startDocument () throws SAXException
void endDocument () throws SAXException
void startPrefixMapping (CharArray prefix, CharArray uri) throws SAXException
void endPrefixMapping (CharArray prefix) throws SAXException
void startElement (CharArray namespaceURI, CharArray localName, CharArray qName, javolution.xml.sax.Attributes atts) throws SAXException
void endElement (CharArray namespaceURI, CharArray localName, CharArray qName) throws SAXException
void characters (char ch[], int start, int length) throws SAXException
void ignorableWhitespace (char ch[], int start, int length) throws SAXException
void processingInstruction (CharArray target, CharArray data) throws SAXException
void skippedEntity (CharArray name) throws SAXException
int getLength ()
String getURI (int index)
String getLocalName (int index)
String getQName (int index)
String getType (int index)
String getValue (int index)
int getIndex (String uri, String localName)
int getIndex (String qName)
String getType (String uri, String localName)
String getType (String qName)
String getValue (String uri, String localName)
String getValue (String qName)
void startElement (CharArray uri, CharArray localName, CharArray qName, Attributes atts) throws SAXException
CharArray getType (CharSequence uri, CharSequence localName)
CharArray getType (CharSequence qName)
CharArray getValue (CharSequence uri, CharSequence localName)
CharArray getValue (CharSequence qName)
int getIndex (CharSequence uri, CharSequence localName)
int getIndex (CharSequence qName)
Private Attributes
ContentHandler _sax2Handler = DEFAULT_HANDLER
javolution.xml.sax.Attributes _attributes
Detailed Description
This class defines the proxy for content handler and attributes.
Definition at line 161 of file SAX2ReaderImpl.java.
Constructor & Destructor Documentation
Proxy()
javolution.xml.sax.SAX2ReaderImpl.Proxy.Proxy ()
Default constructor.
Definition at line 178 of file SAX2ReaderImpl.java.
 {}
Member Function Documentation
characters()
void javolution.xml.sax.SAX2ReaderImpl.Proxy.characters (char ch[], int start, int length) throws SAXException
Receives notification of character data.
Parameters
ch the characters from the XML document.
start the start position in the array.
length the number of characters to read from the array.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implements javolution.xml.sax.ContentHandler.
Definition at line 224 of file SAX2ReaderImpl.java.
{
             _sax2Handler.characters(ch, start, length);
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._sax2Handler, and javolution.xml.sax.ContentHandler.characters().
endDocument()
void javolution.xml.sax.SAX2ReaderImpl.Proxy.endDocument () throws SAXException
Receives notification of the end of a document.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implements javolution.xml.sax.ContentHandler.
Definition at line 191 of file SAX2ReaderImpl.java.
{
             _sax2Handler.endDocument();
             _sax2Handler = DEFAULT_HANDLER;
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._sax2Handler, javolution.xml.sax.SAX2ReaderImpl.DEFAULT_HANDLER, and javolution.xml.sax.ContentHandler.endDocument().
endElement()
void javolution.xml.sax.SAX2ReaderImpl.Proxy.endElement (CharArray uri, CharArray localName, CharArray qName) throws SAXException
Receives notification of the end of an element.
Parameters
uri the namespace URI, or an empty character sequence if the element has no Namespace URI or if namespace processing is not being performed.
localName the local name (without prefix), or an empty character sequence if namespace processing is not being performed.
qName the qualified XML 1.0 name (with prefix), or an empty character sequence if qualified names are not available.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implements javolution.xml.sax.ContentHandler.
Definition at line 217 of file SAX2ReaderImpl.java.
{
             _sax2Handler.endElement(namespaceURI.toString(),
                     localName.toString(), qName.toString());
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._sax2Handler, and javolution.xml.sax.ContentHandler.endElement().
endPrefixMapping()
void javolution.xml.sax.SAX2ReaderImpl.Proxy.endPrefixMapping (CharArray prefix) throws SAXException
Ends the scope of a prefix-URI mapping.
Parameters
prefix the prefix that was being mapping.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implements javolution.xml.sax.ContentHandler.
Definition at line 203 of file SAX2ReaderImpl.java.
{
             _sax2Handler.endPrefixMapping(prefix.toString());
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._sax2Handler, and javolution.xml.sax.ContentHandler.endPrefixMapping().
getIndex() [1/4]
int javolution.xml.sax.Attributes.getIndex (CharSequence qName) inherited
Looks up the index of an attribute by XML 1.0 qualified name (convenience method). This method returns the index of the attribute whose name has the same character content as the specified qName.
Parameters
qName the qualified (prefixed) name.
Returns
the index of the attribute, or -1 if it does not appear in the list.
Implemented in javolution.xml.internal.stream.AttributesImpl.
getIndex() [2/4]
int javolution.xml.sax.Attributes.getIndex (CharSequence uri, CharSequence localName) inherited
Looks up the index of an attribute by namespace name (convenience method). This method returns the index of the attribute whose uri/localName have the same character content as the specified uri/localName.
Parameters
uri the Namespace URI, or an empty character sequence if the name has no Namespace URI.
localName the attribute's local name.
Returns
the index of the attribute, or -1 if it does not appear in the list.
Implemented in javolution.xml.internal.stream.AttributesImpl.
getIndex() [3/4]
int javolution.xml.sax.SAX2ReaderImpl.Proxy.getIndex (String qName)
Definition at line 294 of file SAX2ReaderImpl.java.
{
             return (qName != null && _attributes != null ? _attributes
                     .getIndex(toCharSequence(qName)) : -1);
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes, javolution.xml.sax.SAX2ReaderImpl.Proxy.getIndex(), and javolution.xml.sax.SAX2ReaderImpl.toCharSequence().
getIndex() [4/4]
int javolution.xml.sax.SAX2ReaderImpl.Proxy.getIndex (String uri, String localName)
Definition at line 287 of file SAX2ReaderImpl.java.
{
             return (uri != null && localName != null && _attributes != null ? _attributes
                     .getIndex(toCharSequence(uri), toCharSequence(localName))
                     : -1);
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes, and javolution.xml.sax.SAX2ReaderImpl.toCharSequence().
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.getIndex().
getLength()
int javolution.xml.sax.SAX2ReaderImpl.Proxy.getLength ()
Returns the number of attributes in this list of attributes.
Returns
the number of attributes.
Implements javolution.xml.sax.Attributes.
Definition at line 248 of file SAX2ReaderImpl.java.
{
             return (_attributes != null ? _attributes.getLength() : 0);
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes, and javolution.xml.sax.Attributes.getLength().
getLocalName()
String javolution.xml.sax.SAX2ReaderImpl.Proxy.getLocalName (int index)
Looks up an attribute's local name by index.
Parameters
index the attribute index (zero-based).
Returns
the local name, or an empty character sequence if Namespace processing is not being performed, or null if the index is out of range.
See also
getLength
Implements javolution.xml.sax.Attributes.
Definition at line 260 of file SAX2ReaderImpl.java.
{
             CharSequence chars = (_attributes != null ? _attributes
                     .getLocalName(index) : null);
             return (chars != null ? chars.toString() : "");
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes, and javolution.xml.sax.Attributes.getLocalName().
getQName()
String javolution.xml.sax.SAX2ReaderImpl.Proxy.getQName (int index)
Looks up an attribute's XML 1.0 qualified name by index.
Parameters
index the attribute index (zero-based).
Returns
the XML 1.0 qualified name, or an empty character sequence if none is available, or null if the index is out of range.
See also
getLength
Implements javolution.xml.sax.Attributes.
Definition at line 267 of file SAX2ReaderImpl.java.
{
             CharSequence chars = (_attributes != null ? _attributes
                     .getQName(index) : null);
             return (chars != null ? chars.toString() : "");
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes, and javolution.xml.sax.Attributes.getQName().
getType() [1/5]
CharArray javolution.xml.sax.Attributes.getType (CharSequence qName) inherited
Looks up an attribute's type by XML 1.0 qualified name. This method returns the type of the attribute whose qName has the same character content as the specified qName.
Parameters
qName The XML 1.0 qualified name.
Returns
the attribute type as a string, or null if the attribute is not in the list or if qualified names are not available.
Implemented in javolution.xml.internal.stream.AttributesImpl.
getType() [2/5]
CharArray javolution.xml.sax.Attributes.getType (CharSequence uri, CharSequence localName) inherited
Looks up an attribute's type by Namespace name (convenience method). This method returns the type of the attribute whose uri/localName have the same character content as the specified uri/localName.
Parameters
uri the Namespace URI, or an empty string if the name has no Namespace URI.
localName the local name of the attribute.
Returns
the attribute type as a string, or null if the attribute is not in the list or if Namespace processing is not being performed.
Implemented in javolution.xml.internal.stream.AttributesImpl.
getType() [3/5]
String javolution.xml.sax.SAX2ReaderImpl.Proxy.getType (int index)
Looks up an attribute's type by index.
The attribute type is one of the strings "CDATA", "ID", "IDREF", "IDREFS", "NMTOKEN", "NMTOKENS", "ENTITY", "ENTITIES", or "NOTATION" (always in upper case).
If the parser has not read a declaration for the attribute, or if the parser does not report attribute types, then it must return the value "CDATA" as stated in the XML 1.0 Recommentation (clause 3.3.3, "Attribute-TextBuilder Normalization").
For an enumerated attribute that is not a notation, the parser will report the type as "NMTOKEN".
Parameters
index the attribute index (zero-based).
Returns
the attribute's type as a string, or null if the index is out of range.
See also
getLength
Implements javolution.xml.sax.Attributes.
Definition at line 274 of file SAX2ReaderImpl.java.
{
             return (_attributes != null ? _attributes.getType(index).toString()
                     : null);
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes, javolution.xml.sax.Attributes.getType(), and javolution.text.CharArray.toString().
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.getType().
getType() [4/5]
String javolution.xml.sax.SAX2ReaderImpl.Proxy.getType (String qName)
Definition at line 307 of file SAX2ReaderImpl.java.
{
             return (qName != null && _attributes != null ? _attributes.getType(
                     toCharSequence(qName)).toString() : null);
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes, javolution.xml.sax.Attributes.getType(), and javolution.xml.sax.SAX2ReaderImpl.toCharSequence().
getType() [5/5]
String javolution.xml.sax.SAX2ReaderImpl.Proxy.getType (String uri, String localName)
Definition at line 300 of file SAX2ReaderImpl.java.
{
             return (uri != null && localName != null && _attributes != null ? _attributes
                     .getType(toCharSequence(uri), toCharSequence(localName))
                     .toString() : null);
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes, javolution.xml.sax.SAX2ReaderImpl.Proxy.getType(), and javolution.xml.sax.SAX2ReaderImpl.toCharSequence().
getURI()
String javolution.xml.sax.SAX2ReaderImpl.Proxy.getURI (int index)
Looks up an attribute's Namespace URI by index.
Parameters
index the attribute index (zero-based).
Returns
the Namespace URI, or an empty character sequence if none is available, or null if the index is out of range.
See also
getLength
Implements javolution.xml.sax.Attributes.
Definition at line 253 of file SAX2ReaderImpl.java.
{
             CharSequence chars = (_attributes != null ? _attributes
                     .getURI(index) : null);
             return (chars != null ? chars.toString() : "");
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes, and javolution.xml.sax.Attributes.getURI().
getValue() [1/5]
CharArray javolution.xml.sax.Attributes.getValue (CharSequence qName) inherited
Looks up an attribute's value by XML 1.0 qualified name (convenience method). This method returns the value of the attribute whose qName has the same character content as the specified qName.
Parameters
qName The XML 1.0 qualified name.
Returns
the attribute value as a character sequence, or null if the attribute is not in the list or if qualified names are not available.
Implemented in javolution.xml.internal.stream.AttributesImpl.
getValue() [2/5]
CharArray javolution.xml.sax.Attributes.getValue (CharSequence uri, CharSequence localName) inherited
Looks up an attribute's value by Namespace name (convenience method). This method returns the value of the attribute whose uri/localName have the same character content as the specified uri/localName.
Parameters
uri the Namespace URI, or the empty string if the name has no Namespace URI.
localName the local name of the attribute.
Returns
the attribute value as a character sequence, or null if the attribute is not in the list.
Implemented in javolution.xml.internal.stream.AttributesImpl.
getValue() [3/5]
String javolution.xml.sax.SAX2ReaderImpl.Proxy.getValue (int index)
Looks up an attribute's value by index.
If the attribute value is a list of tokens (IDREFS, ENTITIES, or NMTOKENS), the tokens will be concatenated into a single string with each token separated by a single space.
Parameters
index the attribute index (zero-based).
Returns
the attribute's value as a character sequence, null if the index is out of range.
See also
getLength
Implements javolution.xml.sax.Attributes.
Definition at line 280 of file SAX2ReaderImpl.java.
{
             CharSequence chars = (_attributes != null ? _attributes
                     .getValue(index) : null);
             return (chars != null ? chars.toString() : null);
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes, and javolution.xml.sax.Attributes.getValue().
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.getValue().
getValue() [4/5]
String javolution.xml.sax.SAX2ReaderImpl.Proxy.getValue (String qName)
Definition at line 324 of file SAX2ReaderImpl.java.
{
             return (qName != null && _attributes != null ? _attributes
                     .getValue(toCharSequence(qName)).toString() : null);
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes, javolution.xml.sax.SAX2ReaderImpl.Proxy.getValue(), and javolution.xml.sax.SAX2ReaderImpl.toCharSequence().
getValue() [5/5]
String javolution.xml.sax.SAX2ReaderImpl.Proxy.getValue (String uri, String localName)
Definition at line 313 of file SAX2ReaderImpl.java.
{
             return (uri != null
                     && localName != null
                     && _attributes != null
                     && _attributes.getValue(toCharSequence(uri),
                             toCharSequence(localName)) != null ? _attributes
                     .getValue(toCharSequence(uri), toCharSequence(localName))
                     .toString() : null);
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes, javolution.xml.sax.Attributes.getValue(), javolution.xml.sax.SAX2ReaderImpl.Proxy.getValue(), and javolution.xml.sax.SAX2ReaderImpl.toCharSequence().
ignorableWhitespace()
void javolution.xml.sax.SAX2ReaderImpl.Proxy.ignorableWhitespace (char ch[], int start, int length) throws SAXException
Receives notification of ignorable whitespace in element content.
Parameters
ch the characters from the XML document.
start the start position in the array.
length the number of characters to read from the array.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implements javolution.xml.sax.ContentHandler.
Definition at line 230 of file SAX2ReaderImpl.java.
{
             _sax2Handler.ignorableWhitespace(ch, start, length);
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._sax2Handler, and javolution.xml.sax.ContentHandler.ignorableWhitespace().
processingInstruction()
void javolution.xml.sax.SAX2ReaderImpl.Proxy.processingInstruction (CharArray target, CharArray data) throws SAXException
Receives notification of a processing instruction.
Parameters
target the processing instruction target.
data the processing instruction data, or null if none was supplied. The data does not include any whitespace separating it from the target.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implements javolution.xml.sax.ContentHandler.
Definition at line 236 of file SAX2ReaderImpl.java.
{
             _sax2Handler.processingInstruction(target.toString(),
                     data.toString());
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._sax2Handler, and javolution.xml.sax.ContentHandler.processingInstruction().
setDocumentLocator()
void javolution.xml.sax.SAX2ReaderImpl.Proxy.setDocumentLocator (Locator locator)
Receives an object for locating the origin of SAX document events.
Parameters
locator the document locator.
Implements javolution.xml.sax.ContentHandler.
Definition at line 181 of file SAX2ReaderImpl.java.
{
             _sax2Handler.setDocumentLocator(locator);
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._sax2Handler, and javolution.xml.sax.ContentHandler.setDocumentLocator().
skippedEntity()
void javolution.xml.sax.SAX2ReaderImpl.Proxy.skippedEntity (CharArray name) throws SAXException
Receives notification of a skipped entity.
Parameters
name the name of the skipped entity. If it is a parameter entity, the name will begin with '', and if it is the external DTD subset, it will be the character sequence "[dtd]".
Exceptions
org.xml.sax.SAXException any SAX exception.
Implements javolution.xml.sax.ContentHandler.
Definition at line 243 of file SAX2ReaderImpl.java.
{
             _sax2Handler.skippedEntity(name.toString());
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._sax2Handler, and javolution.xml.sax.ContentHandler.skippedEntity().
startDocument()
void javolution.xml.sax.SAX2ReaderImpl.Proxy.startDocument () throws SAXException
Receives notification of the beginning of a document.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implements javolution.xml.sax.ContentHandler.
Definition at line 186 of file SAX2ReaderImpl.java.
{
             _sax2Handler.startDocument();
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._sax2Handler, and javolution.xml.sax.ContentHandler.startDocument().
startElement() [1/2]
void javolution.xml.sax.SAX2ReaderImpl.Proxy.startElement (CharArray namespaceURI, CharArray localName, CharArray qName, javolution.xml.sax.Attributes atts) throws SAXException
Definition at line 208 of file SAX2ReaderImpl.java.
{
             _attributes = atts;
             _sax2Handler.startElement(namespaceURI.toString(),
                     localName.toString(), qName.toString(), this);
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes, javolution.xml.sax.SAX2ReaderImpl.Proxy._sax2Handler, and javolution.xml.sax.ContentHandler.startElement().
startElement() [2/2]
void javolution.xml.sax.ContentHandler.startElement (CharArray uri, CharArray localName, CharArray qName, Attributes atts) throws SAXException inherited
Receives notification of the beginning of an element.
Parameters
uri the namespace URI, or an empty character sequence if the element has no Namespace URI or if namespace processing is not being performed.
localName the local name (without prefix), or an empty character sequence if namespace processing is not being performed.
qName the qualified name (with prefix), or an empty character sequence if qualified names are not available.
atts the attributes attached to the element. If there are no attributes, it shall be an empty Attributes object.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.sax.SAX2ReaderImpl.Proxy.startElement().
startPrefixMapping()
void javolution.xml.sax.SAX2ReaderImpl.Proxy.startPrefixMapping (CharArray prefix, CharArray uri) throws SAXException
Begins the scope of a prefix-URI Namespace mapping.
Parameters
prefix the Namespace prefix being declared.
uri the namespace URI the prefix is mapped to.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implements javolution.xml.sax.ContentHandler.
Definition at line 197 of file SAX2ReaderImpl.java.
{
             _sax2Handler.startPrefixMapping(prefix.toString(), uri.toString());
         }
References javolution.xml.sax.SAX2ReaderImpl.Proxy._sax2Handler, and javolution.xml.sax.ContentHandler.startPrefixMapping().
Member Data Documentation
_attributes
javolution.xml.sax.Attributes javolution.xml.sax.SAX2ReaderImpl.Proxy._attributes private
Holds the real-time attributes implementation from which attributes values are read.
Definition at line 173 of file SAX2ReaderImpl.java.
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.getIndex(), javolution.xml.sax.SAX2ReaderImpl.Proxy.getLength(), javolution.xml.sax.SAX2ReaderImpl.Proxy.getLocalName(), javolution.xml.sax.SAX2ReaderImpl.Proxy.getQName(), javolution.xml.sax.SAX2ReaderImpl.Proxy.getType(), javolution.xml.sax.SAX2ReaderImpl.Proxy.getURI(), javolution.xml.sax.SAX2ReaderImpl.Proxy.getValue(), and javolution.xml.sax.SAX2ReaderImpl.Proxy.startElement().
_sax2Handler
ContentHandler javolution.xml.sax.SAX2ReaderImpl.Proxy._sax2Handler = DEFAULT_HANDLER private
Holds the SAX2 content handler to which SAX2 events are forwarded.
Definition at line 167 of file SAX2ReaderImpl.java.
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.characters(), javolution.xml.sax.SAX2ReaderImpl.Proxy.endDocument(), javolution.xml.sax.SAX2ReaderImpl.Proxy.endElement(), javolution.xml.sax.SAX2ReaderImpl.Proxy.endPrefixMapping(), javolution.xml.sax.SAX2ReaderImpl.getContentHandler(), javolution.xml.sax.SAX2ReaderImpl.Proxy.ignorableWhitespace(), javolution.xml.sax.SAX2ReaderImpl.Proxy.processingInstruction(), javolution.xml.sax.SAX2ReaderImpl.setContentHandler(), javolution.xml.sax.SAX2ReaderImpl.Proxy.setDocumentLocator(), javolution.xml.sax.SAX2ReaderImpl.Proxy.skippedEntity(), javolution.xml.sax.SAX2ReaderImpl.Proxy.startDocument(), javolution.xml.sax.SAX2ReaderImpl.Proxy.startElement(), and javolution.xml.sax.SAX2ReaderImpl.Proxy.startPrefixMapping().
The documentation for this class was generated from the following file:
SAX2ReaderImpl.java