Javolution 6.0.0 java: javolution.util.Index Class Reference
javolution.util.Index Class Reference
Classes
class Decimal
Public Member Functions
int compareTo (Index that)
int compareTo (int value)
Index copy ()
double doubleValue ()
boolean equals (Object obj)
float floatValue ()
int hashCode ()
int intValue ()
boolean isZero ()
long longValue ()
Index next ()
Index previous ()
String toString ()
Index value ()
Static Public Member Functions
static Index valueOf (int value)
Static Public Attributes
static final Configurable< Integer > UNIQUE
static final Index ZERO = new Index(0)
Protected Member Functions
final Object readResolve () throws ObjectStreamException
Static Package Functions
[static initializer]
Private Member Functions
Index (int value)
Private Attributes
final int value
Static Private Attributes
static final long serialVersionUID = 0x600L
static final Index[] INSTANCES = new Index[UNIQUE.get()]
Detailed Description
A non-negative number representing a position in an arrangement. For example: [code] class SparseVector<F> { FastMap<Index, F> elements = new FastMap<Index, F>(); ... }[/code]
Index performance is on-par with the primitive
int
type for small values and similar to Integer instances for large values. Small indexes have no adverse effect on the garbage collector and have fast equals method due to their unicity.
Author
Jean-Marie Dautelle
Version
5.1, July 26, 2007
Definition at line 43 of file Index.java.
Constructor & Destructor Documentation
Index()
javolution.util.Index.Index (int value) private
Creates an index having the specified value.
Definition at line 123 of file Index.java.
{
         this.value = value;
     }
Member Function Documentation
[static initializer]()
javolution.util.Index.[static initializer] static package
compareTo() [1/2]
int javolution.util.Index.compareTo (Index that)
Compares this index with the specified index for order. Returns a negative integer, zero, or a positive integer as this index is less than, equal to, or greater than the specified index.
Parameters
that the index to be compared.
Returns
a negative integer, zero, or a positive integer as this index is less than, equal to, or greater than the specified index.
Definition at line 136 of file Index.java.
{
         return this.value - that.value;
     }
References javolution.util.Index.value.
compareTo() [2/2]
int javolution.util.Index.compareTo (int value)
Compares this index with the specified integer value for order. Returns a negative integer, zero, or a positive integer as this index is less than, equal to, or greater than the specified value.
Parameters
value the value to be compared.
Returns
a negative integer, zero, or a positive integer as this index is less than, equal to, or greater than the specified value.
Definition at line 149 of file Index.java.
{
         return this.value - value;
     }
copy()
Index javolution.util.Index.copy ()
Returns a copy of this index or this if the indexes is small (in permanent memory) in order to maintain unicity.
Definition at line 157 of file Index.java.
{
         return value < INSTANCES.length ? this : new Index(value);
     }
doubleValue()
double javolution.util.Index.doubleValue ()
Returns the index value as double.
Returns
the index value.
Definition at line 166 of file Index.java.
{
         return (double) value;
     }
equals()
boolean javolution.util.Index.equals (Object obj)
Indicates if this index is equals to the one specified (for small indices this method is equivalent to ==).
Definition at line 175 of file Index.java.
{
         return (this.value < INSTANCES.length) ? (this == obj)
                 : ((obj instanceof Index) ? (((Index) obj).value == value)
                         : false);
     }
floatValue()
float javolution.util.Index.floatValue ()
Returns the index value as float.
Returns
the index value.
Definition at line 186 of file Index.java.
{
         return (float) value;
     }
hashCode()
int javolution.util.Index.hashCode ()
Returns the hash code for this index.
Definition at line 194 of file Index.java.
{
         return value;
     }
intValue()
int javolution.util.Index.intValue ()
Returns the index value as int.
Returns
the index value.
Definition at line 203 of file Index.java.
{
         return value;
     }
Referenced by javolution.util.internal.bitset.BitSetServiceImpl.add().
isZero()
boolean javolution.util.Index.isZero ()
Indicates if this index is zero.
Returns
this == ZERO
Definition at line 212 of file Index.java.
{
         return this == ZERO;
     }
longValue()
long javolution.util.Index.longValue ()
Returns the index value as long.
Returns
the index value.
Definition at line 221 of file Index.java.
{
         return value;
     }
next()
Index javolution.util.Index.next ()
Returns the index after this one.
Definition at line 228 of file Index.java.
{
         return Index.valueOf(value + 1);
     }
References javolution.util.Index.valueOf().
previous()
Index javolution.util.Index.previous ()
Returns the index before this one.
Exceptions
IndexOutOfBoundsException if (this == Index.ZERO)
Definition at line 237 of file Index.java.
{
         return Index.valueOf(value - 1);
     }
References javolution.util.Index.valueOf().
readResolve()
final Object javolution.util.Index.readResolve () throws ObjectStreamException protected
Ensures index unicity during deserialization.
Definition at line 244 of file Index.java.
{
         return Index.valueOf(value);
     }
References javolution.util.Index.valueOf().
toString()
String javolution.util.Index.toString ()
Returns the String representation of this index.
Returns
TextContext.getFormat(Index.class).format(this)
Definition at line 254 of file Index.java.
{
         return TextContext.getFormat(Index.class).format(this);
     }
References javolution.text.TextContext.getFormat().
value()
Index javolution.util.Index.value ()
Returns
this
.
Implements javolution.lang.ValueType< T >.
Definition at line 259 of file Index.java.
{
         return this;
     }
valueOf()
static Index javolution.util.Index.valueOf (int value) static
Returns the index for the specified
int
non-negative value (returns a preallocated instance if the specified value is small).
Parameters
value the index value.
Returns
the corresponding index.
Exceptions
IndexOutOfBoundsException if value < 0
Definition at line 111 of file Index.java.
{
         return (value < INSTANCES.length) ? INSTANCES[value] : new Index(value);
     }
Referenced by javolution.util.internal.bitset.BitSetIteratorImpl.next(), javolution.util.Index.next(), javolution.util.Index.Decimal.parse(), javolution.util.Index.previous(), javolution.util.Index.readResolve(), and javolution.xml.XMLReferenceResolver.writeReference().
Member Data Documentation
INSTANCES
final Index [] javolution.util.Index.INSTANCES = new Index[UNIQUE.get()] static private
Definition at line 94 of file Index.java.
serialVersionUID
final long javolution.util.Index.serialVersionUID = 0x600L static private
Definition at line 93 of file Index.java.
UNIQUE
final Configurable<Integer> javolution.util.Index.UNIQUE static
Initial value:
= new Configurable<Integer>() {
        @Override
        protected Integer getDefault() {
            return 1024;
        }
        @Override
        protected Integer initialized(Integer value) {
            return MathLib.min(value, 65536);
        }
        @Override
        protected Integer reconfigured(Integer oldCount, Integer newCount) {
             throw new UnsupportedOperationException(
                     "Unicity reconfiguration not supported.");
        }
    }
Holds the number of unique preallocated instances (default
1024
). This number is configurable, for example with
-Djavolution.util.Index#UNIQUE=0
there is no unique instance.
Definition at line 69 of file Index.java.
value
final int javolution.util.Index.value private
Holds the index value.
Definition at line 118 of file Index.java.
Referenced by javolution.util.Index.compareTo().
ZERO
final Index javolution.util.Index.ZERO = new Index(0) static
Holds the index zero (value 0).
Definition at line 91 of file Index.java.
The documentation for this class was generated from the following file:
Index.java