Javolution 6.0.0 java: javolution.io.CharSequenceReader Class Reference
javolution.io.CharSequenceReader Class Reference
Public Member Functions
CharSequenceReader ()
CharSequenceReader setInput (CharSequence charSequence)
boolean ready () throws IOException
void close ()
int read () throws IOException
int read (char cbuf[], int off, int len) throws IOException
void read (Appendable dest) throws IOException
void reset ()
Private Attributes
CharSequence _input
int _index
Detailed Description
This class allows any CharSequence to be used as a reader.
Author
Jean-Marie Dautelle
Version
3.8, May 8, 2004
Definition at line 25 of file CharSequenceReader.java.
Constructor & Destructor Documentation
CharSequenceReader()
javolution.io.CharSequenceReader.CharSequenceReader ()
Creates a new character sequence reader for which the character sequence input is not set.
See also
setInput
Definition at line 43 of file CharSequenceReader.java.
 {}
Member Function Documentation
close()
void javolution.io.CharSequenceReader.close ()
Closes and resets this reader for reuse.
Definition at line 76 of file CharSequenceReader.java.
{
         if (_input != null) {
             reset();
         }
     }
References javolution.io.CharSequenceReader._input, and javolution.io.CharSequenceReader.reset().
read() [1/3]
int javolution.io.CharSequenceReader.read () throws IOException
Reads a single character. This method does not block, -1 is returned if the end of the character sequence input has been reached.
Returns
the 31-bits Unicode of the character read, or -1 if there is no more remaining bytes to be read.
Exceptions
IOException if an I/O error occurs (e.g. incomplete character sequence being read).
Definition at line 91 of file CharSequenceReader.java.
{
         if (_input == null)
             throw new IOException("Reader closed");
         return (_index < _input.length()) ? _input.charAt(_index++) : -1;
     }
References javolution.io.CharSequenceReader._index, and javolution.io.CharSequenceReader._input.
read() [2/3]
void javolution.io.CharSequenceReader.read (Appendable dest) throws IOException
Reads characters into the specified appendable. This method does not block.
Parameters
dest the destination buffer.
Exceptions
IOException if an I/O error occurs.
Definition at line 144 of file CharSequenceReader.java.
{
         if (_input == null)
             throw new IOException("Reader closed");
         dest.append(_input);
     }
References javolution.io.CharSequenceReader._input.
read() [3/3]
int javolution.io.CharSequenceReader.read (char cbuf[], int off, int len) throws IOException
Reads characters into a portion of an array. This method does not block.
Parameters
cbuf the destination buffer.
off the offset at which to start storing characters.
len the maximum number of characters to read
Returns
the number of characters read, or -1 if there is no more character to be read.
Exceptions
IOException if an I/O error occurs.
Definition at line 108 of file CharSequenceReader.java.
{
         if (_input == null)
             throw new IOException("Reader closed");
         final int inputLength = _input.length();
         if (_index >= inputLength)
             return -1;
         final int count = MathLib.min(inputLength - _index, len);
         final Object csq = _input;
         if (csq instanceof String) {
             String str = (String) csq;
             str.getChars(_index, _index + count, cbuf, off);
         } else if (csq instanceof Text) {
             Text txt = (Text) csq;
             txt.getChars(_index, _index + count, cbuf, off);
         } else if (csq instanceof TextBuilder) {
             TextBuilder tb = (TextBuilder) csq;
             tb.getChars(_index, _index + count, cbuf, off);
         } else if (csq instanceof CharArray) {
             CharArray ca = (CharArray) csq;
             System.arraycopy(ca.array(), _index + ca.offset(), cbuf, off, count);
         } else { // Generic CharSequence.
             for (int i = off, n = off + count, j = _index; i < n;) {
                 cbuf[i++] = _input.charAt(j++);
             }
         }
         _index += count;
         return count;
     }
References javolution.io.CharSequenceReader._index, javolution.io.CharSequenceReader._input, javolution.text.CharArray.array(), javolution.text.TextBuilder.getChars(), javolution.text.Text.getChars(), javolution.lang.MathLib.min(), and javolution.text.CharArray.offset().
ready()
boolean javolution.io.CharSequenceReader.ready () throws IOException
Indicates if this stream is ready to be read.
Returns
true if this reader has remaining characters to read; false otherwise.
Exceptions
IOException if an I/O error occurs.
Definition at line 67 of file CharSequenceReader.java.
{
         if (_input == null)
             throw new IOException("Reader closed");
         return true;
     }
References javolution.io.CharSequenceReader._input.
reset()
void javolution.io.CharSequenceReader.reset ()
Definition at line 151 of file CharSequenceReader.java.
{
         _index = 0;
         _input = null;
     }
References javolution.io.CharSequenceReader._index, and javolution.io.CharSequenceReader._input.
Referenced by javolution.io.CharSequenceReader.close().
setInput()
CharSequenceReader javolution.io.CharSequenceReader.setInput (CharSequence charSequence)
Sets the character sequence to use for reading.
Parameters
charSequence the character sequence to be read.
Returns
this reader.
Exceptions
IllegalStateException if this reader is being reused and it has not been closed or reset.
Definition at line 53 of file CharSequenceReader.java.
{
         if (_input != null)
             throw new IllegalStateException("Reader not closed or reset");
         _input = charSequence;
         return this;
     }
References javolution.io.CharSequenceReader._input.
Member Data Documentation
_index
int javolution.io.CharSequenceReader._index private
Holds the current index into the character sequence.
Definition at line 35 of file CharSequenceReader.java.
Referenced by javolution.io.CharSequenceReader.read(), and javolution.io.CharSequenceReader.reset().
_input
CharSequence javolution.io.CharSequenceReader._input private
Holds the character sequence input.
Definition at line 30 of file CharSequenceReader.java.
Referenced by javolution.io.CharSequenceReader.close(), javolution.io.CharSequenceReader.read(), javolution.io.CharSequenceReader.ready(), javolution.io.CharSequenceReader.reset(), and javolution.io.CharSequenceReader.setInput().
The documentation for this class was generated from the following file:
CharSequenceReader.java