Javolution 6.0.0 java: javolution.text.internal.TextContextImpl Class Reference
javolution.text.internal.TextContextImpl Class Reference
Public Member Functions
TextContextImpl ()
TextContextImpl (TextContextImpl parent)
void exit ()
Static Public Member Functions
static TextContext enter ()
static< T extends AbstractContext > T enter (Class< T > custom)
static< T > TextFormat< T > getFormat (Class<? extends T > type)
static AbstractContext current ()
static void inherit (AbstractContext ctx)
Protected Member Functions
TextContext inner ()
AbstractContext enterInner ()
AbstractContext getOuter ()
Static Protected Member Functions
static< T extends AbstractContext > T current (Class< T > type)
Package Functions
protected< T > TextFormat< T > searchFormat (Class<? extends T > type)
public< T > void setFormat (Class<? extends T > type, TextFormat< T > format)
Private Member Functions
void storePrimitiveTypesFormats ()
Static Private Member Functions
static TextContext currentTextContext ()
Private Attributes
final FastMap< Class<?>, TextFormat<?> > localFormats
final FastMap< Class<?>, TextFormat<?> > defaultFormats
AbstractContext outer
Static Private Attributes
static final TextFormat<?> OBJECT_FORMAT
static final ThreadLocal< AbstractContext > CURRENT = new ThreadLocal<AbstractContext>()
Detailed Description
Holds the default implementation of TextContext.
Author
Jean-Marie Dautelle
Version
6.0, July 21, 2013
Definition at line 37 of file TextContextImpl.java.
Constructor & Destructor Documentation
TextContextImpl() [1/2]
javolution.text.internal.TextContextImpl.TextContextImpl ()
Default constructor for root
Definition at line 70 of file TextContextImpl.java.
{
         localFormats = new FastMap<Class<?>, TextFormat<?>>(); // Updated only during configuration.
         defaultFormats = new FastMap<Class<?>, TextFormat<?>>().shared(); // Can be updated concurrently.
         storePrimitiveTypesFormats();
     }
References javolution.text.internal.TextContextImpl.defaultFormats, javolution.text.internal.TextContextImpl.localFormats, and javolution.text.internal.TextContextImpl.storePrimitiveTypesFormats().
Referenced by javolution.text.internal.TextContextImpl.inner().
TextContextImpl() [2/2]
javolution.text.internal.TextContextImpl.TextContextImpl (TextContextImpl parent)
Inner constructor
Definition at line 77 of file TextContextImpl.java.
{
         localFormats = new FastMap<Class<?>, TextFormat<?>>()
                 .putAll(parent.localFormats);
         defaultFormats = parent.defaultFormats;
     }
References javolution.text.internal.TextContextImpl.defaultFormats, and javolution.text.internal.TextContextImpl.localFormats.
Member Function Documentation
current() [1/2]
static AbstractContext javolution.context.AbstractContext.current () static inherited
Returns the current context for the current thread or
null
if this thread has no context (default).
Definition at line 61 of file AbstractContext.java.
{
         return AbstractContext.CURRENT.get();
     }
References javolution.context.AbstractContext.CURRENT.
Referenced by javolution.context.LogContext.currentLogContext(), javolution.context.SecurityContext.currentSecurityContext(), javolution.text.TextContext.currentTextContext(), javolution.xml.XMLContext.currentXMLContext(), javolution.context.LocalContext.enter(), javolution.context.ConcurrentContext.enter(), and javolution.context.LocalContext.Parameter< T >.get().
current() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.current (Class< T > type) static protected inherited
Returns the current context of specified type or
null
if none.
Definition at line 69 of file AbstractContext.java.
{
         AbstractContext ctx = AbstractContext.CURRENT.get();
         while (ctx != null) {
             if (type.isInstance(ctx))
                 return (T) ctx;
             ctx = ctx.outer;
         }
         return null;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
currentTextContext()
static TextContext javolution.text.TextContext.currentTextContext () static private inherited
Returns the current text context.
Definition at line 87 of file TextContext.java.
{
         TextContext ctx = AbstractContext.current(TextContext.class);
         if (ctx != null)
             return ctx;
         return OSGiServices.getTextContext();
     }
References javolution.context.AbstractContext.current(), and javolution.osgi.internal.OSGiServices.getTextContext().
Referenced by javolution.text.TextContext.enter(), and javolution.text.TextContext.getFormat().
enter() [1/2]
static TextContext javolution.text.TextContext.enter () static inherited
Enters and returns a new text context instance.
Definition at line 59 of file TextContext.java.
{
         return (TextContext) TextContext.currentTextContext().enterInner();
     }
References javolution.text.TextContext.currentTextContext(), and javolution.context.AbstractContext.enterInner().
enter() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.enter (Class< T > custom) static inherited
Enters the scope of a custom context. This method raises a SecurityException if the permission to enter contexts of the specified class is not granted. For example, the following disallow entering any custom context. [code] SecurityContext ctx = SecurityContext.enter(); try { ctx.revoke(new SecurityContext.Permission(AbstractContext.class, "enter")); ... // Cannot enter any custom context. } finally { ctx.exit(); // Back to previous security settings. }[/code]
Parameters
custom the custom context to enter.
Exceptions
IllegalArgumentException if the specified class default constructor cannot be instantiated.
SecurityException if
SecurityContext.Permission(custom, "enter")
is not granted.
See also
SecurityContext.Permission
Definition at line 101 of file AbstractContext.java.
{
         SecurityContext.check(new Permission<T>(custom, "enter"));
         try {
             return (T) custom.newInstance().enterInner();
         } catch (InstantiationException e) {
             throw new IllegalArgumentException(
                     "Cannot instantiate instance of " + custom, e);
         } catch (IllegalAccessException e) {
             throw new IllegalArgumentException("Cannot access " + custom, e);
         }
     }
References javolution.context.SecurityContext.check().
enterInner()
AbstractContext javolution.context.AbstractContext.enterInner () protected inherited
Enters the scope of an inner context which becomes the current context; the previous current context becomes the outer of this context.
Returns
the inner context entered.
Definition at line 141 of file AbstractContext.java.
{
         AbstractContext inner = inner();
         inner.outer = AbstractContext.CURRENT.get();
         AbstractContext.CURRENT.set(inner);
         return inner;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
Referenced by javolution.xml.XMLContext.enter(), javolution.text.TextContext.enter(), javolution.context.LogContext.enter(), javolution.context.LocalContext.enter(), javolution.context.SecurityContext.enter(), and javolution.context.ConcurrentContext.enter().
exit()
void javolution.context.AbstractContext.exit () inherited
Exits the scope of this context; the outer of this context becomes
the current context.
Exceptions
IllegalStateException if this context is not the current context.
Reimplemented in javolution.context.ConcurrentContext, and javolution.context.internal.ConcurrentContextImpl.
Definition at line 155 of file AbstractContext.java.
{
         if (this != AbstractContext.CURRENT.get())
             throw new IllegalStateException(
                     "This context is not the current context");
         AbstractContext.CURRENT.set(outer);
         outer = null;
     }
References javolution.context.AbstractContext.CURRENT.
getFormat()
static <T> TextFormat<T> javolution.text.TextContext.getFormat (Class<? extends T > type) static inherited
Returns the text format for the specified type. It is the most specialized format able to parse/format instances of the specified class. If there is no default format for the specified class, the standard object format (toString based) is returned.
Definition at line 69 of file TextContext.java.
{
         return TextContext.currentTextContext().searchFormat(type);
     }
References javolution.text.TextContext.currentTextContext(), and javolution.text.TextContext.searchFormat().
Referenced by javolution.text.TextBuilder.append(), javolution.util.FastCollection< E >.Format.format(), javolution.xml.XMLFormat< T >.InputElement.getAttribute(), javolution.xml.XMLFormat< T >.Default.newInstance(), javolution.lang.Configurable< javolution.context.LogContext.Level >.parse(), javolution.util.Index.toString(), javolution.util.FastMap< Object, javolution.util.Index >.toString(), javolution.util.FastCollection< E >.toString(), and javolution.xml.XMLFormat< T >.Default.write().
getOuter()
AbstractContext javolution.context.AbstractContext.getOuter () protected inherited
Returns the outer context of this context or
null
if this context has no outer context.
Definition at line 167 of file AbstractContext.java.
{
         return outer;
     }
inherit()
static void javolution.context.AbstractContext.inherit (AbstractContext ctx) static inherited
Inherits the specified context which becomes the context of the current thread. This method is particularly useful when creating new threads to make them inherits from the context stack of the parent thread. [code] //Spawns a new thread inheriting the context of the current thread. MyThread myThread = new MyThread(); myThread.inherited = AbstractContext.current(); myThread.start(); ... class MyThread extends Thread { AbstractContext inherited; public void run() { AbstractContext.inherit(inherited); // Sets current context. ... } }[/code]
Definition at line 131 of file AbstractContext.java.
{
         CURRENT.set(ctx);
     }
Referenced by javolution.context.internal.ConcurrentThreadImpl.run().
inner()
TextContext javolution.text.internal.TextContextImpl.inner () protected
Returns a new inner instance of this context inheriting the properties of this context. The new instance can be configured independently from its parent.
Reimplemented from javolution.context.AbstractContext.
Definition at line 84 of file TextContextImpl.java.
{
         return new TextContextImpl(this);
     }
References javolution.text.internal.TextContextImpl.TextContextImpl().
searchFormat()
protected<T> TextFormat<T> javolution.text.internal.TextContextImpl.searchFormat (Class<? extends T > type) package
Searches the most specialized format for the specified type.
Reimplemented from javolution.text.TextContext.
Definition at line 90 of file TextContextImpl.java.
{
         Class<?> cls = type;
         while (cls != null) {
             TextFormat<?> format;
             // Search local format first.
             if (localFormats.size() > 0) {
                 format = localFormats.get(cls);
                 if (format != null) return (TextFormat<T>) format;
             }
             // Then search default format.
             format = defaultFormats.get(cls);
             if (format != null) return (TextFormat<T>) format;
             // Search annotations.
             DefaultTextFormat annotation = cls
                     .getAnnotation(DefaultTextFormat.class);
             if (annotation != null) { // Found it.
                 try {
                     format = annotation.value().newInstance();
                 } catch (Throwable error) {
                     LogContext.warning(error);
                 }
                 // Updates the default mapping.
                 Class<?> mappedClass = type;
                 while (true) {
                     defaultFormats.put(mappedClass, format);
                     if (mappedClass.equals(cls)) break;
                     mappedClass = mappedClass.getSuperclass();
                 }
                 return (TextFormat<T>) format;
             }
             // Search superclass.
             cls = cls.getSuperclass();
         }
         throw new Error("Object default format not found !");
     }
References javolution.text.internal.TextContextImpl.defaultFormats, javolution.text.internal.TextContextImpl.localFormats, javolution.text.DefaultTextFormat.value(), and javolution.context.LogContext.warning().
setFormat()
public<T> void javolution.text.internal.TextContextImpl.setFormat (Class<? extends T > type, TextFormat< T > newFormat) package
Sets the text format for the specified type (and its sub-types).
Reimplemented from javolution.text.TextContext.
Definition at line 129 of file TextContextImpl.java.
{
         localFormats.put(type, format);
     }
References javolution.text.internal.TextContextImpl.localFormats.
storePrimitiveTypesFormats()
void javolution.text.internal.TextContextImpl.storePrimitiveTypesFormats () private
Definition at line 137 of file TextContextImpl.java.
{
         defaultFormats.put(Object.class, OBJECT_FORMAT);
         defaultFormats.put(Boolean.class, new TextFormat<Boolean>() {
             public Appendable format(Boolean obj, Appendable dest)
                     throws IOException {
                 return TypeFormat.format(obj.booleanValue(), dest);
             }
             public Boolean parse(CharSequence csq, Cursor cursor) {
                 return TypeFormat.parseBoolean(csq, cursor);
             }
         });
         defaultFormats.put(Character.class, new TextFormat<Character>() {
             public Appendable format(Character obj, Appendable dest)
                     throws IOException {
                 return dest.append(obj.charValue());
             }
             public Character parse(CharSequence csq, Cursor cursor) {
                 return Character.valueOf(cursor.nextChar(csq));
             }
         });
         defaultFormats.put(Byte.class, new TextFormat<Byte>() {
             public Appendable format(Byte obj, Appendable dest)
                     throws IOException {
                 return TypeFormat.format(obj.byteValue(), dest);
             }
             public Byte parse(CharSequence csq, Cursor cursor) {
                 return Byte.valueOf(TypeFormat.parseByte(csq, 10, cursor));
             }
         });
         defaultFormats.put(Short.class, new TextFormat<Short>() {
             public Appendable format(Short obj, Appendable dest)
                     throws IOException {
                 return TypeFormat.format(obj.shortValue(), dest);
             }
             public Short parse(CharSequence csq, Cursor cursor) {
                 return Short.valueOf(TypeFormat.parseShort(csq, 10, cursor));
             }
         });
         defaultFormats.put(Integer.class, new TextFormat<Integer>() {
             public Appendable format(Integer obj, Appendable dest)
                     throws IOException {
                 return TypeFormat.format(obj.intValue(), dest);
             }
             public Integer parse(CharSequence csq, Cursor cursor) {
                 return Integer.valueOf(TypeFormat.parseInt(csq, 10, cursor));
             }
         });
         defaultFormats.put(Long.class, new TextFormat<Long>() {
             public Appendable format(Long obj, Appendable dest)
                     throws IOException {
                 return TypeFormat.format(obj.longValue(), dest);
             }
             public Long parse(CharSequence csq, Cursor cursor) {
                 return Long.valueOf(TypeFormat.parseLong(csq, 10, cursor));
             }
         });
         defaultFormats.put(Float.class, new TextFormat<Float>() {
             public Appendable format(Float obj, Appendable dest)
                     throws IOException {
                 return TypeFormat.format(obj.floatValue(), dest);
             }
             public Float parse(CharSequence csq, Cursor cursor) {
                 return new Float(TypeFormat.parseFloat(csq, cursor));
             }
         });
         defaultFormats.put(Double.class, new TextFormat<Double>() {
             public Appendable format(Double obj, Appendable dest)
                     throws IOException {
                 return TypeFormat.format(obj.doubleValue(), dest);
             }
             public Double parse(CharSequence csq, Cursor cursor) {
                 return new Double(TypeFormat.parseDouble(csq, cursor));
             }
         });
         defaultFormats.put(String.class, new TextFormat<String>() {
             public Appendable format(String obj, Appendable dest)
                     throws IOException {
                 return dest.append(obj);
             }
             public String parse(CharSequence csq, Cursor cursor) {
                 CharSequence tmp = csq.subSequence(cursor.getIndex(),
                         csq.length());
                 cursor.setIndex(csq.length());
                 return tmp.toString();
             }
         });
         defaultFormats.put(Class.class, new TextFormat<Class<?>>() {
             public Appendable format(Class<?> obj, Appendable dest)
                     throws IOException {
                 return dest.append(obj.getName());
             }
             public Class<?> parse(CharSequence csq, Cursor cursor) {
                 CharSequence name = cursor.nextToken(csq, CharSet.WHITESPACES);
                 try {
                     return Class.forName(name.toString());
                 } catch (ClassNotFoundException e) {
                     throw new IllegalArgumentException("Class " + name
                             + " Not Found");
                 }
             }
         });
         defaultFormats.put(Date.class, new TextFormat<Date>() {
             TimeZone tz = TimeZone.getTimeZone("UTC");
             DateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm'Z'");
             {
                 df.setTimeZone(tz);
             }
             public Appendable format(Date obj, Appendable dest)
                     throws IOException {
                 return dest.append(df.format(obj));
             }
             public Date parse(CharSequence csq, Cursor cursor) {
                 CharSequence date = cursor.nextToken(csq, CharSet.WHITESPACES);
                 try {
                     return df.parse(date.toString());
                 } catch (ParseException error) {
                     throw new IllegalArgumentException(error);
                 }
             }
         });
         defaultFormats.put(BigInteger.class, new TextFormat<BigInteger>() {
             public Appendable format(BigInteger obj, Appendable dest)
                     throws IOException {
                 return dest.append(obj.toString());
             }
             public BigInteger parse(CharSequence csq, Cursor cursor) {
                 CharSequence value = cursor.nextToken(csq, CharSet.WHITESPACES);
                 return new BigInteger(value.toString());
             }
         });
         defaultFormats.put(BigDecimal.class, new TextFormat<BigDecimal>() {
             public Appendable format(BigDecimal obj, Appendable dest)
                     throws IOException {
                 return dest.append(obj.toString());
             }
             public BigDecimal parse(CharSequence csq, Cursor cursor) {
                 CharSequence value = cursor.nextToken(csq, CharSet.WHITESPACES);
                 return new BigDecimal(value.toString());
             }
         });
         defaultFormats.put(Font.class, new TextFormat<Font>() {
             public Appendable format(Font obj, Appendable dest)
                     throws IOException {
                 return dest.append(obj.getName());
             }
             public Font parse(CharSequence csq, Cursor cursor) {
                 CharSequence name = cursor.nextToken(csq, CharSet.WHITESPACES);
                 return Font.decode(name.toString());
             }
         });
         defaultFormats.put(Color.class, new TextFormat<Color>() {
             public Appendable format(Color obj, Appendable dest)
                     throws IOException {
                 return dest.append('#').append(
                         Integer.toHexString(obj.getRGB()));
             }
             public Color parse(CharSequence csq, Cursor cursor) {
                 CharSequence name = cursor.nextToken(csq, CharSet.WHITESPACES);
                 return Color.decode(name.toString());
             }
         });
     }
References javolution.text.internal.TextContextImpl.defaultFormats, javolution.text.internal.TextContextImpl.OBJECT_FORMAT, and javolution.text.TypeFormat.parseBoolean().
Referenced by javolution.text.internal.TextContextImpl.TextContextImpl().
Member Data Documentation
CURRENT
final ThreadLocal<AbstractContext> javolution.context.AbstractContext.CURRENT = new ThreadLocal<AbstractContext>() static private inherited
Holds the last context entered (thread-local).
Definition at line 45 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), javolution.context.AbstractContext.enterInner(), and javolution.context.AbstractContext.exit().
defaultFormats
final FastMap<Class<?>, TextFormat<?> > javolution.text.internal.TextContextImpl.defaultFormats private
Definition at line 67 of file TextContextImpl.java.
Referenced by javolution.text.internal.TextContextImpl.searchFormat(), javolution.text.internal.TextContextImpl.storePrimitiveTypesFormats(), and javolution.text.internal.TextContextImpl.TextContextImpl().
localFormats
final FastMap<Class<?>, TextFormat<?> > javolution.text.internal.TextContextImpl.localFormats private
Definition at line 64 of file TextContextImpl.java.
Referenced by javolution.text.internal.TextContextImpl.searchFormat(), javolution.text.internal.TextContextImpl.setFormat(), and javolution.text.internal.TextContextImpl.TextContextImpl().
OBJECT_FORMAT
final TextFormat<?> javolution.text.internal.TextContextImpl.OBJECT_FORMAT static private
Initial value:
= new TextFormat<Object>() {
        ThreadLocal<Object> objToString = new ThreadLocal<Object>();
        public Appendable format(Object obj, Appendable dest)
                throws IOException {
            if (obj == null) return dest.append("null");
            if (objToString.get() == obj)
            return TypeFormat.format(System.identityHashCode(obj),
                    dest.append("Object#"));
            objToString.set(obj);
            try {
                String str = obj.toString();
                return dest.append(str);
            } finally {
                objToString.set(null);
            }
        }
        public Object parse(CharSequence csq, Cursor cursor) {
            throw new UnsupportedOperationException(
                    "Generic object parsing not supported.");
        }
    }
Definition at line 39 of file TextContextImpl.java.
Referenced by javolution.text.internal.TextContextImpl.storePrimitiveTypesFormats().
outer
AbstractContext javolution.context.AbstractContext.outer private inherited
Holds the outer context or
null
if none (top context).
Definition at line 50 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), and javolution.context.AbstractContext.enterInner().
The documentation for this class was generated from the following file:
TextContextImpl.java