Javolution 6.0.0 java: javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl Class Reference
javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl Class Reference
Public Member Functions
IteratorImpl ()
boolean hasNext ()
E next ()
void remove ()
Private Attributes
E next
final Iterator< E > targetIterator
Detailed Description
Thread-Safe Iterator.
Definition at line 24 of file SharedCollectionImpl.java.
Constructor & Destructor Documentation
IteratorImpl()
javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.IteratorImpl ()
Definition at line 28 of file SharedCollectionImpl.java.
{
             lock.readLock.lock();
             try {
                 targetIterator = cloneTarget().iterator(); // Copy.
             } finally {
                 lock.readLock.unlock();
             }
         }
References javolution.util.internal.collection.SharedCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lock(), javolution.util.internal.collection.SharedCollectionImpl< E >.lock, javolution.util.internal.collection.ReadWriteLockImpl.readLock, javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.targetIterator, and javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.unlock().
Member Function Documentation
hasNext()
boolean javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.hasNext ()
Definition at line 38 of file SharedCollectionImpl.java.
{
             return targetIterator.hasNext();
         }
References javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.targetIterator.
next()
E javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.next ()
Definition at line 43 of file SharedCollectionImpl.java.
{
             next = targetIterator.next();
             return next;
         }
References javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.next, and javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.targetIterator.
remove()
void javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.remove ()
Definition at line 49 of file SharedCollectionImpl.java.
{
             if (next == null) throw new IllegalStateException();
             SharedCollectionImpl.this.remove(next);
             next = null;
         }
References javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.next, and javolution.util.internal.collection.SharedCollectionImpl< E >.remove().
Member Data Documentation
next
E javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.next private
Definition at line 25 of file SharedCollectionImpl.java.
Referenced by javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.next(), and javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.remove().
targetIterator
final Iterator<E> javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.targetIterator private
Definition at line 26 of file SharedCollectionImpl.java.
Referenced by javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.hasNext(), javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.IteratorImpl(), and javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.next().
The documentation for this class was generated from the following file:
SharedCollectionImpl.java