Javolution 6.0.0 java: javolution.io.Struct.UTF8String Class Reference
javolution.io.Struct.UTF8String Class Reference
Public Member Functions
UTF8String (int length)
void set (String string)
String get ()
String toString ()
final Struct struct ()
final int offset ()
final int bitIndex ()
final int bitLength ()
Package Functions
final int get (int wordSize, int word)
final long get (int wordSize, long word)
final int set (int value, int wordSize, int word)
final long set (long value, int wordSize, long word)
Private Attributes
final UTF8ByteBufferWriter _writer = new UTF8ByteBufferWriter()
final UTF8ByteBufferReader _reader = new UTF8ByteBufferReader()
final int _length
final int _offset
final int _bitIndex
final int _bitLength
Detailed Description
This class represents a UTF-8 character string, null terminated (for C/C++ compatibility)
Definition at line 1062 of file Struct.java.
Constructor & Destructor Documentation
UTF8String()
javolution.io.Struct.UTF8String.UTF8String (int length)
Definition at line 1068 of file Struct.java.
{
             super(length << 3, 1);
             _length = length; // Takes into account 0 terminator.
         }
References javolution.io.Struct.UTF8String._length.
Member Function Documentation
bitIndex()
final int javolution.io.Struct.Member.bitIndex () inherited
Holds the bit offset of this member (if any). The actual position of the bits data depends upon the endianess and the word size.
Definition at line 998 of file Struct.java.
{
             return _bitIndex;
         }
References javolution.io.Struct.Member._bitIndex.
Referenced by javolution.io.Struct.Member.get(), javolution.io.Struct.BitField.longValue(), javolution.io.Struct.Member.set(), and javolution.io.Struct.BitField.set().
bitLength()
final int javolution.io.Struct.Member.bitLength () inherited
Returns the number of bits in this member. Can be zero if this member is used to force the next member to the next word boundary.
Returns
the number of bits in the member.
Definition at line 1008 of file Struct.java.
{
             return _bitLength;
         }
References javolution.io.Struct.Member._bitLength.
Referenced by javolution.io.Struct.Member.get(), javolution.io.Struct.Bool.get(), javolution.io.Struct.Signed8.get(), javolution.io.Struct.Unsigned8.get(), javolution.io.Struct.Signed16.get(), javolution.io.Struct.Unsigned16.get(), javolution.io.Struct.Signed32.get(), javolution.io.Struct.Unsigned32.get(), javolution.io.Struct.Signed64.get(), javolution.io.Struct.BitField.longValue(), javolution.io.Struct.Member.Member(), javolution.io.Struct.Member.set(), javolution.io.Struct.Bool.set(), javolution.io.Struct.Signed8.set(), javolution.io.Struct.Unsigned8.set(), javolution.io.Struct.Signed16.set(), javolution.io.Struct.Unsigned16.set(), javolution.io.Struct.Signed32.set(), javolution.io.Struct.Unsigned32.set(), javolution.io.Struct.Signed64.set(), and javolution.io.Struct.BitField.set().
get() [1/3]
String javolution.io.Struct.UTF8String.get ()
Definition at line 1096 of file Struct.java.
{
             final ByteBuffer buffer = getByteBuffer();
             synchronized (buffer) {
                 TextBuilder tmp = new TextBuilder();
                 try {
                     int index = getByteBufferPosition() + offset();
                     buffer.position(index);
                     _reader.setInput(buffer);
                     for (int i = 0; i < _length; i++) {
                         char c = (char) _reader.read();
                         if (c == 0) { // Null terminator.
                             return tmp.toString();
                         } else {
                             tmp.append(c);
                         }
                     }
                     return tmp.toString();
                 } catch (IOException e) { // Should never happen.
                     throw new Error(e.getMessage());
                 } finally {
                     _reader.reset();
                 }
             }
         }
References javolution.io.Struct.UTF8String._length, javolution.io.Struct.UTF8String._reader, javolution.text.TextBuilder.append(), javolution.io.Struct.getByteBuffer(), javolution.io.Struct.getByteBufferPosition(), javolution.io.Struct.Member.offset(), javolution.io.UTF8ByteBufferReader.read(), javolution.io.UTF8ByteBufferReader.reset(), javolution.io.UTF8ByteBufferReader.setInput(), and javolution.text.TextBuilder.toString().
get() [2/3]
final int javolution.io.Struct.Member.get (int wordSize, int word) package inherited
Definition at line 1013 of file Struct.java.
{
             final int shift = (byteOrder() == ByteOrder.BIG_ENDIAN) ? (wordSize << 3)
                     - bitIndex() - bitLength()
                     : bitIndex();
             word >>= shift;
             int mask = 0xFFFFFFFF >>> (32 - bitLength());
             return word & mask;
         }
References javolution.io.Struct.Member.bitIndex(), javolution.io.Struct.Member.bitLength(), and javolution.io.Struct.byteOrder().
get() [3/3]
final long javolution.io.Struct.Member.get (int wordSize, long word) package inherited
Definition at line 1034 of file Struct.java.
{
             final int shift = (byteOrder() == ByteOrder.BIG_ENDIAN) ? (wordSize << 3)
                     - bitIndex() - bitLength()
                     : bitIndex();
             word >>= shift;
             long mask = 0xFFFFFFFFFFFFFFFFL >>> (64 - bitLength());
             return word & mask;
         }
References javolution.io.Struct.Member.bitIndex(), javolution.io.Struct.Member.bitLength(), and javolution.io.Struct.byteOrder().
offset()
final int javolution.io.Struct.Member.offset () inherited
Returns the byte offset of this member in its struct. Equivalent to C/C++ offsetof(struct(), this)
Returns
the offset of this member in the Struct.
Definition at line 989 of file Struct.java.
{
             return _offset;
         }
References javolution.io.Struct.Member._offset.
Referenced by javolution.io.Struct.UTF8String.get(), javolution.io.Struct.Bool.get(), javolution.io.Struct.Signed8.get(), javolution.io.Struct.Unsigned8.get(), javolution.io.Struct.Signed16.get(), javolution.io.Struct.Unsigned16.get(), javolution.io.Struct.Signed32.get(), javolution.io.Struct.Unsigned32.get(), javolution.io.Struct.Signed64.get(), javolution.io.Struct.Float32.get(), javolution.io.Struct.Float64.get(), javolution.io.Struct.Enum8< T extends Enum< T >.get(), javolution.io.Struct.Enum16< T extends Enum< T >.get(), javolution.io.Struct.Enum32< T extends Enum< T >.get(), javolution.io.Struct.Enum64< T extends Enum< T >.get(), javolution.io.Struct.Reference32< S extends Struct >.isUpToDate(), javolution.io.Struct.Reference64< S extends Struct >.isUpToDate(), javolution.io.Struct.BitField.longValue(), javolution.io.Struct.UTF8String.set(), javolution.io.Struct.Bool.set(), javolution.io.Struct.Signed8.set(), javolution.io.Struct.Unsigned8.set(), javolution.io.Struct.Signed16.set(), javolution.io.Struct.Unsigned16.set(), javolution.io.Struct.Signed32.set(), javolution.io.Struct.Unsigned32.set(), javolution.io.Struct.Signed64.set(), javolution.io.Struct.BitField.set(), javolution.io.Struct.Float32.set(), javolution.io.Struct.Float64.set(), javolution.io.Struct.Reference32< S extends Struct >.set(), javolution.io.Struct.Reference64< S extends Struct >.set(), javolution.io.Struct.Enum8< T extends Enum< T >.set(), javolution.io.Struct.Enum16< T extends Enum< T >.set(), javolution.io.Struct.Enum32< T extends Enum< T >.set(), javolution.io.Struct.Enum64< T extends Enum< T >.set(), javolution.io.Struct.Reference32< S extends Struct >.value(), and javolution.io.Struct.Reference64< S extends Struct >.value().
set() [1/3]
final int javolution.io.Struct.Member.set (int value, int wordSize, int word) package inherited
Definition at line 1023 of file Struct.java.
{
             final int shift = (byteOrder() == ByteOrder.BIG_ENDIAN) ? (wordSize << 3)
                     - bitIndex() - bitLength()
                     : bitIndex();
             int mask = 0xFFFFFFFF >>> (32 - bitLength());
             mask <<= shift;
             value <<= shift;
             return (word & ~mask) | (value & mask);
         }
References javolution.io.Struct.Member.bitIndex(), javolution.io.Struct.Member.bitLength(), and javolution.io.Struct.byteOrder().
set() [2/3]
final long javolution.io.Struct.Member.set (long value, int wordSize, long word) package inherited
Definition at line 1044 of file Struct.java.
{
             final int shift = (byteOrder() == ByteOrder.BIG_ENDIAN) ? (wordSize << 3)
                     - bitIndex() - bitLength()
                     : bitIndex();
             long mask = 0xFFFFFFFFFFFFFFFFL >>> (64 - bitLength());
             mask <<= shift;
             value <<= shift;
             return (word & ~mask) | (value & mask);
         }
References javolution.io.Struct.Member.bitIndex(), javolution.io.Struct.Member.bitLength(), and javolution.io.Struct.byteOrder().
set() [3/3]
void javolution.io.Struct.UTF8String.set (String string)
Definition at line 1073 of file Struct.java.
{
             final ByteBuffer buffer = getByteBuffer();
             synchronized (buffer) {
                 try {
                     int index = getByteBufferPosition() + offset();
                     buffer.position(index);
                     _writer.setOutput(buffer);
                     if (string.length() < _length) {
                         _writer.write(string);
                         _writer.write(0); // Marks end of string.
                     } else if (string.length() > _length) { // Truncates.
                         _writer.write(string.substring(0, _length));
                     } else { // Exact same length.
                         _writer.write(string);
                     }
                 } catch (IOException e) { // Should never happen.
                     throw new Error(e.getMessage());
                 } finally {
                     _writer.reset();
                 }
             }
         }
References javolution.io.Struct.UTF8String._length, javolution.io.Struct.UTF8String._writer, javolution.io.Struct.getByteBuffer(), javolution.io.Struct.getByteBufferPosition(), javolution.io.Struct.Member.offset(), javolution.io.UTF8ByteBufferWriter.reset(), javolution.io.UTF8ByteBufferWriter.setOutput(), and javolution.io.UTF8ByteBufferWriter.write().
struct()
final Struct javolution.io.Struct.Member.struct () inherited
Returns the outer struct container.
Returns
the outer struct.
Definition at line 979 of file Struct.java.
{
             return Struct.this;
         }
toString()
String javolution.io.Struct.UTF8String.toString ()
Definition at line 1121 of file Struct.java.
{
             return this.get();
         }
Member Data Documentation
_bitIndex
final int javolution.io.Struct.Member._bitIndex private inherited
Holds the relative bit offset of this member to its struct offset.
Definition at line 903 of file Struct.java.
Referenced by javolution.io.Struct.Member.bitIndex(), and javolution.io.Struct.Member.Member().
_bitLength
final int javolution.io.Struct.Member._bitLength private inherited
Holds the bit length of this member.
Definition at line 907 of file Struct.java.
Referenced by javolution.io.Struct.Member.bitLength(), and javolution.io.Struct.Member.Member().
_length
final int javolution.io.Struct.UTF8String._length private
Definition at line 1066 of file Struct.java.
Referenced by javolution.io.Struct.UTF8String.get(), javolution.io.Struct.UTF8String.set(), and javolution.io.Struct.UTF8String.UTF8String().
_offset
final int javolution.io.Struct.Member._offset private inherited
Holds the relative offset (in bytes) of this member within its struct.
Definition at line 899 of file Struct.java.
Referenced by javolution.io.Struct.Member.Member(), and javolution.io.Struct.Member.offset().
_reader
final UTF8ByteBufferReader javolution.io.Struct.UTF8String._reader = new UTF8ByteBufferReader() private
Definition at line 1065 of file Struct.java.
Referenced by javolution.io.Struct.UTF8String.get().
_writer
final UTF8ByteBufferWriter javolution.io.Struct.UTF8String._writer = new UTF8ByteBufferWriter() private
Definition at line 1064 of file Struct.java.
Referenced by javolution.io.Struct.UTF8String.set().
The documentation for this class was generated from the following file:
Struct.java