Javolution 6.0.0 java: javolution.xml.XMLBinding Class Reference
javolution.xml.XMLBinding Class Reference
Public Member Functions
XMLBinding ()
void setAlias (Class<?> cls, QName qName)
final void setAlias (Class<?> cls, String alias)
void setClassAttribute (QName classAttribute)
final void setClassAttribute (String name)
void reset ()
Protected Member Functions
XMLFormat<?> getFormat (Class<?> forClass) throws XMLStreamException
Class<?> readClass (XMLStreamReader reader, boolean useAttributes) throws XMLStreamException
void writeClass (Class<?> cls, XMLStreamWriter writer, boolean useAttributes) throws XMLStreamException
Static Package Attributes
static final XMLBinding DEFAULT = new XMLBinding()
Private Attributes
QName _classAttribute = QName.valueOf("class")
final FastMap< Class<?>, QName > _classToAlias = new FastMap<Class<?>, QName>()
final FastMap< QName, Class<?> > _aliasToClass = new FastMap<QName, Class<?>>()
Static Private Attributes
static final long serialVersionUID = 6611041662550083919L
Detailed Description
This class represents the binding between Java classes and their XML representation (XMLFormat).
Custom XML bindings can also be used to alias class names and ensure that the XML representation is:
Impervious to obfuscation.
Unaffected by any class refactoring.
Can be mapped to multiple implementations. For example:[code]
// Creates a binding to serialize Swing components into high-level XML // and deserialize the same XML into SWT components. XMLBinding swingBinding = new XMLBinding(); swingBinding.setAlias(javax.swing.JButton.class, "Button"); swingBinding.setAlias(javax.swing.JTable.class, "Table"); ... XMLBinding swtBinding = new XMLBinding(); swtBinding.setAlias(org.eclipse.swt.widgets.Button.class, "Button"); swtBinding.setAlias(org.eclipse.swt.widgets.Table.class, "Table"); ...
// Writes Swing Desktop to XML. XMLObjectWriter writer = new XMLObjectWriter().setBinding(swingBinding); writer.setOutput(new FileOutputStream("C:/desktop.xml")); writer.write(swingDesktop, "Desktop", SwingDesktop.class); writer.close();
// Reads back high-level XML to a SWT implementation!
XMLObjectReader reader = new XMLObjectReader().setXMLBinding(swtBinding); reader.setInput(new FileInputStream("C:/desktop.xml")); SWTDesktop swtDesktop = reader.read("Desktop", SWTDesktop.class); reader.close(); [/code]
More advanced bindings can also be created through sub-classing.[code]
// XML binding using reflection.
public ReflectionBinding extends XMLBinding {
    protected XMLFormat getFormat(Class forClass) {
        Field[] fields = forClass.getDeclaredFields();
        return new XMLReflectionFormat(fields);
    }
}
// XML binding read from DTD input source.
public DTDBinding extends XMLBinding {
    public DTDBinding(InputStream dtd) {
        ...
    }
}
// XML binding overriding default formats.
public MyBinding extends XMLBinding {
    // Non-static formats use unmapped XMLFormat instances.
    XMLFormat<String> myStringFormat = new XMLFormat<String>(null) {...}
    XMLFormat<Collection> myCollectionFormat = new XMLFormat<Collection>(null) {...}
    protected XMLFormat getFormat(Class forClass) throws XMLStreamException {
        if (String.class.equals(forClass))
             return myStringFormat;
        if (Collection.class.isAssignableFrom(forClass))
             return myCollectionFormat;
        return super.getFormat(cls);
    }
}
[/code]
The default XML binding implementation supports all static XML formats (static members of the classes being mapped) as well as the following types:
java.lang.Object (empty element)
java.lang.Class
java.lang.String
java.lang.Appendable
java.util.Collection
java.util.Map
java.lang.Object[]
all primitive types wrappers (e.g. Boolean, Integer ...)
Author
Jean-Marie Dautelle
Version
5.4, December 1, 2009
Definition at line 100 of file XMLBinding.java.
Constructor & Destructor Documentation
XMLBinding()
javolution.xml.XMLBinding.XMLBinding ()
Default constructor.
Definition at line 125 of file XMLBinding.java.
 {}
Member Function Documentation
getFormat()
XMLFormat<?> javolution.xml.XMLBinding.getFormat (Class<?> forClass) throws XMLStreamException protected
Returns the XML format for the specified class/interface. The default implementation returns the XMLContext#getFormat for the specified class.
Parameters
forClass the class for which the XML format is returned.
Returns
the XML format for the specified class (never null).
Definition at line 179 of file XMLBinding.java.
{
         return XMLContext.getFormat(forClass);
     }
References javolution.xml.XMLContext.getFormat().
Referenced by javolution.xml.XMLFormat< T >.OutputElement.add(), and javolution.xml.XMLFormat< T >.InputElement.readInstanceOf().
readClass()
Class<?> javolution.xml.XMLBinding.readClass (XMLStreamReader reader, boolean useAttributes) throws XMLStreamException protected
Reads the class corresponding to the current XML element.
This method is called by XMLFormat.InputElement#getNext() XMLFormat.InputElement#get(String) and XMLFormat.InputElement#get(String, String) to retrieve the Java class corresponding to the current XML element.
If useAttributes is set, the default implementation reads the class name from the class attribute; otherwise the class name (or alias) is read from the current element qualified name.
Parameters
reader the XML stream reader.
useAttributes indicates if the element's attributes should be used to identify the class (e.g. when the element name is specified by the user then attributes have to be used).
Returns
the corresponding class.
Exceptions
XMLStreamException
Definition at line 203 of file XMLBinding.java.
{
         try {
             QName classQName;
             if (useAttributes) {
                 if (_classAttribute == null)
                     throw new XMLStreamException(
                             "Binding has no class attribute defined, cannot retrieve class");
                 classQName = QName.valueOf(reader.getAttributeValue(
                         _classAttribute.getNamespaceURI(),
                         _classAttribute.getLocalName()));
                 if (classQName == null)
                     throw new XMLStreamException(
                             "Cannot retrieve class (class attribute not found)");
             } else {
                 classQName = QName.valueOf(reader.getNamespaceURI(),
                         reader.getLocalName());
             }
             // Searches aliases with namespace URI.
             Class<?> cls = _aliasToClass.get(classQName);
             if (cls != null)
                 return cls;
             // Searches aliases without namespace URI.
             cls = _aliasToClass.get(QName.valueOf(classQName.getLocalName()));
             if (cls != null)
                 return cls;
             // Finally convert the qualified name to a class (ignoring namespace URI).
             cls = Class.forName(classQName.getLocalName().toString());
             if (cls == null)
                 throw new XMLStreamException(
                         "Class "
                                 + classQName.getLocalName()
                                 + " not found (see javolution.lang.Reflection to support additional class loader)");
             _aliasToClass.put(classQName, cls);
             return cls;
         } catch (ClassNotFoundException ex) {
             throw new RuntimeException(ex);
         }
     }
References javolution.xml.XMLBinding._aliasToClass, javolution.xml.XMLBinding._classAttribute, javolution.xml.QName.getLocalName(), javolution.xml.QName.getNamespaceURI(), and javolution.xml.QName.valueOf().
Referenced by javolution.xml.XMLFormat< T >.InputElement.get(), and javolution.xml.XMLFormat< T >.InputElement.getNext().
reset()
void javolution.xml.XMLBinding.reset ()
Definition at line 291 of file XMLBinding.java.
{
         _classAttribute = QName.valueOf("class");
         _aliasToClass.clear();
         _classToAlias.clear();
     }
References javolution.xml.XMLBinding._aliasToClass, javolution.xml.XMLBinding._classAttribute, javolution.xml.XMLBinding._classToAlias, and javolution.xml.QName.valueOf().
setAlias() [1/2]
void javolution.xml.XMLBinding.setAlias (Class<?> cls, QName qName)
Sets the qualified alias for the specified class.
Parameters
cls the class being aliased.
qName the qualified name.
Definition at line 133 of file XMLBinding.java.
{
         _classToAlias.put(cls, qName);
         _aliasToClass.put(qName, cls);
     }
References javolution.xml.XMLBinding._aliasToClass, and javolution.xml.XMLBinding._classToAlias.
Referenced by javolution.xml.XMLBinding.setAlias().
setAlias() [2/2]
final void javolution.xml.XMLBinding.setAlias (Class<?> cls, String alias)
Convenient method equivalent to setAlias(cls, QName.valueOf(alias)).
Parameters
cls the class being aliased.
alias the alias for the specified class.
Definition at line 145 of file XMLBinding.java.
{
         setAlias(cls, QName.valueOf(alias));
     }
References javolution.xml.XMLBinding.setAlias(), and javolution.xml.QName.valueOf().
setClassAttribute() [1/2]
void javolution.xml.XMLBinding.setClassAttribute (QName classAttribute)
Sets the qualified name of the attribute holding the class identifier. If the local name is null the class attribute is never read/written (which may prevent unmarshalling).
Parameters
classAttribute the qualified name of the class attribute or null.
Definition at line 157 of file XMLBinding.java.
{
         _classAttribute = classAttribute;
     }
References javolution.xml.XMLBinding._classAttribute.
Referenced by javolution.xml.XMLBinding.setClassAttribute().
setClassAttribute() [2/2]
final void javolution.xml.XMLBinding.setClassAttribute (String name)
Convenience method equivalent to setClassAttribute(QName.valueOf(name)).
Parameters
name the name of the class attribute or null.
Definition at line 167 of file XMLBinding.java.
{
         setClassAttribute(name == null ? null : QName.valueOf(name));
     }
References javolution.xml.XMLBinding.setClassAttribute(), and javolution.xml.QName.valueOf().
writeClass()
void javolution.xml.XMLBinding.writeClass (Class<?> cls, XMLStreamWriter writer, boolean useAttributes) throws XMLStreamException protected
Writes the specified class to the current XML element attributes or to a new element if the element attributes cannot be used.
This method is called by XMLFormat.OutputElement#add(Object) and XMLFormat.OutputElement#add(Object, String) and XMLFormat.OutputElement#add(Object, String, String) to identify the Java class corresponding to the XML element.
Parameters
cls the class to be written.
writer the XML stream writer.
useAttributes indicates if the element's attributes should be used to identify the class (e.g. when the element name is specified by the user then attributes have to be used).
Exceptions
XMLStreamException
Definition at line 264 of file XMLBinding.java.
{
         QName qName = (QName) _classToAlias.get(cls);
         String name = qName != null ? qName.toString() : cls.getName();
         if (useAttributes) {
             if (_classAttribute == null)
                 return;
             if (_classAttribute.getNamespaceURI() == null) {
                 writer.writeAttribute(_classAttribute.getLocalName(), name);
             } else {
                 writer.writeAttribute(_classAttribute.getNamespaceURI(),
                         _classAttribute.getLocalName(), name);
             }
         } else {
             if (qName != null) {
                 if (qName.getNamespaceURI() == null) {
                     writer.writeStartElement(qName.getLocalName());
                 } else {
                     writer.writeStartElement(qName.getNamespaceURI(),
                             qName.getLocalName());
                 }
             } else {
                 writer.writeStartElement(name);
             }
         }
     }
References javolution.xml.XMLBinding._classAttribute, javolution.xml.XMLBinding._classToAlias, javolution.xml.QName.getLocalName(), javolution.xml.QName.getNamespaceURI(), and javolution.xml.QName.toString().
Referenced by javolution.xml.XMLFormat< T >.OutputElement.add().
Member Data Documentation
_aliasToClass
final FastMap<QName, Class<?> > javolution.xml.XMLBinding._aliasToClass = new FastMap<QName, Class<?>>() private
Holds the alias (QName) to class mapping.
Definition at line 120 of file XMLBinding.java.
Referenced by javolution.xml.XMLBinding.readClass(), javolution.xml.XMLBinding.reset(), and javolution.xml.XMLBinding.setAlias().
_classAttribute
QName javolution.xml.XMLBinding._classAttribute = QName.valueOf("class") private
Holds the class attribute.
Definition at line 110 of file XMLBinding.java.
Referenced by javolution.xml.XMLBinding.readClass(), javolution.xml.XMLBinding.reset(), javolution.xml.XMLBinding.setClassAttribute(), and javolution.xml.XMLBinding.writeClass().
_classToAlias
final FastMap<Class<?>, QName> javolution.xml.XMLBinding._classToAlias = new FastMap<Class<?>, QName>() private
Holds the class to alias (QName) mapping.
Definition at line 115 of file XMLBinding.java.
Referenced by javolution.xml.XMLBinding.reset(), javolution.xml.XMLBinding.setAlias(), and javolution.xml.XMLBinding.writeClass().
DEFAULT
final XMLBinding javolution.xml.XMLBinding.DEFAULT = new XMLBinding() static package
Holds the default instance used by readers/writers (thread-safe).
Definition at line 105 of file XMLBinding.java.
Referenced by javolution.xml.XMLFormat< T >.InputElement.reset(), and javolution.xml.XMLFormat< T >.OutputElement.reset().
serialVersionUID
final long javolution.xml.XMLBinding.serialVersionUID = 6611041662550083919L static private
Definition at line 297 of file XMLBinding.java.
The documentation for this class was generated from the following file:
XMLBinding.java