Javolution 6.0.0 java: javolution.context.LocalContext Class Reference
javolution.context.LocalContext Class Reference abstract
Classes
class Parameter
Public Member Functions
abstract< T > void supersede (Parameter< T > param, T localValue)
void exit ()
Static Public Member Functions
static LocalContext enter ()
static AbstractContext current ()
static< T extends AbstractContext > T enter (Class< T > custom)
static void inherit (AbstractContext ctx)
Protected Member Functions
LocalContext ()
abstract< T > T getValue (Parameter< T > param, T defaultValue)
AbstractContext enterInner ()
AbstractContext getOuter ()
abstract AbstractContext inner ()
Static Protected Member Functions
static< T extends AbstractContext > T current (Class< T > type)
Private Attributes
AbstractContext outer
Static Private Attributes
static final ThreadLocal< AbstractContext > CURRENT = new ThreadLocal<AbstractContext>()
Detailed Description
A context holding locally scoped parameters values.
For example, when performing modulo arithmetics the actual modulo being used is usually the same for most operations and does not need to be specified for each operation. [code] import javolution.context.LocalContext.Parameter; public class ModuloInteger extends Number { public static final Parameter<Integer> MODULO = new Parameter<Integer>() { protected Integer getDefault() { return -1; } }; public ModuloInteger times(ModuloInteger that) { ... }
}
LocalContext ctx = LocalContext.enter(); try { ctx.supersede(ModuloInteger.MODULO, 13); // Sets local modulo value. x = a.times(b).plus(c.times(d)); // Operations modulo 13 ... } finally { ctx.exit(); // Reverts to previous modulo setting. }[/code]
As for any context, local context settings are inherited during ConcurrentContext executions.
Author
Jean-Marie Dautelle
Version
6.0 December 12, 2012
Definition at line 43 of file LocalContext.java.
Constructor & Destructor Documentation
LocalContext()
javolution.context.LocalContext.LocalContext () protected
Default constructor.
Definition at line 92 of file LocalContext.java.
 {}
Member Function Documentation
current() [1/2]
static AbstractContext javolution.context.AbstractContext.current () static inherited
Returns the current context for the current thread or
null
if this thread has no context (default).
Definition at line 61 of file AbstractContext.java.
{
         return AbstractContext.CURRENT.get();
     }
References javolution.context.AbstractContext.CURRENT.
Referenced by javolution.context.LogContext.currentLogContext(), javolution.context.SecurityContext.currentSecurityContext(), javolution.text.TextContext.currentTextContext(), javolution.xml.XMLContext.currentXMLContext(), javolution.context.LocalContext.enter(), javolution.context.ConcurrentContext.enter(), and javolution.context.LocalContext.Parameter< T >.get().
current() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.current (Class< T > type) static protected inherited
Returns the current context of specified type or
null
if none.
Definition at line 69 of file AbstractContext.java.
{
         AbstractContext ctx = AbstractContext.CURRENT.get();
         while (ctx != null) {
             if (type.isInstance(ctx))
                 return (T) ctx;
             ctx = ctx.outer;
         }
         return null;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
enter() [1/2]
static LocalContext javolution.context.LocalContext.enter () static
Enters and returns a new local context instance.
Definition at line 97 of file LocalContext.java.
{
         LocalContext ctx = current(LocalContext.class);
         if (ctx == null) { // Root.
             ctx = OSGiServices.getLocalContext();
         }
         return (LocalContext) ctx.enterInner();
     }
References javolution.context.AbstractContext.current(), javolution.context.AbstractContext.enterInner(), and javolution.osgi.internal.OSGiServices.getLocalContext().
enter() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.enter (Class< T > custom) static inherited
Enters the scope of a custom context. This method raises a SecurityException if the permission to enter contexts of the specified class is not granted. For example, the following disallow entering any custom context. [code] SecurityContext ctx = SecurityContext.enter(); try { ctx.revoke(new SecurityContext.Permission(AbstractContext.class, "enter")); ... // Cannot enter any custom context. } finally { ctx.exit(); // Back to previous security settings. }[/code]
Parameters
custom the custom context to enter.
Exceptions
IllegalArgumentException if the specified class default constructor cannot be instantiated.
SecurityException if
SecurityContext.Permission(custom, "enter")
is not granted.
See also
SecurityContext.Permission
Definition at line 101 of file AbstractContext.java.
{
         SecurityContext.check(new Permission<T>(custom, "enter"));
         try {
             return (T) custom.newInstance().enterInner();
         } catch (InstantiationException e) {
             throw new IllegalArgumentException(
                     "Cannot instantiate instance of " + custom, e);
         } catch (IllegalAccessException e) {
             throw new IllegalArgumentException("Cannot access " + custom, e);
         }
     }
References javolution.context.SecurityContext.check().
enterInner()
AbstractContext javolution.context.AbstractContext.enterInner () protected inherited
Enters the scope of an inner context which becomes the current context; the previous current context becomes the outer of this context.
Returns
the inner context entered.
Definition at line 141 of file AbstractContext.java.
{
         AbstractContext inner = inner();
         inner.outer = AbstractContext.CURRENT.get();
         AbstractContext.CURRENT.set(inner);
         return inner;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
Referenced by javolution.xml.XMLContext.enter(), javolution.text.TextContext.enter(), javolution.context.LogContext.enter(), javolution.context.LocalContext.enter(), javolution.context.SecurityContext.enter(), and javolution.context.ConcurrentContext.enter().
exit()
void javolution.context.AbstractContext.exit () inherited
Exits the scope of this context; the outer of this context becomes
the current context.
Exceptions
IllegalStateException if this context is not the current context.
Reimplemented in javolution.context.ConcurrentContext, and javolution.context.internal.ConcurrentContextImpl.
Definition at line 155 of file AbstractContext.java.
{
         if (this != AbstractContext.CURRENT.get())
             throw new IllegalStateException(
                     "This context is not the current context");
         AbstractContext.CURRENT.set(outer);
         outer = null;
     }
References javolution.context.AbstractContext.CURRENT.
getOuter()
AbstractContext javolution.context.AbstractContext.getOuter () protected inherited
Returns the outer context of this context or
null
if this context has no outer context.
Definition at line 167 of file AbstractContext.java.
{
         return outer;
     }
getValue()
abstract <T> T javolution.context.LocalContext.getValue (Parameter< T > param, T defaultValue) abstract protected
Returns the local value of the specified parameter or the specified default value if not superseded.
Parameters
param the local parameter whose local value is returned.
defaultValue the parameter value if not superseded.
Reimplemented in javolution.context.internal.LocalContextImpl.
Referenced by javolution.context.LocalContext.Parameter< T >.get().
inherit()
static void javolution.context.AbstractContext.inherit (AbstractContext ctx) static inherited
Inherits the specified context which becomes the context of the current thread. This method is particularly useful when creating new threads to make them inherits from the context stack of the parent thread. [code] //Spawns a new thread inheriting the context of the current thread. MyThread myThread = new MyThread(); myThread.inherited = AbstractContext.current(); myThread.start(); ... class MyThread extends Thread { AbstractContext inherited; public void run() { AbstractContext.inherit(inherited); // Sets current context. ... } }[/code]
Definition at line 131 of file AbstractContext.java.
{
         CURRENT.set(ctx);
     }
Referenced by javolution.context.internal.ConcurrentThreadImpl.run().
inner()
abstract AbstractContext javolution.context.AbstractContext.inner () abstract protected inherited
Returns a new inner instance of this context inheriting the properties of this context. The new instance can be configured independently from its parent.
Reimplemented in javolution.context.internal.ConcurrentContextImpl, javolution.text.internal.TextContextImpl, javolution.context.internal.LogContextImpl, javolution.context.internal.SecurityContextImpl, javolution.xml.internal.XMLContextImpl, and javolution.context.internal.LocalContextImpl.
supersede()
abstract <T> void javolution.context.LocalContext.supersede (Parameter< T > param, T localValue) abstract
Supersedes the value of the specified parameter.
Parameters
param the local parameter whose local value is overridden.
localValue the new local value.
Exceptions
SecurityException if the permission to override the specified parameter is not granted.
NullPointerException if the specified local value is
null
.
Reimplemented in javolution.context.internal.LocalContextImpl.
Member Data Documentation
CURRENT
final ThreadLocal<AbstractContext> javolution.context.AbstractContext.CURRENT = new ThreadLocal<AbstractContext>() static private inherited
Holds the last context entered (thread-local).
Definition at line 45 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), javolution.context.AbstractContext.enterInner(), and javolution.context.AbstractContext.exit().
outer
AbstractContext javolution.context.AbstractContext.outer private inherited
Holds the outer context or
null
if none (top context).
Definition at line 50 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), and javolution.context.AbstractContext.enterInner().
The documentation for this class was generated from the following file:
LocalContext.java