Javolution 6.0.0 java: javolution.util.internal.map.MapView< K, V > Class Template Reference
javolution.util.internal.map.MapView< K, V > Class Template Reference abstract
Classes
class EntryComparator
class EntrySet
class KeySet
class Values
Public Member Functions
MapView (MapService< K, V > target)
void clear ()
MapView< K, V > clone ()
abstract boolean containsKey (Object key)
boolean containsValue (Object value)
SetService< Entry< K, V > > entrySet ()
abstract V get (Object key)
boolean isEmpty ()
abstract Iterator< Entry< K, V > > iterator ()
abstract Equality<? super K > keyComparator ()
SetService< K > keySet ()
void perform (Consumer< MapService< K, V >> action, MapService< K, V > view)
abstract V put (K key, V value)
void putAll (Map<? extends K, ? extends V > m)
V putIfAbsent (K key, V value)
abstract V remove (Object key)
boolean remove (Object key, Object value)
V replace (K key, V value)
boolean replace (K key, V oldValue, V newValue)
int size ()
MapService< K, V >[] split (int n)
MapService< K, V > threadSafe ()
void update (Consumer< MapService< K, V >> action, MapService< K, V > view)
abstract Equality<? super V > valueComparator ()
CollectionService< V > values ()
void perform (Consumer< T > action, T part)
void update (Consumer< T > action, T part)
Protected Member Functions
MapService< K, V > target ()
Private Attributes
MapService< K, V > target
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
Map view implementation; can be used as root class for implementations if target is
null
.
Definition at line 29 of file MapView.java.
Constructor & Destructor Documentation
MapView()
javolution.util.internal.map.MapView< K, V >.MapView (MapService< K, V > target)
The view constructor or root class constructor if target is
null
.
Definition at line 218 of file MapView.java.
{
         this.target = target;
     }
References javolution.util.internal.map.MapView< K, V >.target.
Member Function Documentation
clear()
void javolution.util.internal.map.MapView< K, V >.clear ()
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, and javolution.util.internal.map.FastMapImpl< K, V >.
Definition at line 223 of file MapView.java.
{
         Iterator<Entry<K, V>> it = iterator();
         while (it.hasNext()) {
             it.remove();
         }
     }
References javolution.util.internal.map.MapView< K, V >.iterator().
clone()
MapView<K, V> javolution.util.internal.map.MapView< K, V >.clone ()
Returns a copy of this map; updates of the copy should not impact the original.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.AtomicMapImpl< K, V >, and javolution.util.internal.map.FastMapImpl< K, V >.
Definition at line 232 of file MapView.java.
{
         try {
             MapView<K, V> copy = (MapView<K, V>) super.clone();
             if (target != null) { // Not a root class.
                 copy.target = target.clone();
             }
             return copy;
         } catch (CloneNotSupportedException e) {
             throw new Error("Should not happen since target is cloneable");
         }
     }
References javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.split().
containsKey()
abstract boolean javolution.util.internal.map.MapView< K, V >.containsKey (Object key) abstract
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >, javolution.util.internal.map.ParallelMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Referenced by javolution.util.internal.map.MapView< K, V >.KeySet.add(), javolution.util.internal.map.MapView< K, V >.KeySet.contains(), javolution.util.internal.map.MapView< K, V >.putIfAbsent(), javolution.util.internal.map.MapView< K, V >.KeySet.remove(), javolution.util.internal.map.MapView< K, V >.remove(), and javolution.util.internal.map.MapView< K, V >.replace().
containsValue()
boolean javolution.util.internal.map.MapView< K, V >.containsValue (Object value)
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 248 of file MapView.java.
{
         return values().contains(value);
     }
References javolution.util.internal.map.MapView< K, V >.values().
entrySet()
SetService<Entry<K, V> > javolution.util.internal.map.MapView< K, V >.entrySet ()
Returns a set view over the entries of this map. The set support adding/removing entries. Two entries are considered equals if they have the same key regardless of their values.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 253 of file MapView.java.
{
         return new EntrySet();
     }
Referenced by javolution.util.internal.map.MapView< K, V >.KeySet.KeySet(), and javolution.util.internal.map.MapView< K, V >.Values.Values().
get()
abstract V javolution.util.internal.map.MapView< K, V >.get (Object key) abstract
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >, javolution.util.internal.map.ParallelMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Referenced by javolution.util.internal.map.sorted.SortedMapView< K, V >.EntrySortedSet.first(), and javolution.util.internal.map.sorted.SortedMapView< K, V >.EntrySortedSet.last().
isEmpty()
boolean javolution.util.internal.map.MapView< K, V >.isEmpty ()
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 261 of file MapView.java.
{
         return iterator().hasNext();
     }
References javolution.util.internal.map.MapView< K, V >.iterator().
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.isEmpty().
iterator()
abstract Iterator<Entry<K, V> > javolution.util.internal.map.MapView< K, V >.iterator () abstract
Returns an iterator over this map entries.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >, javolution.util.internal.map.ParallelMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Referenced by javolution.util.internal.map.MapView< K, V >.clear(), javolution.util.internal.map.MapView< K, V >.isEmpty(), javolution.util.internal.map.MapView< K, V >.EntrySet.iterator(), and javolution.util.internal.map.MapView< K, V >.size().
keyComparator()
abstract Equality<? super K> javolution.util.internal.map.MapView< K, V >.keyComparator () abstract
Returns the key comparator used for key equality or order if the map is sorted.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >, javolution.util.internal.map.ParallelMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Referenced by javolution.util.internal.map.MapView< K, V >.EntryComparator.areEqual(), javolution.util.internal.map.sorted.SortedMapView< K, V >.comparator(), javolution.util.internal.map.MapView< K, V >.KeySet.comparator(), javolution.util.internal.map.MapView< K, V >.EntryComparator.compare(), and javolution.util.internal.map.MapView< K, V >.EntryComparator.hashCodeOf().
keySet()
SetService<K> javolution.util.internal.map.MapView< K, V >.keySet ()
Returns a set view over the key of this map, the set support adding new key for which the value is automatically
null
.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 272 of file MapView.java.
{
         return new KeySet();
     }
Referenced by javolution.util.FastSet< Index >.FastSet().
perform() [1/2]
void javolution.util.internal.map.MapView< K, V >.perform (Consumer< MapService< K, V >> action, MapService< K, V > view)
Reimplemented in javolution.util.internal.map.ParallelMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Definition at line 277 of file MapView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
References javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.perform().
perform() [2/2]
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
put()
abstract V javolution.util.internal.map.MapView< K, V >.put (K key, V value) abstract
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, javolution.util.internal.map.ParallelMapImpl< K, V >, javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.add(), javolution.util.internal.map.MapView< K, V >.KeySet.add(), javolution.util.internal.map.MapView< K, V >.putAll(), javolution.util.internal.map.MapView< K, V >.putIfAbsent(), and javolution.util.internal.map.MapView< K, V >.replace().
putAll()
void javolution.util.internal.map.MapView< K, V >.putAll (Map<? extends K, ? extends V > m)
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 290 of file MapView.java.
{
         Iterator<?> it = m.entrySet().iterator();
         while (it.hasNext()) {
             Entry<K, V> e = (Entry<K, V>) it.next();
             put(e.getKey(), e.getValue());
         }
     }
References javolution.util.internal.map.MapView< K, V >.put().
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.clone().
putIfAbsent()
V javolution.util.internal.map.MapView< K, V >.putIfAbsent (K key, V value)
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 299 of file MapView.java.
{
         if (!containsKey(key)) return put(key, value);
         else return get(key);
     }
References javolution.util.internal.map.MapView< K, V >.containsKey(), and javolution.util.internal.map.MapView< K, V >.put().
remove() [1/2]
abstract V javolution.util.internal.map.MapView< K, V >.remove (Object key) abstract
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, javolution.util.internal.map.ParallelMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.remove(), and javolution.util.internal.map.MapView< K, V >.KeySet.remove().
remove() [2/2]
boolean javolution.util.internal.map.MapView< K, V >.remove (Object key, Object value)
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 308 of file MapView.java.
{
         if (containsKey(key) && get(key).equals(value)) {
             remove(key);
             return true;
         } else return false;
     }
References javolution.util.internal.map.MapView< K, V >.containsKey().
replace() [1/2]
boolean javolution.util.internal.map.MapView< K, V >.replace (K key, V oldValue, V newValue)
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 323 of file MapView.java.
{
         if (containsKey(key) && get(key).equals(oldValue)) {
             put(key, newValue);
             return true;
         } else return false;
     }
References javolution.util.internal.map.MapView< K, V >.containsKey(), and javolution.util.internal.map.MapView< K, V >.put().
replace() [2/2]
V javolution.util.internal.map.MapView< K, V >.replace (K key, V value)
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 316 of file MapView.java.
{
         if (containsKey(key)) {
             return put(key, value);
         } else return null;
     }
References javolution.util.internal.map.MapView< K, V >.containsKey(), and javolution.util.internal.map.MapView< K, V >.put().
size()
int javolution.util.internal.map.MapView< K, V >.size ()
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 331 of file MapView.java.
                       {
         int count = 0;
         Iterator<Entry<K, V>> it = iterator();
         while (it.hasNext()) {
             count++;
             it.next();
         }
         return count;
     }
References javolution.util.internal.map.MapView< K, V >.iterator().
Referenced by javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >.put(), and javolution.util.internal.map.MapView< K, V >.EntrySet.size().
split()
MapService<K, V> [] javolution.util.internal.map.MapView< K, V >.split (int n)
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Implements javolution.util.function.Splittable< T >.
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 343 of file MapView.java.
{
         if (target == null) return new MapService[] { this }; // No split.
         MapService<K, V>[] subTargets = target.split(n);
         MapService<K, V>[] result = new MapService[subTargets.length];
         for (int i = 0; i < subTargets.length; i++) {
             MapView<K, V> copy = this.clone();
             copy.target = subTargets[i];
             result[i] = copy;
         }
         return result;
     }
References javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.split().
target()
MapService<K, V> javolution.util.internal.map.MapView< K, V >.target () protected
Returns the actual target
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 378 of file MapView.java.
{
         return target;
     }
References javolution.util.internal.map.MapView< K, V >.target.
threadSafe()
MapService<K, V> javolution.util.internal.map.MapView< K, V >.threadSafe ()
Returns a thread-safe version of this service (used during parallel updates).
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 356 of file MapView.java.
{
         return new SharedMapImpl<K, V>(this);
     }
update() [1/2]
void javolution.util.internal.map.MapView< K, V >.update (Consumer< MapService< K, V >> action, MapService< K, V > view)
Reimplemented in javolution.util.internal.map.ParallelMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Definition at line 361 of file MapView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.update(action, view);
         }
     }
References javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.update().
update() [2/2]
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
valueComparator()
abstract Equality<? super V> javolution.util.internal.map.MapView< K, V >.valueComparator () abstract
Returns the value comparator used for value equality.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >, javolution.util.internal.map.ParallelMapImpl< K, V >, javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Referenced by javolution.util.internal.map.MapView< K, V >.Values.comparator().
values()
CollectionService<V> javolution.util.internal.map.MapView< K, V >.values ()
Returns a collection view over the values of this map, the collection support value/entry removal but not adding new values.
Implements javolution.util.service.MapService< K, V >.
Definition at line 373 of file MapView.java.
{
         return new Values();
     }
Referenced by javolution.util.internal.map.MapView< K, V >.containsValue().
Member Data Documentation
serialVersionUID
final long javolution.util.internal.map.MapView< K, V >.serialVersionUID = 0x600L static private
Definition at line 212 of file MapView.java.
target
MapService<K, V> javolution.util.internal.map.MapView< K, V >.target private
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 213 of file MapView.java.
Referenced by javolution.util.internal.map.AtomicMapImpl< K, V >.AtomicMapImpl(), javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >.AtomicSortedMapImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.clear(), javolution.util.internal.map.MapView< K, V >.clone(), javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.SharedMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >.comparator(), javolution.util.internal.map.SequentialMapImpl< K, V >.containsKey(), javolution.util.internal.map.ParallelMapImpl< K, V >.containsKey(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.containsKey(), javolution.util.internal.map.SharedMapImpl< K, V >.containsKey(), javolution.util.internal.map.SharedMapImpl< K, V >.containsValue(), javolution.util.internal.map.SequentialMapImpl< K, V >.get(), javolution.util.internal.map.ParallelMapImpl< K, V >.get(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.get(), javolution.util.internal.map.SharedMapImpl< K, V >.get(), javolution.util.internal.map.SharedMapImpl< K, V >.isEmpty(), javolution.util.internal.map.SequentialMapImpl< K, V >.iterator(), javolution.util.internal.map.ParallelMapImpl< K, V >.iterator(), javolution.util.internal.map.SequentialMapImpl< K, V >.keyComparator(), javolution.util.internal.map.ParallelMapImpl< K, V >.keyComparator(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.keyComparator(), javolution.util.internal.map.SharedMapImpl< K, V >.keyComparator(), javolution.util.internal.map.MapView< K, V >.MapView(), javolution.util.internal.map.ParallelMapImpl< K, V >.ParallelMapImpl(), javolution.util.internal.map.ParallelMapImpl< K, V >.perform(), javolution.util.internal.map.MapView< K, V >.perform(), javolution.util.internal.map.SequentialMapImpl< K, V >.put(), javolution.util.internal.map.ParallelMapImpl< K, V >.put(), javolution.util.internal.map.AtomicMapImpl< K, V >.put(), javolution.util.internal.map.SharedMapImpl< K, V >.put(), javolution.util.internal.map.AtomicMapImpl< K, V >.putAll(), javolution.util.internal.map.SharedMapImpl< K, V >.putAll(), javolution.util.internal.map.AtomicMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.SharedMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.SequentialMapImpl< K, V >.remove(), javolution.util.internal.map.ParallelMapImpl< K, V >.remove(), javolution.util.internal.map.AtomicMapImpl< K, V >.remove(), javolution.util.internal.map.SharedMapImpl< K, V >.remove(), javolution.util.internal.map.AtomicMapImpl< K, V >.replace(), javolution.util.internal.map.SharedMapImpl< K, V >.replace(), javolution.util.internal.map.SequentialMapImpl< K, V >.SequentialMapImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.SharedMapImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.size(), javolution.util.internal.map.SharedMapImpl< K, V >.split(), javolution.util.internal.map.MapView< K, V >.split(), javolution.util.internal.map.MapView< K, V >.target(), javolution.util.internal.map.AtomicMapImpl< K, V >.targetView(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.UnmodifiableMapImpl(), javolution.util.internal.map.ParallelMapImpl< K, V >.update(), javolution.util.internal.map.AtomicMapImpl< K, V >.update(), javolution.util.internal.map.MapView< K, V >.update(), javolution.util.internal.map.SequentialMapImpl< K, V >.valueComparator(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.valueComparator(), javolution.util.internal.map.ParallelMapImpl< K, V >.valueComparator(), and javolution.util.internal.map.SharedMapImpl< K, V >.valueComparator().
The documentation for this class was generated from the following file:
MapView.java