Javolution 6.0.0 java: javolution.util.FastBitSet Class Reference
javolution.util.FastBitSet Class Reference
Public Member Functions
FastBitSet ()
FastBitSet unmodifiable ()
FastBitSet shared ()
void and (FastBitSet that)
void andNot (FastBitSet that)
int cardinality ()
void clear ()
void clear (int bitIndex)
void clear (int fromIndex, int toIndex)
void flip (int bitIndex)
void flip (int fromIndex, int toIndex)
boolean get (int bitIndex)
FastBitSet get (int fromIndex, int toIndex)
boolean intersects (FastBitSet that)
int length ()
int nextClearBit (int fromIndex)
int nextSetBit (int fromIndex)
int previousClearBit (int fromIndex)
int previousSetBit (int fromIndex)
void or (FastBitSet that)
void set (int bitIndex)
void set (int bitIndex, boolean value)
void set (int fromIndex, int toIndex)
void set (int fromIndex, int toIndex, boolean value)
void xor (FastBitSet that)
FastBitSet addAll (Index... elements)
FastBitSet addAll (FastCollection<? extends Index > elements)
FastSet< E > atomic ()
FastSet< E > filtered (final Predicate<? super E > filter)
boolean isEmpty ()
int size ()
boolean contains (Object obj)
boolean remove (Object obj)
FastSet< E > addAll (E... elements)
FastSet< E > addAll (FastCollection<? extends E > that)
Protected Member Functions
FastBitSet (BitSetService impl)
BitSetService service ()
Private Attributes
final BitSetService service
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
A high-performance bitset with real-time behavior.
This class is integrated with the collection framework as a set of indices and obeys the collection semantic for methods such as size (cardinality) or equals (same set of indices).
Author
Jean-Marie Dautelle
Version
6.0, July 21, 2013
Definition at line 27 of file FastBitSet.java.
Constructor & Destructor Documentation
FastBitSet() [1/2]
javolution.util.FastBitSet.FastBitSet ()
Creates an empty bit set.
Definition at line 39 of file FastBitSet.java.
{
         service = new BitSetServiceImpl();
     }
References javolution.util.FastBitSet.service.
Referenced by javolution.util.FastBitSet.get().
FastBitSet() [2/2]
javolution.util.FastBitSet.FastBitSet (BitSetService impl) protected
Creates a fast bit set based on the specified implementation.
Definition at line 46 of file FastBitSet.java.
{
         this.service = impl;
     }
Member Function Documentation
addAll() [1/4]
FastSet<E> javolution.util.FastSet< E >.addAll (E... elements) inherited
Returns this collection with the specified element added.
Parameters
elements the elements to be added.
Returns
this
Definition at line 133 of file FastSet.java.
{
         return (FastSet<E>) super.addAll(elements);
     }
addAll() [2/4]
FastSet<E> javolution.util.FastSet< E >.addAll (FastCollection<? extends E > that) inherited
Returns this collection with the specified collection's elements added in sequence.
Definition at line 138 of file FastSet.java.
{
         return (FastSet<E>) super.addAll(that);
     }
addAll() [3/4]
FastBitSet javolution.util.FastBitSet.addAll (FastCollection<? extends Index > elements)
Definition at line 352 of file FastBitSet.java.
{
         return (FastBitSet) super.addAll(elements);
     }
References javolution.util.FastBitSet.addAll().
addAll() [4/4]
FastBitSet javolution.util.FastBitSet.addAll (Index... elements)
Definition at line 347 of file FastBitSet.java.
{
         return (FastBitSet) super.addAll(elements);
     }
References javolution.util.FastBitSet.addAll().
Referenced by javolution.util.FastBitSet.addAll().
and()
void javolution.util.FastBitSet.and (FastBitSet that)
Performs the logical AND operation on this bit set and the given bit set. This means it builds the intersection of the two sets. The result is stored into this bit set.
Parameters
that the second bit set.
Definition at line 76 of file FastBitSet.java.
{
         service.and(that.service);
     }
References javolution.util.service.BitSetService.and(), and javolution.util.FastBitSet.service.
andNot()
void javolution.util.FastBitSet.andNot (FastBitSet that)
Performs the logical AND operation on this bit set and the complement of the given bit set. This means it selects every element in the first set, that isn't in the second set. The result is stored into this bit set.
Parameters
that the second bit set
Definition at line 89 of file FastBitSet.java.
{
         service.andNot(that.service);
     }
References javolution.util.service.BitSetService.andNot(), and javolution.util.FastBitSet.service.
atomic()
FastSet<E> javolution.util.FastSet< E >.atomic inherited
Returns an atomic view over this collection. All operations that write or access multiple elements in the collection (such as addAll(), retainAll()) are atomic. Iterators on atomic collections are thread-safe (no ConcurrentModificationException possible).
Definition at line 75 of file FastSet.java.
{
         return new FastSet<E>(new AtomicSetImpl<E>(service()));
     }
cardinality()
int javolution.util.FastBitSet.cardinality ()
Returns the number of bits set to
true
(or the size of this set).
Returns
the number of bits being set.
Definition at line 99 of file FastBitSet.java.
{
         return service.cardinality();
     }
References javolution.util.service.BitSetService.cardinality(), and javolution.util.FastBitSet.service.
clear() [1/3]
void javolution.util.FastBitSet.clear ()
Sets all bits in the set to
false
(empty the set).
Definition at line 107 of file FastBitSet.java.
{
         service.clear();
     }
References javolution.util.service.BitSetService.clear(), and javolution.util.FastBitSet.service.
clear() [2/3]
void javolution.util.FastBitSet.clear (int bitIndex)
Removes the specified integer value from this set. That is the corresponding bit is cleared.
Parameters
bitIndex a non-negative integer.
Exceptions
IndexOutOfBoundsException if
index < 0
Definition at line 118 of file FastBitSet.java.
{
         service.clear(bitIndex);
     }
References javolution.util.service.BitSetService.clear(), and javolution.util.FastBitSet.service.
clear() [3/3]
void javolution.util.FastBitSet.clear (int fromIndex, int toIndex)
Sets the bits from the specified
fromIndex
(inclusive) to the specified
toIndex
(exclusive) to
false
.
Parameters
fromIndex index of the first bit to be cleared.
toIndex index after the last bit to be cleared.
Exceptions
IndexOutOfBoundsException if
(fromIndex < 0) | (toIndex < fromIndex)
Definition at line 132 of file FastBitSet.java.
{
         service.clear(fromIndex, toIndex);
     }
References javolution.util.service.BitSetService.clear(), and javolution.util.FastBitSet.service.
contains()
boolean javolution.util.FastSet< E >.contains (Object obj) inherited
Indicates if this collection contains the specified element.
Definition at line 118 of file FastSet.java.
{
         return service.contains(obj);
     }
filtered()
FastSet<E> javolution.util.FastSet< E >.filtered (final Predicate<? super E > filter) inherited
Returns a view exposing only the elements matching the specified filter. Adding elements not matching the specified filter has no effect. If this collection is initially empty, using a filtered view to add new elements ensure that this collection has only elements satisfying the filter predicate.
Definition at line 80 of file FastSet.java.
{
         return new FastSet<E>(new FilteredSetImpl<E>(service(), filter));
     }
flip() [1/2]
void javolution.util.FastBitSet.flip (int bitIndex)
Sets the bit at the index to the opposite value.
Parameters
bitIndex the index of the bit.
Exceptions
IndexOutOfBoundsException if
bitIndex < 0
Definition at line 142 of file FastBitSet.java.
{
         service.flip(bitIndex);
     }
References javolution.util.service.BitSetService.flip(), and javolution.util.FastBitSet.service.
flip() [2/2]
void javolution.util.FastBitSet.flip (int fromIndex, int toIndex)
Sets a range of bits to the opposite value.
Parameters
fromIndex the low index (inclusive).
toIndex the high index (exclusive).
Exceptions
IndexOutOfBoundsException if
(fromIndex < 0) | (toIndex < fromIndex)
Definition at line 155 of file FastBitSet.java.
{
         service.flip(fromIndex, toIndex);
     }
References javolution.util.service.BitSetService.flip(), and javolution.util.FastBitSet.service.
get() [1/2]
boolean javolution.util.FastBitSet.get (int bitIndex)
Returns
true
if the specified integer is in this bit set;
false
otherwise.
Parameters
bitIndex a non-negative integer.
Returns
the value of the bit at the specified index.
Exceptions
IndexOutOfBoundsException if
bitIndex < 0
Definition at line 167 of file FastBitSet.java.
{
         return service.get(bitIndex);
     }
References javolution.util.service.BitSetService.get(), and javolution.util.FastBitSet.service.
get() [2/2]
FastBitSet javolution.util.FastBitSet.get (int fromIndex, int toIndex)
Returns a new bit set composed of a range of bits from this one.
Parameters
fromIndex the low index (inclusive).
toIndex the high index (exclusive).
Returns
a context allocated bit set instance.
Exceptions
IndexOutOfBoundsException if
(fromIndex < 0) | (toIndex < fromIndex)
Definition at line 181 of file FastBitSet.java.
{
         return new FastBitSet(service.get(fromIndex, toIndex));
     }
References javolution.util.FastBitSet.FastBitSet(), javolution.util.service.BitSetService.get(), and javolution.util.FastBitSet.service.
intersects()
boolean javolution.util.FastBitSet.intersects (FastBitSet that)
Returns
true
if this bit set shares at least one common bit with the specified bit set.
Parameters
that the bit set to check for intersection
Returns
true
if the sets intersect;
false
otherwise.
Definition at line 193 of file FastBitSet.java.
{
         return service.intersects(that.service);
     }
References javolution.util.service.BitSetService.intersects(), and javolution.util.FastBitSet.service.
isEmpty()
boolean javolution.util.FastSet< E >.isEmpty inherited
Indicates if this collection is empty.
Definition at line 100 of file FastSet.java.
{
         return size() == 0;
     }
length()
int javolution.util.FastBitSet.length ()
Returns the logical number of bits actually used by this bit set. It returns the index of the highest set bit plus one.
Note: This method does not return the number of set bits which is returned by size
Returns
the index of the highest set bit plus one.
Definition at line 206 of file FastBitSet.java.
{
         return service.length();
     }
References javolution.util.service.BitSetService.length(), and javolution.util.FastBitSet.service.
nextClearBit()
int javolution.util.FastBitSet.nextClearBit (int fromIndex)
Returns the index of the next
false
bit, from the specified bit (inclusive).
Parameters
fromIndex the start location.
Returns
the first
false
bit.
Exceptions
IndexOutOfBoundsException if
fromIndex < 0
Definition at line 218 of file FastBitSet.java.
{
         return service.nextClearBit(fromIndex);
     }
References javolution.util.service.BitSetService.nextClearBit(), and javolution.util.FastBitSet.service.
nextSetBit()
int javolution.util.FastBitSet.nextSetBit (int fromIndex)
Returns the index of the next
true
bit, from the specified bit (inclusive). If there is none,
-1
is returned. The following code will iterates through the bit set:[code] for (int i=nextSetBit(0); i >= 0; i = nextSetBit(i+1)) { ... }[/code]
Parameters
fromIndex the start location.
Returns
the first
false
bit.
Exceptions
IndexOutOfBoundsException if
fromIndex < 0
Definition at line 234 of file FastBitSet.java.
{
         return service.nextSetBit(fromIndex);
     }
References javolution.util.service.BitSetService.nextSetBit(), and javolution.util.FastBitSet.service.
or()
void javolution.util.FastBitSet.or (FastBitSet that)
Performs the logical OR operation on this bit set and the one specified. In other words, builds the union of the two sets.
The result is stored into this bit set.
Parameters
that the second bit set.
Definition at line 274 of file FastBitSet.java.
{
         service.or(that.service);
     }
References javolution.util.service.BitSetService.or(), and javolution.util.FastBitSet.service.
previousClearBit()
int javolution.util.FastBitSet.previousClearBit (int fromIndex)
Returns the index of the previous
false
bit, from the specified bit (inclusive).
Parameters
fromIndex the start location.
Returns
the first
false
bit.
Exceptions
IndexOutOfBoundsException if
fromIndex < -1
Definition at line 246 of file FastBitSet.java.
{
         return service.previousClearBit(fromIndex);
     }
References javolution.util.service.BitSetService.previousClearBit(), and javolution.util.FastBitSet.service.
previousSetBit()
int javolution.util.FastBitSet.previousSetBit (int fromIndex)
Returns the index of the previous
true
bit, from the specified bit (inclusive). If there is none,
-1
is returned. The following code will iterates through the bit set:[code] for (int i = length(); (i = previousSetBit(i-1)) >= 0;) { ... }[/code]
Parameters
fromIndex the start location.
Returns
the first
false
bit.
Exceptions
IndexOutOfBoundsException if
fromIndex < -1
Definition at line 262 of file FastBitSet.java.
{
         return service.previousSetBit(fromIndex);
     }
References javolution.util.service.BitSetService.previousSetBit(), and javolution.util.FastBitSet.service.
remove()
boolean javolution.util.FastSet< E >.remove (Object obj) inherited
Removes the specified element from this collection.
Definition at line 124 of file FastSet.java.
{
         return service.remove(obj);
     }
service()
BitSetService javolution.util.FastBitSet.service () protected
Definition at line 357 of file FastBitSet.java.
{
         return service;
     }
References javolution.util.FastBitSet.service.
set() [1/4]
void javolution.util.FastBitSet.set (int bitIndex)
Adds the specified integer to this set (corresponding bit is set to
true
.
Parameters
bitIndex a non-negative integer.
Exceptions
IndexOutOfBoundsException if
bitIndex < 0
Definition at line 285 of file FastBitSet.java.
{
         service.set(bitIndex);
     }
References javolution.util.FastBitSet.service, and javolution.util.service.BitSetService.set().
set() [2/4]
void javolution.util.FastBitSet.set (int bitIndex, boolean value)
Sets the bit at the given index to the specified value.
Parameters
bitIndex the position to set.
value the value to set it to.
Exceptions
IndexOutOfBoundsException if
bitIndex < 0
Definition at line 296 of file FastBitSet.java.
{
         service.set(bitIndex, value);
     }
References javolution.util.FastBitSet.service, and javolution.util.service.BitSetService.set().
set() [3/4]
void javolution.util.FastBitSet.set (int fromIndex, int toIndex)
Sets the bits from the specified
fromIndex
(inclusive) to the specified
toIndex
(exclusive) to
true
.
Parameters
fromIndex index of the first bit to be set.
toIndex index after the last bit to be set.
Exceptions
IndexOutOfBoundsException if
(fromIndex < 0) | (toIndex < fromIndex)
Definition at line 310 of file FastBitSet.java.
{
         if ((fromIndex < 0) || (toIndex < fromIndex)) throw new IndexOutOfBoundsException();
         service.set(fromIndex, toIndex);
     }
References javolution.util.FastBitSet.service, and javolution.util.service.BitSetService.set().
set() [4/4]
void javolution.util.FastBitSet.set (int fromIndex, int toIndex, boolean value)
Sets the bits between from (inclusive) and to (exclusive) to the specified value.
Parameters
fromIndex the start range (inclusive).
toIndex the end range (exclusive).
value the value to set it to.
Exceptions
IndexOutOfBoundsException if
bitIndex < 0
Definition at line 325 of file FastBitSet.java.
{
         service.set(fromIndex, toIndex, value);
     }
References javolution.util.FastBitSet.service, and javolution.util.service.BitSetService.set().
shared()
FastBitSet javolution.util.FastBitSet.shared ()
Definition at line 60 of file FastBitSet.java.
{
         throw new UnsupportedOperationException("NOT DONE YET"); // TODO
     }
size()
int javolution.util.FastSet< E >.size inherited
Returns the size of this collection.
Definition at line 106 of file FastSet.java.
                       {
         return service.size();
     }
unmodifiable()
FastBitSet javolution.util.FastBitSet.unmodifiable ()
Definition at line 55 of file FastBitSet.java.
{
         throw new UnsupportedOperationException("NOT DONE YET"); // TODO
     }
xor()
void javolution.util.FastBitSet.xor (FastBitSet that)
Performs the logical XOR operation on this bit set and the one specified. In other words, builds the symmetric remainder of the two sets (the elements that are in one set, but not in the other).
The result is stored into this bit set.
Parameters
that the second bit set.
Definition at line 338 of file FastBitSet.java.
{
         service.xor(that.service);
     }
References javolution.util.FastBitSet.service, and javolution.util.service.BitSetService.xor().
Member Data Documentation
serialVersionUID
final long javolution.util.FastBitSet.serialVersionUID = 0x600L static private
Definition at line 29 of file FastBitSet.java.
service
final BitSetService javolution.util.FastBitSet.service private
Holds the bit set implementation.
Definition at line 34 of file FastBitSet.java.
Referenced by javolution.util.FastBitSet.and(), javolution.util.FastBitSet.andNot(), javolution.util.FastBitSet.cardinality(), javolution.util.FastBitSet.clear(), javolution.util.FastBitSet.FastBitSet(), javolution.util.FastBitSet.flip(), javolution.util.FastBitSet.get(), javolution.util.FastBitSet.intersects(), javolution.util.FastBitSet.length(), javolution.util.FastBitSet.nextClearBit(), javolution.util.FastBitSet.nextSetBit(), javolution.util.FastBitSet.or(), javolution.util.FastBitSet.previousClearBit(), javolution.util.FastBitSet.previousSetBit(), javolution.util.FastBitSet.service(), javolution.util.FastBitSet.set(), and javolution.util.FastBitSet.xor().
The documentation for this class was generated from the following file:
FastBitSet.java