Javolution 6.0.0 java: javolution.xml.sax.XMLReaderImpl Class Reference
javolution.xml.sax.XMLReaderImpl Class Reference
Public Member Functions
XMLReaderImpl ()
void parse (InputStream in) throws IOException, SAXException
void parse (InputStream in, String encoding) throws IOException, SAXException
void parse (Reader reader) throws IOException, SAXException
void parse (InputSource input) throws IOException, SAXException
void parse (String systemId) throws IOException, SAXException
void setContentHandler (ContentHandler handler)
ContentHandler getContentHandler ()
void setErrorHandler (ErrorHandler handler)
ErrorHandler getErrorHandler ()
boolean getFeature (String name) throws SAXNotRecognizedException, SAXNotSupportedException
void setFeature (String name, boolean value) throws SAXNotRecognizedException, SAXNotSupportedException
Object getProperty (String name) throws SAXNotRecognizedException, SAXNotSupportedException
void setProperty (String name, Object value) throws SAXNotRecognizedException, SAXNotSupportedException
void setEntityResolver (EntityResolver resolver)
EntityResolver getEntityResolver ()
void setDTDHandler (DTDHandler handler)
DTDHandler getDTDHandler ()
void reset ()
Private Member Functions
void parseAll () throws XMLStreamException, SAXException
Private Attributes
ContentHandler _contentHandler
ErrorHandler _errorHandler
final XMLStreamReaderImpl _xmlReader = new XMLStreamReaderImpl()
EntityResolver _entityResolver
DTDHandler _dtdHandler
Static Private Attributes
static DefaultHandler DEFAULT_HANDLER = new DefaultHandler()
static final CharArray NO_CHAR = new CharArray("")
Detailed Description
This class provides a real-time SAX2-like XML parser; this parser is extremely fast and does not create temporary objects (no garbage generated and no GC interruption).
The parser is implemented as a SAX2 wrapper around
XMLStreamReaderImpl and share the same characteristics.
Note: This parser is a SAX2-like parser with the java.lang.String type replaced by CharArray/CharSequence in the ContentHandler, Attributes interfaces and DefaultHandler base class. If a standard SAX2 or JAXP parser is required, you may consider using the wrapping class SAX2ReaderImpl. Fast but not as fast as java.lang.String instances are dynamically allocated while parsing.
Author
Jean-Marie Dautelle
Version
4.0, June 16, 2006
Definition at line 48 of file XMLReaderImpl.java.
Constructor & Destructor Documentation
XMLReaderImpl()
javolution.xml.sax.XMLReaderImpl.XMLReaderImpl ()
Default constructor.
Definition at line 73 of file XMLReaderImpl.java.
{
         // Sets default handlers.
         setContentHandler(DEFAULT_HANDLER);
         setErrorHandler(DEFAULT_HANDLER);
     }
References javolution.xml.sax.XMLReaderImpl.DEFAULT_HANDLER, javolution.xml.sax.XMLReaderImpl.setContentHandler(), and javolution.xml.sax.XMLReaderImpl.setErrorHandler().
Member Function Documentation
getContentHandler()
ContentHandler javolution.xml.sax.XMLReaderImpl.getContentHandler ()
Return the current content handler.
Returns
The current content handler, or null if none has been registered.
See also
setContentHandler
Implements javolution.xml.sax.XMLReader.
Definition at line 195 of file XMLReaderImpl.java.
{
         return (_contentHandler == DEFAULT_HANDLER) ? null : _contentHandler;
     }
References javolution.xml.sax.XMLReaderImpl._contentHandler, and javolution.xml.sax.XMLReaderImpl.DEFAULT_HANDLER.
getDTDHandler()
DTDHandler javolution.xml.sax.XMLReaderImpl.getDTDHandler ()
Return the current DTD handler.
Returns
The current DTD handler, or null if none has been registered.
See also
setDTDHandler
Implements javolution.xml.sax.XMLReader.
Definition at line 266 of file XMLReaderImpl.java.
{
         return _dtdHandler;
     }
References javolution.xml.sax.XMLReaderImpl._dtdHandler.
Referenced by javolution.xml.sax.SAX2ReaderImpl.getDTDHandler().
getEntityResolver()
EntityResolver javolution.xml.sax.XMLReaderImpl.getEntityResolver ()
Return the current entity resolver.
Returns
The current entity resolver, or null if none has been registered.
See also
setEntityResolver
Implements javolution.xml.sax.XMLReader.
Definition at line 256 of file XMLReaderImpl.java.
{
         return _entityResolver;
     }
References javolution.xml.sax.XMLReaderImpl._entityResolver.
Referenced by javolution.xml.sax.SAX2ReaderImpl.getEntityResolver().
getErrorHandler()
ErrorHandler javolution.xml.sax.XMLReaderImpl.getErrorHandler ()
Return the current error handler.
Returns
The current error handler, or null if none has been registered.
See also
setErrorHandler
Implements javolution.xml.sax.XMLReader.
Definition at line 209 of file XMLReaderImpl.java.
{
         return (_errorHandler == DEFAULT_HANDLER) ? null : _errorHandler;
     }
References javolution.xml.sax.XMLReaderImpl._errorHandler, and javolution.xml.sax.XMLReaderImpl.DEFAULT_HANDLER.
Referenced by javolution.xml.sax.SAX2ReaderImpl.getErrorHandler().
getFeature()
boolean javolution.xml.sax.XMLReaderImpl.getFeature (String name) throws SAXNotRecognizedException, SAXNotSupportedException
Look up the value of a feature flag.
The feature name is any fully-qualified URI. It is possible for an XMLReader to recognize a feature name but temporarily be unable to return its value. Some feature values may be available only in specific contexts, such as before, during, or after a parse. Also, some feature values may not be programmatically accessible. (In the case of an adapter for SAX1 org.xml.sax.Parser, there is no implementation-independent way to expose whether the underlying parser is performing validation, expanding external entities, and so forth.)
All XMLReaders are required to recognize the http://xml.org/sax/features/namespaces and the http://xml.org/sax/features/namespace-prefixes feature names.
Typical usage is something like this:
XMLReader r = new MySAXDriver();
                        // try to activate validation
try {
  r.setFeature("http://xml.org/sax/features/validation", true);
} catch (SAXException e) {
  System.err.println("Cannot activate validation.");
}
                        // register event handlers
r.setContentHandler(new MyContentHandler());
r.setErrorHandler(new MyErrorHandler());
                        // parse the first document
try {
  r.parse("http://www.foo.com/mydoc.xml");
} catch (IOException e) {
  System.err.println("I/O exception reading XML document");
} catch (SAXException e) {
  System.err.println("XML exception reading document.");
}
Implementors are free (and encouraged) to invent their own features, using names built on their own URIs.
Parameters
name The feature name, which is a fully-qualified URI.
Returns
The current value of the feature (true or false).
Exceptions
org.xml.sax.SAXNotRecognizedException If the feature value can't be assigned or retrieved.
org.xml.sax.SAXNotSupportedException When the XMLReader recognizes the feature name but cannot determine its value at this time.
See also
setFeature
Implements javolution.xml.sax.XMLReader.
Definition at line 214 of file XMLReaderImpl.java.
{
         if (name.equals("http://xml.org/sax/features/namespaces")) {
             return true;
         } else if (name
                 .equals("http://xml.org/sax/features/namespace-prefixes")) {
             return true;
         } else {
             throw new SAXNotRecognizedException("Feature " + name
                     + " not recognized");
         }
     }
Referenced by javolution.xml.sax.SAX2ReaderImpl.getFeature().
getProperty()
Object javolution.xml.sax.XMLReaderImpl.getProperty (String name) throws SAXNotRecognizedException, SAXNotSupportedException
Look up the value of a property.
The property name is any fully-qualified URI. It is possible for an XMLReader to recognize a property name but temporarily be unable to return its value. Some property values may be available only in specific contexts, such as before, during, or after a parse.
XMLReaders are not required to recognize any specific property names, though an initial core set is documented for SAX2.
Implementors are free (and encouraged) to invent their own properties, using names built on their own URIs.
Parameters
name The property name, which is a fully-qualified URI.
Returns
The current value of the property.
Exceptions
org.xml.sax.SAXNotRecognizedException If the property value can't be assigned or retrieved.
org.xml.sax.SAXNotSupportedException When the XMLReader recognizes the property name but cannot determine its value at this time.
See also
setProperty
Implements javolution.xml.sax.XMLReader.
Definition at line 238 of file XMLReaderImpl.java.
{
         throw new SAXNotRecognizedException("Property " + name
                 + " not recognized");
     }
Referenced by javolution.xml.sax.SAX2ReaderImpl.getProperty().
parse() [1/5]
void javolution.xml.sax.XMLReaderImpl.parse (InputSource input) throws IOException, SAXException
Parse an XML document.
The application can use this method to instruct the XML reader to begin parsing an XML document from any valid input source (a character stream, a byte stream, or a URI).
Applications may not invoke this method while a parse is in progress (they should create a new XMLReader instead for each nested XML document). Once a parse is complete, an application may reuse the same XMLReader object, possibly with a different input source. Configuration of the XMLReader object (such as handler bindings and values established for feature flags and properties) is unchanged by completion of a parse, unless the definition of that aspect of the configuration explicitly specifies other behavior. (For example, feature flags or properties exposing characteristics of the document being parsed.)
During the parse, the XMLReader will provide information about the XML document through the registered event handlers.
This method is synchronous: it will not return until parsing has ended. If a client application wants to terminate parsing early, it should throw an exception.
Parameters
input The input source for the top-level of the XML document.
Exceptions
org.xml.sax.SAXException Any SAX exception, possibly wrapping another exception.
j2me.io.IOException An IO exception from the parser, possibly from a byte stream or character stream supplied by the application.
See also
org.xml.sax.InputSource
setEntityResolver
setDTDHandler
setContentHandler
setErrorHandler
Implements javolution.xml.sax.XMLReader.
Definition at line 154 of file XMLReaderImpl.java.
{
         Reader reader = input.getCharacterStream();
         if (reader != null) {
             parse(reader);
         } else {
             InputStream inStream = input.getByteStream();
             if (inStream != null) {
                 parse(inStream, input.getEncoding());
             } else {
                 parse(input.getSystemId());
             }
         }
     }
References javolution.xml.sax.XMLReaderImpl.parse().
parse() [2/5]
void javolution.xml.sax.XMLReaderImpl.parse (InputStream in) throws IOException, SAXException
Parses an XML document from the specified input stream (encoding retrieved from input source and the XML prolog if any).
Parameters
in the input stream with unknown encoding.
Exceptions
org.xml.sax.SAXException any SAX exception, possibly wrapping another exception.
IOException an IO exception from the parser, possibly from a byte stream or character stream supplied by the application.
Definition at line 90 of file XMLReaderImpl.java.
{
         try {
             _xmlReader.setInput(in);
             parseAll();
         } catch (XMLStreamException e) {
             if (e.getNestedException() instanceof IOException)
                 throw (IOException) e.getNestedException();
             throw new SAXException(e.getMessage());
         } finally {
             _xmlReader.reset();
         }
     }
References javolution.xml.sax.XMLReaderImpl._xmlReader, javolution.xml.stream.XMLStreamException.getNestedException(), javolution.xml.sax.XMLReaderImpl.parseAll(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
Referenced by javolution.xml.sax.SAX2ReaderImpl.parse(), and javolution.xml.sax.XMLReaderImpl.parse().
parse() [3/5]
void javolution.xml.sax.XMLReaderImpl.parse (InputStream in, String encoding) throws IOException, SAXException
Parses an XML document from the specified input stream and encoding.
Parameters
in the input stream.
encoding the input stream encoding.
Exceptions
org.xml.sax.SAXException any SAX exception, possibly wrapping another exception.
IOException an IO exception from the parser, possibly from a byte stream or character stream supplied by the application.
Definition at line 114 of file XMLReaderImpl.java.
{
         try {
             _xmlReader.setInput(in, encoding);
             parseAll();
         } catch (XMLStreamException e) {
             if (e.getNestedException() instanceof IOException)
                 throw (IOException) e.getNestedException();
             throw new SAXException(e.getMessage());
         } finally {
             _xmlReader.reset();
         }
     }
References javolution.xml.sax.XMLReaderImpl._xmlReader, javolution.xml.stream.XMLStreamException.getNestedException(), javolution.xml.sax.XMLReaderImpl.parseAll(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
parse() [4/5]
void javolution.xml.sax.XMLReaderImpl.parse (Reader reader) throws IOException, SAXException
Parses an XML document using the specified reader.
Parameters
reader the document reader.
Exceptions
SAXException any SAX exception, possibly wrapping another exception.
IOException an IO exception from the parser, possibly from a byte stream or character stream supplied by the application.
See also
javolution.io.UTF8StreamReader
javolution.io.UTF8ByteBufferReader
javolution.io.CharSequenceReader
Definition at line 140 of file XMLReaderImpl.java.
{
         try {
             _xmlReader.setInput(reader);
             parseAll();
         } catch (XMLStreamException e) {
             if (e.getNestedException() instanceof IOException)
                 throw (IOException) e.getNestedException();
             throw new SAXException(e.getMessage());
         } finally {
             _xmlReader.reset();
         }
     }
References javolution.xml.sax.XMLReaderImpl._xmlReader, javolution.xml.stream.XMLStreamException.getNestedException(), javolution.xml.sax.XMLReaderImpl.parseAll(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
parse() [5/5]
void javolution.xml.sax.XMLReaderImpl.parse (String systemId) throws IOException, SAXException
Parse an XML document from a system identifier (URI).
This method is a shortcut for the common case of reading a document from a system identifier. It is the exact equivalent of the following:
parse(new InputSource(systemId));
If the system identifier is a URL, it must be fully resolved by the application before it is passed to the parser.
Parameters
systemId The system identifier (URI).
Exceptions
org.xml.sax.SAXException Any SAX exception, possibly wrapping another exception.
j2me.io.IOException An IO exception from the parser, possibly from a byte stream or character stream supplied by the application.
See also
parse(org.xml.sax.InputSource)
Implements javolution.xml.sax.XMLReader.
Definition at line 169 of file XMLReaderImpl.java.
{
         InputStream inStream;
         try {
             URL url = new URL(systemId);
             inStream = url.openStream();
         } catch (Exception urlException) { // Try as filename.
             try {
                 inStream = new FileInputStream(systemId);
             } catch (Exception fileException) {
                 throw new UnsupportedOperationException("Cannot parse "
                         + systemId);
             }
         }
         parse(inStream);
     }
References javolution.xml.sax.XMLReaderImpl.parse().
parseAll()
void javolution.xml.sax.XMLReaderImpl.parseAll () throws XMLStreamException, SAXException private
Parses the whole document using the real-time pull parser.
Exceptions
SAXException any SAX exception, possibly wrapping another exception.
IOException an IO exception from the parser, possibly from a byte stream or character stream supplied by the application.
Definition at line 285 of file XMLReaderImpl.java.
{
         int eventType = _xmlReader.getEventType();
         if (eventType != XMLStreamConstants.START_DOCUMENT)
             throw new SAXException("Currently parsing");
         _contentHandler.startDocument();
         boolean doContinue = true;
         while (doContinue) {
             CharArray uri, localName, qName, prefix, text;
             switch (_xmlReader.next()) {
                 case XMLStreamConstants.START_ELEMENT:
                     // Start prefix mapping.
                     for (int i = 0, count = _xmlReader.getNamespaceCount(); i < count; i++) {
                         prefix = _xmlReader.getNamespacePrefix(i);
                         prefix = (prefix == null) ? NO_CHAR : prefix; // Default namespace is ""
                         uri = _xmlReader.getNamespaceURI(i);
                         _contentHandler.startPrefixMapping(prefix, uri);
                     }
                     // Start element.
                     uri = _xmlReader.getNamespaceURI();
                     uri = (uri == null) ? NO_CHAR : uri;
                     localName = _xmlReader.getLocalName();
                     qName = _xmlReader.getQName();
                     _contentHandler.startElement(uri, localName, qName,
                             _xmlReader.getAttributes());
                     break;
                 case XMLStreamConstants.END_ELEMENT:
                     // End element.
                     uri = _xmlReader.getNamespaceURI();
                     uri = (uri == null) ? NO_CHAR : uri;
                     localName = _xmlReader.getLocalName();
                     qName = _xmlReader.getQName();
                     _contentHandler.endElement(uri, localName, qName);
                     // End prefix mapping.
                     for (int i = 0, count = _xmlReader.getNamespaceCount(); i < count; i++) {
                         prefix = _xmlReader.getNamespacePrefix(i);
                         prefix = (prefix == null) ? NO_CHAR : prefix; // Default namespace is ""
                         _contentHandler.endPrefixMapping(prefix);
                     }
                     break;
                 case XMLStreamConstants.CDATA:
                 case XMLStreamConstants.CHARACTERS:
                     text = _xmlReader.getText();
                     _contentHandler.characters(text.array(), text.offset(),
                             text.length());
                     break;
                 case XMLStreamConstants.SPACE:
                     text = _xmlReader.getText();
                     _contentHandler.ignorableWhitespace(text.array(),
                             text.offset(), text.length());
                     break;
                 case XMLStreamConstants.PROCESSING_INSTRUCTION:
                     _contentHandler.processingInstruction(
                             _xmlReader.getPITarget(), _xmlReader.getPIData());
                     break;
                 case XMLStreamConstants.COMMENT:
                     // Ignores.
                     break;
                 case XMLStreamConstants.END_DOCUMENT:
                     doContinue = false;
                     _xmlReader.close();
                     break;
             }
         }
     }
References javolution.xml.sax.XMLReaderImpl._contentHandler, javolution.xml.sax.XMLReaderImpl._xmlReader, javolution.text.CharArray.array(), javolution.xml.stream.XMLStreamConstants.CDATA, javolution.xml.stream.XMLStreamConstants.CHARACTERS, javolution.xml.sax.ContentHandler.characters(), javolution.xml.internal.stream.XMLStreamReaderImpl.close(), javolution.xml.stream.XMLStreamConstants.COMMENT, javolution.xml.stream.XMLStreamConstants.END_DOCUMENT, javolution.xml.stream.XMLStreamConstants.END_ELEMENT, javolution.xml.sax.ContentHandler.endElement(), javolution.xml.sax.ContentHandler.endPrefixMapping(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributes(), javolution.xml.internal.stream.XMLStreamReaderImpl.getEventType(), javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceCount(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespacePrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPIData(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPITarget(), javolution.xml.internal.stream.XMLStreamReaderImpl.getQName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getText(), javolution.xml.sax.ContentHandler.ignorableWhitespace(), javolution.text.CharArray.length(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.sax.XMLReaderImpl.NO_CHAR, javolution.text.CharArray.offset(), javolution.xml.stream.XMLStreamConstants.PROCESSING_INSTRUCTION, javolution.xml.sax.ContentHandler.processingInstruction(), javolution.xml.stream.XMLStreamConstants.SPACE, javolution.xml.stream.XMLStreamConstants.START_DOCUMENT, javolution.xml.stream.XMLStreamConstants.START_ELEMENT, javolution.xml.sax.ContentHandler.startDocument(), javolution.xml.sax.ContentHandler.startElement(), and javolution.xml.sax.ContentHandler.startPrefixMapping().
Referenced by javolution.xml.sax.XMLReaderImpl.parse().
reset()
void javolution.xml.sax.XMLReaderImpl.reset ()
Definition at line 271 of file XMLReaderImpl.java.
{
         setContentHandler(DEFAULT_HANDLER);
         setErrorHandler(DEFAULT_HANDLER);
         _xmlReader.reset();
     }
References javolution.xml.sax.XMLReaderImpl._xmlReader, javolution.xml.sax.XMLReaderImpl.DEFAULT_HANDLER, javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), javolution.xml.sax.XMLReaderImpl.setContentHandler(), and javolution.xml.sax.XMLReaderImpl.setErrorHandler().
Referenced by javolution.xml.sax.SAX2ReaderImpl.parse(), and javolution.xml.sax.SAX2ReaderImpl.reset().
setContentHandler()
void javolution.xml.sax.XMLReaderImpl.setContentHandler (ContentHandler handler)
Allow an application to register a content event handler.
If the application does not register a content handler, all content events reported by the SAX parser will be silently ignored.
Applications may register a new or different handler in the middle of a parse, and the SAX parser must begin using the new handler immediately.
Parameters
handler The content handler.
See also
getContentHandler
Implements javolution.xml.sax.XMLReader.
Definition at line 186 of file XMLReaderImpl.java.
{
         if (handler != null) {
             _contentHandler = handler;
         } else {
             throw new NullPointerException();
         }
     }
References javolution.xml.sax.XMLReaderImpl._contentHandler.
Referenced by javolution.xml.sax.XMLReaderImpl.reset(), javolution.xml.sax.SAX2ReaderImpl.setContentHandler(), and javolution.xml.sax.XMLReaderImpl.XMLReaderImpl().
setDTDHandler()
void javolution.xml.sax.XMLReaderImpl.setDTDHandler (DTDHandler handler)
Allow an application to register a DTD event handler.
If the application does not register a DTD handler, all DTD events reported by the SAX parser will be silently ignored.
Applications may register a new or different handler in the middle of a parse, and the SAX parser must begin using the new handler immediately.
Parameters
handler The DTD handler.
See also
getDTDHandler
Implements javolution.xml.sax.XMLReader.
Definition at line 260 of file XMLReaderImpl.java.
{
         _dtdHandler = handler;
     }
References javolution.xml.sax.XMLReaderImpl._dtdHandler.
Referenced by javolution.xml.sax.SAX2ReaderImpl.setDTDHandler().
setEntityResolver()
void javolution.xml.sax.XMLReaderImpl.setEntityResolver (EntityResolver resolver)
Allow an application to register an entity resolver.
If the application does not register an entity resolver, the XMLReader will perform its own default resolution.
Applications may register a new or different resolver in the middle of a parse, and the SAX parser must begin using the new resolver immediately.
Parameters
resolver The entity resolver.
See also
getEntityResolver
Implements javolution.xml.sax.XMLReader.
Definition at line 250 of file XMLReaderImpl.java.
{
         _entityResolver = resolver;
     }
References javolution.xml.sax.XMLReaderImpl._entityResolver.
Referenced by javolution.xml.sax.SAX2ReaderImpl.setEntityResolver().
setErrorHandler()
void javolution.xml.sax.XMLReaderImpl.setErrorHandler (ErrorHandler handler)
Allow an application to register an error event handler.
If the application does not register an error handler, all error events reported by the SAX parser will be silently ignored; however, normal processing may not continue. It is highly recommended that all SAX applications implement an error handler to avoid unexpected bugs.
Applications may register a new or different handler in the middle of a parse, and the SAX parser must begin using the new handler immediately.
Parameters
handler The error handler.
See also
getErrorHandler
Implements javolution.xml.sax.XMLReader.
Definition at line 200 of file XMLReaderImpl.java.
{
         if (handler != null) {
             _errorHandler = handler;
         } else {
             throw new NullPointerException();
         }
     }
References javolution.xml.sax.XMLReaderImpl._errorHandler.
Referenced by javolution.xml.sax.XMLReaderImpl.reset(), javolution.xml.sax.SAX2ReaderImpl.setErrorHandler(), and javolution.xml.sax.XMLReaderImpl.XMLReaderImpl().
setFeature()
void javolution.xml.sax.XMLReaderImpl.setFeature (String name, boolean value) throws SAXNotRecognizedException, SAXNotSupportedException
Set the value of a feature flag.
The feature name is any fully-qualified URI. It is possible for an XMLReader to expose a feature value but to be unable to change the current value. Some feature values may be immutable or mutable only in specific contexts, such as before, during, or after a parse.
All XMLReaders are required to support setting http://xml.org/sax/features/namespaces to true and http://xml.org/sax/features/namespace-prefixes to false.
Parameters
name The feature name, which is a fully-qualified URI.
value The requested value of the feature (true or false).
Exceptions
org.xml.sax.SAXNotRecognizedException If the feature value can't be assigned or retrieved.
org.xml.sax.SAXNotSupportedException When the XMLReader recognizes the feature name but cannot set the requested value.
See also
getFeature
Implements javolution.xml.sax.XMLReader.
Definition at line 227 of file XMLReaderImpl.java.
{
         if (name.equals("http://xml.org/sax/features/namespaces")
                 || name.equals("http://xml.org/sax/features/namespace-prefixes")) {
             return; // Ignores, these features are always set.
         } else {
             throw new SAXNotRecognizedException("Feature " + name
                     + " not recognized");
         }
     }
Referenced by javolution.xml.sax.SAX2ReaderImpl.setFeature().
setProperty()
void javolution.xml.sax.XMLReaderImpl.setProperty (String name, Object value) throws SAXNotRecognizedException, SAXNotSupportedException
Set the value of a property.
The property name is any fully-qualified URI. It is possible for an XMLReader to recognize a property name but to be unable to change the current value. Some property values may be immutable or mutable only in specific contexts, such as before, during, or after a parse.
XMLReaders are not required to recognize setting any specific property names, though a core set is defined by SAX2.
This method is also the standard mechanism for setting extended handlers.
Parameters
name The property name, which is a fully-qualified URI.
value The requested value for the property.
Exceptions
org.xml.sax.SAXNotRecognizedException If the property value can't be assigned or retrieved.
org.xml.sax.SAXNotSupportedException When the XMLReader recognizes the property name but cannot set the requested value.
Implements javolution.xml.sax.XMLReader.
Definition at line 244 of file XMLReaderImpl.java.
{
         throw new SAXNotRecognizedException("Property " + name
                 + " not recognized");
     }
Referenced by javolution.xml.sax.SAX2ReaderImpl.setProperty().
Member Data Documentation
_contentHandler
ContentHandler javolution.xml.sax.XMLReaderImpl._contentHandler private
Holds the content handler.
Definition at line 58 of file XMLReaderImpl.java.
Referenced by javolution.xml.sax.XMLReaderImpl.getContentHandler(), javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.sax.XMLReaderImpl.setContentHandler().
_dtdHandler
DTDHandler javolution.xml.sax.XMLReaderImpl._dtdHandler private
Definition at line 264 of file XMLReaderImpl.java.
Referenced by javolution.xml.sax.XMLReaderImpl.getDTDHandler(), and javolution.xml.sax.XMLReaderImpl.setDTDHandler().
_entityResolver
EntityResolver javolution.xml.sax.XMLReaderImpl._entityResolver private
Definition at line 254 of file XMLReaderImpl.java.
Referenced by javolution.xml.sax.XMLReaderImpl.getEntityResolver(), and javolution.xml.sax.XMLReaderImpl.setEntityResolver().
_errorHandler
ErrorHandler javolution.xml.sax.XMLReaderImpl._errorHandler private
Holds the error handler.
Definition at line 63 of file XMLReaderImpl.java.
Referenced by javolution.xml.sax.XMLReaderImpl.getErrorHandler(), and javolution.xml.sax.XMLReaderImpl.setErrorHandler().
_xmlReader
final XMLStreamReaderImpl javolution.xml.sax.XMLReaderImpl._xmlReader = new XMLStreamReaderImpl() private
Holds reusable StAX reader.
Definition at line 68 of file XMLReaderImpl.java.
Referenced by javolution.xml.sax.XMLReaderImpl.parse(), javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.sax.XMLReaderImpl.reset().
DEFAULT_HANDLER
DefaultHandler javolution.xml.sax.XMLReaderImpl.DEFAULT_HANDLER = new DefaultHandler() static private
Holds the default handler instance.
Definition at line 53 of file XMLReaderImpl.java.
Referenced by javolution.xml.sax.XMLReaderImpl.getContentHandler(), javolution.xml.sax.XMLReaderImpl.getErrorHandler(), javolution.xml.sax.XMLReaderImpl.reset(), and javolution.xml.sax.XMLReaderImpl.XMLReaderImpl().
NO_CHAR
final CharArray javolution.xml.sax.XMLReaderImpl.NO_CHAR = new CharArray("") static private
Definition at line 362 of file XMLReaderImpl.java.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll().
The documentation for this class was generated from the following file:
XMLReaderImpl.java