Javolution 6.0.0 java: javolution.util.internal.collection.AtomicCollectionImpl< E > Class Template Reference
javolution.util.internal.collection.AtomicCollectionImpl< E > Class Template Reference
Classes
class IteratorImpl
Public Member Functions
AtomicCollectionImpl (CollectionService< E > target)
synchronized boolean add (E element)
synchronized boolean addAll (Collection<? extends E > c)
synchronized void clear ()
synchronized AtomicCollectionImpl< E > clone ()
Equality<? super E > comparator ()
boolean contains (Object o)
boolean containsAll (Collection<?> c)
boolean equals (Object o)
int hashCode ()
boolean isEmpty ()
Iterator< E > iterator ()
synchronized boolean remove (Object o)
synchronized boolean removeAll (Collection<?> c)
synchronized boolean retainAll (Collection<?> c)
int size ()
CollectionService< E >[] split (int n)
CollectionService< E > threadSafe ()
Object[] toArray ()
synchronized void update (Consumer< CollectionService< E >> action, CollectionService< E > view)
FastCollection< E > addAll (E... elements)
FastCollection< E > addAll (FastCollection<? extends E > that)
void perform (Consumer< CollectionService< E >> action, CollectionService< E > view)
void perform (Consumer<? extends Collection< E >> action)
void perform (Consumer< T > action, T part)
void update (Consumer<? extends Collection< E >> action)
void update (Consumer< T > action, T part)
FastCollection< E > atomic ()
FastCollection< E > shared ()
FastCollection< E > parallel ()
FastCollection< E > sequential ()
FastCollection< E > unmodifiable ()
FastCollection< E > filtered (Predicate<? super E > filter)
FastCollection< E > sorted ()
FastCollection< E > sorted (Comparator<? super E > cmp)
FastCollection< E > reversed ()
FastCollection< E > distinct ()
void forEach (final Consumer<? super E > consumer)
boolean removeIf (final Predicate<? super E > filter)
E reduce (Reducer< E > reducer)
E min ()
E max ()
String toString ()
Protected Member Functions
CollectionService< E > targetView ()
CollectionService< E > cloneTarget ()
final boolean updateInProgress ()
CollectionService< E > target ()
CollectionService< E > service ()
Static Protected Member Functions
static< E > CollectionService< E > serviceOf (FastCollection< E > collection)
Protected Attributes
volatile CollectionService< E > immutable
transient Thread updatingThread
Package Functions
public< T > T[] toArray (T[] a)
public< R > FastCollection< R > mapped (Function<? super E, ? extends R > function)
public< T extends E > T any (Class< T > type)
public< T extends Collection< E > > Immutable< T > toImmutable ()
Private Attributes
CollectionService< E > target
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
An atomic view over a collection (copy-on-write).
Definition at line 21 of file AtomicCollectionImpl.java.
Constructor & Destructor Documentation
AtomicCollectionImpl()
javolution.util.internal.collection.AtomicCollectionImpl< E >.AtomicCollectionImpl (CollectionService< E > target)
Definition at line 55 of file AtomicCollectionImpl.java.
{
         super(target);
         this.immutable = cloneTarget();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), and javolution.util.internal.collection.CollectionView< E >.target.
Member Function Documentation
add()
synchronized boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.add (E element)
Adds the specified element to this collection
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 61 of file AtomicCollectionImpl.java.
{
         boolean changed = target().add(element);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.collection.CollectionView< E >.target, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
addAll() [1/3]
synchronized boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.addAll (Collection<? extends E > that)
Adds all the specified elements to this collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 68 of file AtomicCollectionImpl.java.
{
         boolean changed = target().addAll(c);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.collection.CollectionView< E >.target, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
addAll() [2/3]
FastCollection<E> javolution.util.FastCollection< E >.addAll (E... elements) inherited
Returns this collection with the specified element added.
Parameters
elements the elements to be added.
Returns
this
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSortedSet< E >, javolution.util.FastSet< E >, and javolution.util.FastSortedTable< E >.
Definition at line 552 of file FastCollection.java.
{
         for (E e : elements) {
             add(e);
         }
         return this;
     }
addAll() [3/3]
FastCollection<E> javolution.util.FastCollection< E >.addAll (FastCollection<? extends E > that) inherited
Returns this collection with the specified collection's elements added in sequence.
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSortedSet< E >, javolution.util.FastSet< E >, and javolution.util.FastSortedTable< E >.
Definition at line 564 of file FastCollection.java.
{
         addAll((Collection<? extends E>) that);
         return this;
     }
any()
public<T extends E> T javolution.util.FastCollection< E >.any (Class< T > type) package inherited
Returns any non-null element of the specified type (convenience method).
Parameters
type the element type searched for.
Returns
reduce(Reducers.any(type))
See also
Reducers::any
Definition at line 515 of file FastCollection.java.
{
         return (T) reduce((Reducer<E>) Reducers.any(type));
     }
References javolution.util.function.Reducers.any().
atomic()
FastCollection<E> javolution.util.FastCollection< E >.atomic () inherited
Returns an atomic view over this collection. All operations that write or access multiple elements in the collection (such as addAll(), retainAll()) are atomic. Iterators on atomic collections are thread-safe (no ConcurrentModificationException possible).
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSet< E >, javolution.util.FastSortedTable< E >, and javolution.util.FastSortedSet< E >.
Definition at line 187 of file FastCollection.java.
{
         return new AtomicCollectionImpl<E>(service());
     }
clear()
synchronized void javolution.util.internal.collection.AtomicCollectionImpl< E >.clear ()
Removes all elements from this collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 75 of file AtomicCollectionImpl.java.
{
         clear();
         if (!updateInProgress()) {
             immutable = cloneTarget();
         }
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
clone()
synchronized AtomicCollectionImpl<E> javolution.util.internal.collection.AtomicCollectionImpl< E >.clone ()
Returns a copy of this collection; updates of the copy should not impact the original.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 83 of file AtomicCollectionImpl.java.
                                                         { // Synchronized required since working with real target.
         AtomicCollectionImpl<E> copy = (AtomicCollectionImpl<E>) super.clone();
         copy.updatingThread = null;
         return copy;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.clone(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updatingThread.
Referenced by javolution.util.internal.collection.AtomicCollectionImpl< E >.clone().
cloneTarget()
CollectionService<E> javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget () protected
Returns a clone copy of target.
Definition at line 191 of file AtomicCollectionImpl.java.
{
         try {
             return target().clone();
         } catch (CloneNotSupportedException e) {
             throw new Error("Cannot happen since target is Cloneable.");
         }
     }
References javolution.util.internal.collection.CollectionView< E >.target.
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.add(), javolution.util.internal.collection.AtomicCollectionImpl< E >.add(), javolution.util.internal.table.AtomicTableImpl< E >.addAll(), javolution.util.internal.collection.AtomicCollectionImpl< E >.addAll(), javolution.util.internal.table.AtomicTableImpl< E >.addFirst(), javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >.addIfAbsent(), javolution.util.internal.table.AtomicTableImpl< E >.addLast(), javolution.util.internal.collection.AtomicCollectionImpl< E >.AtomicCollectionImpl(), javolution.util.internal.collection.AtomicCollectionImpl< E >.clear(), javolution.util.internal.table.AtomicTableImpl< E >.offerFirst(), javolution.util.internal.table.AtomicTableImpl< E >.offerLast(), javolution.util.internal.table.AtomicTableImpl< E >.pollFirst(), javolution.util.internal.table.AtomicTableImpl< E >.pollLast(), javolution.util.internal.collection.AtomicCollectionImpl< E >.remove(), javolution.util.internal.table.AtomicTableImpl< E >.remove(), javolution.util.internal.collection.AtomicCollectionImpl< E >.removeAll(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirst(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirstOccurrence(), javolution.util.internal.table.AtomicTableImpl< E >.removeLast(), javolution.util.internal.table.AtomicTableImpl< E >.removeLastOccurrence(), javolution.util.internal.collection.AtomicCollectionImpl< E >.retainAll(), javolution.util.internal.table.AtomicTableImpl< E >.set(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.update().
comparator()
Equality<? super E> javolution.util.internal.collection.AtomicCollectionImpl< E >.comparator ()
Returns the comparator uses by this collection for equality and/or ordering if this collection is sorted.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 90 of file AtomicCollectionImpl.java.
{
         return immutable.comparator();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable.
contains()
boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.contains (Object searched)
Indicates if this collection contains the specified element.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 95 of file AtomicCollectionImpl.java.
{
         return targetView().contains(o);
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
containsAll()
boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.containsAll (Collection<?> that)
Indicates if this collection contains all the specified elements.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 100 of file AtomicCollectionImpl.java.
{
         return targetView().containsAll(c);
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
distinct()
FastCollection<E> javolution.util.FastCollection< E >.distinct () inherited
Returns a view exposing only distinct elements (it does not iterate twice over the same elements). Adding elements already in the collection through this view has no effect. If this collection is initially empty, using a distinct view to add new elements ensures that this collection has no duplicate.
Definition at line 293 of file FastCollection.java.
{
         return new DistinctCollectionImpl<E>(service());
     }
equals()
boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.equals (Object obj)
Compares the specified object with this collection for equality. This method follows the Collection#equals(Object) specification if this collection comparator is Equalities#STANDARD (default). Otherwise, only collections using the same comparator can be considered equals.
Parameters
obj the object to be compared for equality with this collection
Returns
true if both collections are considered equals; false otherwise.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 105 of file AtomicCollectionImpl.java.
{
         return targetView().equals(o);
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
filtered()
FastCollection<E> javolution.util.FastCollection< E >.filtered (Predicate<? super E > filter) inherited
Returns a view exposing only the elements matching the specified filter. Adding elements not matching the specified filter has no effect. If this collection is initially empty, using a filtered view to add new elements ensure that this collection has only elements satisfying the filter predicate.
Reimplemented in javolution.util.FastSet< E >.
Definition at line 250 of file FastCollection.java.
{
         return new FilteredCollectionImpl<E>(service(), filter);
     }
forEach()
void javolution.util.FastCollection< E >.forEach (final Consumer<? super E > consumer) inherited
Iterates over all this collection elements applying the specified consumer (convenience method). Iterations are performed concurrently if the collection is parallel.
Parameters
consumer the functional consumer applied to the collection elements.
Definition at line 346 of file FastCollection.java.
{
         perform(new Consumer<Collection<E>>() {
             public void accept(Collection<E> view) {
                 Iterator<E> it = view.iterator();
                 while (it.hasNext()) {
                     consumer.accept(it.next());
                 }
             }
         });
     }
References javolution.util.function.Consumer< T >.accept().
hashCode()
int javolution.util.internal.collection.AtomicCollectionImpl< E >.hashCode ()
Returns the hash code of this collection. This method follows the Collection#hashCode() specification if this collection comparator is Equalities#STANDARD.
Returns
this collection hash code.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 110 of file AtomicCollectionImpl.java.
{
         return targetView().hashCode();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
isEmpty()
boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.isEmpty ()
Indicates if this collection is empty.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 115 of file AtomicCollectionImpl.java.
{
         return targetView().isEmpty();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
iterator()
Iterator<E> javolution.util.internal.collection.AtomicCollectionImpl< E >.iterator ()
Returns an iterator over this collection elements. For shared/atomic collections the iterator is immune to concurrent modifications. In other words the elements iterated over may or may not reflect the current state of the collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Reimplemented in javolution.util.internal.table.AtomicTableImpl< E >.
Definition at line 120 of file AtomicCollectionImpl.java.
{
         return new IteratorImpl();
     }
mapped()
public<R> FastCollection<R> javolution.util.FastCollection< E >.mapped (Function<? super E, ? extends R > function) package inherited
Returns a view exposing elements through the specified mapping function. The returned view does not allow new elements to be added.
Definition at line 258 of file FastCollection.java.
{
         return new MappedCollectionImpl<E, R>(service(), function);
     }
Referenced by javolution.xml.internal.stream.EntitiesImpl.setEntitiesMapping().
max()
E javolution.util.FastCollection< E >.max () inherited
Returns the largest element of this collection using this collection comparator (convenience method). Returns
null
if this collection is empty.
Returns
reduce(Reducers.max(comparator()))
See also
Reducers::max
Definition at line 541 of file FastCollection.java.
                    {
         return reduce(Reducers.max(comparator()));
     }
References javolution.util.function.Reducers.max().
min()
E javolution.util.FastCollection< E >.min () inherited
Returns the smallest element of this collection using this collection comparator (convenience method). Returns
null
if this collection is empty.
Returns
reduce(Reducers.min(comparator()))
See also
Reducers::min
Definition at line 528 of file FastCollection.java.
                    {
         return reduce(Reducers.min(comparator()));
     }
References javolution.util.function.Reducers.min().
parallel()
FastCollection<E> javolution.util.FastCollection< E >.parallel () inherited
Returns a parallel collection. Parallel collections affect only closure-based operations, all others operations behaving the same. Parallel actions are performed concurrently using Javolution ConcurrentContext. The number of parallel views is derived from the context concurrency (
number of parallel views = concurrency + 1
). Parallel views do not require this collection to be thread-safe (internal synchronization).
See also
#perform(Consumer)
#update(Consumer)
#forEach(Consumer)
#removeIf(Predicate)
#reduce(Reducer)
Definition at line 222 of file FastCollection.java.
{
         return new ParallelCollectionImpl<E>(service());
     }
perform() [1/3]
void javolution.util.internal.collection.CollectionView< E >.perform (Consumer< CollectionService< E >> action, CollectionService< E > view) inherited
Reimplemented in javolution.util.internal.collection.ParallelCollectionImpl< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Definition at line 163 of file CollectionView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
perform() [2/3]
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
perform() [3/3]
void javolution.util.FastCollection< E >.perform (Consumer<? extends Collection< E >> action) inherited
Executes the specified read-only action on this collection. That logic may be performed concurrently on sub-collections if this collection is parallel.
Parameters
action the read-only action.
Exceptions
UnsupportedOperationException if the action tries to update this collection and this collection is thread-safe.
ClassCastException if the action type is not compatible with this collection (e.g. action on set and this is a list).
See also
#update(Consumer)
Definition at line 315 of file FastCollection.java.
{
         service().perform((Consumer<CollectionService<E>>) action, service());
     }
reduce()
E javolution.util.FastCollection< E >.reduce (Reducer< E > reducer) inherited
Performs a reduction of the elements of this collection using the specified reducer. This may not involve iterating over all the collection elements, for example the reducers: Reducers#any, Reducers#and and Reducers#or may stop iterating early. Reduction is performed concurrently if this collection is parallel.
Parameters
reducer the collection reducer.
Returns
the reduction result.
Definition at line 396 of file FastCollection.java.
{
         perform(reducer);
         return reducer.get();
     }
remove()
synchronized boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.remove (Object searched)
Removes the specified element from this collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 125 of file AtomicCollectionImpl.java.
{
         boolean changed = target().remove(o);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.collection.CollectionView< E >.target, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
Referenced by javolution.util.internal.collection.AtomicCollectionImpl< E >.IteratorImpl.remove().
removeAll()
synchronized boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.removeAll (Collection<?> that)
Removes all the specified element from this collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 132 of file AtomicCollectionImpl.java.
{
         boolean changed = target().removeAll(c);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.collection.CollectionView< E >.target, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
removeIf()
boolean javolution.util.FastCollection< E >.removeIf (final Predicate<? super E > filter) inherited
Removes from this collection all the elements matching the specified functional predicate (convenience method). Removals are performed concurrently if this collection is parallel and atomically if this collection is atomic.
Parameters
filter a predicate returning
true
for elements to be removed.
Returns
true
if at least one element has been removed;
false
otherwise.
Definition at line 368 of file FastCollection.java.
{
         final boolean[] removed = new boolean[1];
         update(new Consumer<Collection<E>>() {
             public void accept(Collection<E> view) {
                 Iterator<E> it = view.iterator();
                 while (it.hasNext()) {
                     if (filter.test(it.next())) {
                         it.remove(); // Ok mutable iteration.
                         removed[0] = true;
                     }
                 }
             }
         });
         return removed[0];
     }
retainAll()
synchronized boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.retainAll (Collection<?> that)
Removes all the elements except those in the specified collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 139 of file AtomicCollectionImpl.java.
{
         boolean changed = target().retainAll(c);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.collection.CollectionView< E >.target, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
reversed()
FastCollection<E> javolution.util.FastCollection< E >.reversed () inherited
Returns a view exposing elements in reverse iterative order.
Reimplemented in javolution.util.FastTable< E >.
Definition at line 282 of file FastCollection.java.
{
         return new ReversedCollectionImpl<E>(service());
     }
sequential()
FastCollection<E> javolution.util.FastCollection< E >.sequential () inherited
Returns a sequential view of this collection. Using this view, all closure-based iterations are performed sequentially.
Definition at line 230 of file FastCollection.java.
{
         return new SequentialCollectionImpl<E>(service());
     }
service()
CollectionService<E> javolution.util.internal.collection.CollectionView< E >.service () protected inherited
Returns the service implementation of this collection (for sub-classes).
Reimplemented from javolution.util.FastCollection< E >.
Definition at line 274 of file CollectionView.java.
{
         return this;
     }
serviceOf()
static <E> CollectionService<E> javolution.util.FastCollection< E >.serviceOf (FastCollection< E > collection) static protected inherited
Returns the service implementation of any fast collection (for sub-classes).
Definition at line 647 of file FastCollection.java.
{
         return collection.service();
     }
References javolution.util.FastCollection< E >.service().
shared()
FastCollection<E> javolution.util.FastCollection< E >.shared () inherited
Returns a thread-safe view over this collection. The shared view allows for concurrent read as long as there is no writer. The default implementation is based on readers-writers locks giving priority to writers. Iterators on shared collections are thread-safe (no ConcurrentModificationException possible).
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSet< E >, javolution.util.FastSortedTable< E >, and javolution.util.FastSortedSet< E >.
Definition at line 201 of file FastCollection.java.
{
         return new SharedCollectionImpl<E>(service());
     }
size()
int javolution.util.internal.collection.AtomicCollectionImpl< E >.size ()
Returns the size of this collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 146 of file AtomicCollectionImpl.java.
                       {
         return targetView().size();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
sorted() [1/2]
FastCollection<E> javolution.util.FastCollection< E >.sorted () inherited
Returns a view exposing elements sorted according to the collection order.
Definition at line 267 of file FastCollection.java.
{
         return new SortedCollectionImpl<E>(service(), comparator());
     }
Referenced by javolution.util.internal.collection.SortedCollectionImpl< E >.IteratorImpl.IteratorImpl().
sorted() [2/2]
FastCollection<E> javolution.util.FastCollection< E >.sorted (Comparator<? super E > cmp) inherited
Returns a view exposing elements sorted according to the specified comparator.
Definition at line 275 of file FastCollection.java.
{
         return new SortedCollectionImpl<E>(service(), cmp);
     }
split()
CollectionService<E> [] javolution.util.internal.collection.AtomicCollectionImpl< E >.split (int n)
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Reimplemented in javolution.util.internal.table.AtomicTableImpl< E >.
Definition at line 152 of file AtomicCollectionImpl.java.
                                                { // Split not supported.
         return new CollectionService[] { this };
     }
target()
CollectionService<E> javolution.util.internal.collection.CollectionView< E >.target () protected inherited
Returns the actual target
Reimplemented in javolution.util.internal.table.SharedTableImpl< E >, javolution.util.internal.table.TableView< E >, javolution.util.internal.table.AtomicTableImpl< E >, javolution.util.internal.set.sorted.SharedSortedSetImpl< E >, javolution.util.internal.table.sorted.SortedTableView< E >, javolution.util.internal.set.sorted.UnmodifiableSortedSetImpl< E >, javolution.util.internal.set.sorted.SortedSetView< E >, javolution.util.internal.table.sorted.SharedSortedTableImpl< E >, javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >, javolution.util.internal.set.SetView< E >, and javolution.util.internal.table.sorted.UnmodifiableSortedTableImpl< E >.
Definition at line 279 of file CollectionView.java.
{
         return target;
     }
targetView()
CollectionService<E> javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView () protected
Returns either the immutable target or the actual target if updating thread.
Reimplemented in javolution.util.internal.table.AtomicTableImpl< E >, javolution.util.internal.set.sorted.AtomicSortedSetImpl< E >, and javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >.
Definition at line 185 of file AtomicCollectionImpl.java.
{
         return ((updatingThread == null) || (updatingThread != Thread.currentThread()))
                 ? immutable : target();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.collection.CollectionView< E >.target, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updatingThread.
Referenced by javolution.util.internal.collection.AtomicCollectionImpl< E >.contains(), javolution.util.internal.collection.AtomicCollectionImpl< E >.containsAll(), javolution.util.internal.collection.AtomicCollectionImpl< E >.equals(), javolution.util.internal.collection.AtomicCollectionImpl< E >.hashCode(), javolution.util.internal.collection.AtomicCollectionImpl< E >.isEmpty(), javolution.util.internal.collection.AtomicCollectionImpl< E >.IteratorImpl.IteratorImpl(), javolution.util.internal.collection.AtomicCollectionImpl< E >.size(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.toArray().
threadSafe()
CollectionService<E> javolution.util.internal.collection.AtomicCollectionImpl< E >.threadSafe ()
Returns a thread-safe version of this service (used during parallel updates).
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Reimplemented in javolution.util.internal.table.AtomicTableImpl< E >, javolution.util.internal.set.sorted.AtomicSortedSetImpl< E >, javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >, and javolution.util.internal.set.AtomicSetImpl< E >.
Definition at line 157 of file AtomicCollectionImpl.java.
{
         return this;
     }
toArray() [1/2]
Object [] javolution.util.internal.collection.AtomicCollectionImpl< E >.toArray ()
Returns an array holding this collection elements.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 162 of file AtomicCollectionImpl.java.
{
         return targetView().toArray();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
toArray() [2/2]
public<T> T [] javolution.util.internal.collection.AtomicCollectionImpl< E >.toArray (T[] array) package
Returns the specified array holding this collection elements if enough capacity.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 167 of file AtomicCollectionImpl.java.
{
         return targetView().toArray(a);
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
toImmutable()
public<T extends Collection<E> > Immutable<T> javolution.util.FastCollection< E >.toImmutable () package inherited
Returns an immutable reference over this collection. The immutable value is an unmodifiable view of this collection. The caller must guarantees that the original collection is never going to be updated (e.g. there is no reference left of the original collection).
Definition at line 585 of file FastCollection.java.
{
         return new Immutable<T>() {
             @SuppressWarnings("unchecked")
             final T value = (T) unmodifiable();
             @Override
             public T value() {
                 return value;
             }
         };
     }
toString()
String javolution.util.FastCollection< E >.toString () inherited
Returns the string representation of this collection using its default format.
Definition at line 634 of file FastCollection.java.
{
         return TextContext.getFormat(FastCollection.class).format(this);
     }
References javolution.text.TextContext.getFormat().
unmodifiable()
FastCollection<E> javolution.util.FastCollection< E >.unmodifiable () inherited
Returns an unmodifiable view over this collection. Any attempt to modify the collection through this view will result into a java.lang.UnsupportedOperationException being raised.
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSet< E >, javolution.util.FastSortedTable< E >, and javolution.util.FastSortedSet< E >.
Definition at line 239 of file FastCollection.java.
{
         return new UnmodifiableCollectionImpl<E>(service());
     }
update() [1/3]
synchronized void javolution.util.internal.collection.AtomicCollectionImpl< E >.update (Consumer< CollectionService< E >> action, CollectionService< E > view)
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 172 of file AtomicCollectionImpl.java.
{
         updatingThread = Thread.currentThread(); // Update in progress.
         try {
             target().update(action, view); // No copy performed.
         } finally {
             updatingThread = null;
             immutable = cloneTarget(); // One single copy !
         }
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.collection.CollectionView< E >.target, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updatingThread.
update() [2/3]
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
update() [3/3]
void javolution.util.FastCollection< E >.update (Consumer<? extends Collection< E >> action) inherited
Executes the specified update action on this collection. That logic may be performed concurrently on sub-collections if this collection is parallel. For atomic collections the update is atomic (either concurrent readers see the full result of the action or nothing).
Parameters
action the update action.
Exceptions
ClassCastException if the action type is not compatible with this collection (e.g. action on set and this is a list).
See also
#perform(Consumer)
Definition at line 334 of file FastCollection.java.
{
         service().update((Consumer<CollectionService<E>>) action, service());
     }
Referenced by javolution.util.FastTable< javolution.xml.internal.stream.XMLStreamReaderImpl >.sort().
updateInProgress()
final boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress () protected
Indicates if the current thread is doing an atomic update.
Definition at line 200 of file AtomicCollectionImpl.java.
{
         return updatingThread == Thread.currentThread();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.updatingThread.
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.add(), javolution.util.internal.collection.AtomicCollectionImpl< E >.add(), javolution.util.internal.table.AtomicTableImpl< E >.addAll(), javolution.util.internal.collection.AtomicCollectionImpl< E >.addAll(), javolution.util.internal.table.AtomicTableImpl< E >.addFirst(), javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >.addIfAbsent(), javolution.util.internal.table.AtomicTableImpl< E >.addLast(), javolution.util.internal.collection.AtomicCollectionImpl< E >.clear(), javolution.util.internal.table.AtomicTableImpl< E >.offerFirst(), javolution.util.internal.table.AtomicTableImpl< E >.offerLast(), javolution.util.internal.table.AtomicTableImpl< E >.pollFirst(), javolution.util.internal.table.AtomicTableImpl< E >.pollLast(), javolution.util.internal.collection.AtomicCollectionImpl< E >.remove(), javolution.util.internal.table.AtomicTableImpl< E >.remove(), javolution.util.internal.collection.AtomicCollectionImpl< E >.removeAll(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirst(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirstOccurrence(), javolution.util.internal.table.AtomicTableImpl< E >.removeLast(), javolution.util.internal.table.AtomicTableImpl< E >.removeLastOccurrence(), javolution.util.internal.collection.AtomicCollectionImpl< E >.retainAll(), and javolution.util.internal.table.AtomicTableImpl< E >.set().
Member Data Documentation
immutable
volatile CollectionService<E> javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable protected
Definition at line 52 of file AtomicCollectionImpl.java.
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.add(), javolution.util.internal.collection.AtomicCollectionImpl< E >.add(), javolution.util.internal.table.AtomicTableImpl< E >.addAll(), javolution.util.internal.collection.AtomicCollectionImpl< E >.addAll(), javolution.util.internal.table.AtomicTableImpl< E >.addFirst(), javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >.addIfAbsent(), javolution.util.internal.table.AtomicTableImpl< E >.addLast(), javolution.util.internal.collection.AtomicCollectionImpl< E >.clear(), javolution.util.internal.collection.AtomicCollectionImpl< E >.comparator(), javolution.util.internal.table.AtomicTableImpl< E >.offerFirst(), javolution.util.internal.table.AtomicTableImpl< E >.offerLast(), javolution.util.internal.table.AtomicTableImpl< E >.pollFirst(), javolution.util.internal.table.AtomicTableImpl< E >.pollLast(), javolution.util.internal.collection.AtomicCollectionImpl< E >.remove(), javolution.util.internal.table.AtomicTableImpl< E >.remove(), javolution.util.internal.collection.AtomicCollectionImpl< E >.removeAll(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirst(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirstOccurrence(), javolution.util.internal.table.AtomicTableImpl< E >.removeLast(), javolution.util.internal.table.AtomicTableImpl< E >.removeLastOccurrence(), javolution.util.internal.collection.AtomicCollectionImpl< E >.retainAll(), javolution.util.internal.table.AtomicTableImpl< E >.set(), javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.update().
serialVersionUID
final long javolution.util.internal.collection.AtomicCollectionImpl< E >.serialVersionUID = 0x600L static private
Definition at line 51 of file AtomicCollectionImpl.java.
target
CollectionService<E> javolution.util.internal.collection.CollectionView< E >.target private inherited
Reimplemented in javolution.util.internal.table.SharedTableImpl< E >, javolution.util.internal.table.TableView< E >, javolution.util.internal.table.AtomicTableImpl< E >, javolution.util.internal.set.sorted.SharedSortedSetImpl< E >, javolution.util.internal.table.sorted.SortedTableView< E >, javolution.util.internal.set.sorted.UnmodifiableSortedSetImpl< E >, javolution.util.internal.set.sorted.SortedSetView< E >, javolution.util.internal.table.sorted.SharedSortedTableImpl< E >, javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >, javolution.util.internal.set.SetView< E >, and javolution.util.internal.table.sorted.UnmodifiableSortedTableImpl< E >.
Definition at line 33 of file CollectionView.java.
Referenced by javolution.util.internal.collection.SequentialCollectionImpl< E >.add(), javolution.util.internal.collection.ParallelCollectionImpl< E >.add(), javolution.util.internal.collection.ReversedCollectionImpl< E >.add(), javolution.util.internal.collection.AtomicCollectionImpl< E >.add(), javolution.util.internal.collection.DistinctCollectionImpl< E >.add(), javolution.util.internal.collection.SortedCollectionImpl< E >.add(), javolution.util.internal.collection.SharedCollectionImpl< E >.add(), javolution.util.internal.collection.FilteredCollectionImpl< E >.add(), javolution.util.internal.collection.AtomicCollectionImpl< E >.addAll(), javolution.util.internal.collection.SharedCollectionImpl< E >.addAll(), javolution.util.internal.collection.AtomicCollectionImpl< E >.AtomicCollectionImpl(), javolution.util.internal.set.AtomicSetImpl< E >.AtomicSetImpl(), javolution.util.internal.set.sorted.AtomicSortedSetImpl< E >.AtomicSortedSetImpl(), javolution.util.internal.collection.SequentialCollectionImpl< E >.clear(), javolution.util.internal.collection.ParallelCollectionImpl< E >.clear(), javolution.util.internal.collection.ReversedCollectionImpl< E >.clear(), javolution.util.internal.collection.DistinctCollectionImpl< E >.clear(), javolution.util.internal.collection.SortedCollectionImpl< E >.clear(), javolution.util.internal.collection.SharedCollectionImpl< E >.clear(), javolution.util.internal.collection.CollectionView< R >.clone(), javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.SharedCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.CollectionView< R >.CollectionView(), javolution.util.internal.collection.SequentialCollectionImpl< E >.comparator(), javolution.util.internal.collection.ParallelCollectionImpl< E >.comparator(), javolution.util.internal.collection.UnmodifiableCollectionImpl< E >.comparator(), javolution.util.internal.collection.ReversedCollectionImpl< E >.comparator(), javolution.util.internal.collection.DistinctCollectionImpl< E >.comparator(), javolution.util.internal.collection.FilteredCollectionImpl< E >.comparator(), javolution.util.internal.collection.SharedCollectionImpl< E >.comparator(), javolution.util.internal.collection.SequentialCollectionImpl< E >.contains(), javolution.util.internal.collection.ParallelCollectionImpl< E >.contains(), javolution.util.internal.collection.UnmodifiableCollectionImpl< E >.contains(), javolution.util.internal.collection.ReversedCollectionImpl< E >.contains(), javolution.util.internal.collection.DistinctCollectionImpl< E >.contains(), javolution.util.internal.collection.FilteredCollectionImpl< E >.contains(), javolution.util.internal.collection.SortedCollectionImpl< E >.contains(), javolution.util.internal.collection.SharedCollectionImpl< E >.contains(), javolution.util.internal.collection.SharedCollectionImpl< E >.containsAll(), javolution.util.internal.collection.DistinctCollectionImpl< E >.DistinctCollectionImpl(), javolution.util.internal.collection.SharedCollectionImpl< E >.equals(), javolution.util.internal.collection.FilteredCollectionImpl< E >.FilteredCollectionImpl(), javolution.util.internal.set.FilteredSetImpl< E >.FilteredSetImpl(), javolution.util.internal.collection.SharedCollectionImpl< E >.hashCode(), javolution.util.internal.collection.SequentialCollectionImpl< E >.isEmpty(), javolution.util.internal.collection.ParallelCollectionImpl< E >.isEmpty(), javolution.util.internal.collection.UnmodifiableCollectionImpl< E >.isEmpty(), javolution.util.internal.collection.ReversedCollectionImpl< E >.isEmpty(), javolution.util.internal.collection.DistinctCollectionImpl< E >.isEmpty(), javolution.util.internal.collection.SortedCollectionImpl< E >.isEmpty(), javolution.util.internal.collection.SharedCollectionImpl< E >.isEmpty(), javolution.util.internal.collection.SequentialCollectionImpl< E >.iterator(), javolution.util.internal.collection.ParallelCollectionImpl< E >.iterator(), javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.IteratorImpl(), javolution.util.internal.collection.SortedCollectionImpl< E >.IteratorImpl.IteratorImpl(), javolution.util.internal.collection.FilteredCollectionImpl< E >.IteratorImpl.IteratorImpl(), javolution.util.internal.collection.ParallelCollectionImpl< E >.ParallelCollectionImpl(), javolution.util.internal.collection.ParallelCollectionImpl< E >.perform(), javolution.util.internal.collection.CollectionView< R >.perform(), javolution.util.internal.collection.SharedCollectionImpl< E >.perform(), javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.remove(), javolution.util.internal.collection.SortedCollectionImpl< E >.IteratorImpl.remove(), javolution.util.internal.collection.SequentialCollectionImpl< E >.remove(), javolution.util.internal.collection.ParallelCollectionImpl< E >.remove(), javolution.util.internal.collection.ReversedCollectionImpl< E >.remove(), javolution.util.internal.collection.FilteredCollectionImpl< E >.remove(), javolution.util.internal.collection.SortedCollectionImpl< E >.remove(), javolution.util.internal.collection.AtomicCollectionImpl< E >.remove(), javolution.util.internal.collection.SharedCollectionImpl< E >.remove(), javolution.util.internal.collection.AtomicCollectionImpl< E >.removeAll(), javolution.util.internal.collection.SharedCollectionImpl< E >.removeAll(), javolution.util.internal.collection.AtomicCollectionImpl< E >.retainAll(), javolution.util.internal.collection.SharedCollectionImpl< E >.retainAll(), javolution.util.internal.collection.ReversedCollectionImpl< E >.ReversedCollectionImpl(), javolution.util.internal.collection.SequentialCollectionImpl< E >.SequentialCollectionImpl(), javolution.util.internal.collection.SharedCollectionImpl< E >.SharedCollectionImpl(), javolution.util.internal.set.SharedSetImpl< E >.SharedSetImpl(), javolution.util.internal.collection.SequentialCollectionImpl< E >.size(), javolution.util.internal.collection.UnmodifiableCollectionImpl< E >.size(), javolution.util.internal.collection.ParallelCollectionImpl< E >.size(), javolution.util.internal.collection.ReversedCollectionImpl< E >.size(), javolution.util.internal.collection.SortedCollectionImpl< E >.size(), javolution.util.internal.collection.SharedCollectionImpl< E >.size(), javolution.util.internal.collection.SortedCollectionImpl< E >.SortedCollectionImpl(), javolution.util.internal.collection.CollectionView< R >.split(), javolution.util.internal.collection.SharedCollectionImpl< E >.split(), javolution.util.internal.collection.CollectionView< R >.target(), javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView(), javolution.util.internal.collection.SharedCollectionImpl< E >.toArray(), javolution.util.internal.collection.UnmodifiableCollectionImpl< E >.UnmodifiableCollectionImpl(), javolution.util.internal.set.UnmodifiableSetImpl< E >.UnmodifiableSetImpl(), javolution.util.internal.collection.ParallelCollectionImpl< E >.update(), javolution.util.internal.collection.AtomicCollectionImpl< E >.update(), and javolution.util.internal.collection.CollectionView< R >.update().
updatingThread
transient Thread javolution.util.internal.collection.AtomicCollectionImpl< E >.updatingThread protected
Definition at line 53 of file AtomicCollectionImpl.java.
Referenced by javolution.util.internal.collection.AtomicCollectionImpl< E >.clone(), javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView(), javolution.util.internal.collection.AtomicCollectionImpl< E >.update(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
The documentation for this class was generated from the following file:
AtomicCollectionImpl.java