Javolution 6.0.0 java: javolution.xml.internal.stream.EntitiesImpl Class Reference
javolution.xml.internal.stream.EntitiesImpl Class Reference
Public Member Functions
int getMaxLength ()
int replaceEntity (char[] buffer, int start, int length) throws XMLStreamException
void setEntitiesMapping (Map< String, String > entityToReplacementText)
Map< String, String > getEntitiesMapping ()
void reset ()
Package Functions
EntitiesImpl ()
Private Attributes
int _maxLength = 1
Map< String, String > _entitiesMapping
CharArray _tmp = new CharArray()
Detailed Description
Defines entities while parsing.
Author
Jean-Marie Dautelle
Version
4.0, June 16, 2006
Definition at line 24 of file EntitiesImpl.java.
Constructor & Destructor Documentation
EntitiesImpl()
javolution.xml.internal.stream.EntitiesImpl.EntitiesImpl () package
Default constructor.
Definition at line 39 of file EntitiesImpl.java.
 {}
Member Function Documentation
getEntitiesMapping()
Map<String, String> javolution.xml.internal.stream.EntitiesImpl.getEntitiesMapping ()
Returns the custom entity mapping or
null
if none.
Definition at line 145 of file EntitiesImpl.java.
{
         return _entitiesMapping;
     }
References javolution.xml.internal.stream.EntitiesImpl._entitiesMapping.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getProperty().
getMaxLength()
int javolution.xml.internal.stream.EntitiesImpl.getMaxLength ()
Returns the length of the largest entity defined (default
1
).
Definition at line 44 of file EntitiesImpl.java.
{
         return _maxLength;
     }
References javolution.xml.internal.stream.EntitiesImpl._maxLength.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity().
replaceEntity()
int javolution.xml.internal.stream.EntitiesImpl.replaceEntity (char[] buffer, int start, int length) throws XMLStreamException
Replaces the entity at the specified position. The five predefined XML entities "&#38;lt;", "&#38;gt;", "&#38;apos;", "&#38;quot;", "&#38;amp;" as well as character refererences (decimal or hexadecimal) are always recognized.
Parameters
buffer the data buffer.
start the index of entity first character (index of '&')
Returns
the length of the replacement entity (including ';')
Exceptions
XMLStreamException if the entity is not recognized.
Definition at line 59 of file EntitiesImpl.java.
{
         // Checks for character references.
         if (buffer[start + 1] == '#') {
             char c = buffer[start + 2];
             int base = (c == 'x') ? 16 : 10;
             int i = (c == 'x') ? 3 : 2;
             int charValue = 0;
             for (; i < length - 1; i++) {
                 c = buffer[start + i];
                 charValue *= base;
                 charValue += (c <= '9') ? (c - '0') : (c <= 'Z') ? c - 'A'
                         : c - 'a';
             }
             buffer[start] = (char) charValue;
             return 1;
         }
         if ((buffer[start + 1] == 'l') && (buffer[start + 2] == 't')
                 && (buffer[start + 3] == ';')) {
             buffer[start] = '<';
             return 1;
         }
         if ((buffer[start + 1] == 'g') && (buffer[start + 2] == 't')
                 && (buffer[start + 3] == ';')) {
             buffer[start] = '>';
             return 1;
         }
         if ((buffer[start + 1] == 'a') && (buffer[start + 2] == 'p')
                 && (buffer[start + 3] == 'o') && (buffer[start + 4] == 's')
                 && (buffer[start + 5] == ';')) {
             buffer[start] = '\'';
             return 1;
         }
         if ((buffer[start + 1] == 'q') && (buffer[start + 2] == 'u')
                 && (buffer[start + 3] == 'o') && (buffer[start + 4] == 't')
                 && (buffer[start + 5] == ';')) {
             buffer[start] = '"';
             return 1;
         }
         if ((buffer[start + 1] == 'a') && (buffer[start + 2] == 'm')
                 && (buffer[start + 3] == 'p') && (buffer[start + 4] == ';')) {
             buffer[start] = '&';
             return 1;
         }
         // Searches user defined entities.
         _tmp.setArray(buffer, start + 1, length - 2);
         CharSequence replacementText = (_entitiesMapping != null) ?  _entitiesMapping
                 .get(_tmp) : null;
         if (replacementText == null)
             throw new XMLStreamException("Entity " + _tmp + " not recognized");
         int replacementTextLength = replacementText.length();
         for (int i = 0; i < replacementTextLength; i++) {
             buffer[start + i] = replacementText.charAt(i);
         }
         return replacementTextLength;
     }
References javolution.xml.internal.stream.EntitiesImpl._entitiesMapping, javolution.xml.internal.stream.EntitiesImpl._tmp, and javolution.text.CharArray.setArray().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity().
reset()
void javolution.xml.internal.stream.EntitiesImpl.reset ()
Definition at line 150 of file EntitiesImpl.java.
{
         _maxLength = 1;
         _entitiesMapping = null;
     }
References javolution.xml.internal.stream.EntitiesImpl._entitiesMapping, and javolution.xml.internal.stream.EntitiesImpl._maxLength.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
setEntitiesMapping()
void javolution.xml.internal.stream.EntitiesImpl.setEntitiesMapping (Map< String, String > entityToReplacementText)
Sets the current custom entity mapping. For example:
new FastMap().put("copy", "©")
to define the copyright entity.
Definition at line 129 of file EntitiesImpl.java.
{
         FastTable<String> values = new FastTable<String>();
         values.addAll(entityToReplacementText.values());
         _maxLength = values.mapped(new Function<CharSequence, Integer>() {
             @Override
             public Integer apply(CharSequence csq) {
                 return csq.length();
             }}).max();
           _entitiesMapping = entityToReplacementText;
     }
References javolution.xml.internal.stream.EntitiesImpl._entitiesMapping, javolution.xml.internal.stream.EntitiesImpl._maxLength, javolution.util.FastTable< E >.addAll(), and javolution.util.FastCollection< E >.mapped().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.setEntities().
Member Data Documentation
_entitiesMapping
Map<String, String> javolution.xml.internal.stream.EntitiesImpl._entitiesMapping private
Holds the user defined entities mapping.
Definition at line 34 of file EntitiesImpl.java.
Referenced by javolution.xml.internal.stream.EntitiesImpl.getEntitiesMapping(), javolution.xml.internal.stream.EntitiesImpl.replaceEntity(), javolution.xml.internal.stream.EntitiesImpl.reset(), and javolution.xml.internal.stream.EntitiesImpl.setEntitiesMapping().
_maxLength
int javolution.xml.internal.stream.EntitiesImpl._maxLength = 1 private
Holds maximum length.
Definition at line 29 of file EntitiesImpl.java.
Referenced by javolution.xml.internal.stream.EntitiesImpl.getMaxLength(), javolution.xml.internal.stream.EntitiesImpl.reset(), and javolution.xml.internal.stream.EntitiesImpl.setEntitiesMapping().
_tmp
CharArray javolution.xml.internal.stream.EntitiesImpl._tmp = new CharArray() private
Definition at line 123 of file EntitiesImpl.java.
Referenced by javolution.xml.internal.stream.EntitiesImpl.replaceEntity().
The documentation for this class was generated from the following file:
EntitiesImpl.java