Javolution 6.0.0 java: javolution.context.internal.LogContextImpl Class Reference
javolution.context.internal.LogContextImpl Class Reference
Public Member Functions
void prefix (Object... pfx)
void setLevel (Level level)
void suffix (Object... sfx)
abstract void setLevel (Level level)
void exit ()
Static Public Member Functions
static void debug (Object... message)
static LogContext enter ()
static< T extends AbstractContext > T enter (Class< T > custom)
static void error (Object... message)
static void info (Object... message)
static void warning (Object... message)
static AbstractContext current ()
static void inherit (AbstractContext ctx)
Static Public Attributes
static final Configurable< Level > LEVEL
Protected Member Functions
LogContext inner ()
void log (Level level, Object... message)
abstract void log (Level level, Object... message)
AbstractContext enterInner ()
AbstractContext getOuter ()
Static Protected Member Functions
static< T extends AbstractContext > T current (Class< T > type)
Private Member Functions
Level currentLevel ()
Static Private Member Functions
static LogContext currentLogContext ()
Private Attributes
Level level
Object[] prefix = NONE
Object[] suffix = NONE
AbstractContext outer
Static Private Attributes
static final Object[] NONE = new Object[0]
static final int[] TO_OSGI_LEVEL
static final ThreadLocal< AbstractContext > CURRENT = new ThreadLocal<AbstractContext>()
Detailed Description
The default implementation of LogContext.
Definition at line 20 of file LogContextImpl.java.
Member Function Documentation
current() [1/2]
static AbstractContext javolution.context.AbstractContext.current () static inherited
Returns the current context for the current thread or
null
if this thread has no context (default).
Definition at line 61 of file AbstractContext.java.
{
         return AbstractContext.CURRENT.get();
     }
References javolution.context.AbstractContext.CURRENT.
Referenced by javolution.context.LogContext.currentLogContext(), javolution.context.SecurityContext.currentSecurityContext(), javolution.text.TextContext.currentTextContext(), javolution.xml.XMLContext.currentXMLContext(), javolution.context.LocalContext.enter(), javolution.context.ConcurrentContext.enter(), and javolution.context.LocalContext.Parameter< T >.get().
current() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.current (Class< T > type) static protected inherited
Returns the current context of specified type or
null
if none.
Definition at line 69 of file AbstractContext.java.
{
         AbstractContext ctx = AbstractContext.CURRENT.get();
         while (ctx != null) {
             if (type.isInstance(ctx))
                 return (T) ctx;
             ctx = ctx.outer;
         }
         return null;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
currentLevel()
Level javolution.context.internal.LogContextImpl.currentLevel () private
Definition at line 86 of file LogContextImpl.java.
{
         if (LEVEL == null) return Level.DEBUG; // Only during class initialization.
         if (level == null) return LEVEL.get();
         return level;
     }
References javolution.context.LogContext.Level.DEBUG, javolution.context.internal.LogContextImpl.level, and javolution.context.LogContext.LEVEL.
Referenced by javolution.context.internal.LogContextImpl.log().
currentLogContext()
static LogContext javolution.context.LogContext.currentLogContext () static private inherited
Definition at line 120 of file LogContext.java.
{
         LogContext ctx = current(LogContext.class);
         if (ctx != null)
             return ctx;
         return OSGiServices.getLogContext();
     }
References javolution.context.AbstractContext.current(), and javolution.osgi.internal.OSGiServices.getLogContext().
Referenced by javolution.context.LogContext.debug(), javolution.context.LogContext.enter(), javolution.context.LogContext.error(), javolution.context.LogContext.info(), and javolution.context.LogContext.warning().
debug()
static void javolution.context.LogContext.debug (Object... message) static inherited
Logs the specified debug message.
Definition at line 87 of file LogContext.java.
{
         currentLogContext().log(Level.DEBUG, message);
     }
References javolution.context.LogContext.currentLogContext(), javolution.context.LogContext.Level.DEBUG, and javolution.context.LogContext.log().
Referenced by javolution.lang.Configurable< javolution.context.LogContext.Level >.Configurable(), javolution.osgi.internal.ConfigurableListenerImpl.configurableInitialized(), javolution.osgi.internal.ConfigurableListenerImpl.configurableReconfigured(), javolution.lang.Initializer.initializeLoadedClasses(), javolution.lang.Initializer.loadClass(), and javolution.test.Perfometer< T >.printDetails().
enter() [1/2]
static LogContext javolution.context.LogContext.enter () static inherited
Enters and returns a new log context instance.
Definition at line 94 of file LogContext.java.
{
         return (LogContext) currentLogContext().enterInner();
     }
References javolution.context.LogContext.currentLogContext(), and javolution.context.AbstractContext.enterInner().
enter() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.enter (Class< T > custom) static inherited
Enters the scope of a custom context. This method raises a SecurityException if the permission to enter contexts of the specified class is not granted. For example, the following disallow entering any custom context. [code] SecurityContext ctx = SecurityContext.enter(); try { ctx.revoke(new SecurityContext.Permission(AbstractContext.class, "enter")); ... // Cannot enter any custom context. } finally { ctx.exit(); // Back to previous security settings. }[/code]
Parameters
custom the custom context to enter.
Exceptions
IllegalArgumentException if the specified class default constructor cannot be instantiated.
SecurityException if
SecurityContext.Permission(custom, "enter")
is not granted.
See also
SecurityContext.Permission
Definition at line 101 of file AbstractContext.java.
{
         SecurityContext.check(new Permission<T>(custom, "enter"));
         try {
             return (T) custom.newInstance().enterInner();
         } catch (InstantiationException e) {
             throw new IllegalArgumentException(
                     "Cannot instantiate instance of " + custom, e);
         } catch (IllegalAccessException e) {
             throw new IllegalArgumentException("Cannot access " + custom, e);
         }
     }
References javolution.context.SecurityContext.check().
enterInner()
AbstractContext javolution.context.AbstractContext.enterInner () protected inherited
Enters the scope of an inner context which becomes the current context; the previous current context becomes the outer of this context.
Returns
the inner context entered.
Definition at line 141 of file AbstractContext.java.
{
         AbstractContext inner = inner();
         inner.outer = AbstractContext.CURRENT.get();
         AbstractContext.CURRENT.set(inner);
         return inner;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
Referenced by javolution.xml.XMLContext.enter(), javolution.text.TextContext.enter(), javolution.context.LogContext.enter(), javolution.context.LocalContext.enter(), javolution.context.SecurityContext.enter(), and javolution.context.ConcurrentContext.enter().
error()
static void javolution.context.LogContext.error (Object... message) static inherited
Logs the specified error message (which may include any Throwable instance).
Definition at line 102 of file LogContext.java.
{
         currentLogContext().log(Level.ERROR, message);
     }
References javolution.context.LogContext.currentLogContext(), javolution.context.LogContext.Level.ERROR, and javolution.context.LogContext.log().
Referenced by javolution.lang.Initializer.initializeLoadedClasses().
exit()
void javolution.context.AbstractContext.exit () inherited
Exits the scope of this context; the outer of this context becomes
the current context.
Exceptions
IllegalStateException if this context is not the current context.
Reimplemented in javolution.context.ConcurrentContext, and javolution.context.internal.ConcurrentContextImpl.
Definition at line 155 of file AbstractContext.java.
{
         if (this != AbstractContext.CURRENT.get())
             throw new IllegalStateException(
                     "This context is not the current context");
         AbstractContext.CURRENT.set(outer);
         outer = null;
     }
References javolution.context.AbstractContext.CURRENT.
getOuter()
AbstractContext javolution.context.AbstractContext.getOuter () protected inherited
Returns the outer context of this context or
null
if this context has no outer context.
Definition at line 167 of file AbstractContext.java.
{
         return outer;
     }
info()
static void javolution.context.LogContext.info (Object... message) static inherited
Logs the specified info message.
Definition at line 109 of file LogContext.java.
{
         currentLogContext().log(Level.INFO, message);
     }
References javolution.context.LogContext.currentLogContext(), javolution.context.LogContext.Level.INFO, and javolution.context.LogContext.log().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.increaseDataBuffer(), javolution.xml.internal.stream.XMLStreamReaderImpl.increaseStack(), and javolution.test.Perfometer< T >.print().
inherit()
static void javolution.context.AbstractContext.inherit (AbstractContext ctx) static inherited
Inherits the specified context which becomes the context of the current thread. This method is particularly useful when creating new threads to make them inherits from the context stack of the parent thread. [code] //Spawns a new thread inheriting the context of the current thread. MyThread myThread = new MyThread(); myThread.inherited = AbstractContext.current(); myThread.start(); ... class MyThread extends Thread { AbstractContext inherited; public void run() { AbstractContext.inherit(inherited); // Sets current context. ... } }[/code]
Definition at line 131 of file AbstractContext.java.
{
         CURRENT.set(ctx);
     }
Referenced by javolution.context.internal.ConcurrentThreadImpl.run().
inner()
LogContext javolution.context.internal.LogContextImpl.inner () protected
Returns a new inner instance of this context inheriting the properties of this context. The new instance can be configured independently from its parent.
Reimplemented from javolution.context.AbstractContext.
Definition at line 52 of file LogContextImpl.java.
{
         LogContextImpl ctx = new LogContextImpl();
         ctx.prefix = prefix;
         ctx.suffix = suffix;
         ctx.level = level;
         return ctx;
     }
References javolution.context.internal.LogContextImpl.level, javolution.context.internal.LogContextImpl.prefix, and javolution.context.internal.LogContextImpl.suffix.
log() [1/2]
void javolution.context.internal.LogContextImpl.log (Level level, Object... message) protected
Definition at line 61 of file LogContextImpl.java.
{
         if (level.compareTo(currentLevel()) < 0)
             return;
         TextBuilder tmp = new TextBuilder();
         Throwable exception = null;
         for (Object pfx : prefix) {
             tmp.append(pfx); // Uses TextContext for formatting.
         }
         for (Object obj : message) {
             if ((exception == null) && (obj instanceof Throwable)) {
                 exception = (Throwable) obj;
             } else {
                 tmp.append(obj); // Uses TextContext for formatting.
             }
         }
         for (Object sfx : suffix) {
             tmp.append(sfx); // Uses TextContext for formatting.
         }
         int osgiLevel = TO_OSGI_LEVEL[level.ordinal()];
         String msg = tmp.toString();
         Object[] logServices = OSGiServices.getLogServices();
         for (Object logService : logServices) {
             ((LogService)logService).log(osgiLevel, msg, exception);
         }
     }
References javolution.text.TextBuilder.append(), javolution.context.internal.LogContextImpl.currentLevel(), javolution.osgi.internal.OSGiServices.getLogServices(), javolution.context.internal.LogContextImpl.level, javolution.context.internal.LogContextImpl.prefix, javolution.context.internal.LogContextImpl.suffix, javolution.context.internal.LogContextImpl.TO_OSGI_LEVEL, and javolution.text.TextBuilder.toString().
log() [2/2]
abstract void javolution.context.LogContext.log (Level level, Object... message) abstract protected inherited
Logs the specified message at the specified level.
Referenced by javolution.context.LogContext.debug(), javolution.context.LogContext.error(), javolution.context.LogContext.info(), and javolution.context.LogContext.warning().
prefix()
void javolution.context.internal.LogContextImpl.prefix (Object... prefixes)
Prefixes all messages being logged by the specified prefixes (prefixing existing prefixes if any).
Reimplemented from javolution.context.LogContext.
Definition at line 31 of file LogContextImpl.java.
{
         Object[] tmp = new Object[prefix.length + pfx.length];
         System.arraycopy(pfx, 0, tmp, 0, pfx.length);
         System.arraycopy(prefix, 0, tmp, pfx.length, prefix.length);
         prefix = tmp;
     }
References javolution.context.internal.LogContextImpl.prefix.
setLevel() [1/2]
void javolution.context.internal.LogContextImpl.setLevel (Level level)
Definition at line 39 of file LogContextImpl.java.
{
         this.level = level;
     }
References javolution.context.internal.LogContextImpl.level.
setLevel() [2/2]
abstract void javolution.context.LogContext.setLevel (Level level) abstract inherited
Set the logging level, messages below that level are not logged.
suffix()
void javolution.context.internal.LogContextImpl.suffix (Object... suffixes)
Suffixes all messages being logged by the specified suffixes (suffixing existing suffixes if any).
Reimplemented from javolution.context.LogContext.
Definition at line 44 of file LogContextImpl.java.
{
         Object[] tmp = new Object[suffix.length + sfx.length];
         System.arraycopy(suffix, 0, tmp, 0, suffix.length);
         System.arraycopy(sfx, 0, tmp, suffix.length, sfx.length);
         suffix = tmp;
     }
References javolution.context.internal.LogContextImpl.suffix.
warning()
static void javolution.context.LogContext.warning (Object... message) static inherited
Logs the specified warning message.
Definition at line 116 of file LogContext.java.
{
         currentLogContext().log(Level.WARNING, message);
     }
References javolution.context.LogContext.currentLogContext(), javolution.context.LogContext.log(), and javolution.context.LogContext.Level.WARNING.
Referenced by javolution.text.internal.TextContextImpl.searchFormat().
Member Data Documentation
CURRENT
final ThreadLocal<AbstractContext> javolution.context.AbstractContext.CURRENT = new ThreadLocal<AbstractContext>() static private inherited
Holds the last context entered (thread-local).
Definition at line 45 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), javolution.context.AbstractContext.enterInner(), and javolution.context.AbstractContext.exit().
level
Level javolution.context.internal.LogContextImpl.level private
Definition at line 26 of file LogContextImpl.java.
Referenced by javolution.context.internal.LogContextImpl.currentLevel(), javolution.context.internal.LogContextImpl.inner(), javolution.context.internal.LogContextImpl.log(), and javolution.context.internal.LogContextImpl.setLevel().
LEVEL
final Configurable<Level> javolution.context.LogContext.LEVEL static inherited
Initial value:
= new Configurable<Level>() {
        @Override
        protected Level getDefault() {
            return Level.DEBUG;
        }
        @Override
        public Level parse(String str) {
            return Level.valueOf(str);
        }
    }
Holds the default logging level (DEBUG). This level is configurable. For example, running with the option -Djavolution.context.LogContextLEVEL=WARNING
causes the debug/info not to be logged.
Definition at line 73 of file LogContext.java.
Referenced by javolution.context.internal.LogContextImpl.currentLevel().
NONE
final Object [] javolution.context.internal.LogContextImpl.NONE = new Object[0] static private
Definition at line 22 of file LogContextImpl.java.
outer
AbstractContext javolution.context.AbstractContext.outer private inherited
Holds the outer context or
null
if none (top context).
Definition at line 50 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), and javolution.context.AbstractContext.enterInner().
prefix
Object [] javolution.context.internal.LogContextImpl.prefix = NONE private
Definition at line 27 of file LogContextImpl.java.
Referenced by javolution.context.internal.LogContextImpl.inner(), javolution.context.internal.LogContextImpl.log(), and javolution.context.internal.LogContextImpl.prefix().
suffix
Object [] javolution.context.internal.LogContextImpl.suffix = NONE private
Definition at line 28 of file LogContextImpl.java.
Referenced by javolution.context.internal.LogContextImpl.inner(), javolution.context.internal.LogContextImpl.log(), and javolution.context.internal.LogContextImpl.suffix().
TO_OSGI_LEVEL
final int [] javolution.context.internal.LogContextImpl.TO_OSGI_LEVEL static private
Initial value:
= { LogService.LOG_DEBUG,
            LogService.LOG_INFO, LogService.LOG_WARNING, LogService.LOG_ERROR }
Definition at line 23 of file LogContextImpl.java.
Referenced by javolution.context.internal.LogContextImpl.log().
The documentation for this class was generated from the following file:
LogContextImpl.java