Javolution 6.0.0 java: javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V > Class Template Reference
javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V > Class Template Reference
Public Member Functions
SharedSortedMapImpl (SortedMapService< K, V > target)
Comparator<? super K > comparator ()
SortedSetService< Map.Entry< K, V > > entrySet ()
K firstKey ()
SortedMapService< K, V > headMap (K toKey)
SortedSetService< K > keySet ()
K lastKey ()
SortedMapService< K, V > subMap (K fromKey, K toKey)
SortedMapService< K, V > tailMap (K fromKey)
SortedMapService< K, V > threadSafe ()
void clear ()
boolean containsKey (Object key)
boolean containsValue (Object value)
V get (Object key)
boolean isEmpty ()
Iterator< Entry< K, V > > iterator ()
Equality<? super K > keyComparator ()
V put (K key, V value)
void putAll (Map<? extends K, ? extends V > m)
V putIfAbsent (K key, V value)
V remove (Object key)
boolean remove (Object key, Object value)
V replace (K key, V value)
boolean replace (K key, V oldValue, V newValue)
int size ()
MapService< K, V >[] split (int n)
Equality<? super V > valueComparator ()
MapView< K, V > clone ()
void perform (Consumer< MapService< K, V >> action, MapService< K, V > view)
void perform (Consumer< T > action, T part)
void update (Consumer< MapService< K, V >> action, MapService< K, V > view)
void update (Consumer< T > action, T part)
CollectionService< V > values ()
Protected Member Functions
SortedMapService< K, V > target ()
MapService< K, V > cloneTarget ()
Protected Attributes
ReadWriteLockImpl lock
transient Thread updatingThread
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
A shared view over a sorted map.
Definition at line 21 of file SharedSortedMapImpl.java.
Constructor & Destructor Documentation
SharedSortedMapImpl()
javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.SharedSortedMapImpl (SortedMapService< K, V > target)
Definition at line 25 of file SharedSortedMapImpl.java.
{
         super(target);
     }
References javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.target().
Member Function Documentation
clear()
void javolution.util.internal.map.SharedMapImpl< K, V >.clear () inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 70 of file SharedMapImpl.java.
{
         lock.writeLock.lock();
         try {
             target().clear();
         } finally {
             lock.writeLock.unlock();
         }
     }
References javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.lock(), javolution.util.internal.map.MapView< K, V >.target, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.unlock(), and javolution.util.internal.collection.ReadWriteLockImpl.writeLock.
clone()
MapView<K, V> javolution.util.internal.map.MapView< K, V >.clone () inherited
Returns a copy of this map; updates of the copy should not impact the original.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.AtomicMapImpl< K, V >, and javolution.util.internal.map.FastMapImpl< K, V >.
Definition at line 232 of file MapView.java.
{
         try {
             MapView<K, V> copy = (MapView<K, V>) super.clone();
             if (target != null) { // Not a root class.
                 copy.target = target.clone();
             }
             return copy;
         } catch (CloneNotSupportedException e) {
             throw new Error("Should not happen since target is cloneable");
         }
     }
References javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.split().
cloneTarget()
MapService<K, V> javolution.util.internal.map.SharedMapImpl< K, V >.cloneTarget () protected inherited
Returns a clone copy of target.
Definition at line 237 of file SharedMapImpl.java.
{
         try {
             return target().clone();
         } catch (CloneNotSupportedException e) {
             throw new Error("Cannot happen since target is Cloneable.");
         }
     }
References javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.IteratorImpl().
comparator()
Comparator<? super K> javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.comparator ()
Definition at line 31 of file SharedSortedMapImpl.java.
{
         return target().keyComparator();
     }
References javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.target().
containsKey()
boolean javolution.util.internal.map.SharedMapImpl< K, V >.containsKey (Object key) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 80 of file SharedMapImpl.java.
{
         lock.readLock.lock();
         try {
             return target().containsKey(key);
         } finally {
             lock.readLock.unlock();
         }
     }
References javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lock(), javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.readLock, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.unlock().
containsValue()
boolean javolution.util.internal.map.SharedMapImpl< K, V >.containsValue (Object value) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 90 of file SharedMapImpl.java.
{
         lock.readLock.lock();
         try {
             return target().containsValue(value);
         } finally {
             lock.readLock.unlock();
         }
     }
References javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lock(), javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.readLock, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.unlock().
entrySet()
SortedSetService<Map.Entry<K, V> > javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.entrySet ()
Returns a set view over the entries of this map. The set support adding/removing entries. Two entries are considered equals if they have the same key regardless of their values.
Implements javolution.util.service.SortedMapService< K, V >.
Definition at line 36 of file SharedSortedMapImpl.java.
{
         return new SubSortedMapImpl<K,V>(this, null, null).entrySet();
     }
References javolution.util.internal.map.sorted.SortedMapView< K, V >.entrySet().
firstKey()
K javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.firstKey ()
Definition at line 42 of file SharedSortedMapImpl.java.
{
         lock.readLock.lock();
         try {
             return target().firstKey();
         } finally {
             lock.readLock.unlock();
         }
     }
References javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lock(), javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.readLock, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.target(), and javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.unlock().
get()
V javolution.util.internal.map.SharedMapImpl< K, V >.get (Object key) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 100 of file SharedMapImpl.java.
{
         lock.readLock.lock();
         try {
             return target().get(key);
         } finally {
             lock.readLock.unlock();
         }
     }
References javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lock(), javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.readLock, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.unlock().
headMap()
SortedMapService<K, V> javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.headMap (K toKey)
Implements javolution.util.service.SortedMapService< K, V >.
Definition at line 53 of file SharedSortedMapImpl.java.
{
         return new SubSortedMapImpl<K,V>(this, null, toKey);
     }
isEmpty()
boolean javolution.util.internal.map.SharedMapImpl< K, V >.isEmpty () inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 110 of file SharedMapImpl.java.
{
         lock.readLock.lock();
         try {
             return target().isEmpty();
         } finally {
             lock.readLock.unlock();
         }
     }
References javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lock(), javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.readLock, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.unlock().
iterator()
Iterator<Entry<K, V> > javolution.util.internal.map.SharedMapImpl< K, V >.iterator () inherited
Returns an iterator over this map entries.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 120 of file SharedMapImpl.java.
{
         return new IteratorImpl();
     }
keyComparator()
Equality<? super K> javolution.util.internal.map.SharedMapImpl< K, V >.keyComparator () inherited
Returns the key comparator used for key equality or order if the map is sorted.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 125 of file SharedMapImpl.java.
{
         return target().keyComparator();
     }
References javolution.util.internal.map.MapView< K, V >.target.
keySet()
SortedSetService<K> javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.keySet ()
Returns a set view over the key of this map, the set support adding new key for which the value is automatically
null
.
Implements javolution.util.service.SortedMapService< K, V >.
Definition at line 58 of file SharedSortedMapImpl.java.
{
         return new SubSortedMapImpl<K,V>(this, null, null).keySet();
     }
References javolution.util.internal.map.sorted.SortedMapView< K, V >.keySet().
lastKey()
K javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.lastKey ()
Definition at line 63 of file SharedSortedMapImpl.java.
{
         lock.readLock.lock();
         try {
             return target().lastKey();
         } finally {
             lock.readLock.unlock();
         }
     }
References javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lock(), javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.readLock, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.target(), and javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.unlock().
perform() [1/2]
void javolution.util.internal.map.MapView< K, V >.perform (Consumer< MapService< K, V >> action, MapService< K, V > view) inherited
Reimplemented in javolution.util.internal.map.ParallelMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Definition at line 277 of file MapView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
References javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.perform().
perform() [2/2]
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
put()
V javolution.util.internal.map.SharedMapImpl< K, V >.put (K key, V value) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 130 of file SharedMapImpl.java.
{
         lock.writeLock.lock();
         try {
             return target().put(key, value);
         } finally {
             lock.writeLock.unlock();
         }
     }
References javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.lock(), javolution.util.internal.map.MapView< K, V >.target, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.unlock(), and javolution.util.internal.collection.ReadWriteLockImpl.writeLock.
putAll()
void javolution.util.internal.map.SharedMapImpl< K, V >.putAll (Map<? extends K, ? extends V > m) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 140 of file SharedMapImpl.java.
{
         lock.writeLock.lock();
         try {
             target().putAll(m);
         } finally {
             lock.writeLock.unlock();
         }
     }
References javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.lock(), javolution.util.internal.map.MapView< K, V >.target, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.unlock(), and javolution.util.internal.collection.ReadWriteLockImpl.writeLock.
putIfAbsent()
V javolution.util.internal.map.SharedMapImpl< K, V >.putIfAbsent (K key, V value) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 150 of file SharedMapImpl.java.
{
         lock.writeLock.lock();
         try {
             return target().putIfAbsent(key, value);
         } finally {
             lock.writeLock.unlock();
         }
     }
References javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.lock(), javolution.util.internal.map.MapView< K, V >.target, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.unlock(), and javolution.util.internal.collection.ReadWriteLockImpl.writeLock.
remove() [1/2]
V javolution.util.internal.map.SharedMapImpl< K, V >.remove (Object key) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 160 of file SharedMapImpl.java.
{
         lock.writeLock.lock();
         try {
             return target().remove(key);
         } finally {
             lock.writeLock.unlock();
         }
     }
References javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.lock(), javolution.util.internal.map.MapView< K, V >.target, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.unlock(), and javolution.util.internal.collection.ReadWriteLockImpl.writeLock.
Referenced by javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.remove().
remove() [2/2]
boolean javolution.util.internal.map.SharedMapImpl< K, V >.remove (Object key, Object value) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 170 of file SharedMapImpl.java.
{
         lock.writeLock.lock();
         try {
             return target().remove(key, value);
         } finally {
             lock.writeLock.unlock();
         }
     }
References javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.lock(), javolution.util.internal.map.MapView< K, V >.target, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.unlock(), and javolution.util.internal.collection.ReadWriteLockImpl.writeLock.
replace() [1/2]
boolean javolution.util.internal.map.SharedMapImpl< K, V >.replace (K key, V oldValue, V newValue) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 190 of file SharedMapImpl.java.
{
         lock.writeLock.lock();
         try {
             return target().replace(key, oldValue, newValue);
         } finally {
             lock.writeLock.unlock();
         }
     }
References javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.lock(), javolution.util.internal.map.MapView< K, V >.target, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.unlock(), and javolution.util.internal.collection.ReadWriteLockImpl.writeLock.
replace() [2/2]
V javolution.util.internal.map.SharedMapImpl< K, V >.replace (K key, V value) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 180 of file SharedMapImpl.java.
{
         lock.writeLock.lock();
         try {
             return target().replace(key, value);
         } finally {
             lock.writeLock.unlock();
         }
     }
References javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.lock(), javolution.util.internal.map.MapView< K, V >.target, javolution.util.internal.collection.ReadWriteLockImpl.WriteLock.unlock(), and javolution.util.internal.collection.ReadWriteLockImpl.writeLock.
size()
int javolution.util.internal.map.SharedMapImpl< K, V >.size () inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 200 of file SharedMapImpl.java.
                       {
         lock.readLock.lock();
         try {
             return target().size();
         } finally {
             lock.readLock.unlock();
         }
     }
References javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lock(), javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.readLock, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.unlock().
split()
MapService<K, V> [] javolution.util.internal.map.SharedMapImpl< K, V >.split (int n) inherited
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 211 of file SharedMapImpl.java.
{
         MapService<K, V>[] tmp;
         lock.readLock.lock();
         try {
             tmp = target().split(n);
         } finally {
             lock.readLock.unlock();
         }
         MapService<K, V>[] result = new MapService[tmp.length];
         for (int i = 0; i < tmp.length; i++) {
             result[i] = new SharedMapImpl<K, V>(tmp[i], lock); // Same lock.
         }
         return result;
     }
References javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lock(), javolution.util.internal.map.SharedMapImpl< K, V >.lock, javolution.util.internal.collection.ReadWriteLockImpl.readLock, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.unlock().
subMap()
SortedMapService<K, V> javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.subMap (K fromKey, K toKey)
Implements javolution.util.service.SortedMapService< K, V >.
Definition at line 73 of file SharedSortedMapImpl.java.
{
         return new SubSortedMapImpl<K,V>(this, fromKey, toKey);
     }
tailMap()
SortedMapService<K, V> javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.tailMap (K fromKey)
Implements javolution.util.service.SortedMapService< K, V >.
Definition at line 78 of file SharedSortedMapImpl.java.
{
         return new SubSortedMapImpl<K,V>(this, fromKey, null);
     }
target()
SortedMapService<K,V> javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.target () protected
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 88 of file SharedSortedMapImpl.java.
{
         return (SortedMapService<K,V>) super.target();
     }
Referenced by javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.comparator(), javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.firstKey(), javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.lastKey(), and javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.SharedSortedMapImpl().
threadSafe()
SortedMapService<K, V> javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.threadSafe ()
Returns a thread-safe version of this service (used during parallel updates).
Reimplemented from javolution.util.internal.map.SharedMapImpl< K, V >.
Definition at line 83 of file SharedSortedMapImpl.java.
{
         return this;
     }
update() [1/2]
void javolution.util.internal.map.MapView< K, V >.update (Consumer< MapService< K, V >> action, MapService< K, V > view) inherited
Reimplemented in javolution.util.internal.map.ParallelMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Definition at line 361 of file MapView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.update(action, view);
         }
     }
References javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.update().
update() [2/2]
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
valueComparator()
Equality<? super V> javolution.util.internal.map.SharedMapImpl< K, V >.valueComparator () inherited
Returns the value comparator used for value equality.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 232 of file SharedMapImpl.java.
{
         return target().valueComparator();
     }
References javolution.util.internal.map.MapView< K, V >.target.
values()
CollectionService<V> javolution.util.internal.map.MapView< K, V >.values () inherited
Returns a collection view over the values of this map, the collection support value/entry removal but not adding new values.
Implements javolution.util.service.MapService< K, V >.
Definition at line 373 of file MapView.java.
{
         return new Values();
     }
Referenced by javolution.util.internal.map.MapView< K, V >.containsValue().
Member Data Documentation
lock
ReadWriteLockImpl javolution.util.internal.map.SharedMapImpl< K, V >.lock protected inherited
Definition at line 57 of file SharedMapImpl.java.
Referenced by javolution.util.internal.map.SharedMapImpl< K, V >.clear(), javolution.util.internal.map.SharedMapImpl< K, V >.containsKey(), javolution.util.internal.map.SharedMapImpl< K, V >.containsValue(), javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.firstKey(), javolution.util.internal.map.SharedMapImpl< K, V >.get(), javolution.util.internal.map.SharedMapImpl< K, V >.isEmpty(), javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.IteratorImpl(), javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.lastKey(), javolution.util.internal.map.SharedMapImpl< K, V >.put(), javolution.util.internal.map.SharedMapImpl< K, V >.putAll(), javolution.util.internal.map.SharedMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.SharedMapImpl< K, V >.remove(), javolution.util.internal.map.SharedMapImpl< K, V >.replace(), javolution.util.internal.map.SharedMapImpl< K, V >.SharedMapImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.size(), and javolution.util.internal.map.SharedMapImpl< K, V >.split().
serialVersionUID
final long javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.serialVersionUID = 0x600L static private
Definition at line 23 of file SharedSortedMapImpl.java.
updatingThread
transient Thread javolution.util.internal.map.SharedMapImpl< K, V >.updatingThread protected inherited
Definition at line 58 of file SharedMapImpl.java.
The documentation for this class was generated from the following file:
SharedSortedMapImpl.java