Javolution 6.0.0 java: javolution.xml.stream.XMLStreamException Class Reference
javolution.xml.stream.XMLStreamException Class Reference
Public Member Functions
XMLStreamException ()
XMLStreamException (String msg)
XMLStreamException (Throwable nested)
XMLStreamException (String msg, Throwable nested)
XMLStreamException (String msg, Location location, Throwable nested)
XMLStreamException (String msg, Location location)
Throwable getNestedException ()
Location getLocation ()
String toString ()
Private Attributes
Throwable _nested
Location _location
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
This class represents the base exception for unexpected processing errors.
Author
Jean-Marie Dautelle
Version
3.8, May 22, 2006
Definition at line 17 of file XMLStreamException.java.
Constructor & Destructor Documentation
XMLStreamException() [1/6]
javolution.xml.stream.XMLStreamException.XMLStreamException ()
Default constructor
Definition at line 32 of file XMLStreamException.java.
{
         super();
     }
XMLStreamException() [2/6]
javolution.xml.stream.XMLStreamException.XMLStreamException (String msg)
Constructs an exception with the assocated message.
Parameters
msg the message to report.
Definition at line 41 of file XMLStreamException.java.
{
         super(msg);
     }
XMLStreamException() [3/6]
javolution.xml.stream.XMLStreamException.XMLStreamException (Throwable nested)
Constructs an exception with the assocated nested exception.
Parameters
nested the nested exception.
Definition at line 50 of file XMLStreamException.java.
{
         _nested = nested;
     }
References javolution.xml.stream.XMLStreamException._nested.
XMLStreamException() [4/6]
javolution.xml.stream.XMLStreamException.XMLStreamException (String msg, Throwable nested)
Constructs an exception with the assocated message and exception.
Parameters
msg the message to report.
nested the nested exception.
Definition at line 60 of file XMLStreamException.java.
{
         super(msg);
         _nested = nested;
     }
References javolution.xml.stream.XMLStreamException._nested.
XMLStreamException() [5/6]
javolution.xml.stream.XMLStreamException.XMLStreamException (String msg, Location location, Throwable nested)
Constructs an exception with the assocated message, exception and location.
Parameters
msg the message to report.
location the location.
nested the nested exception.
Definition at line 73 of file XMLStreamException.java.
{
         super(msg);
         _nested = nested;
         _location = location;
     }
References javolution.xml.stream.XMLStreamException._location, and javolution.xml.stream.XMLStreamException._nested.
XMLStreamException() [6/6]
javolution.xml.stream.XMLStreamException.XMLStreamException (String msg, Location location)
Constructs an exception with the assocated message, exception and location.
Parameters
msg the message to report
location the location of the error
Definition at line 86 of file XMLStreamException.java.
{
         super(msg);
         _location = location;
     }
References javolution.xml.stream.XMLStreamException._location.
Member Function Documentation
getLocation()
Location javolution.xml.stream.XMLStreamException.getLocation ()
Returns the location of the exception.
Returns
the location of the exception or null if none is available
Definition at line 106 of file XMLStreamException.java.
{
         return _location;
     }
References javolution.xml.stream.XMLStreamException._location.
getNestedException()
Throwable javolution.xml.stream.XMLStreamException.getNestedException ()
Returns the nested exception.
Returns
the nested exception
Definition at line 96 of file XMLStreamException.java.
{
         return _nested;
     }
References javolution.xml.stream.XMLStreamException._nested.
Referenced by javolution.xml.sax.XMLReaderImpl.parse().
toString()
String javolution.xml.stream.XMLStreamException.toString ()
Returns the textual representation of this exception.
Returns
the string representation of the exception.
Definition at line 115 of file XMLStreamException.java.
{
         String msg = super.toString();
         if (_location != null) {
             msg += " (at line " + _location.getLineNumber() + ", column "
                     + _location.getColumnNumber() + ")";
         }
         if (_nested != null) {
             msg += " caused by " + _nested.toString();
         }
         return msg;
     }
References javolution.xml.stream.XMLStreamException._location, javolution.xml.stream.XMLStreamException._nested, javolution.xml.stream.Location.getColumnNumber(), and javolution.xml.stream.Location.getLineNumber().
Member Data Documentation
_location
Location javolution.xml.stream.XMLStreamException._location private
Holds the location.
Definition at line 27 of file XMLStreamException.java.
Referenced by javolution.xml.stream.XMLStreamException.getLocation(), javolution.xml.stream.XMLStreamException.toString(), and javolution.xml.stream.XMLStreamException.XMLStreamException().
_nested
Throwable javolution.xml.stream.XMLStreamException._nested private
Holds the nested exception if any.
Definition at line 22 of file XMLStreamException.java.
Referenced by javolution.xml.stream.XMLStreamException.getNestedException(), javolution.xml.stream.XMLStreamException.toString(), and javolution.xml.stream.XMLStreamException.XMLStreamException().
serialVersionUID
final long javolution.xml.stream.XMLStreamException.serialVersionUID = 1L static private
Definition at line 127 of file XMLStreamException.java.
The documentation for this class was generated from the following file:
XMLStreamException.java