Javolution 6.0.0 java: javolution.util.internal.set.MappedSetImpl< E, R > Class Template Reference
javolution.util.internal.set.MappedSetImpl< E, R > Class Template Reference abstract
Public Member Functions
MappedSetImpl (SetService< E > target, Function<? super E, ? extends R > function)
abstract boolean add (R r)
abstract boolean contains (Object r)
abstract boolean remove (Object r)
SetService< R > threadSafe ()
abstract boolean add (E element)
void clear ()
Equality<? super R > comparator ()
boolean isEmpty ()
Iterator< R > iterator ()
int size ()
boolean addAll (Collection<? extends E > c)
CollectionView< E > clone ()
boolean containsAll (Collection<?> c)
boolean equals (Object o)
int hashCode ()
void perform (Consumer< CollectionService< E >> action, CollectionService< E > view)
boolean removeAll (Collection<?> c)
boolean retainAll (Collection<?> c)
CollectionService< E >[] split (int n)
Object[] toArray ()
void update (Consumer< CollectionService< E >> action, CollectionService< E > view)
CollectionService< E > clone () throws CloneNotSupportedException
Equality<? super E > comparator ()
void perform (Consumer< T > action, T part)
T[] split (int n)
void update (Consumer< T > action, T part)
Protected Member Functions
CollectionService< E > target ()
CollectionService< E > service ()
Protected Attributes
final Function<? super E, ? extends R > function
Package Functions
public< T > T[] toArray (T[] a)
Private Attributes
CollectionService< E > target
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
A mapped view over a set.
Definition at line 18 of file MappedSetImpl.java.
Constructor & Destructor Documentation
MappedSetImpl()
javolution.util.internal.set.MappedSetImpl< E, R >.MappedSetImpl (SetService< E > target, Function<? super E, ? extends R > function)
Definition at line 23 of file MappedSetImpl.java.
{
         super(target, function);
     }
Member Function Documentation
add() [1/2]
abstract boolean javolution.util.internal.collection.CollectionView< E >.add (E element) abstract inherited
Adds the specified element to this collection
add() [2/2]
abstract boolean javolution.util.internal.set.MappedSetImpl< E, R >.add (R r) abstract
Reimplemented from javolution.util.internal.collection.MappedCollectionImpl< E, R >.
addAll()
boolean javolution.util.internal.collection.CollectionView< E >.addAll (Collection<? extends E > that) inherited
Adds all the specified elements to this collection.
Definition at line 46 of file CollectionView.java.
{
         boolean changed = false;
         Iterator<? extends E> it = c.iterator();
         while (it.hasNext()) {
             if (add(it.next())) changed = true;
         }
         return changed;
     }
clear()
void javolution.util.internal.collection.MappedCollectionImpl< E, R >.clear () inherited
Definition at line 66 of file MappedCollectionImpl.java.
{
         target().clear();
     }
clone() [1/2]
CollectionService<E> javolution.util.service.CollectionService< E >.clone () throws CloneNotSupportedException inherited
Returns a copy of this collection; updates of the copy should not impact the original.
Implemented in javolution.util.internal.table.FastTableImpl< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, and javolution.util.internal.collection.CollectionView< E >.
clone() [2/2]
CollectionView<E> javolution.util.internal.collection.CollectionView< E >.clone () inherited
Returns a copy of this collection; updates of the copy should not impact the original.
Definition at line 66 of file CollectionView.java.
{
         try {
             CollectionView<E> copy = (CollectionView<E>) super.clone();
             if (target != null) { // Not a root class.
                 copy.target = target.clone();
             }
             return copy;
         } catch (CloneNotSupportedException e) {
             throw new Error("Should not happen since target is cloneable");
         }
     }
comparator() [1/2]
Equality<? super E> javolution.util.service.CollectionService< E >.comparator () inherited
Returns the comparator used for element equality or order if the collection is sorted.
Implemented in javolution.util.internal.map.MapView< K, V >.KeySet, javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.bitset.BitSetServiceImpl, javolution.util.internal.table.FastTableImpl< E >, javolution.util.internal.table.SubTableImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, javolution.util.internal.collection.SortedCollectionImpl< E >, javolution.util.internal.set.sorted.SubSortedSetImpl< E >, javolution.util.internal.collection.CollectionView< E >, javolution.util.internal.collection.FilteredCollectionImpl< E >, javolution.util.internal.table.UnmodifiableTableImpl< E >, javolution.util.internal.collection.DistinctCollectionImpl< E >, javolution.util.internal.map.MapView< K, V >.EntrySet, javolution.util.internal.table.ReversedTableImpl< E >, javolution.util.internal.collection.ReversedCollectionImpl< E >, javolution.util.internal.collection.UnmodifiableCollectionImpl< E >, javolution.util.internal.collection.ParallelCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Referenced by javolution.util.FastTable< javolution.xml.internal.stream.XMLStreamReaderImpl >.sort().
comparator() [2/2]
Equality<? super R> javolution.util.internal.collection.MappedCollectionImpl< E, R >.comparator () inherited
Reimplemented in javolution.util.internal.map.MapView< K, V >.Values, and javolution.util.internal.map.MapView< K, V >.KeySet.
Definition at line 71 of file MappedCollectionImpl.java.
{
         return Equalities.STANDARD;
     }
contains()
abstract boolean javolution.util.internal.set.MappedSetImpl< E, R >.contains (Object r) abstract
Reimplemented in javolution.util.internal.map.MapView< K, V >.KeySet.
containsAll()
boolean javolution.util.internal.collection.CollectionView< E >.containsAll (Collection<?> that) inherited
Indicates if this collection contains all the specified elements.
Definition at line 93 of file CollectionView.java.
{
         for (Object e : c) {
             if (!contains(e)) return false;
         }
         return true;
     }
equals()
boolean javolution.util.internal.collection.CollectionView< E >.equals (Object obj) inherited
Compares the specified object with this collection for equality. This method follows the Collection#equals(Object) specification if this collection comparator is Equalities#STANDARD (default). Otherwise, only collections using the same comparator can be considered equals.
Parameters
obj the object to be compared for equality with this collection
Returns
true if both collections are considered equals; false otherwise.
Definition at line 102 of file CollectionView.java.
{
         // Follow Collection.equals specification if this comparator is standard.
         if (this == o) return true;
         // Check comparators consistency.
         if (o instanceof CollectionService) {
             if (!comparator().equals(((CollectionService<E>) o).comparator())) return false; // Different comparators.
         } else {
             if (!comparator().equals(Equalities.STANDARD)) return false;
         }
         // Collection.equals contract.
         if (this instanceof Set) {
             if (!(o instanceof Set)) return false;
             Set<E> set = (Set<E>) o;
             return (size() == set.size()) && containsAll(set);
         } else if (this instanceof List) {
             if (!(o instanceof List)) return false;
             List<E> list = (List<E>) o;
             if (size() != list.size()) return false; // Short-cut.
             Equality<? super E> cmp = comparator();
             Iterator<E> it1 = this.iterator();
             Iterator<E> it2 = list.iterator();
             while (it1.hasNext()) {
                 if (!it2.hasNext()) return false;
                 if (!cmp.areEqual(it1.next(), it2.next())) return false;
             }
             if (it2.hasNext()) return false;
             return true;
         } else {
             return false;
         }
     }
hashCode()
int javolution.util.internal.collection.CollectionView< E >.hashCode () inherited
Returns the hash code of this collection. This method follows the Collection#hashCode() specification if this collection comparator is Equalities#STANDARD.
Returns
this collection hash code.
Definition at line 135 of file CollectionView.java.
{
         // Follow Collection.equals specification if this comparator is standard.
         Equality<? super E> cmp = comparator();
         Iterator<E> it = this.iterator();
         int hash = 0;
         if (this instanceof Set) {
             while (it.hasNext()) {
                 hash += cmp.hashCodeOf(it.next());
             }
         } else if (this instanceof List) {
             while (it.hasNext()) {
                 hash += 31 * hash + cmp.hashCodeOf(it.next());
             }
         } else {
             hash = super.hashCode();
         }
         return hash;
     }
isEmpty()
boolean javolution.util.internal.collection.MappedCollectionImpl< E, R >.isEmpty () inherited
Definition at line 76 of file MappedCollectionImpl.java.
{
         return target().isEmpty();
     }
iterator()
Iterator<R> javolution.util.internal.collection.MappedCollectionImpl< E, R >.iterator () inherited
Definition at line 81 of file MappedCollectionImpl.java.
{
         return new IteratorImpl();
     }
perform() [1/2]
void javolution.util.internal.collection.CollectionView< E >.perform (Consumer< CollectionService< E >> action, CollectionService< E > view) inherited
Definition at line 163 of file CollectionView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
perform() [2/2]
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
remove()
abstract boolean javolution.util.internal.set.MappedSetImpl< E, R >.remove (Object r) abstract
Reimplemented in javolution.util.internal.map.MapView< K, V >.KeySet.
removeAll()
boolean javolution.util.internal.collection.CollectionView< E >.removeAll (Collection<?> that) inherited
Removes all the specified element from this collection.
Definition at line 186 of file CollectionView.java.
{
         boolean changed = false;
         Iterator<? extends E> it = iterator();
         while (it.hasNext()) {
             if (c.contains(it.next())) {
                 it.remove();
                 changed = true;
             }
         }
         return changed;
     }
retainAll()
boolean javolution.util.internal.collection.CollectionView< E >.retainAll (Collection<?> that) inherited
Removes all the elements except those in the specified collection.
Definition at line 199 of file CollectionView.java.
{
         boolean changed = false;
         Iterator<? extends E> it = iterator();
         while (it.hasNext()) {
             if (!c.contains(it.next())) {
                 it.remove();
                 changed = true;
             }
         }
         return changed;
     }
service()
CollectionService<E> javolution.util.internal.collection.CollectionView< E >.service () protected inherited
Returns the service implementation of this collection (for sub-classes).
Definition at line 274 of file CollectionView.java.
{
         return this;
     }
size()
int javolution.util.internal.collection.MappedCollectionImpl< E, R >.size () inherited
Definition at line 86 of file MappedCollectionImpl.java.
                       {
         return target().size();
     }
split() [1/2]
T [] javolution.util.function.Splittable< T >.split (int n) inherited
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Implemented in javolution.util.internal.map.MapView< K, V >, javolution.util.internal.table.SharedTableImpl< E >, javolution.util.internal.table.TableView< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.CollectionView< E >, javolution.util.internal.table.AtomicTableImpl< E >, javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.collection.AtomicCollectionImpl< E >, and javolution.util.internal.map.MapView< K, V >.EntrySet.
Referenced by javolution.util.internal.map.ParallelMapImpl< K, V >.perform(), and javolution.util.internal.collection.ParallelCollectionImpl< E >.perform().
split() [2/2]
CollectionService<E> [] javolution.util.internal.collection.CollectionView< E >.split (int n) inherited
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Definition at line 224 of file CollectionView.java.
{
         if (target == null) return new CollectionService[] { this }; // No split.
         CollectionService<E>[] subTargets = target.split(n);
         CollectionService<E>[] result = new CollectionService[subTargets.length];
         for (int i = 0; i < subTargets.length; i++) {
             CollectionView<E> copy = this.clone();
             copy.target = subTargets[i];
             result[i] = copy;
         }
         return result;
     }
target()
CollectionService<E> javolution.util.internal.collection.CollectionView< E >.target () protected inherited
Returns the actual target
Definition at line 279 of file CollectionView.java.
{
         return target;
     }
threadSafe()
SetService<R> javolution.util.internal.set.MappedSetImpl< E, R >.threadSafe ()
Returns a thread-safe version of this service (used during parallel updates).
Implements javolution.util.service.SetService< E >.
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >.KeySortedSet.
Definition at line 38 of file MappedSetImpl.java.
{
         return new SharedSetImpl<R>(this);
     }
toArray() [1/2]
Object [] javolution.util.internal.collection.CollectionView< E >.toArray () inherited
Returns an array holding this collection elements.
Definition at line 243 of file CollectionView.java.
{
         return toArray(new Object[size()]);
     }
toArray() [2/2]
public<T> T [] javolution.util.internal.collection.CollectionView< E >.toArray (T[] array) package inherited
Returns the specified array holding this collection elements if enough capacity.
Definition at line 249 of file CollectionView.java.
{
         final int size = size();
         final T[] result = (size <= a.length) ? a
                 : (T[]) java.lang.reflect.Array.newInstance(a.getClass()
                         .getComponentType(), size);
         int i = 0;
         Iterator<E> it = iterator();
         while (it.hasNext()) {
             result[i++] = (T) it.next();
         }
         if (result.length > size) {
             result[size] = null; // As per Collection contract.
         }
         return result;
     }
update() [1/2]
void javolution.util.internal.collection.CollectionView< E >.update (Consumer< CollectionService< E >> action, CollectionService< E > view) inherited
Definition at line 266 of file CollectionView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
update() [2/2]
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
Member Data Documentation
function
final Function<? super E, ? extends R> javolution.util.internal.collection.MappedCollectionImpl< E, R >.function protected inherited
Definition at line 50 of file MappedCollectionImpl.java.
serialVersionUID
final long javolution.util.internal.set.MappedSetImpl< E, R >.serialVersionUID = 0x600L static private
Definition at line 21 of file MappedSetImpl.java.
target
CollectionService<E> javolution.util.internal.collection.CollectionView< E >.target private inherited
Definition at line 33 of file CollectionView.java.
The documentation for this class was generated from the following file:
MappedSetImpl.java