Javolution 6.0.0 java: javolution.context.LocalContext.Parameter< T > Class Template Reference
javolution.context.LocalContext.Parameter< T > Class Template Reference abstract
Public Member Functions
Parameter ()
Permission< Parameter< T > > getSupersedePermission ()
T get ()
String getName ()
Permission< Configurable< T > > getReconfigurePermission ()
T reconfigure (T newValue)
Static Public Attributes
static final Permission< Parameter<?> > SUPERSEDE_PERMISSION
static Permission< Configurable<?> > RECONFIGURE_PERMISSION
Protected Member Functions
abstract T getDefault ()
T initialized (T value)
T parse (String str)
T reconfigured (T oldValue, T newValue)
Private Attributes
final Permission< Parameter< T > > supersedePermission
String name
final Permission< Configurable< T > > reconfigurePermission
volatile T value
Detailed Description
A configurable parameter whose value can be locally superseded within the scope of LocalContext.
Definition at line 49 of file LocalContext.java.
Constructor & Destructor Documentation
Parameter()
javolution.context.LocalContext.Parameter< T >.Parameter ()
Creates a new parameter (configurable).
Definition at line 66 of file LocalContext.java.
{
             this.supersedePermission = new Permission<Parameter<T>>(
                     Parameter.class, "supersede", this);
         }
Member Function Documentation
get()
T javolution.context.LocalContext.Parameter< T >.get ()
Returns the current parameter value (the default value if not reconfigured nor superseded).
Reimplemented from javolution.lang.Configurable< T >.
Definition at line 83 of file LocalContext.java.
{
             LocalContext ctx = current(LocalContext.class);
             return (ctx != null) ? ctx.getValue(this, super.get()) : super.get();
         }
References javolution.context.AbstractContext.current(), and javolution.context.LocalContext.getValue().
getDefault()
abstract T javolution.lang.Configurable< T >.getDefault () abstract protected inherited
Returns this configurable default value (always different from
null
).
Referenced by javolution.lang.Configurable< javolution.context.LogContext.Level >.Configurable(), and javolution.lang.Configurable< javolution.context.LogContext.Level >.parse().
getName()
String javolution.lang.Configurable< T >.getName () inherited
Returns this configurable name. By convention, the name of the configurable is the name of the static field holding the configurable (e.g. "javolution.context.ConcurrentContext#CONCURRENCY"). This method should be overridden if the enclosing class needs to be impervious to obfuscation or if the enclosing class defines multiple configurable fields.
Exceptions
UnsupportedOperationException if the enclosing class has multiple configurable static fields.
Definition at line 185 of file Configurable.java.
{
         if (name != null)
             return name; // Already set.
         Class<?> thisClass = this.getClass();
         Class<?> enclosingClass = thisClass.getEnclosingClass();
         String fieldName = null;
         for (Field field : enclosingClass.getFields()) {
             if (field.getType().isAssignableFrom(thisClass)) {
                 if (fieldName != null) // Indistinguishable field types.
                     throw new UnsupportedOperationException(
                        "Multiple configurables static fields in the same class" +
                        "requires the Configurable.getName() method to be overriden.");
                 fieldName = field.getName();
             }
         }
         return (fieldName != null) ? enclosingClass.getName() + "#" + fieldName
                 : null;
     }
Referenced by javolution.lang.Configurable< javolution.context.LogContext.Level >.Configurable(), javolution.osgi.internal.ConfigurableListenerImpl.configurableInitialized(), and javolution.osgi.internal.ConfigurableListenerImpl.configurableReconfigured().
getReconfigurePermission()
Permission<Configurable<T> > javolution.lang.Configurable< T >.getReconfigurePermission () inherited
Returns the permission to configure this instance.
Definition at line 207 of file Configurable.java.
{
         return reconfigurePermission;
     }
getSupersedePermission()
Permission<Parameter<T> > javolution.context.LocalContext.Parameter< T >.getSupersedePermission ()
Returns the permission to locally supersede the current value of this instance.
Definition at line 75 of file LocalContext.java.
{
             return supersedePermission;
         }
References javolution.context.LocalContext.Parameter< T >.supersedePermission.
initialized()
T javolution.lang.Configurable< T >.initialized (T value) protected inherited
This methods is called when the configurable is initialized. Developers may override this method to perform any initialization logic (e.g. input validation).
Parameters
value the requested value for this configurable.
Returns
the actual value of this configurable.
Definition at line 252 of file Configurable.java.
{
         return value;
     }
Referenced by javolution.lang.Configurable< javolution.context.LogContext.Level >.Configurable().
parse()
T javolution.lang.Configurable< T >.parse (String str) protected inherited
Parses the specified text to return the corresponding value. This method is used to initialize this configurable from system properties. The default implementation uses the TextContext to retrieve the text format (based on DefaultTextFormat class annotation).
Definition at line 264 of file Configurable.java.
{
         Class<? extends T> type = (Class<? extends T>) getDefault().getClass();
         return TextContext.getFormat(type).parse(str);
     }
Referenced by javolution.lang.Configurable< javolution.context.LogContext.Level >.Configurable().
reconfigure()
T javolution.lang.Configurable< T >.reconfigure (T newValue) inherited
Reconfigures this instance with the specified value if authorized by the SecurityContext. This method returns the actual new value which may be different from the requested new value (see reconfigured(Object, Object)).
Parameters
newValue the requested new value.
Returns
the actual new value.
Exceptions
SecurityException if the permission to reconfigure this configurable is not granted.
UnsupportedOperationException if this configurable does not support dynamic reconfiguration.
Definition at line 224 of file Configurable.java.
{
         SecurityContext.check(reconfigurePermission);
         synchronized (this) {
             T oldValue = this.value;
             this.value = reconfigured(oldValue, newValue);
             Object[] listeners = OSGiServices.getConfigurableListeners();
             for (Object listener : listeners) {
                 ((Listener) listener).configurableReconfigured(this, oldValue,
                         this.value);
             }
             return this.value;
         }
     }
reconfigured()
T javolution.lang.Configurable< T >.reconfigured (T oldValue, T newValue) protected inherited
This methods is called when the configurable is reconfigured. Developers may override this method to perform any reconfiguration logic (e.g. hard limiting values).
Parameters
oldValue the old value.
newValue the requested new value.
Returns
the actual new value of this configurable.
Exceptions
UnsupportedOperationException if this configurable does not support dynamic reconfiguration.
Definition at line 280 of file Configurable.java.
{
         return newValue;
     }
Referenced by javolution.lang.Configurable< javolution.context.LogContext.Level >.reconfigure().
Member Data Documentation
name
String javolution.lang.Configurable< T >.name private inherited
Holds the configurable name.
Definition at line 121 of file Configurable.java.
Referenced by javolution.lang.Configurable< javolution.context.LogContext.Level >.Configurable(), and javolution.lang.Configurable< javolution.context.LogContext.Level >.getName().
RECONFIGURE_PERMISSION
Permission<Configurable<?> > javolution.lang.Configurable< T >.RECONFIGURE_PERMISSION static inherited
Initial value:
= new Permission<Configurable<?>>(
            Configurable.class, "reconfigure")
Holds the general permission to reconfigure configurable instances (action "reconfigure"). Whether or not that permission is granted depends on the current SecurityContext. It is possible that the general permission to reconfigure a configurable is granted but revoked for a specific instance. Also, the general permission to reconfigure a configurable may be revoked but granted only for a specific instance.
Definition at line 115 of file Configurable.java.
reconfigurePermission
final Permission<Configurable<T> > javolution.lang.Configurable< T >.reconfigurePermission private inherited
Holds the reconfigure permission.
Definition at line 126 of file Configurable.java.
Referenced by javolution.lang.Configurable< javolution.context.LogContext.Level >.Configurable(), javolution.lang.Configurable< javolution.context.LogContext.Level >.getReconfigurePermission(), and javolution.lang.Configurable< javolution.context.LogContext.Level >.reconfigure().
SUPERSEDE_PERMISSION
final Permission<Parameter<?> > javolution.context.LocalContext.Parameter< T >.SUPERSEDE_PERMISSION static
Initial value:
= new Permission<Parameter<?>>(
                Parameter.class, "supersede")
Holds the general permission to supersede any parameter value (action "supersede").
Definition at line 55 of file LocalContext.java.
supersedePermission
final Permission<Parameter<T> > javolution.context.LocalContext.Parameter< T >.supersedePermission private
Holds this instance supersede permission.
Definition at line 61 of file LocalContext.java.
Referenced by javolution.context.LocalContext.Parameter< T >.getSupersedePermission().
value
volatile T javolution.lang.Configurable< T >.value private inherited
Holds the configurable value.
Definition at line 131 of file Configurable.java.
Referenced by javolution.lang.Configurable< javolution.context.LogContext.Level >.get(), javolution.lang.Configurable< javolution.context.LogContext.Level >.initialized(), and javolution.lang.Configurable< javolution.context.LogContext.Level >.reconfigure().
The documentation for this class was generated from the following file:
LocalContext.java