Javolution 6.0.0 java: javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V > Class Template Reference
javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V > Class Template Reference
Public Member Functions
UnmodifiableSortedMapImpl (SortedMapService< K, V > target)
Comparator<? super K > comparator ()
SortedSetService< Map.Entry< K, V > > entrySet ()
K firstKey ()
SortedMapService< K, V > headMap (K toKey)
SortedSetService< K > keySet ()
K lastKey ()
SortedMapService< K, V > subMap (K fromKey, K toKey)
SortedMapService< K, V > tailMap (K fromKey)
SortedMapService< K, V > threadSafe ()
void clear ()
boolean containsKey (Object key)
V get (Object key)
Iterator< Entry< K, V > > iterator ()
Equality<? super K > keyComparator ()
V put (K key, V value)
V remove (Object key)
boolean remove (Object key, Object value)
Equality<? super V > valueComparator ()
MapView< K, V > clone ()
boolean containsValue (Object value)
boolean isEmpty ()
void perform (Consumer< MapService< K, V >> action, MapService< K, V > view)
void perform (Consumer< T > action, T part)
void putAll (Map<? extends K, ? extends V > m)
V putIfAbsent (K key, V value)
V replace (K key, V value)
boolean replace (K key, V oldValue, V newValue)
int size ()
MapService< K, V >[] split (int n)
void update (Consumer< MapService< K, V >> action, MapService< K, V > view)
void update (Consumer< T > action, T part)
CollectionService< V > values ()
Protected Member Functions
SortedMapService< K, V > target ()
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
An unmodifiable view over a map.
Definition at line 21 of file UnmodifiableSortedMapImpl.java.
Constructor & Destructor Documentation
UnmodifiableSortedMapImpl()
javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.UnmodifiableSortedMapImpl (SortedMapService< K, V > target)
Definition at line 25 of file UnmodifiableSortedMapImpl.java.
{
         super(target);
     }
References javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.target().
Member Function Documentation
clear()
void javolution.util.internal.map.UnmodifiableMapImpl< K, V >.clear () inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 49 of file UnmodifiableMapImpl.java.
{
         throw new UnsupportedOperationException("Unmodifiable");
     }
clone()
MapView<K, V> javolution.util.internal.map.MapView< K, V >.clone () inherited
Returns a copy of this map; updates of the copy should not impact the original.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.AtomicMapImpl< K, V >, and javolution.util.internal.map.FastMapImpl< K, V >.
Definition at line 232 of file MapView.java.
{
         try {
             MapView<K, V> copy = (MapView<K, V>) super.clone();
             if (target != null) { // Not a root class.
                 copy.target = target.clone();
             }
             return copy;
         } catch (CloneNotSupportedException e) {
             throw new Error("Should not happen since target is cloneable");
         }
     }
References javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.split().
comparator()
Comparator<? super K> javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.comparator ()
Definition at line 30 of file UnmodifiableSortedMapImpl.java.
{
         return target().keyComparator();
     }
References javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.target().
containsKey()
boolean javolution.util.internal.map.UnmodifiableMapImpl< K, V >.containsKey (Object key) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 54 of file UnmodifiableMapImpl.java.
{
         return target().containsKey(key);
     }
References javolution.util.internal.map.MapView< K, V >.target.
containsValue()
boolean javolution.util.internal.map.MapView< K, V >.containsValue (Object value) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 248 of file MapView.java.
{
         return values().contains(value);
     }
References javolution.util.internal.map.MapView< K, V >.values().
entrySet()
SortedSetService<Map.Entry<K, V> > javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.entrySet ()
Returns a set view over the entries of this map. The set support adding/removing entries. Two entries are considered equals if they have the same key regardless of their values.
Implements javolution.util.service.SortedMapService< K, V >.
Definition at line 35 of file UnmodifiableSortedMapImpl.java.
{
         return new SubSortedMapImpl<K,V>(this, null, null).entrySet();
     }
References javolution.util.internal.map.sorted.SortedMapView< K, V >.entrySet().
firstKey()
K javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.firstKey ()
Definition at line 40 of file UnmodifiableSortedMapImpl.java.
{
         return target().firstKey();
     }
References javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.target().
get()
V javolution.util.internal.map.UnmodifiableMapImpl< K, V >.get (Object key) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 59 of file UnmodifiableMapImpl.java.
{
         return target().get(key);
     }
References javolution.util.internal.map.MapView< K, V >.target.
headMap()
SortedMapService<K, V> javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.headMap (K toKey)
Implements javolution.util.service.SortedMapService< K, V >.
Definition at line 45 of file UnmodifiableSortedMapImpl.java.
{
         return new SubSortedMapImpl<K,V>(this, null, toKey);
     }
isEmpty()
boolean javolution.util.internal.map.MapView< K, V >.isEmpty () inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 261 of file MapView.java.
{
         return iterator().hasNext();
     }
References javolution.util.internal.map.MapView< K, V >.iterator().
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.isEmpty().
iterator()
Iterator<Entry<K, V> > javolution.util.internal.map.UnmodifiableMapImpl< K, V >.iterator () inherited
Returns an iterator over this map entries.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 64 of file UnmodifiableMapImpl.java.
{
         return new IteratorImpl();
     }
keyComparator()
Equality<? super K> javolution.util.internal.map.UnmodifiableMapImpl< K, V >.keyComparator () inherited
Returns the key comparator used for key equality or order if the map is sorted.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 69 of file UnmodifiableMapImpl.java.
{
         return target().keyComparator();
     }
References javolution.util.internal.map.MapView< K, V >.target.
keySet()
SortedSetService<K> javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.keySet ()
Returns a set view over the key of this map, the set support adding new key for which the value is automatically
null
.
Implements javolution.util.service.SortedMapService< K, V >.
Definition at line 50 of file UnmodifiableSortedMapImpl.java.
{
         return new SubSortedMapImpl<K,V>(this, null, null).keySet();
     }
References javolution.util.internal.map.sorted.SortedMapView< K, V >.keySet().
lastKey()
K javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.lastKey ()
Definition at line 55 of file UnmodifiableSortedMapImpl.java.
{
         return target().lastKey();
     }
References javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.target().
perform() [1/2]
void javolution.util.internal.map.MapView< K, V >.perform (Consumer< MapService< K, V >> action, MapService< K, V > view) inherited
Reimplemented in javolution.util.internal.map.ParallelMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Definition at line 277 of file MapView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
References javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.perform().
perform() [2/2]
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
put()
V javolution.util.internal.map.UnmodifiableMapImpl< K, V >.put (K key, V value) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 74 of file UnmodifiableMapImpl.java.
{
         throw new UnsupportedOperationException("Unmodifiable");
     }
putAll()
void javolution.util.internal.map.MapView< K, V >.putAll (Map<? extends K, ? extends V > m) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 290 of file MapView.java.
{
         Iterator<?> it = m.entrySet().iterator();
         while (it.hasNext()) {
             Entry<K, V> e = (Entry<K, V>) it.next();
             put(e.getKey(), e.getValue());
         }
     }
References javolution.util.internal.map.MapView< K, V >.put().
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.clone().
putIfAbsent()
V javolution.util.internal.map.MapView< K, V >.putIfAbsent (K key, V value) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 299 of file MapView.java.
{
         if (!containsKey(key)) return put(key, value);
         else return get(key);
     }
References javolution.util.internal.map.MapView< K, V >.containsKey(), and javolution.util.internal.map.MapView< K, V >.put().
remove() [1/2]
V javolution.util.internal.map.UnmodifiableMapImpl< K, V >.remove (Object key) inherited
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 79 of file UnmodifiableMapImpl.java.
{
         throw new UnsupportedOperationException("Unmodifiable");
     }
remove() [2/2]
boolean javolution.util.internal.map.MapView< K, V >.remove (Object key, Object value) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 308 of file MapView.java.
{
         if (containsKey(key) && get(key).equals(value)) {
             remove(key);
             return true;
         } else return false;
     }
References javolution.util.internal.map.MapView< K, V >.containsKey().
replace() [1/2]
boolean javolution.util.internal.map.MapView< K, V >.replace (K key, V oldValue, V newValue) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 323 of file MapView.java.
{
         if (containsKey(key) && get(key).equals(oldValue)) {
             put(key, newValue);
             return true;
         } else return false;
     }
References javolution.util.internal.map.MapView< K, V >.containsKey(), and javolution.util.internal.map.MapView< K, V >.put().
replace() [2/2]
V javolution.util.internal.map.MapView< K, V >.replace (K key, V value) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 316 of file MapView.java.
{
         if (containsKey(key)) {
             return put(key, value);
         } else return null;
     }
References javolution.util.internal.map.MapView< K, V >.containsKey(), and javolution.util.internal.map.MapView< K, V >.put().
size()
int javolution.util.internal.map.MapView< K, V >.size () inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 331 of file MapView.java.
                       {
         int count = 0;
         Iterator<Entry<K, V>> it = iterator();
         while (it.hasNext()) {
             count++;
             it.next();
         }
         return count;
     }
References javolution.util.internal.map.MapView< K, V >.iterator().
Referenced by javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >.put(), and javolution.util.internal.map.MapView< K, V >.EntrySet.size().
split()
MapService<K, V> [] javolution.util.internal.map.MapView< K, V >.split (int n) inherited
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Implements javolution.util.function.Splittable< T >.
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 343 of file MapView.java.
{
         if (target == null) return new MapService[] { this }; // No split.
         MapService<K, V>[] subTargets = target.split(n);
         MapService<K, V>[] result = new MapService[subTargets.length];
         for (int i = 0; i < subTargets.length; i++) {
             MapView<K, V> copy = this.clone();
             copy.target = subTargets[i];
             result[i] = copy;
         }
         return result;
     }
References javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.split().
subMap()
SortedMapService<K, V> javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.subMap (K fromKey, K toKey)
Implements javolution.util.service.SortedMapService< K, V >.
Definition at line 60 of file UnmodifiableSortedMapImpl.java.
{
         return new SubSortedMapImpl<K,V>(this, fromKey, toKey);
     }
tailMap()
SortedMapService<K, V> javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.tailMap (K fromKey)
Implements javolution.util.service.SortedMapService< K, V >.
Definition at line 65 of file UnmodifiableSortedMapImpl.java.
{
         return new SubSortedMapImpl<K,V>(this, fromKey, null);
     }
target()
SortedMapService<K,V> javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.target () protected
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 76 of file UnmodifiableSortedMapImpl.java.
{
         return (SortedMapService<K,V>) super.target();
     }
Referenced by javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.comparator(), javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.firstKey(), javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.lastKey(), and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.UnmodifiableSortedMapImpl().
threadSafe()
SortedMapService<K, V> javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.threadSafe ()
Returns a thread-safe version of this service (used during parallel updates).
Reimplemented from javolution.util.internal.map.UnmodifiableMapImpl< K, V >.
Definition at line 70 of file UnmodifiableSortedMapImpl.java.
{
         return this;
     }
update() [1/2]
void javolution.util.internal.map.MapView< K, V >.update (Consumer< MapService< K, V >> action, MapService< K, V > view) inherited
Reimplemented in javolution.util.internal.map.ParallelMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Definition at line 361 of file MapView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.update(action, view);
         }
     }
References javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.update().
update() [2/2]
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
valueComparator()
Equality<? super V> javolution.util.internal.map.UnmodifiableMapImpl< K, V >.valueComparator () inherited
Returns the value comparator used for value equality.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 89 of file UnmodifiableMapImpl.java.
{
         return target().valueComparator();
     }
References javolution.util.internal.map.MapView< K, V >.target.
values()
CollectionService<V> javolution.util.internal.map.MapView< K, V >.values () inherited
Returns a collection view over the values of this map, the collection support value/entry removal but not adding new values.
Implements javolution.util.service.MapService< K, V >.
Definition at line 373 of file MapView.java.
{
         return new Values();
     }
Referenced by javolution.util.internal.map.MapView< K, V >.containsValue().
Member Data Documentation
serialVersionUID
final long javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.serialVersionUID = 0x600L static private
Definition at line 23 of file UnmodifiableSortedMapImpl.java.
The documentation for this class was generated from the following file:
UnmodifiableSortedMapImpl.java