Javolution 6.0.0 java: javolution.context.LogContext Class Reference
javolution.context.LogContext Class Reference abstract
Classes
enum Level
Public Member Functions
abstract void prefix (Object... prefixes)
abstract void setLevel (Level level)
abstract void suffix (Object... suffixes)
void exit ()
Static Public Member Functions
static void debug (Object... message)
static LogContext enter ()
static void error (Object... message)
static void info (Object... message)
static void warning (Object... message)
static AbstractContext current ()
static< T extends AbstractContext > T enter (Class< T > custom)
static void inherit (AbstractContext ctx)
Static Public Attributes
static final Configurable< Level > LEVEL
Protected Member Functions
LogContext ()
abstract void log (Level level, Object... message)
AbstractContext enterInner ()
AbstractContext getOuter ()
abstract AbstractContext inner ()
Static Protected Member Functions
static< T extends AbstractContext > T current (Class< T > type)
Static Private Member Functions
static LogContext currentLogContext ()
Private Attributes
AbstractContext outer
Static Private Attributes
static final ThreadLocal< AbstractContext > CURRENT = new ThreadLocal<AbstractContext>()
Detailed Description
Asynchronous logging context integrated with the OSGi logging framework. The logging back-end, or how the log entries are displayed, stored, or processed is unspecified but always performed asynchronously. When running outside OSGi, log messages are sent to System#out. Message formatting itself is always performed synchronously using the current TextContext.
Logging contexts support automatic prefixing/suffixing of any information relevant to the user/developer (thread info, user id, and so on). [code] void run() { LogContext ctx = LogContext.enter(); try { // Prefix the executing thread to any message being logged. ctx.prefix("[Thread: ", Thead.currentThread(), "] "); ... } finally { ctx.exit(); } }[/code]
Applications should separate messages elements by commas and not use String concatenations when calling log methods otherwise the concatenation is performed even when log events are filtered out. [code] LogContext ctx = LogContext.enter(); try { ctx.setLevel(Level.INFO); // Does not log debug messages. ... LogContext.debug("Index: ", index, " at maximum value"); // GOOD, no formatting performed ! LogContext.debug("Index: " + index + " at maximum value"); // BAD, formatting performed even though nothing is logged ! ... } finally { ctx.exit(); }[/code]
Author
Jean-Marie Dautelle
Version
6.0, July 21, 2013
See also
Understanding OSGi Logging
Definition at line 56 of file LogContext.java.
Constructor & Destructor Documentation
LogContext()
javolution.context.LogContext.LogContext () protected
Default constructor.
Definition at line 130 of file LogContext.java.
 {}
Member Function Documentation
current() [1/2]
static AbstractContext javolution.context.AbstractContext.current () static inherited
Returns the current context for the current thread or
null
if this thread has no context (default).
Definition at line 61 of file AbstractContext.java.
{
         return AbstractContext.CURRENT.get();
     }
References javolution.context.AbstractContext.CURRENT.
Referenced by javolution.context.LogContext.currentLogContext(), javolution.context.SecurityContext.currentSecurityContext(), javolution.text.TextContext.currentTextContext(), javolution.xml.XMLContext.currentXMLContext(), javolution.context.LocalContext.enter(), javolution.context.ConcurrentContext.enter(), and javolution.context.LocalContext.Parameter< T >.get().
current() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.current (Class< T > type) static protected inherited
Returns the current context of specified type or
null
if none.
Definition at line 69 of file AbstractContext.java.
{
         AbstractContext ctx = AbstractContext.CURRENT.get();
         while (ctx != null) {
             if (type.isInstance(ctx))
                 return (T) ctx;
             ctx = ctx.outer;
         }
         return null;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
currentLogContext()
static LogContext javolution.context.LogContext.currentLogContext () static private
Definition at line 120 of file LogContext.java.
{
         LogContext ctx = current(LogContext.class);
         if (ctx != null)
             return ctx;
         return OSGiServices.getLogContext();
     }
References javolution.context.AbstractContext.current(), and javolution.osgi.internal.OSGiServices.getLogContext().
Referenced by javolution.context.LogContext.debug(), javolution.context.LogContext.enter(), javolution.context.LogContext.error(), javolution.context.LogContext.info(), and javolution.context.LogContext.warning().
debug()
static void javolution.context.LogContext.debug (Object... message) static
Logs the specified debug message.
Definition at line 87 of file LogContext.java.
{
         currentLogContext().log(Level.DEBUG, message);
     }
References javolution.context.LogContext.currentLogContext(), javolution.context.LogContext.Level.DEBUG, and javolution.context.LogContext.log().
Referenced by javolution.lang.Configurable< javolution.context.LogContext.Level >.Configurable(), javolution.osgi.internal.ConfigurableListenerImpl.configurableInitialized(), javolution.osgi.internal.ConfigurableListenerImpl.configurableReconfigured(), javolution.lang.Initializer.initializeLoadedClasses(), javolution.lang.Initializer.loadClass(), and javolution.test.Perfometer< T >.printDetails().
enter() [1/2]
static LogContext javolution.context.LogContext.enter () static
Enters and returns a new log context instance.
Definition at line 94 of file LogContext.java.
{
         return (LogContext) currentLogContext().enterInner();
     }
References javolution.context.LogContext.currentLogContext(), and javolution.context.AbstractContext.enterInner().
enter() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.enter (Class< T > custom) static inherited
Enters the scope of a custom context. This method raises a SecurityException if the permission to enter contexts of the specified class is not granted. For example, the following disallow entering any custom context. [code] SecurityContext ctx = SecurityContext.enter(); try { ctx.revoke(new SecurityContext.Permission(AbstractContext.class, "enter")); ... // Cannot enter any custom context. } finally { ctx.exit(); // Back to previous security settings. }[/code]
Parameters
custom the custom context to enter.
Exceptions
IllegalArgumentException if the specified class default constructor cannot be instantiated.
SecurityException if
SecurityContext.Permission(custom, "enter")
is not granted.
See also
SecurityContext.Permission
Definition at line 101 of file AbstractContext.java.
{
         SecurityContext.check(new Permission<T>(custom, "enter"));
         try {
             return (T) custom.newInstance().enterInner();
         } catch (InstantiationException e) {
             throw new IllegalArgumentException(
                     "Cannot instantiate instance of " + custom, e);
         } catch (IllegalAccessException e) {
             throw new IllegalArgumentException("Cannot access " + custom, e);
         }
     }
References javolution.context.SecurityContext.check().
enterInner()
AbstractContext javolution.context.AbstractContext.enterInner () protected inherited
Enters the scope of an inner context which becomes the current context; the previous current context becomes the outer of this context.
Returns
the inner context entered.
Definition at line 141 of file AbstractContext.java.
{
         AbstractContext inner = inner();
         inner.outer = AbstractContext.CURRENT.get();
         AbstractContext.CURRENT.set(inner);
         return inner;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
Referenced by javolution.xml.XMLContext.enter(), javolution.text.TextContext.enter(), javolution.context.LogContext.enter(), javolution.context.LocalContext.enter(), javolution.context.SecurityContext.enter(), and javolution.context.ConcurrentContext.enter().
error()
static void javolution.context.LogContext.error (Object... message) static
Logs the specified error message (which may include any Throwable instance).
Definition at line 102 of file LogContext.java.
{
         currentLogContext().log(Level.ERROR, message);
     }
References javolution.context.LogContext.currentLogContext(), javolution.context.LogContext.Level.ERROR, and javolution.context.LogContext.log().
Referenced by javolution.lang.Initializer.initializeLoadedClasses().
exit()
void javolution.context.AbstractContext.exit () inherited
Exits the scope of this context; the outer of this context becomes
the current context.
Exceptions
IllegalStateException if this context is not the current context.
Reimplemented in javolution.context.ConcurrentContext, and javolution.context.internal.ConcurrentContextImpl.
Definition at line 155 of file AbstractContext.java.
{
         if (this != AbstractContext.CURRENT.get())
             throw new IllegalStateException(
                     "This context is not the current context");
         AbstractContext.CURRENT.set(outer);
         outer = null;
     }
References javolution.context.AbstractContext.CURRENT.
getOuter()
AbstractContext javolution.context.AbstractContext.getOuter () protected inherited
Returns the outer context of this context or
null
if this context has no outer context.
Definition at line 167 of file AbstractContext.java.
{
         return outer;
     }
info()
static void javolution.context.LogContext.info (Object... message) static
Logs the specified info message.
Definition at line 109 of file LogContext.java.
{
         currentLogContext().log(Level.INFO, message);
     }
References javolution.context.LogContext.currentLogContext(), javolution.context.LogContext.Level.INFO, and javolution.context.LogContext.log().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.increaseDataBuffer(), javolution.xml.internal.stream.XMLStreamReaderImpl.increaseStack(), and javolution.test.Perfometer< T >.print().
inherit()
static void javolution.context.AbstractContext.inherit (AbstractContext ctx) static inherited
Inherits the specified context which becomes the context of the current thread. This method is particularly useful when creating new threads to make them inherits from the context stack of the parent thread. [code] //Spawns a new thread inheriting the context of the current thread. MyThread myThread = new MyThread(); myThread.inherited = AbstractContext.current(); myThread.start(); ... class MyThread extends Thread { AbstractContext inherited; public void run() { AbstractContext.inherit(inherited); // Sets current context. ... } }[/code]
Definition at line 131 of file AbstractContext.java.
{
         CURRENT.set(ctx);
     }
Referenced by javolution.context.internal.ConcurrentThreadImpl.run().
inner()
abstract AbstractContext javolution.context.AbstractContext.inner () abstract protected inherited
Returns a new inner instance of this context inheriting the properties of this context. The new instance can be configured independently from its parent.
Reimplemented in javolution.context.internal.ConcurrentContextImpl, javolution.text.internal.TextContextImpl, javolution.context.internal.LogContextImpl, javolution.context.internal.SecurityContextImpl, javolution.xml.internal.XMLContextImpl, and javolution.context.internal.LocalContextImpl.
log()
abstract void javolution.context.LogContext.log (Level level, Object... message) abstract protected
Logs the specified message at the specified level.
Referenced by javolution.context.LogContext.debug(), javolution.context.LogContext.error(), javolution.context.LogContext.info(), and javolution.context.LogContext.warning().
prefix()
abstract void javolution.context.LogContext.prefix (Object... prefixes) abstract
Prefixes all messages being logged by the specified prefixes (prefixing existing prefixes if any).
Reimplemented in javolution.context.internal.LogContextImpl.
setLevel()
abstract void javolution.context.LogContext.setLevel (Level level) abstract
Set the logging level, messages below that level are not logged.
suffix()
abstract void javolution.context.LogContext.suffix (Object... suffixes) abstract
Suffixes all messages being logged by the specified suffixes (suffixing existing suffixes if any).
Reimplemented in javolution.context.internal.LogContextImpl.
warning()
static void javolution.context.LogContext.warning (Object... message) static
Logs the specified warning message.
Definition at line 116 of file LogContext.java.
{
         currentLogContext().log(Level.WARNING, message);
     }
References javolution.context.LogContext.currentLogContext(), javolution.context.LogContext.log(), and javolution.context.LogContext.Level.WARNING.
Referenced by javolution.text.internal.TextContextImpl.searchFormat().
Member Data Documentation
CURRENT
final ThreadLocal<AbstractContext> javolution.context.AbstractContext.CURRENT = new ThreadLocal<AbstractContext>() static private inherited
Holds the last context entered (thread-local).
Definition at line 45 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), javolution.context.AbstractContext.enterInner(), and javolution.context.AbstractContext.exit().
LEVEL
final Configurable<Level> javolution.context.LogContext.LEVEL static
Initial value:
= new Configurable<Level>() {
        @Override
        protected Level getDefault() {
            return Level.DEBUG;
        }
        @Override
        public Level parse(String str) {
            return Level.valueOf(str);
        }
    }
Holds the default logging level (DEBUG). This level is configurable. For example, running with the option -Djavolution.context.LogContextLEVEL=WARNING
causes the debug/info not to be logged.
Definition at line 73 of file LogContext.java.
Referenced by javolution.context.internal.LogContextImpl.currentLevel().
outer
AbstractContext javolution.context.AbstractContext.outer private inherited
Holds the outer context or
null
if none (top context).
Definition at line 50 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), and javolution.context.AbstractContext.enterInner().
The documentation for this class was generated from the following file:
LogContext.java