Javolution 6.0.0 java: javolution.util.internal.map.AtomicMapImpl< K, V > Class Template Reference
javolution.util.internal.map.AtomicMapImpl< K, V > Class Template Reference
Classes
class IteratorImpl
Public Member Functions
AtomicMapImpl (MapService< K, V > target)
synchronized void clear ()
synchronized AtomicMapImpl< K, V > clone ()
boolean containsKey (Object key)
boolean containsValue (Object value)
V get (Object key)
boolean isEmpty ()
Iterator< Entry< K, V > > iterator ()
Equality<? super K > keyComparator ()
synchronized V put (K key, V value)
synchronized void putAll (Map<? extends K, ? extends V > m)
synchronized V putIfAbsent (K key, V value)
synchronized V remove (Object key)
synchronized boolean remove (Object key, Object value)
synchronized V replace (K key, V value)
synchronized boolean replace (K key, V oldValue, V newValue)
int size ()
MapService< K, V >[] split (int n)
MapService< K, V > threadSafe ()
synchronized void update (Consumer< MapService< K, V >> action, MapService< K, V > view)
Equality<? super V > valueComparator ()
SetService< Entry< K, V > > entrySet ()
SetService< K > keySet ()
void perform (Consumer< MapService< K, V >> action, MapService< K, V > view)
void perform (Consumer< T > action, T part)
void update (Consumer< T > action, T part)
CollectionService< V > values ()
Protected Member Functions
MapService< K, V > cloneTarget ()
MapService< K, V > targetView ()
final boolean updateInProgress ()
MapService< K, V > target ()
Protected Attributes
volatile MapService< K, V > immutable
transient Thread updatingThread
Private Attributes
MapService< K, V > target
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
An atomic view over a map (copy-on-write).
Definition at line 21 of file AtomicMapImpl.java.
Constructor & Destructor Documentation
AtomicMapImpl()
javolution.util.internal.map.AtomicMapImpl< K, V >.AtomicMapImpl (MapService< K, V > target)
Definition at line 51 of file AtomicMapImpl.java.
{
         super(target);
         this.immutable = cloneTarget();
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), and javolution.util.internal.map.MapView< K, V >.target.
Member Function Documentation
clear()
synchronized void javolution.util.internal.map.AtomicMapImpl< K, V >.clear ()
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 57 of file AtomicMapImpl.java.
{
         clear();
         if (!updateInProgress()) {
             immutable = cloneTarget();
         }
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.AtomicMapImpl< K, V >.immutable, and javolution.util.internal.map.AtomicMapImpl< K, V >.updateInProgress().
clone()
synchronized AtomicMapImpl<K, V> javolution.util.internal.map.AtomicMapImpl< K, V >.clone ()
Returns a copy of this map; updates of the copy should not impact the original.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 65 of file AtomicMapImpl.java.
{
         AtomicMapImpl<K, V> copy = (AtomicMapImpl<K, V>) super.clone();
         copy.updatingThread = null;
         return copy;
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.clone(), and javolution.util.internal.map.AtomicMapImpl< K, V >.updatingThread.
Referenced by javolution.util.internal.map.AtomicMapImpl< K, V >.clone().
cloneTarget()
MapService<K, V> javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget () protected
Returns a clone copy of target.
Definition at line 183 of file AtomicMapImpl.java.
{
         try {
             return target().clone();
         } catch (CloneNotSupportedException e) {
             throw new Error("Cannot happen since target is Cloneable.");
         }
     }
References javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.AtomicMapImpl< K, V >.AtomicMapImpl(), javolution.util.internal.map.AtomicMapImpl< K, V >.clear(), javolution.util.internal.map.AtomicMapImpl< K, V >.put(), javolution.util.internal.map.AtomicMapImpl< K, V >.putAll(), javolution.util.internal.map.AtomicMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.AtomicMapImpl< K, V >.remove(), javolution.util.internal.map.AtomicMapImpl< K, V >.replace(), and javolution.util.internal.map.AtomicMapImpl< K, V >.update().
containsKey()
boolean javolution.util.internal.map.AtomicMapImpl< K, V >.containsKey (Object key)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 72 of file AtomicMapImpl.java.
{
         return targetView().containsKey(key);
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.targetView().
containsValue()
boolean javolution.util.internal.map.AtomicMapImpl< K, V >.containsValue (Object value)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 77 of file AtomicMapImpl.java.
{
         return targetView().containsValue(value);
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.targetView().
entrySet()
SetService<Entry<K, V> > javolution.util.internal.map.MapView< K, V >.entrySet () inherited
Returns a set view over the entries of this map. The set support adding/removing entries. Two entries are considered equals if they have the same key regardless of their values.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 253 of file MapView.java.
{
         return new EntrySet();
     }
Referenced by javolution.util.internal.map.MapView< K, V >.KeySet.KeySet(), and javolution.util.internal.map.MapView< K, V >.Values.Values().
get()
V javolution.util.internal.map.AtomicMapImpl< K, V >.get (Object key)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 82 of file AtomicMapImpl.java.
{
         return targetView().get(key);
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.targetView().
isEmpty()
boolean javolution.util.internal.map.AtomicMapImpl< K, V >.isEmpty ()
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 87 of file AtomicMapImpl.java.
{
         return targetView().isEmpty();
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.targetView().
iterator()
Iterator<Entry<K, V> > javolution.util.internal.map.AtomicMapImpl< K, V >.iterator ()
Returns an iterator over this map entries.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 92 of file AtomicMapImpl.java.
{
         return new IteratorImpl();
     }
keyComparator()
Equality<? super K> javolution.util.internal.map.AtomicMapImpl< K, V >.keyComparator ()
Returns the key comparator used for key equality or order if the map is sorted.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 97 of file AtomicMapImpl.java.
{
         return targetView().keyComparator();
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.targetView().
keySet()
SetService<K> javolution.util.internal.map.MapView< K, V >.keySet () inherited
Returns a set view over the key of this map, the set support adding new key for which the value is automatically
null
.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 272 of file MapView.java.
{
         return new KeySet();
     }
Referenced by javolution.util.FastSet< Index >.FastSet().
perform() [1/2]
void javolution.util.internal.map.MapView< K, V >.perform (Consumer< MapService< K, V >> action, MapService< K, V > view) inherited
Reimplemented in javolution.util.internal.map.ParallelMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Definition at line 277 of file MapView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
References javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.perform().
perform() [2/2]
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
put()
synchronized V javolution.util.internal.map.AtomicMapImpl< K, V >.put (K key, V value)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 102 of file AtomicMapImpl.java.
{
         V v = target().put(key, value);
         if (!updateInProgress()) immutable = cloneTarget();
         return v;
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.AtomicMapImpl< K, V >.immutable, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.map.AtomicMapImpl< K, V >.updateInProgress().
putAll()
synchronized void javolution.util.internal.map.AtomicMapImpl< K, V >.putAll (Map<? extends K, ? extends V > m)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 109 of file AtomicMapImpl.java.
{
         target().putAll(m);
         if (!updateInProgress()) immutable = cloneTarget();
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.AtomicMapImpl< K, V >.immutable, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.map.AtomicMapImpl< K, V >.updateInProgress().
putIfAbsent()
synchronized V javolution.util.internal.map.AtomicMapImpl< K, V >.putIfAbsent (K key, V value)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 115 of file AtomicMapImpl.java.
{
         V v = target().putIfAbsent(key, value);
         if (!updateInProgress()) immutable = cloneTarget();
         return v;
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.AtomicMapImpl< K, V >.immutable, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.map.AtomicMapImpl< K, V >.updateInProgress().
remove() [1/2]
synchronized V javolution.util.internal.map.AtomicMapImpl< K, V >.remove (Object key)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 122 of file AtomicMapImpl.java.
{
         V v = target().remove(key);
         if (!updateInProgress()) immutable = cloneTarget();
         return v;
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.AtomicMapImpl< K, V >.immutable, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.map.AtomicMapImpl< K, V >.updateInProgress().
Referenced by javolution.util.internal.map.AtomicMapImpl< K, V >.IteratorImpl.remove().
remove() [2/2]
synchronized boolean javolution.util.internal.map.AtomicMapImpl< K, V >.remove (Object key, Object value)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 129 of file AtomicMapImpl.java.
{
         boolean changed = target().remove(key, value);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.AtomicMapImpl< K, V >.immutable, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.map.AtomicMapImpl< K, V >.updateInProgress().
replace() [1/2]
synchronized boolean javolution.util.internal.map.AtomicMapImpl< K, V >.replace (K key, V oldValue, V newValue)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 143 of file AtomicMapImpl.java.
{
         boolean changed = target().replace(key, oldValue, newValue);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.AtomicMapImpl< K, V >.immutable, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.map.AtomicMapImpl< K, V >.updateInProgress().
replace() [2/2]
synchronized V javolution.util.internal.map.AtomicMapImpl< K, V >.replace (K key, V value)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 136 of file AtomicMapImpl.java.
{
         V v = target().replace(key, value);
         if (!updateInProgress()) immutable = cloneTarget();
         return v;
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.AtomicMapImpl< K, V >.immutable, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.map.AtomicMapImpl< K, V >.updateInProgress().
size()
int javolution.util.internal.map.AtomicMapImpl< K, V >.size ()
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 150 of file AtomicMapImpl.java.
                       {
         return targetView().size();
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.targetView().
split()
MapService<K, V> [] javolution.util.internal.map.AtomicMapImpl< K, V >.split (int n)
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 156 of file AtomicMapImpl.java.
                                            { // Split not supported.
         return new MapService[] { this };
     }
target()
MapService<K, V> javolution.util.internal.map.MapView< K, V >.target () protected inherited
Returns the actual target
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 378 of file MapView.java.
{
         return target;
     }
References javolution.util.internal.map.MapView< K, V >.target.
targetView()
MapService<K, V> javolution.util.internal.map.AtomicMapImpl< K, V >.targetView () protected
Returns either the immutable target or the actual target if updating thread.
Reimplemented in javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >.
Definition at line 193 of file AtomicMapImpl.java.
{
         return ((updatingThread == null) || (updatingThread != Thread.currentThread()))
                 ? immutable : target();
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.immutable, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.map.AtomicMapImpl< K, V >.updatingThread.
Referenced by javolution.util.internal.map.AtomicMapImpl< K, V >.containsKey(), javolution.util.internal.map.AtomicMapImpl< K, V >.containsValue(), javolution.util.internal.map.AtomicMapImpl< K, V >.get(), javolution.util.internal.map.AtomicMapImpl< K, V >.isEmpty(), javolution.util.internal.map.AtomicMapImpl< K, V >.keyComparator(), javolution.util.internal.map.AtomicMapImpl< K, V >.size(), and javolution.util.internal.map.AtomicMapImpl< K, V >.valueComparator().
threadSafe()
MapService<K, V> javolution.util.internal.map.AtomicMapImpl< K, V >.threadSafe ()
Returns a thread-safe version of this service (used during parallel updates).
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Reimplemented in javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >.
Definition at line 161 of file AtomicMapImpl.java.
{
         return this;
     }
update() [1/2]
synchronized void javolution.util.internal.map.AtomicMapImpl< K, V >.update (Consumer< MapService< K, V >> action, MapService< K, V > view)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 166 of file AtomicMapImpl.java.
{
         updatingThread = Thread.currentThread(); // Update in progress.
         try {
             target().update(action, view); // No copy performed.
         } finally {
             updatingThread = null;
             immutable = cloneTarget(); // One single copy !
         }
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.AtomicMapImpl< K, V >.immutable, javolution.util.internal.map.MapView< K, V >.target, and javolution.util.internal.map.AtomicMapImpl< K, V >.updatingThread.
update() [2/2]
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
updateInProgress()
final boolean javolution.util.internal.map.AtomicMapImpl< K, V >.updateInProgress () protected
Indicates if the current thread is doing an atomic update.
Definition at line 200 of file AtomicMapImpl.java.
{
         return updatingThread == Thread.currentThread();
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.updatingThread.
Referenced by javolution.util.internal.map.AtomicMapImpl< K, V >.clear(), javolution.util.internal.map.AtomicMapImpl< K, V >.put(), javolution.util.internal.map.AtomicMapImpl< K, V >.putAll(), javolution.util.internal.map.AtomicMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.AtomicMapImpl< K, V >.remove(), and javolution.util.internal.map.AtomicMapImpl< K, V >.replace().
valueComparator()
Equality<? super V> javolution.util.internal.map.AtomicMapImpl< K, V >.valueComparator ()
Returns the value comparator used for value equality.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 178 of file AtomicMapImpl.java.
{
         return targetView().valueComparator();
     }
References javolution.util.internal.map.AtomicMapImpl< K, V >.targetView().
values()
CollectionService<V> javolution.util.internal.map.MapView< K, V >.values () inherited
Returns a collection view over the values of this map, the collection support value/entry removal but not adding new values.
Implements javolution.util.service.MapService< K, V >.
Definition at line 373 of file MapView.java.
{
         return new Values();
     }
Referenced by javolution.util.internal.map.MapView< K, V >.containsValue().
Member Data Documentation
immutable
volatile MapService<K, V> javolution.util.internal.map.AtomicMapImpl< K, V >.immutable protected
Definition at line 48 of file AtomicMapImpl.java.
Referenced by javolution.util.internal.map.AtomicMapImpl< K, V >.clear(), javolution.util.internal.map.AtomicMapImpl< K, V >.put(), javolution.util.internal.map.AtomicMapImpl< K, V >.putAll(), javolution.util.internal.map.AtomicMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.AtomicMapImpl< K, V >.remove(), javolution.util.internal.map.AtomicMapImpl< K, V >.replace(), javolution.util.internal.map.AtomicMapImpl< K, V >.targetView(), and javolution.util.internal.map.AtomicMapImpl< K, V >.update().
serialVersionUID
final long javolution.util.internal.map.AtomicMapImpl< K, V >.serialVersionUID = 0x600L static private
Definition at line 47 of file AtomicMapImpl.java.
target
MapService<K, V> javolution.util.internal.map.MapView< K, V >.target private inherited
Reimplemented in javolution.util.internal.map.sorted.SortedMapView< K, V >, javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >, and javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.
Definition at line 213 of file MapView.java.
Referenced by javolution.util.internal.map.AtomicMapImpl< K, V >.AtomicMapImpl(), javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >.AtomicSortedMapImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.clear(), javolution.util.internal.map.MapView< K, V >.clone(), javolution.util.internal.map.AtomicMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.SharedMapImpl< K, V >.cloneTarget(), javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >.comparator(), javolution.util.internal.map.SequentialMapImpl< K, V >.containsKey(), javolution.util.internal.map.ParallelMapImpl< K, V >.containsKey(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.containsKey(), javolution.util.internal.map.SharedMapImpl< K, V >.containsKey(), javolution.util.internal.map.SharedMapImpl< K, V >.containsValue(), javolution.util.internal.map.SequentialMapImpl< K, V >.get(), javolution.util.internal.map.ParallelMapImpl< K, V >.get(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.get(), javolution.util.internal.map.SharedMapImpl< K, V >.get(), javolution.util.internal.map.SharedMapImpl< K, V >.isEmpty(), javolution.util.internal.map.SequentialMapImpl< K, V >.iterator(), javolution.util.internal.map.ParallelMapImpl< K, V >.iterator(), javolution.util.internal.map.SequentialMapImpl< K, V >.keyComparator(), javolution.util.internal.map.ParallelMapImpl< K, V >.keyComparator(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.keyComparator(), javolution.util.internal.map.SharedMapImpl< K, V >.keyComparator(), javolution.util.internal.map.MapView< K, V >.MapView(), javolution.util.internal.map.ParallelMapImpl< K, V >.ParallelMapImpl(), javolution.util.internal.map.ParallelMapImpl< K, V >.perform(), javolution.util.internal.map.MapView< K, V >.perform(), javolution.util.internal.map.SequentialMapImpl< K, V >.put(), javolution.util.internal.map.ParallelMapImpl< K, V >.put(), javolution.util.internal.map.AtomicMapImpl< K, V >.put(), javolution.util.internal.map.SharedMapImpl< K, V >.put(), javolution.util.internal.map.AtomicMapImpl< K, V >.putAll(), javolution.util.internal.map.SharedMapImpl< K, V >.putAll(), javolution.util.internal.map.AtomicMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.SharedMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.SequentialMapImpl< K, V >.remove(), javolution.util.internal.map.ParallelMapImpl< K, V >.remove(), javolution.util.internal.map.AtomicMapImpl< K, V >.remove(), javolution.util.internal.map.SharedMapImpl< K, V >.remove(), javolution.util.internal.map.AtomicMapImpl< K, V >.replace(), javolution.util.internal.map.SharedMapImpl< K, V >.replace(), javolution.util.internal.map.SequentialMapImpl< K, V >.SequentialMapImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.SharedMapImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.size(), javolution.util.internal.map.SharedMapImpl< K, V >.split(), javolution.util.internal.map.MapView< K, V >.split(), javolution.util.internal.map.MapView< K, V >.target(), javolution.util.internal.map.AtomicMapImpl< K, V >.targetView(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.UnmodifiableMapImpl(), javolution.util.internal.map.ParallelMapImpl< K, V >.update(), javolution.util.internal.map.AtomicMapImpl< K, V >.update(), javolution.util.internal.map.MapView< K, V >.update(), javolution.util.internal.map.SequentialMapImpl< K, V >.valueComparator(), javolution.util.internal.map.UnmodifiableMapImpl< K, V >.valueComparator(), javolution.util.internal.map.ParallelMapImpl< K, V >.valueComparator(), and javolution.util.internal.map.SharedMapImpl< K, V >.valueComparator().
updatingThread
transient Thread javolution.util.internal.map.AtomicMapImpl< K, V >.updatingThread protected
Definition at line 49 of file AtomicMapImpl.java.
Referenced by javolution.util.internal.map.AtomicMapImpl< K, V >.clone(), javolution.util.internal.map.AtomicMapImpl< K, V >.targetView(), javolution.util.internal.map.AtomicMapImpl< K, V >.update(), and javolution.util.internal.map.AtomicMapImpl< K, V >.updateInProgress().
The documentation for this class was generated from the following file:
AtomicMapImpl.java