Javolution 6.0.0 java: javolution.context.internal.ConcurrentContextImpl Class Reference
javolution.context.internal.ConcurrentContextImpl Class Reference
Public Member Functions
ConcurrentContextImpl ()
ConcurrentContextImpl (ConcurrentContextImpl parent)
synchronized void completed (Throwable error)
void execute (Runnable logic)
synchronized void exit ()
int getConcurrency ()
void setConcurrency (int concurrency)
Static Public Member Functions
static ConcurrentContext enter ()
static< T extends AbstractContext > T enter (Class< T > custom)
static void execute (Runnable... logics)
static AbstractContext current ()
static void inherit (AbstractContext ctx)
Static Public Attributes
static final Configurable< Integer > CONCURRENCY
Protected Member Functions
ConcurrentContext inner ()
AbstractContext enterInner ()
AbstractContext getOuter ()
Static Protected Member Functions
static< T extends AbstractContext > T current (Class< T > type)
Private Attributes
int completedCount
Throwable error
int initiatedCount
final ConcurrentContextImpl parent
ConcurrentThreadImpl[] threads
AbstractContext outer
Static Private Attributes
static final ThreadLocal< AbstractContext > CURRENT = new ThreadLocal<AbstractContext>()
Detailed Description
Holds the default implementation of ConcurrentContext.
Definition at line 17 of file ConcurrentContextImpl.java.
Constructor & Destructor Documentation
ConcurrentContextImpl() [1/2]
javolution.context.internal.ConcurrentContextImpl.ConcurrentContextImpl ()
Default constructor (root).
Definition at line 29 of file ConcurrentContextImpl.java.
{
         this.parent = null;
         int nbThreads = ConcurrentContext.CONCURRENCY.get();
         threads = new ConcurrentThreadImpl[nbThreads];
         for (int i = 0; i < nbThreads; i++) {
             threads[i] = new ConcurrentThreadImpl();
             threads[i].start();
         }
     }
References javolution.context.ConcurrentContext.CONCURRENCY, javolution.lang.Configurable< T >.get(), and javolution.context.internal.ConcurrentContextImpl.threads.
Referenced by javolution.context.internal.ConcurrentContextImpl.inner().
ConcurrentContextImpl() [2/2]
javolution.context.internal.ConcurrentContextImpl.ConcurrentContextImpl (ConcurrentContextImpl parent)
Inner implementation.
Definition at line 42 of file ConcurrentContextImpl.java.
{
         this.parent = parent;
         this.threads = parent.threads; // Inherit threads from parents.
     }
References javolution.context.internal.ConcurrentContextImpl.parent, and javolution.context.internal.ConcurrentContextImpl.threads.
Member Function Documentation
completed()
synchronized void javolution.context.internal.ConcurrentContextImpl.completed (Throwable error)
Definition at line 48 of file ConcurrentContextImpl.java.
{
         if (error != null) {
             this.error = error;
         }
         completedCount++;
         this.notify();
     }
References javolution.context.internal.ConcurrentContextImpl.completedCount, and javolution.context.internal.ConcurrentContextImpl.error.
Referenced by javolution.context.internal.ConcurrentThreadImpl.run().
current() [1/2]
static AbstractContext javolution.context.AbstractContext.current () static inherited
Returns the current context for the current thread or
null
if this thread has no context (default).
Definition at line 61 of file AbstractContext.java.
{
         return AbstractContext.CURRENT.get();
     }
References javolution.context.AbstractContext.CURRENT.
Referenced by javolution.context.LogContext.currentLogContext(), javolution.context.SecurityContext.currentSecurityContext(), javolution.text.TextContext.currentTextContext(), javolution.xml.XMLContext.currentXMLContext(), javolution.context.LocalContext.enter(), javolution.context.ConcurrentContext.enter(), and javolution.context.LocalContext.Parameter< T >.get().
current() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.current (Class< T > type) static protected inherited
Returns the current context of specified type or
null
if none.
Definition at line 69 of file AbstractContext.java.
{
         AbstractContext ctx = AbstractContext.CURRENT.get();
         while (ctx != null) {
             if (type.isInstance(ctx))
                 return (T) ctx;
             ctx = ctx.outer;
         }
         return null;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
enter() [1/2]
static ConcurrentContext javolution.context.ConcurrentContext.enter () static inherited
Enters and returns a new concurrent context instance.
Definition at line 186 of file ConcurrentContext.java.
{
         ConcurrentContext ctx = current(ConcurrentContext.class);
         if (ctx == null) { // Root.
             ctx = OSGiServices.getConcurrentContext();
         }
         return (ConcurrentContext) ctx.enterInner();
     }
References javolution.context.AbstractContext.current(), javolution.context.AbstractContext.enterInner(), and javolution.osgi.internal.OSGiServices.getConcurrentContext().
Referenced by javolution.context.ConcurrentContext.execute(), javolution.util.internal.map.ParallelMapImpl< K, V >.perform(), javolution.util.internal.collection.ParallelCollectionImpl< E >.perform(), javolution.util.internal.map.ParallelMapImpl< K, V >.update(), and javolution.util.internal.collection.ParallelCollectionImpl< E >.update().
enter() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.enter (Class< T > custom) static inherited
Enters the scope of a custom context. This method raises a SecurityException if the permission to enter contexts of the specified class is not granted. For example, the following disallow entering any custom context. [code] SecurityContext ctx = SecurityContext.enter(); try { ctx.revoke(new SecurityContext.Permission(AbstractContext.class, "enter")); ... // Cannot enter any custom context. } finally { ctx.exit(); // Back to previous security settings. }[/code]
Parameters
custom the custom context to enter.
Exceptions
IllegalArgumentException if the specified class default constructor cannot be instantiated.
SecurityException if
SecurityContext.Permission(custom, "enter")
is not granted.
See also
SecurityContext.Permission
Definition at line 101 of file AbstractContext.java.
{
         SecurityContext.check(new Permission<T>(custom, "enter"));
         try {
             return (T) custom.newInstance().enterInner();
         } catch (InstantiationException e) {
             throw new IllegalArgumentException(
                     "Cannot instantiate instance of " + custom, e);
         } catch (IllegalAccessException e) {
             throw new IllegalArgumentException("Cannot access " + custom, e);
         }
     }
References javolution.context.SecurityContext.check().
enterInner()
AbstractContext javolution.context.AbstractContext.enterInner () protected inherited
Enters the scope of an inner context which becomes the current context; the previous current context becomes the outer of this context.
Returns
the inner context entered.
Definition at line 141 of file AbstractContext.java.
{
         AbstractContext inner = inner();
         inner.outer = AbstractContext.CURRENT.get();
         AbstractContext.CURRENT.set(inner);
         return inner;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
Referenced by javolution.xml.XMLContext.enter(), javolution.text.TextContext.enter(), javolution.context.LogContext.enter(), javolution.context.LocalContext.enter(), javolution.context.SecurityContext.enter(), and javolution.context.ConcurrentContext.enter().
execute() [1/2]
void javolution.context.internal.ConcurrentContextImpl.execute (Runnable logic)
Executes the specified logic by a concurrent thread if one available; otherwise the logic is executed by the current thread. Any exception or error occurring during the concurrent execution is propagated to the current thread upon exit of the concurrent context.
Parameters
logic the logic to be executed concurrently when possible.
Reimplemented from javolution.context.ConcurrentContext.
Definition at line 57 of file ConcurrentContextImpl.java.
{
         // Find a thread not busy.
         for (ConcurrentThreadImpl thread : threads) {
             if (thread.execute(logic, this)) {
                 initiatedCount++;
                 return;
             }
         }
         // Executes by current thread.
         try {
             logic.run();
         } catch (Throwable e) {
             error = e;
         }
     }
References javolution.context.internal.ConcurrentContextImpl.error, javolution.context.internal.ConcurrentContextImpl.initiatedCount, and javolution.context.internal.ConcurrentContextImpl.threads.
execute() [2/2]
static void javolution.context.ConcurrentContext.execute (Runnable... logics) static inherited
Convenience method to executes the specified logics concurrently. This method is equivalent to: [code] ConcurrentContext ctx = ConcurrentContext.enter(); try { ctx.execute(logics[0]); ctx.execute(logics[1]); ... } finally { ctx.exit(); }[/code]
Parameters
logics the logics to execute concurrently if possible.
Definition at line 209 of file ConcurrentContext.java.
{
         ConcurrentContext ctx = ConcurrentContext.enter();
         try {
             for (Runnable logic : logics) {
                 ctx.execute(logic);
             }
         } finally {
             ctx.exit();
         }
     }
References javolution.context.ConcurrentContext.enter(), javolution.context.ConcurrentContext.execute(), and javolution.context.ConcurrentContext.exit().
Referenced by javolution.context.ConcurrentContext.execute(), javolution.util.internal.map.ParallelMapImpl< K, V >.perform(), javolution.util.internal.collection.ParallelCollectionImpl< E >.perform(), javolution.util.internal.map.ParallelMapImpl< K, V >.update(), and javolution.util.internal.collection.ParallelCollectionImpl< E >.update().
exit()
synchronized void javolution.context.internal.ConcurrentContextImpl.exit ()
Exits the scope of this concurrent context; this method blocks until all the concurrent executions are completed.
Exceptions
RuntimeException re-exports any exception raised during concurrent executions.
Error re-exports any error raised during concurrent executions.
IllegalStateException if this context is not the current context.
Reimplemented from javolution.context.ConcurrentContext.
Definition at line 74 of file ConcurrentContextImpl.java.
{
         super.exit();
         try {
             while (initiatedCount != completedCount) {
                 this.wait();
             }
         } catch (InterruptedException ex) {
             this.error = ex;
         }
         if (error == null)
             return; // Everything fine.
         if (error instanceof RuntimeException)
             throw (RuntimeException) error;
         if (error instanceof Error)
             throw (Error) error;
         throw new RuntimeException(error);
     }
References javolution.context.internal.ConcurrentContextImpl.completedCount, javolution.context.internal.ConcurrentContextImpl.error, and javolution.context.internal.ConcurrentContextImpl.initiatedCount.
getConcurrency()
int javolution.context.internal.ConcurrentContextImpl.getConcurrency ()
Returns the current concurrency which is basically the number of concurrent threads authorized to do concurrent work (on top of all others threads of course).
Reimplemented from javolution.context.ConcurrentContext.
Definition at line 93 of file ConcurrentContextImpl.java.
{
         return threads.length;
     }
References javolution.context.internal.ConcurrentContextImpl.threads.
getOuter()
AbstractContext javolution.context.AbstractContext.getOuter () protected inherited
Returns the outer context of this context or
null
if this context has no outer context.
Definition at line 167 of file AbstractContext.java.
{
         return outer;
     }
inherit()
static void javolution.context.AbstractContext.inherit (AbstractContext ctx) static inherited
Inherits the specified context which becomes the context of the current thread. This method is particularly useful when creating new threads to make them inherits from the context stack of the parent thread. [code] //Spawns a new thread inheriting the context of the current thread. MyThread myThread = new MyThread(); myThread.inherited = AbstractContext.current(); myThread.start(); ... class MyThread extends Thread { AbstractContext inherited; public void run() { AbstractContext.inherit(inherited); // Sets current context. ... } }[/code]
Definition at line 131 of file AbstractContext.java.
{
         CURRENT.set(ctx);
     }
Referenced by javolution.context.internal.ConcurrentThreadImpl.run().
inner()
ConcurrentContext javolution.context.internal.ConcurrentContextImpl.inner () protected
Returns a new inner instance of this context inheriting the properties of this context. The new instance can be configured independently from its parent.
Reimplemented from javolution.context.AbstractContext.
Definition at line 109 of file ConcurrentContextImpl.java.
{
         return new ConcurrentContextImpl(this);
     }
References javolution.context.internal.ConcurrentContextImpl.ConcurrentContextImpl().
setConcurrency()
void javolution.context.internal.ConcurrentContextImpl.setConcurrency (int concurrency)
Sets the maximum concurrency. Setting a value greater than the current concurrency has no effect (concurrency can only be reduced).
Reimplemented from javolution.context.ConcurrentContext.
Definition at line 98 of file ConcurrentContextImpl.java.
{
         // The setting of the concurrency can only reduce the number
         // of threads available in the context.
         int nbThreads = MathLib.min(parent.threads.length, concurrency);
         threads = new ConcurrentThreadImpl[nbThreads];
         for (int i = 0; i < nbThreads; i++) { // Reused from parent threads.
             threads[i] = parent.threads[i];
         }
     }
References javolution.lang.MathLib.min(), javolution.context.internal.ConcurrentContextImpl.parent, and javolution.context.internal.ConcurrentContextImpl.threads.
Member Data Documentation
completedCount
int javolution.context.internal.ConcurrentContextImpl.completedCount private
Definition at line 19 of file ConcurrentContextImpl.java.
Referenced by javolution.context.internal.ConcurrentContextImpl.completed(), and javolution.context.internal.ConcurrentContextImpl.exit().
CONCURRENCY
final Configurable<Integer> javolution.context.ConcurrentContext.CONCURRENCY static inherited
Initial value:
= new Configurable<Integer>() {
        @Override
        protected Integer getDefault() {
            return Runtime.getRuntime().availableProcessors() - 1;
        }
        @Override
        protected Integer initialized(Integer value) {
            return MathLib.min(value, 65536);
        }
        @Override
        protected Integer reconfigured(Integer oldCount, Integer newCount) {
            throw new UnsupportedOperationException(
                    "Concurrency reconfiguration not supported.");
        }
    }
Holds the maximum concurrency
(default Runtime.getRuntime().availableProcessors() - 1). The maximum concurrency is configurable. For example, the JVM option
-Djavolution.context.ConcurrentContext#CONCURRENCY=0
disables concurrency.
Definition at line 160 of file ConcurrentContext.java.
Referenced by javolution.context.internal.ConcurrentContextImpl.ConcurrentContextImpl().
CURRENT
final ThreadLocal<AbstractContext> javolution.context.AbstractContext.CURRENT = new ThreadLocal<AbstractContext>() static private inherited
Holds the last context entered (thread-local).
Definition at line 45 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), javolution.context.AbstractContext.enterInner(), and javolution.context.AbstractContext.exit().
error
Throwable javolution.context.internal.ConcurrentContextImpl.error private
Definition at line 20 of file ConcurrentContextImpl.java.
Referenced by javolution.context.internal.ConcurrentContextImpl.completed(), javolution.context.internal.ConcurrentContextImpl.execute(), and javolution.context.internal.ConcurrentContextImpl.exit().
initiatedCount
int javolution.context.internal.ConcurrentContextImpl.initiatedCount private
Definition at line 22 of file ConcurrentContextImpl.java.
Referenced by javolution.context.internal.ConcurrentContextImpl.execute(), and javolution.context.internal.ConcurrentContextImpl.exit().
outer
AbstractContext javolution.context.AbstractContext.outer private inherited
Holds the outer context or
null
if none (top context).
Definition at line 50 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), and javolution.context.AbstractContext.enterInner().
parent
final ConcurrentContextImpl javolution.context.internal.ConcurrentContextImpl.parent private
Definition at line 23 of file ConcurrentContextImpl.java.
Referenced by javolution.context.internal.ConcurrentContextImpl.ConcurrentContextImpl(), and javolution.context.internal.ConcurrentContextImpl.setConcurrency().
threads
ConcurrentThreadImpl [] javolution.context.internal.ConcurrentContextImpl.threads private
Definition at line 24 of file ConcurrentContextImpl.java.
Referenced by javolution.context.internal.ConcurrentContextImpl.ConcurrentContextImpl(), javolution.context.internal.ConcurrentContextImpl.execute(), javolution.context.internal.ConcurrentContextImpl.getConcurrency(), and javolution.context.internal.ConcurrentContextImpl.setConcurrency().
The documentation for this class was generated from the following file:
ConcurrentContextImpl.java