Javolution 6.0.0 java: javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl Class Reference
javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl Class Reference
Public Member Functions
boolean hasNext ()
E next ()
void remove ()
Private Attributes
boolean ahead
final FastSet< E > iterated = new FastSet<E>(comparator())
E next
final Iterator< E > targetIterator = target().iterator()
Detailed Description
Peeking ahead iterator.
Definition at line 23 of file DistinctCollectionImpl.java.
Member Function Documentation
hasNext()
boolean javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.hasNext ()
Definition at line 31 of file DistinctCollectionImpl.java.
{
             if (ahead) return true;
             while (targetIterator.hasNext()) {
                 next = targetIterator.next();
                 if (!iterated.contains(next)) {
                     ahead = true;
                     return true;
                 }
             }
             return false;
         }
References javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.ahead, javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.iterated, javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.next, and javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.targetIterator.
Referenced by javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.next().
next()
E javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.next ()
Definition at line 44 of file DistinctCollectionImpl.java.
{
             hasNext(); // Moves ahead.
             ahead = false;
             return next;
         }
References javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.ahead, javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.hasNext(), and javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.next.
remove()
void javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.remove ()
Definition at line 51 of file DistinctCollectionImpl.java.
{
             targetIterator.remove();
         }
References javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.targetIterator.
Member Data Documentation
ahead
boolean javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.ahead private
Definition at line 25 of file DistinctCollectionImpl.java.
Referenced by javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.hasNext(), and javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.next().
iterated
final FastSet<E> javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.iterated = new FastSet<E>(comparator()) private
Definition at line 26 of file DistinctCollectionImpl.java.
Referenced by javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.hasNext().
next
E javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.next private
Definition at line 27 of file DistinctCollectionImpl.java.
Referenced by javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.hasNext(), and javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.next().
targetIterator
final Iterator<E> javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.targetIterator = target().iterator() private
Definition at line 28 of file DistinctCollectionImpl.java.
Referenced by javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.hasNext(), and javolution.util.internal.collection.DistinctCollectionImpl< E >.IteratorImpl.remove().
The documentation for this class was generated from the following file:
DistinctCollectionImpl.java