Javolution 6.0.0 java: javolution.util.FastSortedSet< E > Class Template Reference
javolution.util.FastSortedSet< E > Class Template Reference
Public Member Functions
FastSortedSet ()
FastSortedSet (Equality<? super E > comparator)
FastSortedSet< E > atomic ()
FastSortedSet< E > shared ()
FastSortedSet< E > unmodifiable ()
boolean add (E e)
boolean contains (Object obj)
boolean remove (Object obj)
FastSortedSet< E > subSet (E fromElement, E toElement)
FastSortedSet< E > headSet (E toElement)
FastSortedSet< E > tailSet (E fromElement)
E first ()
E last ()
FastSortedSet< E > addAll (E... elements)
FastSortedSet< E > addAll (FastCollection<? extends E > that)
FastSet< E > filtered (final Predicate<? super E > filter)
boolean isEmpty ()
int size ()
void clear ()
boolean addAll (final Collection<? extends E > that)
FastCollection< E > parallel ()
FastCollection< E > sequential ()
FastCollection< E > sorted ()
FastCollection< E > sorted (Comparator<? super E > cmp)
FastCollection< E > reversed ()
FastCollection< E > distinct ()
void perform (Consumer<? extends Collection< E >> action)
void update (Consumer<? extends Collection< E >> action)
void forEach (final Consumer<? super E > consumer)
boolean removeIf (final Predicate<? super E > filter)
E reduce (Reducer< E > reducer)
Iterator< E > iterator ()
boolean containsAll (Collection<?> that)
boolean removeAll (final Collection<?> that)
boolean retainAll (final Collection<?> that)
Object[] toArray ()
E min ()
E max ()
Equality<? super E > comparator ()
boolean equals (Object obj)
int hashCode ()
String toString ()
Protected Member Functions
FastSortedSet (SortedSetService< E > service)
SortedSetService< E > service ()
Static Protected Member Functions
static< E > CollectionService< E > serviceOf (FastCollection< E > collection)
Package Functions
public< R > FastCollection< R > mapped (Function<? super E, ? extends R > function)
public< T > T[] toArray (final T[] array)
public< T extends E > T any (Class< T > type)
public< T extends Collection< E > > Immutable< T > toImmutable ()
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
A high-performance sorted set with real-time behavior.
Author
Jean-Marie Dautelle
Version
6.0, July 21, 2013
Definition at line 30 of file FastSortedSet.java.
Constructor & Destructor Documentation
FastSortedSet() [1/3]
javolution.util.FastSortedSet< E >.FastSortedSet ()
Creates an empty sorted set ordered on elements natural order.
Definition at line 37 of file FastSortedSet.java.
{
         this(Equalities.STANDARD);
     }
References javolution.util.function.Equalities.STANDARD.
FastSortedSet() [2/3]
javolution.util.FastSortedSet< E >.FastSortedSet (Equality<? super E > comparator)
Creates an empty sorted set ordered using the specified comparator.
Definition at line 44 of file FastSortedSet.java.
{
         super(new FastSortedMapImpl<E, Void>(comparator, Equalities.IDENTITY)
                 .keySet());
     }
References javolution.util.FastCollection< E >.comparator(), javolution.util.function.Equalities.IDENTITY, and javolution.util.internal.map.sorted.SortedMapView< K, V >.keySet().
FastSortedSet() [3/3]
javolution.util.FastSortedSet< E >.FastSortedSet (SortedSetService< E > service) protected
Creates a sorted set backed up by the specified service implementation.
Definition at line 52 of file FastSortedSet.java.
{
         super(service);
     }
References javolution.util.FastSortedSet< E >.service().
Member Function Documentation
add()
boolean javolution.util.FastSortedSet< E >.add (E element)
Adds the specified element to this collection
Reimplemented from javolution.util.FastCollection< E >.
Definition at line 81 of file FastSortedSet.java.
{
         return super.add(e);
     }
addAll() [1/3]
FastSortedSet<E> javolution.util.FastSortedSet< E >.addAll (E... elements)
Returns this collection with the specified element added.
Parameters
elements the elements to be added.
Returns
this
Reimplemented from javolution.util.FastSet< E >.
Definition at line 139 of file FastSortedSet.java.
{
         return (FastSortedSet<E>) super.addAll(elements);
     }
addAll() [2/3]
FastSortedSet<E> javolution.util.FastSortedSet< E >.addAll (FastCollection<? extends E > that)
Returns this collection with the specified collection's elements added in sequence.
Reimplemented from javolution.util.FastSet< E >.
Definition at line 144 of file FastSortedSet.java.
{
         return (FastSortedSet<E>) super.addAll(that);
     }
addAll() [3/3]
boolean javolution.util.FastCollection< E >.addAll (final Collection<? extends E > that) inherited
Adds all the specified elements to this collection.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, and javolution.util.internal.collection.CollectionView< E >.
Definition at line 462 of file FastCollection.java.
{
         return service().addAll(that);
     }
any()
public<T extends E> T javolution.util.FastCollection< E >.any (Class< T > type) package inherited
Returns any non-null element of the specified type (convenience method).
Parameters
type the element type searched for.
Returns
reduce(Reducers.any(type))
See also
Reducers::any
Definition at line 515 of file FastCollection.java.
{
         return (T) reduce((Reducer<E>) Reducers.any(type));
     }
References javolution.util.function.Reducers.any().
atomic()
FastSortedSet<E> javolution.util.FastSortedSet< E >.atomic ()
Returns an atomic view over this collection. All operations that write or access multiple elements in the collection (such as addAll(), retainAll()) are atomic. Iterators on atomic collections are thread-safe (no ConcurrentModificationException possible).
Reimplemented from javolution.util.FastSet< E >.
Definition at line 61 of file FastSortedSet.java.
{
         return new FastSortedSet<E>(new AtomicSortedSetImpl<E>(service()));
     }
References javolution.util.FastSortedSet< E >.service().
clear()
void javolution.util.FastSet< E >.clear () inherited
Removes all elements from this collection.
Reimplemented from javolution.util.FastCollection< E >.
Definition at line 112 of file FastSet.java.
{
         service.clear();
     }
comparator()
Equality<? super E> javolution.util.FastCollection< E >.comparator () inherited
Returns the comparator uses by this collection for equality and/or ordering if this collection is sorted.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.bitset.BitSetServiceImpl, javolution.util.internal.table.FastTableImpl< E >, javolution.util.internal.table.SubTableImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, javolution.util.internal.collection.SortedCollectionImpl< E >, javolution.util.internal.set.sorted.SubSortedSetImpl< E >, javolution.util.internal.collection.CollectionView< E >, javolution.util.internal.collection.FilteredCollectionImpl< E >, javolution.util.internal.table.UnmodifiableTableImpl< E >, javolution.util.internal.collection.DistinctCollectionImpl< E >, javolution.util.internal.map.MapView< K, V >.EntrySet, javolution.util.internal.table.ReversedTableImpl< E >, javolution.util.internal.collection.ReversedCollectionImpl< E >, javolution.util.internal.collection.UnmodifiableCollectionImpl< E >, javolution.util.internal.collection.ParallelCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Definition at line 574 of file FastCollection.java.
{
         return service().comparator();
     }
Referenced by javolution.util.FastSet< Index >.FastSet(), javolution.util.FastSortedSet< E >.FastSortedSet(), javolution.util.FastSortedTable< E >.FastSortedTable(), and javolution.util.FastTable< javolution.xml.internal.stream.XMLStreamReaderImpl >.FastTable().
contains()
boolean javolution.util.FastSortedSet< E >.contains (Object searched)
Indicates if this collection contains the specified element.
Reimplemented from javolution.util.FastSet< E >.
Definition at line 87 of file FastSortedSet.java.
{
         return super.contains(obj);
     }
containsAll()
boolean javolution.util.FastCollection< E >.containsAll (Collection<?> that) inherited
Indicates if this collection contains all the specified elements.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, and javolution.util.internal.collection.CollectionView< E >.
Definition at line 469 of file FastCollection.java.
{
         return service().containsAll(that);
     }
distinct()
FastCollection<E> javolution.util.FastCollection< E >.distinct () inherited
Returns a view exposing only distinct elements (it does not iterate twice over the same elements). Adding elements already in the collection through this view has no effect. If this collection is initially empty, using a distinct view to add new elements ensures that this collection has no duplicate.
Definition at line 293 of file FastCollection.java.
{
         return new DistinctCollectionImpl<E>(service());
     }
equals()
boolean javolution.util.FastCollection< E >.equals (Object obj) inherited
Compares the specified object with this collection for equality. This method follows the Collection#equals(Object) specification if this collection comparator is Equalities#STANDARD (default). Otherwise, only collections using the same comparator can be considered equals.
Parameters
obj the object to be compared for equality with this collection
Returns
true if both collections are considered equals; false otherwise.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, and javolution.util.internal.collection.CollectionView< E >.
Definition at line 611 of file FastCollection.java.
{
         return service().equals(obj);
     }
filtered()
FastSet<E> javolution.util.FastSet< E >.filtered (final Predicate<? super E > filter) inherited
Returns a view exposing only the elements matching the specified filter. Adding elements not matching the specified filter has no effect. If this collection is initially empty, using a filtered view to add new elements ensure that this collection has only elements satisfying the filter predicate.
Reimplemented from javolution.util.FastCollection< E >.
Definition at line 80 of file FastSet.java.
{
         return new FastSet<E>(new FilteredSetImpl<E>(service(), filter));
     }
first()
E javolution.util.FastSortedSet< E >.first ()
Returns the first (lowest) element currently in this set.
Definition at line 124 of file FastSortedSet.java.
                      {
         return service().first();
     }
References javolution.util.FastSortedSet< E >.service().
Referenced by javolution.util.FastSortedSet< E >.headSet().
forEach()
void javolution.util.FastCollection< E >.forEach (final Consumer<? super E > consumer) inherited
Iterates over all this collection elements applying the specified consumer (convenience method). Iterations are performed concurrently if the collection is parallel.
Parameters
consumer the functional consumer applied to the collection elements.
Definition at line 346 of file FastCollection.java.
{
         perform(new Consumer<Collection<E>>() {
             public void accept(Collection<E> view) {
                 Iterator<E> it = view.iterator();
                 while (it.hasNext()) {
                     consumer.accept(it.next());
                 }
             }
         });
     }
References javolution.util.function.Consumer< T >.accept().
hashCode()
int javolution.util.FastCollection< E >.hashCode () inherited
Returns the hash code of this collection. This method follows the Collection#hashCode() specification if this collection comparator is Equalities#STANDARD.
Returns
this collection hash code.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.CollectionView< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 625 of file FastCollection.java.
{
         return service().hashCode();
     }
headSet()
FastSortedSet<E> javolution.util.FastSortedSet< E >.headSet (E toElement)
Returns a view of the portion of this set whose elements are strictly less than toElement.
Definition at line 111 of file FastSortedSet.java.
{
         return subSet(first(), toElement);
     }
References javolution.util.FastSortedSet< E >.first(), and javolution.util.FastSortedSet< E >.subSet().
isEmpty()
boolean javolution.util.FastSet< E >.isEmpty () inherited
Indicates if this collection is empty.
Reimplemented from javolution.util.FastCollection< E >.
Definition at line 100 of file FastSet.java.
{
         return size() == 0;
     }
iterator()
Iterator<E> javolution.util.FastCollection< E >.iterator () inherited
Returns an iterator over this collection elements. For shared/atomic collections the iterator is immune to concurrent modifications. In other words the elements iterated over may or may not reflect the current state of the collection.
Reimplemented in javolution.util.internal.bitset.BitSetServiceImpl, javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.CollectionView< E >, javolution.util.internal.table.FastTableImpl< E >, javolution.util.internal.table.SharedTableImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, javolution.util.internal.set.sorted.SubSortedSetImpl< E >, javolution.util.internal.table.TableView< E >, javolution.util.internal.collection.SortedCollectionImpl< E >, javolution.util.internal.map.MapView< K, V >.EntrySet, javolution.util.internal.collection.DistinctCollectionImpl< E >, javolution.util.internal.collection.FilteredCollectionImpl< E >, javolution.util.internal.table.AtomicTableImpl< E >, javolution.util.internal.collection.ReversedCollectionImpl< E >, javolution.util.internal.collection.UnmodifiableCollectionImpl< E >, javolution.util.internal.collection.ParallelCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Definition at line 455 of file FastCollection.java.
{
         return service().iterator();
     }
Referenced by javolution.xml.internal.stream.NamespacesImpl.getPrefixes().
last()
E javolution.util.FastSortedSet< E >.last ()
Returns the last (highest) element currently in this set.
Definition at line 130 of file FastSortedSet.java.
                     {
         return service().last();
     }
References javolution.util.FastSortedSet< E >.service().
Referenced by javolution.util.FastSortedSet< E >.tailSet().
mapped()
public<R> FastCollection<R> javolution.util.FastCollection< E >.mapped (Function<? super E, ? extends R > function) package inherited
Returns a view exposing elements through the specified mapping function. The returned view does not allow new elements to be added.
Definition at line 258 of file FastCollection.java.
{
         return new MappedCollectionImpl<E, R>(service(), function);
     }
Referenced by javolution.xml.internal.stream.EntitiesImpl.setEntitiesMapping().
max()
E javolution.util.FastCollection< E >.max () inherited
Returns the largest element of this collection using this collection comparator (convenience method). Returns
null
if this collection is empty.
Returns
reduce(Reducers.max(comparator()))
See also
Reducers::max
Definition at line 541 of file FastCollection.java.
                    {
         return reduce(Reducers.max(comparator()));
     }
References javolution.util.function.Reducers.max().
min()
E javolution.util.FastCollection< E >.min () inherited
Returns the smallest element of this collection using this collection comparator (convenience method). Returns
null
if this collection is empty.
Returns
reduce(Reducers.min(comparator()))
See also
Reducers::min
Definition at line 528 of file FastCollection.java.
                    {
         return reduce(Reducers.min(comparator()));
     }
References javolution.util.function.Reducers.min().
parallel()
FastCollection<E> javolution.util.FastCollection< E >.parallel () inherited
Returns a parallel collection. Parallel collections affect only closure-based operations, all others operations behaving the same. Parallel actions are performed concurrently using Javolution ConcurrentContext. The number of parallel views is derived from the context concurrency (
number of parallel views = concurrency + 1
). Parallel views do not require this collection to be thread-safe (internal synchronization).
See also
#perform(Consumer)
#update(Consumer)
#forEach(Consumer)
#removeIf(Predicate)
#reduce(Reducer)
Definition at line 222 of file FastCollection.java.
{
         return new ParallelCollectionImpl<E>(service());
     }
perform()
void javolution.util.FastCollection< E >.perform (Consumer<? extends Collection< E >> action) inherited
Executes the specified read-only action on this collection. That logic may be performed concurrently on sub-collections if this collection is parallel.
Parameters
action the read-only action.
Exceptions
UnsupportedOperationException if the action tries to update this collection and this collection is thread-safe.
ClassCastException if the action type is not compatible with this collection (e.g. action on set and this is a list).
See also
#update(Consumer)
Definition at line 315 of file FastCollection.java.
{
         service().perform((Consumer<CollectionService<E>>) action, service());
     }
reduce()
E javolution.util.FastCollection< E >.reduce (Reducer< E > reducer) inherited
Performs a reduction of the elements of this collection using the specified reducer. This may not involve iterating over all the collection elements, for example the reducers: Reducers#any, Reducers#and and Reducers#or may stop iterating early. Reduction is performed concurrently if this collection is parallel.
Parameters
reducer the collection reducer.
Returns
the reduction result.
Definition at line 396 of file FastCollection.java.
{
         perform(reducer);
         return reducer.get();
     }
remove()
boolean javolution.util.FastSortedSet< E >.remove (Object searched)
Removes the specified element from this collection.
Reimplemented from javolution.util.FastSet< E >.
Definition at line 93 of file FastSortedSet.java.
{
         return super.remove(obj);
     }
removeAll()
boolean javolution.util.FastCollection< E >.removeAll (final Collection<?> that) inherited
Removes all the specified element from this collection.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.CollectionView< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 476 of file FastCollection.java.
{
         return service().removeAll(that);
     }
removeIf()
boolean javolution.util.FastCollection< E >.removeIf (final Predicate<? super E > filter) inherited
Removes from this collection all the elements matching the specified functional predicate (convenience method). Removals are performed concurrently if this collection is parallel and atomically if this collection is atomic.
Parameters
filter a predicate returning
true
for elements to be removed.
Returns
true
if at least one element has been removed;
false
otherwise.
Definition at line 368 of file FastCollection.java.
{
         final boolean[] removed = new boolean[1];
         update(new Consumer<Collection<E>>() {
             public void accept(Collection<E> view) {
                 Iterator<E> it = view.iterator();
                 while (it.hasNext()) {
                     if (filter.test(it.next())) {
                         it.remove(); // Ok mutable iteration.
                         removed[0] = true;
                     }
                 }
             }
         });
         return removed[0];
     }
retainAll()
boolean javolution.util.FastCollection< E >.retainAll (final Collection<?> that) inherited
Removes all the elements except those in the specified collection.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.CollectionView< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 483 of file FastCollection.java.
{
         return service().retainAll(that);
     }
reversed()
FastCollection<E> javolution.util.FastCollection< E >.reversed () inherited
Returns a view exposing elements in reverse iterative order.
Reimplemented in javolution.util.FastTable< E >.
Definition at line 282 of file FastCollection.java.
{
         return new ReversedCollectionImpl<E>(service());
     }
sequential()
FastCollection<E> javolution.util.FastCollection< E >.sequential () inherited
Returns a sequential view of this collection. Using this view, all closure-based iterations are performed sequentially.
Definition at line 230 of file FastCollection.java.
{
         return new SequentialCollectionImpl<E>(service());
     }
service()
SortedSetService<E> javolution.util.FastSortedSet< E >.service () protected
Holds the actual service implementation.
Reimplemented from javolution.util.FastSet< E >.
Definition at line 149 of file FastSortedSet.java.
{
         return (SortedSetService<E>) super.service();
     }
Referenced by javolution.util.FastSortedSet< E >.atomic(), javolution.util.FastSortedSet< E >.FastSortedSet(), javolution.util.FastSortedSet< E >.first(), javolution.util.FastSortedSet< E >.last(), javolution.util.FastSortedSet< E >.shared(), javolution.util.FastSortedSet< E >.subSet(), and javolution.util.FastSortedSet< E >.unmodifiable().
serviceOf()
static <E> CollectionService<E> javolution.util.FastCollection< E >.serviceOf (FastCollection< E > collection) static protected inherited
Returns the service implementation of any fast collection (for sub-classes).
Definition at line 647 of file FastCollection.java.
{
         return collection.service();
     }
References javolution.util.FastCollection< E >.service().
shared()
FastSortedSet<E> javolution.util.FastSortedSet< E >.shared ()
Returns a thread-safe view over this collection. The shared view allows for concurrent read as long as there is no writer. The default implementation is based on readers-writers locks giving priority to writers. Iterators on shared collections are thread-safe (no ConcurrentModificationException possible).
Reimplemented from javolution.util.FastSet< E >.
Definition at line 66 of file FastSortedSet.java.
{
         return new FastSortedSet<E>(new SharedSortedSetImpl<E>(service()));
     }
References javolution.util.FastSortedSet< E >.service().
size()
int javolution.util.FastSet< E >.size () inherited
Returns the size of this collection.
Reimplemented from javolution.util.FastCollection< E >.
Definition at line 106 of file FastSet.java.
                       {
         return service.size();
     }
Referenced by javolution.util.FastSet< Index >.isEmpty().
sorted() [1/2]
FastCollection<E> javolution.util.FastCollection< E >.sorted () inherited
Returns a view exposing elements sorted according to the collection order.
Definition at line 267 of file FastCollection.java.
{
         return new SortedCollectionImpl<E>(service(), comparator());
     }
Referenced by javolution.util.internal.collection.SortedCollectionImpl< E >.IteratorImpl.IteratorImpl().
sorted() [2/2]
FastCollection<E> javolution.util.FastCollection< E >.sorted (Comparator<? super E > cmp) inherited
Returns a view exposing elements sorted according to the specified comparator.
Definition at line 275 of file FastCollection.java.
{
         return new SortedCollectionImpl<E>(service(), cmp);
     }
subSet()
FastSortedSet<E> javolution.util.FastSortedSet< E >.subSet (E fromElement, E toElement)
Returns a view of the portion of this set whose elements range from fromElement, inclusive, to toElement, exclusive.
Definition at line 104 of file FastSortedSet.java.
{
         return new FastSortedSet<E>(service().subSet(fromElement, toElement));
     }
References javolution.util.FastSortedSet< E >.service().
Referenced by javolution.util.FastSortedSet< E >.headSet(), and javolution.util.FastSortedSet< E >.tailSet().
tailSet()
FastSortedSet<E> javolution.util.FastSortedSet< E >.tailSet (E fromElement)
Returns a view of the portion of this set whose elements are greater than or equal to fromElement.
Definition at line 118 of file FastSortedSet.java.
{
         return subSet(fromElement, last());
     }
References javolution.util.FastSortedSet< E >.last(), and javolution.util.FastSortedSet< E >.subSet().
toArray() [1/2]
Object [] javolution.util.FastCollection< E >.toArray () inherited
Returns an array holding this collection elements.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.CollectionView< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 490 of file FastCollection.java.
{
         return service().toArray();
     }
toArray() [2/2]
public<T> T [] javolution.util.FastCollection< E >.toArray (final T[] array) package inherited
Returns the specified array holding this collection elements if enough capacity.
Reimplemented in javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.CollectionView< E >, and javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 498 of file FastCollection.java.
{
         return service().toArray(array);
     }
toImmutable()
public<T extends Collection<E> > Immutable<T> javolution.util.FastCollection< E >.toImmutable () package inherited
Returns an immutable reference over this collection. The immutable value is an unmodifiable view of this collection. The caller must guarantees that the original collection is never going to be updated (e.g. there is no reference left of the original collection).
Definition at line 585 of file FastCollection.java.
{
         return new Immutable<T>() {
             @SuppressWarnings("unchecked")
             final T value = (T) unmodifiable();
             @Override
             public T value() {
                 return value;
             }
         };
     }
toString()
String javolution.util.FastCollection< E >.toString () inherited
Returns the string representation of this collection using its default format.
Definition at line 634 of file FastCollection.java.
{
         return TextContext.getFormat(FastCollection.class).format(this);
     }
References javolution.text.TextContext.getFormat().
unmodifiable()
FastSortedSet<E> javolution.util.FastSortedSet< E >.unmodifiable ()
Returns an unmodifiable view over this collection. Any attempt to modify the collection through this view will result into a java.lang.UnsupportedOperationException being raised.
Reimplemented from javolution.util.FastSet< E >.
Definition at line 71 of file FastSortedSet.java.
{
         return new FastSortedSet<E>(new UnmodifiableSortedSetImpl<E>(service()));
     }
References javolution.util.FastSortedSet< E >.service().
update()
void javolution.util.FastCollection< E >.update (Consumer<? extends Collection< E >> action) inherited
Executes the specified update action on this collection. That logic may be performed concurrently on sub-collections if this collection is parallel. For atomic collections the update is atomic (either concurrent readers see the full result of the action or nothing).
Parameters
action the update action.
Exceptions
ClassCastException if the action type is not compatible with this collection (e.g. action on set and this is a list).
See also
#perform(Consumer)
Definition at line 334 of file FastCollection.java.
{
         service().update((Consumer<CollectionService<E>>) action, service());
     }
Referenced by javolution.util.FastTable< javolution.xml.internal.stream.XMLStreamReaderImpl >.sort().
Member Data Documentation
serialVersionUID
final long javolution.util.FastSortedSet< E >.serialVersionUID = 0x600L static private
Definition at line 32 of file FastSortedSet.java.
The documentation for this class was generated from the following file:
FastSortedSet.java