Javolution 6.0.0 java: javolution.lang.MathLib Class Reference
javolution.lang.MathLib Class Reference
Static Public Member Functions
static int bitLength (int i)
static int bitLength (long l)
static int bitCount (long longValue)
static int numberOfLeadingZeros (long longValue)
static int numberOfTrailingZeros (long longValue)
static int digitLength (int i)
static int digitLength (long l)
static double toDoublePow2 (long m, int n)
static double toDoublePow10 (long m, int n)
static long toLongPow2 (double d, int n)
static long toLongPow10 (double d, int n)
static int floorLog2 (double d)
static int floorLog10 (double d)
static double toRadians (double degrees)
static double toDegrees (double radians)
static double sqrt (double x)
static double rem (double x, double y)
static double ceil (double x)
static double floor (double x)
static double sin (double radians)
static double cos (double radians)
static double tan (double radians)
static double asin (double x)
static double acos (double x)
static double atan (double x)
static double atan2 (double y, double x)
static double sinh (double x)
static double cosh (double x)
static double tanh (double x)
static double exp (double x)
static double log (double x)
static double log10 (double x)
static double pow (double x, double y)
static int round (float f)
static long round (double d)
static int abs (int i)
static long abs (long l)
static float abs (float f)
static double abs (double d)
static int max (int x, int y)
static long max (long x, long y)
static float max (float x, float y)
static double max (double x, double y)
static int min (int x, int y)
static long min (long x, long y)
static float min (float x, float y)
static double min (double x, double y)
Static Public Attributes
static final double E = 2.71828182845904523536028747135266
static final double PI = 3.1415926535897932384626433832795
static final double HALF_PI = 1.5707963267948966192313216916398
static final double TWO_PI = 6.283185307179586476925286766559
static final double FOUR_PI = 12.566370614359172953850573533118
static final double PI_SQUARE = 9.8696044010893586188344909998762
static final double LOG2 = 0.69314718055994530941723212145818
static final double LOG10 = 2.3025850929940456840179914546844
static final double SQRT2 = 1.4142135623730950488016887242097
static final double NaN = 0.0 / 0.0
static final double Infinity = 1.0 / 0.0
Static Package Functions
static double _atan (double x)
static double _ieee754_log (double x)
static double _ieee754_exp (double x)
Static Package Attributes
static final double atanhi []
static final double atanlo []
static final double aT []
static final double one = 1.0
static final double huge = 1.0e300
static final double ln2_hi = 6.93147180369123816490e-01
static final double ln2_lo = 1.90821492927058770002e-10
static final double two54 = 1.80143985094819840000e+16
static final double Lg1 = 6.666666666666735130e-01
static final double Lg2 = 3.999999999940941908e-01
static final double Lg3 = 2.857142874366239149e-01
static final double Lg4 = 2.222219843214978396e-01
static final double Lg5 = 1.818357216161805012e-01
static final double Lg6 = 1.531383769920937332e-01
static final double Lg7 = 1.479819860511658591e-01
static final double zero = 0.0
static final double halF [] = { 0.5, -0.5, }
static final double twom1000 = 9.33263618503218878990e-302
static final double o_threshold = 7.09782712893383973096e+02
static final double u_threshold = -7.45133219101941108420e+02
static final double ln2HI []
static final double ln2LO []
static final double invln2 = 1.44269504088896338700e+00
static final double P1 = 1.66666666666666019037e-01
static final double P2 = -2.77777777770155933842e-03
static final double P3 = 6.61375632143793436117e-05
static final double P4 = -1.65339022054652515390e-06
static final double P5 = 4.13813679705723846039e-08
Private Member Functions
MathLib ()
Static Private Attributes
static final byte[] BIT_LENGTH
static final long MASK_63 = 0x7FFFFFFFFFFFFFFFL
static final long MASK_32 = 0xFFFFFFFFL
static final int[] POW5_INT
static final double LOG2_DIV_LOG10 = 0.3010299956639811952137388947
static double INV_LOG10 = 0.43429448190325182765112891891661
Detailed Description
An utility class providing a Realtime implementation of the math library.
Author
Jean-Marie Dautelle
Version
4.2, January 6, 2007
Definition at line 20 of file MathLib.java.
Constructor & Destructor Documentation
MathLib()
javolution.lang.MathLib.MathLib () private
Default constructor.
Definition at line 25 of file MathLib.java.
 {}
Member Function Documentation
_atan()
static double javolution.lang.MathLib._atan (double x) static package
Definition at line 1109 of file MathLib.java.
{
         double w, s1, s2, z;
         int ix, hx, id;
         long xBits = Double.doubleToLongBits(x);
         int __HIx = (int) (xBits >> 32);
         int __LOx = (int) xBits;
         hx = __HIx;
         ix = hx & 0x7fffffff;
         if (ix >= 0x44100000) { // if |x| >= 2^66
             if (ix > 0x7ff00000 || (ix == 0x7ff00000 && (__LOx != 0)))
                 return x + x; // NaN
             if (hx > 0)
                 return atanhi[3] + atanlo[3];
             else
                 return -atanhi[3] - atanlo[3];
         }
         if (ix < 0x3fdc0000) { // |x| < 0.4375
             if (ix < 0x3e200000) // |x| < 2^-29
                 if (huge + x > one)
                     return x;
             id = -1;
         } else {
             x = MathLib.abs(x);
             if (ix < 0x3ff30000) // |x| < 1.1875
                 if (ix < 0x3fe60000) { // 7/16 <=|x|<11/16
                     id = 0;
                     x = (2.0 * x - one) / (2.0 + x);
                 } else { // 11/16<=|x|< 19/16
                     id = 1;
                     x = (x - one) / (x + one);
                 }
             else if (ix < 0x40038000) { // |x| < 2.4375
                 id = 2;
                 x = (x - 1.5) / (one + 1.5 * x);
             } else { // 2.4375 <= |x| < 2^66
                 id = 3;
                 x = -1.0 / x;
             }
         }
         // end of argument reduction
         z = x * x;
         w = z * z;
         // break sum from i=0 to 10 aT[i]z**(i+1) into odd and even poly
         s1 = z
                 * (aT[0] + w
                         * (aT[2] + w
                                 * (aT[4] + w
                                         * (aT[6] + w * (aT[8] + w * aT[10])))));
         s2 = w * (aT[1] + w * (aT[3] + w * (aT[5] + w * (aT[7] + w * aT[9]))));
         if (id < 0)
             return x - x * (s1 + s2);
         else {
             z = atanhi[id] - ((x * (s1 + s2) - atanlo[id]) - x);
             return (hx < 0) ? -z : z;
         }
     }
References javolution.lang.MathLib.abs(), javolution.lang.MathLib.aT, javolution.lang.MathLib.atanhi, javolution.lang.MathLib.atanlo, javolution.lang.MathLib.huge, and javolution.lang.MathLib.one.
Referenced by javolution.lang.MathLib.atan().
_ieee754_exp()
static double javolution.lang.MathLib._ieee754_exp (double x) static package
Definition at line 1404 of file MathLib.java.
     {
         double y, hi = 0, lo = 0, c, t;
         int k = 0, xsb;
         int hx; // Unsigned.
         long xBits = Double.doubleToLongBits(x);
         int __HIx = (int) (xBits >> 32);
         int __LOx = (int) xBits;
         hx = __HIx; // high word of x
         xsb = (hx >> 31) & 1; // sign bit of x
         hx &= 0x7fffffff; // high word of |x|
         // filter out non-finite argument
         if (hx >= 0x40862E42) { // if |x|>=709.78...
             if (hx >= 0x7ff00000)
                 if (((hx & 0xfffff) | __LOx) != 0)
                     return x + x; // NaN
                 else
                     return (xsb == 0) ? x : 0.0;
             if (x > o_threshold)
                 return huge * huge; // overflow
             if (x < u_threshold)
                 return twom1000 * twom1000; // underflow
         }
         // argument reduction
         if (hx > 0x3fd62e42) { // if  |x| > 0.5 ln2
             if (hx < 0x3FF0A2B2) { // and |x| < 1.5 ln2
                 hi = x - ln2HI[xsb];
                 lo = ln2LO[xsb];
                 k = 1 - xsb - xsb;
             } else {
                 k = (int) (invln2 * x + halF[xsb]);
                 t = k;
                 hi = x - t * ln2HI[0]; // t*ln2HI is exact here
                 lo = t * ln2LO[0];
             }
             x = hi - lo;
         } else if (hx < 0x3e300000) { // when |x|<2**-28
             if (huge + x > one)
                 return one + x;// trigger inexact
         } else
             k = 0;
         // x is now in primary range
         t = x * x;
         c = x - t * (P1 + t * (P2 + t * (P3 + t * (P4 + t * P5))));
         if (k == 0)
             return one - ((x * c) / (c - 2.0) - x);
         else
             y = one - ((lo - (x * c) / (2.0 - c)) - hi);
         long yBits = Double.doubleToLongBits(y);
         int __HIy = (int) (yBits >> 32);
         if (k >= -1021) {
             __HIy += (k << 20); // add k to y's exponent
             yBits = ((__HIy & 0xFFFFFFFFL) << 32) | (yBits & 0xFFFFFFFFL);
             y = Double.longBitsToDouble(yBits);
             return y;
         } else {
             __HIy += ((k + 1000) << 20);// add k to y's exponent
             yBits = ((__HIy & 0xFFFFFFFFL) << 32) | (yBits & 0xFFFFFFFFL);
             y = Double.longBitsToDouble(yBits);
             return y * twom1000;
         }
     }
References javolution.lang.MathLib.halF, javolution.lang.MathLib.huge, javolution.lang.MathLib.invln2, javolution.lang.MathLib.ln2HI, javolution.lang.MathLib.ln2LO, javolution.lang.MathLib.o_threshold, javolution.lang.MathLib.one, javolution.lang.MathLib.P1, javolution.lang.MathLib.P2, javolution.lang.MathLib.P3, javolution.lang.MathLib.P4, javolution.lang.MathLib.P5, javolution.lang.MathLib.twom1000, and javolution.lang.MathLib.u_threshold.
Referenced by javolution.lang.MathLib.exp().
_ieee754_log()
static double javolution.lang.MathLib._ieee754_log (double x) static package
Definition at line 1244 of file MathLib.java.
{
         double hfsq, f, s, z, R, w, t1, t2, dk;
         int k, hx, i, j;
         int lx; // unsigned
         long xBits = Double.doubleToLongBits(x);
         hx = (int) (xBits >> 32);
         lx = (int) xBits;
         k = 0;
         if (hx < 0x00100000) { // x < 2**-1022
             if (((hx & 0x7fffffff) | lx) == 0)
                 return -two54 / zero; // log(+-0)=-inf
             if (hx < 0)
                 return (x - x) / zero; // log(-#) = NaN
             k -= 54;
             x *= two54; // subnormal number, scale up x
             xBits = Double.doubleToLongBits(x);
             hx = (int) (xBits >> 32); // high word of x
         }
         if (hx >= 0x7ff00000)
             return x + x;
         k += (hx >> 20) - 1023;
         hx &= 0x000fffff;
         i = (hx + 0x95f64) & 0x100000;
         xBits = Double.doubleToLongBits(x);
         int HIx = hx | (i ^ 0x3ff00000); // normalize x or x/2
         xBits = ((HIx & 0xFFFFFFFFL) << 32) | (xBits & 0xFFFFFFFFL);
         x = Double.longBitsToDouble(xBits);
         k += (i >> 20);
         f = x - 1.0;
         if ((0x000fffff & (2 + hx)) < 3) { // |f| < 2**-20
             if (f == zero)
                 if (k == 0)
                     return zero;
                 else {
                     dk = (double) k;
                     return dk * ln2_hi + dk * ln2_lo;
                 }
             R = f * f * (0.5 - 0.33333333333333333 * f);
             if (k == 0)
                 return f - R;
             else {
                 dk = (double) k;
                 return dk * ln2_hi - ((R - dk * ln2_lo) - f);
             }
         }
         s = f / (2.0 + f);
         dk = (double) k;
         z = s * s;
         i = hx - 0x6147a;
         w = z * z;
         j = 0x6b851 - hx;
         t1 = w * (Lg2 + w * (Lg4 + w * Lg6));
         t2 = z * (Lg1 + w * (Lg3 + w * (Lg5 + w * Lg7)));
         i |= j;
         R = t2 + t1;
         if (i > 0) {
             hfsq = 0.5 * f * f;
             if (k == 0)
                 return f - (hfsq - s * (hfsq + R));
             else
                 return dk * ln2_hi
                         - ((hfsq - (s * (hfsq + R) + dk * ln2_lo)) - f);
         } else if (k == 0)
             return f - s * (f - R);
         else
             return dk * ln2_hi - ((s * (f - R) - dk * ln2_lo) - f);
     }
References javolution.lang.MathLib.Lg1, javolution.lang.MathLib.Lg2, javolution.lang.MathLib.Lg3, javolution.lang.MathLib.Lg4, javolution.lang.MathLib.Lg5, javolution.lang.MathLib.Lg6, javolution.lang.MathLib.Lg7, javolution.lang.MathLib.ln2_hi, javolution.lang.MathLib.ln2_lo, javolution.lang.MathLib.two54, and javolution.lang.MathLib.zero.
Referenced by javolution.lang.MathLib.log().
abs() [1/4]
static double javolution.lang.MathLib.abs (double d) static
Returns the absolute value of the specified double argument.
Parameters
d the double value.
Returns
d or -d
Definition at line 951 of file MathLib.java.
{
         return (d < 0) ? -d : d;
     }
abs() [2/4]
static float javolution.lang.MathLib.abs (float f) static
Returns the absolute value of the specified float argument.
Parameters
f the float value.
Returns
f or -f
Definition at line 941 of file MathLib.java.
{
         return (f < 0) ? -f : f;
     }
abs() [3/4]
static int javolution.lang.MathLib.abs (int i) static
Returns the absolute value of the specified int argument.
Parameters
i the int value.
Returns
i or -i
Definition at line 921 of file MathLib.java.
{
         return (i < 0) ? -i : i;
     }
Referenced by javolution.lang.MathLib._atan(), javolution.text.TextBuilder.append(), javolution.text.TypeFormat.format(), and javolution.lang.MathLib.rem().
abs() [4/4]
static long javolution.lang.MathLib.abs (long l) static
Returns the absolute value of the specified long argument.
Parameters
l the long value.
Returns
l or -l
Definition at line 931 of file MathLib.java.
{
         return (l < 0) ? -l : l;
     }
acos()
static double javolution.lang.MathLib.acos (double x) static
Returns the arc cosine of the specified value, in the range of 0.0 through pi.
Parameters
x the value whose arc cosine is to be returned.
Returns
the arc cosine in radians for the specified value.
Definition at line 760 of file MathLib.java.
{
         return HALF_PI - MathLib.asin(x);
     }
References javolution.lang.MathLib.asin(), and javolution.lang.MathLib.HALF_PI.
asin()
static double javolution.lang.MathLib.asin (double x) static
Returns the arc sine of the specified value, in the range of -pi/2 through pi/2.
Parameters
x the value whose arc sine is to be returned.
Returns
the arc sine in radians for the specified value.
Definition at line 741 of file MathLib.java.
{
         if (x < -1.0 || x > 1.0)
             return MathLib.NaN;
         if (x == -1.0)
             return -HALF_PI;
         if (x == 1.0)
             return HALF_PI;
         return MathLib.atan(x / MathLib.sqrt(1.0 - x * x));
     }
References javolution.lang.MathLib.atan(), javolution.lang.MathLib.HALF_PI, javolution.lang.MathLib.NaN, and javolution.lang.MathLib.sqrt().
Referenced by javolution.lang.MathLib.acos().
atan()
static double javolution.lang.MathLib.atan (double x) static
Returns the arc tangent of the specified value, in the range of -pi/2 through pi/2.
Parameters
x the value whose arc tangent is to be returned.
Returns
the arc tangent in radians for the specified value.
See also
Inverse Tangent – from MathWorld
Definition at line 775 of file MathLib.java.
{
         return MathLib._atan(x);
     }
References javolution.lang.MathLib._atan().
Referenced by javolution.lang.MathLib.asin(), and javolution.lang.MathLib.atan2().
atan2()
static double javolution.lang.MathLib.atan2 (double y, double x) static
Returns the angle theta such that (x == cos(theta)) && (y == sin(theta)).
Parameters
y the y value.
x the x value.
Returns
the angle theta in radians.
See also
Wikipedia: Atan2
Definition at line 790 of file MathLib.java.
{
         // From Wikipedia.
         if (x > 0) return MathLib.atan(y / x);
         if ((y >= 0) && (x < 0)) return MathLib.atan(y / x) + PI;
         if ((y < 0) && (x < 0)) return MathLib.atan(y / x) - PI;
         if ((y > 0) && (x == 0)) return PI / 2;
         if ((y < 0) && (x == 0)) return -PI / 2;
         return Double.NaN; // ((y == 0) && (x == 0))
     }
References javolution.lang.MathLib.atan(), and javolution.lang.MathLib.PI.
bitCount()
static int javolution.lang.MathLib.bitCount (long longValue) static
Returns the number of one-bits in the two's complement binary representation of the specified long value. This function is sometimes referred to as the population count.
Parameters
longValue the long value.
Returns
the number of one-bits in the two's complement binary representation of the specified longValue.
Definition at line 97 of file MathLib.java.
{
         longValue = longValue - ((longValue >>> 1) & 0x5555555555555555L);
         longValue = (longValue & 0x3333333333333333L)
                 + ((longValue >>> 2) & 0x3333333333333333L);
         longValue = (longValue + (longValue >>> 4)) & 0x0f0f0f0f0f0f0f0fL;
         longValue = longValue + (longValue >>> 8);
         longValue = longValue + (longValue >>> 16);
         longValue = longValue + (longValue >>> 32);
         return (int) longValue & 0x7f;
     }
Referenced by javolution.util.internal.bitset.BitSetServiceImpl.cardinality().
bitLength() [1/2]
static int javolution.lang.MathLib.bitLength (int i) static
Returns the number of bits in the minimal two's-complement representation of the specified int, excluding a sign bit. For positive int, this is equivalent to the number of bits in the ordinary binary representation. For negative int, it is equivalent to the number of bits of the positive value -(i + 1).
Parameters
i the int value for which the bit length is returned.
Returns
the bit length of i.
Definition at line 38 of file MathLib.java.
{
         if (i < 0)
             i = -++i;
         return (i < 1 << 16) ? (i < 1 << 8) ? BIT_LENGTH[i]
                 : BIT_LENGTH[i >>> 8] + 8
                 : (i < 1 << 24) ? BIT_LENGTH[i >>> 16] + 16
                         : BIT_LENGTH[i >>> 24] + 24;
     }
References javolution.lang.MathLib.BIT_LENGTH.
Referenced by javolution.lang.MathLib.bitLength(), javolution.lang.MathLib.toDoublePow10(), javolution.lang.MathLib.toDoublePow2(), and javolution.lang.MathLib.toLongPow10().
bitLength() [2/2]
static int javolution.lang.MathLib.bitLength (long l) static
Returns the number of bits in the minimal two's-complement representation of the specified long, excluding a sign bit. For positive long, this is equivalent to the number of bits in the ordinary binary representation. For negative long, it is equivalent to the number of bits of the positive value -(l + 1).
Parameters
l the long value for which the bit length is returned.
Returns
the bit length of l.
Definition at line 72 of file MathLib.java.
{
         int i = (int) (l >> 32);
         if (i > 0)
             return (i < 1 << 16) ? (i < 1 << 8) ? BIT_LENGTH[i] + 32
                     : BIT_LENGTH[i >>> 8] + 40
                     : (i < 1 << 24) ? BIT_LENGTH[i >>> 16] + 48
                             : BIT_LENGTH[i >>> 24] + 56;
         if (i < 0)
             return bitLength(-++l);
         i = (int) l;
         return (i < 0) ? 32 : (i < 1 << 16) ? (i < 1 << 8) ? BIT_LENGTH[i]
                 : BIT_LENGTH[i >>> 8] + 8
                 : (i < 1 << 24) ? BIT_LENGTH[i >>> 16] + 16
                         : BIT_LENGTH[i >>> 24] + 24;
     }
References javolution.lang.MathLib.BIT_LENGTH, and javolution.lang.MathLib.bitLength().
ceil()
static double javolution.lang.MathLib.ceil (double x) static
Returns the smallest (closest to negative infinity) double value that is not less than the argument and is equal to a mathematical integer.
Parameters
x the value.
Returns
java.lang.Math.ceil(x)
Definition at line 678 of file MathLib.java.
{
         return Math.ceil(x); // CLDC 1.1
     }
cos()
static double javolution.lang.MathLib.cos (double radians) static
Returns the trigonometric cosine of the specified angle in radians.
Parameters
radians the angle in radians.
Returns
java.lang.Math.cos(radians)
Definition at line 716 of file MathLib.java.
{
         return Math.cos(radians); // CLDC 1.1
     }
cosh()
static double javolution.lang.MathLib.cosh (double x) static
Returns the hyperbolic cosine of x.
Parameters
x the value for which the hyperbolic cosine is calculated.
Returns
(exp(x) + exp(-x)) / 2
Definition at line 820 of file MathLib.java.
{
         return (MathLib.exp(x) + MathLib.exp(-x)) * 0.5;
     }
References javolution.lang.MathLib.exp().
digitLength() [1/2]
static int javolution.lang.MathLib.digitLength (int i) static
Returns the number of digits of the decimal representation of the specified int value, excluding the sign character if any.
Parameters
i the int value for which the digit length is returned.
Returns
String.valueOf(i).length() for zero or positive values; String.valueOf(i).length() - 1 for negative values.
Definition at line 161 of file MathLib.java.
{
         if (i >= 0)
             return (i >= 100000) ? (i >= 10000000) ? (i >= 1000000000) ? 10
                     : (i >= 100000000) ? 9 : 8 : (i >= 1000000) ? 7 : 6
                     : (i >= 100) ? (i >= 10000) ? 5 : (i >= 1000) ? 4 : 3
                             : (i >= 10) ? 2 : 1;
         if (i == Integer.MIN_VALUE)
             return 10; // "2147483648".length()
         return digitLength(-i); // No overflow possible.
     }
Referenced by javolution.text.TextBuilder.append(), javolution.text.TextBuilder.appendFraction(), and javolution.lang.MathLib.digitLength().
digitLength() [2/2]
static int javolution.lang.MathLib.digitLength (long l) static
Returns the number of digits of the decimal representation of the the specified long, excluding the sign character if any.
Parameters
l the long value for which the digit length is returned.
Returns
String.valueOf(l).length() for zero or positive values; String.valueOf(l).length() - 1 for negative values.
Definition at line 180 of file MathLib.java.
{
         if (l >= 0)
             return (l <= Integer.MAX_VALUE) ? digitLength((int) l)
                     : // At least 10 digits or more.
                     (l >= 100000000000000L) ? (l >= 10000000000000000L) ? (l >= 1000000000000000000L) ? 19
                             : (l >= 100000000000000000L) ? 18 : 17
                             : (l >= 1000000000000000L) ? 16 : 15
                             : (l >= 100000000000L) ? (l >= 10000000000000L) ? 14
                                     : (l >= 1000000000000L) ? 13 : 12
                                     : (l >= 10000000000L) ? 11 : 10;
         if (l == Long.MIN_VALUE)
             return 19; // "9223372036854775808".length()
         return digitLength(-l);
     }
References javolution.lang.MathLib.digitLength().
exp()
static double javolution.lang.MathLib.exp (double x) static
Returns e raised to the specified power.
Parameters
x the exponent.
Returns
ex
See also
Exponential Function – from MathWorld
Definition at line 846 of file MathLib.java.
{
         return MathLib._ieee754_exp(x);
     }
References javolution.lang.MathLib._ieee754_exp().
Referenced by javolution.lang.MathLib.cosh(), javolution.lang.MathLib.floorLog2(), javolution.lang.MathLib.pow(), javolution.lang.MathLib.sinh(), javolution.lang.MathLib.tanh(), javolution.lang.MathLib.toDoublePow2(), javolution.lang.MathLib.toLongPow10(), and javolution.lang.MathLib.toLongPow2().
floor()
static double javolution.lang.MathLib.floor (double x) static
Returns the largest (closest to positive infinity) double value that is not greater than the argument and is equal to a mathematical integer.
Parameters
x the value.
Returns
java.lang.Math.ceil(x)
Definition at line 692 of file MathLib.java.
{
         return Math.floor(x); // CLDC 1.1
     }
Referenced by javolution.lang.MathLib.round().
floorLog10()
static int javolution.lang.MathLib.floorLog10 (double d) static
Returns the largest power of 10 that is less than or equal to the the specified positive value.
Parameters
d the double number.
Returns
floor(Log10(abs(d)))
Exceptions
ArithmeticException if d <= 0 or d is NaN or Infinity.
Definition at line 549 of file MathLib.java.
{
         int guess = (int) (LOG2_DIV_LOG10 * MathLib.floorLog2(d));
         double pow10 = MathLib.toDoublePow10(1, guess);
         if ((pow10 <= d) && (pow10 * 10 > d))
             return guess;
         if (pow10 > d)
             return guess - 1;
         return guess + 1;
     }
References javolution.lang.MathLib.floorLog2(), javolution.lang.MathLib.LOG2_DIV_LOG10, and javolution.lang.MathLib.toDoublePow10().
Referenced by javolution.text.TextBuilder.append().
floorLog2()
static int javolution.lang.MathLib.floorLog2 (double d) static
Returns the largest power of 2 that is less than or equal to the the specified positive value.
Parameters
d the double number.
Returns
floor(Log2(abs(d)))
Exceptions
ArithmeticException if d <= 0 or d is NaN or Infinity.
Definition at line 526 of file MathLib.java.
{
         if (d <= 0)
             throw new ArithmeticException("Negative number or zero");
         long bits = Double.doubleToLongBits(d);
         int exp = ((int) (bits >> 52)) & 0x7FF;
         if (exp == 0x7FF)
             throw new ArithmeticException("Infinity or NaN");
         if (exp == 0)
             return floorLog2(d * 18014398509481984L) - 54; // 2^54 Exact.
         return exp - 1023;
     }
References javolution.lang.MathLib.exp().
Referenced by javolution.lang.MathLib.floorLog10().
log()
static double javolution.lang.MathLib.log (double x) static
Returns the natural logarithm (base e) of the specified value.
Parameters
x the value greater than 0.0.
Returns
the value y such as ey == x
Definition at line 859 of file MathLib.java.
{
         return MathLib._ieee754_log(x);
     }
References javolution.lang.MathLib._ieee754_log().
Referenced by javolution.lang.MathLib.log10(), and javolution.lang.MathLib.pow().
log10()
static double javolution.lang.MathLib.log10 (double x) static
Returns the decimal logarithm of the specified value.
Parameters
x the value greater than 0.0.
Returns
the value y such as 10y == x
Definition at line 871 of file MathLib.java.
{
         return log(x) * INV_LOG10;
     }
References javolution.lang.MathLib.INV_LOG10, and javolution.lang.MathLib.log().
max() [1/4]
static double javolution.lang.MathLib.max (double x, double y) static
Returns the greater of two double values.
Parameters
x the first value.
y the second value.
Returns
the larger of x and y.
Definition at line 997 of file MathLib.java.
{
         return (x >= y) ? x : y;
     }
max() [2/4]
static float javolution.lang.MathLib.max (float x, float y) static
Returns the greater of two float values.
Parameters
x the first value.
y the second value.
Returns
the larger of x and y.
Definition at line 986 of file MathLib.java.
{
         return (x >= y) ? x : y;
     }
max() [3/4]
static int javolution.lang.MathLib.max (int x, int y) static
Returns the greater of two int values.
Parameters
x the first value.
y the second value.
Returns
the larger of x and y.
Definition at line 964 of file MathLib.java.
{
         return (x >= y) ? x : y;
     }
Referenced by javolution.text.Text.getDepth(), javolution.text.Text.indexOf(), and javolution.io.Struct.Member.Member().
max() [4/4]
static long javolution.lang.MathLib.max (long x, long y) static
Returns the greater of two long values.
Parameters
x the first value.
y the second value.
Returns
the larger of x and y.
Definition at line 975 of file MathLib.java.
{
         return (x >= y) ? x : y;
     }
min() [1/4]
static double javolution.lang.MathLib.min (double x, double y) static
Returns the smaller of two double values.
Parameters
x the first value.
y the second value.
Returns
the smaller of x and y.
Definition at line 1045 of file MathLib.java.
{
         return (x < y) ? x : y;
     }
min() [2/4]
static float javolution.lang.MathLib.min (float x, float y) static
Returns the smaller of two float values.
Parameters
x the first value.
y the second value.
Returns
the smaller of x and y.
Definition at line 1032 of file MathLib.java.
{
         return (x < y) ? x : y;
     }
min() [3/4]
static int javolution.lang.MathLib.min (int x, int y) static
Returns the smaller of two int values.
Parameters
x the first value.
y the second value.
Returns
the smaller of x and y.
Definition at line 1010 of file MathLib.java.
{
         return (x < y) ? x : y;
     }
Referenced by javolution.util.internal.bitset.BitSetServiceImpl.and(), javolution.util.internal.bitset.BitSetServiceImpl.andNot(), javolution.text.TextBuilder.append(), javolution.util.internal.comparator.LexicalComparatorImpl.compare(), javolution.util.internal.table.FractalTableImpl.copyTo(), javolution.util.internal.bitset.BitSetServiceImpl.get(), javolution.text.TextBuilder.getChars(), javolution.util.internal.bitset.BitSetServiceImpl.intersects(), javolution.text.Text.lastIndexOf(), javolution.test.Perfometer< T >.measure(), javolution.text.CharSet.minus(), javolution.io.CharSequenceReader.read(), and javolution.context.internal.ConcurrentContextImpl.setConcurrency().
min() [4/4]
static long javolution.lang.MathLib.min (long x, long y) static
Returns the smaller of two long values.
Parameters
x the first value.
y the second value.
Returns
the smaller of x and y.
Definition at line 1021 of file MathLib.java.
{
         return (x < y) ? x : y;
     }
numberOfLeadingZeros()
static int javolution.lang.MathLib.numberOfLeadingZeros (long longValue) static
Returns the number of zero bits preceding the highest-order ("leftmost") one-bit in the two's complement binary representation of the specified long value. Returns 64 if the specifed value is zero.
Parameters
longValue the long value.
Returns
the number of leading zero bits.
Definition at line 117 of file MathLib.java.
{
         // From Hacker's Delight
         if (longValue == 0)
             return 64;
         int n = 1;
         int x = (int)(longValue >>> 32);
         if (x == 0) { n += 32; x = (int)longValue; }
         if (x >>> 16 == 0) { n += 16; x <<= 16; }
         if (x >>> 24 == 0) { n +=  8; x <<=  8; }
         if (x >>> 28 == 0) { n +=  4; x <<=  4; }
         if (x >>> 30 == 0) { n +=  2; x <<=  2; }
         n -= x >>> 31;
         return n;
     }
Referenced by javolution.util.internal.bitset.BitSetServiceImpl.length().
numberOfTrailingZeros()
static int javolution.lang.MathLib.numberOfTrailingZeros (long longValue) static
Returns the number of zero bits following the lowest-order ("rightmost") one-bit in the two's complement binary representation of the specified long value. Returns 64 if the specifed value is zero.
Parameters
longValue the long value.
Returns
the number of trailing zero bits.
Definition at line 140 of file MathLib.java.
{
         // From Hacker's Delight
         int x, y;
         if (longValue == 0) return 64;
         int n = 63;
         y = (int)longValue; if (y != 0) { n = n -32; x = y; } else x = (int)(longValue>>>32);
         y = x <<16; if (y != 0) { n = n -16; x = y; }
         y = x << 8; if (y != 0) { n = n - 8; x = y; }
         y = x << 4; if (y != 0) { n = n - 4; x = y; }
         y = x << 2; if (y != 0) { n = n - 2; x = y; }
         return n - ((x << 1) >>> 31);
       }
pow()
static double javolution.lang.MathLib.pow (double x, double y) static
Returns the value of the first argument raised to the power of the second argument.
Parameters
x the base.
y the exponent.
Returns
xy
Definition at line 885 of file MathLib.java.
{
         // Use close approximation (+/- LSB)
         if ((x < 0) && (y == (int) y))
             return (((int) y) & 1) == 0 ? pow(-x, y) : -pow(-x, y);
         return MathLib.exp(y * MathLib.log(x));
     }
References javolution.lang.MathLib.exp(), and javolution.lang.MathLib.log().
rem()
static double javolution.lang.MathLib.rem (double x, double y) static
Returns the remainder of the division of the specified two arguments.
Parameters
x the dividend.
y the divisor.
Returns
x - round(x / y) * y
Definition at line 660 of file MathLib.java.
{
         double tmp = x / y;
         if (MathLib.abs(tmp) <= Long.MAX_VALUE)
             return x - MathLib.round(tmp) * y;
         else
             return NaN;
     }
References javolution.lang.MathLib.abs(), javolution.lang.MathLib.NaN, and javolution.lang.MathLib.round().
round() [1/2]
static long javolution.lang.MathLib.round (double d) static
Returns the closest long to the specified argument.
Parameters
d the double value to be rounded to a long
Returns
the nearest long value.
Definition at line 911 of file MathLib.java.
{
         return (long) floor(d + 0.5d);
     }
References javolution.lang.MathLib.floor().
round() [2/2]
static int javolution.lang.MathLib.round (float f) static
Returns the closest int to the specified argument.
Parameters
f the float value to be rounded to a int
Returns
the nearest int value.
Definition at line 898 of file MathLib.java.
{
         return (int) floor(f + 0.5f);
     }
References javolution.lang.MathLib.floor().
Referenced by javolution.lang.MathLib.rem().
sin()
static double javolution.lang.MathLib.sin (double radians) static
Returns the trigonometric sine of the specified angle in radians.
Parameters
radians the angle in radians.
Returns
java.lang.Math.sin(radians)
Definition at line 704 of file MathLib.java.
{
         return Math.sin(radians); // CLDC 1.1
     }
sinh()
static double javolution.lang.MathLib.sinh (double x) static
Returns the hyperbolic sine of x.
Parameters
x the value for which the hyperbolic sine is calculated.
Returns
(exp(x) - exp(-x)) / 2
Definition at line 808 of file MathLib.java.
{
         return (MathLib.exp(x) - MathLib.exp(-x)) * 0.5;
     }
References javolution.lang.MathLib.exp().
sqrt()
static double javolution.lang.MathLib.sqrt (double x) static
Returns the positive square root of the specified value.
Parameters
x the value.
Returns
java.lang.Math.sqrt(x)
Definition at line 647 of file MathLib.java.
{
         return Math.sqrt(x); // CLDC 1.1
     }
Referenced by javolution.lang.MathLib.asin().
tan()
static double javolution.lang.MathLib.tan (double radians) static
Returns the trigonometric tangent of the specified angle in radians.
Parameters
radians the angle in radians.
Returns
java.lang.Math.tan(radians)
Definition at line 728 of file MathLib.java.
{
         return Math.tan(radians); // CLDC 1.1
     }
tanh()
static double javolution.lang.MathLib.tanh (double x) static
Returns the hyperbolic tangent of x.
Parameters
x the value for which the hyperbolic tangent is calculated.
Returns
(exp(2 * x) - 1) / (exp(2 * x) + 1)
Definition at line 832 of file MathLib.java.
{
         return (MathLib.exp(2 * x) - 1) / (MathLib.exp(2 * x) + 1);
     }
References javolution.lang.MathLib.exp().
toDegrees()
static double javolution.lang.MathLib.toDegrees (double radians) static
Converts an angle in radians to degrees.
Parameters
radians the angle in radians.
Returns
the specified angle in degrees.
Definition at line 635 of file MathLib.java.
{
         return radians * (180.0 / PI);
     }
References javolution.lang.MathLib.PI.
toDoublePow10()
static double javolution.lang.MathLib.toDoublePow10 (long m, int n) static
Returns the closest double representation of the specified long number multiplied by a power of ten.
Parameters
m the long multiplier.
n the power of ten exponent.
Returns
multiplier * 10n.
Definition at line 240 of file MathLib.java.
{
         if (m == 0)
             return 0.0;
         if (m == Long.MIN_VALUE)
             return toDoublePow10(Long.MIN_VALUE / 10, n + 1);
         if (m < 0)
             return -toDoublePow10(-m, n);
         if (n >= 0) { // Positive power.
             if (n > 308)
                 return Double.POSITIVE_INFINITY;
             // Works with 4 x 32 bits registers (x3:x2:x1:x0)
             long x0 = 0; // 32 bits.
             long x1 = 0; // 32 bits.
             long x2 = m & MASK_32; // 32 bits.
             long x3 = m >>> 32; // 32 bits.
             int pow2 = 0;
             while (n != 0) {
                 int i = (n >= POW5_INT.length) ? POW5_INT.length - 1 : n;
                 int coef = POW5_INT[i]; // 31 bits max.
                 if (((int) x0) != 0)
                     x0 *= coef; // 63 bits max.
                 if (((int) x1) != 0)
                     x1 *= coef; // 63 bits max.
                 x2 *= coef; // 63 bits max.
                 x3 *= coef; // 63 bits max.
                 x1 += x0 >>> 32;
                 x0 &= MASK_32;
                 x2 += x1 >>> 32;
                 x1 &= MASK_32;
                 x3 += x2 >>> 32;
                 x2 &= MASK_32;
                 // Adjusts powers.
                 pow2 += i;
                 n -= i;
                 // Normalizes (x3 should be 32 bits max).
                 long carry = x3 >>> 32;
                 if (carry != 0) { // Shift.
                     x0 = x1;
                     x1 = x2;
                     x2 = x3 & MASK_32;
                     x3 = carry;
                     pow2 += 32;
                 }
             }
             // Merges registers to a 63 bits mantissa.
             int shift = 31 - MathLib.bitLength(x3); // -1..30
             pow2 -= shift;
             long mantissa = (shift < 0) ? (x3 << 31) | (x2 >>> 1) : // x3 is 32 bits.
                     (((x3 << 32) | x2) << shift) | (x1 >>> (32 - shift));
             return toDoublePow2(mantissa, pow2);
         } else { // n < 0
             if (n < -324 - 20)
                 return 0.0;
             // Works with x1:x0 126 bits register.
             long x1 = m; // 63 bits.
             long x0 = 0; // 63 bits.
             int pow2 = 0;
             while (true) {
                 // Normalizes x1:x0
                 int shift = 63 - MathLib.bitLength(x1);
                 x1 <<= shift;
                 x1 |= x0 >>> (63 - shift);
                 x0 = (x0 << shift) & MASK_63;
                 pow2 -= shift;
                 // Checks if division has to be performed.
                 if (n == 0)
                     break; // Done.
                 // Retrieves power of 5 divisor.
                 int i = (-n >= POW5_INT.length) ? POW5_INT.length - 1 : -n;
                 int divisor = POW5_INT[i];
                 // Performs the division (126 bits by 31 bits).
                 long wh = (x1 >>> 32);
                 long qh = wh / divisor;
                 long r = wh - qh * divisor;
                 long wl = (r << 32) | (x1 & MASK_32);
                 long ql = wl / divisor;
                 r = wl - ql * divisor;
                 x1 = (qh << 32) | ql;
                 wh = (r << 31) | (x0 >>> 32);
                 qh = wh / divisor;
                 r = wh - qh * divisor;
                 wl = (r << 32) | (x0 & MASK_32);
                 ql = wl / divisor;
                 x0 = (qh << 32) | ql;
                 // Adjusts powers.
                 n += i;
                 pow2 -= i;
             }
             return toDoublePow2(x1, pow2);
         }
     }
References javolution.lang.MathLib.bitLength(), javolution.lang.MathLib.MASK_32, javolution.lang.MathLib.MASK_63, javolution.lang.MathLib.POW5_INT, and javolution.lang.MathLib.toDoublePow2().
Referenced by javolution.text.TextBuilder.append(), javolution.lang.MathLib.floorLog10(), and javolution.text.TypeFormat.parseDouble().
toDoublePow2()
static double javolution.lang.MathLib.toDoublePow2 (long m, int n) static
Returns the closest double representation of the specified long number multiplied by a power of two.
Parameters
m the long multiplier.
n the power of two exponent.
Returns
m * 2n.
Definition at line 203 of file MathLib.java.
{
         if (m == 0)
             return 0.0;
         if (m == Long.MIN_VALUE)
             return toDoublePow2(Long.MIN_VALUE >> 1, n + 1);
         if (m < 0)
             return -toDoublePow2(-m, n);
         int bitLength = MathLib.bitLength(m);
         int shift = bitLength - 53;
         long exp = 1023L + 52 + n + shift; // Use long to avoid overflow.
         if (exp >= 0x7FF)
             return Double.POSITIVE_INFINITY;
         if (exp <= 0) { // Degenerated number (subnormal, assume 0 for bit 52)
             if (exp <= -54)
                 return 0.0;
             return toDoublePow2(m, n + 54) / 18014398509481984L; // 2^54 Exact.
         }
         // Normal number.
         long bits = (shift > 0) ? (m >> shift) + ((m >> (shift - 1)) & 1) : // Rounding.
                 m << -shift;
         if (((bits >> 52) != 1) && (++exp >= 0x7FF))
             return Double.POSITIVE_INFINITY;
         bits &= 0x000fffffffffffffL; // Clears MSB (bit 52)
         bits |= exp << 52;
         return Double.longBitsToDouble(bits);
     }
References javolution.lang.MathLib.bitLength(), and javolution.lang.MathLib.exp().
Referenced by javolution.lang.MathLib.toDoublePow10().
toLongPow10()
static long javolution.lang.MathLib.toLongPow10 (double d, int n) static
Returns the closest long representation of the specified double number multiplied by a power of ten.
Parameters
d the double multiplier.
n the power of two exponent.
Returns
d * 10n.
Definition at line 400 of file MathLib.java.
{
         long bits = Double.doubleToLongBits(d);
         boolean isNegative = (bits >> 63) != 0;
         int exp = ((int) (bits >> 52)) & 0x7FF;
         long m = bits & 0x000fffffffffffffL;
         if (exp == 0x7FF)
             throw new ArithmeticException(
                     "Cannot convert to long (Infinity or NaN)");
         if (exp == 0) {
             if (m == 0)
                 return 0L;
             return toLongPow10(d * 1E16, n - 16);
         }
         m |= 0x0010000000000000L; // Sets MSB (bit 52)
         int pow2 = exp - 1023 - 52;
         // Retrieves 63 bits m with n == 0.
         if (n >= 0) {
             // Works with 4 x 32 bits registers (x3:x2:x1:x0)
             long x0 = 0; // 32 bits.
             long x1 = 0; // 32 bits.
             long x2 = m & MASK_32; // 32 bits.
             long x3 = m >>> 32; // 32 bits.
             while (n != 0) {
                 int i = (n >= POW5_INT.length) ? POW5_INT.length - 1 : n;
                 int coef = POW5_INT[i]; // 31 bits max.
                 if (((int) x0) != 0)
                     x0 *= coef; // 63 bits max.
                 if (((int) x1) != 0)
                     x1 *= coef; // 63 bits max.
                 x2 *= coef; // 63 bits max.
                 x3 *= coef; // 63 bits max.
                 x1 += x0 >>> 32;
                 x0 &= MASK_32;
                 x2 += x1 >>> 32;
                 x1 &= MASK_32;
                 x3 += x2 >>> 32;
                 x2 &= MASK_32;
                 // Adjusts powers.
                 pow2 += i;
                 n -= i;
                 // Normalizes (x3 should be 32 bits max).
                 long carry = x3 >>> 32;
                 if (carry != 0) { // Shift.
                     x0 = x1;
                     x1 = x2;
                     x2 = x3 & MASK_32;
                     x3 = carry;
                     pow2 += 32;
                 }
             }
             // Merges registers to a 63 bits mantissa.
             int shift = 31 - MathLib.bitLength(x3); // -1..30
             pow2 -= shift;
             m = (shift < 0) ? (x3 << 31) | (x2 >>> 1) : // x3 is 32 bits.
                     (((x3 << 32) | x2) << shift) | (x1 >>> (32 - shift));
         } else { // n < 0
             // Works with x1:x0 126 bits register.
             long x1 = m; // 63 bits.
             long x0 = 0; // 63 bits.
             while (true) {
                 // Normalizes x1:x0
                 int shift = 63 - MathLib.bitLength(x1);
                 x1 <<= shift;
                 x1 |= x0 >>> (63 - shift);
                 x0 = (x0 << shift) & MASK_63;
                 pow2 -= shift;
                 // Checks if division has to be performed.
                 if (n == 0)
                     break; // Done.
                 // Retrieves power of 5 divisor.
                 int i = (-n >= POW5_INT.length) ? POW5_INT.length - 1 : -n;
                 int divisor = POW5_INT[i];
                 // Performs the division (126 bits by 31 bits).
                 long wh = (x1 >>> 32);
                 long qh = wh / divisor;
                 long r = wh - qh * divisor;
                 long wl = (r << 32) | (x1 & MASK_32);
                 long ql = wl / divisor;
                 r = wl - ql * divisor;
                 x1 = (qh << 32) | ql;
                 wh = (r << 31) | (x0 >>> 32);
                 qh = wh / divisor;
                 r = wh - qh * divisor;
                 wl = (r << 32) | (x0 & MASK_32);
                 ql = wl / divisor;
                 x0 = (qh << 32) | ql;
                 // Adjusts powers.
                 n += i;
                 pow2 -= i;
             }
             m = x1;
         }
         if (pow2 > 0)
             throw new ArithmeticException("Overflow");
         if (pow2 < -63)
             return 0;
         m = (m >> -pow2) + ((m >> -(pow2 + 1)) & 1); // Rounding.
         return isNegative ? -m : m;
     }
References javolution.lang.MathLib.bitLength(), javolution.lang.MathLib.exp(), javolution.lang.MathLib.MASK_32, javolution.lang.MathLib.MASK_63, and javolution.lang.MathLib.POW5_INT.
Referenced by javolution.text.TextBuilder.append().
toLongPow2()
static long javolution.lang.MathLib.toLongPow2 (double d, int n) static
Returns the closest long representation of the specified double number multiplied by a power of two.
Parameters
d the double multiplier.
n the power of two exponent.
Returns
d * 2n
Exceptions
ArithmeticException if the conversion cannot be performed (NaN, Infinity or overflow).
Definition at line 366 of file MathLib.java.
{
         long bits = Double.doubleToLongBits(d);
         boolean isNegative = (bits >> 63) != 0;
         int exp = ((int) (bits >> 52)) & 0x7FF;
         long m = bits & 0x000fffffffffffffL;
         if (exp == 0x7FF)
             throw new ArithmeticException(
                     "Cannot convert to long (Infinity or NaN)");
         if (exp == 0) {
             if (m == 0)
                 return 0L;
             return toLongPow2(d * 18014398509481984L, n - 54); // 2^54 Exact.
         }
         m |= 0x0010000000000000L; // Sets MSB (bit 52)
         long shift = exp - 1023L - 52 + n; // Use long to avoid overflow.
         if (shift <= -64)
             return 0L;
         if (shift >= 11)
             throw new ArithmeticException("Cannot convert to long (overflow)");
         m = (shift >= 0) ? m << shift : (m >> -shift)
                 + ((m >> -(shift + 1)) & 1); // Rounding.
         return isNegative ? -m : m;
     }
References javolution.lang.MathLib.exp().
toRadians()
static double javolution.lang.MathLib.toRadians (double degrees) static
Converts an angle in degrees to radians.
Parameters
degrees the angle in degrees.
Returns
the specified angle in radians.
Definition at line 623 of file MathLib.java.
{
         return degrees * (PI / 180.0);
     }
References javolution.lang.MathLib.PI.
Member Data Documentation
aT
final double javolution.lang.MathLib.aT[] static package
Initial value:
= { 3.33333333333329318027e-01,
            -1.99999999998764832476e-01,
            1.42857142725034663711e-01,
            -1.11111104054623557880e-01,
            9.09088713343650656196e-02,
            -7.69187620504482999495e-02,
            6.66107313738753120669e-02,
            -5.83357013379057348645e-02,
            4.97687799461593236017e-02,
            -3.65315727442169155270e-02,
            1.62858201153657823623e-02,
    }
Definition at line 1094 of file MathLib.java.
Referenced by javolution.lang.MathLib._atan().
atanhi
final double javolution.lang.MathLib.atanhi[] static package
Initial value:
= { 4.63647609000806093515e-01,
            7.85398163397448278999e-01,
            9.82793723247329054082e-01,
            1.57079632679489655800e+00,
    }
Definition at line 1082 of file MathLib.java.
Referenced by javolution.lang.MathLib._atan().
atanlo
final double javolution.lang.MathLib.atanlo[] static package
Initial value:
= { 2.26987774529616870924e-17,
            3.06161699786838301793e-17,
            1.39033110312309984516e-17,
            6.12323399573676603587e-17,
    }
Definition at line 1088 of file MathLib.java.
Referenced by javolution.lang.MathLib._atan().
BIT_LENGTH
final byte [] javolution.lang.MathLib.BIT_LENGTH static private
Initial value:
= { 0, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4,
            4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6,
            6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
            6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
            7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
            7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
            7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
            8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
            8, 8, 8 }
Definition at line 47 of file MathLib.java.
Referenced by javolution.lang.MathLib.bitLength().
E
final double javolution.lang.MathLib.E = 2.71828182845904523536028747135266 static
The natural logarithm.
Definition at line 564 of file MathLib.java.
FOUR_PI
final double javolution.lang.MathLib.FOUR_PI = 12.566370614359172953850573533118 static
Four time the ratio of the circumference of a circle to its diameter.
Definition at line 584 of file MathLib.java.
halF
final double javolution.lang.MathLib.halF[] = { 0.5, -0.5, } static package
Definition at line 1389 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_exp().
HALF_PI
final double javolution.lang.MathLib.HALF_PI = 1.5707963267948966192313216916398 static
Half the ratio of the circumference of a circle to its diameter.
Definition at line 574 of file MathLib.java.
Referenced by javolution.lang.MathLib.acos(), and javolution.lang.MathLib.asin().
huge
final double javolution.lang.MathLib.huge = 1.0e300 static package
Definition at line 1107 of file MathLib.java.
Referenced by javolution.lang.MathLib._atan(), and javolution.lang.MathLib._ieee754_exp().
Infinity
final double javolution.lang.MathLib.Infinity = 1.0 / 0.0 static
Infinity.
Definition at line 614 of file MathLib.java.
INV_LOG10
double javolution.lang.MathLib.INV_LOG10 = 0.43429448190325182765112891891661 static private
Definition at line 875 of file MathLib.java.
Referenced by javolution.lang.MathLib.log10().
invln2
final double javolution.lang.MathLib.invln2 = 1.44269504088896338700e+00 static package
Definition at line 1397 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_exp().
Lg1
final double javolution.lang.MathLib.Lg1 = 6.666666666666735130e-01 static package
Definition at line 1234 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_log().
Lg2
final double javolution.lang.MathLib.Lg2 = 3.999999999940941908e-01 static package
Definition at line 1235 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_log().
Lg3
final double javolution.lang.MathLib.Lg3 = 2.857142874366239149e-01 static package
Definition at line 1236 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_log().
Lg4
final double javolution.lang.MathLib.Lg4 = 2.222219843214978396e-01 static package
Definition at line 1237 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_log().
Lg5
final double javolution.lang.MathLib.Lg5 = 1.818357216161805012e-01 static package
Definition at line 1238 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_log().
Lg6
final double javolution.lang.MathLib.Lg6 = 1.531383769920937332e-01 static package
Definition at line 1239 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_log().
Lg7
final double javolution.lang.MathLib.Lg7 = 1.479819860511658591e-01 static package
Definition at line 1240 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_log().
ln2_hi
final double javolution.lang.MathLib.ln2_hi = 6.93147180369123816490e-01 static package
Definition at line 1231 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_log().
ln2_lo
final double javolution.lang.MathLib.ln2_lo = 1.90821492927058770002e-10 static package
Definition at line 1232 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_log().
ln2HI
final double javolution.lang.MathLib.ln2HI[] static package
Initial value:
= { 6.93147180369123816490e-01,
                    -6.93147180369123816490e-01, }
Definition at line 1393 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_exp().
ln2LO
final double javolution.lang.MathLib.ln2LO[] static package
Initial value:
= { 1.90821492927058770002e-10,
                    -1.90821492927058770002e-10, }
Definition at line 1395 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_exp().
LOG10
final double javolution.lang.MathLib.LOG10 = 2.3025850929940456840179914546844 static
The natural logarithm of ten.
Definition at line 599 of file MathLib.java.
LOG2
final double javolution.lang.MathLib.LOG2 = 0.69314718055994530941723212145818 static
The natural logarithm of two.
Definition at line 594 of file MathLib.java.
LOG2_DIV_LOG10
final double javolution.lang.MathLib.LOG2_DIV_LOG10 = 0.3010299956639811952137388947 static private
Definition at line 559 of file MathLib.java.
Referenced by javolution.lang.MathLib.floorLog10().
MASK_32
final long javolution.lang.MathLib.MASK_32 = 0xFFFFFFFFL static private
Definition at line 349 of file MathLib.java.
Referenced by javolution.lang.MathLib.toDoublePow10(), and javolution.lang.MathLib.toLongPow10().
MASK_63
final long javolution.lang.MathLib.MASK_63 = 0x7FFFFFFFFFFFFFFFL static private
Definition at line 347 of file MathLib.java.
Referenced by javolution.lang.MathLib.toDoublePow10(), and javolution.lang.MathLib.toLongPow10().
NaN
final double javolution.lang.MathLib.NaN = 0.0 / 0.0 static
Not-A-Number.
Definition at line 609 of file MathLib.java.
Referenced by javolution.lang.MathLib.asin(), and javolution.lang.MathLib.rem().
o_threshold
final double javolution.lang.MathLib.o_threshold = 7.09782712893383973096e+02 static package
Definition at line 1391 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_exp().
one
final double javolution.lang.MathLib.one = 1.0 static package
Definition at line 1107 of file MathLib.java.
Referenced by javolution.lang.MathLib._atan(), and javolution.lang.MathLib._ieee754_exp().
P1
final double javolution.lang.MathLib.P1 = 1.66666666666666019037e-01 static package
Definition at line 1398 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_exp().
P2
final double javolution.lang.MathLib.P2 = -2.77777777770155933842e-03 static package
Definition at line 1399 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_exp().
P3
final double javolution.lang.MathLib.P3 = 6.61375632143793436117e-05 static package
Definition at line 1400 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_exp().
P4
final double javolution.lang.MathLib.P4 = -1.65339022054652515390e-06 static package
Definition at line 1401 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_exp().
P5
final double javolution.lang.MathLib.P5 = 4.13813679705723846039e-08 static package
Definition at line 1402 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_exp().
PI
final double javolution.lang.MathLib.PI = 3.1415926535897932384626433832795 static
The ratio of the circumference of a circle to its diameter.
Definition at line 569 of file MathLib.java.
Referenced by javolution.lang.MathLib.atan2(), javolution.lang.MathLib.toDegrees(), and javolution.lang.MathLib.toRadians().
PI_SQUARE
final double javolution.lang.MathLib.PI_SQUARE = 9.8696044010893586188344909998762 static
Holds PI * PI.
Definition at line 589 of file MathLib.java.
POW5_INT
final int [] javolution.lang.MathLib.POW5_INT static private
Initial value:
= { 1, 5, 25, 125, 625, 3125, 15625,
            78125, 390625, 1953125, 9765625, 48828125, 244140625, 1220703125 }
Definition at line 351 of file MathLib.java.
Referenced by javolution.lang.MathLib.toDoublePow10(), and javolution.lang.MathLib.toLongPow10().
SQRT2
final double javolution.lang.MathLib.SQRT2 = 1.4142135623730950488016887242097 static
The square root of two.
Definition at line 604 of file MathLib.java.
two54
final double javolution.lang.MathLib.two54 = 1.80143985094819840000e+16 static package
Definition at line 1233 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_log().
TWO_PI
final double javolution.lang.MathLib.TWO_PI = 6.283185307179586476925286766559 static
Twice the ratio of the circumference of a circle to its diameter.
Definition at line 579 of file MathLib.java.
twom1000
final double javolution.lang.MathLib.twom1000 = 9.33263618503218878990e-302 static package
Definition at line 1390 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_exp().
u_threshold
final double javolution.lang.MathLib.u_threshold = -7.45133219101941108420e+02 static package
Definition at line 1392 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_exp().
zero
final double javolution.lang.MathLib.zero = 0.0 static package
Definition at line 1242 of file MathLib.java.
Referenced by javolution.lang.MathLib._ieee754_log().
The documentation for this class was generated from the following file:
MathLib.java