Javolution 6.0.0 java: javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl Class Reference
javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl Class Reference
Public Member Functions
IteratorImpl ()
boolean hasNext ()
E next ()
void remove ()
Private Attributes
final E[] elements = (E[]) new Object[size()]
int index = 0
Detailed Description
Reversing Iterator.
Definition at line 22 of file ReversedCollectionImpl.java.
Constructor & Destructor Documentation
IteratorImpl()
javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.IteratorImpl ()
Definition at line 28 of file ReversedCollectionImpl.java.
{
             Iterator<E> it = target().iterator();
             while (it.hasNext() && (index < elements.length)) {
                 elements[index++] = it.next();
             }
         }
References javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.elements, javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.index, and javolution.util.internal.collection.CollectionView< E >.target.
Member Function Documentation
hasNext()
boolean javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.hasNext ()
Definition at line 36 of file ReversedCollectionImpl.java.
{
             return index > 0;
         }
References javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.index.
next()
E javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.next ()
Definition at line 41 of file ReversedCollectionImpl.java.
{
             return elements[--index];
         }
References javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.elements, and javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.index.
remove()
void javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.remove ()
Definition at line 46 of file ReversedCollectionImpl.java.
{
             target().remove(elements[index]);
         }
References javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.elements, javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.index, and javolution.util.internal.collection.CollectionView< E >.target.
Member Data Documentation
elements
final E [] javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.elements = (E[]) new Object[size()] private
Definition at line 25 of file ReversedCollectionImpl.java.
Referenced by javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.IteratorImpl(), javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.next(), and javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.remove().
index
int javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.index = 0 private
Definition at line 26 of file ReversedCollectionImpl.java.
Referenced by javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.hasNext(), javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.IteratorImpl(), javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.next(), and javolution.util.internal.collection.ReversedCollectionImpl< E >.IteratorImpl.remove().
The documentation for this class was generated from the following file:
ReversedCollectionImpl.java