Javolution 6.0.0 java: javolution.util.function.Equalities Class Reference
javolution.util.function.Equalities Class Reference
Static Public Attributes
static final Equality< Object > STANDARD = new StandardComparatorImpl<Object>()
static final Equality< Object > IDENTITY = new IdentityComparatorImpl<Object>()
static final Equality< Object > ARRAY = new ArrayComparatorImpl()
static final Equality< CharSequence > LEXICAL = new LexicalComparatorImpl()
static final Equality< CharSequence > LEXICAL_CASE_INSENSITIVE = new LexicalCaseInsensitiveComparatorImpl()
static final Equality< CharSequence > LEXICAL_FAST = new LexicalFastComparatorImpl()
Private Member Functions
Equalities ()
Detailed Description
A set of useful equalities comparators.
Author
Jean-Marie Dautelle
Version
6.0, July 21, 2013
Definition at line 20 of file Equalities.java.
Constructor & Destructor Documentation
Equalities()
javolution.util.function.Equalities.Equalities () private
Utility class (private constructor).
Definition at line 78 of file Equalities.java.
 {}
Member Data Documentation
ARRAY
final Equality<Object> javolution.util.function.Equalities.ARRAY = new ArrayComparatorImpl() static
A content array comparator. If the content of an array is also an array (multi-dimensional arrays), that same comparator is used for equality and comparison (recursive). The standard comparator is used for non-array elements.
Definition at line 50 of file Equalities.java.
IDENTITY
final Equality<Object> javolution.util.function.Equalities.IDENTITY = new IdentityComparatorImpl<Object>() static
A comparator for which instances are only equals to themselves. For comparisons an empirical method consistent with equals (
==
) is used.
Definition at line 40 of file Equalities.java.
Referenced by javolution.util.internal.bitset.BitSetServiceImpl.comparator(), javolution.util.FastSet< Index >.FastSet(), and javolution.util.FastSortedSet< E >.FastSortedSet().
LEXICAL
final Equality<CharSequence> javolution.util.function.Equalities.LEXICAL = new LexicalComparatorImpl() static
A lexicographic comparator for any CharSequence.
Definition at line 57 of file Equalities.java.
Referenced by javolution.text.CharArray.compareTo(), and javolution.text.Text.compareTo().
LEXICAL_CASE_INSENSITIVE
final Equality<CharSequence> javolution.util.function.Equalities.LEXICAL_CASE_INSENSITIVE = new LexicalCaseInsensitiveComparatorImpl() static
A case insensitive lexicographic comparator for any CharSequence.
Definition at line 64 of file Equalities.java.
LEXICAL_FAST
final Equality<CharSequence> javolution.util.function.Equalities.LEXICAL_FAST = new LexicalFastComparatorImpl() static
An optimized lexical comparator for any CharSequence taking a sample of few characters instead of the whole character sequence to calculate the hash code (still equality comparison checks all characters).
Definition at line 73 of file Equalities.java.
STANDARD
final Equality<Object> javolution.util.function.Equalities.STANDARD = new StandardComparatorImpl<Object>() static
A standard object comparator (based on the object hashCode and equals methods). Comparisons either use the object natural order (which should be consistent with equals) or an empirical method (if the object does not implement Comparable).
Definition at line 31 of file Equalities.java.
Referenced by javolution.util.internal.collection.MappedCollectionImpl< Entry< K, V >, V >.comparator(), javolution.util.internal.collection.CollectionView< R >.equals(), javolution.util.FastMap< Object, javolution.util.Index >.FastMap(), javolution.util.FastSet< Index >.FastSet(), javolution.util.FastSortedMap< K, V >.FastSortedMap(), javolution.util.FastSortedSet< E >.FastSortedSet(), javolution.util.FastSortedTable< E >.FastSortedTable(), and javolution.util.FastTable< javolution.xml.internal.stream.XMLStreamReaderImpl >.FastTable().
The documentation for this class was generated from the following file:
Equalities.java