Javolution 6.0.0 java: javolution.text.CharSet Class Reference
javolution.text.CharSet Class Reference
Public Member Functions
boolean contains (char c)
int indexIn (CharSequence csq)
int indexIn (CharSequence csq, int fromIndex)
int indexIn (char[] chars)
int indexIn (char[] chars, int fromIndex)
int lastIndexIn (CharSequence csq)
int lastIndexIn (CharSequence csq, int fromIndex)
int lastIndexIn (char[] chars)
int lastIndexIn (char[] chars, int fromIndex)
CharSet plus (CharSet that)
CharSet minus (CharSet that)
String toString ()
CharSet value ()
Static Public Member Functions
static CharSet valueOf (char... chars)
static CharSet rangeOf (char first, char last)
Static Public Attributes
static final CharSet EMPTY = new CharSet(new long[0])
static final CharSet WHITESPACES
static final CharSet SPACES
static final CharSet ISO_CONTROLS
Private Member Functions
CharSet (long[] mapping)
CharSet copy ()
Private Attributes
final long[] _mapping
Detailed Description
A set of characters (typically used for parsing purpose where it is significantly faster than regular expressions for simple patterns). For example: [code] // Integration with Text. Text number; int exponentIndex = num.indexOfAny(CharSet.valueOf('e', 'E'));
// Integration with TextFormat. public List<Integer> parse(CharSequence csq, Cursor cursor) { FastTable<Integer> numbers = FastTable.newInstance(); while (cursor.skip(CharSet.WHITESPACES, csq)) { numbers.add(TypeFormat.parseInt(csq, cursor)); } return numbers; } [/code]
Author
Jean-Marie Dautelle
Version
3.7, January 1, 2006
Definition at line 35 of file CharSet.java.
Constructor & Destructor Documentation
CharSet()
javolution.text.CharSet.CharSet (long[] mapping) private
Creates a character set with the specified mapping.
Parameters
mapping the character set mapping.
Definition at line 82 of file CharSet.java.
{
         _mapping = mapping;
     }
References javolution.text.CharSet._mapping.
Referenced by javolution.text.CharSet.copy(), javolution.text.CharSet.rangeOf(), and javolution.text.CharSet.valueOf().
Member Function Documentation
contains()
boolean javolution.text.CharSet.contains (char c)
Indicates if the specified character is contained by this character set.
Parameters
c the character to test.
Returns
true if this character set contains the specified character; false otherwise.
Definition at line 135 of file CharSet.java.
{
         final int i = c >> 6;
         return i < _mapping.length ? (_mapping[i] & (1L << (c & 63))) != 0
                 : false;
     }
References javolution.text.CharSet._mapping.
Referenced by javolution.text.Cursor.at(), javolution.text.CharSet.indexIn(), javolution.text.Text.indexOfAny(), javolution.text.CharSet.lastIndexIn(), javolution.text.Text.lastIndexOfAny(), javolution.text.Cursor.nextToken(), javolution.text.Cursor.skipAny(), and javolution.text.CharSet.toString().
copy()
CharSet javolution.text.CharSet.copy () private
Returns a copy of this character set.
Definition at line 315 of file CharSet.java.
{
         CharSet charSet = new CharSet(new long[this._mapping.length]);
         for (int i = _mapping.length; --i >= 0;) {
             charSet._mapping[i] = _mapping[i];
         }
         return charSet;
     }
References javolution.text.CharSet._mapping, and javolution.text.CharSet.CharSet().
Referenced by javolution.text.CharSet.minus(), and javolution.text.CharSet.plus().
indexIn() [1/4]
int javolution.text.CharSet.indexIn (char[] chars)
Equivalent to indexIn(chars, 0)
Returns
the index in the specified character sequence or -1 if none found.
Definition at line 176 of file CharSet.java.
{
         return indexIn(chars, 0);
     }
References javolution.text.CharSet.indexIn().
indexIn() [2/4]
int javolution.text.CharSet.indexIn (char[] chars, int fromIndex)
Returns the first index in the specified character array of one of the character of this set.
Parameters
chars the character array to be searched.
fromIndex the index to search from.
Returns
the index in the specified character sequence or -1 if none found.
Definition at line 189 of file CharSet.java.
{
         for (int i = fromIndex, n = chars.length; i < n; i++) {
             if (contains(chars[i]))
                 return i;
         }
         return -1;
     }
References javolution.text.CharSet.contains().
indexIn() [3/4]
int javolution.text.CharSet.indexIn (CharSequence csq)
Equivalent to indexIn(csq, 0)
Parameters
csq the character sequence to be searched.
Returns
the index in the specified character sequence or -1 if none found.
Definition at line 149 of file CharSet.java.
{
         return indexIn(csq, 0);
     }
Referenced by javolution.text.CharSet.indexIn().
indexIn() [4/4]
int javolution.text.CharSet.indexIn (CharSequence csq, int fromIndex)
Returns the first index in the specified character sequence of one of the character of this set.
Parameters
csq the character sequence to be searched.
fromIndex the index to search from.
Returns
the index in the specified character sequence or -1 if none found.
Definition at line 162 of file CharSet.java.
{
         for (int i = fromIndex, n = csq.length(); i < n; i++) {
             if (contains(csq.charAt(i)))
                 return i;
         }
         return -1;
     }
References javolution.text.CharSet.contains().
lastIndexIn() [1/4]
int javolution.text.CharSet.lastIndexIn (char[] chars)
Equivalent to lastIndexIn(chars, chars.length-1)
Returns
the index in the specified character sequence or -1 if none found.
Definition at line 234 of file CharSet.java.
{
         return lastIndexIn(chars, chars.length - 1);
     }
References javolution.text.CharSet.lastIndexIn().
lastIndexIn() [2/4]
int javolution.text.CharSet.lastIndexIn (char[] chars, int fromIndex)
Returns the last index in the specified character array of one of the character of this set.
Parameters
chars the character array to be searched.
fromIndex the index to search from (backward).
Returns
the index in the specified character sequence or -1 if none found.
Definition at line 247 of file CharSet.java.
{
         for (int i = fromIndex; i >= 0; i--) {
             if (contains(chars[i]))
                 return i;
         }
         return -1;
     }
References javolution.text.CharSet.contains().
lastIndexIn() [3/4]
int javolution.text.CharSet.lastIndexIn (CharSequence csq)
Equivalent to lastIndexIn(csq, csq.length()-1)
Parameters
csq the character sequence to be searched.
Returns
the last index in the specified character sequence or -1 if none found.
Definition at line 206 of file CharSet.java.
{
         return lastIndexIn(csq, csq.length() - 1);
     }
Referenced by javolution.text.CharSet.lastIndexIn().
lastIndexIn() [4/4]
int javolution.text.CharSet.lastIndexIn (CharSequence csq, int fromIndex)
Returns the last index in the specified character sequence of one of the character of this set.
Parameters
csq the character sequence to be searched.
fromIndex the index to search from (backward).
Returns
the index in the specified character sequence or -1 if none found.
Definition at line 219 of file CharSet.java.
{
         for (int i = fromIndex; i >= 0; --i) {
             if (contains(csq.charAt(i)))
                 return i;
         }
         return -1;
     }
References javolution.text.CharSet.contains().
minus()
CharSet javolution.text.CharSet.minus (CharSet that)
Returns the character set containing the characters from this character minus the characters from the character set specified.
Parameters
that the set containing the character to be removed.
Returns
this - that
Definition at line 279 of file CharSet.java.
{
         CharSet result = this.copy();
         for (int i = MathLib.min(this._mapping.length, that._mapping.length); --i >= 0;) {
             result._mapping[i] &= ~that._mapping[i];
         }
         return result;
     }
References javolution.text.CharSet._mapping, javolution.text.CharSet.copy(), and javolution.lang.MathLib.min().
plus()
CharSet javolution.text.CharSet.plus (CharSet that)
Returns the character set containing the characters from this character set plus the characters from the character set specified.
Parameters
that the set containing the characters to be added.
Returns
this + that
Definition at line 262 of file CharSet.java.
{
         if (that._mapping.length > this._mapping.length)
             return that.plus(this);
         CharSet result = this.copy();
         for (int i = that._mapping.length; --i >= 0;) {
             result._mapping[i] |= that._mapping[i];
         }
         return result;
     }
References javolution.text.CharSet._mapping, javolution.text.CharSet.copy(), and javolution.text.CharSet.plus().
Referenced by javolution.text.CharSet.plus().
rangeOf()
static CharSet javolution.text.CharSet.rangeOf (char first, char last) static
Returns the character set holding the characters in the specified range.
Parameters
first the first character.
last the last character.
Returns
the corresponding character set.
Exceptions
IllegalArgumentException if first > last
Definition at line 116 of file CharSet.java.
{
         if (first > last)
             throw new IllegalArgumentException(
                     "first should be less or equal to last");
         CharSet charSet = new CharSet(new long[(last >> 6) + 1]);
         for (char c = first; c <= last; c++) {
             charSet._mapping[c >> 6] |= 1L << (c & 63);
         }
         return charSet;
     }
References javolution.text.CharSet._mapping, and javolution.text.CharSet.CharSet().
toString()
String javolution.text.CharSet.toString ()
Returns the textual representation of this character set.
Returns
the textual representation.
Definition at line 293 of file CharSet.java.
{
         TextBuilder tb = new TextBuilder();
         tb.append('{');
         int length = _mapping.length << 6;
         for (int i = 0; i < length; i++) {
             if (this.contains((char) i)) {
                 if (tb.length() > 1) {
                     tb.append(',');
                     tb.append(' ');
                 }
                 tb.append('\'');
                 tb.append((char) i);
                 tb.append('\'');
             }
         }
         tb.append('}');
         return tb.toString();
     }
References javolution.text.CharSet._mapping, javolution.text.TextBuilder.append(), javolution.text.CharSet.contains(), javolution.text.TextBuilder.length(), and javolution.text.TextBuilder.toString().
value()
CharSet javolution.text.CharSet.value ()
Returns the constant value held by this object.
Implements javolution.lang.Immutable< T >.
Definition at line 324 of file CharSet.java.
{
         return this;
     }
valueOf()
static CharSet javolution.text.CharSet.valueOf (char... chars) static
Returns the character set holding the specified characters.
Parameters
chars the characters contained by this character set.
Returns
the corresponding character set.
Definition at line 92 of file CharSet.java.
{
         int maxChar = 0;
         for (int i = chars.length; --i >= 0;) {
             if (chars[i] > maxChar) {
                 maxChar = chars[i];
             }
         }
         CharSet charSet = new CharSet(new long[(maxChar >> 6) + 1]);
         for (int i = chars.length; --i >= 0;) {
             char c = chars[i];
             charSet._mapping[c >> 6] |= 1L << (c & 63);
         }
         return charSet;
     }
References javolution.text.CharSet._mapping, and javolution.text.CharSet.CharSet().
Member Data Documentation
_mapping
final long [] javolution.text.CharSet._mapping private
Holds the containment mapping.
Definition at line 75 of file CharSet.java.
Referenced by javolution.text.CharSet.CharSet(), javolution.text.CharSet.contains(), javolution.text.CharSet.copy(), javolution.text.CharSet.minus(), javolution.text.CharSet.plus(), javolution.text.CharSet.rangeOf(), javolution.text.CharSet.toString(), and javolution.text.CharSet.valueOf().
EMPTY
final CharSet javolution.text.CharSet.EMPTY = new CharSet(new long[0]) static
Represents an empty character set.
Definition at line 40 of file CharSet.java.
ISO_CONTROLS
final CharSet javolution.text.CharSet.ISO_CONTROLS static
Initial value:
= CharSet.valueOf(new char[] {
            0x0, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xA, 0xB, 0xC,
            0xD, 0xE, 0xF, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
            0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x7F, 0x80, 0x81,
            0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C,
            0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97,
            0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F })
Represents ISO control characters according to Java (see Character#isISOControl(char)).
Definition at line 64 of file CharSet.java.
SPACES
final CharSet javolution.text.CharSet.SPACES static
Initial value:
= CharSet.valueOf(new char[] { 0x20,
            0xA0, 0x1680, 0x180E, 0x2000, 0x2001, 0x2002, 0x2003, 0x2004,
            0x2005, 0x2006, 0x2007, 0x2008, 0x2009, 0x200A, 0x200B, 0x2028,
            0x2029, 0x202F, 0x205F, 0x3000 })
Represents spaces characters according to Java (see Character#isSpaceChar(char)).
Definition at line 55 of file CharSet.java.
WHITESPACES
final CharSet javolution.text.CharSet.WHITESPACES static
Initial value:
= CharSet.valueOf(new char[] { 0x9,
            0xA, 0xB, 0xC, 0xD, 0x1C, 0x1D, 0x1E, 0x1F, 0x20, 0x1680, 0x180E,
            0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2008,
            0x2009, 0x200A, 0x200B, 0x2028, 0x2029, 0x205F, 0x3000 })
Represents white spaces characters according to Java (see Character#isWhitespace(char)).
Definition at line 46 of file CharSet.java.
The documentation for this class was generated from the following file:
CharSet.java