Javolution 6.0.0 java: javolution.xml.internal.stream.XMLStreamReaderImpl Class Reference
javolution.xml.internal.stream.XMLStreamReaderImpl Class Reference
Classes
class LocationImpl
Public Member Functions
XMLStreamReaderImpl ()
void setInput (InputStream in) throws XMLStreamException
void setInput (InputStream in, String encoding) throws XMLStreamException
void setInput (Reader reader) throws XMLStreamException
int getDepth ()
CharArray getQName ()
CharArray getQName (int depth)
Attributes getAttributes ()
void setEntities (Map< String, String > entities)
String toString ()
int next () throws XMLStreamException
void reset ()
void require (int type, CharSequence namespaceURI, CharSequence localName) throws XMLStreamException
CharArray getElementText () throws XMLStreamException
Object getProperty (String name) throws IllegalArgumentException
void close () throws XMLStreamException
int getAttributeCount ()
CharArray getAttributeLocalName (int index)
CharArray getAttributeNamespace (int index)
CharArray getAttributePrefix (int index)
CharArray getAttributeType (int index)
CharArray getAttributeValue (CharSequence uri, CharSequence localName)
CharArray getAttributeValue (int index)
CharArray getCharacterEncodingScheme ()
String getEncoding ()
int getEventType ()
CharArray getLocalName ()
Location getLocation ()
int getNamespaceCount ()
CharArray getNamespacePrefix (int index)
CharArray getNamespaceURI (CharSequence prefix)
CharArray getNamespaceURI (int index)
NamespaceContext getNamespaceContext ()
CharArray getNamespaceURI ()
CharArray getPrefix ()
CharArray getPIData ()
CharArray getPITarget ()
CharArray getText ()
char[] getTextCharacters ()
int getTextCharacters (int sourceStart, char[] target, int targetStart, int length) throws XMLStreamException
int getTextLength ()
int getTextStart ()
CharArray getVersion ()
boolean isStandalone ()
boolean standaloneSet ()
boolean hasName ()
boolean hasNext () throws XMLStreamException
boolean hasText ()
boolean isAttributeSpecified (int index)
boolean isCharacters ()
boolean isEndElement ()
boolean isStartElement ()
boolean isWhiteSpace ()
int nextTag () throws XMLStreamException
Static Public Attributes
static final int START_ELEMENT = 1
static final int END_ELEMENT = 2
static final int PROCESSING_INSTRUCTION = 3
static final int CHARACTERS = 4
static final int COMMENT = 5
static final int SPACE = 6
static final int START_DOCUMENT = 7
static final int END_DOCUMENT = 8
static final int ENTITY_REFERENCE = 9
static final int ATTRIBUTE = 10
static final int DTD = 11
static final int CDATA = 12
static final int NAMESPACE = 13
static final int NOTATION_DECLARATION = 14
static final int ENTITY_DECLARATION = 15
Package Functions
XMLStreamReaderImpl (XMLInputFactoryImpl factory)
Package Attributes
CharArray _prolog
boolean _charactersPending = false
Static Package Attributes
static final String[] NAMES_OF_EVENTS
static final int READER_BUFFER_CAPACITY = 4096
Private Member Functions
void reloadBuffer () throws XMLStreamException
boolean isEndOfStream () throws XMLStreamException
char handleEndOfLine (char c) throws XMLStreamException
char replaceEntity () throws XMLStreamException
void processAttribute () throws XMLStreamException
void processEndTag () throws XMLStreamException
void processStartTag () throws XMLStreamException
CharArray newSeq (int offset, int length)
CharArray newSeq2 ()
void increaseDataBuffer ()
void increaseStack ()
IllegalStateException illegalState (String msg)
String detectEncoding (InputStream input) throws XMLStreamException
final CharArray readPrologAttribute (CharSequence name)
Static Private Member Functions
static boolean isUTF8 (Object encoding)
static boolean isXMLNS (CharArray chars)
static boolean isWhiteSpace (char c)
Private Attributes
int _readIndex
int _readCount
char[] _data = new char[READER_BUFFER_CAPACITY * 2]
int _index
int _depth
CharArray _qName
int _prefixSep
CharArray _attrQName
int _attrPrefixSep
CharArray _attrValue
int _eventType = START_DOCUMENT
boolean _isEmpty
int _start
int _state = STATE_CHARACTERS
CharArray _text
Reader _reader
final char[] _readBuffer = new char[READER_BUFFER_CAPACITY]
int _startOffset
final LocationImpl _location = new LocationImpl()
final NamespacesImpl _namespaces = new NamespacesImpl()
final AttributesImpl _attributes = new AttributesImpl(_namespaces)
CharArray[] _elemStack = new CharArray[16]
String _encoding
final EntitiesImpl _entities = new EntitiesImpl()
final UTF8StreamReader _utf8StreamReader = new UTF8StreamReader()
final XMLInputFactoryImpl _factory
final Runnable _createSeqLogic
CharArray[] _seqs = new CharArray[256]
int _seqsIndex
int _seqsCapacity
Static Private Attributes
static final int STATE_CHARACTERS = 1
static final int STATE_MARKUP = 2
static final int STATE_COMMENT = 3
static final int STATE_PI = 4
static final int STATE_CDATA = 5
static final int STATE_OPEN_TAGxREAD_ELEM_NAME = 6
static final int STATE_OPEN_TAGxELEM_NAME_READ = 7
static final int STATE_OPEN_TAGxREAD_ATTR_NAME = 8
static final int STATE_OPEN_TAGxATTR_NAME_READ = 9
static final int STATE_OPEN_TAGxEQUAL_READ = 10
static final int STATE_OPEN_TAGxREAD_ATTR_VALUE_SIMPLE_QUOTE = 11
static final int STATE_OPEN_TAGxREAD_ATTR_VALUE_DOUBLE_QUOTE = 12
static final int STATE_OPEN_TAGxEMPTY_TAG = 13
static final int STATE_CLOSE_TAGxREAD_ELEM_NAME = 14
static final int STATE_CLOSE_TAGxELEM_NAME_READ = 15
static final int STATE_DTD = 16
static final int STATE_DTD_INTERNAL = 17
static final CharArray ENCODING = new CharArray("encoding")
static final CharArray VERSION = new CharArray("version")
static final CharArray STANDALONE = new CharArray("standalone")
Detailed Description
XMLStreamReader implementation.
This implementation returns all contiguous character data in a single chunk (always coalescing). It is non-validating (DTD is returned unparsed). Although, users may define custom entities mapping using the setEntities method (e.g. after parsing/resolving external entities).
Definition at line 38 of file XMLStreamReaderImpl.java.
Constructor & Destructor Documentation
XMLStreamReaderImpl() [1/2]
javolution.xml.internal.stream.XMLStreamReaderImpl.XMLStreamReaderImpl ()
Default constructor.
Definition at line 198 of file XMLStreamReaderImpl.java.
{
         this(null);
     }
XMLStreamReaderImpl() [2/2]
javolution.xml.internal.stream.XMLStreamReaderImpl.XMLStreamReaderImpl (XMLInputFactoryImpl factory) package
Factory-based constructor.
Definition at line 205 of file XMLStreamReaderImpl.java.
{
         _factory = factory;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._factory.
Member Function Documentation
close()
void javolution.xml.internal.stream.XMLStreamReaderImpl.close () throws XMLStreamException
Frees any resources associated with this Reader. This method does not close the underlying input source.
Exceptions
XMLStreamException if there are errors freeing associated resources
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1181 of file XMLStreamReaderImpl.java.
{
         reset();
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll().
detectEncoding()
String javolution.xml.internal.stream.XMLStreamReaderImpl.detectEncoding (InputStream input) throws XMLStreamException private
Definition at line 1437 of file XMLStreamReaderImpl.java.
{
         // Autodetect encoding (see http://en.wikipedia.org/wiki/UTF-16)
         int byte0;
         try {
             byte0 = input.read();
         } catch (IOException e) {
             throw new XMLStreamException(e);
         }
         if (byte0 == -1)
             throw new XMLStreamException("Premature End-Of-File");
         if (byte0 == '<') { // UTF-8 or compatible encoding.
             _readBuffer[_startOffset++] = '<';
             return "UTF-8";
         } else {
             int byte1;
             try {
                 byte1 = input.read();
             } catch (IOException e) {
                 throw new XMLStreamException(e);
             }
             if (byte1 == -1)
                 throw new XMLStreamException("Premature End-Of-File");
             if ((byte0 == 0) && (byte1 == '<')) { // UTF-16 BIG ENDIAN
                 _readBuffer[_startOffset++] = '<';
                 return "UTF-16BE";
             } else if ((byte0 == '<') && (byte1 == 0)) { // UTF-16 LITTLE ENDIAN
                 _readBuffer[_startOffset++] = '<';
                 return "UTF-16LE";
             } else if ((byte0 == 0xFF) && (byte1 == 0xFE)) { // BOM for UTF-16 LITTLE ENDIAN
                 return "UTF-16";
             } else if ((byte0 == 0xFE) && (byte1 == 0xFF)) { // BOM for UTF-16 BIG ENDIAN
                 return "UTF-16";
             } else { // Encoding unknown (or no prolog) assumes UTF-8
                 _readBuffer[_startOffset++] = (char) byte0;
                 _readBuffer[_startOffset++] = (char) byte1;
                 return "UTF-8";
             }
         }
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._readBuffer, and javolution.xml.internal.stream.XMLStreamReaderImpl._startOffset.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
getAttributeCount()
int javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeCount ()
Returns the count of attributes on this START_ELEMENT, this method is only valid on a START_ELEMENT or ATTRIBUTE. This count excludes namespace definitions. Attribute indices are zero-based.
Returns
returns the number of attributes.
Exceptions
IllegalStateException if not a START_ELEMENT or ATTRIBUTE.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1185 of file XMLStreamReaderImpl.java.
{
         if (_eventType != XMLStreamConstants.START_ELEMENT)
             throw illegalState("Not a start element");
         return _attributes.getLength();
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._attributes, javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.AttributesImpl.getLength(), javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
getAttributeLocalName()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeLocalName (int index)
Returns the localName of the attribute at the provided index.
Parameters
index the position of the attribute.
Returns
the localName of the attribute.
Exceptions
IllegalStateException if not a START_ELEMENT or ATTRIBUTE.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1191 of file XMLStreamReaderImpl.java.
{
         if (_eventType != XMLStreamConstants.START_ELEMENT)
             throw illegalState("Not a start element");
         return _attributes.getLocalName(index);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._attributes, javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.AttributesImpl.getLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
getAttributeNamespace()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeNamespace (int index)
Returns the namespace of the attribute at the provided index
Parameters
index the position of the attribute.
Returns
the namespace URI or null if no prefix.
Exceptions
IllegalStateException if not a START_ELEMENT or ATTRIBUTE.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1197 of file XMLStreamReaderImpl.java.
{
         if (_eventType != XMLStreamConstants.START_ELEMENT)
             throw illegalState("Not a start element");
         CharArray prefix = _attributes.getPrefix(index);
         return _namespaces.getNamespaceURINullAllowed(prefix);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._attributes, javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._namespaces, javolution.xml.internal.stream.NamespacesImpl.getNamespaceURINullAllowed(), javolution.xml.internal.stream.AttributesImpl.getPrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
getAttributePrefix()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributePrefix (int index)
Returns the prefix of this attribute at the provided index
Parameters
index the position of the attribute.
Returns
the prefix of the attribute or null if no prefix.
Exceptions
IllegalStateException if not a START_ELEMENT or ATTRIBUTE.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1204 of file XMLStreamReaderImpl.java.
{
         if (_eventType != XMLStreamConstants.START_ELEMENT)
             throw illegalState("Not a start element");
         return _attributes.getPrefix(index);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._attributes, javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.AttributesImpl.getPrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
getAttributes()
Attributes javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributes ()
Returns the current attributes (SAX2-Like).
Returns
returns the number of attributes.
Exceptions
IllegalStateException if not a START_ELEMENT.
Definition at line 342 of file XMLStreamReaderImpl.java.
{
         if (_eventType != XMLStreamConstants.START_ELEMENT)
             throw new IllegalStateException("Not a start element");
         return _attributes;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._attributes, javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
Referenced by javolution.xml.XMLFormat< T >.InputElement.getAttributes(), and javolution.xml.sax.XMLReaderImpl.parseAll().
getAttributeType()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeType (int index)
Returns the XML type of the attribute at the provided index.
Parameters
index the position of the attribute
Returns
the XML type of the attribute.
Exceptions
IllegalStateException if not a START_ELEMENT or ATTRIBUTE.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1210 of file XMLStreamReaderImpl.java.
{
         if (_eventType != XMLStreamConstants.START_ELEMENT)
             throw illegalState("Not a start element");
         return _attributes.getType(index);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._attributes, javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.AttributesImpl.getType(), javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
getAttributeValue() [1/2]
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeValue (CharSequence namespaceURI, CharSequence localName)
Returns the normalized attribute value of the attribute with the namespace and localName.
Parameters
namespaceURI the namespace of the attribute or null.
localName the local name of the attribute.
Returns
returns the value of the attribute or null.
Exceptions
IllegalStateException if not a START_ELEMENT or ATTRIBUTE.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1216 of file XMLStreamReaderImpl.java.
{
         if (_eventType != XMLStreamConstants.START_ELEMENT)
             throw illegalState("Not a start element");
         return (uri == null) ? _attributes.getValue(localName) : _attributes
                 .getValue(uri, localName);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._attributes, javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.AttributesImpl.getValue(), javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
Referenced by javolution.xml.XMLFormat< T >.InputElement.getAttribute().
getAttributeValue() [2/2]
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeValue (int index)
Returns the value of the attribute at the index.
Parameters
index the position of the attribute.
Returns
the attribute value.
Exceptions
IllegalStateException if not a START_ELEMENT or ATTRIBUTE.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1223 of file XMLStreamReaderImpl.java.
{
         if (_eventType != XMLStreamConstants.START_ELEMENT)
             throw illegalState("Not a start element");
         return _attributes.getValue(index);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._attributes, javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.AttributesImpl.getValue(), javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
getCharacterEncodingScheme()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getCharacterEncodingScheme ()
Returns the character encoding declared on the xml declaration.
Returns
the encoding declared in the document or null
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1229 of file XMLStreamReaderImpl.java.
{
         return readPrologAttribute(ENCODING);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl.ENCODING, and javolution.xml.internal.stream.XMLStreamReaderImpl.readPrologAttribute().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
getDepth()
int javolution.xml.internal.stream.XMLStreamReaderImpl.getDepth ()
Returns the current depth of the element. Outside the root element, the depth is 0. The depth is incremented by 1 when a start tag is reached. The depth is decremented AFTER the end tag event was observed. [code] 0 <root> 1 sometext 1 <foobar> 2 </foobar> 2 </root> 1 0 [/code]
Returns
the nesting depth.
Definition at line 305 of file XMLStreamReaderImpl.java.
{
         return _depth;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._depth.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getQName().
getElementText()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText () throws XMLStreamException
Reads the content of a text-only element, an exception is thrown if this is not a text-only element. Regardless of the value of javax.xml.stream.isCoalescing this method always returns coalesced content.
Precondition: the current event is START_ELEMENT.
Postcondition: the current event is the corresponding END_ELEMENT.
The method does the following (implementations are free to optimized but must do equivalent processing):
if (getEventType() != XMLStreamConstants.START_ELEMENT) {
    throw new XMLStreamException(
            "parser must be on START_ELEMENT to read next text", getLocation());
}
int eventType = next();
StringBuffer content = new StringBuffer();
while (eventType != XMLStreamConstants.END_ELEMENT) {
    if (eventType == XMLStreamConstants.CHARACTERS
            || eventType == XMLStreamConstants.CDATA
            || eventType == XMLStreamConstants.SPACE
            || eventType == XMLStreamConstants.ENTITY_REFERENCE) {
        buf.append(getText());
    } else if (eventType == XMLStreamConstants.PROCESSING_INSTRUCTION
            || eventType == XMLStreamConstants.COMMENT) {
        // skipping
    } else if (eventType == XMLStreamConstants.END_DOCUMENT) {
        throw new XMLStreamException(
                "unexpected end of document when reading element text content",
                this);
    } else if (eventType == XMLStreamConstants.START_ELEMENT) {
        throw new XMLStreamException(
                "element text content may not contain START_ELEMENT",
                getLocation());
    } else {
        throw new XMLStreamException("Unexpected event type " + eventType,
                getLocation());
    }
    eventType = next();
}
return buf.toString();
Exceptions
XMLStreamException if the current event is not a START_ELEMENT or if a non text element is encountered.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1133 of file XMLStreamReaderImpl.java.
{
         // Derived from interface specification code.
         if (getEventType() != XMLStreamConstants.START_ELEMENT) { throw new XMLStreamException(
                 "Parser must be on START_ELEMENT to read next text",
                 getLocation()); }
         CharArray text = null;
         int eventType = next();
         while (eventType != XMLStreamConstants.END_ELEMENT) {
             if (eventType == XMLStreamConstants.CHARACTERS) {
                 if (text == null) {
                     text = getText();
                 } else { // Merge (adjacent text, comments and PI are not kept).
                     text.setArray(_data, text.offset(), text.length()
                             + getText().length());
                 }
             } else if (eventType == XMLStreamConstants.PROCESSING_INSTRUCTION
                     || eventType == XMLStreamConstants.COMMENT) {
                 // Skips (not kept).
             } else if (eventType == XMLStreamConstants.END_DOCUMENT) {
                 throw new XMLStreamException(
                         "Unexpected end of document when reading element text content",
                         getLocation());
             } else if (eventType == XMLStreamConstants.START_ELEMENT) {
                 throw new XMLStreamException(
                         "Element text content may not contain START_ELEMENT",
                         getLocation());
             } else {
                 throw new XMLStreamException("Unexpected event type "
                         + NAMES_OF_EVENTS[eventType], getLocation());
             }
             eventType = next();
         }
         return (text != null) ? text : newSeq(0, 0);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._data, javolution.xml.stream.XMLStreamConstants.CHARACTERS, javolution.xml.stream.XMLStreamConstants.COMMENT, javolution.xml.stream.XMLStreamConstants.END_DOCUMENT, javolution.xml.stream.XMLStreamConstants.END_ELEMENT, javolution.xml.internal.stream.XMLStreamReaderImpl.getEventType(), javolution.xml.internal.stream.XMLStreamReaderImpl.getLocation(), javolution.xml.internal.stream.XMLStreamReaderImpl.getText(), javolution.text.CharArray.length(), javolution.xml.internal.stream.XMLStreamReaderImpl.NAMES_OF_EVENTS, javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.text.CharArray.offset(), javolution.xml.stream.XMLStreamConstants.PROCESSING_INSTRUCTION, javolution.text.CharArray.setArray(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
Referenced by javolution.xml.XMLFormat< T >.InputElement.getText().
getEncoding()
String javolution.xml.internal.stream.XMLStreamReaderImpl.getEncoding ()
Returns the input encoding if known or null if unknown.
Returns
the encoding of this instance or null.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1235 of file XMLStreamReaderImpl.java.
{
         return _encoding;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._encoding.
getEventType()
int javolution.xml.internal.stream.XMLStreamReaderImpl.getEventType ()
Returns an integer code that indicates the type of the event the cursor is pointing to.
Returns
the event type.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1239 of file XMLStreamReaderImpl.java.
{
         return _eventType;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText(), javolution.xml.XMLFormat< T >.InputElement.hasNext(), and javolution.xml.sax.XMLReaderImpl.parseAll().
getLocalName()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName ()
Returns the (local) name of the current event. For START_ELEMENT or END_ELEMENT returns the (local) name of the current element. For ENTITY_REFERENCE it returns entity name. The current event must be START_ELEMENT or END_ELEMENT, or ENTITY_REFERENCE.
Returns
the localName.
Exceptions
IllegalStateException if this not a START_ELEMENT, END_ELEMENT or ENTITY_REFERENCE
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1243 of file XMLStreamReaderImpl.java.
{
         if ((_eventType != XMLStreamConstants.START_ELEMENT)
                 && (_eventType != XMLStreamConstants.END_ELEMENT))
             throw illegalState("Not a start or end element");
         if (_prefixSep < 0)
             return _qName;
         CharArray localName = newSeq(_prefixSep + 1,
                 _qName.offset() + _qName.length() - _prefixSep - 1);
         return localName;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._prefixSep, javolution.xml.internal.stream.XMLStreamReaderImpl._qName, javolution.xml.stream.XMLStreamConstants.END_ELEMENT, javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), javolution.text.CharArray.length(), javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq(), javolution.text.CharArray.offset(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
Referenced by javolution.xml.XMLFormat< T >.InputElement.get(), javolution.xml.XMLFormat< T >.InputElement.getNext(), javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.internal.stream.XMLStreamReaderImpl.require().
getLocation()
Location javolution.xml.internal.stream.XMLStreamReaderImpl.getLocation ()
Return the current location of the processor. If the Location is unknown the processor should return an implementation of Location that returns -1 for the location and null for the publicId and systemId. The location information is only valid until next() is called.
Returns
the current location.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1254 of file XMLStreamReaderImpl.java.
{
         return _location;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._location.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText(), javolution.xml.XMLFormat< T >.InputElement.getNext(), and javolution.xml.XMLFormat< T >.InputElement.readInstanceOf().
getNamespaceContext()
NamespaceContext javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceContext ()
Returns a read only namespace context for the current position.
Returns
return a namespace context
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1286 of file XMLStreamReaderImpl.java.
{
         return _namespaces;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._namespaces.
getNamespaceCount()
int javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceCount ()
Returns the count of namespaces declared on this START_ELEMENT or END_ELEMENT. This method is only valid on a START_ELEMENT, END_ELEMENT or NAMESPACE. On an END_ELEMENT the count is of the namespaces that are about to go out of scope. This is the equivalent of the information reported by SAX callback for an end element event.
Returns
returns the number of namespace declarations on this specific element.
Exceptions
IllegalStateException if not a START_ELEMENT or END_ELEMENT.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1258 of file XMLStreamReaderImpl.java.
{
         if ((_eventType != XMLStreamConstants.START_ELEMENT)
                 && (_eventType != XMLStreamConstants.END_ELEMENT))
             throw illegalState("Not a start or end element");
         return _namespaces._namespacesCount[_depth];
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._depth, javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._namespaces, javolution.xml.internal.stream.NamespacesImpl._namespacesCount, javolution.xml.stream.XMLStreamConstants.END_ELEMENT, javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll().
getNamespacePrefix()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespacePrefix (int index)
Returns the prefix for the namespace declared at the index.
Parameters
index the position of the namespace declaration.
Returns
returns the namespace prefix or null if no prefix.
Exceptions
IllegalStateException if this is not a START_ELEMENT, END_ELEMENT or NAMESPACE.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1265 of file XMLStreamReaderImpl.java.
{
         if ((_eventType != XMLStreamConstants.START_ELEMENT)
                 && (_eventType != XMLStreamConstants.END_ELEMENT))
             throw illegalState("Not a start or end element");
         return _namespaces._prefixes[index];
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._namespaces, javolution.xml.internal.stream.NamespacesImpl._prefixes, javolution.xml.stream.XMLStreamConstants.END_ELEMENT, javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll().
getNamespaceURI() [1/3]
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI ()
If the current event is a START_ELEMENT or END_ELEMENT this method returns the URI of the current element (URI mapping to the prefix element/attribute has; or if no prefix null).
Returns
the URI bound to this elements prefix or null.
Exceptions
IllegalStateException if not a START_ELEMENT, END_ELEMENT or ATTRIBUTE.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1290 of file XMLStreamReaderImpl.java.
{
         return _namespaces.getNamespaceURINullAllowed(getPrefix());
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._namespaces, javolution.xml.internal.stream.NamespacesImpl.getNamespaceURINullAllowed(), and javolution.xml.internal.stream.XMLStreamReaderImpl.getPrefix().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.require().
getNamespaceURI() [2/3]
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI (CharSequence prefix)
Returns the uri for the given prefix. The uri returned depends on the current state of the processor.
NOTE:The 'xml' prefix is bound as defined in Namespaces in XML specification to "http://www.w3.org/XML/1998/namespace".
NOTE: The 'xmlns' prefix must be resolved to following namespace http://www.w3.org/2000/xmlns/
Parameters
prefix the prefix to lookup.
Returns
the uri bound to the given prefix or null if it is not bound
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1272 of file XMLStreamReaderImpl.java.
{
         if ((_eventType != XMLStreamConstants.START_ELEMENT)
                 && (_eventType != XMLStreamConstants.END_ELEMENT))
             throw illegalState("Not a start or end element");
         return _namespaces.getNamespaceURI(prefix);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._namespaces, javolution.xml.stream.XMLStreamConstants.END_ELEMENT, javolution.xml.internal.stream.NamespacesImpl.getNamespaceURI(), javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
Referenced by javolution.xml.XMLFormat< T >.InputElement.get(), and javolution.xml.sax.XMLReaderImpl.parseAll().
getNamespaceURI() [3/3]
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI (int index)
Returns the URI for the namespace declared at the index.
Parameters
index the position of the namespace declaration.
Returns
returns the namespace uri or null if no prefix.
Exceptions
IllegalStateException if this is not a START_ELEMENT, END_ELEMENT or NAMESPACE.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1279 of file XMLStreamReaderImpl.java.
{
         if ((_eventType != XMLStreamConstants.START_ELEMENT)
                 && (_eventType != XMLStreamConstants.END_ELEMENT))
             throw illegalState("Not a start or end element");
         return _namespaces._namespaces[index];
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.NamespacesImpl._namespaces, javolution.xml.internal.stream.XMLStreamReaderImpl._namespaces, javolution.xml.stream.XMLStreamConstants.END_ELEMENT, javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
getPIData()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getPIData ()
Get the data section of a processing instruction.
Returns
the data (if processing instruction has any) or null if the processing instruction only has target.
Exceptions
IllegalStateException if the current event is not a XMLStreamConstants#PROCESSING_INSTRUCTION
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1305 of file XMLStreamReaderImpl.java.
{
         if (_eventType != XMLStreamConstants.PROCESSING_INSTRUCTION)
             throw illegalState("Not a processing instruction");
         int offset = _text.indexOf(' ') + _text.offset() + 1;
         CharArray piData = newSeq(offset, _text.length() - offset);
         return piData;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._text, javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), javolution.text.CharArray.indexOf(), javolution.text.CharArray.length(), javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq(), javolution.text.CharArray.offset(), and javolution.xml.stream.XMLStreamConstants.PROCESSING_INSTRUCTION.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
getPITarget()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getPITarget ()
Returns the target of a processing instruction.
Returns
the target.
Exceptions
IllegalStateException if the current event is not a XMLStreamConstants#PROCESSING_INSTRUCTION
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1313 of file XMLStreamReaderImpl.java.
{
         if (_eventType != XMLStreamConstants.PROCESSING_INSTRUCTION)
             throw illegalState("Not a processing instruction");
         CharArray piTarget = newSeq(_text.offset(),
                 _text.indexOf(' ') + _text.offset());
         return piTarget;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._text, javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), javolution.text.CharArray.indexOf(), javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq(), javolution.text.CharArray.offset(), and javolution.xml.stream.XMLStreamConstants.PROCESSING_INSTRUCTION.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll().
getPrefix()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getPrefix ()
Returns the prefix of the current event or null if the event does not have a prefix.
Returns
the prefix or null
Exceptions
IllegalStateException if not a START_ELEMENT or END_ELEMENT.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1294 of file XMLStreamReaderImpl.java.
{
         if ((_eventType != XMLStreamConstants.START_ELEMENT)
                 && (_eventType != XMLStreamConstants.END_ELEMENT))
             throw illegalState("Not a start or end element");
         if (_prefixSep < 0)
             return null;
         int offset = _qName.offset();
         CharArray prefix = newSeq(offset, _prefixSep - offset);
         return prefix;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._prefixSep, javolution.xml.internal.stream.XMLStreamReaderImpl._qName, javolution.xml.stream.XMLStreamConstants.END_ELEMENT, javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq(), javolution.text.CharArray.offset(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI().
getProperty()
Object javolution.xml.internal.stream.XMLStreamReaderImpl.getProperty (String name) throws IllegalArgumentException
Gets the value of a feature/property from the underlying implementation
Parameters
name the name of the property.
Returns
the value of the property.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1169 of file XMLStreamReaderImpl.java.
{
         if (name.equals(XMLInputFactory.IS_COALESCING)) {
             return Boolean.TRUE;
         } else if (name.equals(XMLInputFactory.ENTITIES)) {
             return _entities.getEntitiesMapping();
         } else {
             throw new IllegalArgumentException("Property: " + name
                     + " not supported");
         }
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._entities, javolution.xml.stream.XMLInputFactory.ENTITIES, javolution.xml.internal.stream.EntitiesImpl.getEntitiesMapping(), and javolution.xml.stream.XMLInputFactory.IS_COALESCING.
getQName() [1/2]
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getQName ()
Returns the qualified name of the current event.
Returns
the qualified name.
Exceptions
IllegalStateException if this not a START_ELEMENT or END_ELEMENT.
Definition at line 315 of file XMLStreamReaderImpl.java.
{
         if ((_eventType != XMLStreamConstants.START_ELEMENT)
                 && (_eventType != XMLStreamConstants.END_ELEMENT))
             throw new IllegalStateException(
                     "Not a start element or an end element");
         return _qName;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._qName, javolution.xml.stream.XMLStreamConstants.END_ELEMENT, and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll().
getQName() [2/2]
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getQName (int depth)
Returns the qualified name of the element at the specified level. This method can be used to retrieve the XPath of the current element.
Returns
the qualified name of the element at the specified level.
Exceptions
IllegalArgumentException if depth > getDepth()
Definition at line 330 of file XMLStreamReaderImpl.java.
{
         if (depth > this.getDepth())
             throw new IllegalArgumentException();
         return _elemStack[depth];
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._elemStack, and javolution.xml.internal.stream.XMLStreamReaderImpl.getDepth().
getText()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getText ()
Returns the current value of the parse event as a string, this returns the string value of a CHARACTERS event, returns the value of a COMMENT, the replacement value for an ENTITY_REFERENCE, the string value of a CDATA section, the string value for a SPACE event, or the String value of the internal subset of the DTD. If an ENTITY_REFERENCE has been resolved, any character data will be reported as CHARACTERS events.
Returns
the current text or null
Exceptions
IllegalStateException if this state is not a valid text state.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1321 of file XMLStreamReaderImpl.java.
{
         if ((_eventType != XMLStreamConstants.CHARACTERS)
                 && (_eventType != XMLStreamConstants.COMMENT)
                 && (_eventType != XMLStreamConstants.DTD))
             throw illegalState("Not a text event");
         return _text;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._text, javolution.xml.stream.XMLStreamConstants.CHARACTERS, javolution.xml.stream.XMLStreamConstants.COMMENT, javolution.xml.stream.XMLStreamConstants.DTD, and javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText(), javolution.xml.internal.stream.XMLStreamReaderImpl.getTextCharacters(), javolution.xml.internal.stream.XMLStreamReaderImpl.getTextLength(), javolution.xml.internal.stream.XMLStreamReaderImpl.getTextStart(), and javolution.xml.sax.XMLReaderImpl.parseAll().
getTextCharacters() [1/2]
char [] javolution.xml.internal.stream.XMLStreamReaderImpl.getTextCharacters ()
Returns an array which contains the characters from this event. This array should be treated as read-only and transient. I.e. the array will contain the text characters until the XMLStreamReader moves on to the next event. Attempts to hold onto the character array beyond that time or modify the contents of the array are breaches of the contract for this interface.
Returns
the current text or an empty array.
Exceptions
IllegalStateException if this state is not a valid text state.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1329 of file XMLStreamReaderImpl.java.
{
         return getText().array();
     }
References javolution.text.CharArray.array(), and javolution.xml.internal.stream.XMLStreamReaderImpl.getText().
getTextCharacters() [2/2]
int javolution.xml.internal.stream.XMLStreamReaderImpl.getTextCharacters (int sourceStart, char[] target, int targetStart, int length) throws XMLStreamException
Gets the the text associated with a CHARACTERS, SPACE or CDATA event. Text starting a "sourceStart" is copied into "target" starting at "targetStart". Up to "length" characters are copied. The number of characters actually copied is returned.
The "sourceStart" argument must be greater or equal to 0 and less than or equal to the number of characters associated with the event. Usually, one requests text starting at a "sourceStart" of 0. If the number of characters actually copied is less than the "length", then there is no more text. Otherwise, subsequent calls need to be made until all text has been retrieved. For example:
int length = 1024; char[] myBuffer = new char[ length ];
for (int sourceStart = 0 ; ; sourceStart += length) { int nCopied = stream.getTextCharacters(sourceStart, myBuffer, 0, length);
if (nCopied < length) break; } XMLStreamException may be thrown if there are any XML errors in the underlying source. The "targetStart" argument must be greater than or equal to 0 and less than the length of "target", Length must be greater than 0 and "targetStart + length" must be less than or equal to length of "target".
Parameters
sourceStart the index of te first character in the source array to copy
target the destination array
targetStart the start offset in the target array
length the number of characters to copy
Returns
the number of characters actually copied
Exceptions
XMLStreamException if the XML source is not well-formed.
IndexOutOfBoundsException if targetStart < 0 or > than the length of target
IndexOutOfBoundsException if length < 0 or targetStart + length > length of target
UnsupportedOperationException if this method is not supported.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1333 of file XMLStreamReaderImpl.java.
{
         CharArray text = getText();
         int copyLength = Math.min(length, text.length());
         System.arraycopy(text.array(), sourceStart + text.offset(), target,
                 targetStart, copyLength);
         return copyLength;
     }
References javolution.text.CharArray.array(), javolution.xml.internal.stream.XMLStreamReaderImpl.getText(), javolution.text.CharArray.length(), and javolution.text.CharArray.offset().
getTextLength()
int javolution.xml.internal.stream.XMLStreamReaderImpl.getTextLength ()
Returns the length of the sequence of characters for this Text event within the text character array.
Exceptions
IllegalStateException if this state is not a valid text state.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1342 of file XMLStreamReaderImpl.java.
{
         return getText().length();
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl.getText(), and javolution.text.CharArray.length().
getTextStart()
int javolution.xml.internal.stream.XMLStreamReaderImpl.getTextStart ()
Returns the offset into the text character array where the first character (of this text event) is stored.
Exceptions
IllegalStateException if this state is not a valid text state.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1346 of file XMLStreamReaderImpl.java.
{
         return getText().offset();
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl.getText(), and javolution.text.CharArray.offset().
getVersion()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.getVersion ()
Gets the xml version declared on the xml declaration.
Returns
the XML version or null
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1350 of file XMLStreamReaderImpl.java.
{
         return readPrologAttribute(VERSION);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl.readPrologAttribute(), and javolution.xml.internal.stream.XMLStreamReaderImpl.VERSION.
handleEndOfLine()
char javolution.xml.internal.stream.XMLStreamReaderImpl.handleEndOfLine (char c) throws XMLStreamException private
Handles end of line as per XML Spec. 2.11
Parameters
c the potential end of line character.
Returns
the replacement character for end of line.
Definition at line 877 of file XMLStreamReaderImpl.java.
{
         if (c == 0xD) { // Replaces #xD with #xA
             // Unless next char is #xA, then skip,
             // #xD#xA will be replaced by #xA
             if (_readIndex >= _readCount)
                 reloadBuffer();
             if ((_readIndex < _readCount) && (_readBuffer[_readIndex] == 0xA))
                 _readIndex++; // Skips 0xD
             c = (char) 0xA;
         }
         if (c == 0xA) {
             _location._line++;
             _location._column = -_readIndex; // column = 0
         } else if (c == 0x0) { throw new XMLStreamException(
                 "Illegal XML character U+0000", _location); }
         return c;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl._column, javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl._line, javolution.xml.internal.stream.XMLStreamReaderImpl._location, javolution.xml.internal.stream.XMLStreamReaderImpl._readBuffer, javolution.xml.internal.stream.XMLStreamReaderImpl._readCount, javolution.xml.internal.stream.XMLStreamReaderImpl._readIndex, and javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
hasName()
boolean javolution.xml.internal.stream.XMLStreamReaderImpl.hasName ()
Indicates if the current event has a name (is a START_ELEMENT or END_ELEMENT).
Returns
true if the current event has a name; false otherwise.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1367 of file XMLStreamReaderImpl.java.
{
         return (_eventType == XMLStreamConstants.START_ELEMENT)
                 || (_eventType == XMLStreamConstants.END_ELEMENT);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.stream.XMLStreamConstants.END_ELEMENT, and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
hasNext()
boolean javolution.xml.internal.stream.XMLStreamReaderImpl.hasNext () throws XMLStreamException
Returns true if there are more parsing events and false if there are no more events. This method will return false if the current state of the XMLStreamReader is END_DOCUMENT.
Returns
true if there are more events, false otherwise.
Exceptions
XMLStreamException if there is a fatal error detecting the next state.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1372 of file XMLStreamReaderImpl.java.
{
         return _eventType != XMLStreamConstants.END_DOCUMENT;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, and javolution.xml.stream.XMLStreamConstants.END_DOCUMENT.
hasText()
boolean javolution.xml.internal.stream.XMLStreamReaderImpl.hasText ()
Indicates if the current event has text. The following events have text: CHARACTERS, DTD ,ENTITY_REFERENCE, COMMENT, SPACE.
Returns
true if the current event as text; false otherwise.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1376 of file XMLStreamReaderImpl.java.
{
         return ((_eventType == XMLStreamConstants.CHARACTERS)
                 || (_eventType == XMLStreamConstants.COMMENT) || (_eventType == XMLStreamConstants.DTD))
                 && (_text.length() > 0);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._text, javolution.xml.stream.XMLStreamConstants.CHARACTERS, javolution.xml.stream.XMLStreamConstants.COMMENT, javolution.xml.stream.XMLStreamConstants.DTD, and javolution.text.CharArray.length().
illegalState()
IllegalStateException javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState (String msg) private
Definition at line 1432 of file XMLStreamReaderImpl.java.
{
         return new IllegalStateException(msg + " ("
                 + NAMES_OF_EVENTS[_eventType] + ")");
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, and javolution.xml.internal.stream.XMLStreamReaderImpl.NAMES_OF_EVENTS.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeCount(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeNamespace(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributePrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeType(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeValue(), javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceCount(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespacePrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPIData(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPITarget(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPrefix(), and javolution.xml.internal.stream.XMLStreamReaderImpl.getText().
increaseDataBuffer()
void javolution.xml.internal.stream.XMLStreamReaderImpl.increaseDataBuffer () private
Definition at line 1048 of file XMLStreamReaderImpl.java.
{
         // Note: The character data at any nesting level is discarded
         //       only when moving to outer nesting level (due to coalescing).
         //       This accumulation may cause resize of the data buffer if
         //       numerous elements at the same nesting level are separated by
         //       spaces or indentation.
         char[] tmp = new char[_data.length * 2];
         javolution.context.LogContext.info(new CharArray(
                 "XMLStreamReaderImpl: Data buffer increased to " + tmp.length));
         System.arraycopy(_data, 0, tmp, 0, _data.length);
         _data = tmp;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._data, and javolution.context.LogContext.info().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), and javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity().
increaseStack()
void javolution.xml.internal.stream.XMLStreamReaderImpl.increaseStack () private
Definition at line 1062 of file XMLStreamReaderImpl.java.
{
         CharArray[] tmp = new CharArray[_elemStack.length * 2];
         javolution.context.LogContext.info(new CharArray(
                 "XMLStreamReaderImpl: CharArray stack increased to "
                         + tmp.length));
         System.arraycopy(_elemStack, 0, tmp, 0, _elemStack.length);
         _elemStack = tmp;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._elemStack, javolution.context.LogContext.info(), and javolution.text.CharArray.length().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.processStartTag().
isAttributeSpecified()
boolean javolution.xml.internal.stream.XMLStreamReaderImpl.isAttributeSpecified (int index)
Indicates if this attribute was created by default.
Parameters
index the position of the attribute.
Returns
true if this is a default attribute; false otherwise.
Exceptions
IllegalStateException if not a START_ELEMENT or ATTRIBUTE.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1382 of file XMLStreamReaderImpl.java.
{
         if (_eventType != XMLStreamConstants.START_ELEMENT)
             throw new IllegalStateException("Not a start element");
         return _attributes.getValue(index) != null;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._attributes, javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.AttributesImpl.getValue(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
isCharacters()
boolean javolution.xml.internal.stream.XMLStreamReaderImpl.isCharacters ()
Indicates if the cursor points to character data.
Returns
true if the cursor points to character data; false otherwise.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1388 of file XMLStreamReaderImpl.java.
{
         return _eventType == XMLStreamConstants.CHARACTERS;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, and javolution.xml.stream.XMLStreamConstants.CHARACTERS.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.isWhiteSpace().
isEndElement()
boolean javolution.xml.internal.stream.XMLStreamReaderImpl.isEndElement ()
Indicates if the cursor points to an end tag.
Returns
true if the cursor points to a end tag; false otherwise.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1392 of file XMLStreamReaderImpl.java.
{
         return _eventType == XMLStreamConstants.END_ELEMENT;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, and javolution.xml.stream.XMLStreamConstants.END_ELEMENT.
isEndOfStream()
boolean javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream () throws XMLStreamException private
Detects end of stream.
Returns
true if end of stream has being reached and the event type (CHARACTERS or END_DOCUMENT) has been set; false otherwise.
Definition at line 845 of file XMLStreamReaderImpl.java.
{
         if (_readIndex >= _readCount)
             reloadBuffer();
         if (_readCount <= 0) {
             // _state == STATE_CHARACTERS (otherwise reloadBuffer() exception)
             if (_eventType == END_DOCUMENT)
                 throw new XMLStreamException(
                         "End document has already been reached");
             int length = _index - _start;
             if (length > 0) { // Flushes trailing characters.
                 if (_charactersPending) {
                     _text.setArray(_data, _text.offset(), _text.length()
                             + length); // Coalescing.
                 } else {
                     _text = newSeq(_start, length);
                 }
                 _start = _index;
                 _eventType = CHARACTERS;
             } else {
                 _eventType = END_DOCUMENT;
             }
             return true;
         }
         return false;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._charactersPending, javolution.xml.internal.stream.XMLStreamReaderImpl._data, javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._index, javolution.xml.internal.stream.XMLStreamReaderImpl._readCount, javolution.xml.internal.stream.XMLStreamReaderImpl._readIndex, javolution.xml.internal.stream.XMLStreamReaderImpl._start, javolution.xml.internal.stream.XMLStreamReaderImpl._text, javolution.xml.stream.XMLStreamConstants.CHARACTERS, javolution.xml.stream.XMLStreamConstants.END_DOCUMENT, javolution.text.CharArray.length(), javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq(), javolution.text.CharArray.offset(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), and javolution.text.CharArray.setArray().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
isStandalone()
boolean javolution.xml.internal.stream.XMLStreamReaderImpl.isStandalone ()
Gets the standalone declaration from the xml declaration.
Returns
true if this is standalone; false otherwise.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1356 of file XMLStreamReaderImpl.java.
{
         CharArray standalone = readPrologAttribute(STANDALONE);
         return (standalone != null) ? standalone.equals("no") : true;
     }
References javolution.text.CharArray.equals(), javolution.xml.internal.stream.XMLStreamReaderImpl.readPrologAttribute(), and javolution.xml.internal.stream.XMLStreamReaderImpl.STANDALONE.
isStartElement()
boolean javolution.xml.internal.stream.XMLStreamReaderImpl.isStartElement ()
Indicates if the cursor points to a start tag.
Returns
true if the cursor points to a start tag; false otherwise.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1396 of file XMLStreamReaderImpl.java.
{
         return _eventType == XMLStreamConstants.START_ELEMENT;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
isUTF8()
static boolean javolution.xml.internal.stream.XMLStreamReaderImpl.isUTF8 (Object encoding) static private
Definition at line 231 of file XMLStreamReaderImpl.java.
{
         return encoding.equals("utf-8") || encoding.equals("UTF-8")
                 || encoding.equals("ASCII") || encoding.equals("utf8")
                 || encoding.equals("UTF8");
     }
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
isWhiteSpace() [1/2]
boolean javolution.xml.internal.stream.XMLStreamReaderImpl.isWhiteSpace ()
Indicates if the cursor points to character data that consists of all whitespace.
Returns
true if the cursor points to whitespaces; false otherwise.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1400 of file XMLStreamReaderImpl.java.
{
         if (isCharacters()) {
             char[] chars = _text.array();
             for (int i = _text.offset(), end = _text.offset() + _text.length(); i < end;) {
                 if (!isWhiteSpace(chars[i++]))
                     return false;
             }
             return true;
         }
         return false;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._text, javolution.text.CharArray.array(), javolution.xml.internal.stream.XMLStreamReaderImpl.isCharacters(), javolution.text.CharArray.length(), and javolution.text.CharArray.offset().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.nextTag().
isWhiteSpace() [2/2]
static boolean javolution.xml.internal.stream.XMLStreamReaderImpl.isWhiteSpace (char c) static private
Definition at line 1413 of file XMLStreamReaderImpl.java.
{
         return (c == 0x20) || (c == 0x9) || (c == 0xD) || (c == 0xA);
     }
isXMLNS()
static boolean javolution.xml.internal.stream.XMLStreamReaderImpl.isXMLNS (CharArray chars) static private
Definition at line 964 of file XMLStreamReaderImpl.java.
{
         return (chars.length() == 5) && (chars.charAt(0) == 'x')
                 && (chars.charAt(1) == 'm') && (chars.charAt(2) == 'l')
                 && (chars.charAt(3) == 'n') && (chars.charAt(4) == 's');
     }
References javolution.text.CharArray.charAt(), and javolution.text.CharArray.length().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.processAttribute().
newSeq()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq (int offset, int length) private
Definition at line 1016 of file XMLStreamReaderImpl.java.
{
         CharArray seq = (_seqsIndex < _seqsCapacity) ? _seqs[_seqsIndex++]
                 : newSeq2();
         return seq.setArray(_data, offset, length);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._data, javolution.xml.internal.stream.XMLStreamReaderImpl._seqs, javolution.xml.internal.stream.XMLStreamReaderImpl._seqsCapacity, javolution.xml.internal.stream.XMLStreamReaderImpl._seqsIndex, javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq2(), and javolution.text.CharArray.setArray().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText(), javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPIData(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPITarget(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.processAttribute(), and javolution.xml.internal.stream.XMLStreamReaderImpl.readPrologAttribute().
newSeq2()
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq2 () private
Definition at line 1022 of file XMLStreamReaderImpl.java.
{
         _createSeqLogic.run();
         return _seqs[_seqsIndex++];
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._createSeqLogic, javolution.xml.internal.stream.XMLStreamReaderImpl._seqs, and javolution.xml.internal.stream.XMLStreamReaderImpl._seqsIndex.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq().
next()
int javolution.xml.internal.stream.XMLStreamReaderImpl.next () throws XMLStreamException
Gets next parsing event - contiguous character data is returned into a single chunk.
By default entity references must be expanded and reported transparently to the application. An exception will be thrown if an entity reference cannot be expanded. If element content is empty (i.e. content is "") then no CHARACTERS event will be reported.
Given the following XML:
<foo><!–description-->content text<![CDATA[<greeting>Hello</greeting>]]>other content</foo>
The behavior of calling next() when being on foo will be:
1- the comment (COMMENT)
2- then the characters section (CHARACTERS)
3- then the CDATA section (another CHARACTERS)
4- then the next characters section (another CHARACTERS)
5- then the END_ELEMENT
NOTE: empty element (such as <tag/>) will be reported with two separate events: START_ELEMENT, END_ELEMENT - This preserves parsing equivalency of empty element to <tag></tag>.
This method will throw an IllegalStateException if it is called after hasNext() returns false.
Returns
the integer code corresponding to the current parse event
Exceptions
NoSuchElementException if this is called when hasNext() returns false
XMLStreamException if there is an error processing the underlying XML source
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 380 of file XMLStreamReaderImpl.java.
{
         // Clears previous state.
         if (_eventType == START_ELEMENT) {
             if (_isEmpty) { // Previous empty tag, generates END_TAG automatically.
                 _isEmpty = false;
                 return _eventType = END_ELEMENT;
             }
         } else if (_eventType == END_ELEMENT) {
             _namespaces.pop();
             CharArray startElem = _elemStack[_depth--];
             _start = _index = startElem.offset();
             while (_seqs[--_seqsIndex] != startElem) { // Recycles CharArray instances.
             }
         }
         // Reader loop.
         while (true) {
             // Main character reading block.
             if ((_readIndex >= _readCount) && isEndOfStream())
                 return _eventType; // END_DOCUMENT or CHARACTERS.
             char c = _readBuffer[_readIndex++];
             if (c <= '&')
                 c = (c == '&') ? replaceEntity()
                         : (c < ' ') ? handleEndOfLine(c) : c;
             _data[_index++] = c;
             // Main processing.
             //
             switch (_state) {
                 case STATE_CHARACTERS:
                     while (true) { // Read characters data all at once.
                         if (c == '<') {
                             int length = _index - _start - 1;
                             if (length > 0) {
                                 if (_charactersPending) {
                                     _text.setArray(_data, _text.offset(),
                                             _text.length() + length); // Coalescing.
                                 } else {
                                     _text = newSeq(_start, length);
                                     _charactersPending = true;
                                 }
                                 _start = _index - 1; // Keeps '<' as part of markup.
                             }
                             _state = STATE_MARKUP;
                             break;
                         }
                         // Local character reading block.
                         if ((_readIndex >= _readCount) && isEndOfStream())
                             return _eventType;
                         c = _readBuffer[_readIndex++];
                         if (c <= '&')
                             c = (c == '&') ? replaceEntity()
                                     : (c < ' ') ? handleEndOfLine(c) : c;
                         _data[_index++] = c;
                     }
                     break;
                 case STATE_CDATA:
                     while (true) { // Reads CDATA all at once.
                         if ((c == '>') && (_index - _start >= 3)
                                 && (_data[_index - 2] == ']')
                                 && (_data[_index - 3] == ']')) {
                             _index -= 3;
                             int length = _index - _start;
                             if (length > 0) { // Not empty.
                                 if (_charactersPending) {
                                     _text.setArray(_data, _text.offset(),
                                             _text.length() + length); // Coalescing.
                                 } else {
                                     _text = newSeq(_start, length);
                                     _charactersPending = true;
                                 }
                             }
                             _start = _index;
                             _state = STATE_CHARACTERS;
                             break;
                         }
                         // Local character reading block.
                         if (_readIndex >= _readCount)
                             reloadBuffer();
                         c = _readBuffer[_readIndex++];
                         if (c < ' ')
                             c = handleEndOfLine(c);
                         _data[_index++] = c;
                     }
                     break;
                 case STATE_DTD:
                     if (c == '>') {
                         _text = newSeq(_start, _index - _start);
                         _index = _start; // Do not keep DTD.
                         _state = STATE_CHARACTERS;
                         return _eventType = DTD;
                     } else if (c == '[') {
                         _state = STATE_DTD_INTERNAL;
                     }
                     break;
                 case STATE_DTD_INTERNAL:
                     if (c == ']') {
                         _state = STATE_DTD;
                     }
                     break;
                 case STATE_MARKUP: // Starts with '<'
                     if (_index - _start == 2) {
                         if (c == '/') {
                             _start = _index = _index - 2;
                             _state = STATE_CLOSE_TAGxREAD_ELEM_NAME;
                             _prefixSep = -1;
                             if (_charactersPending) { // Flush characters event.
                                 _charactersPending = false;
                                 return _eventType = CHARACTERS;
                             }
                         } else if (c == '?') {
                             _start = _index = _index - 2;
                             _state = STATE_PI;
                             if (_charactersPending) { // Flush characters event.
                                 _charactersPending = false;
                                 return _eventType = CHARACTERS;
                             }
                         } else if (c != '!') { // Element tag (first letter).
                             _data[_start] = c;
                             _index = _start + 1;
                             _state = STATE_OPEN_TAGxREAD_ELEM_NAME;
                             _prefixSep = -1;
                             if (_charactersPending) { // Flush character event.
                                 _charactersPending = false;
                                 return _eventType = CHARACTERS;
                             }
                         }
                     } else if ((_index - _start == 4)
                             && (_data[_start + 1] == '!')
                             && (_data[_start + 2] == '-')
                             && (_data[_start + 3] == '-')) {
                         _start = _index = _index - 4; // Removes <!--
                         _state = STATE_COMMENT;
                         if (_charactersPending) { // Flush character event.
                             _charactersPending = false;
                             return _eventType = CHARACTERS;
                         }
                     } else if ((_index - _start == 9)
                             && (_data[_start + 1] == '!')
                             && (_data[_start + 2] == '[')
                             && (_data[_start + 3] == 'C')
                             && (_data[_start + 4] == 'D')
                             && (_data[_start + 5] == 'A')
                             && (_data[_start + 6] == 'T')
                             && (_data[_start + 7] == 'A')
                             && (_data[_start + 8] == '[')) {
                         _start = _index = _index - 9; // Do not keep <![CDATA[
                         _state = STATE_CDATA;
                     } else if ((_index - _start == 9)
                             && (_data[_start + 1] == '!')
                             && (_data[_start + 2] == 'D')
                             && (_data[_start + 3] == 'O')
                             && (_data[_start + 4] == 'C')
                             && (_data[_start + 5] == 'T')
                             && (_data[_start + 6] == 'Y')
                             && (_data[_start + 7] == 'P')
                             && (_data[_start + 8] == 'E')) {
                         // Keeps <!DOCTYPE as part of DTD.
                         _state = STATE_DTD;
                     } else {
                         // Ignores, e.g. <!ELEMENT <!ENTITY...
                     }
                     break;
                 case STATE_COMMENT:
                     while (true) { // Read comment all at once.
                         if ((c == '>') && (_index - _start >= 3)
                                 && (_data[_index - 2] == '-')
                                 && (_data[_index - 3] == '-')) {
                             _index -= 3; // Removes -->
                             _text = newSeq(_start, _index - _start);
                             _state = STATE_CHARACTERS;
                             _index = _start; // Do not keep comments.
                             return _eventType = COMMENT;
                         }
                         // Local character reading block.
                         if (_readIndex >= _readCount)
                             reloadBuffer();
                         c = _readBuffer[_readIndex++];
                         if (c < ' ')
                             c = handleEndOfLine(c);
                         _data[_index++] = c;
                     }
                 case STATE_PI:
                     if ((c == '>') && (_index - _start >= 2)
                             && (_data[_index - 2] == '?')) {
                         _index -= 2; // Removes ?>
                         _text = newSeq(_start, _index - _start);
                         _state = STATE_CHARACTERS;
                         _index = _start; // Do not keep processing instructions.
                         return _eventType = PROCESSING_INSTRUCTION;
                     }
                     break;
                 // OPEN_TAG:
                 case STATE_OPEN_TAGxREAD_ELEM_NAME:
                     _attributes.reset();
                     _namespaces.push();
                     while (true) { // Read element name all at once.
                         if (c < '@') { // Else avoid multiple checks.
                             if (c == '>') {
                                 _qName = newSeq(_start, --_index - _start);
                                 _start = _index;
                                 _state = STATE_CHARACTERS;
                                 processStartTag();
                                 _isEmpty = false;
                                 return _eventType = START_ELEMENT;
                             } else if (c == '/') {
                                 _qName = newSeq(_start, --_index - _start);
                                 _start = _index;
                                 _state = STATE_OPEN_TAGxEMPTY_TAG;
                                 break;
                             } else if (c == ':') {
                                 _prefixSep = _index - 1;
                             } else if (c <= ' ') {
                                 _qName = newSeq(_start, --_index - _start);
                                 _state = STATE_OPEN_TAGxELEM_NAME_READ;
                                 break;
                             }
                         }
                         if (_readIndex >= _readCount)
                             reloadBuffer();
                         c = _data[_index++] = _readBuffer[_readIndex++];
                     }
                     break;
                 case STATE_OPEN_TAGxELEM_NAME_READ:
                     if (c == '>') {
                         _start = --_index;
                         _state = STATE_CHARACTERS;
                         processStartTag();
                         _isEmpty = false;
                         return _eventType = START_ELEMENT;
                     } else if (c == '/') {
                         _state = STATE_OPEN_TAGxEMPTY_TAG;
                     } else if (c > ' ') {
                         _start = _index - 1; // Includes current character.
                         _attrPrefixSep = -1;
                         _state = STATE_OPEN_TAGxREAD_ATTR_NAME;
                     }
                     break;
                 case STATE_OPEN_TAGxREAD_ATTR_NAME:
                     while (true) { // Read attribute name all at once.
                         if (c < '@') { // Else avoid multiple checks.
                             if (c <= ' ') {
                                 _attrQName = newSeq(_start, --_index - _start);
                                 _state = STATE_OPEN_TAGxATTR_NAME_READ;
                                 break;
                             } else if (c == '=') {
                                 _attrQName = newSeq(_start, --_index - _start);
                                 _state = STATE_OPEN_TAGxEQUAL_READ;
                                 break;
                             } else if (c == ':') {
                                 _attrPrefixSep = _index - 1;
                             }
                         }
                         if (_readIndex >= _readCount)
                             reloadBuffer();
                         _data[_index++] = c = _readBuffer[_readIndex++];
                     }
                     break;
                 case STATE_OPEN_TAGxATTR_NAME_READ:
                     if (c == '=') {
                         --_index;
                         _state = STATE_OPEN_TAGxEQUAL_READ;
                     } else if (c > ' ') { throw new XMLStreamException(
                             "'=' expected", _location); }
                     break;
                 case STATE_OPEN_TAGxEQUAL_READ:
                     if (c == '\'') {
                         _start = --_index;
                         _state = STATE_OPEN_TAGxREAD_ATTR_VALUE_SIMPLE_QUOTE;
                     } else if (c == '\"') {
                         _start = --_index;
                         _state = STATE_OPEN_TAGxREAD_ATTR_VALUE_DOUBLE_QUOTE;
                     } else if (c > ' ') { throw new XMLStreamException(
                             "Quotes expected", _location); }
                     break;
                 case STATE_OPEN_TAGxREAD_ATTR_VALUE_SIMPLE_QUOTE:
                     while (true) { // Read attribute value all at once.
                         if (c == '\'') {
                             _attrValue = newSeq(_start, --_index - _start);
                             processAttribute();
                             _state = STATE_OPEN_TAGxELEM_NAME_READ;
                             break;
                         }
                         // Local character reading block.
                         if (_readIndex >= _readCount)
                             reloadBuffer();
                         c = _readBuffer[_readIndex++];
                         if (c == '&')
                             c = replaceEntity();
                         _data[_index++] = c;
                     }
                     break;
                 case STATE_OPEN_TAGxREAD_ATTR_VALUE_DOUBLE_QUOTE:
                     while (true) { // Read attribute value all at once.
                         if (c == '\"') {
                             _attrValue = newSeq(_start, --_index - _start);
                             processAttribute();
                             _state = STATE_OPEN_TAGxELEM_NAME_READ;
                             break;
                         }
                         // Local character reading block.
                         if (_readIndex >= _readCount)
                             reloadBuffer();
                         c = _readBuffer[_readIndex++];
                         if (c == '&')
                             c = replaceEntity();
                         _data[_index++] = c;
                     }
                     break;
                 case STATE_OPEN_TAGxEMPTY_TAG:
                     if (c == '>') {
                         _start = --_index;
                         _state = STATE_CHARACTERS;
                         processStartTag();
                         _isEmpty = true;
                         return _eventType = START_ELEMENT;
                     } else {
                         throw new XMLStreamException("'>' expected", _location);
                     }
                     // CLOSE_TAG:
                 case STATE_CLOSE_TAGxREAD_ELEM_NAME:
                     while (true) { // Element name can be read all at once.
                         if (c < '@') { // Else avoid multiple checks.
                             if (c == '>') {
                                 _qName = newSeq(_start, --_index - _start);
                                 _start = _index;
                                 _state = STATE_CHARACTERS;
                                 processEndTag();
                                 return _eventType = END_ELEMENT;
                             } else if (c == ':') {
                                 _prefixSep = _index - 1;
                             } else if (c <= ' ') {
                                 _qName = newSeq(_start, --_index - _start);
                                 _state = STATE_CLOSE_TAGxELEM_NAME_READ;
                                 break;
                             }
                         }
                         if (_readIndex >= _readCount)
                             reloadBuffer();
                         c = _data[_index++] = _readBuffer[_readIndex++];
                     }
                     break;
                 case STATE_CLOSE_TAGxELEM_NAME_READ:
                     if (c == '>') {
                         _start = --_index;
                         _state = STATE_CHARACTERS;
                         processEndTag();
                         return _eventType = END_ELEMENT;
                     } else if (c > ' ') { throw new XMLStreamException(
                             "'>' expected", _location); }
                     break;
                 default:
                     throw new XMLStreamException("State unknown: " + _state,
                             _location);
             }
         }
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._attributes, javolution.xml.internal.stream.XMLStreamReaderImpl._attrPrefixSep, javolution.xml.internal.stream.XMLStreamReaderImpl._attrQName, javolution.xml.internal.stream.XMLStreamReaderImpl._attrValue, javolution.xml.internal.stream.XMLStreamReaderImpl._charactersPending, javolution.xml.internal.stream.XMLStreamReaderImpl._data, javolution.xml.internal.stream.XMLStreamReaderImpl._depth, javolution.xml.internal.stream.XMLStreamReaderImpl._elemStack, javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._index, javolution.xml.internal.stream.XMLStreamReaderImpl._isEmpty, javolution.xml.internal.stream.XMLStreamReaderImpl._location, javolution.xml.internal.stream.XMLStreamReaderImpl._namespaces, javolution.xml.internal.stream.XMLStreamReaderImpl._prefixSep, javolution.xml.internal.stream.XMLStreamReaderImpl._qName, javolution.xml.internal.stream.XMLStreamReaderImpl._readBuffer, javolution.xml.internal.stream.XMLStreamReaderImpl._readCount, javolution.xml.internal.stream.XMLStreamReaderImpl._readIndex, javolution.xml.internal.stream.XMLStreamReaderImpl._seqs, javolution.xml.internal.stream.XMLStreamReaderImpl._seqsIndex, javolution.xml.internal.stream.XMLStreamReaderImpl._start, javolution.xml.internal.stream.XMLStreamReaderImpl._state, javolution.xml.internal.stream.XMLStreamReaderImpl._text, javolution.xml.stream.XMLStreamConstants.CHARACTERS, javolution.xml.stream.XMLStreamConstants.COMMENT, javolution.xml.stream.XMLStreamConstants.DTD, javolution.xml.stream.XMLStreamConstants.END_ELEMENT, javolution.xml.internal.stream.XMLStreamReaderImpl.handleEndOfLine(), javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream(), javolution.text.CharArray.length(), javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq(), javolution.text.CharArray.offset(), javolution.xml.internal.stream.NamespacesImpl.pop(), javolution.xml.internal.stream.XMLStreamReaderImpl.processAttribute(), javolution.xml.internal.stream.XMLStreamReaderImpl.processEndTag(), javolution.xml.stream.XMLStreamConstants.PROCESSING_INSTRUCTION, javolution.xml.internal.stream.XMLStreamReaderImpl.processStartTag(), javolution.xml.internal.stream.NamespacesImpl.push(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity(), javolution.xml.internal.stream.AttributesImpl.reset(), javolution.text.CharArray.setArray(), javolution.xml.stream.XMLStreamConstants.START_ELEMENT, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_CDATA, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_CHARACTERS, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_CLOSE_TAGxELEM_NAME_READ, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_CLOSE_TAGxREAD_ELEM_NAME, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_COMMENT, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_DTD, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_DTD_INTERNAL, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_MARKUP, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxATTR_NAME_READ, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxELEM_NAME_READ, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxEMPTY_TAG, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxEQUAL_READ, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxREAD_ATTR_NAME, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxREAD_ATTR_VALUE_DOUBLE_QUOTE, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxREAD_ATTR_VALUE_SIMPLE_QUOTE, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxREAD_ELEM_NAME, and javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_PI.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText(), javolution.xml.XMLFormat< T >.InputElement.getNext(), javolution.xml.internal.stream.XMLStreamReaderImpl.nextTag(), javolution.xml.sax.XMLReaderImpl.parseAll(), javolution.xml.XMLFormat< T >.InputElement.readReference(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
nextTag()
int javolution.xml.internal.stream.XMLStreamReaderImpl.nextTag () throws XMLStreamException
Skips any white space (isWhiteSpace() returns true), COMMENT, or PROCESSING_INSTRUCTION, until a START_ELEMENT or END_ELEMENT is reached. If other than white space characters, COMMENT, PROCESSING_INSTRUCTION, START_ELEMENT, END_ELEMENT are encountered, an exception is thrown. This method should be used when processing element-only content seperated by white space.
Precondition: none
Postcondition: the current event is START_ELEMENT or END_ELEMENT and cursor may have moved over any whitespace event.
Essentially it does the following (implementations are free to optimized but must do equivalent processing):
  int eventType = next();
  while((eventType == XMLStreamConstants.CHARACTERS && isWhiteSpace()) // skip whitespace
  || (eventType == XMLStreamConstants.CDATA && isWhiteSpace())
  // skip whitespace
  || eventType == XMLStreamConstants.SPACE
  || eventType == XMLStreamConstants.PROCESSING_INSTRUCTION
  || eventType == XMLStreamConstants.COMMENT
  ) {
  eventType = next();
  }
  if (eventType != XMLStreamConstants.START_ELEMENT && eventType != XMLStreamConstants.END_ELEMENT) {
  throw new String XMLStreamException("expected start or end tag", getLocation());
  }
  return eventType;
Returns
the event type of the element read (START_ELEMENT or END_ELEMENT)
Exceptions
XMLStreamException if the current event is not white space, PROCESSING_INSTRUCTION, START_ELEMENT or END_ELEMENT
NoSuchElementException if this is called when hasNext() returns false
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1417 of file XMLStreamReaderImpl.java.
{
         int eventType = next();
         while (eventType == XMLStreamConstants.COMMENT
                 || eventType == XMLStreamConstants.PROCESSING_INSTRUCTION
                 || eventType == XMLStreamConstants.DTD
                 || (eventType == XMLStreamConstants.CHARACTERS && isWhiteSpace())) {
             eventType = next();
         }
         if (eventType != XMLStreamConstants.START_ELEMENT
                 && eventType != XMLStreamConstants.END_ELEMENT)
             throw new XMLStreamException("Tag expected (but found "
                     + NAMES_OF_EVENTS[_eventType] + ")");
         return eventType;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.stream.XMLStreamConstants.CHARACTERS, javolution.xml.stream.XMLStreamConstants.COMMENT, javolution.xml.stream.XMLStreamConstants.DTD, javolution.xml.stream.XMLStreamConstants.END_ELEMENT, javolution.xml.internal.stream.XMLStreamReaderImpl.isWhiteSpace(), javolution.xml.internal.stream.XMLStreamReaderImpl.NAMES_OF_EVENTS, javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.stream.XMLStreamConstants.PROCESSING_INSTRUCTION, and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
Referenced by javolution.xml.XMLFormat< T >.InputElement.hasNext().
processAttribute()
void javolution.xml.internal.stream.XMLStreamReaderImpl.processAttribute () throws XMLStreamException private
Processes the attribute just read.
Definition at line 938 of file XMLStreamReaderImpl.java.
{
         if (_attrPrefixSep < 0) { // No prefix.
             if (isXMLNS(_attrQName)) { // Sets default namespace.
                 _namespaces.setPrefix(_namespaces._defaultNsPrefix, _attrValue);
             } else {
                 _attributes.addAttribute(_attrQName, null, _attrQName,
                         _attrValue);
             }
         } else { // Prefix.
             final int offset = _attrQName.offset();
             final int length = _attrQName.length();
             CharArray prefix = newSeq(offset, _attrPrefixSep - offset);
             CharArray localName = newSeq(_attrPrefixSep + 1, offset + length
                     - _attrPrefixSep - 1);
             if (isXMLNS(prefix)) { // Namespace association.
                 _namespaces.setPrefix(localName, _attrValue);
             } else {
                 _attributes.addAttribute(localName, prefix, _attrQName,
                         _attrValue);
             }
         }
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._attributes, javolution.xml.internal.stream.XMLStreamReaderImpl._attrPrefixSep, javolution.xml.internal.stream.XMLStreamReaderImpl._attrQName, javolution.xml.internal.stream.XMLStreamReaderImpl._attrValue, javolution.xml.internal.stream.NamespacesImpl._defaultNsPrefix, javolution.xml.internal.stream.XMLStreamReaderImpl._namespaces, javolution.xml.internal.stream.AttributesImpl.addAttribute(), javolution.xml.internal.stream.XMLStreamReaderImpl.isXMLNS(), javolution.text.CharArray.length(), javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq(), javolution.text.CharArray.offset(), and javolution.xml.internal.stream.NamespacesImpl.setPrefix().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
processEndTag()
void javolution.xml.internal.stream.XMLStreamReaderImpl.processEndTag () throws XMLStreamException private
Definition at line 970 of file XMLStreamReaderImpl.java.
{
         if (!_qName.equals(_elemStack[_depth]))
             throw new XMLStreamException("Unexpected end tag for " + _qName,
                     _location);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._depth, javolution.xml.internal.stream.XMLStreamReaderImpl._elemStack, javolution.xml.internal.stream.XMLStreamReaderImpl._location, javolution.xml.internal.stream.XMLStreamReaderImpl._qName, and javolution.text.CharArray.equals().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
processStartTag()
void javolution.xml.internal.stream.XMLStreamReaderImpl.processStartTag () throws XMLStreamException private
Definition at line 976 of file XMLStreamReaderImpl.java.
{
         if (++_depth >= _elemStack.length) {
             increaseStack();
         }
         _elemStack[_depth] = _qName;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._depth, javolution.xml.internal.stream.XMLStreamReaderImpl._elemStack, javolution.xml.internal.stream.XMLStreamReaderImpl._qName, javolution.xml.internal.stream.XMLStreamReaderImpl.increaseStack(), and javolution.text.CharArray.length().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
readPrologAttribute()
final CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.readPrologAttribute (CharSequence name) private
Definition at line 1477 of file XMLStreamReaderImpl.java.
{
         if (_prolog == null)
             return null;
         final int READ_EQUAL = 0;
         final int READ_QUOTE = 1;
         final int VALUE_SIMPLE_QUOTE = 2;
         final int VALUE_DOUBLE_QUOTE = 3;
         int i = _prolog.indexOf(name);
         if (i >= 0) {
             i += _prolog.offset();
             int maxIndex = _prolog.offset() + _prolog.length();
             i += name.length();
             int state = READ_EQUAL;
             int valueOffset = 0;
             while (i < maxIndex) {
                 char c = _prolog.array()[i++];
                 switch (state) {
                     case READ_EQUAL:
                         if (c == '=') {
                             state = READ_QUOTE;
                         }
                         break;
                     case READ_QUOTE:
                         if (c == '"') {
                             state = VALUE_DOUBLE_QUOTE;
                             valueOffset = i;
                         } else if (c == '\'') {
                             state = VALUE_SIMPLE_QUOTE;
                             valueOffset = i;
                         }
                         break;
                     case VALUE_SIMPLE_QUOTE:
                         if (c == '\'')
                             return newSeq(valueOffset, i - valueOffset - 1);
                         break;
                     case VALUE_DOUBLE_QUOTE:
                         if (c == '"')
                             return newSeq(valueOffset, i - valueOffset - 1);
                         break;
                 }
             }
         }
         return null;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._prolog, javolution.text.CharArray.array(), javolution.text.CharArray.indexOf(), javolution.text.CharArray.length(), javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq(), and javolution.text.CharArray.offset().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getCharacterEncodingScheme(), javolution.xml.internal.stream.XMLStreamReaderImpl.getVersion(), javolution.xml.internal.stream.XMLStreamReaderImpl.isStandalone(), and javolution.xml.internal.stream.XMLStreamReaderImpl.standaloneSet().
reloadBuffer()
void javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer () throws XMLStreamException private
Reloads data buffer.
Parameters
detectEndOfStream indicates
Returns
true if the buffer has been reloaded; false if the end of stream has being reached and the event type (CHARACTERS or END_DOCUMENT) has been set.
Definition at line 818 of file XMLStreamReaderImpl.java.
{
         if (_reader == null)
             throw new XMLStreamException("Input not specified");
         _location._column += _readIndex;
         _location._charactersRead += _readIndex;
         _readIndex = 0;
         try {
             _readCount = _reader.read(_readBuffer, 0, _readBuffer.length);
             if ((_readCount <= 0)
                     && ((_depth != 0) || (_state != STATE_CHARACTERS)))
                 throw new XMLStreamException("Unexpected end of document",
                         _location);
         } catch (IOException e) {
             throw new XMLStreamException(e);
         }
         while ((_index + _readCount) >= _data.length) { // Potential overflow.
             increaseDataBuffer();
         }
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl._charactersRead, javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl._column, javolution.xml.internal.stream.XMLStreamReaderImpl._data, javolution.xml.internal.stream.XMLStreamReaderImpl._depth, javolution.xml.internal.stream.XMLStreamReaderImpl._index, javolution.xml.internal.stream.XMLStreamReaderImpl._location, javolution.xml.internal.stream.XMLStreamReaderImpl._readBuffer, javolution.xml.internal.stream.XMLStreamReaderImpl._readCount, javolution.xml.internal.stream.XMLStreamReaderImpl._reader, javolution.xml.internal.stream.XMLStreamReaderImpl._readIndex, javolution.xml.internal.stream.XMLStreamReaderImpl._state, javolution.xml.internal.stream.XMLStreamReaderImpl.increaseDataBuffer(), and javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_CHARACTERS.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.handleEndOfLine(), javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), and javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity().
replaceEntity()
char javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity () throws XMLStreamException private
Replaces an entity if the current state allows it.
Returns
the next character after the text replacement or '&' if no replacement took place.
Definition at line 901 of file XMLStreamReaderImpl.java.
{
         if ((_state == STATE_COMMENT) || (_state == STATE_PI)
                 || (_state == STATE_CDATA))
             return '&'; // (&2.4)
         int start = _index; // Index of first replacement character.
         _data[_index++] = '&';
         while (true) {
             if (_readIndex >= _readCount)
                 reloadBuffer();
             char c = _data[_index++] = _readBuffer[_readIndex++];
             if (c == ';')
                 break;
             if (c <= ' ')
                 throw new XMLStreamException("';' expected", _location);
         }
         // Ensures that the replacement string holds in the data buffer.
         while (start + _entities.getMaxLength() >= _data.length) {
             increaseDataBuffer();
         }
         // Replaces the entity.
         int length = _entities.replaceEntity(_data, start, _index - start);
         // Returns the next character after entity unless ampersand.
         _index = start + length;
         // Local character reading block.
         if (_readIndex >= _readCount)
             reloadBuffer();
         char c = _readBuffer[_readIndex++];
         return (c == '&') ? (c = replaceEntity()) : c;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._data, javolution.xml.internal.stream.XMLStreamReaderImpl._entities, javolution.xml.internal.stream.XMLStreamReaderImpl._index, javolution.xml.internal.stream.XMLStreamReaderImpl._location, javolution.xml.internal.stream.XMLStreamReaderImpl._readBuffer, javolution.xml.internal.stream.XMLStreamReaderImpl._readCount, javolution.xml.internal.stream.XMLStreamReaderImpl._readIndex, javolution.xml.internal.stream.XMLStreamReaderImpl._state, javolution.xml.internal.stream.EntitiesImpl.getMaxLength(), javolution.xml.internal.stream.XMLStreamReaderImpl.increaseDataBuffer(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), javolution.xml.internal.stream.EntitiesImpl.replaceEntity(), javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_CDATA, javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_COMMENT, and javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_PI.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
require()
void javolution.xml.internal.stream.XMLStreamReaderImpl.require (int type, CharSequence namespaceURI, CharSequence localName) throws XMLStreamException
Tests if the current event is of the given type and if the namespace and name match the current namespace and name of the current event. If the namespaceURI is null it is not checked for equality, if the localName is null it is not checked for equality.
Parameters
type the event type.
namespaceURI the uri of the event, may be null.
localName the localName of the event, may be null.
Exceptions
XMLStreamException if the required values are not matched.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1118 of file XMLStreamReaderImpl.java.
{
         if (_eventType != type)
             throw new XMLStreamException("Expected event: "
                     + NAMES_OF_EVENTS[type] + ", found event: "
                     + NAMES_OF_EVENTS[_eventType]);
         if ((namespaceURI != null) && !getNamespaceURI().equals(namespaceURI))
             throw new XMLStreamException("Expected namespace URI: "
                     + namespaceURI + ", found: " + getNamespaceURI());
         if ((localName != null) && !getLocalName().equals(localName))
             throw new XMLStreamException("Expected local name: " + localName
                     + ", found: " + getLocalName());
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI(), and javolution.xml.internal.stream.XMLStreamReaderImpl.NAMES_OF_EVENTS.
reset()
void javolution.xml.internal.stream.XMLStreamReaderImpl.reset ()
Definition at line 984 of file XMLStreamReaderImpl.java.
{
         // Resets all members (alphabetically ordered).
         _attributes.reset();
         _attrPrefixSep = 0;
         _attrQName = null;
         _attrValue = null;
         _attrQName = null;
         _charactersPending = false;
         _encoding = null;
         _entities.reset();
         _eventType = START_DOCUMENT;
         _index = 0;
         _isEmpty = false;
         _location.reset();
         _namespaces.reset();
         _prolog = null;
         _readCount = 0;
         _reader = null;
         _depth = 0;
         _readIndex = 0;
         _seqsIndex = 0;
         _start = 0;
         _startOffset = 0;
         _state = STATE_CHARACTERS;
         _utf8StreamReader.reset();
         // Recycles if factory produced.
         if (_factory != null)
             _factory.recycle(this);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._attributes, javolution.xml.internal.stream.XMLStreamReaderImpl._attrPrefixSep, javolution.xml.internal.stream.XMLStreamReaderImpl._attrQName, javolution.xml.internal.stream.XMLStreamReaderImpl._attrValue, javolution.xml.internal.stream.XMLStreamReaderImpl._charactersPending, javolution.xml.internal.stream.XMLStreamReaderImpl._depth, javolution.xml.internal.stream.XMLStreamReaderImpl._encoding, javolution.xml.internal.stream.XMLStreamReaderImpl._entities, javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._factory, javolution.xml.internal.stream.XMLStreamReaderImpl._index, javolution.xml.internal.stream.XMLStreamReaderImpl._isEmpty, javolution.xml.internal.stream.XMLStreamReaderImpl._location, javolution.xml.internal.stream.XMLStreamReaderImpl._namespaces, javolution.xml.internal.stream.XMLStreamReaderImpl._prolog, javolution.xml.internal.stream.XMLStreamReaderImpl._readCount, javolution.xml.internal.stream.XMLStreamReaderImpl._reader, javolution.xml.internal.stream.XMLStreamReaderImpl._readIndex, javolution.xml.internal.stream.XMLStreamReaderImpl._seqsIndex, javolution.xml.internal.stream.XMLStreamReaderImpl._start, javolution.xml.internal.stream.XMLStreamReaderImpl._startOffset, javolution.xml.internal.stream.XMLStreamReaderImpl._state, javolution.xml.internal.stream.XMLStreamReaderImpl._utf8StreamReader, javolution.xml.internal.stream.XMLInputFactoryImpl.recycle(), javolution.xml.internal.stream.EntitiesImpl.reset(), javolution.xml.internal.stream.AttributesImpl.reset(), javolution.xml.internal.stream.NamespacesImpl.reset(), javolution.io.UTF8StreamReader.reset(), javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.reset(), javolution.xml.stream.XMLStreamConstants.START_DOCUMENT, and javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_CHARACTERS.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.close(), javolution.xml.sax.XMLReaderImpl.parse(), javolution.xml.sax.XMLReaderImpl.reset(), javolution.xml.XMLFormat< T >.InputElement.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
setEntities()
void javolution.xml.internal.stream.XMLStreamReaderImpl.setEntities (Map< String, String > entities)
Defines a custom entities to replacement text mapping for this reader. For example:[code] FastMap<String, String> HTML_ENTITIES = new FastMap<String, String>(); HTML_ENTITIES.put("nbsp", " "); HTML_ENTITIES.put("copy", ""); HTML_ENTITIES.put("eacute", ""); ... XMLStreamReaderImpl reader = new XMLStreamReaderImpl(); reader.setEntities(HTML_ENTITIES); [/code] The entities mapping may be changed dynamically (e.g. after reading the DTD and all external entities references are resolved).
Parameters
entities the entities to replacement texts mapping (both must be CharSequence instances).
Definition at line 365 of file XMLStreamReaderImpl.java.
{
         _entities.setEntitiesMapping(entities);
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._entities, and javolution.xml.internal.stream.EntitiesImpl.setEntitiesMapping().
Referenced by javolution.xml.internal.stream.XMLInputFactoryImpl.newReader().
setInput() [1/3]
void javolution.xml.internal.stream.XMLStreamReaderImpl.setInput (InputStream in) throws XMLStreamException
Sets the input stream source for this XML stream reader (encoding retrieved from XML prolog if any). This method attempts to detect the encoding automatically.
Parameters
in the input source with unknown encoding.
Definition at line 216 of file XMLStreamReaderImpl.java.
{
         setInput(in, detectEncoding(in));
         CharArray prologEncoding = getCharacterEncodingScheme();
         // Checks if necessary to change the reader.
         if ((prologEncoding != null) && !prologEncoding.equals(_encoding)
                 && !(isUTF8(prologEncoding) && isUTF8(_encoding))) {
             // Changes reader (keep characters already read).
             int startOffset = _readCount;
             reset();
             _startOffset = startOffset;
             setInput(in, prologEncoding.toString());
         }
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._encoding, javolution.xml.internal.stream.XMLStreamReaderImpl._readCount, javolution.xml.internal.stream.XMLStreamReaderImpl._startOffset, javolution.xml.internal.stream.XMLStreamReaderImpl.detectEncoding(), javolution.text.CharArray.equals(), javolution.xml.internal.stream.XMLStreamReaderImpl.getCharacterEncodingScheme(), javolution.xml.internal.stream.XMLStreamReaderImpl.isUTF8(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.text.CharArray.toString().
Referenced by javolution.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(), javolution.xml.sax.XMLReaderImpl.parse(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
setInput() [2/3]
void javolution.xml.internal.stream.XMLStreamReaderImpl.setInput (InputStream in, String encoding) throws XMLStreamException
Sets the input stream source and encoding for this XML stream reader.
Parameters
in the input source.
encoding the associated encoding.
Definition at line 243 of file XMLStreamReaderImpl.java.
{
         _encoding = encoding;
         if (isUTF8(encoding)) { // Use our fast UTF-8 Reader.
             setInput(_utf8StreamReader.setInput(in));
         } else {
             try {
                 setInput(new InputStreamReader(in, encoding));
             } catch (UnsupportedEncodingException e) {
                 throw new XMLStreamException(e);
             }
         }
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._encoding, javolution.xml.internal.stream.XMLStreamReaderImpl._utf8StreamReader, javolution.xml.internal.stream.XMLStreamReaderImpl.isUTF8(), javolution.io.UTF8StreamReader.setInput(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
setInput() [3/3]
void javolution.xml.internal.stream.XMLStreamReaderImpl.setInput (Reader reader) throws XMLStreamException
Sets the reader input source for this XML stream reader. This method reads the prolog (if any).
Parameters
reader the input source reader.
See also
javolution.io.UTF8StreamReader
javolution.io.UTF8ByteBufferReader
javolution.io.CharSequenceReader
Definition at line 266 of file XMLStreamReaderImpl.java.
{
         if (_reader != null)
             throw new IllegalStateException("Reader not closed or reset");
         _reader = reader;
         try { // Reads prolog (if there)
             int readCount = reader.read(_readBuffer, _startOffset,
                     _readBuffer.length - _startOffset);
             _readCount = (readCount >= 0) ? readCount + _startOffset
                     : _startOffset;
             if ((_readCount >= 5) && (_readBuffer[0] == '<')
                     && (_readBuffer[1] == '?') && (_readBuffer[2] == 'x')
                     && (_readBuffer[3] == 'm') && (_readBuffer[4] == 'l')
                     && (_readBuffer[5] == ' ')) { // Prolog detected.
                 next(); // Processing instruction.
                 _prolog = this.getPIData();
                 _index = _prolog.offset() + _prolog.length(); // Keep prolog.
                 _start = _index; // Default state.
                 _eventType = START_DOCUMENT; // Resets to START_DOCUMENT.
             }
         } catch (IOException e) {
             throw new XMLStreamException(e);
         }
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._index, javolution.xml.internal.stream.XMLStreamReaderImpl._prolog, javolution.xml.internal.stream.XMLStreamReaderImpl._readBuffer, javolution.xml.internal.stream.XMLStreamReaderImpl._readCount, javolution.xml.internal.stream.XMLStreamReaderImpl._reader, javolution.xml.internal.stream.XMLStreamReaderImpl._start, javolution.xml.internal.stream.XMLStreamReaderImpl._startOffset, javolution.xml.internal.stream.XMLStreamReaderImpl.getPIData(), javolution.text.CharArray.length(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.text.CharArray.offset(), and javolution.xml.stream.XMLStreamConstants.START_DOCUMENT.
standaloneSet()
boolean javolution.xml.internal.stream.XMLStreamReaderImpl.standaloneSet ()
Checks if standalone was set in the document.
Returns
true if standalone was set; false otherwise.
Implements javolution.xml.stream.XMLStreamReader.
Definition at line 1361 of file XMLStreamReaderImpl.java.
{
         return readPrologAttribute(STANDALONE) != null;
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl.readPrologAttribute(), and javolution.xml.internal.stream.XMLStreamReaderImpl.STANDALONE.
toString()
String javolution.xml.internal.stream.XMLStreamReaderImpl.toString ()
Returns the textual representation of this reader current state.
Returns
the textual representation of the current state.
Definition at line 374 of file XMLStreamReaderImpl.java.
{
         return "XMLStreamReader - State: " + NAMES_OF_EVENTS[_eventType]
                 + ", Location: " + _location.toString();
     }
References javolution.xml.internal.stream.XMLStreamReaderImpl._eventType, javolution.xml.internal.stream.XMLStreamReaderImpl._location, javolution.xml.internal.stream.XMLStreamReaderImpl.NAMES_OF_EVENTS, and javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.toString().
Member Data Documentation
_attributes
final AttributesImpl javolution.xml.internal.stream.XMLStreamReaderImpl._attributes = new AttributesImpl(_namespaces) private
Holds the current attributes.
Definition at line 168 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeCount(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeNamespace(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributePrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributes(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeType(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeValue(), javolution.xml.internal.stream.XMLStreamReaderImpl.isAttributeSpecified(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.processAttribute(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
_attrPrefixSep
int javolution.xml.internal.stream.XMLStreamReaderImpl._attrPrefixSep private
Holds attribute prefix separator index.
Definition at line 102 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.processAttribute(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
_attrQName
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl._attrQName private
Holds attribute qualified name.
Definition at line 97 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.processAttribute(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
_attrValue
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl._attrValue private
Holds attribute value.
Definition at line 107 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.processAttribute(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
_charactersPending
boolean javolution.xml.internal.stream.XMLStreamReaderImpl._charactersPending = false package
Indicates if characters are pending for potential coalescing.
Definition at line 122 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
_createSeqLogic
final Runnable javolution.xml.internal.stream.XMLStreamReaderImpl._createSeqLogic private
Initial value:
= new Runnable() {
        public void run() {
            if (_seqsCapacity >= _seqs.length) {
                CharArray[] tmp = new CharArray[_seqs.length * 2];
                System.arraycopy(_seqs, 0, tmp, 0, _seqs.length);
                _seqs = tmp;
            }
            CharArray seq = new CharArray();
            _seqs[_seqsCapacity++] = seq;
        }
    }
Definition at line 1027 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq2().
_data
char [] javolution.xml.internal.stream.XMLStreamReaderImpl._data = new char[READER_BUFFER_CAPACITY * 2] private
Holds the data buffer for CharSequence produced by this parser.
Definition at line 72 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText(), javolution.xml.internal.stream.XMLStreamReaderImpl.increaseDataBuffer(), javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream(), javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), and javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity().
_depth
int javolution.xml.internal.stream.XMLStreamReaderImpl._depth private
Holds the current element nesting.
Definition at line 82 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getDepth(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceCount(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.processEndTag(), javolution.xml.internal.stream.XMLStreamReaderImpl.processStartTag(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
_elemStack
CharArray [] javolution.xml.internal.stream.XMLStreamReaderImpl._elemStack = new CharArray[16] private
Holds working stack (by nesting level).
Definition at line 173 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getQName(), javolution.xml.internal.stream.XMLStreamReaderImpl.increaseStack(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.processEndTag(), and javolution.xml.internal.stream.XMLStreamReaderImpl.processStartTag().
_encoding
String javolution.xml.internal.stream.XMLStreamReaderImpl._encoding private
Holds stream encoding if known.
Definition at line 178 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getEncoding(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
_entities
final EntitiesImpl javolution.xml.internal.stream.XMLStreamReaderImpl._entities = new EntitiesImpl() private
Holds the entities.
Definition at line 183 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getProperty(), javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setEntities().
_eventType
int javolution.xml.internal.stream.XMLStreamReaderImpl._eventType = START_DOCUMENT private
Holds current event type
Definition at line 112 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeCount(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeNamespace(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributePrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributes(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeType(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeValue(), javolution.xml.internal.stream.XMLStreamReaderImpl.getEventType(), javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceCount(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespacePrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPIData(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPITarget(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getQName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getText(), javolution.xml.internal.stream.XMLStreamReaderImpl.hasName(), javolution.xml.internal.stream.XMLStreamReaderImpl.hasNext(), javolution.xml.internal.stream.XMLStreamReaderImpl.hasText(), javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), javolution.xml.internal.stream.XMLStreamReaderImpl.isAttributeSpecified(), javolution.xml.internal.stream.XMLStreamReaderImpl.isCharacters(), javolution.xml.internal.stream.XMLStreamReaderImpl.isEndElement(), javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream(), javolution.xml.internal.stream.XMLStreamReaderImpl.isStartElement(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.nextTag(), javolution.xml.internal.stream.XMLStreamReaderImpl.require(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), javolution.xml.internal.stream.XMLStreamReaderImpl.setInput(), and javolution.xml.internal.stream.XMLStreamReaderImpl.toString().
_factory
final XMLInputFactoryImpl javolution.xml.internal.stream.XMLStreamReaderImpl._factory private
Holds the factory (if any)
Definition at line 193 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.XMLStreamReaderImpl().
_index
int javolution.xml.internal.stream.XMLStreamReaderImpl._index private
Holds the current index of the data buffer (_data).
Definition at line 77 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
_isEmpty
boolean javolution.xml.internal.stream.XMLStreamReaderImpl._isEmpty private
Indicates if event type is START_TAG, and tag is empty, i.e. <sometag>
Definition at line 117 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
_location
final LocationImpl javolution.xml.internal.stream.XMLStreamReaderImpl._location = new LocationImpl() private
Holds the location object.
Definition at line 158 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getLocation(), javolution.xml.internal.stream.XMLStreamReaderImpl.handleEndOfLine(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.processEndTag(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.toString().
_namespaces
final NamespacesImpl javolution.xml.internal.stream.XMLStreamReaderImpl._namespaces = new NamespacesImpl() private
Holds the namespace stack.
Definition at line 163 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeNamespace(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceContext(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceCount(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespacePrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.processAttribute(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
_prefixSep
int javolution.xml.internal.stream.XMLStreamReaderImpl._prefixSep private
Holds element prefix separator index.
Definition at line 92 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPrefix(), and javolution.xml.internal.stream.XMLStreamReaderImpl.next().
_prolog
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl._prolog package
Holds the prolog if any.
Definition at line 57 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.readPrologAttribute(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
_qName
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl._qName private
Holds qualified name (include prefix).
Definition at line 87 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getQName(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.processEndTag(), and javolution.xml.internal.stream.XMLStreamReaderImpl.processStartTag().
_readBuffer
final char [] javolution.xml.internal.stream.XMLStreamReaderImpl._readBuffer = new char[READER_BUFFER_CAPACITY] private
Holds the character buffer used for reading.
Definition at line 147 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.detectEncoding(), javolution.xml.internal.stream.XMLStreamReaderImpl.handleEndOfLine(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
_readCount
int javolution.xml.internal.stream.XMLStreamReaderImpl._readCount private
Number of characters read from reader
Definition at line 67 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.handleEndOfLine(), javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
_reader
Reader javolution.xml.internal.stream.XMLStreamReaderImpl._reader private
Holds the reader input source (null when unused).
Definition at line 142 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
_readIndex
int javolution.xml.internal.stream.XMLStreamReaderImpl._readIndex private
Holds the current index in the character buffer.
Definition at line 62 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.getCharacterOffset(), javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.getColumnNumber(), javolution.xml.internal.stream.XMLStreamReaderImpl.handleEndOfLine(), javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
_seqs
CharArray [] javolution.xml.internal.stream.XMLStreamReaderImpl._seqs = new CharArray[256] private
Definition at line 1041 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq(), javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq2(), and javolution.xml.internal.stream.XMLStreamReaderImpl.next().
_seqsCapacity
int javolution.xml.internal.stream.XMLStreamReaderImpl._seqsCapacity private
Definition at line 1045 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq().
_seqsIndex
int javolution.xml.internal.stream.XMLStreamReaderImpl._seqsIndex private
Definition at line 1043 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq(), javolution.xml.internal.stream.XMLStreamReaderImpl.newSeq2(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
_start
int javolution.xml.internal.stream.XMLStreamReaderImpl._start private
Holds the start index for the current state within _data array.
Definition at line 127 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
_startOffset
int javolution.xml.internal.stream.XMLStreamReaderImpl._startOffset private
Holds the start offset in the character buffer (due to auto detection of encoding).
Definition at line 153 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.detectEncoding(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
_state
int javolution.xml.internal.stream.XMLStreamReaderImpl._state = STATE_CHARACTERS private
Holds the parser state.
Definition at line 132 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
_text
CharArray javolution.xml.internal.stream.XMLStreamReaderImpl._text private
Holds the current text.
Definition at line 137 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getPIData(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPITarget(), javolution.xml.internal.stream.XMLStreamReaderImpl.getText(), javolution.xml.internal.stream.XMLStreamReaderImpl.hasText(), javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream(), javolution.xml.internal.stream.XMLStreamReaderImpl.isWhiteSpace(), and javolution.xml.internal.stream.XMLStreamReaderImpl.next().
_utf8StreamReader
final UTF8StreamReader javolution.xml.internal.stream.XMLStreamReaderImpl._utf8StreamReader = new UTF8StreamReader() private
Holds the reader for input streams.
Definition at line 188 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
ATTRIBUTE
final int javolution.xml.stream.XMLStreamConstants.ATTRIBUTE = 10 static inherited
Indicates an event is an attribute.
Definition at line 71 of file XMLStreamConstants.java.
CDATA
final int javolution.xml.stream.XMLStreamConstants.CDATA = 12 static inherited
Indicates an event is a CDATA section.
Definition at line 81 of file XMLStreamConstants.java.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.ws.WebServiceClient.readResponse().
CHARACTERS
final int javolution.xml.stream.XMLStreamConstants.CHARACTERS = 4 static inherited
Indicates an event is characters.
Definition at line 39 of file XMLStreamConstants.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText(), javolution.xml.internal.stream.XMLStreamReaderImpl.getText(), javolution.xml.internal.stream.XMLStreamReaderImpl.hasText(), javolution.xml.internal.stream.XMLStreamReaderImpl.isCharacters(), javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.nextTag(), javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.ws.WebServiceClient.readResponse().
COMMENT
final int javolution.xml.stream.XMLStreamConstants.COMMENT = 5 static inherited
Indicates an event is a comment.
Definition at line 44 of file XMLStreamConstants.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText(), javolution.xml.internal.stream.XMLStreamReaderImpl.getText(), javolution.xml.internal.stream.XMLStreamReaderImpl.hasText(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.nextTag(), javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.ws.WebServiceClient.readResponse().
DTD
final int javolution.xml.stream.XMLStreamConstants.DTD = 11 static inherited
Indicates an event is a DTD.
Definition at line 76 of file XMLStreamConstants.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getText(), javolution.xml.internal.stream.XMLStreamReaderImpl.hasText(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), and javolution.xml.internal.stream.XMLStreamReaderImpl.nextTag().
ENCODING
final CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.ENCODING = new CharArray("encoding") static private
Definition at line 1233 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getCharacterEncodingScheme().
END_DOCUMENT
final int javolution.xml.stream.XMLStreamConstants.END_DOCUMENT = 8 static inherited
Indicates an event is an end document.
Definition at line 61 of file XMLStreamConstants.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText(), javolution.xml.internal.stream.XMLStreamReaderImpl.hasNext(), javolution.xml.internal.stream.XMLStreamReaderImpl.isEndOfStream(), javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.ws.WebServiceClient.readResponse().
END_ELEMENT
final int javolution.xml.stream.XMLStreamConstants.END_ELEMENT = 2 static inherited
Indicates an event is an end element.
Definition at line 29 of file XMLStreamConstants.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText(), javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceCount(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespacePrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI(), javolution.xml.XMLFormat< T >.InputElement.getNext(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getQName(), javolution.xml.internal.stream.XMLStreamReaderImpl.hasName(), javolution.xml.internal.stream.XMLStreamReaderImpl.isEndElement(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.nextTag(), javolution.xml.sax.XMLReaderImpl.parseAll(), javolution.xml.XMLFormat< T >.InputElement.readReference(), and javolution.xml.ws.WebServiceClient.readResponse().
ENTITY_DECLARATION
final int javolution.xml.stream.XMLStreamConstants.ENTITY_DECLARATION = 15 static inherited
Indicates a Entity Declaration.
Definition at line 96 of file XMLStreamConstants.java.
ENTITY_REFERENCE
final int javolution.xml.stream.XMLStreamConstants.ENTITY_REFERENCE = 9 static inherited
Indicates an event is an entity reference.
Definition at line 66 of file XMLStreamConstants.java.
NAMES_OF_EVENTS
final String [] javolution.xml.internal.stream.XMLStreamReaderImpl.NAMES_OF_EVENTS static package
Initial value:
= new String[] { "UNDEFINED",
            "START_ELEMENT", "END_ELEMENT", "PROCESSING_INSTRUCTIONS",
            "CHARACTERS", "COMMENT", "SPACE", "START_DOCUMENT", "END_DOCUMENT",
            "ENTITY_REFERENCE", "ATTRIBUTE", "DTD", "CDATA", "NAMESPACE",
            "NOTATION_DECLARATION", "ENTITY_DECLARATION" }
Holds the textual representation for events.
Definition at line 43 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText(), javolution.xml.internal.stream.XMLStreamReaderImpl.illegalState(), javolution.xml.internal.stream.XMLStreamReaderImpl.nextTag(), javolution.xml.internal.stream.XMLStreamReaderImpl.require(), and javolution.xml.internal.stream.XMLStreamReaderImpl.toString().
NAMESPACE
final int javolution.xml.stream.XMLStreamConstants.NAMESPACE = 13 static inherited
Indicates the event is a namespace declaration.
Definition at line 86 of file XMLStreamConstants.java.
NOTATION_DECLARATION
final int javolution.xml.stream.XMLStreamConstants.NOTATION_DECLARATION = 14 static inherited
Indicates a Notation.
Definition at line 91 of file XMLStreamConstants.java.
PROCESSING_INSTRUCTION
final int javolution.xml.stream.XMLStreamConstants.PROCESSING_INSTRUCTION = 3 static inherited
Indicates an event is a processing instruction.
Definition at line 34 of file XMLStreamConstants.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPIData(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPITarget(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.nextTag(), and javolution.xml.sax.XMLReaderImpl.parseAll().
READER_BUFFER_CAPACITY
final int javolution.xml.internal.stream.XMLStreamReaderImpl.READER_BUFFER_CAPACITY = 4096 static package
Holds the reader buffer capacity.
Definition at line 52 of file XMLStreamReaderImpl.java.
SPACE
final int javolution.xml.stream.XMLStreamConstants.SPACE = 6 static inherited
The characters are white space (see [XML], 2.10 "White Space Handling"). Events are only reported as SPACE if they are ignorable white space. Otherwise they are reported as CHARACTERS.
Definition at line 51 of file XMLStreamConstants.java.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.ws.WebServiceClient.readResponse().
STANDALONE
final CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.STANDALONE = new CharArray("standalone") static private
Definition at line 1365 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.isStandalone(), and javolution.xml.internal.stream.XMLStreamReaderImpl.standaloneSet().
START_DOCUMENT
final int javolution.xml.stream.XMLStreamConstants.START_DOCUMENT = 7 static inherited
Indicates an event is a start document.
Definition at line 56 of file XMLStreamConstants.java.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll(), javolution.xml.ws.WebServiceClient.readResponse(), javolution.xml.internal.stream.XMLStreamReaderImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
START_ELEMENT
final int javolution.xml.stream.XMLStreamConstants.START_ELEMENT = 1 static inherited
Indicates an event is a start element.
Definition at line 24 of file XMLStreamConstants.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeCount(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeNamespace(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributePrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributes(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeType(), javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeValue(), javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText(), javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceCount(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespacePrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI(), javolution.xml.internal.stream.XMLStreamReaderImpl.getPrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.getQName(), javolution.xml.internal.stream.XMLStreamReaderImpl.hasName(), javolution.xml.XMLFormat< T >.InputElement.hasNext(), javolution.xml.ws.WebServiceClient.invoke(), javolution.xml.internal.stream.XMLStreamReaderImpl.isAttributeSpecified(), javolution.xml.internal.stream.XMLStreamReaderImpl.isStartElement(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.nextTag(), javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.ws.WebServiceClient.readResponse().
STATE_CDATA
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_CDATA = 5 static private
Definition at line 784 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next(), and javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity().
STATE_CHARACTERS
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_CHARACTERS = 1 static private
Definition at line 776 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
STATE_CLOSE_TAGxELEM_NAME_READ
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_CLOSE_TAGxELEM_NAME_READ = 15 static private
Definition at line 804 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
STATE_CLOSE_TAGxREAD_ELEM_NAME
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_CLOSE_TAGxREAD_ELEM_NAME = 14 static private
Definition at line 802 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
STATE_COMMENT
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_COMMENT = 3 static private
Definition at line 780 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next(), and javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity().
STATE_DTD
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_DTD = 16 static private
Definition at line 806 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
STATE_DTD_INTERNAL
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_DTD_INTERNAL = 17 static private
Definition at line 808 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
STATE_MARKUP
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_MARKUP = 2 static private
Definition at line 778 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
STATE_OPEN_TAGxATTR_NAME_READ
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxATTR_NAME_READ = 9 static private
Definition at line 792 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
STATE_OPEN_TAGxELEM_NAME_READ
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxELEM_NAME_READ = 7 static private
Definition at line 788 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
STATE_OPEN_TAGxEMPTY_TAG
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxEMPTY_TAG = 13 static private
Definition at line 800 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
STATE_OPEN_TAGxEQUAL_READ
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxEQUAL_READ = 10 static private
Definition at line 794 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
STATE_OPEN_TAGxREAD_ATTR_NAME
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxREAD_ATTR_NAME = 8 static private
Definition at line 790 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
STATE_OPEN_TAGxREAD_ATTR_VALUE_DOUBLE_QUOTE
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxREAD_ATTR_VALUE_DOUBLE_QUOTE = 12 static private
Definition at line 798 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
STATE_OPEN_TAGxREAD_ATTR_VALUE_SIMPLE_QUOTE
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxREAD_ATTR_VALUE_SIMPLE_QUOTE = 11 static private
Definition at line 796 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
STATE_OPEN_TAGxREAD_ELEM_NAME
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_OPEN_TAGxREAD_ELEM_NAME = 6 static private
Definition at line 786 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next().
STATE_PI
final int javolution.xml.internal.stream.XMLStreamReaderImpl.STATE_PI = 4 static private
Definition at line 782 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next(), and javolution.xml.internal.stream.XMLStreamReaderImpl.replaceEntity().
VERSION
final CharArray javolution.xml.internal.stream.XMLStreamReaderImpl.VERSION = new CharArray("version") static private
Definition at line 1354 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getVersion().
The documentation for this class was generated from the following file:
XMLStreamReaderImpl.java