Javolution 6.0.0 java: javolution.xml.internal.stream.XMLInputFactoryImpl Class Reference
javolution.xml.internal.stream.XMLInputFactoryImpl Class Reference
Public Member Functions
XMLStreamReaderImpl createXMLStreamReader (InputStream stream) throws XMLStreamException
XMLStreamReaderImpl createXMLStreamReader (InputStream stream, String encoding) throws XMLStreamException
XMLStreamReaderImpl createXMLStreamReader (Reader reader) throws XMLStreamException
Object getProperty (String name) throws IllegalArgumentException
boolean isPropertySupported (String name)
void setProperty (String name, Object value) throws IllegalArgumentException
XMLInputFactory clone ()
Static Public Attributes
static final String IS_COALESCING = "javolution.xml.stream.isCoalescing"
static final String IS_VALIDATING = "javolution.xml.stream.isValidating"
static final String ENTITIES = "javolution.xml.stream.entities"
Package Functions
void recycle (XMLStreamReaderImpl reader)
Private Member Functions
XMLStreamReaderImpl newReader ()
Private Attributes
Map< String, String > _entities = null
FastTable< XMLStreamReaderImpl > _recycled
Detailed Description
The default XML input factory implementation.
Definition at line 22 of file XMLInputFactoryImpl.java.
Member Function Documentation
clone()
XMLInputFactory javolution.xml.internal.stream.XMLInputFactoryImpl.clone ()
Returns a clone of this factory which can be independently configured.
Implements javolution.xml.stream.XMLInputFactory.
Definition at line 97 of file XMLInputFactoryImpl.java.
{
         try {
             XMLInputFactoryImpl clone = (XMLInputFactoryImpl) super.clone();
             clone._recycled = new FastTable<XMLStreamReaderImpl>().shared();
             return clone;
         } catch (CloneNotSupportedException e) {
             throw new Error();// Cannot happen since cloneable.
         }
     }
References javolution.xml.stream.XMLInputFactory.clone(), and javolution.util.FastTable< E >.shared().
createXMLStreamReader() [1/3]
XMLStreamReaderImpl javolution.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader (InputStream stream) throws XMLStreamException
Returns a XML stream reader for the specified input stream (encoding autodetected).
Parameters
stream the input stream to read from.
Returns
a xml stream reader possibly recycled.
Exceptions
XMLStreamException
Implements javolution.xml.stream.XMLInputFactory.
Definition at line 28 of file XMLInputFactoryImpl.java.
{
         XMLStreamReaderImpl xmlReader = newReader();
         xmlReader.setInput(stream);
         return xmlReader;
     }
References javolution.xml.internal.stream.XMLInputFactoryImpl.newReader(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
createXMLStreamReader() [2/3]
XMLStreamReaderImpl javolution.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader (InputStream stream, String encoding) throws XMLStreamException
Returns a XML stream reader for the specified input stream using the specified encoding.
Parameters
stream the input stream to read from.
encoding the character encoding of the stream.
Returns
a xml stream reader possibly recycled.
Exceptions
XMLStreamException
Implements javolution.xml.stream.XMLInputFactory.
Definition at line 36 of file XMLInputFactoryImpl.java.
{
         XMLStreamReaderImpl xmlReader = newReader();
         xmlReader.setInput(stream, encoding);
         return xmlReader;
     }
References javolution.xml.internal.stream.XMLInputFactoryImpl.newReader(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
createXMLStreamReader() [3/3]
XMLStreamReaderImpl javolution.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader (Reader reader) throws XMLStreamException
Returns a XML stream reader for the specified I/O reader.
Parameters
reader the XML data to read from.
Exceptions
XMLStreamException
Implements javolution.xml.stream.XMLInputFactory.
Definition at line 44 of file XMLInputFactoryImpl.java.
{
         XMLStreamReaderImpl xmlReader = newReader();
         xmlReader.setInput(reader);
         return xmlReader;
     }
References javolution.xml.internal.stream.XMLInputFactoryImpl.newReader(), and javolution.xml.internal.stream.XMLStreamReaderImpl.setInput().
getProperty()
Object javolution.xml.internal.stream.XMLInputFactoryImpl.getProperty (String name) throws IllegalArgumentException
Gets the value of a feature/property from the underlying implementation.
Parameters
name the name of the property (may not be null).
Returns
the value of the property.
Exceptions
IllegalArgumentException if the property is not supported.
Implements javolution.xml.stream.XMLInputFactory.
Definition at line 52 of file XMLInputFactoryImpl.java.
{
         if (name.equals(IS_COALESCING)) {
             return Boolean.TRUE;
         } else if (name.equals(ENTITIES)) {
             return _entities;
         } else {
             throw new IllegalArgumentException("Property: " + name
                     + " not supported");
         }
     }
References javolution.xml.internal.stream.XMLInputFactoryImpl._entities, javolution.xml.stream.XMLInputFactory.ENTITIES, and javolution.xml.stream.XMLInputFactory.IS_COALESCING.
isPropertySupported()
boolean javolution.xml.internal.stream.XMLInputFactoryImpl.isPropertySupported (String name)
Queries the set of properties that this factory supports.
Parameters
name the name of the property.
Returns
true if the property is supported; false otherwise.
Implements javolution.xml.stream.XMLInputFactory.
Definition at line 64 of file XMLInputFactoryImpl.java.
{
         return name.equals(IS_COALESCING) || name.equals(ENTITIES);
     }
References javolution.xml.stream.XMLInputFactory.ENTITIES, and javolution.xml.stream.XMLInputFactory.IS_COALESCING.
newReader()
XMLStreamReaderImpl javolution.xml.internal.stream.XMLInputFactoryImpl.newReader () private
Definition at line 87 of file XMLInputFactoryImpl.java.
{
         XMLStreamReaderImpl xmlReader = _recycled.pollLast();
         if (xmlReader == null) xmlReader = new XMLStreamReaderImpl(this);
         if (_entities != null) {
             xmlReader.setEntities(_entities);
         }
         return xmlReader;
     }
References javolution.xml.internal.stream.XMLInputFactoryImpl._entities, javolution.xml.internal.stream.XMLInputFactoryImpl._recycled, and javolution.xml.internal.stream.XMLStreamReaderImpl.setEntities().
Referenced by javolution.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader().
recycle()
void javolution.xml.internal.stream.XMLInputFactoryImpl.recycle (XMLStreamReaderImpl reader) package
Recycles the specified instance.
Definition at line 83 of file XMLInputFactoryImpl.java.
{
         _recycled.addLast(reader);
     }
References javolution.xml.internal.stream.XMLInputFactoryImpl._recycled.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
setProperty()
void javolution.xml.internal.stream.XMLInputFactoryImpl.setProperty (String name, Object value) throws IllegalArgumentException
Allows the user to set specific feature/property on the underlying implementation. The underlying implementation is not required to support every setting of every property in the specification and may use IllegalArgumentException to signal that an unsupported property may not be set with the specified value.
Parameters
name the name of the property.
value the value of the property
Exceptions
IllegalArgumentException if the property is not supported.
Implements javolution.xml.stream.XMLInputFactory.
Definition at line 70 of file XMLInputFactoryImpl.java.
{
         if (name.equals(IS_COALESCING)) {
             // Do nothing, always coalescing.
         } else if (name.equals(ENTITIES)) {
             _entities = (Map<String, String>) value;
         } else {
             throw new IllegalArgumentException("Property: " + name
                     + " not supported");
         }
     }
References javolution.xml.internal.stream.XMLInputFactoryImpl._entities, javolution.xml.stream.XMLInputFactory.ENTITIES, and javolution.xml.stream.XMLInputFactory.IS_COALESCING.
Member Data Documentation
_entities
Map<String, String> javolution.xml.internal.stream.XMLInputFactoryImpl._entities = null private
Definition at line 23 of file XMLInputFactoryImpl.java.
Referenced by javolution.xml.internal.stream.XMLInputFactoryImpl.getProperty(), javolution.xml.internal.stream.XMLInputFactoryImpl.newReader(), and javolution.xml.internal.stream.XMLInputFactoryImpl.setProperty().
_recycled
FastTable<XMLStreamReaderImpl> javolution.xml.internal.stream.XMLInputFactoryImpl._recycled private
Initial value:
= new FastTable<XMLStreamReaderImpl>()
            .shared()
Definition at line 24 of file XMLInputFactoryImpl.java.
Referenced by javolution.xml.internal.stream.XMLInputFactoryImpl.newReader(), and javolution.xml.internal.stream.XMLInputFactoryImpl.recycle().
ENTITIES
final String javolution.xml.stream.XMLInputFactory.ENTITIES = "javolution.xml.stream.entities" static inherited
Property used to specify additional entities to be recognized by the readers (type: java.util.Map, default: null). For example:[code] FastMap<String, String> HTML_ENTITIES = new FastMap<String, String>(); HTML_ENTITIES.put("nbsp", " "); HTML_ENTITIES.put("copy", ""); HTML_ENTITIES.put("eacute", ""); ... XMLInputFactory factory = factoryRef.getService(); factory.setProperty(ENTITIES, HTML_ENTITIES); [/code]
Definition at line 80 of file XMLInputFactory.java.
Referenced by javolution.xml.internal.stream.XMLInputFactoryImpl.getProperty(), javolution.xml.internal.stream.XMLStreamReaderImpl.getProperty(), javolution.xml.internal.stream.XMLInputFactoryImpl.isPropertySupported(), and javolution.xml.internal.stream.XMLInputFactoryImpl.setProperty().
IS_COALESCING
final String javolution.xml.stream.XMLInputFactory.IS_COALESCING = "javolution.xml.stream.isCoalescing" static inherited
The property that requires the parser to coalesce adjacent character data sections.
Definition at line 60 of file XMLInputFactory.java.
Referenced by javolution.xml.internal.stream.XMLInputFactoryImpl.getProperty(), javolution.xml.internal.stream.XMLStreamReaderImpl.getProperty(), javolution.xml.internal.stream.XMLInputFactoryImpl.isPropertySupported(), and javolution.xml.internal.stream.XMLInputFactoryImpl.setProperty().
IS_VALIDATING
final String javolution.xml.stream.XMLInputFactory.IS_VALIDATING = "javolution.xml.stream.isValidating" static inherited
The property that requires the parser to validate the input data.
Definition at line 65 of file XMLInputFactory.java.
The documentation for this class was generated from the following file:
XMLInputFactoryImpl.java