Javolution 6.0.0 java: javolution.context.internal.ConcurrentThreadImpl Class Reference
javolution.context.internal.ConcurrentThreadImpl Class Reference
Public Member Functions
ConcurrentThreadImpl ()
boolean execute (Runnable logic, ConcurrentContextImpl inContext)
void run ()
Private Attributes
ConcurrentContextImpl context
AtomicBoolean isBusy = new AtomicBoolean()
Runnable logic
int priority
Static Private Attributes
static int count
Detailed Description
A worker thread executing in a concurrent context.
Definition at line 20 of file ConcurrentThreadImpl.java.
Constructor & Destructor Documentation
ConcurrentThreadImpl()
javolution.context.internal.ConcurrentThreadImpl.ConcurrentThreadImpl ()
Default constructor.
Definition at line 31 of file ConcurrentThreadImpl.java.
{
         this.setName("ConcurrentThread-" + ++count);
         setDaemon(true);
     }
References javolution.context.internal.ConcurrentThreadImpl.count.
Member Function Documentation
execute()
boolean javolution.context.internal.ConcurrentThreadImpl.execute (Runnable logic, ConcurrentContextImpl inContext)
Executes the specified logic by this thread if ready; returns
false
if this thread is busy.
Definition at line 40 of file ConcurrentThreadImpl.java.
{
         if (!isBusy.compareAndSet(false, true))
             return false;
         synchronized (this) {
             this.priority = Thread.currentThread().getPriority();
             this.context = inContext;
             this.logic = logic;
             this.notify();
         }
         return true;
     }
References javolution.context.internal.ConcurrentThreadImpl.isBusy, and javolution.context.internal.ConcurrentThreadImpl.logic.
run()
void javolution.context.internal.ConcurrentThreadImpl.run ()
Definition at line 53 of file ConcurrentThreadImpl.java.
                       {
         while (true) { // Main loop.
             try {
                 synchronized (this) {
                     while (logic == null) this.wait();
                 }
                 this.setPriority(priority);
                 AbstractContext.inherit(context);
                 logic.run();
                 context.completed(null);
             } catch (Throwable error) {
                 context.completed(error);
             }
             // Clean up.
             logic = null;
             context = null;
             AbstractContext.inherit(null);
             isBusy.set(false);
         }
     }
References javolution.context.internal.ConcurrentContextImpl.completed(), javolution.context.internal.ConcurrentThreadImpl.context, javolution.context.AbstractContext.inherit(), javolution.context.internal.ConcurrentThreadImpl.isBusy, javolution.context.internal.ConcurrentThreadImpl.logic, and javolution.context.internal.ConcurrentThreadImpl.priority.
Member Data Documentation
context
ConcurrentContextImpl javolution.context.internal.ConcurrentThreadImpl.context private
Definition at line 23 of file ConcurrentThreadImpl.java.
Referenced by javolution.context.internal.ConcurrentThreadImpl.run().
count
int javolution.context.internal.ConcurrentThreadImpl.count static private
Definition at line 22 of file ConcurrentThreadImpl.java.
Referenced by javolution.context.internal.ConcurrentThreadImpl.ConcurrentThreadImpl().
isBusy
AtomicBoolean javolution.context.internal.ConcurrentThreadImpl.isBusy = new AtomicBoolean() private
Definition at line 24 of file ConcurrentThreadImpl.java.
Referenced by javolution.context.internal.ConcurrentThreadImpl.execute(), and javolution.context.internal.ConcurrentThreadImpl.run().
logic
Runnable javolution.context.internal.ConcurrentThreadImpl.logic private
Definition at line 25 of file ConcurrentThreadImpl.java.
Referenced by javolution.context.internal.ConcurrentThreadImpl.execute(), and javolution.context.internal.ConcurrentThreadImpl.run().
priority
int javolution.context.internal.ConcurrentThreadImpl.priority private
Definition at line 26 of file ConcurrentThreadImpl.java.
Referenced by javolution.context.internal.ConcurrentThreadImpl.run().
The documentation for this class was generated from the following file:
ConcurrentThreadImpl.java