Javolution 6.0.0 java: javolution.util.function.Reducers Class Reference
javolution.util.function.Reducers Class Reference
Classes
class AndReducer
class AnyReducer
class MaxReducer
class MinReducer
class OrReducer
class SumReducer
Static Public Member Functions
static< E > Reducer< E > any (Class<? extends E > type)
static< E > Reducer< E > max (Comparator<? super E > comparator)
static< E > Reducer< E > min (Comparator<? super E > comparator)
static Reducer< Boolean > and ()
static Reducer< Boolean > or ()
static Reducer< Integer > sum ()
Private Member Functions
Reducers ()
Detailed Description
A set of useful reducers of collection elements.
Author
Jean-Marie Dautelle
Version
6.0, July 21, 2013
See also
FastCollection::reduce(Reducer)
Definition at line 30 of file Reducers.java.
Constructor & Destructor Documentation
Reducers()
javolution.util.function.Reducers.Reducers () private
Definition at line 33 of file Reducers.java.
 {}
Member Function Documentation
and()
static Reducer<Boolean> javolution.util.function.Reducers.and () static
Conditional 'and' operator (returns
true
if the collection is empty). This operator stops iterating as soon as a
false
value is found.
Definition at line 155 of file Reducers.java.
{
         return new AndReducer();
     }
any()
static <E> Reducer<E> javolution.util.function.Reducers.any (Class<? extends E > type) static
Returns any non-null element of the specified type. This reducer stops iterating as soon as an element with the matching type is found.
Definition at line 42 of file Reducers.java.
{
         return new AnyReducer<E>(type);
     }
Referenced by javolution.util.FastCollection< E >.any().
max()
static <E> Reducer<E> javolution.util.function.Reducers.max (Comparator<? super E > comparator) static
Returns the greatest element of a collection according to the specified comparator (returns
null
if the collection is empty).
Parameters
comparator the comparator to use for comparison.
Definition at line 80 of file Reducers.java.
{
         return new MaxReducer<E>(comparator);
     }
Referenced by javolution.util.FastCollection< E >.max().
min()
static <E> Reducer<E> javolution.util.function.Reducers.min (Comparator<? super E > comparator) static
Returns the smallest element of a collection according to the collection comparator (returns
null
if the collection is empty).
Definition at line 117 of file Reducers.java.
{
         return new MinReducer<E>(comparator);
     }
Referenced by javolution.util.FastCollection< E >.min().
or()
static Reducer<Boolean> javolution.util.function.Reducers.or () static
Conditional 'or' operator (returns
false
if the collection is empty). This operator stops iterating as soon as a
true
value is found.
Definition at line 183 of file Reducers.java.
{
         return new OrReducer();
     }
sum()
static Reducer<Integer> javolution.util.function.Reducers.sum () static
Returns the sum of the specified integers value (returns
0
if the collection is empty).
Definition at line 210 of file Reducers.java.
{
         return new SumReducer();
     }
The documentation for this class was generated from the following file:
Reducers.java