Javolution 6.0.0 java: javolution.xml.internal.stream.AttributesImpl Class Reference
javolution.xml.internal.stream.AttributesImpl Class Reference
Classes
class AttributeImpl
Public Member Functions
AttributesImpl (NamespacesImpl namespaces)
void addAttribute (CharArray localName, CharArray prefix, CharArray qName, CharArray value)
int getIndex (CharSequence qName)
int getIndex (CharSequence uri, CharSequence localName)
int getLength ()
CharArray getLocalName (int index)
CharArray getPrefix (int index)
CharArray getQName (int index)
CharArray getType (CharSequence qName)
CharArray getType (CharSequence uri, CharSequence localName)
CharArray getType (int index)
CharArray getURI (int index)
CharArray getValue (CharSequence qName)
CharArray getValue (CharSequence uri, CharSequence localName)
CharArray getValue (int index)
void reset ()
Private Attributes
final FastTable< AttributeImpl > attributes = new FastTable<AttributeImpl>()
int length
final NamespacesImpl namespaces
Static Private Attributes
static final CharArray CDATA = new CharArray("CDATA")
static final CharArray EMPTY = new CharArray()
Detailed Description
This class provides the implementation of the Attributes interface for the StAX parser.
Definition at line 11 of file AttributesImpl.java.
Constructor & Destructor Documentation
AttributesImpl()
javolution.xml.internal.stream.AttributesImpl.AttributesImpl (NamespacesImpl namespaces)
Creates a list of attribute using the specified namespace stack.
Definition at line 48 of file AttributesImpl.java.
{
         this.namespaces = namespaces;
     }
References javolution.xml.internal.stream.AttributesImpl.namespaces.
Member Function Documentation
addAttribute()
void javolution.xml.internal.stream.AttributesImpl.addAttribute (CharArray localName, CharArray prefix, CharArray qName, CharArray value)
Adds an attribute to the end of the attribute list.
Parameters
localName the local name.
prefix the prefix or null if none.
qName the qualified (prefixed) name.
value the attribute value.
Definition at line 60 of file AttributesImpl.java.
{
         AttributeImpl attribute;
         if (length >= attributes.size()) {
             attribute = new AttributeImpl();
             attributes.add(attribute);
         } else {
             attribute = attributes.get(length);
         }
         attribute.localName = localName;
         attribute.prefix = prefix;
         attribute.qName = qName;
         attribute.value = value;
         length++;
     }
References javolution.xml.internal.stream.AttributesImpl.attributes, javolution.xml.internal.stream.AttributesImpl.length, javolution.xml.internal.stream.AttributesImpl.AttributeImpl.localName, javolution.xml.internal.stream.AttributesImpl.AttributeImpl.prefix, javolution.xml.internal.stream.AttributesImpl.AttributeImpl.qName, and javolution.xml.internal.stream.AttributesImpl.AttributeImpl.value.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.processAttribute().
getIndex() [1/2]
int javolution.xml.internal.stream.AttributesImpl.getIndex (CharSequence qName)
Looks up the index of an attribute by XML 1.0 qualified name (convenience method). This method returns the index of the attribute whose name has the same character content as the specified qName.
Parameters
qName the qualified (prefixed) name.
Returns
the index of the attribute, or -1 if it does not appear in the list.
Implements javolution.xml.sax.Attributes.
Definition at line 77 of file AttributesImpl.java.
{
         for (int i = 0; i < length; i++) {
             if (qName.equals(attributes.get(i).qName))
                 return i;
         }
         return -1;
     }
References javolution.xml.internal.stream.AttributesImpl.attributes, and javolution.xml.internal.stream.AttributesImpl.length.
Referenced by javolution.xml.internal.stream.AttributesImpl.getType(), and javolution.xml.internal.stream.AttributesImpl.getValue().
getIndex() [2/2]
int javolution.xml.internal.stream.AttributesImpl.getIndex (CharSequence uri, CharSequence localName)
Looks up the index of an attribute by namespace name (convenience method). This method returns the index of the attribute whose uri/localName have the same character content as the specified uri/localName.
Parameters
uri the Namespace URI, or an empty character sequence if the name has no Namespace URI.
localName the attribute's local name.
Returns
the index of the attribute, or -1 if it does not appear in the list.
Implements javolution.xml.sax.Attributes.
Definition at line 86 of file AttributesImpl.java.
{
         for (int i = 0; i < length; i++) {
             AttributeImpl attribute = attributes.get(i);
             if (localName.equals(attribute.localName)) {
                 if (attribute.prefix == null) { // No namespace URI.
                     if (uri.length() == 0)
                         return i;
                 } else { // Check if matching namespace URI.
                     if (uri.equals(namespaces.getNamespaceURI(attribute.prefix)))
                         return i;
                 }
             }
         }
         return -1;
     }
References javolution.xml.internal.stream.AttributesImpl.attributes, javolution.xml.internal.stream.NamespacesImpl.getNamespaceURI(), javolution.xml.internal.stream.AttributesImpl.length, javolution.xml.internal.stream.AttributesImpl.AttributeImpl.localName, javolution.xml.internal.stream.AttributesImpl.namespaces, and javolution.xml.internal.stream.AttributesImpl.AttributeImpl.prefix.
getLength()
int javolution.xml.internal.stream.AttributesImpl.getLength ()
Returns the number of attributes in this list of attributes.
Returns
the number of attributes.
Implements javolution.xml.sax.Attributes.
Definition at line 103 of file AttributesImpl.java.
{
         return length;
     }
References javolution.xml.internal.stream.AttributesImpl.length.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeCount().
getLocalName()
CharArray javolution.xml.internal.stream.AttributesImpl.getLocalName (int index)
Looks up an attribute's local name by index.
Parameters
index the attribute index (zero-based).
Returns
the local name, or an empty character sequence if Namespace processing is not being performed, or null if the index is out of range.
See also
getLength
Implements javolution.xml.sax.Attributes.
Definition at line 108 of file AttributesImpl.java.
{
         if ((index < 0) || (index >= length)) return null;
         return attributes.get(index).localName;
     }
References javolution.xml.internal.stream.AttributesImpl.attributes, and javolution.xml.internal.stream.AttributesImpl.length.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeLocalName().
getPrefix()
CharArray javolution.xml.internal.stream.AttributesImpl.getPrefix (int index)
Definition at line 113 of file AttributesImpl.java.
{
         if ((index < 0) || (index >= length)) return null;
         return attributes.get(index).prefix;
     }
References javolution.xml.internal.stream.AttributesImpl.attributes, and javolution.xml.internal.stream.AttributesImpl.length.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeNamespace(), and javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributePrefix().
getQName()
CharArray javolution.xml.internal.stream.AttributesImpl.getQName (int index)
Looks up an attribute's XML 1.0 qualified name by index.
Parameters
index the attribute index (zero-based).
Returns
the XML 1.0 qualified name, or an empty character sequence if none is available, or null if the index is out of range.
See also
getLength
Implements javolution.xml.sax.Attributes.
Definition at line 119 of file AttributesImpl.java.
{
         if ((index < 0) || (index >= length)) return null;
         return attributes.get(index).qName;
     }
References javolution.xml.internal.stream.AttributesImpl.attributes, and javolution.xml.internal.stream.AttributesImpl.length.
getType() [1/3]
CharArray javolution.xml.internal.stream.AttributesImpl.getType (CharSequence qName)
Looks up an attribute's type by XML 1.0 qualified name. This method returns the type of the attribute whose qName has the same character content as the specified qName.
Parameters
qName The XML 1.0 qualified name.
Returns
the attribute type as a string, or null if the attribute is not in the list or if qualified names are not available.
Implements javolution.xml.sax.Attributes.
Definition at line 125 of file AttributesImpl.java.
{
         return (getIndex(qName) >= 0) ? CDATA : null;
     }
References javolution.xml.internal.stream.AttributesImpl.CDATA, and javolution.xml.internal.stream.AttributesImpl.getIndex().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeType().
getType() [2/3]
CharArray javolution.xml.internal.stream.AttributesImpl.getType (CharSequence uri, CharSequence localName)
Looks up an attribute's type by Namespace name (convenience method). This method returns the type of the attribute whose uri/localName have the same character content as the specified uri/localName.
Parameters
uri the Namespace URI, or an empty string if the name has no Namespace URI.
localName the local name of the attribute.
Returns
the attribute type as a string, or null if the attribute is not in the list or if Namespace processing is not being performed.
Implements javolution.xml.sax.Attributes.
Definition at line 130 of file AttributesImpl.java.
{
          return (getIndex(uri, localName) >= 0) ? CDATA : null;
     }
References javolution.xml.internal.stream.AttributesImpl.CDATA, and javolution.xml.internal.stream.AttributesImpl.getIndex().
getType() [3/3]
CharArray javolution.xml.internal.stream.AttributesImpl.getType (int index)
Looks up an attribute's type by index.
The attribute type is one of the strings "CDATA", "ID", "IDREF", "IDREFS", "NMTOKEN", "NMTOKENS", "ENTITY", "ENTITIES", or "NOTATION" (always in upper case).
If the parser has not read a declaration for the attribute, or if the parser does not report attribute types, then it must return the value "CDATA" as stated in the XML 1.0 Recommentation (clause 3.3.3, "Attribute-TextBuilder Normalization").
For an enumerated attribute that is not a notation, the parser will report the type as "NMTOKEN".
Parameters
index the attribute index (zero-based).
Returns
the attribute's type as a string, or null if the index is out of range.
See also
getLength
Implements javolution.xml.sax.Attributes.
Definition at line 135 of file AttributesImpl.java.
{
         if ((index < 0) || (index >= length)) return null;
         return CDATA;
     }
References javolution.xml.internal.stream.AttributesImpl.CDATA, and javolution.xml.internal.stream.AttributesImpl.length.
getURI()
CharArray javolution.xml.internal.stream.AttributesImpl.getURI (int index)
Looks up an attribute's Namespace URI by index.
Parameters
index the attribute index (zero-based).
Returns
the Namespace URI, or an empty character sequence if none is available, or null if the index is out of range.
See also
getLength
Implements javolution.xml.sax.Attributes.
Definition at line 140 of file AttributesImpl.java.
{
         if ((index < 0) || (index >= length)) return null;
         CharArray prefix = attributes.get(index).prefix;
         return (prefix == null) ? EMPTY : namespaces.getNamespaceURI(prefix);
     }
References javolution.xml.internal.stream.AttributesImpl.attributes, javolution.xml.internal.stream.AttributesImpl.EMPTY, javolution.xml.internal.stream.NamespacesImpl.getNamespaceURI(), javolution.xml.internal.stream.AttributesImpl.length, and javolution.xml.internal.stream.AttributesImpl.namespaces.
getValue() [1/3]
CharArray javolution.xml.internal.stream.AttributesImpl.getValue (CharSequence qName)
Looks up an attribute's value by XML 1.0 qualified name (convenience method). This method returns the value of the attribute whose qName has the same character content as the specified qName.
Parameters
qName The XML 1.0 qualified name.
Returns
the attribute value as a character sequence, or null if the attribute is not in the list or if qualified names are not available.
Implements javolution.xml.sax.Attributes.
Definition at line 147 of file AttributesImpl.java.
{
         final int index = getIndex(qName);
         return (index >= 0) ? attributes.get(index).value : null;
     }
References javolution.xml.internal.stream.AttributesImpl.attributes, and javolution.xml.internal.stream.AttributesImpl.getIndex().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeValue(), and javolution.xml.internal.stream.XMLStreamReaderImpl.isAttributeSpecified().
getValue() [2/3]
CharArray javolution.xml.internal.stream.AttributesImpl.getValue (CharSequence uri, CharSequence localName)
Looks up an attribute's value by Namespace name (convenience method). This method returns the value of the attribute whose uri/localName have the same character content as the specified uri/localName.
Parameters
uri the Namespace URI, or the empty string if the name has no Namespace URI.
localName the local name of the attribute.
Returns
the attribute value as a character sequence, or null if the attribute is not in the list.
Implements javolution.xml.sax.Attributes.
Definition at line 153 of file AttributesImpl.java.
{
         final int index = getIndex(uri, localName);
         return (index >= 0) ? attributes.get(index).value : null;
     }
References javolution.xml.internal.stream.AttributesImpl.attributes, and javolution.xml.internal.stream.AttributesImpl.getIndex().
getValue() [3/3]
CharArray javolution.xml.internal.stream.AttributesImpl.getValue (int index)
Looks up an attribute's value by index.
If the attribute value is a list of tokens (IDREFS, ENTITIES, or NMTOKENS), the tokens will be concatenated into a single string with each token separated by a single space.
Parameters
index the attribute index (zero-based).
Returns
the attribute's value as a character sequence, null if the index is out of range.
See also
getLength
Implements javolution.xml.sax.Attributes.
Definition at line 159 of file AttributesImpl.java.
{
         if ((index < 0) || (index >= length)) return null;
         return attributes.get(index).value;
     }
References javolution.xml.internal.stream.AttributesImpl.attributes, and javolution.xml.internal.stream.AttributesImpl.length.
reset()
void javolution.xml.internal.stream.AttributesImpl.reset ()
Clear the attribute list for reuse.
Definition at line 167 of file AttributesImpl.java.
{
         length = 0;
     }
References javolution.xml.internal.stream.AttributesImpl.length.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
Member Data Documentation
attributes
final FastTable<AttributeImpl> javolution.xml.internal.stream.AttributesImpl.attributes = new FastTable<AttributeImpl>() private
Holds the attributes.
Definition at line 33 of file AttributesImpl.java.
Referenced by javolution.xml.internal.stream.AttributesImpl.addAttribute(), javolution.xml.internal.stream.AttributesImpl.getIndex(), javolution.xml.internal.stream.AttributesImpl.getLocalName(), javolution.xml.internal.stream.AttributesImpl.getPrefix(), javolution.xml.internal.stream.AttributesImpl.getQName(), javolution.xml.internal.stream.AttributesImpl.getURI(), and javolution.xml.internal.stream.AttributesImpl.getValue().
CDATA
final CharArray javolution.xml.internal.stream.AttributesImpl.CDATA = new CharArray("CDATA") static private
Definition at line 26 of file AttributesImpl.java.
Referenced by javolution.xml.internal.stream.AttributesImpl.getType().
EMPTY
final CharArray javolution.xml.internal.stream.AttributesImpl.EMPTY = new CharArray() static private
Definition at line 28 of file AttributesImpl.java.
Referenced by javolution.xml.internal.stream.AttributesImpl.getURI().
length
int javolution.xml.internal.stream.AttributesImpl.length private
Holds the current number of attributes set.
Definition at line 38 of file AttributesImpl.java.
Referenced by javolution.xml.internal.stream.AttributesImpl.addAttribute(), javolution.xml.internal.stream.AttributesImpl.getIndex(), javolution.xml.internal.stream.AttributesImpl.getLength(), javolution.xml.internal.stream.AttributesImpl.getLocalName(), javolution.xml.internal.stream.AttributesImpl.getPrefix(), javolution.xml.internal.stream.AttributesImpl.getQName(), javolution.xml.internal.stream.AttributesImpl.getType(), javolution.xml.internal.stream.AttributesImpl.getURI(), javolution.xml.internal.stream.AttributesImpl.getValue(), and javolution.xml.internal.stream.AttributesImpl.reset().
namespaces
final NamespacesImpl javolution.xml.internal.stream.AttributesImpl.namespaces private
Holds the namespace stack.
Definition at line 43 of file AttributesImpl.java.
Referenced by javolution.xml.internal.stream.AttributesImpl.AttributesImpl(), javolution.xml.internal.stream.AttributesImpl.getIndex(), and javolution.xml.internal.stream.AttributesImpl.getURI().
The documentation for this class was generated from the following file:
AttributesImpl.java