Javolution 6.0.0 java: javolution.io.Union Class Reference
javolution.io.Union Class Reference abstract
Public Member Functions
Union ()
final boolean isUnion ()
final int size ()
Struct outer ()
final ByteBuffer getByteBuffer ()
final Struct setByteBuffer (ByteBuffer byteBuffer, int position)
final Struct setByteBufferPosition (int position)
final int getByteBufferPosition ()
int read (InputStream in) throws IOException
void write (OutputStream out) throws IOException
final long address ()
String toString ()
ByteOrder byteOrder ()
boolean isPacked ()
long readBits (int bitOffset, int bitSize)
void writeBits (long value, int bitOffset, int bitSize)
Static Public Attributes
static final LocalContext.Parameter< Integer > MAXIMUM_ALIGNMENT
Protected Member Functions
UTF8String[] array (UTF8String[] array, int stringLength)
Package Functions
protected< S extends Struct > S inner (S struct)
protected< S extends Struct > S[] array (S[] structs)
protected< S extends Struct > S[][] array (S[][] structs)
protected< S extends Struct > S[][][] array (S[][][] structs)
protected< M extends Member > M[] array (M[] arrayMember)
protected< M extends Member > M[][] array (M[][] arrayMember)
protected< M extends Member > M[][][] array (M[][][] arrayMember)
Package Attributes
Struct _outer
ByteBuffer _byteBuffer
int _outerOffset
int _alignment = 1
int _length
int _index
int _wordSize
int _bitsUsed
boolean _resetIndex
byte[] _bytes
Private Member Functions
synchronized ByteBuffer newBuffer ()
long readByteBufferLong (int index)
void writeByteBufferLong (int index, long value)
Static Private Member Functions
static byte readByte (int index, ByteBuffer byteBuffer)
static void writeByte (int index, ByteBuffer byteBuffer, byte value)
Static Private Attributes
static final char[] HEXA
static final Class<? extends Bool[]> BOOL = new Bool[0].getClass()
static final Class<? extends Signed8[]> SIGNED_8
static final Class<? extends Unsigned8[]> UNSIGNED_8
static final Class<? extends Signed16[]> SIGNED_16
static final Class<? extends Unsigned16[]> UNSIGNED_16
static final Class<? extends Signed32[]> SIGNED_32
static final Class<? extends Unsigned32[]> UNSIGNED_32
static final Class<? extends Signed64[]> SIGNED_64
static final Class<? extends Float32[]> FLOAT_32
static final Class<? extends Float64[]> FLOAT_64
Detailed Description
Equivalent to C/C++ union; this class works in the same way as Struct (sub-class) except that all members are mapped to the same location in memory.
Here is an example of C union: [code] union Number { int asInt; float asFloat; char asString[12]; };[/code] And its Java equivalent:[code] public class Number extends Union { Signed32 asInt = new Signed32(); Float32 asFloat = new Float32(); Utf8String asString = new Utf8String(12); }[/code] As for any Struct, fields are directly accessible:[code] Number num = new Number(); num.asInt.set(23); num.asString.set("23"); // Null terminated (C compatible) float f = num.asFloat.get();[/code]
Author
Jean-Marie Dautelle
Version
1.0, October 4, 2004
Definition at line 36 of file Union.java.
Constructor & Destructor Documentation
Union()
javolution.io.Union.Union ()
Default constructor.
Definition at line 41 of file Union.java.
 {}
Member Function Documentation
address()
final long javolution.io.Struct.address () inherited
Returns this struct address. This method allows for structs to be referenced (e.g. pointer) from other structs.
Returns
the struct memory address.
Exceptions
UnsupportedOperationException if the struct buffer is not a direct buffer.
See also
Reference32
Reference64
Definition at line 393 of file Struct.java.
{
         ByteBuffer thisBuffer = this.getByteBuffer();
         if (thisBuffer instanceof sun.nio.ch.DirectBuffer)
           return ((sun.nio.ch.DirectBuffer)thisBuffer).address();
         throw new UnsupportedOperationException();
     }
References javolution.io.Struct.getByteBuffer().
Referenced by javolution.io.Struct.Reference32< S extends Struct >.set(), and javolution.io.Struct.Reference64< S extends Struct >.set().
array() [1/7]
protected<M extends Member> M [] javolution.io.Struct.array (M[] arrayMember) package inherited
Defines the specified array member. For predefined members, the array is populated when empty; custom members should use literal (populated) arrays.
Parameters
arrayMember the array member.
Returns
the specified array member.
Exceptions
UnsupportedOperationException if the specified array is empty and the member type is unknown.
Definition at line 618 of file Struct.java.
{
         boolean resetIndexSaved = _resetIndex;
         if (_resetIndex) {
             _index = 0;
             _resetIndex = false; // Ensures the array elements are sequential.
         }
         if (BOOL.isInstance(arrayMember)) {
             for (int i = 0; i < arrayMember.length;) {
                 arrayMember[i++] = (M) this.new Bool();
             }
         } else if (SIGNED_8.isInstance(arrayMember)) {
             for (int i = 0; i < arrayMember.length;) {
                 arrayMember[i++] = (M) this.new Signed8();
             }
         } else if (UNSIGNED_8.isInstance(arrayMember)) {
             for (int i = 0; i < arrayMember.length;) {
                 arrayMember[i++] = (M) this.new Unsigned8();
             }
         } else if (SIGNED_16.isInstance(arrayMember)) {
             for (int i = 0; i < arrayMember.length;) {
                 arrayMember[i++] = (M) this.new Signed16();
             }
         } else if (UNSIGNED_16.isInstance(arrayMember)) {
             for (int i = 0; i < arrayMember.length;) {
                 arrayMember[i++] = (M) this.new Unsigned16();
             }
         } else if (SIGNED_32.isInstance(arrayMember)) {
             for (int i = 0; i < arrayMember.length;) {
                 arrayMember[i++] = (M) this.new Signed32();
             }
         } else if (UNSIGNED_32.isInstance(arrayMember)) {
             for (int i = 0; i < arrayMember.length;) {
                 arrayMember[i++] = (M) this.new Unsigned32();
             }
         } else if (SIGNED_64.isInstance(arrayMember)) {
             for (int i = 0; i < arrayMember.length;) {
                 arrayMember[i++] = (M) this.new Signed64();
             }
         } else if (FLOAT_32.isInstance(arrayMember)) {
             for (int i = 0; i < arrayMember.length;) {
                 arrayMember[i++] = (M) this.new Float32();
             }
         } else if (FLOAT_64.isInstance(arrayMember)) {
             for (int i = 0; i < arrayMember.length;) {
                 arrayMember[i++] = (M) this.new Float64();
             }
         } else {
             throw new UnsupportedOperationException(
                     "Cannot create member elements, the arrayMember should "
                             + "contain the member instances instead of null");
         }
         _resetIndex = resetIndexSaved;
         return (M[]) arrayMember;
     }
References javolution.io.Struct._index, javolution.io.Struct._resetIndex, javolution.io.Struct.BOOL, javolution.io.Struct.FLOAT_32, javolution.io.Struct.FLOAT_64, javolution.io.Struct.SIGNED_16, javolution.io.Struct.SIGNED_32, javolution.io.Struct.SIGNED_64, javolution.io.Struct.SIGNED_8, javolution.io.Struct.UNSIGNED_16, javolution.io.Struct.UNSIGNED_32, and javolution.io.Struct.UNSIGNED_8.
array() [2/7]
protected<M extends Member> M [][] javolution.io.Struct.array (M arrayMember[][]) package inherited
Defines the specified two-dimensional array member. For predefined members, the array is populated when empty; custom members should use literal (populated) arrays.
Parameters
arrayMember the two-dimensional array member.
Returns
the specified array member.
Exceptions
UnsupportedOperationException if the specified array is empty and the member type is unknown.
Definition at line 703 of file Struct.java.
{
         boolean resetIndexSaved = _resetIndex;
         if (_resetIndex) {
             _index = 0;
             _resetIndex = false; // Ensures the array elements are sequential.
         }
         for (int i = 0; i < arrayMember.length; i++) {
             array(arrayMember[i]);
         }
         _resetIndex = resetIndexSaved;
         return (M[][]) arrayMember;
     }
References javolution.io.Struct._index, javolution.io.Struct._resetIndex, and javolution.io.Struct.array().
array() [3/7]
protected<M extends Member> M [][][] javolution.io.Struct.array (M arrayMember[][][]) package inherited
Defines the specified three-dimensional array member. For predefined members, the array is populated when empty; custom members should use literal (populated) arrays.
Parameters
arrayMember the three-dimensional array member.
Returns
the specified array member.
Exceptions
UnsupportedOperationException if the specified array is empty and the member type is unknown.
Definition at line 726 of file Struct.java.
{
         boolean resetIndexSaved = _resetIndex;
         if (_resetIndex) {
             _index = 0;
             _resetIndex = false; // Ensures the array elements are sequential.
         }
         for (int i = 0; i < arrayMember.length; i++) {
             array(arrayMember[i]);
         }
         _resetIndex = resetIndexSaved;
         return (M[][][]) arrayMember;
     }
References javolution.io.Struct._index, javolution.io.Struct._resetIndex, and javolution.io.Struct.array().
array() [4/7]
protected<S extends Struct> S [] javolution.io.Struct.array (S[] structs) package inherited
Defines the specified array of structs as inner structs. The array is populated if necessary using the struct component default constructor (which must be public).
Parameters
structs the struct array.
Returns
the specified struct array.
Exceptions
IllegalArgumentException if the specified array contains inner structs.
Definition at line 532 of file Struct.java.
{
         Class<?> structClass = null;
         boolean resetIndexSaved = _resetIndex;
         if (_resetIndex) {
             _index = 0;
             _resetIndex = false; // Ensures the array elements are sequential.
         }
         for (int i = 0; i < structs.length;) {
             S struct = structs[i];
             if (struct == null) {
                 try {
                     if (structClass == null) {
                         String arrayName = structs.getClass().getName();
                         String structName = arrayName.substring(2,
                                 arrayName.length() - 1);
                         structClass = Class.forName(structName);
                         if (structClass == null) { throw new IllegalArgumentException(
                                 "Struct class: " + structName + " not found"); }
                     }
                     struct = (S) structClass.newInstance();
                 } catch (Exception e) {
                     throw new RuntimeException(e.getMessage());
                 }
             }
             structs[i++] = inner(struct);
         }
         _resetIndex = resetIndexSaved;
         return (S[]) structs;
     }
References javolution.io.Struct._index, javolution.io.Struct._resetIndex, and javolution.io.Struct.inner().
Referenced by javolution.io.Struct.array().
array() [5/7]
protected<S extends Struct> S [][] javolution.io.Struct.array (S structs[][]) package inherited
Defines the specified two-dimensional array of structs as inner structs. The array is populated if necessary using the struct component default constructor (which must be public).
Parameters
structs the two dimensional struct array.
Returns
the specified struct array.
Exceptions
IllegalArgumentException if the specified array contains inner structs.
Definition at line 572 of file Struct.java.
{
         boolean resetIndexSaved = _resetIndex;
         if (_resetIndex) {
             _index = 0;
             _resetIndex = false; // Ensures the array elements are sequential.
         }
         for (int i = 0; i < structs.length; i++) {
             array(structs[i]);
         }
         _resetIndex = resetIndexSaved;
         return (S[][]) structs;
     }
References javolution.io.Struct._index, javolution.io.Struct._resetIndex, and javolution.io.Struct.array().
array() [6/7]
protected<S extends Struct> S [][][] javolution.io.Struct.array (S structs[][][]) package inherited
Defines the specified three dimensional array of structs as inner structs. The array is populated if necessary using the struct component default constructor (which must be public).
Parameters
structs the three dimensional struct array.
Returns
the specified struct array.
Exceptions
IllegalArgumentException if the specified array contains inner structs.
Definition at line 595 of file Struct.java.
{
         boolean resetIndexSaved = _resetIndex;
         if (_resetIndex) {
             _index = 0;
             _resetIndex = false; // Ensures the array elements are sequential.
         }
         for (int i = 0; i < structs.length; i++) {
             array(structs[i]);
         }
         _resetIndex = resetIndexSaved;
         return (S[][][]) structs;
     }
References javolution.io.Struct._index, javolution.io.Struct._resetIndex, and javolution.io.Struct.array().
array() [7/7]
UTF8String [] javolution.io.Struct.array (UTF8String[] array, int stringLength) protected inherited
Defines the specified array of UTF-8 strings, all strings having the specified length (convenience method).
Parameters
array the string array.
stringLength the length of the string elements.
Returns
the specified string array.
Definition at line 747 of file Struct.java.
{
         boolean resetIndexSaved = _resetIndex;
         if (_resetIndex) {
             _index = 0;
             _resetIndex = false; // Ensures the array elements are sequential.
         }
         for (int i = 0; i < array.length; i++) {
             array[i] = new UTF8String(stringLength);
         }
         _resetIndex = resetIndexSaved;
         return array;
     }
References javolution.io.Struct._index, javolution.io.Struct._resetIndex, and javolution.io.Struct.array().
byteOrder()
ByteOrder javolution.io.Struct.byteOrder () inherited
Returns the byte order for this struct (configurable). The byte order is inherited by inner structs. Sub-classes may change the byte order by overriding this method. For example:[code] public class TopStruct extends Struct { ... // Members initialization. public ByteOrder byteOrder() { // TopStruct and its inner structs use hardware byte order. return ByteOrder.nativeOrder(); } }}[/code]
Returns
the byte order when reading/writing multibyte values (default: network byte order, BIG_ENDIAN).
Definition at line 480 of file Struct.java.
{
         return (_outer != null) ? _outer.byteOrder() : ByteOrder.BIG_ENDIAN;
     }
References javolution.io.Struct._outer, and javolution.io.Struct.byteOrder().
Referenced by javolution.io.Struct.byteOrder(), javolution.io.Struct.Member.get(), javolution.io.Struct.newBuffer(), javolution.io.Struct.readBits(), javolution.io.Struct.Member.set(), javolution.io.Struct.setByteBuffer(), and javolution.io.Struct.writeBits().
getByteBuffer()
final ByteBuffer javolution.io.Struct.getByteBuffer () inherited
Returns the byte buffer for this struct. This method will allocate a new direct buffer if none has been set.
Changes to the buffer's content are visible in this struct, and vice versa.
The buffer of an inner struct is the same as its parent struct.
If no byte buffer has been set, a direct buffer is allocated with a capacity equals to this struct's size.
Returns
the current byte buffer or a new direct buffer if none set.
See also
setByteBuffer
Definition at line 254 of file Struct.java.
{
         if (_outer != null) return _outer.getByteBuffer();
         return (_byteBuffer != null) ? _byteBuffer : newBuffer();
     }
References javolution.io.Struct._byteBuffer, javolution.io.Struct._outer, javolution.io.Struct.getByteBuffer(), and javolution.io.Struct.newBuffer().
Referenced by javolution.io.Struct.address(), javolution.io.Struct.UTF8String.get(), javolution.io.Struct.Bool.get(), javolution.io.Struct.Signed8.get(), javolution.io.Struct.Unsigned8.get(), javolution.io.Struct.Signed16.get(), javolution.io.Struct.Unsigned16.get(), javolution.io.Struct.Signed32.get(), javolution.io.Struct.Unsigned32.get(), javolution.io.Struct.Signed64.get(), javolution.io.Struct.Float32.get(), javolution.io.Struct.Float64.get(), javolution.io.Struct.Enum8< T extends Enum< T >.get(), javolution.io.Struct.Enum16< T extends Enum< T >.get(), javolution.io.Struct.Enum32< T extends Enum< T >.get(), javolution.io.Struct.Enum64< T extends Enum< T >.get(), javolution.io.Struct.getByteBuffer(), javolution.io.Struct.Reference32< S extends Struct >.isUpToDate(), javolution.io.Struct.Reference64< S extends Struct >.isUpToDate(), javolution.io.Struct.read(), javolution.io.Struct.readByteBufferLong(), javolution.io.Struct.UTF8String.set(), javolution.io.Struct.Bool.set(), javolution.io.Struct.Signed8.set(), javolution.io.Struct.Unsigned8.set(), javolution.io.Struct.Signed16.set(), javolution.io.Struct.Unsigned16.set(), javolution.io.Struct.Signed32.set(), javolution.io.Struct.Unsigned32.set(), javolution.io.Struct.Signed64.set(), javolution.io.Struct.Float32.set(), javolution.io.Struct.Float64.set(), javolution.io.Struct.Reference32< S extends Struct >.set(), javolution.io.Struct.Reference64< S extends Struct >.set(), javolution.io.Struct.Enum8< T extends Enum< T >.set(), javolution.io.Struct.Enum16< T extends Enum< T >.set(), javolution.io.Struct.Enum32< T extends Enum< T >.set(), javolution.io.Struct.Enum64< T extends Enum< T >.set(), javolution.io.Struct.setByteBufferPosition(), javolution.io.Struct.toString(), javolution.io.Struct.Reference32< S extends Struct >.value(), javolution.io.Struct.Reference64< S extends Struct >.value(), javolution.io.Struct.write(), and javolution.io.Struct.writeByteBufferLong().
getByteBufferPosition()
final int javolution.io.Struct.getByteBufferPosition () inherited
Returns the absolute byte position of this struct within its associated byte buffer.
Returns
the absolute position of this struct (can be an inner struct) in the byte buffer.
Definition at line 312 of file Struct.java.
{
         return (_outer != null) ? _outer.getByteBufferPosition() + _outerOffset
                 : _outerOffset;
     }
References javolution.io.Struct._outer, javolution.io.Struct._outerOffset, and javolution.io.Struct.getByteBufferPosition().
Referenced by javolution.io.Struct.UTF8String.get(), javolution.io.Struct.Bool.get(), javolution.io.Struct.Signed8.get(), javolution.io.Struct.Unsigned8.get(), javolution.io.Struct.Signed16.get(), javolution.io.Struct.Unsigned16.get(), javolution.io.Struct.Signed32.get(), javolution.io.Struct.Unsigned32.get(), javolution.io.Struct.Signed64.get(), javolution.io.Struct.Float32.get(), javolution.io.Struct.Float64.get(), javolution.io.Struct.Enum8< T extends Enum< T >.get(), javolution.io.Struct.Enum16< T extends Enum< T >.get(), javolution.io.Struct.Enum32< T extends Enum< T >.get(), javolution.io.Struct.Enum64< T extends Enum< T >.get(), javolution.io.Struct.getByteBufferPosition(), javolution.io.Struct.Reference32< S extends Struct >.isUpToDate(), javolution.io.Struct.Reference64< S extends Struct >.isUpToDate(), javolution.io.Struct.read(), javolution.io.Struct.readBits(), javolution.io.Struct.UTF8String.set(), javolution.io.Struct.Bool.set(), javolution.io.Struct.Signed8.set(), javolution.io.Struct.Unsigned8.set(), javolution.io.Struct.Signed16.set(), javolution.io.Struct.Unsigned16.set(), javolution.io.Struct.Signed32.set(), javolution.io.Struct.Unsigned32.set(), javolution.io.Struct.Signed64.set(), javolution.io.Struct.Float32.set(), javolution.io.Struct.Float64.set(), javolution.io.Struct.Reference32< S extends Struct >.set(), javolution.io.Struct.Reference64< S extends Struct >.set(), javolution.io.Struct.Enum8< T extends Enum< T >.set(), javolution.io.Struct.Enum16< T extends Enum< T >.set(), javolution.io.Struct.Enum32< T extends Enum< T >.set(), javolution.io.Struct.Enum64< T extends Enum< T >.set(), javolution.io.Struct.toString(), javolution.io.Struct.Reference32< S extends Struct >.value(), javolution.io.Struct.Reference64< S extends Struct >.value(), javolution.io.Struct.write(), and javolution.io.Struct.writeBits().
inner()
protected<S extends Struct> S javolution.io.Struct.inner (S struct) package inherited
Defines the specified struct as inner of this struct.
Parameters
struct the inner struct.
Returns
the specified struct.
Exceptions
IllegalArgumentException if the specified struct is already an inner struct.
Definition at line 513 of file Struct.java.
{
         if (struct._outer != null) throw new IllegalArgumentException(
                 "struct: Already an inner struct");
         Member inner = new Member(struct.size() << 3, struct._alignment); // Update indexes.
         struct._outer = this;
         struct._outerOffset = inner.offset();
         return (S) struct;
     }
References javolution.io.Struct._alignment, javolution.io.Struct._outer, and javolution.io.Struct.size().
Referenced by javolution.io.Struct.array().
isPacked()
boolean javolution.io.Struct.isPacked () inherited
Indicates if this struct is packed (configurable). By default, members of a struct are aligned on the boundary corresponding to the member base type; padding is performed if necessary. This directive is not inherited by inner structs. Sub-classes may change the packing directive by overriding this method. For example:[code] public class MyStruct extends Struct { ... // Members initialization. public boolean isPacked() { return true; // MyStruct is packed. } }}[/code]
Returns
true if word size requirements are ignored. false otherwise (default).
Definition at line 501 of file Struct.java.
{
         return false;
     }
Referenced by javolution.io.Struct.Member.Member().
isUnion()
final boolean javolution.io.Union.isUnion ()
Returns true.
Returns
true
Reimplemented from javolution.io.Struct.
Definition at line 48 of file Union.java.
{
         return true;
     }
newBuffer()
synchronized ByteBuffer javolution.io.Struct.newBuffer () private inherited
Definition at line 259 of file Struct.java.
{
         if (_byteBuffer != null) return _byteBuffer; // Synchronized check.
         ByteBuffer bf = ByteBuffer.allocateDirect(size());
         bf.order(byteOrder());
         setByteBuffer(bf, 0);
         return _byteBuffer;
     }
References javolution.io.Struct._byteBuffer, javolution.io.Struct.byteOrder(), javolution.io.Struct.setByteBuffer(), and javolution.io.Struct.size().
Referenced by javolution.io.Struct.getByteBuffer().
outer()
Struct javolution.io.Struct.outer () inherited
Returns the outer of this struct or null if this struct is not an inner struct.
Returns
the outer struct or null.
Definition at line 236 of file Struct.java.
{
         return _outer;
     }
References javolution.io.Struct._outer.
read()
int javolution.io.Struct.read (InputStream in) throws IOException inherited
Reads this struct from the specified input stream (convenience method when using Stream I/O). For better performance, use of Block I/O (e.g. java.nio.channels.*) is recommended. This method behaves appropriately when not all of the data is available from the input stream. Incomplete data is extremely common when the input stream is associated with something like a TCP connection. The typical usage pattern in those scenarios is to repeatedly call read() until the entire message is received.
Parameters
in the input stream being read from.
Returns
the number of bytes read (typically the size of this struct.
Exceptions
IOException if an I/O error occurs.
Definition at line 332 of file Struct.java.
{
         ByteBuffer buffer = getByteBuffer();
         int size = size();
         int remaining = size - buffer.position();
         if (remaining == 0) remaining = size;// at end so move to beginning
         int alreadyRead = size - remaining; // typically 0
         if (buffer.hasArray()) {
             int offset = buffer.arrayOffset() + getByteBufferPosition();
             int bytesRead = in
                     .read(buffer.array(), offset + alreadyRead, remaining);
             buffer.position(getByteBufferPosition() + alreadyRead + bytesRead
                     - offset);
             return bytesRead;
         } else {
             synchronized (buffer) {
                 if (_bytes == null) {
                     _bytes = new byte[size()];
                 }
                 int bytesRead = in.read(_bytes, 0, remaining);
                 buffer.position(getByteBufferPosition() + alreadyRead);
                 buffer.put(_bytes, 0, bytesRead);
                 return bytesRead;
             }
         }
     }
References javolution.io.Struct._bytes, javolution.io.Struct.getByteBuffer(), javolution.io.Struct.getByteBufferPosition(), and javolution.io.Struct.size().
readBits()
long javolution.io.Struct.readBits (int bitOffset, int bitSize) inherited
Reads the specified bits from this Struct as an long (signed) integer value.
Parameters
bitOffset the bit start position in the Struct.
bitSize the number of bits.
Returns
the specified bits read as a signed long.
Exceptions
IllegalArgumentException if (bitOffset + bitSize - 1) / 8 >= this.size()
Definition at line 770 of file Struct.java.
{
         if ((bitOffset + bitSize - 1) >> 3 >= this.size()) throw new IllegalArgumentException(
                 "Attempt to read outside the Struct");
         int offset = bitOffset >> 3;
         int bitStart = bitOffset - (offset << 3);
         bitStart = (byteOrder() == ByteOrder.BIG_ENDIAN) ? bitStart : 64
                 - bitSize - bitStart;
         int index = getByteBufferPosition() + offset;
         long value = readByteBufferLong(index);
         value <<= bitStart; // Clears preceding bits.
         value >>= (64 - bitSize); // Signed shift.
         return value;
     }
References javolution.io.Struct.byteOrder(), javolution.io.Struct.getByteBufferPosition(), javolution.io.Struct.readByteBufferLong(), and javolution.io.Struct.size().
Referenced by javolution.io.Struct.BitField.longValue().
readByte()
static byte javolution.io.Struct.readByte (int index, ByteBuffer byteBuffer) static private inherited
Definition at line 809 of file Struct.java.
{
         return (index < byteBuffer.limit()) ? byteBuffer.get(index) : 0;
     }
Referenced by javolution.io.Struct.readByteBufferLong().
readByteBufferLong()
long javolution.io.Struct.readByteBufferLong (int index) private inherited
Definition at line 784 of file Struct.java.
{
         ByteBuffer byteBuffer = getByteBuffer();
         if (index + 8 < byteBuffer.limit()) return byteBuffer.getLong(index);
         // Else possible buffer overflow.
         if (byteBuffer.order() == ByteOrder.LITTLE_ENDIAN) {
             return (readByte(index, byteBuffer) & 0xff)
                     + ((readByte(++index, byteBuffer) & 0xff) << 8)
                     + ((readByte(++index, byteBuffer) & 0xff) << 16)
                     + ((readByte(++index, byteBuffer) & 0xffL) << 24)
                     + ((readByte(++index, byteBuffer) & 0xffL) << 32)
                     + ((readByte(++index, byteBuffer) & 0xffL) << 40)
                     + ((readByte(++index, byteBuffer) & 0xffL) << 48)
                     + ((readByte(++index, byteBuffer) & 0xffL) << 56);
         } else {
             return (((long) readByte(index, byteBuffer)) << 56)
                     + ((readByte(++index, byteBuffer) & 0xffL) << 48)
                     + ((readByte(++index, byteBuffer) & 0xffL) << 40)
                     + ((readByte(++index, byteBuffer) & 0xffL) << 32)
                     + ((readByte(++index, byteBuffer) & 0xffL) << 24)
                     + ((readByte(++index, byteBuffer) & 0xff) << 16)
                     + ((readByte(++index, byteBuffer) & 0xff) << 8)
                     + (readByte(++index, byteBuffer) & 0xffL);
         }
     }
References javolution.io.Struct.getByteBuffer(), and javolution.io.Struct.readByte().
Referenced by javolution.io.Struct.readBits(), and javolution.io.Struct.writeBits().
setByteBuffer()
final Struct javolution.io.Struct.setByteBuffer (ByteBuffer byteBuffer, int position) inherited
Sets the current byte buffer for this struct. The specified byte buffer can be mapped to memory for direct memory access or can wrap a shared byte array for I/O purpose (e.g. DatagramPacket). The capacity of the specified byte buffer should be at least the size of this struct plus the offset position.
Parameters
byteBuffer the new byte buffer.
position the position of this struct in the specified byte buffer.
Returns
this
Exceptions
IllegalArgumentException if the specified byteBuffer has a different byte order than this struct.
UnsupportedOperationException if this struct is an inner struct.
See also
byteOrder()
Definition at line 283 of file Struct.java.
{
         if (byteBuffer.order() != byteOrder()) throw new IllegalArgumentException(
                 "The byte order of the specified byte buffer"
                         + " is different from this struct byte order");
         if (_outer != null) throw new UnsupportedOperationException(
                 "Inner struct byte buffer is inherited from outer");
         _byteBuffer = byteBuffer;
         _outerOffset = position;
         return this;
     }
References javolution.io.Struct._byteBuffer, javolution.io.Struct._outer, javolution.io.Struct._outerOffset, and javolution.io.Struct.byteOrder().
Referenced by javolution.io.Struct.newBuffer(), and javolution.io.Struct.setByteBufferPosition().
setByteBufferPosition()
final Struct javolution.io.Struct.setByteBufferPosition (int position) inherited
Sets the byte position of this struct within its byte buffer.
Parameters
position the position of this struct in its byte buffer.
Returns
this
Exceptions
UnsupportedOperationException if this struct is an inner struct.
Definition at line 301 of file Struct.java.
{
         return setByteBuffer(this.getByteBuffer(), position);
     }
References javolution.io.Struct.getByteBuffer(), and javolution.io.Struct.setByteBuffer().
size()
final int javolution.io.Struct.size () inherited
Returns the size in bytes of this struct. The size includes tail padding to satisfy the struct word size requirement (defined by the largest word size of its members).
Returns
the C/C++ sizeof(this).
Definition at line 225 of file Struct.java.
{
         return (_alignment <= 1) ? _length
                 : ((_length + _alignment - 1) / _alignment) * _alignment;
     }
References javolution.io.Struct._alignment, and javolution.io.Struct._length.
Referenced by javolution.io.Struct.inner(), javolution.io.Struct.newBuffer(), javolution.io.Struct.read(), javolution.io.Struct.readBits(), javolution.io.Struct.toString(), javolution.io.Struct.write(), and javolution.io.Struct.writeBits().
toString()
String javolution.io.Struct.toString () inherited
Returns the String representation of this struct in the form of its constituing bytes (hexadecimal). For example:[code] public static class Student extends Struct { Utf8String name = new Utf8String(16); Unsigned16 year = new Unsigned16(); Float32 grade = new Float32(); } Student student = new Student(); student.name.set("John Doe"); student.year.set(2003); student.grade.set(12.5f); System.out.println(student);
4A 6F 68 6E 20 44 6F 65 00 00 00 00 00 00 00 00 07 D3 00 00 41 48 00 00[/code]
Returns
a hexadecimal representation of the bytes content for this struct.
Definition at line 420 of file Struct.java.
{
         TextBuilder tmp = new TextBuilder();
         final int size = size();
         final ByteBuffer buffer = getByteBuffer();
         final int start = getByteBufferPosition();
         for (int i = 0; i < size; i++) {
             int b = buffer.get(start + i) & 0xFF;
             tmp.append(HEXA[b >> 4]);
             tmp.append(HEXA[b & 0xF]);
             tmp.append(((i & 0xF) == 0xF) ? '\n' : ' ');
         }
         return tmp.toString();
     }
References javolution.text.TextBuilder.append(), javolution.io.Struct.getByteBuffer(), javolution.io.Struct.getByteBufferPosition(), javolution.io.Struct.HEXA, javolution.io.Struct.size(), and javolution.text.TextBuilder.toString().
write()
void javolution.io.Struct.write (OutputStream out) throws IOException inherited
Writes this struct to the specified output stream (convenience method when using Stream I/O). For better performance, use of Block I/O (e.g. java.nio.channels.*) is recommended.
Parameters
out the output stream to write to.
Exceptions
IOException if an I/O error occurs.
Definition at line 366 of file Struct.java.
{
         ByteBuffer buffer = getByteBuffer();
         if (buffer.hasArray()) {
             int offset = buffer.arrayOffset() + getByteBufferPosition();
             out.write(buffer.array(), offset, size());
         } else {
             synchronized (buffer) {
                 if (_bytes == null) {
                     _bytes = new byte[size()];
                 }
                 buffer.position(getByteBufferPosition());
                 buffer.get(_bytes);
                 out.write(_bytes);
             }
         }
     }
References javolution.io.Struct._bytes, javolution.io.Struct.getByteBuffer(), javolution.io.Struct.getByteBufferPosition(), and javolution.io.Struct.size().
writeBits()
void javolution.io.Struct.writeBits (long value, int bitOffset, int bitSize) inherited
Writes the specified bits into this Struct.
Parameters
value the bits value as a signed long.
bitOffset the bit start position in the Struct.
bitSize the number of bits.
Exceptions
IllegalArgumentException if (bitOffset + bitSize - 1) / 8 >= this.size()
Definition at line 822 of file Struct.java.
{
         if ((bitOffset + bitSize - 1) >> 3 >= this.size()) throw new IllegalArgumentException(
                 "Attempt to write outside the Struct");
         int offset = bitOffset >> 3;
         int bitStart = (byteOrder() == ByteOrder.BIG_ENDIAN) ? bitOffset
                 - (offset << 3) : 64 - bitSize - (bitOffset - (offset << 3));
         long mask = -1L;
         mask <<= bitStart; // Clears preceding bits
         mask >>>= (64 - bitSize); // Unsigned shift.
         mask <<= 64 - bitSize - bitStart;
         value <<= (64 - bitSize - bitStart);
         value &= mask; // Protects against out of range values.
         int index = getByteBufferPosition() + offset;
         long oldValue = readByteBufferLong(index);
         long resetValue = oldValue & (~mask);
         long newValue = resetValue | value;
         writeByteBufferLong(index, newValue);
     }
References javolution.io.Struct.byteOrder(), javolution.io.Struct.getByteBufferPosition(), javolution.io.Struct.readByteBufferLong(), javolution.io.Struct.size(), and javolution.io.Struct.writeByteBufferLong().
Referenced by javolution.io.Struct.BitField.set().
writeByte()
static void javolution.io.Struct.writeByte (int index, ByteBuffer byteBuffer, byte value) static private inherited
Definition at line 869 of file Struct.java.
{
         if (index < byteBuffer.limit()) {
             byteBuffer.put(index, value);
         }
     }
Referenced by javolution.io.Struct.writeByteBufferLong().
writeByteBufferLong()
void javolution.io.Struct.writeByteBufferLong (int index, long value) private inherited
Definition at line 841 of file Struct.java.
{
         ByteBuffer byteBuffer = getByteBuffer();
         if (index + 8 < byteBuffer.limit()) {
             byteBuffer.putLong(index, value);
             return;
         }
         // Else possible buffer overflow.
         if (byteBuffer.order() == ByteOrder.LITTLE_ENDIAN) {
             writeByte(index, byteBuffer, (byte) value);
             writeByte(++index, byteBuffer, (byte) (value >> 8));
             writeByte(++index, byteBuffer, (byte) (value >> 16));
             writeByte(++index, byteBuffer, (byte) (value >> 24));
             writeByte(++index, byteBuffer, (byte) (value >> 32));
             writeByte(++index, byteBuffer, (byte) (value >> 40));
             writeByte(++index, byteBuffer, (byte) (value >> 48));
             writeByte(++index, byteBuffer, (byte) (value >> 56));
         } else {
             writeByte(index, byteBuffer, (byte) (value >> 56));
             writeByte(++index, byteBuffer, (byte) (value >> 48));
             writeByte(++index, byteBuffer, (byte) (value >> 40));
             writeByte(++index, byteBuffer, (byte) (value >> 32));
             writeByte(++index, byteBuffer, (byte) (value >> 24));
             writeByte(++index, byteBuffer, (byte) (value >> 16));
             writeByte(++index, byteBuffer, (byte) (value >> 8));
             writeByte(++index, byteBuffer, (byte) value);
         }
     }
References javolution.io.Struct.getByteBuffer(), and javolution.io.Struct.writeByte().
Referenced by javolution.io.Struct.writeBits().
Member Data Documentation
_alignment
int javolution.io.Struct._alignment = 1 package inherited
Holds this struct alignment in bytes (largest word size of its members).
Definition at line 181 of file Struct.java.
Referenced by javolution.io.Struct.inner(), javolution.io.Struct.Member.Member(), and javolution.io.Struct.size().
_bitsUsed
int javolution.io.Struct._bitsUsed package inherited
Holds the bits used in the word during construction (for bit fields). This is the number of bits used in the last word.
Definition at line 200 of file Struct.java.
Referenced by javolution.io.Struct.Member.Member().
_byteBuffer
ByteBuffer javolution.io.Struct._byteBuffer package inherited
Holds the byte buffer backing the struct (top struct).
Definition at line 172 of file Struct.java.
Referenced by javolution.io.Struct.getByteBuffer(), javolution.io.Struct.newBuffer(), and javolution.io.Struct.setByteBuffer().
_bytes
byte [] javolution.io.Struct._bytes package inherited
Holds bytes array for Stream I/O when byteBuffer has no intrinsic array.
Definition at line 209 of file Struct.java.
Referenced by javolution.io.Struct.read(), and javolution.io.Struct.write().
_index
int javolution.io.Struct._index package inherited
Holds the index position during construction. This is the index a the first unused byte available.
Definition at line 190 of file Struct.java.
Referenced by javolution.io.Struct.array(), and javolution.io.Struct.Member.Member().
_length
int javolution.io.Struct._length package inherited
Holds this struct's length.
Definition at line 185 of file Struct.java.
Referenced by javolution.io.Struct.Member.Member(), and javolution.io.Struct.size().
_outer
Struct javolution.io.Struct._outer package inherited
Holds the outer struct if any.
Definition at line 168 of file Struct.java.
Referenced by javolution.io.Struct.byteOrder(), javolution.io.Struct.getByteBuffer(), javolution.io.Struct.getByteBufferPosition(), javolution.io.Struct.inner(), javolution.io.Struct.outer(), and javolution.io.Struct.setByteBuffer().
_outerOffset
int javolution.io.Struct._outerOffset package inherited
Holds the offset of this struct relative to the outer struct or to the byte buffer if there is no outer.
Definition at line 177 of file Struct.java.
Referenced by javolution.io.Struct.getByteBufferPosition(), and javolution.io.Struct.setByteBuffer().
_resetIndex
boolean javolution.io.Struct._resetIndex package inherited
Indicates if the index has to be reset for each new field (true only for Union subclasses).
Definition at line 205 of file Struct.java.
Referenced by javolution.io.Struct.array(), javolution.io.Struct.Member.Member(), and javolution.io.Struct.Struct().
_wordSize
int javolution.io.Struct._wordSize package inherited
Holds the word size during construction (for bit fields). This is the size of the last word used.
Definition at line 195 of file Struct.java.
Referenced by javolution.io.Struct.Member.Member().
BOOL
final Class<? extends Bool[]> javolution.io.Struct.BOOL = new Bool[0].getClass() static private inherited
Definition at line 673 of file Struct.java.
Referenced by javolution.io.Struct.array().
FLOAT_32
final Class<? extends Float32[]> javolution.io.Struct.FLOAT_32 static private inherited
Initial value:
= new Float32[0]
            .getClass()
Definition at line 688 of file Struct.java.
Referenced by javolution.io.Struct.array().
FLOAT_64
final Class<? extends Float64[]> javolution.io.Struct.FLOAT_64 static private inherited
Initial value:
= new Float64[0]
            .getClass()
Definition at line 690 of file Struct.java.
Referenced by javolution.io.Struct.array().
HEXA
final char [] javolution.io.Struct.HEXA static private inherited
Initial value:
= { '0', '1', '2', '3', '4', '5', '6',
            '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F' }
Definition at line 434 of file Struct.java.
Referenced by javolution.io.Struct.toString().
MAXIMUM_ALIGNMENT
final LocalContext.Parameter<Integer> javolution.io.Struct.MAXIMUM_ALIGNMENT static inherited
Initial value:
= new LocalContext.Parameter<Integer>() {
        @Override
        protected Integer getDefault() {
            return 4;
        }
    }
Configurable holding the maximum wordSize in bytes (default 4). Should be a value greater or equal to 1.
Definition at line 158 of file Struct.java.
SIGNED_16
final Class<? extends Signed16[]> javolution.io.Struct.SIGNED_16 static private inherited
Initial value:
= new Signed16[0]
            .getClass()
Definition at line 678 of file Struct.java.
Referenced by javolution.io.Struct.array().
SIGNED_32
final Class<? extends Signed32[]> javolution.io.Struct.SIGNED_32 static private inherited
Initial value:
= new Signed32[0]
            .getClass()
Definition at line 682 of file Struct.java.
Referenced by javolution.io.Struct.array().
SIGNED_64
final Class<? extends Signed64[]> javolution.io.Struct.SIGNED_64 static private inherited
Initial value:
= new Signed64[0]
            .getClass()
Definition at line 686 of file Struct.java.
Referenced by javolution.io.Struct.array().
SIGNED_8
final Class<? extends Signed8[]> javolution.io.Struct.SIGNED_8 static private inherited
Initial value:
= new Signed8[0]
            .getClass()
Definition at line 674 of file Struct.java.
Referenced by javolution.io.Struct.array().
UNSIGNED_16
final Class<? extends Unsigned16[]> javolution.io.Struct.UNSIGNED_16 static private inherited
Initial value:
= new Unsigned16[0]
            .getClass()
Definition at line 680 of file Struct.java.
Referenced by javolution.io.Struct.array().
UNSIGNED_32
final Class<? extends Unsigned32[]> javolution.io.Struct.UNSIGNED_32 static private inherited
Initial value:
= new Unsigned32[0]
            .getClass()
Definition at line 684 of file Struct.java.
Referenced by javolution.io.Struct.array().
UNSIGNED_8
final Class<? extends Unsigned8[]> javolution.io.Struct.UNSIGNED_8 static private inherited
Initial value:
= new Unsigned8[0]
            .getClass()
Definition at line 676 of file Struct.java.
Referenced by javolution.io.Struct.array().
The documentation for this class was generated from the following file:
Union.java