Javolution 6.0.0 java: javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl Class Reference
javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl Class Reference
Public Member Functions
boolean hasNext ()
Entry< K, V > next ()
void remove ()
Private Attributes
boolean ahead
final Equality<? super K > cmp = keyComparator()
Entry< K, V > next
final Iterator< Entry< K, V > > targetIterator
Detailed Description
Peeking ahead iterator.
Definition at line 23 of file SubSortedMapImpl.java.
Member Function Documentation
hasNext()
boolean javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.hasNext ()
Definition at line 32 of file SubSortedMapImpl.java.
{
             if (ahead) return true;
             while (targetIterator.hasNext()) {
                 next = targetIterator.next();
                 if ((from != null) && (cmp.compare(next.getKey(), from) < 0)) continue;
                 if ((to != null) && (cmp.compare(next.getKey(), to) >= 0)) break;
                 ahead = true;
                 return true;
             }
             return false;
         }
References javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.ahead, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.cmp, javolution.util.function.Equality< T >.compare(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.from, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.next, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.targetIterator, and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.to.
Referenced by javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.next().
next()
Entry<K, V> javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.next ()
Definition at line 45 of file SubSortedMapImpl.java.
{
             hasNext(); // Moves ahead.
             ahead = false;
             return next;
         }
References javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.ahead, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.hasNext(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.next.
remove()
void javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.remove ()
Definition at line 52 of file SubSortedMapImpl.java.
{
             targetIterator.remove();
         }
References javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.targetIterator.
Member Data Documentation
ahead
boolean javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.ahead private
Definition at line 25 of file SubSortedMapImpl.java.
Referenced by javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.hasNext(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.next().
cmp
final Equality<? super K> javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.cmp = keyComparator() private
Definition at line 26 of file SubSortedMapImpl.java.
Referenced by javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.hasNext().
next
Entry<K, V> javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.next private
Definition at line 27 of file SubSortedMapImpl.java.
Referenced by javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.hasNext(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.next().
targetIterator
final Iterator<Entry<K, V> > javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.targetIterator private
Initial value:
= target()
                .iterator()
Definition at line 28 of file SubSortedMapImpl.java.
Referenced by javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.hasNext(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.remove().
The documentation for this class was generated from the following file:
SubSortedMapImpl.java