Javolution 6.0.0 java: javolution.util.internal.comparator.LexicalCaseInsensitiveComparatorImpl Class Reference
javolution.util.internal.comparator.LexicalCaseInsensitiveComparatorImpl Class Reference
Public Member Functions
int hashCodeOf (CharSequence csq)
boolean areEqual (CharSequence csq1, CharSequence csq2)
int compare (CharSequence left, CharSequence right)
int hashCodeOf (T object)
boolean areEqual (T left, T right)
int compare (T left, T right)
Static Private Member Functions
static char up (char c)
Static Private Attributes
static final long serialVersionUID = -1046672327934410697L
Detailed Description
The case insensitive lexical comparator implementation.
Definition at line 18 of file LexicalCaseInsensitiveComparatorImpl.java.
Member Function Documentation
areEqual() [1/2]
boolean javolution.util.internal.comparator.LexicalCaseInsensitiveComparatorImpl.areEqual (CharSequence csq1, CharSequence csq2)
Definition at line 35 of file LexicalCaseInsensitiveComparatorImpl.java.
{
         if (csq1 == csq2)
             return true;
         if ((csq1 == null) || (csq2 == null))
             return false;
         if ((csq1 instanceof String) && (csq2 instanceof String)) // Optimization.
             return ((String) csq1).equalsIgnoreCase((String) csq2);
         int n = csq1.length();
         if (csq2.length() != n)
             return false;
         for (int i = 0; i < n;) {
             if (up(csq1.charAt(i)) != up(csq2.charAt(i++)))
                 return false;
         }
         return true;
     }
References javolution.util.internal.comparator.LexicalCaseInsensitiveComparatorImpl.up().
areEqual() [2/2]
boolean javolution.util.function.Equality< T >.areEqual (T left, T right) inherited
Indicates if the specified objects can be considered equal. This methods is equivalent to
(compare(o1, o2) == 0)
but usually faster.
Parameters
left the first object (or null).
right the second object (or null).
Returns
true if both objects are considered equal; false otherwise.
Referenced by javolution.util.internal.map.MapView< K, V >.EntryComparator.areEqual(), javolution.util.internal.collection.CollectionView< R >.contains(), javolution.util.internal.collection.CollectionView< R >.equals(), javolution.util.internal.table.TableView< E >.indexOf(), javolution.util.internal.table.TableView< E >.lastIndexOf(), javolution.util.internal.map.FastMapImpl< K, V >.remove(), javolution.util.internal.collection.CollectionView< R >.remove(), and javolution.util.internal.map.FastMapImpl< K, V >.replace().
compare() [1/2]
int javolution.util.internal.comparator.LexicalCaseInsensitiveComparatorImpl.compare (CharSequence left, CharSequence right)
Definition at line 53 of file LexicalCaseInsensitiveComparatorImpl.java.
{
         if (left == null)
             return -1;
         if (right == null)
             return 1;
         if ((left instanceof String) && (right instanceof String)) // Optimization.
             return ((String) left).compareToIgnoreCase((String) right);
         int i = 0;
         int n = Math.min(left.length(), right.length());
         while (n-- != 0) {
             char c1 = up(left.charAt(i));
             char c2 = up(right.charAt(i++));
             if (c1 != c2)
                 return c1 - c2;
         }
         return left.length() - right.length();
     }
References javolution.util.internal.comparator.LexicalCaseInsensitiveComparatorImpl.up().
compare() [2/2]
int javolution.util.function.Equality< T >.compare (T left, T right) inherited
Compares the specified objects for order. Returns a negative integer, zero, or a positive integer as the first argument is less than, possibly equal to, or greater than the second. Implementation classes should ensure that comparisons with
null
is supported.
Parameters
left the first object.
right the second object.
Returns
a negative integer, zero, or a positive integer as the first argument is less than, possibly equal to, or greater than the second.
Referenced by javolution.util.internal.set.sorted.SubSortedSetImpl< E >.add(), javolution.util.internal.map.MapView< K, V >.EntryComparator.compare(), javolution.text.CharArray.compareTo(), javolution.text.Text.compareTo(), javolution.util.internal.set.sorted.SubSortedSetImpl< E >.contains(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.containsKey(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.get(), javolution.util.internal.set.sorted.SubSortedSetImpl< E >.IteratorImpl.hasNext(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.hasNext(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.put(), javolution.util.internal.set.sorted.SubSortedSetImpl< E >.remove(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.remove().
hashCodeOf() [1/2]
int javolution.util.internal.comparator.LexicalCaseInsensitiveComparatorImpl.hashCodeOf (CharSequence csq)
Definition at line 24 of file LexicalCaseInsensitiveComparatorImpl.java.
{
         if (csq == null)
             return 0;
         int h = 0;
         for (int i = 0, n = csq.length(); i < n;) {
             h = 31 * h + up(csq.charAt(i++));
         }
         return h;
     }
References javolution.util.internal.comparator.LexicalCaseInsensitiveComparatorImpl.up().
hashCodeOf() [2/2]
int javolution.util.function.Equality< T >.hashCodeOf (T object) inherited
Returns the hash code for the specified object (consistent with areEqual). Two objects considered equal have the same hash code. The hash code of null is always 0.
Parameters
object the object to return the hashcode for.
Returns
the hashcode for the specified object.
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.containsKey(), javolution.util.internal.map.FastMapImpl< K, V >.get(), javolution.util.internal.collection.CollectionView< R >.hashCode(), javolution.util.internal.map.MapView< K, V >.EntryComparator.hashCodeOf(), javolution.util.internal.map.FastMapImpl< K, V >.put(), javolution.util.internal.map.FastMapImpl< K, V >.putIfAbsent(), javolution.util.internal.map.FastMapImpl< K, V >.remove(), and javolution.util.internal.map.FastMapImpl< K, V >.replace().
up()
static char javolution.util.internal.comparator.LexicalCaseInsensitiveComparatorImpl.up (char c) static private
Definition at line 72 of file LexicalCaseInsensitiveComparatorImpl.java.
{
         return Character.toUpperCase(c);
     }
Referenced by javolution.util.internal.comparator.LexicalCaseInsensitiveComparatorImpl.areEqual(), javolution.util.internal.comparator.LexicalCaseInsensitiveComparatorImpl.compare(), and javolution.util.internal.comparator.LexicalCaseInsensitiveComparatorImpl.hashCodeOf().
Member Data Documentation
serialVersionUID
final long javolution.util.internal.comparator.LexicalCaseInsensitiveComparatorImpl.serialVersionUID = -1046672327934410697L static private
Definition at line 21 of file LexicalCaseInsensitiveComparatorImpl.java.
The documentation for this class was generated from the following file:
LexicalCaseInsensitiveComparatorImpl.java