Javolution 6.0.0 java: javolution.text.TextContext Class Reference
javolution.text.TextContext Class Reference abstract
Public Member Functions
abstract< T > void setFormat (Class<? extends T > type, TextFormat< T > newFormat)
void exit ()
Static Public Member Functions
static TextContext enter ()
static< T > TextFormat< T > getFormat (Class<? extends T > type)
static AbstractContext current ()
static< T extends AbstractContext > T enter (Class< T > custom)
static void inherit (AbstractContext ctx)
Protected Member Functions
TextContext ()
abstract< T > TextFormat< T > searchFormat (Class<? extends T > type)
AbstractContext enterInner ()
AbstractContext getOuter ()
abstract AbstractContext inner ()
Static Protected Member Functions
static< T extends AbstractContext > T current (Class< T > type)
Static Private Member Functions
static TextContext currentTextContext ()
Private Attributes
AbstractContext outer
Static Private Attributes
static final ThreadLocal< AbstractContext > CURRENT = new ThreadLocal<AbstractContext>()
Detailed Description
A context for plain text parsing/formatting. This context provides the TextFormat to parse/format objects of any class. If not superseded, the text format for a class is specified by the DefaultTextFormat annotation.
A text context always returns the most specialized format. If the class has no default format annotation (inherited or not), then the default java.lang.Object format (which calls Object#toString) is returned. A predefined format exists for the following standard types:
java.lang.Object (parsing not supported, formatting calls toString())
java.lang.Boolean
java.lang.Character
java.lang.Byte
java.lang.Short
java.lang.Integer
java.lang.Long
java.lang.Float
java.lang.Double
java.lang.Class
java.lang.String
java.util.Date (ISO 8601)
java.math.BigInteger
java.math.BigDecimal
java.awt.Color (hexadecimal RGB value, e.g.
0x112233
)
java.awt.Font
Author
Jean-Marie Dautelle
Version
6.0 December 12, 2012
Definition at line 49 of file TextContext.java.
Constructor & Destructor Documentation
TextContext()
javolution.text.TextContext.TextContext () protected
Default constructor.
Definition at line 54 of file TextContext.java.
 {}
Member Function Documentation
current() [1/2]
static AbstractContext javolution.context.AbstractContext.current () static inherited
Returns the current context for the current thread or
null
if this thread has no context (default).
Definition at line 61 of file AbstractContext.java.
{
         return AbstractContext.CURRENT.get();
     }
References javolution.context.AbstractContext.CURRENT.
Referenced by javolution.context.LogContext.currentLogContext(), javolution.context.SecurityContext.currentSecurityContext(), javolution.text.TextContext.currentTextContext(), javolution.xml.XMLContext.currentXMLContext(), javolution.context.LocalContext.enter(), javolution.context.ConcurrentContext.enter(), and javolution.context.LocalContext.Parameter< T >.get().
current() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.current (Class< T > type) static protected inherited
Returns the current context of specified type or
null
if none.
Definition at line 69 of file AbstractContext.java.
{
         AbstractContext ctx = AbstractContext.CURRENT.get();
         while (ctx != null) {
             if (type.isInstance(ctx))
                 return (T) ctx;
             ctx = ctx.outer;
         }
         return null;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
currentTextContext()
static TextContext javolution.text.TextContext.currentTextContext () static private
Returns the current text context.
Definition at line 87 of file TextContext.java.
{
         TextContext ctx = AbstractContext.current(TextContext.class);
         if (ctx != null)
             return ctx;
         return OSGiServices.getTextContext();
     }
References javolution.context.AbstractContext.current(), and javolution.osgi.internal.OSGiServices.getTextContext().
Referenced by javolution.text.TextContext.enter(), and javolution.text.TextContext.getFormat().
enter() [1/2]
static TextContext javolution.text.TextContext.enter () static
Enters and returns a new text context instance.
Definition at line 59 of file TextContext.java.
{
         return (TextContext) TextContext.currentTextContext().enterInner();
     }
References javolution.text.TextContext.currentTextContext(), and javolution.context.AbstractContext.enterInner().
enter() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.enter (Class< T > custom) static inherited
Enters the scope of a custom context. This method raises a SecurityException if the permission to enter contexts of the specified class is not granted. For example, the following disallow entering any custom context. [code] SecurityContext ctx = SecurityContext.enter(); try { ctx.revoke(new SecurityContext.Permission(AbstractContext.class, "enter")); ... // Cannot enter any custom context. } finally { ctx.exit(); // Back to previous security settings. }[/code]
Parameters
custom the custom context to enter.
Exceptions
IllegalArgumentException if the specified class default constructor cannot be instantiated.
SecurityException if
SecurityContext.Permission(custom, "enter")
is not granted.
See also
SecurityContext.Permission
Definition at line 101 of file AbstractContext.java.
{
         SecurityContext.check(new Permission<T>(custom, "enter"));
         try {
             return (T) custom.newInstance().enterInner();
         } catch (InstantiationException e) {
             throw new IllegalArgumentException(
                     "Cannot instantiate instance of " + custom, e);
         } catch (IllegalAccessException e) {
             throw new IllegalArgumentException("Cannot access " + custom, e);
         }
     }
References javolution.context.SecurityContext.check().
enterInner()
AbstractContext javolution.context.AbstractContext.enterInner () protected inherited
Enters the scope of an inner context which becomes the current context; the previous current context becomes the outer of this context.
Returns
the inner context entered.
Definition at line 141 of file AbstractContext.java.
{
         AbstractContext inner = inner();
         inner.outer = AbstractContext.CURRENT.get();
         AbstractContext.CURRENT.set(inner);
         return inner;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
Referenced by javolution.xml.XMLContext.enter(), javolution.text.TextContext.enter(), javolution.context.LogContext.enter(), javolution.context.LocalContext.enter(), javolution.context.SecurityContext.enter(), and javolution.context.ConcurrentContext.enter().
exit()
void javolution.context.AbstractContext.exit () inherited
Exits the scope of this context; the outer of this context becomes
the current context.
Exceptions
IllegalStateException if this context is not the current context.
Reimplemented in javolution.context.ConcurrentContext, and javolution.context.internal.ConcurrentContextImpl.
Definition at line 155 of file AbstractContext.java.
{
         if (this != AbstractContext.CURRENT.get())
             throw new IllegalStateException(
                     "This context is not the current context");
         AbstractContext.CURRENT.set(outer);
         outer = null;
     }
References javolution.context.AbstractContext.CURRENT.
getFormat()
static <T> TextFormat<T> javolution.text.TextContext.getFormat (Class<? extends T > type) static
Returns the text format for the specified type. It is the most specialized format able to parse/format instances of the specified class. If there is no default format for the specified class, the standard object format (toString based) is returned.
Definition at line 69 of file TextContext.java.
{
         return TextContext.currentTextContext().searchFormat(type);
     }
References javolution.text.TextContext.currentTextContext(), and javolution.text.TextContext.searchFormat().
Referenced by javolution.text.TextBuilder.append(), javolution.util.FastCollection< E >.Format.format(), javolution.xml.XMLFormat< T >.InputElement.getAttribute(), javolution.xml.XMLFormat< T >.Default.newInstance(), javolution.lang.Configurable< javolution.context.LogContext.Level >.parse(), javolution.util.Index.toString(), javolution.util.FastMap< Object, javolution.util.Index >.toString(), javolution.util.FastCollection< E >.toString(), and javolution.xml.XMLFormat< T >.Default.write().
getOuter()
AbstractContext javolution.context.AbstractContext.getOuter () protected inherited
Returns the outer context of this context or
null
if this context has no outer context.
Definition at line 167 of file AbstractContext.java.
{
         return outer;
     }
inherit()
static void javolution.context.AbstractContext.inherit (AbstractContext ctx) static inherited
Inherits the specified context which becomes the context of the current thread. This method is particularly useful when creating new threads to make them inherits from the context stack of the parent thread. [code] //Spawns a new thread inheriting the context of the current thread. MyThread myThread = new MyThread(); myThread.inherited = AbstractContext.current(); myThread.start(); ... class MyThread extends Thread { AbstractContext inherited; public void run() { AbstractContext.inherit(inherited); // Sets current context. ... } }[/code]
Definition at line 131 of file AbstractContext.java.
{
         CURRENT.set(ctx);
     }
Referenced by javolution.context.internal.ConcurrentThreadImpl.run().
inner()
abstract AbstractContext javolution.context.AbstractContext.inner () abstract protected inherited
Returns a new inner instance of this context inheriting the properties of this context. The new instance can be configured independently from its parent.
Reimplemented in javolution.context.internal.ConcurrentContextImpl, javolution.text.internal.TextContextImpl, javolution.context.internal.LogContextImpl, javolution.context.internal.SecurityContextImpl, javolution.xml.internal.XMLContextImpl, and javolution.context.internal.LocalContextImpl.
searchFormat()
abstract <T> TextFormat<T> javolution.text.TextContext.searchFormat (Class<? extends T > type) abstract protected
Searches the most specialized format for the specified type.
Reimplemented in javolution.text.internal.TextContextImpl.
Referenced by javolution.text.TextContext.getFormat().
setFormat()
abstract <T> void javolution.text.TextContext.setFormat (Class<? extends T > type, TextFormat< T > newFormat) abstract
Sets the text format for the specified type (and its sub-types).
Reimplemented in javolution.text.internal.TextContextImpl.
Member Data Documentation
CURRENT
final ThreadLocal<AbstractContext> javolution.context.AbstractContext.CURRENT = new ThreadLocal<AbstractContext>() static private inherited
Holds the last context entered (thread-local).
Definition at line 45 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), javolution.context.AbstractContext.enterInner(), and javolution.context.AbstractContext.exit().
outer
AbstractContext javolution.context.AbstractContext.outer private inherited
Holds the outer context or
null
if none (top context).
Definition at line 50 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), and javolution.context.AbstractContext.enterInner().
The documentation for this class was generated from the following file:
TextContext.java