Javolution 6.0.0 java: javolution.text.TypeFormat Class Reference
javolution.text.TypeFormat Class Reference
Static Public Member Functions
static boolean parseBoolean (CharSequence csq, Cursor cursor)
static boolean parseBoolean (CharSequence csq)
static byte parseByte (CharSequence csq, int radix, Cursor cursor)
static byte parseByte (CharSequence csq, int radix)
static byte parseByte (CharSequence csq, Cursor cursor)
static byte parseByte (CharSequence csq)
static short parseShort (CharSequence csq, int radix, Cursor cursor)
static short parseShort (CharSequence csq, int radix)
static short parseShort (CharSequence csq, Cursor cursor)
static short parseShort (CharSequence csq)
static int parseInt (CharSequence csq, int radix, Cursor cursor)
static int parseInt (CharSequence csq, int radix)
static int parseInt (CharSequence csq, Cursor cursor)
static int parseInt (CharSequence csq)
static long parseLong (CharSequence csq, int radix, Cursor cursor)
static long parseLong (CharSequence csq, int radix)
static long parseLong (CharSequence csq, Cursor cursor)
static long parseLong (CharSequence csq)
static float parseFloat (CharSequence csq, Cursor cursor)
static float parseFloat (CharSequence csq)
static double parseDouble (CharSequence csq, Cursor cursor) throws NumberFormatException
static double parseDouble (CharSequence csq) throws NumberFormatException
static Appendable format (boolean b, Appendable a) throws IOException
static Appendable format (int i, Appendable a) throws IOException
static Appendable format (int i, int radix, Appendable a) throws IOException
static Appendable format (long l, Appendable a) throws IOException
static Appendable format (long l, int radix, Appendable a) throws IOException
static Appendable format (float f, Appendable a) throws IOException
static Appendable format (double d, Appendable a) throws IOException
static Appendable format (double d, int digits, boolean scientific, boolean showZero, Appendable a) throws IOException
Static Package Functions
static boolean match (String str, CharSequence csq, int start, int length)
static boolean match (String str, String csq, int start, int length)
Private Member Functions
TypeFormat ()
Static Private Attributes
static final int INT_MAX_DIV10 = Integer.MAX_VALUE / 10
static final long LONG_MAX_DIV10 = Long.MAX_VALUE / 10
Detailed Description
Utility class to parse CharSequence into primitive types and to format primitive types into any Appendable.
Methods from this class do not create temporary objects and are typically faster than standard library methods.
The number of digits when formatting floating point numbers can be specified. The default setting for double is 17 digits or even 16 digits when the conversion is lossless back and forth (mimic the standard library formatting).
[code] TypeFormat.format(0.2, a) = "0.2" // 17 or 16 digits (as long as lossless conversion), remove trailing zeros. TypeFormat.format(0.2, 17, false, false, a) = "0.20000000000000001" // Closest 17 digits number. TypeFormat.format(0.2, 19, false, false, a) = "0.2000000000000000111" // Closest 19 digits. TypeFormat.format(0.2, 4, false, false, a) = "0.2" // Fixed-point notation, remove trailing zeros. TypeFormat.format(0.2, 4, false, true, a) = "0.2000" // Fixed-point notation, fixed number of digits. TypeFormat.format(0.2, 4, true, false, a) = "2.0E-1" // Scientific notation, remove trailing zeros.
TypeFormat.format(0.2, 4, true, true, a) = "2.000E-1" // Scientific notation, fixed number of digits. [/code]
For non-primitive objects, formatting is typically performed using specialized TextFormat instances.
Author
Jean-Marie Dautelle
Version
5.3, February 15, 2009
Definition at line 43 of file TypeFormat.java.
Constructor & Destructor Documentation
TypeFormat()
javolution.text.TypeFormat.TypeFormat () private
Default constructor (forbids derivation).
Definition at line 48 of file TypeFormat.java.
 {}
Member Function Documentation
format() [1/8]
static Appendable javolution.text.TypeFormat.format (boolean b, Appendable a) throws IOException static
Formats the specified boolean and appends the resulting text to the Appendable argument.
Parameters
b a boolean.
a the Appendable to append.
Returns
the specified StringBuffer object.
Exceptions
IOException if an I/O exception occurs.
Definition at line 597 of file TypeFormat.java.
{
         return b ? a.append("true") : a.append("false");
     }
Referenced by javolution.util.Index.Decimal.format(), and javolution.text.TypeFormat.format().
format() [2/8]
static Appendable javolution.text.TypeFormat.format (double d, Appendable a) throws IOException static
Formats the specified double value (16 or 17 digits output).
Parameters
d the double value.
a the Appendable to append.
Returns
TypeFormat.format(d, -1, (MathLib.abs(d) >= 1E7) || (MathLib.abs(d) < 0.001), false, a)
Exceptions
IOException if an I/O exception occurs.
See also
TextBuilder::append(double)
Definition at line 700 of file TypeFormat.java.
{
         return TypeFormat.format(d, -1,
                 (MathLib.abs(d) >= 1E7) || (MathLib.abs(d) < 0.001), false, a);
     }
References javolution.lang.MathLib.abs(), and javolution.text.TypeFormat.format().
format() [3/8]
static Appendable javolution.text.TypeFormat.format (double d, int digits, boolean scientific, boolean showZero, Appendable a) throws IOException static
Formats the specified double value according to the specified formatting arguments.
Parameters
d the double value.
digits the number of significative digits (excludes exponent) or -1 to mimic the standard library (16 or 17 digits).
scientific true to forces the use of the scientific notation (e.g. 1.23E3); false otherwise.
showZero true if trailing fractional zeros are represented; false otherwise.
a the Appendable to append.
Returns
the specified Appendable object.
Exceptions
IllegalArgumentException if (digits > 19))
IOException if an I/O exception occurs.
See also
TextBuilder::append(double, int, boolean, boolean)
Definition at line 723 of file TypeFormat.java.
{
         if (a instanceof TextBuilder)
             return ((TextBuilder) a).append(d, digits, scientific, showZero);
         TextBuilder tb = new TextBuilder();
         tb.append(d, digits, scientific, showZero);
         return a.append(tb);
     }
References javolution.text.TextBuilder.append().
format() [4/8]
static Appendable javolution.text.TypeFormat.format (float f, Appendable a) throws IOException static
Formats the specified float value.
Parameters
f the float value.
a the Appendable to append.
Returns
TypeFormat.format(f, 10, (MathLib.abs(f) >= 1E7) || (MathLib.abs(f) < 0.001), false, a)
Exceptions
IOException if an I/O exception occurs.
Definition at line 686 of file TypeFormat.java.
{
         return TypeFormat.format(f, 10,
                 (MathLib.abs(f) >= 1E7) || (MathLib.abs(f) < 0.001), false, a);
     }
References javolution.lang.MathLib.abs(), and javolution.text.TypeFormat.format().
format() [5/8]
static Appendable javolution.text.TypeFormat.format (int i, Appendable a) throws IOException static
Formats the specified int and appends the resulting text (decimal representation) to the Appendable argument.
Parameters
i the int number.
a the Appendable to append.
Returns
the specified Appendable object.
Exceptions
IOException if an I/O exception occurs.
Definition at line 611 of file TypeFormat.java.
{
         if (a instanceof TextBuilder)
             return ((TextBuilder) a).append(i);
         TextBuilder tb = new TextBuilder();
         tb.append(i);
         return a.append(tb);
     }
References javolution.text.TextBuilder.append().
format() [6/8]
static Appendable javolution.text.TypeFormat.format (int i, int radix, Appendable a) throws IOException static
Formats the specified int in the specified radix and appends the resulting text to the Appendable argument.
Parameters
i the int number.
radix the radix.
a the Appendable to append.
Returns
the specified Appendable object.
Exceptions
IllegalArgumentException if radix is not in [2 .. 36] range.
IOException if an I/O exception occurs.
Definition at line 630 of file TypeFormat.java.
{
         if (a instanceof TextBuilder)
             return ((TextBuilder) a).append(i, radix);
         TextBuilder tb = new TextBuilder();
         tb.append(i, radix);
         return a.append(tb);
     }
References javolution.text.TextBuilder.append().
format() [7/8]
static Appendable javolution.text.TypeFormat.format (long l, Appendable a) throws IOException static
Formats the specified long and appends the resulting text (decimal representation) to the Appendable argument.
Parameters
l the long number.
a the Appendable to append.
Returns
the specified Appendable object.
Exceptions
IOException if an I/O exception occurs.
See also
parseLong
Definition at line 649 of file TypeFormat.java.
{
         if (a instanceof TextBuilder)
             return ((TextBuilder) a).append(l);
         TextBuilder tb = new TextBuilder();
         tb.append(l);
         return a.append(tb);
     }
References javolution.text.TextBuilder.append().
format() [8/8]
static Appendable javolution.text.TypeFormat.format (long l, int radix, Appendable a) throws IOException static
Formats the specified long in the specified radix and appends the resulting text to the Appendable argument.
Parameters
l the long number.
radix the radix.
a the Appendable to append.
Returns
the specified Appendable object.
Exceptions
IllegalArgumentException if radix is not in [2 .. 36] range.
IOException if an I/O exception occurs.
See also
parseLong(CharSequence, int)
Definition at line 669 of file TypeFormat.java.
{
         if (a instanceof TextBuilder)
             return ((TextBuilder) a).append(l, radix);
         TextBuilder tb = new TextBuilder();
         tb.append(l, radix);
         return a.append(tb);
     }
References javolution.text.TextBuilder.append().
match() [1/2]
static boolean javolution.text.TypeFormat.match (String str, CharSequence csq, int start, int length) static package
Definition at line 569 of file TypeFormat.java.
{
         for (int i = 0; i < str.length(); i++) {
             if ((start + i >= length) || csq.charAt(start + i) != str.charAt(i))
                 return false;
         }
         return true;
     }
Referenced by javolution.text.TypeFormat.parseDouble().
match() [2/2]
static boolean javolution.text.TypeFormat.match (String str, String csq, int start, int length) static package
Definition at line 577 of file TypeFormat.java.
{
         for (int i = 0; i < str.length(); i++) {
             if ((start + i >= length) || csq.charAt(start + i) != str.charAt(i))
                 return false;
         }
         return true;
     }
parseBoolean() [1/2]
static boolean javolution.text.TypeFormat.parseBoolean (CharSequence csq) static
Parses the whole specified character sequence as a boolean.
Parameters
csq the character sequence to parse.
Returns
parseBoolean(csq, new Cursor())
Exceptions
IllegalArgumentException if the specified character sequence is different from "true" or "false" ignoring cases.
Definition at line 96 of file TypeFormat.java.
{
         Cursor cursor = new Cursor();
         boolean result = parseBoolean(csq, cursor);
         if (!cursor.atEnd(csq))
             throw new IllegalArgumentException("Extraneous characters \""
                     + cursor.tail(csq) + "\"");
         return result;
     }
References javolution.text.Cursor.atEnd(), javolution.text.TypeFormat.parseBoolean(), and javolution.text.Cursor.tail().
parseBoolean() [2/2]
static boolean javolution.text.TypeFormat.parseBoolean (CharSequence csq, Cursor cursor) static
Parses the specified character sequence from the specified position as a boolean ignoring cases.
Parameters
csq the character sequence to parse.
cursor the cursor position (being maintained).
Returns
the next boolean value.
Exceptions
IllegalArgumentException if the character sequence from the specified position is different from "true" or "false" ignoring cases.
Definition at line 65 of file TypeFormat.java.
{
         int start = cursor.getIndex();
         int end = csq.length();
         if ((end >= start + 5)
                 && (csq.charAt(start) == 'f' || csq.charAt(start) == 'F')) { // False.
             if ((csq.charAt(++start) == 'a' || csq.charAt(start) == 'A')
                     && (csq.charAt(++start) == 'l' || csq.charAt(start) == 'L')
                     && (csq.charAt(++start) == 's' || csq.charAt(start) == 'S')
                     && (csq.charAt(++start) == 'e' || csq.charAt(start) == 'E')) {
                 cursor.increment(5);
                 return false;
             }
         } else if ((end >= start + 4)
                 && (csq.charAt(start) == 't' || csq.charAt(start) == 'T')) // True.
             if ((csq.charAt(++start) == 'r' || csq.charAt(start) == 'R')
                     && (csq.charAt(++start) == 'u' || csq.charAt(start) == 'U')
                     && (csq.charAt(++start) == 'e' || csq.charAt(start) == 'E')) {
                 cursor.increment(4);
                 return true;
             }
         throw new IllegalArgumentException("Invalid boolean representation");
     }
References javolution.text.Cursor.getIndex(), and javolution.text.Cursor.increment().
Referenced by javolution.text.TypeFormat.parseBoolean(), javolution.text.internal.TextContextImpl.storePrimitiveTypesFormats(), and javolution.text.CharArray.toBoolean().
parseByte() [1/4]
static byte javolution.text.TypeFormat.parseByte (CharSequence csq) static
Parses the whole specified character sequence as a signed decimal byte.
Parameters
csq the character sequence to parse.
Returns
parseByte(csq, 10)
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable byte or contains extraneous characters.
Definition at line 167 of file TypeFormat.java.
{
         return parseByte(csq, 10);
     }
References javolution.text.TypeFormat.parseByte().
parseByte() [2/4]
static byte javolution.text.TypeFormat.parseByte (CharSequence csq, Cursor cursor) static
Parses the specified character sequence from the specified position as a signed decimal byte.
Parameters
csq the character sequence to parse.
cursor the cursor position being updated.
Returns
the corresponding byte.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable byte.
Definition at line 153 of file TypeFormat.java.
{
         return parseByte(csq, 10, cursor);
     }
References javolution.text.TypeFormat.parseByte().
parseByte() [3/4]
static byte javolution.text.TypeFormat.parseByte (CharSequence csq, int radix) static
Parses the whole specified character sequence
as a signed byte in the specified radix.
Parameters
csq the character sequence to parse.
radix the radix to be used while parsing.
Returns
the corresponding byte.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable byte or contains extraneous characters.
Definition at line 134 of file TypeFormat.java.
{
         Cursor cursor = new Cursor();
         byte result = parseByte(csq, radix, cursor);
         if (!cursor.atEnd(csq))
             throw new IllegalArgumentException("Extraneous characters \""
                     + cursor.tail(csq) + "\"");
         return result;
     }
References javolution.text.Cursor.atEnd(), javolution.text.TypeFormat.parseByte(), and javolution.text.Cursor.tail().
parseByte() [4/4]
static byte javolution.text.TypeFormat.parseByte (CharSequence csq, int radix, Cursor cursor) static
Parses the specified character sequence from the specified position as a signed byte in the specified radix.
Parameters
csq the character sequence to parse.
radix the radix to be used while parsing.
cursor the cursor position being updated.
Returns
the corresponding byte.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable byte.
Definition at line 116 of file TypeFormat.java.
{
         int i = parseInt(csq, radix, cursor);
         if ((i < Byte.MIN_VALUE) || (i > Byte.MAX_VALUE))
             throw new NumberFormatException("Overflow");
         return (byte) i;
     }
References javolution.text.TypeFormat.parseInt().
Referenced by javolution.text.TypeFormat.parseByte().
parseDouble() [1/2]
static double javolution.text.TypeFormat.parseDouble (CharSequence csq) throws NumberFormatException static
Parses the whole specified character sequence as a double. The format must be of the form: <decimal>{'.'<fraction>}{'E|e'<exponent>}.
Parameters
csq the character sequence to parse.
Returns
the double number represented by this character sequence.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable long or contains extraneous characters.
Definition at line 559 of file TypeFormat.java.
{
         Cursor cursor = new Cursor();
         double result = parseDouble(csq, cursor);
         if (!cursor.atEnd(csq))
             throw new IllegalArgumentException("Extraneous characters \""
                     + cursor.tail(csq) + "\"");
         return result;
     }
References javolution.text.Cursor.atEnd(), javolution.text.TypeFormat.parseDouble(), and javolution.text.Cursor.tail().
parseDouble() [2/2]
static double javolution.text.TypeFormat.parseDouble (CharSequence csq, Cursor cursor) throws NumberFormatException static
Parses the specified character sequence from the specified position as a double.
Parameters
csq the character sequence to parse.
cursor the cursor position (being maintained) or null> to parse the whole character sequence.
Returns
the double number represented by this character sequence.
Exceptions
NumberFormatException if the character sequence does not contain a parsable double.
Definition at line 464 of file TypeFormat.java.
{
         final int start = cursor.getIndex();
         final int end = csq.length();
         int i = start;
         char c = csq.charAt(i);
         // Checks for NaN.
         if ((c == 'N') && match("NaN", csq, i, end)) {
             cursor.increment(3);
             return Double.NaN;
         }
         // Reads sign.
         boolean isNegative = (c == '-');
         if ((isNegative || (c == '+')) && (++i < end))
             c = csq.charAt(i);
         // Checks for Infinity.
         if ((c == 'I') && match("Infinity", csq, i, end)) {
             cursor.increment(i + 8 - start);
             return isNegative ? Double.NEGATIVE_INFINITY
                     : Double.POSITIVE_INFINITY;
         }
         // At least one digit or a '.' required.
         if (((c < '0') || (c > '9')) && (c != '.'))
             throw new NumberFormatException("Digit or '.' required");
         // Reads decimal and fraction (both merged to a long).
         long decimal = 0;
         int decimalPoint = -1;
         while (true) {
             int digit = c - '0';
             if ((digit >= 0) && (digit < 10)) {
                 long tmp = decimal * 10 + digit;
                 if ((decimal > LONG_MAX_DIV10) || (tmp < decimal))
                     throw new NumberFormatException(
                             "Too many digits - Overflow");
                 decimal = tmp;
             } else if ((c == '.') && (decimalPoint < 0))
                 decimalPoint = i;
             else
                 break;
             if (++i >= end)
                 break;
             c = csq.charAt(i);
         }
         if (isNegative)
             decimal = -decimal;
         int fractionLength = (decimalPoint >= 0) ? i - decimalPoint - 1 : 0;
         // Reads exponent.
         int exp = 0;
         if ((i < end) && ((c == 'E') || (c == 'e'))) {
             c = csq.charAt(++i);
             boolean isNegativeExp = (c == '-');
             if ((isNegativeExp || (c == '+')) && (++i < end))
                 c = csq.charAt(i);
             if ((c < '0') || (c > '9')) // At least one digit required.
                 throw new NumberFormatException("Invalid exponent");
             while (true) {
                 int digit = c - '0';
                 if ((digit >= 0) && (digit < 10)) {
                     int tmp = exp * 10 + digit;
                     if ((exp > INT_MAX_DIV10) || (tmp < exp))
                         throw new NumberFormatException("Exponent Overflow");
                     exp = tmp;
                 } else
                     break;
                 if (++i >= end)
                     break;
                 c = csq.charAt(i);
             }
             if (isNegativeExp)
                 exp = -exp;
         }
         cursor.increment(i - start);
         return javolution.lang.MathLib.toDoublePow10(decimal, exp
                 - fractionLength);
     }
References javolution.text.TypeFormat.INT_MAX_DIV10, javolution.text.TypeFormat.LONG_MAX_DIV10, javolution.text.TypeFormat.match(), and javolution.lang.MathLib.toDoublePow10().
Referenced by javolution.text.TypeFormat.parseDouble(), javolution.text.TypeFormat.parseFloat(), and javolution.text.CharArray.toDouble().
parseFloat() [1/2]
static float javolution.text.TypeFormat.parseFloat (CharSequence csq) static
Parses the whole specified character sequence as a float.
Parameters
csq the character sequence to parse.
Returns
the float number represented by the specified character sequence.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable long or contains extraneous characters.
Definition at line 449 of file TypeFormat.java.
{
         return (float) parseDouble(csq);
     }
References javolution.text.TypeFormat.parseDouble().
parseFloat() [2/2]
static float javolution.text.TypeFormat.parseFloat (CharSequence csq, Cursor cursor) static
Parses the specified character sequence from the specified position as a float.
Parameters
csq the character sequence to parse.
cursor the cursor position (being maintained) or null> to parse the whole character sequence.
Returns
the float number represented by the specified character sequence.
Definition at line 436 of file TypeFormat.java.
{
         return (float) parseDouble(csq, cursor);
     }
References javolution.text.TypeFormat.parseDouble().
Referenced by javolution.text.CharArray.toFloat().
parseInt() [1/4]
static int javolution.text.TypeFormat.parseInt (CharSequence csq) static
Parses the whole specified character sequence as a signed decimal int.
Parameters
csq the character sequence to parse.
Returns
parseInt(csq, 10)
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable int or contains extraneous characters.
Definition at line 328 of file TypeFormat.java.
{
         return parseInt(csq, 10);
     }
References javolution.text.TypeFormat.parseInt().
parseInt() [2/4]
static int javolution.text.TypeFormat.parseInt (CharSequence csq, Cursor cursor) static
Parses the specified character sequence from the specified position as a signed decimal int.
Parameters
csq the character sequence to parse.
cursor the cursor position being updated.
Returns
the corresponding int.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable int.
Definition at line 314 of file TypeFormat.java.
{
         return parseInt(csq, 10, cursor);
     }
References javolution.text.TypeFormat.parseInt().
parseInt() [3/4]
static int javolution.text.TypeFormat.parseInt (CharSequence csq, int radix) static
Parses the whole specified character sequence
as a signed int in the specified radix.
Parameters
csq the character sequence to parse.
radix the radix to be used while parsing.
Returns
the corresponding int.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable int or contains extraneous characters.
Definition at line 295 of file TypeFormat.java.
{
         Cursor cursor = new Cursor();
         int result = parseInt(csq, radix, cursor);
         if (!cursor.atEnd(csq))
             throw new IllegalArgumentException("Extraneous characters \""
                     + cursor.tail(csq) + "\"");
         return result;
     }
References javolution.text.Cursor.atEnd(), javolution.text.TypeFormat.parseInt(), and javolution.text.Cursor.tail().
parseInt() [4/4]
static int javolution.text.TypeFormat.parseInt (CharSequence csq, int radix, Cursor cursor) static
Parses the specified character sequence from the specified position as a signed int in the specified radix.
Parameters
csq the character sequence to parse.
radix the radix to be used while parsing.
cursor the cursor position being updated.
Returns
the corresponding int.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable int.
Definition at line 248 of file TypeFormat.java.
{
         int start = cursor.getIndex();
         int end = csq.length();
         boolean isNegative = false;
         int result = 0; // Accumulates negatively (avoid MIN_VALUE overflow).
         int i = start;
         for (; i < end; i++) {
             char c = csq.charAt(i);
             int digit = (c <= '9') ? c - '0'
                     : ((c <= 'Z') && (c >= 'A')) ? c - 'A' + 10
                             : ((c <= 'z') && (c >= 'a')) ? c - 'a' + 10 : -1;
             if ((digit >= 0) && (digit < radix)) {
                 int newResult = result * radix - digit;
                 if (newResult > result)
                     throw new NumberFormatException("Overflow parsing "
                             + csq.subSequence(start, end));
                 result = newResult;
             } else if ((c == '-') && (i == start))
                 isNegative = true;
             else if ((c == '+') && (i == start)) {
                 // Ok.
             } else
                 break;
         }
         // Requires one valid digit character and checks for opposite overflow.
         if ((result == 0) && ((end == 0) || (csq.charAt(i - 1) != '0')))
             throw new NumberFormatException(
                     "Invalid integer representation for "
                             + csq.subSequence(start, end));
         if ((result == Integer.MIN_VALUE) && !isNegative)
             throw new NumberFormatException("Overflow parsing "
                     + csq.subSequence(start, end));
         cursor.increment(i - start);
         return isNegative ? result : -result;
     }
References javolution.text.Cursor.getIndex(), and javolution.text.Cursor.increment().
Referenced by javolution.util.Index.Decimal.parse(), javolution.text.TypeFormat.parseByte(), javolution.text.TypeFormat.parseInt(), javolution.text.TypeFormat.parseShort(), and javolution.text.CharArray.toInt().
parseLong() [1/4]
static long javolution.text.TypeFormat.parseLong (CharSequence csq) static
Parses the whole specified character sequence as a signed decimal long.
Parameters
csq the character sequence to parse.
Returns
parseLong(csq, 10)
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable long or contains extraneous characters.
Definition at line 423 of file TypeFormat.java.
{
         return parseLong(csq, 10);
     }
References javolution.text.TypeFormat.parseLong().
parseLong() [2/4]
static long javolution.text.TypeFormat.parseLong (CharSequence csq, Cursor cursor) static
Parses the specified character sequence from the specified position as a signed decimal long.
Parameters
csq the character sequence to parse.
cursor the cursor position being updated.
Returns
the corresponding long.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable long.
Definition at line 409 of file TypeFormat.java.
{
         return parseLong(csq, 10, cursor);
     }
References javolution.text.TypeFormat.parseLong().
parseLong() [3/4]
static long javolution.text.TypeFormat.parseLong (CharSequence csq, int radix) static
Parses the whole specified character sequence
as a signed long in the specified radix.
Parameters
csq the character sequence to parse.
radix the radix to be used while parsing.
Returns
the corresponding long.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable long or contains extraneous characters.
Definition at line 390 of file TypeFormat.java.
{
         Cursor cursor = new Cursor();
         long result = parseLong(csq, radix, cursor);
         if (!cursor.atEnd(csq))
             throw new IllegalArgumentException("Extraneous characters \""
                     + cursor.tail(csq) + "\"");
         return result;
     }
References javolution.text.Cursor.atEnd(), javolution.text.TypeFormat.parseLong(), and javolution.text.Cursor.tail().
parseLong() [4/4]
static long javolution.text.TypeFormat.parseLong (CharSequence csq, int radix, Cursor cursor) static
Parses the specified character sequence from the specified position as a signed long in the specified radix.
Parameters
csq the character sequence to parse.
radix the radix to be used while parsing.
cursor the cursor position being updated.
Returns
the corresponding long.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable long.
Definition at line 343 of file TypeFormat.java.
{
         final int start = cursor.getIndex();
         final int end = csq.length();
         boolean isNegative = false;
         long result = 0; // Accumulates negatively (avoid MIN_VALUE overflow).
         int i = start;
         for (; i < end; i++) {
             char c = csq.charAt(i);
             int digit = (c <= '9') ? c - '0'
                     : ((c <= 'Z') && (c >= 'A')) ? c - 'A' + 10
                             : ((c <= 'z') && (c >= 'a')) ? c - 'a' + 10 : -1;
             if ((digit >= 0) && (digit < radix)) {
                 long newResult = result * radix - digit;
                 if (newResult > result)
                     throw new NumberFormatException("Overflow parsing "
                             + csq.subSequence(start, end));
                 result = newResult;
             } else if ((c == '-') && (i == start))
                 isNegative = true;
             else if ((c == '+') && (i == start)) {
                 // Ok.
             } else
                 break;
         }
         // Requires one valid digit character and checks for opposite overflow.
         if ((result == 0) && ((end == 0) || (csq.charAt(i - 1) != '0')))
             throw new NumberFormatException(
                     "Invalid integer representation for "
                             + csq.subSequence(start, end));
         if ((result == Long.MIN_VALUE) && !isNegative)
             throw new NumberFormatException("Overflow parsing "
                     + csq.subSequence(start, end));
         cursor.increment(i - start);
         return isNegative ? result : -result;
     }
References javolution.text.Cursor.getIndex(), and javolution.text.Cursor.increment().
Referenced by javolution.text.TypeFormat.parseLong(), and javolution.text.CharArray.toLong().
parseShort() [1/4]
static short javolution.text.TypeFormat.parseShort (CharSequence csq) static
Parses the whole specified character sequence as a signed decimal short.
Parameters
csq the character sequence to parse.
Returns
parseShort(csq, 10)
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable short or contains extraneous characters.
Definition at line 233 of file TypeFormat.java.
{
         return parseShort(csq, 10);
     }
References javolution.text.TypeFormat.parseShort().
parseShort() [2/4]
static short javolution.text.TypeFormat.parseShort (CharSequence csq, Cursor cursor) static
Parses the specified character sequence from the specified position as a signed decimal short.
Parameters
csq the character sequence to parse.
cursor the cursor position being updated.
Returns
the corresponding short.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable short.
Definition at line 219 of file TypeFormat.java.
{
         return parseShort(csq, 10, cursor);
     }
References javolution.text.TypeFormat.parseShort().
parseShort() [3/4]
static short javolution.text.TypeFormat.parseShort (CharSequence csq, int radix) static
Parses the whole specified character sequence
as a signed short in the specified radix.
Parameters
csq the character sequence to parse.
radix the radix to be used while parsing.
Returns
the corresponding short.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable short or contains extraneous characters.
Definition at line 200 of file TypeFormat.java.
{
         Cursor cursor = new Cursor();
         short result = parseShort(csq, radix, cursor);
         if (!cursor.atEnd(csq))
             throw new IllegalArgumentException("Extraneous characters \""
                     + cursor.tail(csq) + "\"");
         return result;
     }
References javolution.text.Cursor.atEnd(), javolution.text.TypeFormat.parseShort(), and javolution.text.Cursor.tail().
parseShort() [4/4]
static short javolution.text.TypeFormat.parseShort (CharSequence csq, int radix, Cursor cursor) static
Parses the specified character sequence from the specified position as a signed short in the specified radix.
Parameters
csq the character sequence to parse.
radix the radix to be used while parsing.
cursor the cursor position being updated.
Returns
the corresponding short.
Exceptions
NumberFormatException if the specified character sequence does not contain a parsable short.
Definition at line 182 of file TypeFormat.java.
{
         int i = parseInt(csq, radix, cursor);
         if ((i < Short.MIN_VALUE) || (i > Short.MAX_VALUE))
             throw new NumberFormatException("Overflow");
         return (short) i;
     }
References javolution.text.TypeFormat.parseInt().
Referenced by javolution.text.TypeFormat.parseShort().
Member Data Documentation
INT_MAX_DIV10
final int javolution.text.TypeFormat.INT_MAX_DIV10 = Integer.MAX_VALUE / 10 static private
Definition at line 545 of file TypeFormat.java.
Referenced by javolution.text.TypeFormat.parseDouble().
LONG_MAX_DIV10
final long javolution.text.TypeFormat.LONG_MAX_DIV10 = Long.MAX_VALUE / 10 static private
Definition at line 546 of file TypeFormat.java.
Referenced by javolution.text.TypeFormat.parseDouble().
The documentation for this class was generated from the following file:
TypeFormat.java