Javolution 6.0.0 java: javolution.util.service.BitSetService Interface Reference
javolution.util.service.BitSetService Interface Reference
Public Member Functions
int cardinality ()
boolean get (int bitIndex)
BitSetService get (int fromIndex, int toIndex)
boolean intersects (BitSetService that)
int length ()
int nextClearBit (int fromIndex)
int nextSetBit (int fromIndex)
int previousClearBit (int fromIndex)
int previousSetBit (int fromIndex)
void clear (int bitIndex)
void clear (int fromIndex, int toIndex)
boolean getAndSet (int bitIndex, boolean value)
void set (int bitIndex)
void set (int bitIndex, boolean value)
void set (int fromIndex, int toIndex)
void set (int fromIndex, int toIndex, boolean value)
void flip (int bitIndex)
void flip (int fromIndex, int toIndex)
void and (BitSetService that)
void andNot (BitSetService that)
void or (BitSetService that)
void xor (BitSetService that)
long[] toLongArray ()
SetService< E > threadSafe ()
Detailed Description
The set of related functionalities which can be used/reused to implement bit-sets collections.
Author
Jean-Marie Dautelle
Version
6.0, July 21, 2013
See also
FastTable
Definition at line 23 of file BitSetService.java.
Member Function Documentation
and()
void javolution.util.service.BitSetService.and (BitSetService that)
See FastBitSet#and(FastBitSet)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.and().
andNot()
void javolution.util.service.BitSetService.andNot (BitSetService that)
See FastBitSet#andNot(FastBitSet)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.andNot().
cardinality()
int javolution.util.service.BitSetService.cardinality ()
See FastBitSet#cardinality()
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.cardinality().
clear() [1/2]
void javolution.util.service.BitSetService.clear (int bitIndex)
See FastBitSet#clear(int)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.clear(), and javolution.util.internal.bitset.BitSetIteratorImpl.remove().
clear() [2/2]
void javolution.util.service.BitSetService.clear (int fromIndex, int toIndex)
See FastBitSet#clear(int, int)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
flip() [1/2]
void javolution.util.service.BitSetService.flip (int bitIndex)
See FastBitSet#flip(int)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.flip().
flip() [2/2]
void javolution.util.service.BitSetService.flip (int fromIndex, int toIndex)
See FastBitSet#flip(int, int)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
get() [1/2]
boolean javolution.util.service.BitSetService.get (int bitIndex)
See FastBitSet#get(int)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.get().
get() [2/2]
BitSetService javolution.util.service.BitSetService.get (int fromIndex, int toIndex)
See FastBitSet#get(int, int)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
getAndSet()
boolean javolution.util.service.BitSetService.getAndSet (int bitIndex, boolean value)
Clear or sets the specified bit, returns true if previously set; false otherwise.
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
intersects()
boolean javolution.util.service.BitSetService.intersects (BitSetService that)
See FastBitSet#intersects(FastBitSet)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.intersects().
length()
int javolution.util.service.BitSetService.length ()
See FastBitSet#length()
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.length().
nextClearBit()
int javolution.util.service.BitSetService.nextClearBit (int fromIndex)
See FastBitSet#nextClearBit(int)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.nextClearBit().
nextSetBit()
int javolution.util.service.BitSetService.nextSetBit (int fromIndex)
See FastBitSet#nextSetBit(int)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.internal.bitset.BitSetIteratorImpl.BitSetIteratorImpl(), javolution.util.internal.bitset.BitSetIteratorImpl.next(), and javolution.util.FastBitSet.nextSetBit().
or()
void javolution.util.service.BitSetService.or (BitSetService that)
See FastBitSet#or(FastBitSet)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.or().
previousClearBit()
int javolution.util.service.BitSetService.previousClearBit (int fromIndex)
See FastBitSet#previousClearBit(int)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.previousClearBit().
previousSetBit()
int javolution.util.service.BitSetService.previousSetBit (int fromIndex)
See FastBitSet#previousSetBit(int)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.previousSetBit().
set() [1/4]
void javolution.util.service.BitSetService.set (int bitIndex)
See FastBitSet#set(int)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.set().
set() [2/4]
void javolution.util.service.BitSetService.set (int bitIndex, boolean value)
See FastBitSet#set(int, boolean)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
set() [3/4]
void javolution.util.service.BitSetService.set (int fromIndex, int toIndex)
See FastBitSet#set(int, int)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
set() [4/4]
void javolution.util.service.BitSetService.set (int fromIndex, int toIndex, boolean value)
See FastBitSet#set(int, int, boolean)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
threadSafe()
SetService<E> javolution.util.service.SetService< E >.threadSafe () inherited
Returns a thread-safe version of this service (used during parallel updates).
toLongArray()
long [] javolution.util.service.BitSetService.toLongArray ()
Returns the minimal length long[] representation of this bitset.
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.internal.bitset.BitSetServiceImpl.and(), javolution.util.internal.bitset.BitSetServiceImpl.andNot(), javolution.util.internal.bitset.BitSetServiceImpl.intersects(), javolution.util.internal.bitset.BitSetServiceImpl.or(), and javolution.util.internal.bitset.BitSetServiceImpl.xor().
xor()
void javolution.util.service.BitSetService.xor (BitSetService that)
See FastBitSet#xor(FastBitSet)
Implemented in javolution.util.internal.bitset.BitSetServiceImpl.
Referenced by javolution.util.FastBitSet.xor().
The documentation for this interface was generated from the following file:
BitSetService.java