Javolution 6.0.0 java: javolution.xml.internal.stream.NamespacesImpl Class Reference
javolution.xml.internal.stream.NamespacesImpl Class Reference
Public Member Functions
NamespacesImpl ()
CharArray getNamespaceURI (CharSequence prefix)
CharArray getPrefix (CharSequence uri)
Iterator< CharArray > getPrefixes (CharSequence namespaceURI)
void reset ()
Package Functions
CharArray getNamespaceURINullAllowed (CharSequence prefix)
CharArray getPrefix (CharSequence uri, int count)
void setPrefix (CharArray prefix, CharArray uri)
void setPrefix (final CharSequence prefix, CharSequence uri, boolean isWritten)
void pop ()
void push ()
Package Attributes
final CharArray _nullNsURI = new CharArray("")
final CharArray _defaultNsPrefix = new CharArray("")
final CharArray _xml = new CharArray("xml")
final CharArray _xmlURI
final CharArray _xmlns = new CharArray("xmlns")
final CharArray _xmlnsURI = new CharArray("http://www.w3.org/2000/xmlns/")
CharArray[] _prefixes = new CharArray[16]
CharArray[] _namespaces = new CharArray[_prefixes.length]
boolean[] _prefixesWritten = new boolean[_prefixes.length]
int[] _namespacesCount = new int[16]
CharArray _defaultNamespace = _nullNsURI
int _defaultNamespaceIndex
Static Package Attributes
static final int NBR_PREDEFINED_NAMESPACES = 3
Private Member Functions
void searchDefaultNamespace ()
void resizeNamespacesCount ()
void resizePrefixStack ()
Private Attributes
int _nesting = 0
CharArray[] _prefixesTmp = new CharArray[_prefixes.length]
CharArray[] _namespacesTmp = new CharArray[_prefixes.length]
Detailed Description
This class represents the namespaces stack while parsing.
Author
Jean-Marie Dautelle
Version
3.2, April 2, 2005
Definition at line 22 of file NamespacesImpl.java.
Constructor & Destructor Documentation
NamespacesImpl()
javolution.xml.internal.stream.NamespacesImpl.NamespacesImpl ()
Default constructor.
Definition at line 84 of file NamespacesImpl.java.
{
         _prefixes[0] = _defaultNsPrefix;
         _namespaces[0] = _nullNsURI;
         _prefixes[1] = _xml;
         _namespaces[1] = _xmlURI;
         _prefixes[2] = _xmlns;
         _namespaces[2] = _xmlnsURI;
         _namespacesCount[0] = NBR_PREDEFINED_NAMESPACES;
     }
References javolution.xml.internal.stream.NamespacesImpl._defaultNsPrefix, javolution.xml.internal.stream.NamespacesImpl._namespaces, javolution.xml.internal.stream.NamespacesImpl._namespacesCount, javolution.xml.internal.stream.NamespacesImpl._nullNsURI, javolution.xml.internal.stream.NamespacesImpl._prefixes, javolution.xml.internal.stream.NamespacesImpl._xml, javolution.xml.internal.stream.NamespacesImpl._xmlns, javolution.xml.internal.stream.NamespacesImpl._xmlnsURI, javolution.xml.internal.stream.NamespacesImpl._xmlURI, and javolution.xml.internal.stream.NamespacesImpl.NBR_PREDEFINED_NAMESPACES.
Member Function Documentation
getNamespaceURI()
CharArray javolution.xml.internal.stream.NamespacesImpl.getNamespaceURI (CharSequence prefix)
Returns the namespace URI bound to a prefix in the current scope or null if the prefix is unbound.
Parameters
prefix prefix to look up
Returns
the namespace URI.
Exceptions
IllegalArgumentException if prefix is null
Implements javolution.xml.stream.NamespaceContext.
Definition at line 95 of file NamespacesImpl.java.
{
         if (prefix == null)
             throw new IllegalArgumentException("null prefix not allowed");
         return getNamespaceURINullAllowed(prefix);
     }
References javolution.xml.internal.stream.NamespacesImpl.getNamespaceURINullAllowed().
Referenced by javolution.xml.internal.stream.AttributesImpl.getIndex(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI(), and javolution.xml.internal.stream.AttributesImpl.getURI().
getNamespaceURINullAllowed()
CharArray javolution.xml.internal.stream.NamespacesImpl.getNamespaceURINullAllowed (CharSequence prefix) package
Definition at line 101 of file NamespacesImpl.java.
{
         if ((prefix == null) || (prefix.length() == 0))
             return _defaultNamespace;
         final int count = _namespacesCount[_nesting];
         for (int i = count; --i >= 0;) {
             if (_prefixes[i].equals(prefix))
                 return _namespaces[i];
         }
         return null; // Not bound.
     }
References javolution.xml.internal.stream.NamespacesImpl._defaultNamespace, javolution.xml.internal.stream.NamespacesImpl._namespaces, javolution.xml.internal.stream.NamespacesImpl._namespacesCount, javolution.xml.internal.stream.NamespacesImpl._nesting, and javolution.xml.internal.stream.NamespacesImpl._prefixes.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeNamespace(), javolution.xml.internal.stream.NamespacesImpl.getNamespaceURI(), and javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI().
getPrefix() [1/2]
CharArray javolution.xml.internal.stream.NamespacesImpl.getPrefix (CharSequence namespaceURI)
Returns the prefix bound to the namespace URI in the current scope or null if the namespace URI is unbound.
Parameters
namespaceURI URI of the namespace to lookup.
Returns
the prefix bound to the namespace URI.
Exceptions
IllegalArgumentException if namespaceURI is null
Implements javolution.xml.stream.NamespaceContext.
Definition at line 113 of file NamespacesImpl.java.
{
         if (uri == null)
             throw new IllegalArgumentException("null namespace URI not allowed");
         return _defaultNamespace.equals(uri) ? _defaultNsPrefix : getPrefix(
                 uri, _namespacesCount[_nesting]);
     }
References javolution.xml.internal.stream.NamespacesImpl._defaultNamespace, javolution.xml.internal.stream.NamespacesImpl._defaultNsPrefix, javolution.xml.internal.stream.NamespacesImpl._namespacesCount, javolution.xml.internal.stream.NamespacesImpl._nesting, and javolution.text.CharArray.equals().
Referenced by javolution.xml.internal.stream.XMLStreamWriterImpl.getPrefix(), javolution.xml.internal.stream.XMLStreamWriterImpl.getRepairedPrefix(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeNamespaces().
getPrefix() [2/2]
CharArray javolution.xml.internal.stream.NamespacesImpl.getPrefix (CharSequence uri, int count) package
Definition at line 120 of file NamespacesImpl.java.
{
         for (int i = count; --i >= 0;) {
             CharArray prefix = _prefixes[i];
             CharArray namespace = _namespaces[i];
             if (namespace.equals(uri)) { // Find matching uri.
                 // Checks that the prefix has not been overwriten after being set.
                 boolean isPrefixOverwritten = false;
                 for (int j = i + 1; j < count; j++) {
                     if (prefix.equals(_prefixes[j])) {
                         isPrefixOverwritten = true;
                         break;
                     }
                 }
                 if (!isPrefixOverwritten)
                     return prefix;
             }
         }
         return null; // Not bound.
     }
References javolution.xml.internal.stream.NamespacesImpl._namespaces, javolution.xml.internal.stream.NamespacesImpl._prefixes, and javolution.text.CharArray.equals().
getPrefixes()
Iterator<CharArray> javolution.xml.internal.stream.NamespacesImpl.getPrefixes (CharSequence namespaceURI)
Returns all prefixes bound to a namespace URI in the current scope (including predefined prefixes).
Parameters
namespaceURI URI of Namespace to lookup
Returns
an Iterator over CharArray prefixes.
Exceptions
IllegalArgumentException if namespaceURI is null
Implements javolution.xml.stream.NamespaceContext.
Definition at line 141 of file NamespacesImpl.java.
{
         FastTable<CharArray> prefixes = new FastTable<CharArray>();
         for (int i = _namespacesCount[_nesting]; --i >= 0;) {
             if (_namespaces[i].equals(namespaceURI)) {
                 prefixes.add(_prefixes[i]);
             }
         }
         return prefixes.iterator();
     }
References javolution.xml.internal.stream.NamespacesImpl._namespaces, javolution.xml.internal.stream.NamespacesImpl._namespacesCount, javolution.xml.internal.stream.NamespacesImpl._nesting, javolution.xml.internal.stream.NamespacesImpl._prefixes, javolution.util.FastTable< E >.add(), and javolution.util.FastCollection< E >.iterator().
pop()
void javolution.xml.internal.stream.NamespacesImpl.pop () package
Definition at line 202 of file NamespacesImpl.java.
                {
         if (_namespacesCount[--_nesting] <= _defaultNamespaceIndex) {
             searchDefaultNamespace();
         }
     }
References javolution.xml.internal.stream.NamespacesImpl._defaultNamespaceIndex, javolution.xml.internal.stream.NamespacesImpl._namespacesCount, javolution.xml.internal.stream.NamespacesImpl._nesting, and javolution.xml.internal.stream.NamespacesImpl.searchDefaultNamespace().
Referenced by javolution.xml.internal.stream.XMLStreamWriterImpl.closeOpenTag(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeEndElement().
push()
void javolution.xml.internal.stream.NamespacesImpl.push () package
Definition at line 219 of file NamespacesImpl.java.
                 {
         _nesting++;
         if (_nesting >= _namespacesCount.length) {
             resizeNamespacesCount();
         }
         _namespacesCount[_nesting] = _namespacesCount[_nesting - 1];
     }
References javolution.xml.internal.stream.NamespacesImpl._namespacesCount, javolution.xml.internal.stream.NamespacesImpl._nesting, and javolution.xml.internal.stream.NamespacesImpl.resizeNamespacesCount().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.next(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeNewElement().
reset()
void javolution.xml.internal.stream.NamespacesImpl.reset ()
Definition at line 227 of file NamespacesImpl.java.
{
         _defaultNamespace = _nullNsURI;
         _defaultNamespaceIndex = 0;
         _namespacesCount[0] = NBR_PREDEFINED_NAMESPACES;
         _nesting = 0;
     }
References javolution.xml.internal.stream.NamespacesImpl._defaultNamespace, javolution.xml.internal.stream.NamespacesImpl._defaultNamespaceIndex, javolution.xml.internal.stream.NamespacesImpl._namespacesCount, javolution.xml.internal.stream.NamespacesImpl._nesting, javolution.xml.internal.stream.NamespacesImpl._nullNsURI, and javolution.xml.internal.stream.NamespacesImpl.NBR_PREDEFINED_NAMESPACES.
Referenced by javolution.xml.internal.stream.XMLStreamWriterImpl.reset(), and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
resizeNamespacesCount()
void javolution.xml.internal.stream.NamespacesImpl.resizeNamespacesCount () private
Definition at line 234 of file NamespacesImpl.java.
{
         final int oldLength = _namespacesCount.length;
         final int newLength = oldLength * 2;
         // Resizes namespaces counts.
         int[] tmp = new int[newLength];
         System.arraycopy(_namespacesCount, 0, tmp, 0, oldLength);
         _namespacesCount = tmp;
     }
References javolution.xml.internal.stream.NamespacesImpl._namespacesCount.
Referenced by javolution.xml.internal.stream.NamespacesImpl.push().
resizePrefixStack()
void javolution.xml.internal.stream.NamespacesImpl.resizePrefixStack () private
Definition at line 245 of file NamespacesImpl.java.
{
         final int oldLength = _prefixes.length;
         final int newLength = oldLength * 2;
         // Resizes prefixes.
         CharArray[] tmp0 = new CharArray[newLength];
         System.arraycopy(_prefixes, 0, tmp0, 0, oldLength);
         _prefixes = tmp0;
         // Resizes namespaces uri.
         CharArray[] tmp1 = new CharArray[newLength];
         System.arraycopy(_namespaces, 0, tmp1, 0, oldLength);
         _namespaces = tmp1;
         // Resizes prefix sets.
         boolean[] tmp2 = new boolean[newLength];
         System.arraycopy(_prefixesWritten, 0, tmp2, 0, oldLength);
         _prefixesWritten = tmp2;
         // Resizes temporary prefix (CharSequence to CharArray conversion).
         CharArray[] tmp3 = new CharArray[newLength];
         System.arraycopy(_prefixesTmp, 0, tmp3, 0, oldLength);
         _prefixesTmp = tmp3;
         // Resizes temporary namespaces (CharSequence to CharArray conversion).
         CharArray[] tmp4 = new CharArray[newLength];
         System.arraycopy(_namespacesTmp, 0, tmp4, 0, oldLength);
         _namespacesTmp = tmp4;
     }
References javolution.xml.internal.stream.NamespacesImpl._namespaces, javolution.xml.internal.stream.NamespacesImpl._namespacesTmp, javolution.xml.internal.stream.NamespacesImpl._prefixes, javolution.xml.internal.stream.NamespacesImpl._prefixesTmp, javolution.xml.internal.stream.NamespacesImpl._prefixesWritten, and javolution.text.CharArray.length().
Referenced by javolution.xml.internal.stream.NamespacesImpl.setPrefix().
searchDefaultNamespace()
void javolution.xml.internal.stream.NamespacesImpl.searchDefaultNamespace () private
Definition at line 208 of file NamespacesImpl.java.
{
         int count = _namespacesCount[_nesting];
         for (int i = count; --i >= 0;) {
             if (_prefixes[i].length() == 0) {
                 _defaultNamespaceIndex = i;
                 return;
             }
         }
         throw new Error("Cannot find default namespace");
     }
References javolution.xml.internal.stream.NamespacesImpl._defaultNamespaceIndex, javolution.xml.internal.stream.NamespacesImpl._namespacesCount, javolution.xml.internal.stream.NamespacesImpl._nesting, and javolution.xml.internal.stream.NamespacesImpl._prefixes.
Referenced by javolution.xml.internal.stream.NamespacesImpl.pop().
setPrefix() [1/2]
void javolution.xml.internal.stream.NamespacesImpl.setPrefix (CharArray prefix, CharArray uri) package
Definition at line 152 of file NamespacesImpl.java.
{
         int index = _namespacesCount[_nesting];
         _prefixes[index] = prefix;
         _namespaces[index] = uri;
         if (prefix.length() == 0) { // The default namespace is set.
             _defaultNamespaceIndex = index;
             _defaultNamespace = uri;
         }
         if (++_namespacesCount[_nesting] >= _prefixes.length)
             resizePrefixStack();
     }
References javolution.xml.internal.stream.NamespacesImpl._defaultNamespace, javolution.xml.internal.stream.NamespacesImpl._defaultNamespaceIndex, javolution.xml.internal.stream.NamespacesImpl._namespaces, javolution.xml.internal.stream.NamespacesImpl._namespacesCount, javolution.xml.internal.stream.NamespacesImpl._nesting, javolution.xml.internal.stream.NamespacesImpl._prefixes, javolution.text.CharArray.length(), and javolution.xml.internal.stream.NamespacesImpl.resizePrefixStack().
Referenced by javolution.xml.internal.stream.XMLStreamWriterImpl.getRepairedPrefix(), javolution.xml.internal.stream.XMLStreamReaderImpl.processAttribute(), javolution.xml.internal.stream.NamespacesImpl.setPrefix(), javolution.xml.internal.stream.XMLStreamWriterImpl.setPrefix(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeNamespace().
setPrefix() [2/2]
void javolution.xml.internal.stream.NamespacesImpl.setPrefix (final CharSequence prefix, CharSequence uri, boolean isWritten) package
Definition at line 166 of file NamespacesImpl.java.
{
         final int index = _namespacesCount[_nesting];
         _prefixesWritten[index] = isWritten;
         final int prefixLength = prefix.length();
         CharArray prefixTmp = _prefixesTmp[index];
         if ((prefixTmp == null) || (prefixTmp.array().length < prefixLength)) {
             _prefixesTmp[index] = new CharArray().setArray(
                     new char[prefixLength + 32], 0, 0);
             prefixTmp = _prefixesTmp[index];
         }
         for (int i = 0; i < prefixLength; i++) {
             prefixTmp.array()[i] = prefix.charAt(i);
         }
         prefixTmp.setArray(prefixTmp.array(), 0, prefixLength);
         final int uriLength = uri.length();
         CharArray namespaceTmp = _namespacesTmp[index];
         if ((namespaceTmp == null) || (namespaceTmp.array().length < uriLength)) {
             _namespacesTmp[index] = new CharArray().setArray(
                     new char[uriLength + 32], 0, 0);
             namespaceTmp = _namespacesTmp[index];
         }
         for (int i = 0; i < uriLength; i++) {
             namespaceTmp.array()[i] = uri.charAt(i);
         }
         namespaceTmp.setArray(namespaceTmp.array(), 0, uriLength);
         // Sets the prefix using CharArray instances.
         setPrefix(prefixTmp, namespaceTmp);
     }
References javolution.xml.internal.stream.NamespacesImpl._namespacesCount, javolution.xml.internal.stream.NamespacesImpl._namespacesTmp, javolution.xml.internal.stream.NamespacesImpl._nesting, javolution.xml.internal.stream.NamespacesImpl._prefixesTmp, javolution.xml.internal.stream.NamespacesImpl._prefixesWritten, javolution.text.CharArray.array(), javolution.text.CharArray.length(), javolution.text.CharArray.setArray(), and javolution.xml.internal.stream.NamespacesImpl.setPrefix().
Member Data Documentation
_defaultNamespace
CharArray javolution.xml.internal.stream.NamespacesImpl._defaultNamespace = _nullNsURI package
Holds the default namespace.
Definition at line 74 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.NamespacesImpl.getNamespaceURINullAllowed(), javolution.xml.internal.stream.NamespacesImpl.getPrefix(), javolution.xml.internal.stream.NamespacesImpl.reset(), javolution.xml.internal.stream.NamespacesImpl.setPrefix(), javolution.xml.internal.stream.XMLStreamWriterImpl.writeAttributeOrNamespace(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeNewElement().
_defaultNamespaceIndex
int javolution.xml.internal.stream.NamespacesImpl._defaultNamespaceIndex package
Holds the default namespace index.
Definition at line 79 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.NamespacesImpl.pop(), javolution.xml.internal.stream.NamespacesImpl.reset(), javolution.xml.internal.stream.NamespacesImpl.searchDefaultNamespace(), and javolution.xml.internal.stream.NamespacesImpl.setPrefix().
_defaultNsPrefix
final CharArray javolution.xml.internal.stream.NamespacesImpl._defaultNsPrefix = new CharArray("") package
Definition at line 35 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.NamespacesImpl.getPrefix(), javolution.xml.internal.stream.NamespacesImpl.NamespacesImpl(), javolution.xml.internal.stream.XMLStreamReaderImpl.processAttribute(), javolution.xml.internal.stream.XMLStreamWriterImpl.setDefaultNamespace(), javolution.xml.internal.stream.XMLStreamWriterImpl.writeDefaultNamespace(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeNamespace().
_namespaces
CharArray [] javolution.xml.internal.stream.NamespacesImpl._namespaces = new CharArray[_prefixes.length] package
Holds the currently mapped namespaces.
Definition at line 59 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI(), javolution.xml.internal.stream.NamespacesImpl.getNamespaceURINullAllowed(), javolution.xml.internal.stream.NamespacesImpl.getPrefix(), javolution.xml.internal.stream.NamespacesImpl.getPrefixes(), javolution.xml.internal.stream.NamespacesImpl.NamespacesImpl(), javolution.xml.internal.stream.NamespacesImpl.resizePrefixStack(), javolution.xml.internal.stream.NamespacesImpl.setPrefix(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeNamespaces().
_namespacesCount
int [] javolution.xml.internal.stream.NamespacesImpl._namespacesCount = new int[16] package
Holds the number of prefix/namespace association per nesting level.
Definition at line 69 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceCount(), javolution.xml.internal.stream.NamespacesImpl.getNamespaceURINullAllowed(), javolution.xml.internal.stream.NamespacesImpl.getPrefix(), javolution.xml.internal.stream.NamespacesImpl.getPrefixes(), javolution.xml.internal.stream.NamespacesImpl.NamespacesImpl(), javolution.xml.internal.stream.NamespacesImpl.pop(), javolution.xml.internal.stream.NamespacesImpl.push(), javolution.xml.internal.stream.NamespacesImpl.reset(), javolution.xml.internal.stream.NamespacesImpl.resizeNamespacesCount(), javolution.xml.internal.stream.NamespacesImpl.searchDefaultNamespace(), javolution.xml.internal.stream.NamespacesImpl.setPrefix(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeNamespaces().
_namespacesTmp
CharArray [] javolution.xml.internal.stream.NamespacesImpl._namespacesTmp = new CharArray[_prefixes.length] private
Definition at line 200 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.NamespacesImpl.resizePrefixStack(), and javolution.xml.internal.stream.NamespacesImpl.setPrefix().
_nesting
int javolution.xml.internal.stream.NamespacesImpl._nesting = 0 private
Holds the current nesting level.
Definition at line 49 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.NamespacesImpl.getNamespaceURINullAllowed(), javolution.xml.internal.stream.NamespacesImpl.getPrefix(), javolution.xml.internal.stream.NamespacesImpl.getPrefixes(), javolution.xml.internal.stream.NamespacesImpl.pop(), javolution.xml.internal.stream.NamespacesImpl.push(), javolution.xml.internal.stream.NamespacesImpl.reset(), javolution.xml.internal.stream.NamespacesImpl.searchDefaultNamespace(), and javolution.xml.internal.stream.NamespacesImpl.setPrefix().
_nullNsURI
final CharArray javolution.xml.internal.stream.NamespacesImpl._nullNsURI = new CharArray("") package
Holds useful CharArray instances (non-static to avoid potential inter-thread corruption).
Definition at line 33 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.NamespacesImpl.NamespacesImpl(), javolution.xml.internal.stream.NamespacesImpl.reset(), javolution.xml.internal.stream.XMLStreamWriterImpl.setPrefix(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeNamespace().
_prefixes
CharArray [] javolution.xml.internal.stream.NamespacesImpl._prefixes = new CharArray[16] package
Holds the currently mapped prefixes.
Definition at line 54 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespacePrefix(), javolution.xml.internal.stream.NamespacesImpl.getNamespaceURINullAllowed(), javolution.xml.internal.stream.NamespacesImpl.getPrefix(), javolution.xml.internal.stream.NamespacesImpl.getPrefixes(), javolution.xml.internal.stream.NamespacesImpl.NamespacesImpl(), javolution.xml.internal.stream.NamespacesImpl.resizePrefixStack(), javolution.xml.internal.stream.NamespacesImpl.searchDefaultNamespace(), javolution.xml.internal.stream.NamespacesImpl.setPrefix(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeNamespaces().
_prefixesTmp
CharArray [] javolution.xml.internal.stream.NamespacesImpl._prefixesTmp = new CharArray[_prefixes.length] private
Definition at line 198 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.NamespacesImpl.resizePrefixStack(), and javolution.xml.internal.stream.NamespacesImpl.setPrefix().
_prefixesWritten
boolean [] javolution.xml.internal.stream.NamespacesImpl._prefixesWritten = new boolean[_prefixes.length] package
Indicates if the prefix has to been written (when writing).
Definition at line 64 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.NamespacesImpl.resizePrefixStack(), javolution.xml.internal.stream.NamespacesImpl.setPrefix(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeNamespaces().
_xml
final CharArray javolution.xml.internal.stream.NamespacesImpl._xml = new CharArray("xml") package
Definition at line 37 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.NamespacesImpl.NamespacesImpl().
_xmlns
final CharArray javolution.xml.internal.stream.NamespacesImpl._xmlns = new CharArray("xmlns") package
Definition at line 42 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.NamespacesImpl.NamespacesImpl(), javolution.xml.internal.stream.XMLStreamWriterImpl.writeNamespace(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeNamespaces().
_xmlnsURI
final CharArray javolution.xml.internal.stream.NamespacesImpl._xmlnsURI = new CharArray("http://www.w3.org/2000/xmlns/") package
Definition at line 44 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.NamespacesImpl.NamespacesImpl(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeNamespaces().
_xmlURI
final CharArray javolution.xml.internal.stream.NamespacesImpl._xmlURI package
Initial value:
= new CharArray(
            "http://www.w3.org/XML/1998/namespace")
Definition at line 39 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.NamespacesImpl.NamespacesImpl().
NBR_PREDEFINED_NAMESPACES
final int javolution.xml.internal.stream.NamespacesImpl.NBR_PREDEFINED_NAMESPACES = 3 static package
Holds the number of predefined namespaces.
Definition at line 27 of file NamespacesImpl.java.
Referenced by javolution.xml.internal.stream.NamespacesImpl.NamespacesImpl(), javolution.xml.internal.stream.NamespacesImpl.reset(), and javolution.xml.internal.stream.XMLStreamWriterImpl.writeNamespaces().
The documentation for this class was generated from the following file:
NamespacesImpl.java