Javolution 6.0.0 java: javolution.util.internal.map.sorted.SubSortedMapImpl< K, V > Class Template Reference
javolution.util.internal.map.sorted.SubSortedMapImpl< K, V > Class Template Reference
Classes
class IteratorImpl
Public Member Functions
SubSortedMapImpl (SortedMapService< K, V > target, K from, K to)
boolean containsKey (Object key)
K firstKey ()
V get (Object key)
Iterator< Entry< K, V > > iterator ()
Equality<? super K > keyComparator ()
K lastKey ()
V put (K key, V value)
V remove (Object key)
Equality<? super V > valueComparator ()
Comparator<? super K > comparator ()
SortedSetService< Map.Entry< K, V > > entrySet ()
SortedMapService< K, V > headMap (K toKey)
SortedSetService< K > keySet ()
SortedMapService< K, V > subMap (K fromKey, K toKey)
SortedMapService< K, V > tailMap (K fromKey)
SortedMapService< K, V > threadSafe ()
void clear ()
MapView< K, V > clone ()
boolean containsValue (Object value)
boolean isEmpty ()
void perform (Consumer< MapService< K, V >> action, MapService< K, V > view)
void perform (Consumer< T > action, T part)
void putAll (Map<? extends K, ? extends V > m)
V putIfAbsent (K key, V value)
boolean remove (Object key, Object value)
V replace (K key, V value)
boolean replace (K key, V oldValue, V newValue)
int size ()
MapService< K, V >[] split (int n)
void update (Consumer< MapService< K, V >> action, MapService< K, V > view)
void update (Consumer< T > action, T part)
CollectionService< V > values ()
Protected Member Functions
SortedMapService< K, V > target ()
Private Attributes
final K from
final K to
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
A view over a portion of a sorted map.
Definition at line 20 of file SubSortedMapImpl.java.
Constructor & Destructor Documentation
SubSortedMapImpl()
javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.SubSortedMapImpl (SortedMapService< K, V > target, K from, K to)
Definition at line 62 of file SubSortedMapImpl.java.
{
         super(target);
         if ((from != null) && (to != null)
                 && (keyComparator().compare(from, to) > 0)) throw new IllegalArgumentException(
                 "from: " + from + ", to: " + to); // As per SortedSet contract.
         this.from = from;
         this.to = to;
     }
References javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.from, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.keyComparator(), javolution.util.internal.map.sorted.SortedMapView< K, V >.target(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.to.
Member Function Documentation
clear()
void javolution.util.internal.map.MapView< K, V >.clear () inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.map.UnmodifiableMapImpl< K, V >, and javolution.util.internal.map.FastMapImpl< K, V >.
Definition at line 223 of file MapView.java.
{
         Iterator<Entry<K, V>> it = iterator();
         while (it.hasNext()) {
             it.remove();
         }
     }
References javolution.util.internal.map.MapView< K, V >.iterator().
clone()
MapView<K, V> javolution.util.internal.map.MapView< K, V >.clone () inherited
Returns a copy of this map; updates of the copy should not impact the original.
Implements javolution.util.service.MapService< K, V >.
Reimplemented in javolution.util.internal.map.AtomicMapImpl< K, V >, and javolution.util.internal.map.FastMapImpl< K, V >.
Definition at line 232 of file MapView.java.
{
         try {
             MapView<K, V> copy = (MapView<K, V>) super.clone();
             if (target != null) { // Not a root class.
                 copy.target = target.clone();
             }
             return copy;
         } catch (CloneNotSupportedException e) {
             throw new Error("Should not happen since target is cloneable");
         }
     }
References javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.split().
comparator()
Comparator<? super K> javolution.util.internal.map.sorted.SortedMapView< K, V >.comparator () inherited
Definition at line 112 of file SortedMapView.java.
{
         return keyComparator();
     }
References javolution.util.internal.map.MapView< K, V >.keyComparator().
containsKey()
boolean javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.containsKey (Object key)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 73 of file SubSortedMapImpl.java.
{
         Equality<? super K> cmp = keyComparator();
         if ((from != null) && (cmp.compare((K) key, from) < 0)) return false;
         if ((to != null) && (cmp.compare((K) key, to) >= 0)) return false;
         return target().containsKey(key);
     }
References javolution.util.function.Equality< T >.compare(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.from, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.keyComparator(), javolution.util.internal.map.sorted.SortedMapView< K, V >.target(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.to.
containsValue()
boolean javolution.util.internal.map.MapView< K, V >.containsValue (Object value) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 248 of file MapView.java.
{
         return values().contains(value);
     }
References javolution.util.internal.map.MapView< K, V >.values().
entrySet()
SortedSetService<Map.Entry<K, V> > javolution.util.internal.map.sorted.SortedMapView< K, V >.entrySet () inherited
Returns a set view over the entries of this map. The set support adding/removing entries. Two entries are considered equals if they have the same key regardless of their values.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 117 of file SortedMapView.java.
{
         return new EntrySortedSet();
     }
Referenced by javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >.entrySet(), javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.entrySet(), and javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.entrySet().
firstKey()
K javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.firstKey ()
Reimplemented from javolution.util.internal.map.sorted.SortedMapView< K, V >.
Definition at line 81 of file SubSortedMapImpl.java.
{
         if (from == null) return target().firstKey();
         Iterator<Entry<K, V>> it = iterator();
         if (!it.hasNext()) throw new NoSuchElementException();
         return it.next().getKey();
     }
References javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.from, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.iterator(), and javolution.util.internal.map.sorted.SortedMapView< K, V >.target().
get()
V javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.get (Object key)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 90 of file SubSortedMapImpl.java.
{
         Equality<? super K> cmp = keyComparator();
         if ((from != null) && (cmp.compare((K) key, from) < 0)) return null;
         if ((to != null) && (cmp.compare((K) key, to) >= 0)) return null;
         return target().get(key);
     }
References javolution.util.function.Equality< T >.compare(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.from, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.keyComparator(), javolution.util.internal.map.sorted.SortedMapView< K, V >.target(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.to.
headMap()
SortedMapService<K, V> javolution.util.internal.map.sorted.SortedMapView< K, V >.headMap (K toKey) inherited
Implements javolution.util.service.SortedMapService< K, V >.
Definition at line 125 of file SortedMapView.java.
{
         return new SubSortedMapImpl<K,V>(this, firstKey(), toKey);
     }
References javolution.util.internal.map.sorted.SortedMapView< K, V >.firstKey().
isEmpty()
boolean javolution.util.internal.map.MapView< K, V >.isEmpty () inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 261 of file MapView.java.
{
         return iterator().hasNext();
     }
References javolution.util.internal.map.MapView< K, V >.iterator().
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.isEmpty().
iterator()
Iterator<Entry<K, V> > javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.iterator ()
Returns an iterator over this map entries.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 98 of file SubSortedMapImpl.java.
{
         return new IteratorImpl();
     }
Referenced by javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.firstKey(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.lastKey().
keyComparator()
Equality<? super K> javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.keyComparator ()
Returns the key comparator used for key equality or order if the map is sorted.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 103 of file SubSortedMapImpl.java.
{
         return target().keyComparator();
     }
References javolution.util.internal.map.sorted.SortedMapView< K, V >.target().
Referenced by javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.containsKey(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.get(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.put(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.remove(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.SubSortedMapImpl().
keySet()
SortedSetService<K> javolution.util.internal.map.sorted.SortedMapView< K, V >.keySet () inherited
Returns a set view over the key of this map, the set support adding new key for which the value is automatically
null
.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 130 of file SortedMapView.java.
{
         return new KeySortedSet();
     }
Referenced by javolution.util.FastSortedSet< E >.FastSortedSet(), javolution.util.internal.map.sorted.UnmodifiableSortedMapImpl< K, V >.keySet(), javolution.util.internal.map.sorted.AtomicSortedMapImpl< K, V >.keySet(), and javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.keySet().
lastKey()
K javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.lastKey ()
Reimplemented from javolution.util.internal.map.sorted.SortedMapView< K, V >.
Definition at line 108 of file SubSortedMapImpl.java.
{
         if (to == null) return target().lastKey();
         Iterator<Entry<K, V>> it = iterator();
         if (!it.hasNext()) throw new NoSuchElementException();
         Entry<K, V> last = it.next();
         while (it.hasNext()) {
             last = it.next();
         }
         return last.getKey();
     }
References javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.iterator(), javolution.util.internal.map.sorted.SortedMapView< K, V >.target(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.to.
perform() [1/2]
void javolution.util.internal.map.MapView< K, V >.perform (Consumer< MapService< K, V >> action, MapService< K, V > view) inherited
Reimplemented in javolution.util.internal.map.ParallelMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Definition at line 277 of file MapView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
References javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.perform().
perform() [2/2]
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
put()
V javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.put (K key, V value)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 120 of file SubSortedMapImpl.java.
{
         Equality<? super K> cmp = keyComparator();
         if ((from != null) && (cmp.compare((K) key, from) < 0)) throw new IllegalArgumentException(
                 "Key: " + key + " outside of this sub-map bounds");
         if ((to != null) && (cmp.compare((K) key, to) >= 0)) throw new IllegalArgumentException(
                 "Key: " + key + " outside of this sub-map bounds");
         return target().put(key, value);
     }
References javolution.util.function.Equality< T >.compare(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.from, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.keyComparator(), javolution.util.internal.map.sorted.SortedMapView< K, V >.target(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.to.
putAll()
void javolution.util.internal.map.MapView< K, V >.putAll (Map<? extends K, ? extends V > m) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 290 of file MapView.java.
{
         Iterator<?> it = m.entrySet().iterator();
         while (it.hasNext()) {
             Entry<K, V> e = (Entry<K, V>) it.next();
             put(e.getKey(), e.getValue());
         }
     }
References javolution.util.internal.map.MapView< K, V >.put().
Referenced by javolution.util.internal.map.FastMapImpl< K, V >.clone().
putIfAbsent()
V javolution.util.internal.map.MapView< K, V >.putIfAbsent (K key, V value) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 299 of file MapView.java.
{
         if (!containsKey(key)) return put(key, value);
         else return get(key);
     }
References javolution.util.internal.map.MapView< K, V >.containsKey(), and javolution.util.internal.map.MapView< K, V >.put().
remove() [1/2]
V javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.remove (Object key)
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 131 of file SubSortedMapImpl.java.
{
         Equality<? super K> cmp = keyComparator();
         if ((from != null) && (cmp.compare((K) key, from) < 0)) return null;
         if ((to != null) && (cmp.compare((K) key, to) >= 0)) return null;
         return target().remove(key);
     }
References javolution.util.function.Equality< T >.compare(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.from, javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.keyComparator(), javolution.util.internal.map.sorted.SortedMapView< K, V >.target(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.to.
remove() [2/2]
boolean javolution.util.internal.map.MapView< K, V >.remove (Object key, Object value) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 308 of file MapView.java.
{
         if (containsKey(key) && get(key).equals(value)) {
             remove(key);
             return true;
         } else return false;
     }
References javolution.util.internal.map.MapView< K, V >.containsKey().
replace() [1/2]
boolean javolution.util.internal.map.MapView< K, V >.replace (K key, V oldValue, V newValue) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 323 of file MapView.java.
{
         if (containsKey(key) && get(key).equals(oldValue)) {
             put(key, newValue);
             return true;
         } else return false;
     }
References javolution.util.internal.map.MapView< K, V >.containsKey(), and javolution.util.internal.map.MapView< K, V >.put().
replace() [2/2]
V javolution.util.internal.map.MapView< K, V >.replace (K key, V value) inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 316 of file MapView.java.
{
         if (containsKey(key)) {
             return put(key, value);
         } else return null;
     }
References javolution.util.internal.map.MapView< K, V >.containsKey(), and javolution.util.internal.map.MapView< K, V >.put().
size()
int javolution.util.internal.map.MapView< K, V >.size () inherited
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 331 of file MapView.java.
                       {
         int count = 0;
         Iterator<Entry<K, V>> it = iterator();
         while (it.hasNext()) {
             count++;
             it.next();
         }
         return count;
     }
References javolution.util.internal.map.MapView< K, V >.iterator().
Referenced by javolution.util.internal.map.sorted.FastSortedMapImpl< K, V >.put(), and javolution.util.internal.map.MapView< K, V >.EntrySet.size().
split()
MapService<K, V> [] javolution.util.internal.map.MapView< K, V >.split (int n) inherited
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Implements javolution.util.function.Splittable< T >.
Reimplemented in javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, and javolution.util.internal.map.AtomicMapImpl< K, V >.
Definition at line 343 of file MapView.java.
{
         if (target == null) return new MapService[] { this }; // No split.
         MapService<K, V>[] subTargets = target.split(n);
         MapService<K, V>[] result = new MapService[subTargets.length];
         for (int i = 0; i < subTargets.length; i++) {
             MapView<K, V> copy = this.clone();
             copy.target = subTargets[i];
             result[i] = copy;
         }
         return result;
     }
References javolution.util.internal.map.MapView< K, V >.clone(), and javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.split().
subMap()
SortedMapService<K, V> javolution.util.internal.map.sorted.SortedMapView< K, V >.subMap (K fromKey, K toKey) inherited
Implements javolution.util.service.SortedMapService< K, V >.
Definition at line 138 of file SortedMapView.java.
{
         return new SubSortedMapImpl<K,V>(this, fromKey, toKey);
     }
tailMap()
SortedMapService<K, V> javolution.util.internal.map.sorted.SortedMapView< K, V >.tailMap (K fromKey) inherited
Implements javolution.util.service.SortedMapService< K, V >.
Definition at line 143 of file SortedMapView.java.
{
         return new SubSortedMapImpl<K,V>(this, fromKey, lastKey());
     }
References javolution.util.internal.map.sorted.SortedMapView< K, V >.lastKey().
target()
SortedMapService<K,V> javolution.util.internal.map.sorted.SortedMapView< K, V >.target () protected inherited
Returns the actual target
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 154 of file SortedMapView.java.
{
         return (SortedMapService<K,V>) super.target();
     }
Referenced by javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.containsKey(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.firstKey(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.get(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.keyComparator(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.lastKey(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.put(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.remove(), javolution.util.internal.map.sorted.SortedMapView< K, V >.SortedMapView(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.SubSortedMapImpl(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.valueComparator().
threadSafe()
SortedMapService<K,V> javolution.util.internal.map.sorted.SortedMapView< K, V >.threadSafe () inherited
Returns a thread-safe version of this service (used during parallel updates).
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 148 of file SortedMapView.java.
{
         return new SharedSortedMapImpl<K,V>(this);
     }
update() [1/2]
void javolution.util.internal.map.MapView< K, V >.update (Consumer< MapService< K, V >> action, MapService< K, V > view) inherited
Reimplemented in javolution.util.internal.map.ParallelMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, and javolution.util.internal.map.SequentialMapImpl< K, V >.
Definition at line 361 of file MapView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.update(action, view);
         }
     }
References javolution.util.internal.map.MapView< K, V >.target.
Referenced by javolution.util.internal.map.MapView< K, V >.EntrySet.update().
update() [2/2]
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
valueComparator()
Equality<? super V> javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.valueComparator ()
Returns the value comparator used for value equality.
Reimplemented from javolution.util.internal.map.MapView< K, V >.
Definition at line 139 of file SubSortedMapImpl.java.
{
         return target().valueComparator();
     }
References javolution.util.internal.map.sorted.SortedMapView< K, V >.target().
values()
CollectionService<V> javolution.util.internal.map.MapView< K, V >.values () inherited
Returns a collection view over the values of this map, the collection support value/entry removal but not adding new values.
Implements javolution.util.service.MapService< K, V >.
Definition at line 373 of file MapView.java.
{
         return new Values();
     }
Referenced by javolution.util.internal.map.MapView< K, V >.containsValue().
Member Data Documentation
from
final K javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.from private
Definition at line 59 of file SubSortedMapImpl.java.
Referenced by javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.containsKey(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.firstKey(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.get(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.hasNext(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.put(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.remove(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.SubSortedMapImpl().
serialVersionUID
final long javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.serialVersionUID = 0x600L static private
Definition at line 57 of file SubSortedMapImpl.java.
to
final K javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.to private
Definition at line 60 of file SubSortedMapImpl.java.
Referenced by javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.containsKey(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.get(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.IteratorImpl.hasNext(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.lastKey(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.put(), javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.remove(), and javolution.util.internal.map.sorted.SubSortedMapImpl< K, V >.SubSortedMapImpl().
The documentation for this class was generated from the following file:
SubSortedMapImpl.java