Javolution 6.0.0 java: javolution.osgi.internal.LogServiceImpl Class Reference
javolution.osgi.internal.LogServiceImpl Class Reference
Classes
class LogEvent
Public Member Functions
LogServiceImpl ()
void log (int level, String message)
void log (int level, String message, Throwable exception)
void log (ServiceReference sr, int level, String message)
void log (ServiceReference sr, int level, String message, Throwable exception)
void run ()
Private Attributes
final FastTable< LogEvent > eventQueue = new FastTable<LogEvent>()
Detailed Description
Holds the default implementation of LogService to be used when running outside OSGi or when the Javolution bundle is not started.
Definition at line 20 of file LogServiceImpl.java.
Constructor & Destructor Documentation
LogServiceImpl()
javolution.osgi.internal.LogServiceImpl.LogServiceImpl ()
Definition at line 30 of file LogServiceImpl.java.
{
         super("Logging-Thread");
         setDaemon(true);
         this.start();
         Thread hook = new Thread(new Runnable() {
             @Override
             public void run() { // Maintains the VM alive until the event queue is flushed
                 synchronized (eventQueue) {
                     try {
                         while (!eventQueue.isEmpty())
                             eventQueue.wait();
                     } catch (InterruptedException e) {}
                 }
             }
         });
         Runtime.getRuntime().addShutdownHook(hook);
     }
References javolution.osgi.internal.LogServiceImpl.eventQueue, and javolution.osgi.internal.LogServiceImpl.run().
Member Function Documentation
log() [1/4]
void javolution.osgi.internal.LogServiceImpl.log (int level, String message)
Definition at line 49 of file LogServiceImpl.java.
{
         log(level, message, null);
     }
log() [2/4]
void javolution.osgi.internal.LogServiceImpl.log (int level, String message, Throwable exception)
Definition at line 54 of file LogServiceImpl.java.
{
         LogEvent event = new LogEvent();
         event.level = level;
         event.message = message;
         event.exception = exception;
         synchronized (eventQueue) {
             eventQueue.addFirst(event);
             eventQueue.notify();
         }
     }
References javolution.osgi.internal.LogServiceImpl.eventQueue.
log() [3/4]
void javolution.osgi.internal.LogServiceImpl.log (ServiceReference sr, int level, String message)
Definition at line 67 of file LogServiceImpl.java.
{
         throw new UnsupportedOperationException();
     }
log() [4/4]
void javolution.osgi.internal.LogServiceImpl.log (ServiceReference sr, int level, String message, Throwable exception)
Definition at line 73 of file LogServiceImpl.java.
{
         throw new UnsupportedOperationException();
     }
run()
void javolution.osgi.internal.LogServiceImpl.run ()
Definition at line 79 of file LogServiceImpl.java.
                       {
         while (true) {
             try {
                 LogEvent event;
                 synchronized (eventQueue) {
                     while (eventQueue.isEmpty())
                         eventQueue.wait();
                     event = eventQueue.pollLast();
                     eventQueue.notify();
                 }
                 switch (event.level) {
                     case LogService.LOG_DEBUG:
                         System.out.println("[DEBUG] " + event.message);
                         break;
                     case LogService.LOG_INFO:
                         System.out.println("[INFO] " + event.message);
                         break;
                     case LogService.LOG_WARNING:
                         System.out.println("[WARNING] " + event.message);
                         break;
                     case LogService.LOG_ERROR:
                         System.out.println("[ERROR] " + event.message);
                         break;
                     default:
                         System.out.println("[UNKNOWN] " + event.message);
                         break;
                 }
                 if (event.exception != null) {
                     event.exception.printStackTrace(System.out);
                 }
             } catch (InterruptedException error) {
                 error.printStackTrace(System.err);
             }
         }
     }
References javolution.osgi.internal.LogServiceImpl.eventQueue, javolution.osgi.internal.LogServiceImpl.LogEvent.exception, javolution.osgi.internal.LogServiceImpl.LogEvent.level, and javolution.osgi.internal.LogServiceImpl.LogEvent.message.
Referenced by javolution.osgi.internal.LogServiceImpl.LogServiceImpl().
Member Data Documentation
eventQueue
final FastTable<LogEvent> javolution.osgi.internal.LogServiceImpl.eventQueue = new FastTable<LogEvent>() private
Definition at line 28 of file LogServiceImpl.java.
Referenced by javolution.osgi.internal.LogServiceImpl.log(), javolution.osgi.internal.LogServiceImpl.LogServiceImpl(), and javolution.osgi.internal.LogServiceImpl.run().
The documentation for this class was generated from the following file:
LogServiceImpl.java