Javolution 6.0.0 java: javolution.util.internal.collection.ReadWriteLockImpl.ReadLock Class Reference
javolution.util.internal.collection.ReadWriteLockImpl.ReadLock Class Reference
Public Member Functions
void lock ()
void lockInterruptibly () throws InterruptedException
Condition newCondition ()
boolean tryLock ()
boolean tryLock (long time, TimeUnit unit) throws InterruptedException
void unlock ()
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
Read-Lock Implementation.
Definition at line 26 of file ReadWriteLockImpl.java.
Member Function Documentation
lock()
void javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lock ()
Definition at line 30 of file ReadWriteLockImpl.java.
{
             try {
                 lockInterruptibly();
             } catch (java.lang.InterruptedException e) {}
         }
References javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lockInterruptibly().
Referenced by javolution.util.internal.collection.SharedCollectionImpl< E >.clone(), javolution.util.internal.collection.SharedCollectionImpl< E >.contains(), javolution.util.internal.collection.SharedCollectionImpl< E >.containsAll(), javolution.util.internal.map.SharedMapImpl< K, V >.containsKey(), javolution.util.internal.map.SharedMapImpl< K, V >.containsValue(), javolution.util.internal.collection.SharedCollectionImpl< E >.equals(), javolution.util.internal.set.sorted.SharedSortedSetImpl< E >.first(), javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.firstKey(), javolution.util.internal.table.SharedTableImpl< E >.get(), javolution.util.internal.map.SharedMapImpl< K, V >.get(), javolution.util.internal.table.SharedTableImpl< E >.getFirst(), javolution.util.internal.table.SharedTableImpl< E >.getLast(), javolution.util.internal.collection.SharedCollectionImpl< E >.hashCode(), javolution.util.internal.table.SharedTableImpl< E >.indexOf(), javolution.util.internal.map.SharedMapImpl< K, V >.isEmpty(), javolution.util.internal.collection.SharedCollectionImpl< E >.isEmpty(), javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.IteratorImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.IteratorImpl(), javolution.util.internal.set.sorted.SharedSortedSetImpl< E >.last(), javolution.util.internal.table.SharedTableImpl< E >.lastIndexOf(), javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.lastKey(), javolution.util.internal.table.SharedTableImpl< E >.peekFirst(), javolution.util.internal.table.SharedTableImpl< E >.peekLast(), javolution.util.internal.collection.SharedCollectionImpl< E >.perform(), javolution.util.internal.table.sorted.SharedSortedTableImpl< E >.positionOf(), javolution.util.internal.map.SharedMapImpl< K, V >.size(), javolution.util.internal.collection.SharedCollectionImpl< E >.size(), javolution.util.internal.map.SharedMapImpl< K, V >.split(), javolution.util.internal.collection.SharedCollectionImpl< E >.split(), and javolution.util.internal.collection.SharedCollectionImpl< E >.toArray().
lockInterruptibly()
void javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lockInterruptibly () throws InterruptedException
Definition at line 37 of file ReadWriteLockImpl.java.
{
             synchronized (ReadWriteLockImpl.this) {
                 if (writerThread == Thread.currentThread()) return; // Current thread has the writer lock.
                 while ((writerThread != null) || (waitingWriters != 0)) {
                     ReadWriteLockImpl.this.wait();
                 }
                 givenLocks++;
             }
         }
References javolution.util.internal.collection.ReadWriteLockImpl.givenLocks, javolution.util.internal.collection.ReadWriteLockImpl.waitingWriters, and javolution.util.internal.collection.ReadWriteLockImpl.writerThread.
Referenced by javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.lock().
newCondition()
Condition javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.newCondition ()
Definition at line 48 of file ReadWriteLockImpl.java.
{
             throw new UnsupportedOperationException();
         }
tryLock() [1/2]
boolean javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.tryLock ()
Definition at line 53 of file ReadWriteLockImpl.java.
{
             throw new UnsupportedOperationException();
         }
tryLock() [2/2]
boolean javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.tryLock (long time, TimeUnit unit) throws InterruptedException
Definition at line 58 of file ReadWriteLockImpl.java.
{
             throw new UnsupportedOperationException();
         }
unlock()
void javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.unlock ()
Definition at line 64 of file ReadWriteLockImpl.java.
{
             synchronized (ReadWriteLockImpl.this) {
                 if (writerThread == Thread.currentThread()) return; // Itself is the writing thread.
                 assert (givenLocks > 0);
                 givenLocks--;
                 ReadWriteLockImpl.this.notifyAll();
             }
         }
References javolution.util.internal.collection.ReadWriteLockImpl.givenLocks, and javolution.util.internal.collection.ReadWriteLockImpl.writerThread.
Referenced by javolution.util.internal.collection.SharedCollectionImpl< E >.clone(), javolution.util.internal.collection.SharedCollectionImpl< E >.contains(), javolution.util.internal.collection.SharedCollectionImpl< E >.containsAll(), javolution.util.internal.map.SharedMapImpl< K, V >.containsKey(), javolution.util.internal.map.SharedMapImpl< K, V >.containsValue(), javolution.util.internal.collection.SharedCollectionImpl< E >.equals(), javolution.util.internal.set.sorted.SharedSortedSetImpl< E >.first(), javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.firstKey(), javolution.util.internal.table.SharedTableImpl< E >.get(), javolution.util.internal.map.SharedMapImpl< K, V >.get(), javolution.util.internal.table.SharedTableImpl< E >.getFirst(), javolution.util.internal.table.SharedTableImpl< E >.getLast(), javolution.util.internal.collection.SharedCollectionImpl< E >.hashCode(), javolution.util.internal.table.SharedTableImpl< E >.indexOf(), javolution.util.internal.map.SharedMapImpl< K, V >.isEmpty(), javolution.util.internal.collection.SharedCollectionImpl< E >.isEmpty(), javolution.util.internal.collection.SharedCollectionImpl< E >.IteratorImpl.IteratorImpl(), javolution.util.internal.map.SharedMapImpl< K, V >.IteratorImpl.IteratorImpl(), javolution.util.internal.set.sorted.SharedSortedSetImpl< E >.last(), javolution.util.internal.table.SharedTableImpl< E >.lastIndexOf(), javolution.util.internal.map.sorted.SharedSortedMapImpl< K, V >.lastKey(), javolution.util.internal.table.SharedTableImpl< E >.peekFirst(), javolution.util.internal.table.SharedTableImpl< E >.peekLast(), javolution.util.internal.collection.SharedCollectionImpl< E >.perform(), javolution.util.internal.table.sorted.SharedSortedTableImpl< E >.positionOf(), javolution.util.internal.map.SharedMapImpl< K, V >.size(), javolution.util.internal.collection.SharedCollectionImpl< E >.size(), javolution.util.internal.map.SharedMapImpl< K, V >.split(), javolution.util.internal.collection.SharedCollectionImpl< E >.split(), and javolution.util.internal.collection.SharedCollectionImpl< E >.toArray().
Member Data Documentation
serialVersionUID
final long javolution.util.internal.collection.ReadWriteLockImpl.ReadLock.serialVersionUID = 0x600L static private
Definition at line 27 of file ReadWriteLockImpl.java.
The documentation for this class was generated from the following file:
ReadWriteLockImpl.java