Javolution 6.0.0 java: javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl Class Reference
javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl Class Reference
Public Member Functions
int getLineNumber ()
int getColumnNumber ()
int getCharacterOffset ()
String getPublicId ()
String getSystemId ()
String toString ()
void reset ()
Package Attributes
int _column
int _line
int _charactersRead
Detailed Description
This inner class represents the parser location.
Definition at line 1074 of file XMLStreamReaderImpl.java.
Member Function Documentation
getCharacterOffset()
int javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.getCharacterOffset ()
Return the byte or character offset into the input source this location is pointing to. If the input source is a file or a byte stream then this is the byte offset into that stream, but if the input source is a character media then the offset is the character offset. Returns -1 if there is no offset available.
Returns
the current offset
Implements javolution.xml.stream.Location.
Definition at line 1090 of file XMLStreamReaderImpl.java.
{
             return _charactersRead + _readIndex;
         }
References javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl._charactersRead, and javolution.xml.internal.stream.XMLStreamReaderImpl._readIndex.
getColumnNumber()
int javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.getColumnNumber ()
Return the column number where the current event ends, returns -1 if none is available.
Returns
the current column number
Implements javolution.xml.stream.Location.
Definition at line 1086 of file XMLStreamReaderImpl.java.
{
             return _column + _readIndex;
         }
References javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl._column, and javolution.xml.internal.stream.XMLStreamReaderImpl._readIndex.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.toString().
getLineNumber()
int javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.getLineNumber ()
Return the line number where the current event ends, returns -1 if none is available.
Returns
the current line number
Implements javolution.xml.stream.Location.
Definition at line 1082 of file XMLStreamReaderImpl.java.
{
             return _line + 1;
         }
References javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl._line.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.toString().
getPublicId()
String javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.getPublicId ()
Returns the public ID of the XML
Returns
the public ID, or null if not available
Implements javolution.xml.stream.Location.
Definition at line 1094 of file XMLStreamReaderImpl.java.
{
             return null; // Not available.
         }
getSystemId()
String javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.getSystemId ()
Returns the system ID of the XML
Returns
the system ID, or null if not available
Implements javolution.xml.stream.Location.
Definition at line 1098 of file XMLStreamReaderImpl.java.
{
             return null; // Not available.
         }
reset()
void javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.reset ()
Definition at line 1106 of file XMLStreamReaderImpl.java.
{
             _line = 0;
             _column = 0;
             _charactersRead = 0;
         }
References javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl._charactersRead, javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl._column, and javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl._line.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
toString()
String javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.toString ()
Definition at line 1102 of file XMLStreamReaderImpl.java.
{
             return "Line " + getLineNumber() + ", Column " + getColumnNumber();
         }
References javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.getColumnNumber(), and javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.getLineNumber().
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.toString().
Member Data Documentation
_charactersRead
int javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl._charactersRead package
Definition at line 1080 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.getCharacterOffset(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), and javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.reset().
_column
int javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl._column package
Definition at line 1076 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.getColumnNumber(), javolution.xml.internal.stream.XMLStreamReaderImpl.handleEndOfLine(), javolution.xml.internal.stream.XMLStreamReaderImpl.reloadBuffer(), and javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.reset().
_line
int javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl._line package
Definition at line 1078 of file XMLStreamReaderImpl.java.
Referenced by javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.getLineNumber(), javolution.xml.internal.stream.XMLStreamReaderImpl.handleEndOfLine(), and javolution.xml.internal.stream.XMLStreamReaderImpl.LocationImpl.reset().
The documentation for this class was generated from the following file:
XMLStreamReaderImpl.java