Javolution 6.0.0 java: javolution.util.internal.table.AtomicTableImpl< E > Class Template Reference
javolution.util.internal.table.AtomicTableImpl< E > Class Template Reference
Public Member Functions
AtomicTableImpl (TableService< E > target)
synchronized void add (int index, E element)
synchronized boolean addAll (int index, Collection<? extends E > c)
synchronized void addFirst (E element)
synchronized void addLast (E element)
Iterator< E > descendingIterator ()
E element ()
E get (int index)
E getFirst ()
E getLast ()
int indexOf (Object element)
ListIterator< E > iterator ()
int lastIndexOf (Object element)
ListIterator< E > listIterator ()
ListIterator< E > listIterator (int index)
boolean offer (E e)
synchronized boolean offerFirst (E e)
synchronized boolean offerLast (E e)
E peek ()
E peekFirst ()
E peekLast ()
E poll ()
synchronized E pollFirst ()
synchronized E pollLast ()
E pop ()
void push (E e)
E remove ()
synchronized E remove (int index)
synchronized E removeFirst ()
synchronized boolean removeFirstOccurrence (Object o)
synchronized E removeLast ()
synchronized boolean removeLastOccurrence (Object o)
synchronized E set (int index, E element)
CollectionService< E >[] split (int n)
TableService< E > subList (int fromIndex, int toIndex)
TableService< E > threadSafe ()
synchronized boolean add (E element)
synchronized boolean addAll (Collection<? extends E > c)
FastCollection< E > addAll (E... elements)
FastCollection< E > addAll (FastCollection<? extends E > that)
synchronized void clear ()
synchronized AtomicCollectionImpl< E > clone ()
Equality<? super E > comparator ()
boolean contains (Object o)
boolean containsAll (Collection<?> c)
boolean equals (Object o)
int hashCode ()
boolean isEmpty ()
synchronized boolean remove (Object o)
synchronized boolean removeAll (Collection<?> c)
synchronized boolean retainAll (Collection<?> c)
int size ()
Object[] toArray ()
synchronized void update (Consumer< CollectionService< E >> action, CollectionService< E > view)
void update (Consumer<? extends Collection< E >> action)
void update (Consumer< T > action, T part)
void perform (Consumer< CollectionService< E >> action, CollectionService< E > view)
void perform (Consumer<? extends Collection< E >> action)
void perform (Consumer< T > action, T part)
FastCollection< E > atomic ()
FastCollection< E > shared ()
FastCollection< E > parallel ()
FastCollection< E > sequential ()
FastCollection< E > unmodifiable ()
FastCollection< E > filtered (Predicate<? super E > filter)
FastCollection< E > sorted ()
FastCollection< E > sorted (Comparator<? super E > cmp)
FastCollection< E > reversed ()
FastCollection< E > distinct ()
void forEach (final Consumer<? super E > consumer)
boolean removeIf (final Predicate<? super E > filter)
E reduce (Reducer< E > reducer)
E min ()
E max ()
String toString ()
Protected Member Functions
TableService< E > targetView ()
TableService< E > target ()
CollectionService< E > cloneTarget ()
final boolean updateInProgress ()
CollectionService< E > service ()
Static Protected Member Functions
static< E > CollectionService< E > serviceOf (FastCollection< E > collection)
Protected Attributes
volatile CollectionService< E > immutable
transient Thread updatingThread
Package Functions
public< T > T[] toArray (T[] a)
public< R > FastCollection< R > mapped (Function<? super E, ? extends R > function)
public< T extends E > T any (Class< T > type)
public< T extends Collection< E > > Immutable< T > toImmutable ()
Static Private Attributes
static final long serialVersionUID = 0x600L
Detailed Description
An atomic view over a table.
Definition at line 22 of file AtomicTableImpl.java.
Constructor & Destructor Documentation
AtomicTableImpl()
javolution.util.internal.table.AtomicTableImpl< E >.AtomicTableImpl (TableService< E > target)
Definition at line 27 of file AtomicTableImpl.java.
{
         super(target);
     }
References javolution.util.internal.table.AtomicTableImpl< E >.target().
Member Function Documentation
add() [1/2]
synchronized boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.add (E element) inherited
Adds the specified element to this collection
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 61 of file AtomicCollectionImpl.java.
{
         boolean changed = target().add(element);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.collection.CollectionView< E >.target, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
add() [2/2]
synchronized void javolution.util.internal.table.AtomicTableImpl< E >.add (int index, E element)
Definition at line 32 of file AtomicTableImpl.java.
{
         target().add(index, element);
         if (!updateInProgress()) immutable = cloneTarget();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.table.AtomicTableImpl< E >.element(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
addAll() [1/4]
synchronized boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.addAll (Collection<? extends E > that) inherited
Adds all the specified elements to this collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 68 of file AtomicCollectionImpl.java.
{
         boolean changed = target().addAll(c);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.collection.CollectionView< E >.target, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
addAll() [2/4]
FastCollection<E> javolution.util.FastCollection< E >.addAll (E... elements) inherited
Returns this collection with the specified element added.
Parameters
elements the elements to be added.
Returns
this
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSortedSet< E >, javolution.util.FastSet< E >, and javolution.util.FastSortedTable< E >.
Definition at line 552 of file FastCollection.java.
{
         for (E e : elements) {
             add(e);
         }
         return this;
     }
addAll() [3/4]
FastCollection<E> javolution.util.FastCollection< E >.addAll (FastCollection<? extends E > that) inherited
Returns this collection with the specified collection's elements added in sequence.
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSortedSet< E >, javolution.util.FastSet< E >, and javolution.util.FastSortedTable< E >.
Definition at line 564 of file FastCollection.java.
{
         addAll((Collection<? extends E>) that);
         return this;
     }
addAll() [4/4]
synchronized boolean javolution.util.internal.table.AtomicTableImpl< E >.addAll (int index, Collection<? extends E > c)
Definition at line 38 of file AtomicTableImpl.java.
{
         boolean changed = target().addAll(index, c);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
addFirst()
synchronized void javolution.util.internal.table.AtomicTableImpl< E >.addFirst (E element)
Definition at line 45 of file AtomicTableImpl.java.
{
         target().addFirst(element);
         if (!updateInProgress()) immutable = cloneTarget();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.table.AtomicTableImpl< E >.element(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.push().
addLast()
synchronized void javolution.util.internal.table.AtomicTableImpl< E >.addLast (E element)
Definition at line 51 of file AtomicTableImpl.java.
{
         target().addLast(element);
         if (!updateInProgress()) immutable = cloneTarget();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.table.AtomicTableImpl< E >.element(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
any()
public<T extends E> T javolution.util.FastCollection< E >.any (Class< T > type) package inherited
Returns any non-null element of the specified type (convenience method).
Parameters
type the element type searched for.
Returns
reduce(Reducers.any(type))
See also
Reducers::any
Definition at line 515 of file FastCollection.java.
{
         return (T) reduce((Reducer<E>) Reducers.any(type));
     }
References javolution.util.function.Reducers.any().
atomic()
FastCollection<E> javolution.util.FastCollection< E >.atomic () inherited
Returns an atomic view over this collection. All operations that write or access multiple elements in the collection (such as addAll(), retainAll()) are atomic. Iterators on atomic collections are thread-safe (no ConcurrentModificationException possible).
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSet< E >, javolution.util.FastSortedTable< E >, and javolution.util.FastSortedSet< E >.
Definition at line 187 of file FastCollection.java.
{
         return new AtomicCollectionImpl<E>(service());
     }
clear()
synchronized void javolution.util.internal.collection.AtomicCollectionImpl< E >.clear () inherited
Removes all elements from this collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 75 of file AtomicCollectionImpl.java.
{
         clear();
         if (!updateInProgress()) {
             immutable = cloneTarget();
         }
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
clone()
synchronized AtomicCollectionImpl<E> javolution.util.internal.collection.AtomicCollectionImpl< E >.clone () inherited
Returns a copy of this collection; updates of the copy should not impact the original.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 83 of file AtomicCollectionImpl.java.
                                                         { // Synchronized required since working with real target.
         AtomicCollectionImpl<E> copy = (AtomicCollectionImpl<E>) super.clone();
         copy.updatingThread = null;
         return copy;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.clone(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updatingThread.
Referenced by javolution.util.internal.collection.AtomicCollectionImpl< E >.clone().
cloneTarget()
CollectionService<E> javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget () protected inherited
Returns a clone copy of target.
Definition at line 191 of file AtomicCollectionImpl.java.
{
         try {
             return target().clone();
         } catch (CloneNotSupportedException e) {
             throw new Error("Cannot happen since target is Cloneable.");
         }
     }
References javolution.util.internal.collection.CollectionView< E >.target.
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.add(), javolution.util.internal.collection.AtomicCollectionImpl< E >.add(), javolution.util.internal.table.AtomicTableImpl< E >.addAll(), javolution.util.internal.collection.AtomicCollectionImpl< E >.addAll(), javolution.util.internal.table.AtomicTableImpl< E >.addFirst(), javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >.addIfAbsent(), javolution.util.internal.table.AtomicTableImpl< E >.addLast(), javolution.util.internal.collection.AtomicCollectionImpl< E >.AtomicCollectionImpl(), javolution.util.internal.collection.AtomicCollectionImpl< E >.clear(), javolution.util.internal.table.AtomicTableImpl< E >.offerFirst(), javolution.util.internal.table.AtomicTableImpl< E >.offerLast(), javolution.util.internal.table.AtomicTableImpl< E >.pollFirst(), javolution.util.internal.table.AtomicTableImpl< E >.pollLast(), javolution.util.internal.collection.AtomicCollectionImpl< E >.remove(), javolution.util.internal.table.AtomicTableImpl< E >.remove(), javolution.util.internal.collection.AtomicCollectionImpl< E >.removeAll(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirst(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirstOccurrence(), javolution.util.internal.table.AtomicTableImpl< E >.removeLast(), javolution.util.internal.table.AtomicTableImpl< E >.removeLastOccurrence(), javolution.util.internal.collection.AtomicCollectionImpl< E >.retainAll(), javolution.util.internal.table.AtomicTableImpl< E >.set(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.update().
comparator()
Equality<? super E> javolution.util.internal.collection.AtomicCollectionImpl< E >.comparator () inherited
Returns the comparator uses by this collection for equality and/or ordering if this collection is sorted.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 90 of file AtomicCollectionImpl.java.
{
         return immutable.comparator();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable.
contains()
boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.contains (Object searched) inherited
Indicates if this collection contains the specified element.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 95 of file AtomicCollectionImpl.java.
{
         return targetView().contains(o);
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
containsAll()
boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.containsAll (Collection<?> that) inherited
Indicates if this collection contains all the specified elements.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 100 of file AtomicCollectionImpl.java.
{
         return targetView().containsAll(c);
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
descendingIterator()
Iterator<E> javolution.util.internal.table.AtomicTableImpl< E >.descendingIterator ()
Definition at line 57 of file AtomicTableImpl.java.
{
         return new ReversedTableImpl<E>(this).iterator();
     }
References javolution.util.internal.table.TableView< E >.iterator().
distinct()
FastCollection<E> javolution.util.FastCollection< E >.distinct () inherited
Returns a view exposing only distinct elements (it does not iterate twice over the same elements). Adding elements already in the collection through this view has no effect. If this collection is initially empty, using a distinct view to add new elements ensures that this collection has no duplicate.
Definition at line 293 of file FastCollection.java.
{
         return new DistinctCollectionImpl<E>(service());
     }
element()
E javolution.util.internal.table.AtomicTableImpl< E >.element ()
Definition at line 62 of file AtomicTableImpl.java.
{
         return getFirst();
     }
References javolution.util.internal.table.AtomicTableImpl< E >.getFirst().
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.add(), javolution.util.internal.table.AtomicTableImpl< E >.addFirst(), javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >.addIfAbsent(), javolution.util.internal.table.AtomicTableImpl< E >.addLast(), javolution.util.internal.table.AtomicTableImpl< E >.indexOf(), javolution.util.internal.table.AtomicTableImpl< E >.lastIndexOf(), javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >.positionOf(), and javolution.util.internal.table.AtomicTableImpl< E >.set().
equals()
boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.equals (Object obj) inherited
Compares the specified object with this collection for equality. This method follows the Collection#equals(Object) specification if this collection comparator is Equalities#STANDARD (default). Otherwise, only collections using the same comparator can be considered equals.
Parameters
obj the object to be compared for equality with this collection
Returns
true if both collections are considered equals; false otherwise.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 105 of file AtomicCollectionImpl.java.
{
         return targetView().equals(o);
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
filtered()
FastCollection<E> javolution.util.FastCollection< E >.filtered (Predicate<? super E > filter) inherited
Returns a view exposing only the elements matching the specified filter. Adding elements not matching the specified filter has no effect. If this collection is initially empty, using a filtered view to add new elements ensure that this collection has only elements satisfying the filter predicate.
Reimplemented in javolution.util.FastSet< E >.
Definition at line 250 of file FastCollection.java.
{
         return new FilteredCollectionImpl<E>(service(), filter);
     }
forEach()
void javolution.util.FastCollection< E >.forEach (final Consumer<? super E > consumer) inherited
Iterates over all this collection elements applying the specified consumer (convenience method). Iterations are performed concurrently if the collection is parallel.
Parameters
consumer the functional consumer applied to the collection elements.
Definition at line 346 of file FastCollection.java.
{
         perform(new Consumer<Collection<E>>() {
             public void accept(Collection<E> view) {
                 Iterator<E> it = view.iterator();
                 while (it.hasNext()) {
                     consumer.accept(it.next());
                 }
             }
         });
     }
References javolution.util.function.Consumer< T >.accept().
get()
E javolution.util.internal.table.AtomicTableImpl< E >.get (int index)
Definition at line 67 of file AtomicTableImpl.java.
{
         return targetView().get(index);
     }
References javolution.util.internal.table.AtomicTableImpl< E >.targetView().
getFirst()
E javolution.util.internal.table.AtomicTableImpl< E >.getFirst ()
Definition at line 72 of file AtomicTableImpl.java.
{
         return targetView().getFirst();
     }
References javolution.util.internal.table.AtomicTableImpl< E >.targetView().
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.element().
getLast()
E javolution.util.internal.table.AtomicTableImpl< E >.getLast ()
Definition at line 77 of file AtomicTableImpl.java.
{
         return targetView().getLast();
     }
References javolution.util.internal.table.AtomicTableImpl< E >.targetView().
hashCode()
int javolution.util.internal.collection.AtomicCollectionImpl< E >.hashCode () inherited
Returns the hash code of this collection. This method follows the Collection#hashCode() specification if this collection comparator is Equalities#STANDARD.
Returns
this collection hash code.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 110 of file AtomicCollectionImpl.java.
{
         return targetView().hashCode();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
indexOf()
int javolution.util.internal.table.AtomicTableImpl< E >.indexOf (Object element)
Definition at line 82 of file AtomicTableImpl.java.
{
         return targetView().indexOf(element);
     }
References javolution.util.internal.table.AtomicTableImpl< E >.element(), and javolution.util.internal.table.AtomicTableImpl< E >.targetView().
isEmpty()
boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.isEmpty () inherited
Indicates if this collection is empty.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 115 of file AtomicCollectionImpl.java.
{
         return targetView().isEmpty();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
iterator()
ListIterator<E> javolution.util.internal.table.AtomicTableImpl< E >.iterator ()
Returns an iterator over this collection elements. For shared/atomic collections the iterator is immune to concurrent modifications. In other words the elements iterated over may or may not reflect the current state of the collection.
Reimplemented from javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 87 of file AtomicTableImpl.java.
{
         return listIterator(0);
     }
References javolution.util.internal.table.AtomicTableImpl< E >.listIterator().
lastIndexOf()
int javolution.util.internal.table.AtomicTableImpl< E >.lastIndexOf (Object element)
Definition at line 92 of file AtomicTableImpl.java.
{
         return targetView().lastIndexOf(element);
     }
References javolution.util.internal.table.AtomicTableImpl< E >.element(), and javolution.util.internal.table.AtomicTableImpl< E >.targetView().
listIterator() [1/2]
ListIterator<E> javolution.util.internal.table.AtomicTableImpl< E >.listIterator ()
Definition at line 97 of file AtomicTableImpl.java.
{
         return listIterator(0);
     }
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.iterator().
listIterator() [2/2]
ListIterator<E> javolution.util.internal.table.AtomicTableImpl< E >.listIterator (int index)
Definition at line 102 of file AtomicTableImpl.java.
{
         return new TableIteratorImpl<E>(this, index); // Iterator view on this.
     }
mapped()
public<R> FastCollection<R> javolution.util.FastCollection< E >.mapped (Function<? super E, ? extends R > function) package inherited
Returns a view exposing elements through the specified mapping function. The returned view does not allow new elements to be added.
Definition at line 258 of file FastCollection.java.
{
         return new MappedCollectionImpl<E, R>(service(), function);
     }
Referenced by javolution.xml.internal.stream.EntitiesImpl.setEntitiesMapping().
max()
E javolution.util.FastCollection< E >.max () inherited
Returns the largest element of this collection using this collection comparator (convenience method). Returns
null
if this collection is empty.
Returns
reduce(Reducers.max(comparator()))
See also
Reducers::max
Definition at line 541 of file FastCollection.java.
                    {
         return reduce(Reducers.max(comparator()));
     }
References javolution.util.function.Reducers.max().
min()
E javolution.util.FastCollection< E >.min () inherited
Returns the smallest element of this collection using this collection comparator (convenience method). Returns
null
if this collection is empty.
Returns
reduce(Reducers.min(comparator()))
See also
Reducers::min
Definition at line 528 of file FastCollection.java.
                    {
         return reduce(Reducers.min(comparator()));
     }
References javolution.util.function.Reducers.min().
offer()
boolean javolution.util.internal.table.AtomicTableImpl< E >.offer (E e)
Definition at line 107 of file AtomicTableImpl.java.
{
         return offerLast(e);
     }
References javolution.util.internal.table.AtomicTableImpl< E >.offerLast().
offerFirst()
synchronized boolean javolution.util.internal.table.AtomicTableImpl< E >.offerFirst (E e)
Definition at line 112 of file AtomicTableImpl.java.
{
         boolean changed = target().offerFirst(e);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
offerLast()
synchronized boolean javolution.util.internal.table.AtomicTableImpl< E >.offerLast (E e)
Definition at line 119 of file AtomicTableImpl.java.
{
         boolean changed = target().offerLast(e);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.offer().
parallel()
FastCollection<E> javolution.util.FastCollection< E >.parallel () inherited
Returns a parallel collection. Parallel collections affect only closure-based operations, all others operations behaving the same. Parallel actions are performed concurrently using Javolution ConcurrentContext. The number of parallel views is derived from the context concurrency (
number of parallel views = concurrency + 1
). Parallel views do not require this collection to be thread-safe (internal synchronization).
See also
#perform(Consumer)
#update(Consumer)
#forEach(Consumer)
#removeIf(Predicate)
#reduce(Reducer)
Definition at line 222 of file FastCollection.java.
{
         return new ParallelCollectionImpl<E>(service());
     }
peek()
E javolution.util.internal.table.AtomicTableImpl< E >.peek ()
Definition at line 126 of file AtomicTableImpl.java.
                     {
         return peekFirst();
     }
References javolution.util.internal.table.AtomicTableImpl< E >.peekFirst().
peekFirst()
E javolution.util.internal.table.AtomicTableImpl< E >.peekFirst ()
Definition at line 131 of file AtomicTableImpl.java.
{
         return targetView().peekFirst();
     }
References javolution.util.internal.table.AtomicTableImpl< E >.targetView().
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.peek().
peekLast()
E javolution.util.internal.table.AtomicTableImpl< E >.peekLast ()
Definition at line 136 of file AtomicTableImpl.java.
{
         return targetView().peekLast();
     }
References javolution.util.internal.table.AtomicTableImpl< E >.targetView().
perform() [1/3]
void javolution.util.internal.collection.CollectionView< E >.perform (Consumer< CollectionService< E >> action, CollectionService< E > view) inherited
Reimplemented in javolution.util.internal.collection.ParallelCollectionImpl< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Definition at line 163 of file CollectionView.java.
{
         if (target == null) {
             action.accept(view);
         } else {
             target.perform(action, view);
         }
     }
perform() [2/3]
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
perform() [3/3]
void javolution.util.FastCollection< E >.perform (Consumer<? extends Collection< E >> action) inherited
Executes the specified read-only action on this collection. That logic may be performed concurrently on sub-collections if this collection is parallel.
Parameters
action the read-only action.
Exceptions
UnsupportedOperationException if the action tries to update this collection and this collection is thread-safe.
ClassCastException if the action type is not compatible with this collection (e.g. action on set and this is a list).
See also
#update(Consumer)
Definition at line 315 of file FastCollection.java.
{
         service().perform((Consumer<CollectionService<E>>) action, service());
     }
poll()
E javolution.util.internal.table.AtomicTableImpl< E >.poll ()
Definition at line 141 of file AtomicTableImpl.java.
                     {
         return pollFirst();
     }
References javolution.util.internal.table.AtomicTableImpl< E >.pollFirst().
pollFirst()
synchronized E javolution.util.internal.table.AtomicTableImpl< E >.pollFirst ()
Definition at line 146 of file AtomicTableImpl.java.
{
         E e = target().pollFirst();
         if ((e != null) && !updateInProgress()) immutable = cloneTarget();
         return e;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.poll().
pollLast()
synchronized E javolution.util.internal.table.AtomicTableImpl< E >.pollLast ()
Definition at line 153 of file AtomicTableImpl.java.
{
         E e = target().pollLast();
         if ((e != null) && !updateInProgress()) immutable = cloneTarget();
         return e;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
pop()
E javolution.util.internal.table.AtomicTableImpl< E >.pop ()
Definition at line 160 of file AtomicTableImpl.java.
                    {
         return removeFirst();
     }
References javolution.util.internal.table.AtomicTableImpl< E >.removeFirst().
push()
void javolution.util.internal.table.AtomicTableImpl< E >.push (E e)
Definition at line 165 of file AtomicTableImpl.java.
{
         addFirst(e);
     }
References javolution.util.internal.table.AtomicTableImpl< E >.addFirst().
reduce()
E javolution.util.FastCollection< E >.reduce (Reducer< E > reducer) inherited
Performs a reduction of the elements of this collection using the specified reducer. This may not involve iterating over all the collection elements, for example the reducers: Reducers#any, Reducers#and and Reducers#or may stop iterating early. Reduction is performed concurrently if this collection is parallel.
Parameters
reducer the collection reducer.
Returns
the reduction result.
Definition at line 396 of file FastCollection.java.
{
         perform(reducer);
         return reducer.get();
     }
remove() [1/3]
E javolution.util.internal.table.AtomicTableImpl< E >.remove ()
Definition at line 170 of file AtomicTableImpl.java.
                       {
         return removeFirst();
     }
References javolution.util.internal.table.AtomicTableImpl< E >.removeFirst().
remove() [2/3]
synchronized E javolution.util.internal.table.AtomicTableImpl< E >.remove (int index)
Definition at line 175 of file AtomicTableImpl.java.
{
         E e = target().remove(index);
         if (!updateInProgress()) immutable = cloneTarget();
         return e;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
remove() [3/3]
synchronized boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.remove (Object searched) inherited
Removes the specified element from this collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 125 of file AtomicCollectionImpl.java.
{
         boolean changed = target().remove(o);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.collection.CollectionView< E >.target, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
Referenced by javolution.util.internal.collection.AtomicCollectionImpl< E >.IteratorImpl.remove().
removeAll()
synchronized boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.removeAll (Collection<?> that) inherited
Removes all the specified element from this collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 132 of file AtomicCollectionImpl.java.
{
         boolean changed = target().removeAll(c);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.collection.CollectionView< E >.target, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
removeFirst()
synchronized E javolution.util.internal.table.AtomicTableImpl< E >.removeFirst ()
Definition at line 182 of file AtomicTableImpl.java.
{
         E e = target().removeFirst();
         if (!updateInProgress()) immutable = cloneTarget();
         return e;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.pop(), and javolution.util.internal.table.AtomicTableImpl< E >.remove().
removeFirstOccurrence()
synchronized boolean javolution.util.internal.table.AtomicTableImpl< E >.removeFirstOccurrence (Object o)
Definition at line 189 of file AtomicTableImpl.java.
{
         boolean changed = target().removeFirstOccurrence(o);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
removeIf()
boolean javolution.util.FastCollection< E >.removeIf (final Predicate<? super E > filter) inherited
Removes from this collection all the elements matching the specified functional predicate (convenience method). Removals are performed concurrently if this collection is parallel and atomically if this collection is atomic.
Parameters
filter a predicate returning
true
for elements to be removed.
Returns
true
if at least one element has been removed;
false
otherwise.
Definition at line 368 of file FastCollection.java.
{
         final boolean[] removed = new boolean[1];
         update(new Consumer<Collection<E>>() {
             public void accept(Collection<E> view) {
                 Iterator<E> it = view.iterator();
                 while (it.hasNext()) {
                     if (filter.test(it.next())) {
                         it.remove(); // Ok mutable iteration.
                         removed[0] = true;
                     }
                 }
             }
         });
         return removed[0];
     }
removeLast()
synchronized E javolution.util.internal.table.AtomicTableImpl< E >.removeLast ()
Definition at line 196 of file AtomicTableImpl.java.
{
         E e = target().removeLast();
         if (!updateInProgress()) immutable = cloneTarget();
         return e;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
removeLastOccurrence()
synchronized boolean javolution.util.internal.table.AtomicTableImpl< E >.removeLastOccurrence (Object o)
Definition at line 203 of file AtomicTableImpl.java.
{
         boolean changed = target().removeLastOccurrence(o);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
retainAll()
synchronized boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.retainAll (Collection<?> that) inherited
Removes all the elements except those in the specified collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 139 of file AtomicCollectionImpl.java.
{
         boolean changed = target().retainAll(c);
         if (changed && !updateInProgress()) immutable = cloneTarget();
         return changed;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.collection.CollectionView< E >.target, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
reversed()
FastCollection<E> javolution.util.FastCollection< E >.reversed () inherited
Returns a view exposing elements in reverse iterative order.
Reimplemented in javolution.util.FastTable< E >.
Definition at line 282 of file FastCollection.java.
{
         return new ReversedCollectionImpl<E>(service());
     }
sequential()
FastCollection<E> javolution.util.FastCollection< E >.sequential () inherited
Returns a sequential view of this collection. Using this view, all closure-based iterations are performed sequentially.
Definition at line 230 of file FastCollection.java.
{
         return new SequentialCollectionImpl<E>(service());
     }
service()
CollectionService<E> javolution.util.internal.collection.CollectionView< E >.service () protected inherited
Returns the service implementation of this collection (for sub-classes).
Reimplemented from javolution.util.FastCollection< E >.
Definition at line 274 of file CollectionView.java.
{
         return this;
     }
serviceOf()
static <E> CollectionService<E> javolution.util.FastCollection< E >.serviceOf (FastCollection< E > collection) static protected inherited
Returns the service implementation of any fast collection (for sub-classes).
Definition at line 647 of file FastCollection.java.
{
         return collection.service();
     }
References javolution.util.FastCollection< E >.service().
set()
synchronized E javolution.util.internal.table.AtomicTableImpl< E >.set (int index, E element)
Definition at line 210 of file AtomicTableImpl.java.
{
         E e = target().set(index, element);
         if (!updateInProgress()) immutable = cloneTarget();
         return e;
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.table.AtomicTableImpl< E >.element(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.table.AtomicTableImpl< E >.target(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
shared()
FastCollection<E> javolution.util.FastCollection< E >.shared () inherited
Returns a thread-safe view over this collection. The shared view allows for concurrent read as long as there is no writer. The default implementation is based on readers-writers locks giving priority to writers. Iterators on shared collections are thread-safe (no ConcurrentModificationException possible).
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSet< E >, javolution.util.FastSortedTable< E >, and javolution.util.FastSortedSet< E >.
Definition at line 201 of file FastCollection.java.
{
         return new SharedCollectionImpl<E>(service());
     }
size()
int javolution.util.internal.collection.AtomicCollectionImpl< E >.size () inherited
Returns the size of this collection.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 146 of file AtomicCollectionImpl.java.
                       {
         return targetView().size();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
sorted() [1/2]
FastCollection<E> javolution.util.FastCollection< E >.sorted () inherited
Returns a view exposing elements sorted according to the collection order.
Definition at line 267 of file FastCollection.java.
{
         return new SortedCollectionImpl<E>(service(), comparator());
     }
Referenced by javolution.util.internal.collection.SortedCollectionImpl< E >.IteratorImpl.IteratorImpl().
sorted() [2/2]
FastCollection<E> javolution.util.FastCollection< E >.sorted (Comparator<? super E > cmp) inherited
Returns a view exposing elements sorted according to the specified comparator.
Definition at line 275 of file FastCollection.java.
{
         return new SortedCollectionImpl<E>(service(), cmp);
     }
split()
CollectionService<E> [] javolution.util.internal.table.AtomicTableImpl< E >.split (int n)
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Reimplemented from javolution.util.internal.collection.AtomicCollectionImpl< E >.
Definition at line 217 of file AtomicTableImpl.java.
{
         return SubTableImpl.splitOf(this, n); // Sub-views over this.
     }
References javolution.util.internal.table.SubTableImpl< E >.splitOf().
subList()
TableService<E> javolution.util.internal.table.AtomicTableImpl< E >.subList (int fromIndex, int toIndex)
Implements javolution.util.service.TableService< E >.
Definition at line 222 of file AtomicTableImpl.java.
{
         return new SubTableImpl<E>(this, fromIndex, toIndex); // View on this.
     }
target()
TableService<E> javolution.util.internal.table.AtomicTableImpl< E >.target () protected
Returns the actual target
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Reimplemented in javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >.
Definition at line 238 of file AtomicTableImpl.java.
{
         return (TableService<E>) super.target();
     }
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.add(), javolution.util.internal.table.AtomicTableImpl< E >.addAll(), javolution.util.internal.table.AtomicTableImpl< E >.addFirst(), javolution.util.internal.table.AtomicTableImpl< E >.addLast(), javolution.util.internal.table.AtomicTableImpl< E >.AtomicTableImpl(), javolution.util.internal.table.AtomicTableImpl< E >.offerFirst(), javolution.util.internal.table.AtomicTableImpl< E >.offerLast(), javolution.util.internal.table.AtomicTableImpl< E >.pollFirst(), javolution.util.internal.table.AtomicTableImpl< E >.pollLast(), javolution.util.internal.table.AtomicTableImpl< E >.remove(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirst(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirstOccurrence(), javolution.util.internal.table.AtomicTableImpl< E >.removeLast(), javolution.util.internal.table.AtomicTableImpl< E >.removeLastOccurrence(), and javolution.util.internal.table.AtomicTableImpl< E >.set().
targetView()
TableService<E> javolution.util.internal.table.AtomicTableImpl< E >.targetView () protected
Returns either the immutable target or the actual target if updating thread.
Reimplemented from javolution.util.internal.collection.AtomicCollectionImpl< E >.
Reimplemented in javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >.
Definition at line 232 of file AtomicTableImpl.java.
{
         return (TableService<E>) super.targetView();
     }
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.get(), javolution.util.internal.table.AtomicTableImpl< E >.getFirst(), javolution.util.internal.table.AtomicTableImpl< E >.getLast(), javolution.util.internal.table.AtomicTableImpl< E >.indexOf(), javolution.util.internal.table.AtomicTableImpl< E >.lastIndexOf(), javolution.util.internal.table.AtomicTableImpl< E >.peekFirst(), and javolution.util.internal.table.AtomicTableImpl< E >.peekLast().
threadSafe()
TableService<E> javolution.util.internal.table.AtomicTableImpl< E >.threadSafe ()
Returns a thread-safe version of this service (used during parallel updates).
Reimplemented from javolution.util.internal.collection.AtomicCollectionImpl< E >.
Reimplemented in javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >.
Definition at line 227 of file AtomicTableImpl.java.
{
         return this;
     }
toArray() [1/2]
Object [] javolution.util.internal.collection.AtomicCollectionImpl< E >.toArray () inherited
Returns an array holding this collection elements.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 162 of file AtomicCollectionImpl.java.
{
         return targetView().toArray();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
toArray() [2/2]
public<T> T [] javolution.util.internal.collection.AtomicCollectionImpl< E >.toArray (T[] array) package inherited
Returns the specified array holding this collection elements if enough capacity.
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 167 of file AtomicCollectionImpl.java.
{
         return targetView().toArray(a);
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView().
toImmutable()
public<T extends Collection<E> > Immutable<T> javolution.util.FastCollection< E >.toImmutable () package inherited
Returns an immutable reference over this collection. The immutable value is an unmodifiable view of this collection. The caller must guarantees that the original collection is never going to be updated (e.g. there is no reference left of the original collection).
Definition at line 585 of file FastCollection.java.
{
         return new Immutable<T>() {
             @SuppressWarnings("unchecked")
             final T value = (T) unmodifiable();
             @Override
             public T value() {
                 return value;
             }
         };
     }
toString()
String javolution.util.FastCollection< E >.toString () inherited
Returns the string representation of this collection using its default format.
Definition at line 634 of file FastCollection.java.
{
         return TextContext.getFormat(FastCollection.class).format(this);
     }
References javolution.text.TextContext.getFormat().
unmodifiable()
FastCollection<E> javolution.util.FastCollection< E >.unmodifiable () inherited
Returns an unmodifiable view over this collection. Any attempt to modify the collection through this view will result into a java.lang.UnsupportedOperationException being raised.
Reimplemented in javolution.util.FastTable< E >, javolution.util.FastSet< E >, javolution.util.FastSortedTable< E >, and javolution.util.FastSortedSet< E >.
Definition at line 239 of file FastCollection.java.
{
         return new UnmodifiableCollectionImpl<E>(service());
     }
update() [1/3]
synchronized void javolution.util.internal.collection.AtomicCollectionImpl< E >.update (Consumer< CollectionService< E >> action, CollectionService< E > view) inherited
Reimplemented from javolution.util.internal.collection.CollectionView< E >.
Definition at line 172 of file AtomicCollectionImpl.java.
{
         updatingThread = Thread.currentThread(); // Update in progress.
         try {
             target().update(action, view); // No copy performed.
         } finally {
             updatingThread = null;
             immutable = cloneTarget(); // One single copy !
         }
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.cloneTarget(), javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable, javolution.util.internal.collection.CollectionView< E >.target, and javolution.util.internal.collection.AtomicCollectionImpl< E >.updatingThread.
update() [2/3]
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
update() [3/3]
void javolution.util.FastCollection< E >.update (Consumer<? extends Collection< E >> action) inherited
Executes the specified update action on this collection. That logic may be performed concurrently on sub-collections if this collection is parallel. For atomic collections the update is atomic (either concurrent readers see the full result of the action or nothing).
Parameters
action the update action.
Exceptions
ClassCastException if the action type is not compatible with this collection (e.g. action on set and this is a list).
See also
#perform(Consumer)
Definition at line 334 of file FastCollection.java.
{
         service().update((Consumer<CollectionService<E>>) action, service());
     }
Referenced by javolution.util.FastTable< javolution.xml.internal.stream.XMLStreamReaderImpl >.sort().
updateInProgress()
final boolean javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress () protected inherited
Indicates if the current thread is doing an atomic update.
Definition at line 200 of file AtomicCollectionImpl.java.
{
         return updatingThread == Thread.currentThread();
     }
References javolution.util.internal.collection.AtomicCollectionImpl< E >.updatingThread.
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.add(), javolution.util.internal.collection.AtomicCollectionImpl< E >.add(), javolution.util.internal.table.AtomicTableImpl< E >.addAll(), javolution.util.internal.collection.AtomicCollectionImpl< E >.addAll(), javolution.util.internal.table.AtomicTableImpl< E >.addFirst(), javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >.addIfAbsent(), javolution.util.internal.table.AtomicTableImpl< E >.addLast(), javolution.util.internal.collection.AtomicCollectionImpl< E >.clear(), javolution.util.internal.table.AtomicTableImpl< E >.offerFirst(), javolution.util.internal.table.AtomicTableImpl< E >.offerLast(), javolution.util.internal.table.AtomicTableImpl< E >.pollFirst(), javolution.util.internal.table.AtomicTableImpl< E >.pollLast(), javolution.util.internal.collection.AtomicCollectionImpl< E >.remove(), javolution.util.internal.table.AtomicTableImpl< E >.remove(), javolution.util.internal.collection.AtomicCollectionImpl< E >.removeAll(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirst(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirstOccurrence(), javolution.util.internal.table.AtomicTableImpl< E >.removeLast(), javolution.util.internal.table.AtomicTableImpl< E >.removeLastOccurrence(), javolution.util.internal.collection.AtomicCollectionImpl< E >.retainAll(), and javolution.util.internal.table.AtomicTableImpl< E >.set().
Member Data Documentation
immutable
volatile CollectionService<E> javolution.util.internal.collection.AtomicCollectionImpl< E >.immutable protected inherited
Definition at line 52 of file AtomicCollectionImpl.java.
Referenced by javolution.util.internal.table.AtomicTableImpl< E >.add(), javolution.util.internal.collection.AtomicCollectionImpl< E >.add(), javolution.util.internal.table.AtomicTableImpl< E >.addAll(), javolution.util.internal.collection.AtomicCollectionImpl< E >.addAll(), javolution.util.internal.table.AtomicTableImpl< E >.addFirst(), javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >.addIfAbsent(), javolution.util.internal.table.AtomicTableImpl< E >.addLast(), javolution.util.internal.collection.AtomicCollectionImpl< E >.clear(), javolution.util.internal.collection.AtomicCollectionImpl< E >.comparator(), javolution.util.internal.table.AtomicTableImpl< E >.offerFirst(), javolution.util.internal.table.AtomicTableImpl< E >.offerLast(), javolution.util.internal.table.AtomicTableImpl< E >.pollFirst(), javolution.util.internal.table.AtomicTableImpl< E >.pollLast(), javolution.util.internal.collection.AtomicCollectionImpl< E >.remove(), javolution.util.internal.table.AtomicTableImpl< E >.remove(), javolution.util.internal.collection.AtomicCollectionImpl< E >.removeAll(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirst(), javolution.util.internal.table.AtomicTableImpl< E >.removeFirstOccurrence(), javolution.util.internal.table.AtomicTableImpl< E >.removeLast(), javolution.util.internal.table.AtomicTableImpl< E >.removeLastOccurrence(), javolution.util.internal.collection.AtomicCollectionImpl< E >.retainAll(), javolution.util.internal.table.AtomicTableImpl< E >.set(), javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.update().
serialVersionUID
final long javolution.util.internal.table.AtomicTableImpl< E >.serialVersionUID = 0x600L static private
Definition at line 25 of file AtomicTableImpl.java.
updatingThread
transient Thread javolution.util.internal.collection.AtomicCollectionImpl< E >.updatingThread protected inherited
Definition at line 53 of file AtomicCollectionImpl.java.
Referenced by javolution.util.internal.collection.AtomicCollectionImpl< E >.clone(), javolution.util.internal.collection.AtomicCollectionImpl< E >.targetView(), javolution.util.internal.collection.AtomicCollectionImpl< E >.update(), and javolution.util.internal.collection.AtomicCollectionImpl< E >.updateInProgress().
The documentation for this class was generated from the following file:
AtomicTableImpl.java