Javolution 6.0.0 java: javolution.io.AppendableWriter Class Reference
javolution.io.AppendableWriter Class Reference
Public Member Functions
AppendableWriter ()
AppendableWriter setOutput (Appendable output)
void write (char c) throws IOException
void write (int c) throws IOException
void write (char cbuf[], int off, int len) throws IOException
void write (String str, int off, int len) throws IOException
void write (CharSequence csq) throws IOException
void flush ()
void close ()
void reset ()
Private Attributes
Appendable _output
char[] _tmpBuffer
final CharSequence _tmpBufferAsCharSequence
Detailed Description
This class allows any Appendable to be used as a writer.
Author
Jean-Marie Dautelle
Version
3.8, May 8, 2006
Definition at line 22 of file AppendableWriter.java.
Constructor & Destructor Documentation
AppendableWriter()
javolution.io.AppendableWriter.AppendableWriter ()
Creates a new appendable writer for which the appendable output is not set.
See also
setOutput(Appendable)
Definition at line 35 of file AppendableWriter.java.
 {}
Member Function Documentation
close()
void javolution.io.AppendableWriter.close ()
Closes and resets this writer for reuse.
Definition at line 153 of file AppendableWriter.java.
{
         if (_output != null) {
             reset();
         }
     }
References javolution.io.AppendableWriter._output, and javolution.io.AppendableWriter.reset().
flush()
void javolution.io.AppendableWriter.flush ()
Flushes the stream.
Definition at line 146 of file AppendableWriter.java.
{
         // Do nothing (no buffer).
     }
reset()
void javolution.io.AppendableWriter.reset ()
Definition at line 159 of file AppendableWriter.java.
{
         _output = null;
         _tmpBuffer = null;
     }
References javolution.io.AppendableWriter._output, and javolution.io.AppendableWriter._tmpBuffer.
Referenced by javolution.io.AppendableWriter.close(), and javolution.xml.ws.WebServiceClient.invoke().
setOutput()
AppendableWriter javolution.io.AppendableWriter.setOutput (Appendable output)
Sets the appendable output being written to. For example:[code] Writer writer = new AppendableWriter().setOutput(new TextBuilder()); [/code]
Parameters
output the appendable written to.
Returns
this writer.
Exceptions
IllegalStateException if this writer is being reused and it has not been closed or reset.
Definition at line 48 of file AppendableWriter.java.
{
         if (_output != null)
             throw new IllegalStateException("Writer not closed or reset");
         _output = output;
         return this;
     }
References javolution.io.AppendableWriter._output.
Referenced by javolution.xml.ws.WebServiceClient.invoke().
write() [1/5]
void javolution.io.AppendableWriter.write (char c) throws IOException
Writes a single character.
Parameters
c char the character to be written.
Exceptions
IOException if an I/O error occurs.
Definition at line 61 of file AppendableWriter.java.
{
         if (_output == null)
             throw new IOException("Writer closed");
         _output.append(c);
     }
References javolution.io.AppendableWriter._output.
write() [2/5]
void javolution.io.AppendableWriter.write (char cbuf[], int off, int len) throws IOException
Writes a portion of an array of characters.
Parameters
cbuf the array of characters.
off the offset from which to start writing characters.
len the number of characters to write.
Exceptions
IOException if an I/O error occurs.
Definition at line 88 of file AppendableWriter.java.
{
         if (_output == null)
             throw new IOException("Writer closed");
         _tmpBuffer = cbuf;
         _output.append(_tmpBufferAsCharSequence, off, off + len);
         _tmpBuffer = null; // Removes temporary references.
     }
References javolution.io.AppendableWriter._output, javolution.io.AppendableWriter._tmpBuffer, and javolution.io.AppendableWriter._tmpBufferAsCharSequence.
write() [3/5]
void javolution.io.AppendableWriter.write (CharSequence csq) throws IOException
Writes the specified character sequence.
Parameters
csq the character sequence.
Exceptions
IOException if an I/O error occurs
Definition at line 137 of file AppendableWriter.java.
{
         if (_output == null)
             throw new IOException("Writer closed");
         _output.append(csq);
     }
References javolution.io.AppendableWriter._output.
write() [4/5]
void javolution.io.AppendableWriter.write (int c) throws IOException
Writes the 16 low-order bits of the given integer value; the 16 high-order bits are ignored.
Parameters
c the value of the character to be written.
Exceptions
IOException if an I/O error occurs.
Definition at line 74 of file AppendableWriter.java.
{
         if (_output == null)
             throw new IOException("Writer closed");
         _output.append((char) c);
     }
References javolution.io.AppendableWriter._output.
write() [5/5]
void javolution.io.AppendableWriter.write (String str, int off, int len) throws IOException
Writes a portion of a string.
Parameters
str a String.
off the offset from which to start writing characters.
len the number of characters to write.
Exceptions
IOException if an I/O error occurs
Definition at line 120 of file AppendableWriter.java.
{
         if (_output == null)
             throw new IOException("Writer closed");
         Object obj = str;
         if (obj instanceof CharSequence) {
             _output.append((CharSequence) obj);
         } else {
             _output.append(Text.valueOf(str));
         }
     }
References javolution.io.AppendableWriter._output, and javolution.text.Text.valueOf().
Member Data Documentation
_output
Appendable javolution.io.AppendableWriter._output private
Holds the current appendable output or null if closed.
Definition at line 27 of file AppendableWriter.java.
Referenced by javolution.io.AppendableWriter.close(), javolution.io.AppendableWriter.reset(), javolution.io.AppendableWriter.setOutput(), and javolution.io.AppendableWriter.write().
_tmpBuffer
char [] javolution.io.AppendableWriter._tmpBuffer private
Definition at line 96 of file AppendableWriter.java.
Referenced by javolution.io.AppendableWriter.reset(), and javolution.io.AppendableWriter.write().
_tmpBufferAsCharSequence
final CharSequence javolution.io.AppendableWriter._tmpBufferAsCharSequence private
Initial value:
= new CharSequence() {
        public int length() {
            return _tmpBuffer.length;
        }
        public char charAt(int index) {
            return _tmpBuffer[index];
        }
        public CharSequence subSequence(int start, int end) {
            throw new UnsupportedOperationException();
        }
    }
Definition at line 98 of file AppendableWriter.java.
Referenced by javolution.io.AppendableWriter.write().
The documentation for this class was generated from the following file:
AppendableWriter.java