Javolution 6.0.0 java: javolution.util.internal.table.QuickSort< E > Class Template Reference
javolution.util.internal.table.QuickSort< E > Class Template Reference
Public Member Functions
QuickSort (TableService< E > table, Comparator<? super E > comparator)
void sort ()
void sort (int first, int last)
Package Functions
void quicksort (int first, int last)
Private Member Functions
int partition (int f, int l)
Private Attributes
final Comparator<? super E > comparator
final TableService< E > table
Detailed Description
A quick sort utility class. From Wikipedia Quick Sort - http://en.wikipedia.org/wiki/Quicksort
Definition at line 19 of file QuickSort.java.
Constructor & Destructor Documentation
QuickSort()
javolution.util.internal.table.QuickSort< E >.QuickSort (TableService< E > table, Comparator<? super E > comparator)
Definition at line 24 of file QuickSort.java.
{
         this.table = table;
         this.comparator = comparator;
     }
References javolution.util.internal.table.QuickSort< E >.comparator, and javolution.util.internal.table.QuickSort< E >.table.
Member Function Documentation
partition()
int javolution.util.internal.table.QuickSort< E >.partition (int f, int l) private
Definition at line 53 of file QuickSort.java.
{
         int up, down;
         E piv = table.get(f);
         up = f;
         down = l;
         do {
             while (comparator.compare(table.get(up), piv) <= 0 && up < l) {
                 up++;
             }
             while (comparator.compare(table.get(down), piv) > 0 && down > f) {
                 down--;
             }
             if (up < down) { // Swaps.
                 E temp = table.get(up);
                 table.set(up, table.get(down));
                 table.set(down, temp);
             }
         } while (down > up);
         table.set(f, table.get(down));
         table.set(down, piv);
         return down;
     }
References javolution.util.internal.table.QuickSort< E >.comparator, and javolution.util.internal.table.QuickSort< E >.table.
Referenced by javolution.util.internal.table.QuickSort< E >.quicksort(), and javolution.util.internal.table.QuickSort< E >.sort().
quicksort()
void javolution.util.internal.table.QuickSort< E >.quicksort (int first, int last) package
Definition at line 44 of file QuickSort.java.
{
         int pivIndex = 0;
         if (first < last) {
             pivIndex = partition(first, last);
             quicksort(first, (pivIndex - 1));
             quicksort((pivIndex + 1), last);
         }
     }
References javolution.util.internal.table.QuickSort< E >.partition().
Referenced by javolution.util.internal.table.QuickSort< E >.sort().
sort() [1/2]
void javolution.util.internal.table.QuickSort< E >.sort ()
Definition at line 29 of file QuickSort.java.
{
         int size = table.size();
         if (size > 0) quicksort(0, table.size() - 1);
     }
References javolution.util.internal.table.QuickSort< E >.quicksort(), and javolution.util.internal.table.QuickSort< E >.table.
Referenced by javolution.util.internal.table.QuickSort< E >.sort(), and javolution.util.FastTable< javolution.xml.internal.stream.XMLStreamReaderImpl >.sort().
sort() [2/2]
void javolution.util.internal.table.QuickSort< E >.sort (int first, int last)
Definition at line 34 of file QuickSort.java.
{
         if (first < last) {
             int pivIndex = partition(first, last);
             sort(first, (pivIndex - 1));
             sort((pivIndex + 1), last);
         }
     }
References javolution.util.internal.table.QuickSort< E >.partition(), and javolution.util.internal.table.QuickSort< E >.sort().
Member Data Documentation
comparator
final Comparator<? super E> javolution.util.internal.table.QuickSort< E >.comparator private
Definition at line 21 of file QuickSort.java.
Referenced by javolution.util.internal.table.QuickSort< E >.partition(), and javolution.util.internal.table.QuickSort< E >.QuickSort().
table
final TableService<E> javolution.util.internal.table.QuickSort< E >.table private
Definition at line 22 of file QuickSort.java.
Referenced by javolution.util.internal.table.QuickSort< E >.partition(), javolution.util.internal.table.QuickSort< E >.QuickSort(), and javolution.util.internal.table.QuickSort< E >.sort().
The documentation for this class was generated from the following file:
QuickSort.java