Javolution 6.0.0 java: javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler Class Reference
javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler Class Reference
Public Member Functions
InputSource resolveEntity (String publicId, String systemId) throws SAXException, IOException
void notationDecl (String name, String publicId, String systemId) throws SAXException
void unparsedEntityDecl (String name, String publicId, String systemId, String notationName) throws SAXException
void setDocumentLocator (Locator locator)
void startDocument () throws SAXException
void endDocument () throws SAXException
void startPrefixMapping (String prefix, String uri) throws SAXException
void endPrefixMapping (String prefix) throws SAXException
void startElement (String uri, String localName, String qName, Attributes atts) throws SAXException
void endElement (String uri, String localName, String qName) throws SAXException
void characters (char[] ch, int start, int length) throws SAXException
void ignorableWhitespace (char[] ch, int start, int length) throws SAXException
void processingInstruction (String target, String data) throws SAXException
void skippedEntity (String name) throws SAXException
void warning (SAXParseException exception) throws SAXException
void error (SAXParseException exception) throws SAXException
void fatalError (SAXParseException exception) throws SAXException
void startPrefixMapping (CharArray prefix, CharArray uri) throws SAXException
void endPrefixMapping (CharArray prefix) throws SAXException
void startElement (CharArray uri, CharArray localName, CharArray qName, Attributes atts) throws SAXException
void endElement (CharArray uri, CharArray localName, CharArray qName) throws SAXException
void processingInstruction (CharArray target, CharArray data) throws SAXException
void skippedEntity (CharArray name) throws SAXException
Detailed Description
Definition at line 330 of file SAX2ReaderImpl.java.
Member Function Documentation
characters()
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.characters (char[] ch, int start, int length) throws SAXException
Receives notification of character data.
Parameters
ch the characters from the XML document.
start the start position in the array.
length the number of characters to read from the array.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implements javolution.xml.sax.ContentHandler.
Definition at line 361 of file SAX2ReaderImpl.java.
                                     {}
endDocument()
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.endDocument () throws SAXException
Receives notification of the end of a document.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implements javolution.xml.sax.ContentHandler.
Definition at line 348 of file SAX2ReaderImpl.java.
 {}
endElement() [1/2]
void javolution.xml.sax.ContentHandler.endElement (CharArray uri, CharArray localName, CharArray qName) throws SAXException inherited
Receives notification of the end of an element.
Parameters
uri the namespace URI, or an empty character sequence if the element has no Namespace URI or if namespace processing is not being performed.
localName the local name (without prefix), or an empty character sequence if namespace processing is not being performed.
qName the qualified XML 1.0 name (with prefix), or an empty character sequence if qualified names are not available.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.endElement(), and javolution.xml.sax.XMLReaderImpl.parseAll().
endElement() [2/2]
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.endElement (String uri, String localName, String qName) throws SAXException
Definition at line 358 of file SAX2ReaderImpl.java.
                                     {}
endPrefixMapping() [1/2]
void javolution.xml.sax.ContentHandler.endPrefixMapping (CharArray prefix) throws SAXException inherited
Ends the scope of a prefix-URI mapping.
Parameters
prefix the prefix that was being mapping.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.endPrefixMapping(), and javolution.xml.sax.XMLReaderImpl.parseAll().
endPrefixMapping() [2/2]
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.endPrefixMapping (String prefix) throws SAXException
Definition at line 353 of file SAX2ReaderImpl.java.
 {}
error()
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.error (SAXParseException exception) throws SAXException
Definition at line 374 of file SAX2ReaderImpl.java.
 {}
fatalError()
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.fatalError (SAXParseException exception) throws SAXException
Definition at line 376 of file SAX2ReaderImpl.java.
{
             throw exception;
         }
ignorableWhitespace()
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.ignorableWhitespace (char[] ch, int start, int length) throws SAXException
Receives notification of ignorable whitespace in element content.
Parameters
ch the characters from the XML document.
start the start position in the array.
length the number of characters to read from the array.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implements javolution.xml.sax.ContentHandler.
Definition at line 364 of file SAX2ReaderImpl.java.
                                     {}
notationDecl()
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.notationDecl (String name, String publicId, String systemId) throws SAXException
Definition at line 338 of file SAX2ReaderImpl.java.
                                     {}
processingInstruction() [1/2]
void javolution.xml.sax.ContentHandler.processingInstruction (CharArray target, CharArray data) throws SAXException inherited
Receives notification of a processing instruction.
Parameters
target the processing instruction target.
data the processing instruction data, or null if none was supplied. The data does not include any whitespace separating it from the target.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.sax.SAX2ReaderImpl.Proxy.processingInstruction().
processingInstruction() [2/2]
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.processingInstruction (String target, String data) throws SAXException
Definition at line 367 of file SAX2ReaderImpl.java.
                                     {}
resolveEntity()
InputSource javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.resolveEntity (String publicId, String systemId) throws SAXException, IOException
Definition at line 333 of file SAX2ReaderImpl.java.
{
             return null;
         }
setDocumentLocator()
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.setDocumentLocator (Locator locator)
Receives an object for locating the origin of SAX document events.
Parameters
locator the document locator.
Implements javolution.xml.sax.ContentHandler.
Definition at line 344 of file SAX2ReaderImpl.java.
 {}
skippedEntity() [1/2]
void javolution.xml.sax.ContentHandler.skippedEntity (CharArray name) throws SAXException inherited
Receives notification of a skipped entity.
Parameters
name the name of the skipped entity. If it is a parameter entity, the name will begin with '', and if it is the external DTD subset, it will be the character sequence "[dtd]".
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.skippedEntity().
skippedEntity() [2/2]
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.skippedEntity (String name) throws SAXException
Definition at line 370 of file SAX2ReaderImpl.java.
 {}
startDocument()
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.startDocument () throws SAXException
Receives notification of the beginning of a document.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implements javolution.xml.sax.ContentHandler.
Definition at line 346 of file SAX2ReaderImpl.java.
 {}
startElement() [1/2]
void javolution.xml.sax.ContentHandler.startElement (CharArray uri, CharArray localName, CharArray qName, Attributes atts) throws SAXException inherited
Receives notification of the beginning of an element.
Parameters
uri the namespace URI, or an empty character sequence if the element has no Namespace URI or if namespace processing is not being performed.
localName the local name (without prefix), or an empty character sequence if namespace processing is not being performed.
qName the qualified name (with prefix), or an empty character sequence if qualified names are not available.
atts the attributes attached to the element. If there are no attributes, it shall be an empty Attributes object.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.sax.SAX2ReaderImpl.Proxy.startElement().
startElement() [2/2]
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.startElement (String uri, String localName, String qName, Attributes atts) throws SAXException
Definition at line 355 of file SAX2ReaderImpl.java.
                                                      {}
startPrefixMapping() [1/2]
void javolution.xml.sax.ContentHandler.startPrefixMapping (CharArray prefix, CharArray uri) throws SAXException inherited
Begins the scope of a prefix-URI Namespace mapping.
Parameters
prefix the Namespace prefix being declared.
uri the namespace URI the prefix is mapped to.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.sax.SAX2ReaderImpl.Proxy.startPrefixMapping().
startPrefixMapping() [2/2]
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.startPrefixMapping (String prefix, String uri) throws SAXException
Definition at line 350 of file SAX2ReaderImpl.java.
                                     {}
unparsedEntityDecl()
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.unparsedEntityDecl (String name, String publicId, String systemId, String notationName) throws SAXException
Definition at line 341 of file SAX2ReaderImpl.java.
                                                                           {}
warning()
void javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler.warning (SAXParseException exception) throws SAXException
Definition at line 372 of file SAX2ReaderImpl.java.
 {}
The documentation for this class was generated from the following file:
SAX2ReaderImpl.java