Javolution 6.0.0 java: javolution.xml.sax.ContentHandler Interface Reference
javolution.xml.sax.ContentHandler Interface Reference
Public Member Functions
void setDocumentLocator (Locator locator)
void startDocument () throws SAXException
void endDocument () throws SAXException
void startPrefixMapping (CharArray prefix, CharArray uri) throws SAXException
void endPrefixMapping (CharArray prefix) throws SAXException
void startElement (CharArray uri, CharArray localName, CharArray qName, Attributes atts) throws SAXException
void endElement (CharArray uri, CharArray localName, CharArray qName) throws SAXException
void characters (char ch[], int start, int length) throws SAXException
void ignorableWhitespace (char ch[], int start, int length) throws SAXException
void processingInstruction (CharArray target, CharArray data) throws SAXException
void skippedEntity (CharArray name) throws SAXException
Detailed Description
Receives notification of the logical content of a document.
It is a more efficient version of org.xml.sax.ContentHandler with CharArray/CharSequence instead of the String to avoid forcing dynamic object allocations.
Author
David Megginson
Jean-Marie Dautelle
Version
4.0, June 16, 2006
Definition at line 27 of file ContentHandler.java.
Member Function Documentation
characters()
void javolution.xml.sax.ContentHandler.characters (char ch[], int start, int length) throws SAXException
Receives notification of character data.
Parameters
ch the characters from the XML document.
start the start position in the array.
length the number of characters to read from the array.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler, javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.characters(), and javolution.xml.sax.XMLReaderImpl.parseAll().
endDocument()
void javolution.xml.sax.ContentHandler.endDocument () throws SAXException
Receives notification of the end of a document.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler, javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.endDocument().
endElement()
void javolution.xml.sax.ContentHandler.endElement (CharArray uri, CharArray localName, CharArray qName) throws SAXException
Receives notification of the end of an element.
Parameters
uri the namespace URI, or an empty character sequence if the element has no Namespace URI or if namespace processing is not being performed.
localName the local name (without prefix), or an empty character sequence if namespace processing is not being performed.
qName the qualified XML 1.0 name (with prefix), or an empty character sequence if qualified names are not available.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.endElement(), and javolution.xml.sax.XMLReaderImpl.parseAll().
endPrefixMapping()
void javolution.xml.sax.ContentHandler.endPrefixMapping (CharArray prefix) throws SAXException
Ends the scope of a prefix-URI mapping.
Parameters
prefix the prefix that was being mapping.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.endPrefixMapping(), and javolution.xml.sax.XMLReaderImpl.parseAll().
ignorableWhitespace()
void javolution.xml.sax.ContentHandler.ignorableWhitespace (char ch[], int start, int length) throws SAXException
Receives notification of ignorable whitespace in element content.
Parameters
ch the characters from the XML document.
start the start position in the array.
length the number of characters to read from the array.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler, javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.ignorableWhitespace(), and javolution.xml.sax.XMLReaderImpl.parseAll().
processingInstruction()
void javolution.xml.sax.ContentHandler.processingInstruction (CharArray target, CharArray data) throws SAXException
Receives notification of a processing instruction.
Parameters
target the processing instruction target.
data the processing instruction data, or null if none was supplied. The data does not include any whitespace separating it from the target.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.sax.SAX2ReaderImpl.Proxy.processingInstruction().
setDocumentLocator()
void javolution.xml.sax.ContentHandler.setDocumentLocator (Locator locator)
Receives an object for locating the origin of SAX document events.
Parameters
locator the document locator.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler, javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.setDocumentLocator().
skippedEntity()
void javolution.xml.sax.ContentHandler.skippedEntity (CharArray name) throws SAXException
Receives notification of a skipped entity.
Parameters
name the name of the skipped entity. If it is a parameter entity, the name will begin with '', and if it is the external DTD subset, it will be the character sequence "[dtd]".
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.SAX2ReaderImpl.Proxy.skippedEntity().
startDocument()
void javolution.xml.sax.ContentHandler.startDocument () throws SAXException
Receives notification of the beginning of a document.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Sax2DefaultHandler, javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.sax.SAX2ReaderImpl.Proxy.startDocument().
startElement()
void javolution.xml.sax.ContentHandler.startElement (CharArray uri, CharArray localName, CharArray qName, Attributes atts) throws SAXException
Receives notification of the beginning of an element.
Parameters
uri the namespace URI, or an empty character sequence if the element has no Namespace URI or if namespace processing is not being performed.
localName the local name (without prefix), or an empty character sequence if namespace processing is not being performed.
qName the qualified name (with prefix), or an empty character sequence if qualified names are not available.
atts the attributes attached to the element. If there are no attributes, it shall be an empty Attributes object.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.sax.SAX2ReaderImpl.Proxy.startElement().
startPrefixMapping()
void javolution.xml.sax.ContentHandler.startPrefixMapping (CharArray prefix, CharArray uri) throws SAXException
Begins the scope of a prefix-URI Namespace mapping.
Parameters
prefix the Namespace prefix being declared.
uri the namespace URI the prefix is mapped to.
Exceptions
org.xml.sax.SAXException any SAX exception.
Implemented in javolution.xml.sax.SAX2ReaderImpl.Proxy, and javolution.xml.sax.DefaultHandler.
Referenced by javolution.xml.sax.XMLReaderImpl.parseAll(), and javolution.xml.sax.SAX2ReaderImpl.Proxy.startPrefixMapping().
The documentation for this interface was generated from the following file:
ContentHandler.java