Javolution 6.0.0 java: javolution.xml.XMLFormat< T >.InputElement Class Reference
javolution.xml.XMLFormat< T >.InputElement Class Reference
Public Member Functions
XMLStreamReader getStreamReader ()
boolean hasNext () throws XMLStreamException
CharArray getText () throws XMLStreamException
Attributes getAttributes () throws XMLStreamException
CharArray getAttribute (String name) throws XMLStreamException
String getAttribute (String name, String defaultValue) throws XMLStreamException
boolean getAttribute (String name, boolean defaultValue) throws XMLStreamException
char getAttribute (String name, char defaultValue) throws XMLStreamException
byte getAttribute (String name, byte defaultValue) throws XMLStreamException
short getAttribute (String name, short defaultValue) throws XMLStreamException
int getAttribute (String name, int defaultValue) throws XMLStreamException
long getAttribute (String name, long defaultValue) throws XMLStreamException
float getAttribute (String name, float defaultValue) throws XMLStreamException
double getAttribute (String name, double defaultValue) throws XMLStreamException
Package Functions
InputElement ()
public< T > T getNext () throws XMLStreamException
public< T > T get (String name) throws XMLStreamException
public< T > T get (String localName, String uri) throws XMLStreamException
public< T > T get (String name, Class< T > cls) throws XMLStreamException
public< T > T get (String localName, String uri, Class< T > cls) throws XMLStreamException
private< T > T readInstanceOf (Class cls) throws XMLStreamException
public< T > T getAttribute (String name, T defaultValue) throws XMLStreamException
void setBinding (XMLBinding xmlBinding)
void setReferenceResolver (XMLReferenceResolver xmlReferenceResolver)
void reset ()
Package Attributes
final XMLStreamReaderImpl _reader = new XMLStreamReaderImpl()
Private Member Functions
Object readReference () throws XMLStreamException
Private Attributes
XMLBinding _binding
XMLReferenceResolver _referenceResolver
boolean _isReaderAtNext
Detailed Description
This class represents an input XML element (unmarshalling).
Definition at line 186 of file XMLFormat.java.
Constructor & Destructor Documentation
InputElement()
javolution.xml.XMLFormat< T >.InputElement.InputElement () package
Default constructor.
Definition at line 211 of file XMLFormat.java.
{
             reset();
         }
Member Function Documentation
get() [1/4]
public<T> T javolution.xml.XMLFormat< T >.InputElement.get (String localName, String uri) throws XMLStreamException package
Returns the object whose type is identified by a XML class attribute only if the XML element has the specified local name and URI.
Parameters
localName the local name.
uri the namespace URI or null.
Returns
the next nested object or null.
Definition at line 299 of file XMLFormat.java.
{
             if (uri == null)
                 return (T) get(localName);
             if (!hasNext()// Asserts isReaderAtNext == true
                     || !_reader.getLocalName().equals(localName)
                     || !_reader.getNamespaceURI().equals(uri))
                 return null;
             Object ref = readReference();
             if (ref != null)
                 return (T) ref;
             // Retrieves object's class from class attribute.
             Class<?> cls = _binding.readClass(_reader, true);
             return readInstanceOf(cls);
         }
References javolution.text.CharArray.equals(), javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI(), and javolution.xml.XMLBinding.readClass().
get() [2/4]
public<T> T javolution.xml.XMLFormat< T >.InputElement.get (String localName, String uri, Class< T > cls) throws XMLStreamException package
Returns the object of specified type only if the XML element has the specified local name and namespace URI.
Parameters
localName the local name.
uri the namespace URI or null.
cls the class identifying the format of the object to return.
Returns
the next nested object or null.
Definition at line 347 of file XMLFormat.java.
{
             if (uri == null)
                 return get(localName, cls);
             if (!hasNext()// Asserts isReaderAtNext == true
                     || !_reader.getLocalName().equals(localName)
                     || !_reader.getNamespaceURI().equals(uri))
                 return null;
             Object ref = readReference();
             if (ref != null)
                 return (T) ref;
             return readInstanceOf(cls);
         }
References javolution.text.CharArray.equals(), javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName(), and javolution.xml.internal.stream.XMLStreamReaderImpl.getNamespaceURI().
get() [3/4]
public<T> T javolution.xml.XMLFormat< T >.InputElement.get (String name) throws XMLStreamException package
Returns the object whose type is identified by a XML class attribute only if the XML element has the specified local name.
Parameters
name the local name of the next element.
Returns
the next nested object or null.
Definition at line 277 of file XMLFormat.java.
{
             if (!hasNext()// Asserts isReaderAtNext == true
                     || !_reader.getLocalName().equals(name))
                 return null;
             Object ref = readReference();
             if (ref != null)
                 return (T) ref;
             // Retrieves object's class from class attribute.
             Class<?> cls = _binding.readClass(_reader, true);
             return readInstanceOf(cls);
         }
References javolution.text.CharArray.equals(), javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName(), and javolution.xml.XMLBinding.readClass().
get() [4/4]
public<T> T javolution.xml.XMLFormat< T >.InputElement.get (String name, Class< T > cls) throws XMLStreamException package
Returns the object of specified type only if the XML element has the specified local name.
Parameters
name the local name of the element to match.
cls the class identifying the format of the object to return.
Returns
the next nested object or null.
Definition at line 326 of file XMLFormat.java.
{
             if (!hasNext()// Asserts isReaderAtNext == true
                     || !_reader.getLocalName().equals(name))
                 return null;
             Object ref = readReference();
             if (ref != null)
                 return (T) ref;
             return readInstanceOf(cls);
         }
References javolution.text.CharArray.equals(), and javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName().
getAttribute() [1/11]
CharArray javolution.xml.XMLFormat< T >.InputElement.getAttribute (String name) throws XMLStreamException
Searches for the attribute having the specified name.
Parameters
name the name of the attribute.
Returns
the value for the specified attribute or null if the attribute is not found.
Definition at line 434 of file XMLFormat.java.
{
             if (_isReaderAtNext)
                 throw new XMLStreamException(
                         "Attributes should be read before reading content");
             return _reader.getAttributeValue(null, name);
         }
References javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributeValue().
getAttribute() [2/11]
boolean javolution.xml.XMLFormat< T >.InputElement.getAttribute (String name, boolean defaultValue) throws XMLStreamException
Returns the specified boolean attribute.
Parameters
name the name of the attribute searched for.
defaultValue the value returned if the attribute is not found.
Returns
the boolean value for the specified attribute or the default value if the attribute is not found.
Definition at line 463 of file XMLFormat.java.
{
             CharArray value = getAttribute(name);
             return (value != null) ? value.toBoolean() : defaultValue;
         }
References javolution.text.CharArray.toBoolean().
getAttribute() [3/11]
byte javolution.xml.XMLFormat< T >.InputElement.getAttribute (String name, byte defaultValue) throws XMLStreamException
Returns the specified byte attribute. This method handles string formats that are used to represent octal and hexadecimal numbers.
Parameters
name the name of the attribute searched for.
defaultValue the value returned if the attribute is not found.
Returns
the byte value for the specified attribute or the default value if the attribute is not found.
Definition at line 497 of file XMLFormat.java.
{
             CharArray value = getAttribute(name);
             return (value != null) ? (byte) value.toInt() : defaultValue;
         }
References javolution.text.CharArray.toInt().
getAttribute() [4/11]
char javolution.xml.XMLFormat< T >.InputElement.getAttribute (String name, char defaultValue) throws XMLStreamException
Returns the specified char attribute.
Parameters
name the name of the attribute searched for.
defaultValue the value returned if the attribute is not found.
Returns
the char value for the specified attribute or the default value if the attribute is not found.
Definition at line 477 of file XMLFormat.java.
{
             CharArray value = getAttribute(name);
             if (value == null)
                 return defaultValue;
             if (value.length() != 1)
                 throw new XMLStreamException(
                         "Single character expected (read '" + value + "')");
             return value.charAt(0);
         }
References javolution.text.CharArray.charAt(), and javolution.text.CharArray.length().
getAttribute() [5/11]
double javolution.xml.XMLFormat< T >.InputElement.getAttribute (String name, double defaultValue) throws XMLStreamException
Returns the specified double attribute.
Parameters
name the name of the attribute searched for.
defaultValue the value returned if the attribute is not found.
Returns
the double value for the specified attribute or the default value if the attribute is not found.
Definition at line 570 of file XMLFormat.java.
{
             CharArray value = getAttribute(name);
             return (value != null) ? value.toDouble() : defaultValue;
         }
References javolution.text.CharArray.toDouble().
getAttribute() [6/11]
float javolution.xml.XMLFormat< T >.InputElement.getAttribute (String name, float defaultValue) throws XMLStreamException
Returns the specified float attribute.
Parameters
name the name of the attribute searched for.
defaultValue the value returned if the attribute is not found.
Returns
the float value for the specified attribute or the default value if the attribute is not found.
Definition at line 556 of file XMLFormat.java.
{
             CharArray value = getAttribute(name);
             return (value != null) ? value.toFloat() : defaultValue;
         }
References javolution.text.CharArray.toFloat().
getAttribute() [7/11]
int javolution.xml.XMLFormat< T >.InputElement.getAttribute (String name, int defaultValue) throws XMLStreamException
Returns the specified int attribute. This method handles string formats that are used to represent octal and hexadecimal numbers.
Parameters
name the name of the attribute searched for.
defaultValue the value returned if the attribute is not found.
Returns
the int value for the specified attribute or the default value if the attribute is not found.
Definition at line 527 of file XMLFormat.java.
{
             CharArray value = getAttribute(name);
             return (value != null) ? value.toInt() : defaultValue;
         }
References javolution.text.CharArray.toInt().
getAttribute() [8/11]
long javolution.xml.XMLFormat< T >.InputElement.getAttribute (String name, long defaultValue) throws XMLStreamException
Returns the specified long attribute. This method handles string formats that are used to represent octal and hexadecimal numbers.
Parameters
name the name of the attribute searched for.
defaultValue the value returned if the attribute is not found.
Returns
the long value for the specified attribute or the default value if the attribute is not found.
Definition at line 542 of file XMLFormat.java.
{
             CharArray value = getAttribute(name);
             return (value != null) ? value.toLong() : defaultValue;
         }
References javolution.text.CharArray.toLong().
getAttribute() [9/11]
short javolution.xml.XMLFormat< T >.InputElement.getAttribute (String name, short defaultValue) throws XMLStreamException
Returns the specified short attribute. This method handles string formats that are used to represent octal and hexadecimal numbers.
Parameters
name the name of the attribute searched for.
defaultValue the value returned if the attribute is not found.
Returns
the short value for the specified attribute or the default value if the attribute is not found.
Definition at line 512 of file XMLFormat.java.
{
             CharArray value = getAttribute(name);
             return (value != null) ? (short) value.toInt() : defaultValue;
         }
References javolution.text.CharArray.toInt().
getAttribute() [10/11]
String javolution.xml.XMLFormat< T >.InputElement.getAttribute (String name, String defaultValue) throws XMLStreamException
Returns the specified String attribute.
Parameters
name the name of the attribute.
defaultValue a default value.
Returns
the value for the specified attribute or the defaultValue if the attribute is not found.
Definition at line 449 of file XMLFormat.java.
{
             CharArray value = getAttribute(name);
             return (value != null) ? value.toString() : defaultValue;
         }
References javolution.text.CharArray.toString().
getAttribute() [11/11]
public<T> T javolution.xml.XMLFormat< T >.InputElement.getAttribute (String name, T defaultValue) throws XMLStreamException package
Returns the attribute of same type as the specified default value.
Parameters
name the name of the attribute.
defaultValue the value returned if the attribute is not found.
Returns
the parse value for the specified attribute or the default value if the attribute is not found.
Definition at line 585 of file XMLFormat.java.
{
             CharArray value = getAttribute(name);
             if (value == null)
                 return defaultValue;
             // Parses attribute value.
             Class<?> type = defaultValue.getClass();
             TextFormat<?> format = TextContext.getFormat(type);
             if (format == null)
                 throw new XMLStreamException("No TextFormat defined for "
                         + type);
             return (T) format.parse(value);
         }
References javolution.text.TextContext.getFormat(), and javolution.text.TextFormat< T >.parse().
getAttributes()
Attributes javolution.xml.XMLFormat< T >.InputElement.getAttributes () throws XMLStreamException
Returns the attributes for this XML input element.
Returns
the attributes mapping.
Definition at line 420 of file XMLFormat.java.
{
             if (_isReaderAtNext)
                 throw new XMLStreamException(
                         "Attributes should be read before content");
             return _reader.getAttributes();
         }
References javolution.xml.internal.stream.XMLStreamReaderImpl.getAttributes().
getNext()
public<T> T javolution.xml.XMLFormat< T >.InputElement.getNext () throws XMLStreamException package
Returns the next object whose type is identified by the local name and URI of the current XML element.
Returns
the next nested object which can be null.
Exceptions
XMLStreamException if hasNext() == false.
Definition at line 248 of file XMLFormat.java.
{
             if (!hasNext()) // Asserts isReaderAtNext == true
                 throw new XMLStreamException("No more element to read",
                         _reader.getLocation());
             // Checks for null.
             if (_reader.getLocalName().equals(NULL)) {
                 if (_reader.next() != XMLStreamReader.END_ELEMENT)
                     throw new XMLStreamException("Non Empty Null Element");
                 _isReaderAtNext = false;
                 return null;
             }
             Object ref = readReference();
             if (ref != null)
                 return (T) ref;
             // Retrieves object's class from element tag.
             Class<?> cls = _binding.readClass(_reader, false);
             return readInstanceOf(cls);
         }
References javolution.xml.stream.XMLStreamConstants.END_ELEMENT, javolution.text.CharArray.equals(), javolution.xml.internal.stream.XMLStreamReaderImpl.getLocalName(), javolution.xml.internal.stream.XMLStreamReaderImpl.getLocation(), javolution.xml.internal.stream.XMLStreamReaderImpl.next(), javolution.xml.XMLFormat< T >.NULL, and javolution.xml.XMLBinding.readClass().
getStreamReader()
XMLStreamReader javolution.xml.XMLFormat< T >.InputElement.getStreamReader ()
Returns the StAX-like stream reader (provides complete control over the unmarshalling process).
Returns
the stream reader.
Definition at line 221 of file XMLFormat.java.
{
             return _reader;
         }
getText()
CharArray javolution.xml.XMLFormat< T >.InputElement.getText () throws XMLStreamException
Returns the content of a text-only element (equivalent to getStreamReader().getElementText()).
Returns
the element text content or an empty sequence if none.
Definition at line 409 of file XMLFormat.java.
{
             CharArray txt = _reader.getElementText();
             _isReaderAtNext = true; // End element is next.
             return txt;
         }
References javolution.xml.internal.stream.XMLStreamReaderImpl.getElementText().
hasNext()
boolean javolution.xml.XMLFormat< T >.InputElement.hasNext () throws XMLStreamException
Indicates if more nested XML element can be read. This method positions the reader at the start of the next XML element to be read (if any).
Returns
true if there is more XML element to be read; false otherwise.
Definition at line 233 of file XMLFormat.java.
{
             if (!_isReaderAtNext) {
                 _isReaderAtNext = true;
                 _reader.nextTag();
             }
             return _reader.getEventType() == XMLStreamReader.START_ELEMENT;
         }
References javolution.xml.internal.stream.XMLStreamReaderImpl.getEventType(), javolution.xml.internal.stream.XMLStreamReaderImpl.nextTag(), and javolution.xml.stream.XMLStreamConstants.START_ELEMENT.
readInstanceOf()
private<T> T javolution.xml.XMLFormat< T >.InputElement.readInstanceOf (Class cls) throws XMLStreamException package
Definition at line 379 of file XMLFormat.java.
{
             // Retrieves format.
             XMLFormat xmlFormat = _binding.getFormat(cls);
             // Creates object.
             _isReaderAtNext = false; // Makes attributes accessible.
             Object obj = xmlFormat.newInstance(cls, this);
             // Adds reference (before reading to support circular reference).
             if (_referenceResolver != null) {
                 _referenceResolver.createReference(obj, this);
             }
             // Parses xml.
             xmlFormat.read(this, obj);
             if (hasNext()) // Asserts _isReaderAtNext == true
                 throw new XMLStreamException("Incomplete element reading",
                         _reader.getLocation());
             _isReaderAtNext = false; // Skips end element.
             return (T) obj;
         }
References javolution.xml.XMLReferenceResolver.createReference(), javolution.xml.XMLBinding.getFormat(), javolution.xml.internal.stream.XMLStreamReaderImpl.getLocation(), javolution.xml.XMLFormat< T >.newInstance(), and javolution.xml.XMLFormat< T >.read().
readReference()
Object javolution.xml.XMLFormat< T >.InputElement.readReference () throws XMLStreamException private
Definition at line 365 of file XMLFormat.java.
{
             if (_referenceResolver == null)
                 return null;
             Object ref = _referenceResolver.readReference(this);
             if (ref == null)
                 return null;
             if (_reader.next() != XMLStreamReader.END_ELEMENT)
                 throw new XMLStreamException("Non Empty Reference Element");
             _isReaderAtNext = false;
             return ref;
         }
References javolution.xml.stream.XMLStreamConstants.END_ELEMENT, javolution.xml.internal.stream.XMLStreamReaderImpl.next(), and javolution.xml.XMLReferenceResolver.readReference().
reset()
void javolution.xml.XMLFormat< T >.InputElement.reset () package
Definition at line 610 of file XMLFormat.java.
                      {
             _binding = XMLBinding.DEFAULT;
             _isReaderAtNext = false;
             _reader.reset();
             _referenceResolver = null;
         }
References javolution.xml.XMLBinding.DEFAULT, and javolution.xml.internal.stream.XMLStreamReaderImpl.reset().
setBinding()
void javolution.xml.XMLFormat< T >.InputElement.setBinding (XMLBinding xmlBinding) package
Definition at line 600 of file XMLFormat.java.
{
             _binding = xmlBinding;
         }
setReferenceResolver()
void javolution.xml.XMLFormat< T >.InputElement.setReferenceResolver (XMLReferenceResolver xmlReferenceResolver) package
Definition at line 605 of file XMLFormat.java.
{
             _referenceResolver = xmlReferenceResolver;
         }
Member Data Documentation
_binding
XMLBinding javolution.xml.XMLFormat< T >.InputElement._binding private
Holds the XML binding.
Definition at line 196 of file XMLFormat.java.
_isReaderAtNext
boolean javolution.xml.XMLFormat< T >.InputElement._isReaderAtNext private
Indicates if the reader is currently positioned on the next element.
Definition at line 206 of file XMLFormat.java.
_reader
final XMLStreamReaderImpl javolution.xml.XMLFormat< T >.InputElement._reader = new XMLStreamReaderImpl() package
Holds the stream reader.
Definition at line 191 of file XMLFormat.java.
_referenceResolver
XMLReferenceResolver javolution.xml.XMLFormat< T >.InputElement._referenceResolver private
Holds the reference resolver.
Definition at line 201 of file XMLFormat.java.
The documentation for this class was generated from the following file:
XMLFormat.java