Javolution 6.0.0 java: javolution.util.service.CollectionService< E > Interface Template Reference
javolution.util.service.CollectionService< E > Interface Template Reference
Public Member Functions
CollectionService< E > clone () throws CloneNotSupportedException
Equality<? super E > comparator ()
CollectionService< E > threadSafe ()
void perform (Consumer< T > action, T part)
T[] split (int n)
void update (Consumer< T > action, T part)
Detailed Description
The fundamental set of related functionalities required to implement fast collections.
Author
Jean-Marie Dautelle
Version
6.0, July 21, 2013
Definition at line 24 of file CollectionService.java.
Member Function Documentation
clone()
CollectionService<E> javolution.util.service.CollectionService< E >.clone () throws CloneNotSupportedException
Returns a copy of this collection; updates of the copy should not impact the original.
Implemented in javolution.util.internal.table.FastTableImpl< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, and javolution.util.internal.collection.CollectionView< E >.
comparator()
Equality<? super E> javolution.util.service.CollectionService< E >.comparator ()
Returns the comparator used for element equality or order if the collection is sorted.
Implemented in javolution.util.internal.map.MapView< K, V >.KeySet, javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.bitset.BitSetServiceImpl, javolution.util.internal.table.FastTableImpl< E >, javolution.util.internal.table.SubTableImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, javolution.util.internal.collection.SortedCollectionImpl< E >, javolution.util.internal.set.sorted.SubSortedSetImpl< E >, javolution.util.internal.collection.CollectionView< E >, javolution.util.internal.collection.FilteredCollectionImpl< E >, javolution.util.internal.table.UnmodifiableTableImpl< E >, javolution.util.internal.collection.DistinctCollectionImpl< E >, javolution.util.internal.map.MapView< K, V >.EntrySet, javolution.util.internal.table.ReversedTableImpl< E >, javolution.util.internal.collection.ReversedCollectionImpl< E >, javolution.util.internal.collection.UnmodifiableCollectionImpl< E >, javolution.util.internal.collection.ParallelCollectionImpl< E >, and javolution.util.internal.collection.SequentialCollectionImpl< E >.
Referenced by javolution.util.FastTable< javolution.xml.internal.stream.XMLStreamReaderImpl >.sort().
perform()
void javolution.util.function.Splittable< T >.perform (Consumer< T > action, T part) inherited
Executes a read-only action on the specified part of this object.
Parameters
action the read-only action.
part this object or a part of it.
Exceptions
UnsupportedOperationException if the action tries to update the specified part.
split()
T [] javolution.util.function.Splittable< T >.split (int n) inherited
Returns
n
distinct parts of this object. This method may return an array of size less than
n
(e.g. an array of size one if this object cannot split).
Parameters
n the number of parts.
Returns
the distinct parts (or views) for this object.
Exceptions
IllegalArgumentException if
n <= 1
Implemented in javolution.util.internal.map.MapView< K, V >, javolution.util.internal.table.SharedTableImpl< E >, javolution.util.internal.table.TableView< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.CollectionView< E >, javolution.util.internal.table.AtomicTableImpl< E >, javolution.util.internal.map.SharedMapImpl< K, V >, javolution.util.internal.map.FastMapImpl< K, V >, javolution.util.internal.map.AtomicMapImpl< K, V >, javolution.util.internal.collection.AtomicCollectionImpl< E >, and javolution.util.internal.map.MapView< K, V >.EntrySet.
Referenced by javolution.util.internal.map.ParallelMapImpl< K, V >.perform(), and javolution.util.internal.collection.ParallelCollectionImpl< E >.perform().
threadSafe()
CollectionService<E> javolution.util.service.CollectionService< E >.threadSafe ()
Returns a thread-safe version of this service (used during parallel updates).
Implemented in javolution.util.internal.table.SharedTableImpl< E >, javolution.util.internal.table.TableView< E >, javolution.util.internal.collection.SharedCollectionImpl< E >, javolution.util.internal.collection.CollectionView< E >, javolution.util.internal.table.AtomicTableImpl< E >, javolution.util.internal.collection.AtomicCollectionImpl< E >, javolution.util.internal.map.sorted.SortedMapView< K, V >.KeySortedSet, javolution.util.internal.collection.UnmodifiableCollectionImpl< E >, javolution.util.internal.set.sorted.SharedSortedSetImpl< E >, javolution.util.internal.map.sorted.SortedMapView< K, V >.EntrySortedSet, javolution.util.internal.table.UnmodifiableTableImpl< E >, javolution.util.internal.table.sorted.SortedTableView< E >, javolution.util.internal.table.sorted.FastSortedTableImpl< E >, javolution.util.internal.set.sorted.UnmodifiableSortedSetImpl< E >, javolution.util.internal.set.sorted.AtomicSortedSetImpl< E >, javolution.util.internal.set.sorted.SortedSetView< E >, javolution.util.internal.table.sorted.SharedSortedTableImpl< E >, javolution.util.internal.table.sorted.AtomicSortedTableImpl< E >, javolution.util.internal.set.SetView< E >, javolution.util.internal.set.MappedSetImpl< E, R >, javolution.util.internal.table.sorted.UnmodifiableSortedTableImpl< E >, javolution.util.service.SortedTableService< E >, javolution.util.service.SortedSetService< E >, javolution.util.internal.set.FilteredSetImpl< E >, javolution.util.service.TableService< E >, javolution.util.internal.set.AtomicSetImpl< E >, javolution.util.internal.set.SharedSetImpl< E >, javolution.util.internal.set.UnmodifiableSetImpl< E >, and javolution.util.service.SetService< E >.
Referenced by javolution.util.internal.collection.ParallelCollectionImpl< E >.update().
update()
void javolution.util.function.Splittable< T >.update (Consumer< T > action, T part) inherited
Executes an update action on the specified part of this object. Any change to the part is reflected in the whole (this object).
Parameters
action the action authorized to update this object part.
part this object or a part of it.
The documentation for this interface was generated from the following file:
CollectionService.java