Javolution 6.0.0 java: javolution.context.SecurityContext Class Reference
javolution.context.SecurityContext Class Reference abstract
Classes
class Permission
Public Member Functions
abstract boolean isGranted (Permission<?> permission)
abstract void grant (Permission<?> permission, Object certificate)
abstract void revoke (Permission<?> permission, Object certificate)
final void grant (Permission<?> permission)
final void revoke (Permission<?> permission)
void exit ()
Static Public Member Functions
static SecurityContext enter ()
static void check (Permission<?> permission)
static AbstractContext current ()
static< T extends AbstractContext > T enter (Class< T > custom)
static void inherit (AbstractContext ctx)
Protected Member Functions
SecurityContext ()
AbstractContext enterInner ()
AbstractContext getOuter ()
abstract AbstractContext inner ()
Static Protected Member Functions
static< T extends AbstractContext > T current (Class< T > type)
Static Private Member Functions
static SecurityContext currentSecurityContext ()
Private Attributes
AbstractContext outer
Static Private Attributes
static final ThreadLocal< AbstractContext > CURRENT = new ThreadLocal<AbstractContext>()
Detailed Description
A high-level security context integrated with OSGi.
When granting/revoking permission the order is important. For example, the following code revokes all configurable permissions except for setting the concurrency level. [code] SecurityContext ctx = SecurityContext.enter(); try { ctx.revoke(Configurable.RECONFIGURE_PERMISSION); ctx.grant(ConcurrentContext.CONCURRENCY.getReconfigurePermission()); ... ConcurrentContext.CONCURRENCY.reconfigure(0); // Ok (permission specifically granted). ... } finally { ctx.exit(); // Back to previous security settings. }[/code]
Author
Jean-Marie Dautelle
Version
6.0, July 21, 2013
Definition at line 34 of file SecurityContext.java.
Constructor & Destructor Documentation
SecurityContext()
javolution.context.SecurityContext.SecurityContext () protected
Default constructor.
Definition at line 178 of file SecurityContext.java.
 {}
Member Function Documentation
check()
static void javolution.context.SecurityContext.check (Permission<?> permission) static
Checks if the specified permission is granted.
Parameters
permission the permission to check.
Exceptions
SecurityException if the specified permission is not granted.
Definition at line 195 of file SecurityContext.java.
{
         if (!currentSecurityContext().isGranted(permission))
             throw new SecurityException(permission + " is not granted.");
     }
References javolution.context.SecurityContext.currentSecurityContext(), and javolution.context.SecurityContext.isGranted().
Referenced by javolution.context.AbstractContext.enter(), and javolution.lang.Configurable< javolution.context.LogContext.Level >.reconfigure().
current() [1/2]
static AbstractContext javolution.context.AbstractContext.current () static inherited
Returns the current context for the current thread or
null
if this thread has no context (default).
Definition at line 61 of file AbstractContext.java.
{
         return AbstractContext.CURRENT.get();
     }
References javolution.context.AbstractContext.CURRENT.
Referenced by javolution.context.LogContext.currentLogContext(), javolution.context.SecurityContext.currentSecurityContext(), javolution.text.TextContext.currentTextContext(), javolution.xml.XMLContext.currentXMLContext(), javolution.context.LocalContext.enter(), javolution.context.ConcurrentContext.enter(), and javolution.context.LocalContext.Parameter< T >.get().
current() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.current (Class< T > type) static protected inherited
Returns the current context of specified type or
null
if none.
Definition at line 69 of file AbstractContext.java.
{
         AbstractContext ctx = AbstractContext.CURRENT.get();
         while (ctx != null) {
             if (type.isInstance(ctx))
                 return (T) ctx;
             ctx = ctx.outer;
         }
         return null;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
currentSecurityContext()
static SecurityContext javolution.context.SecurityContext.currentSecurityContext () static private
Returns the current security context.
Definition at line 250 of file SecurityContext.java.
{
         SecurityContext ctx = current(SecurityContext.class);
         if (ctx != null)
             return ctx;
         return OSGiServices.getSecurityContext();
     }
References javolution.context.AbstractContext.current(), and javolution.osgi.internal.OSGiServices.getSecurityContext().
Referenced by javolution.context.SecurityContext.check(), and javolution.context.SecurityContext.enter().
enter() [1/2]
static SecurityContext javolution.context.SecurityContext.enter () static
Enters and returns a new security context instance.
Returns
the new security context implementation entered.
Definition at line 185 of file SecurityContext.java.
{
         return (SecurityContext) currentSecurityContext().enterInner();
     }
References javolution.context.SecurityContext.currentSecurityContext(), and javolution.context.AbstractContext.enterInner().
enter() [2/2]
static <T extends AbstractContext> T javolution.context.AbstractContext.enter (Class< T > custom) static inherited
Enters the scope of a custom context. This method raises a SecurityException if the permission to enter contexts of the specified class is not granted. For example, the following disallow entering any custom context. [code] SecurityContext ctx = SecurityContext.enter(); try { ctx.revoke(new SecurityContext.Permission(AbstractContext.class, "enter")); ... // Cannot enter any custom context. } finally { ctx.exit(); // Back to previous security settings. }[/code]
Parameters
custom the custom context to enter.
Exceptions
IllegalArgumentException if the specified class default constructor cannot be instantiated.
SecurityException if
SecurityContext.Permission(custom, "enter")
is not granted.
See also
SecurityContext.Permission
Definition at line 101 of file AbstractContext.java.
{
         SecurityContext.check(new Permission<T>(custom, "enter"));
         try {
             return (T) custom.newInstance().enterInner();
         } catch (InstantiationException e) {
             throw new IllegalArgumentException(
                     "Cannot instantiate instance of " + custom, e);
         } catch (IllegalAccessException e) {
             throw new IllegalArgumentException("Cannot access " + custom, e);
         }
     }
References javolution.context.SecurityContext.check().
enterInner()
AbstractContext javolution.context.AbstractContext.enterInner () protected inherited
Enters the scope of an inner context which becomes the current context; the previous current context becomes the outer of this context.
Returns
the inner context entered.
Definition at line 141 of file AbstractContext.java.
{
         AbstractContext inner = inner();
         inner.outer = AbstractContext.CURRENT.get();
         AbstractContext.CURRENT.set(inner);
         return inner;
     }
References javolution.context.AbstractContext.CURRENT, and javolution.context.AbstractContext.outer.
Referenced by javolution.xml.XMLContext.enter(), javolution.text.TextContext.enter(), javolution.context.LogContext.enter(), javolution.context.LocalContext.enter(), javolution.context.SecurityContext.enter(), and javolution.context.ConcurrentContext.enter().
exit()
void javolution.context.AbstractContext.exit () inherited
Exits the scope of this context; the outer of this context becomes
the current context.
Exceptions
IllegalStateException if this context is not the current context.
Reimplemented in javolution.context.ConcurrentContext, and javolution.context.internal.ConcurrentContextImpl.
Definition at line 155 of file AbstractContext.java.
{
         if (this != AbstractContext.CURRENT.get())
             throw new IllegalStateException(
                     "This context is not the current context");
         AbstractContext.CURRENT.set(outer);
         outer = null;
     }
References javolution.context.AbstractContext.CURRENT.
getOuter()
AbstractContext javolution.context.AbstractContext.getOuter () protected inherited
Returns the outer context of this context or
null
if this context has no outer context.
Definition at line 167 of file AbstractContext.java.
{
         return outer;
     }
grant() [1/2]
final void javolution.context.SecurityContext.grant (Permission<?> permission)
Grants the specified permission (convenience method).
Parameters
permission the permission to grant.
Exceptions
SecurityException if the specified permission cannot be granted.
Definition at line 233 of file SecurityContext.java.
{
         grant(permission, null);
     }
References javolution.context.SecurityContext.grant().
grant() [2/2]
abstract void javolution.context.SecurityContext.grant (Permission<?> permission, Object certificate) abstract
Grants the specified permission.
Parameters
permission the permission to grant.
certificate the certificate used to grant that permission or null if none.
Exceptions
SecurityException if the specified permission cannot be granted.
Reimplemented in javolution.context.internal.SecurityContextImpl.
Referenced by javolution.context.SecurityContext.grant().
inherit()
static void javolution.context.AbstractContext.inherit (AbstractContext ctx) static inherited
Inherits the specified context which becomes the context of the current thread. This method is particularly useful when creating new threads to make them inherits from the context stack of the parent thread. [code] //Spawns a new thread inheriting the context of the current thread. MyThread myThread = new MyThread(); myThread.inherited = AbstractContext.current(); myThread.start(); ... class MyThread extends Thread { AbstractContext inherited; public void run() { AbstractContext.inherit(inherited); // Sets current context. ... } }[/code]
Definition at line 131 of file AbstractContext.java.
{
         CURRENT.set(ctx);
     }
Referenced by javolution.context.internal.ConcurrentThreadImpl.run().
inner()
abstract AbstractContext javolution.context.AbstractContext.inner () abstract protected inherited
Returns a new inner instance of this context inheriting the properties of this context. The new instance can be configured independently from its parent.
Reimplemented in javolution.context.internal.ConcurrentContextImpl, javolution.text.internal.TextContextImpl, javolution.context.internal.LogContextImpl, javolution.context.internal.SecurityContextImpl, javolution.xml.internal.XMLContextImpl, and javolution.context.internal.LocalContextImpl.
isGranted()
abstract boolean javolution.context.SecurityContext.isGranted (Permission<?> permission) abstract
Indicates if the specified permission is granted.
Parameters
permission the permission to check.
Reimplemented in javolution.context.internal.SecurityContextImpl.
Referenced by javolution.context.SecurityContext.check().
revoke() [1/2]
final void javolution.context.SecurityContext.revoke (Permission<?> permission)
Revokes the specified permission (convenience method).
Parameters
permission the permission to grant.
Exceptions
SecurityException if the specified permission cannot be revoked.
Definition at line 243 of file SecurityContext.java.
{
         revoke(permission, null);
     }
References javolution.context.SecurityContext.revoke().
revoke() [2/2]
abstract void javolution.context.SecurityContext.revoke (Permission<?> permission, Object certificate) abstract
Revokes the specified permission.
Parameters
permission the permission to grant.
certificate the certificate used to grant that permission or null if none.
Exceptions
SecurityException if the specified permission cannot be revoked.
Reimplemented in javolution.context.internal.SecurityContextImpl.
Referenced by javolution.context.SecurityContext.revoke().
Member Data Documentation
CURRENT
final ThreadLocal<AbstractContext> javolution.context.AbstractContext.CURRENT = new ThreadLocal<AbstractContext>() static private inherited
Holds the last context entered (thread-local).
Definition at line 45 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), javolution.context.AbstractContext.enterInner(), and javolution.context.AbstractContext.exit().
outer
AbstractContext javolution.context.AbstractContext.outer private inherited
Holds the outer context or
null
if none (top context).
Definition at line 50 of file AbstractContext.java.
Referenced by javolution.context.AbstractContext.current(), and javolution.context.AbstractContext.enterInner().
The documentation for this class was generated from the following file:
SecurityContext.java