Javolution 6.0.0 java: javolution.util.internal.bitset.BitSetIteratorImpl Class Reference
javolution.util.internal.bitset.BitSetIteratorImpl Class Reference
Public Member Functions
BitSetIteratorImpl (BitSetService that, int index)
boolean hasNext ()
Index next ()
void remove ()
Private Attributes
final BitSetService that
int nextIndex
int currentIndex = -1
Detailed Description
An iterator over a bit set.
Definition at line 20 of file BitSetIteratorImpl.java.
Constructor & Destructor Documentation
BitSetIteratorImpl()
javolution.util.internal.bitset.BitSetIteratorImpl.BitSetIteratorImpl (BitSetService that, int index)
Definition at line 28 of file BitSetIteratorImpl.java.
{
         this.that = that;
         this.nextIndex = that.nextSetBit(index);
     }
References javolution.util.service.BitSetService.nextSetBit(), and javolution.util.internal.bitset.BitSetIteratorImpl.that.
Member Function Documentation
hasNext()
boolean javolution.util.internal.bitset.BitSetIteratorImpl.hasNext ()
Definition at line 33 of file BitSetIteratorImpl.java.
{
         return (nextIndex >= 0);
     }
References javolution.util.internal.bitset.BitSetIteratorImpl.nextIndex.
next()
Index javolution.util.internal.bitset.BitSetIteratorImpl.next ()
Definition at line 37 of file BitSetIteratorImpl.java.
{
         if (nextIndex < 0)
             throw new NoSuchElementException();
         currentIndex = nextIndex;
         nextIndex = that.nextSetBit(nextIndex);
         return Index.valueOf(currentIndex);
     }
References javolution.util.internal.bitset.BitSetIteratorImpl.currentIndex, javolution.util.internal.bitset.BitSetIteratorImpl.nextIndex, javolution.util.service.BitSetService.nextSetBit(), javolution.util.internal.bitset.BitSetIteratorImpl.that, and javolution.util.Index.valueOf().
remove()
void javolution.util.internal.bitset.BitSetIteratorImpl.remove ()
Definition at line 45 of file BitSetIteratorImpl.java.
{
         if (currentIndex < 0)
             throw new IllegalStateException();
         that.clear(currentIndex);
         currentIndex = -1;
     }
References javolution.util.service.BitSetService.clear(), javolution.util.internal.bitset.BitSetIteratorImpl.currentIndex, and javolution.util.internal.bitset.BitSetIteratorImpl.that.
Member Data Documentation
currentIndex
int javolution.util.internal.bitset.BitSetIteratorImpl.currentIndex = -1 private
Definition at line 26 of file BitSetIteratorImpl.java.
Referenced by javolution.util.internal.bitset.BitSetIteratorImpl.next(), and javolution.util.internal.bitset.BitSetIteratorImpl.remove().
nextIndex
int javolution.util.internal.bitset.BitSetIteratorImpl.nextIndex private
Definition at line 24 of file BitSetIteratorImpl.java.
Referenced by javolution.util.internal.bitset.BitSetIteratorImpl.hasNext(), and javolution.util.internal.bitset.BitSetIteratorImpl.next().
that
final BitSetService javolution.util.internal.bitset.BitSetIteratorImpl.that private
Definition at line 22 of file BitSetIteratorImpl.java.
Referenced by javolution.util.internal.bitset.BitSetIteratorImpl.BitSetIteratorImpl(), javolution.util.internal.bitset.BitSetIteratorImpl.next(), and javolution.util.internal.bitset.BitSetIteratorImpl.remove().
The documentation for this class was generated from the following file:
BitSetIteratorImpl.java