Javolution 6.0.0 java: javolution.lang.Initializer Class Reference
javolution.lang.Initializer Class Reference
Public Member Functions
Initializer (ClassLoader classLoader)
Class<?>[] loadedClasses ()
void loadClass (Class<?> cls)
boolean initializeLoadedClasses ()
Static Public Attributes
static final Configurable< Boolean > SHOW_INITIALIZED
Private Attributes
final ClassLoader classLoader
Detailed Description
An initializer for all classes loaded by any given class loader.
Initialization of classes at startup (or during bundle activation) ensures a significantly improved worst case execution time especially if the classes has configuration logic to be executed then.
Javolution activator initialize Realtime classes when started. When running outside OSGi the method
javolution.osgi.internal.OSGiServices.initializeRealtimeClasses()
can be used to that effect..
Class loading can be performed in a lazy manner and therefore some parts of the class loading process may be done on first use rather than at load time. Javolution bundle activator ensure that all its classes are initialized at start up. The following code illustrates how this can be done for any bundle. [code] public class MyActivator implements BundleActivator { public void start(BundleContext bc) throws Exception { Initializer initializer = new Initializer(MyActivator.class.getClassLoader()); initializer.loadClass(com.foo.internal.UnreferencedClass.class); // Load explicitly classes not directly or indirectly referenced. ... initializer.initializeLoadedClasses(); // Recursive loading/initialization. ... // Continue activation } }[/code]
This utility use reflection to find the classes loaded and may not be supported on all platforms.
Author
Jean-Marie Dautelle
Version
5.1, July 26, 2007
Definition at line 50 of file Initializer.java.
Constructor & Destructor Documentation
Initializer()
javolution.lang.Initializer.Initializer (ClassLoader classLoader)
Creates an initializer for the specified class loader.
Definition at line 69 of file Initializer.java.
{
         this.classLoader = classLoader;
     }
References javolution.lang.Initializer.classLoader.
Member Function Documentation
initializeLoadedClasses()
boolean javolution.lang.Initializer.initializeLoadedClasses ()
Initializes all the loaded classes. If the initialization leads to more classes being loaded, these classes are initialized as well (recursive process).
Returns
true
if initialization has been performed successfully;
false
otherwise.
Definition at line 119 of file Initializer.java.
{
         boolean isInitializationSuccessful = true;
         int nbrClassesInitialized = 0;
         while (true) {
             Class<?>[] classes = loadedClasses();
             if (classes == null) {
                 LogContext
                         .debug("Automatic class initialization not supported.");
                 return false;
             }
             if (nbrClassesInitialized >= classes.length)
                 break; // Done.
             for (int i = nbrClassesInitialized; i < classes.length; i++) {
                 Class<?> cls = classes[i];
                 try {
                     if (SHOW_INITIALIZED.get())
                         LogContext.debug("Initialize ", cls.getName());
                     Class.forName(cls.getName(), true, classLoader);
                 } catch (ClassNotFoundException ex) {
                     isInitializationSuccessful = false;
                     LogContext.error(ex); // Should never happen.
                 }
             }
             nbrClassesInitialized = classes.length;
         }
         LogContext.debug("Initialization of ", nbrClassesInitialized,
                 " classes loaded by ", classLoader);
         return isInitializationSuccessful;
     }
References javolution.lang.Initializer.classLoader, javolution.context.LogContext.debug(), javolution.context.LogContext.error(), javolution.lang.Configurable< T >.get(), javolution.lang.Initializer.loadedClasses(), and javolution.lang.Initializer.SHOW_INITIALIZED.
Referenced by javolution.osgi.internal.OSGiServices.initializeRealtimeClasses().
loadClass()
void javolution.lang.Initializer.loadClass (Class<?> cls)
Loads the specified class (does not perform any initialization). This method is typically used to load unreferenced classes.
Definition at line 103 of file Initializer.java.
{
         try {
             classLoader.loadClass(cls.getName());
         } catch (ClassNotFoundException e) {
             LogContext.debug("Class " + cls + " not found.");
         }
     }
References javolution.lang.Initializer.classLoader, and javolution.context.LogContext.debug().
Referenced by javolution.osgi.internal.OSGiServices.initializeRealtimeClasses().
loadedClasses()
Class<?> [] javolution.lang.Initializer.loadedClasses ()
Returns the classes loaded by the class loader of this initializer or null if not supported by the platform.
Definition at line 78 of file Initializer.java.
{
         Class<?> cls = classLoader.getClass();
         while (cls != java.lang.ClassLoader.class) {
             cls = cls.getSuperclass();
         }
         try {
             java.lang.reflect.Field fldClasses = cls
                     .getDeclaredField("classes");
             fldClasses.setAccessible(true);
             Vector<Class<?>> list = (Vector<Class<?>>) fldClasses
                     .get(classLoader);
             Class<?>[] classes = new Class<?>[list.size()];
             for (int i = 0; i < classes.length; i++) {
                 classes[i] = list.get(i);
             }
             return classes;
         } catch (Throwable e) {
             return null;
         }
     }
References javolution.lang.Initializer.classLoader.
Referenced by javolution.lang.Initializer.initializeLoadedClasses().
Member Data Documentation
classLoader
final ClassLoader javolution.lang.Initializer.classLoader private
The class loader for this initializer
Definition at line 64 of file Initializer.java.
Referenced by javolution.lang.Initializer.initializeLoadedClasses(), javolution.lang.Initializer.Initializer(), javolution.lang.Initializer.loadClass(), and javolution.lang.Initializer.loadedClasses().
SHOW_INITIALIZED
final Configurable<Boolean> javolution.lang.Initializer.SHOW_INITIALIZED static
Initial value:
= new Configurable<Boolean>() {
        @Override
        protected Boolean getDefault() {
            return false;
        }
    }
Indicates if the class being initialized should be logged (default
false
).
Definition at line 56 of file Initializer.java.
Referenced by javolution.lang.Initializer.initializeLoadedClasses().
The documentation for this class was generated from the following file:
Initializer.java