Javolution 6.0.0 java: javolution.text.Cursor Class Reference
javolution.text.Cursor Class Reference
Public Member Functions
Cursor ()
final int getIndex ()
final void setIndex (int i)
final boolean atEnd (CharSequence csq)
final boolean at (char c, CharSequence csq)
final boolean at (CharSet charSet, CharSequence csq)
final boolean at (String str, CharSequence csq)
final char currentChar (CharSequence csq)
final char nextChar (CharSequence csq)
final boolean skipAny (char c, CharSequence csq)
final boolean skipAny (CharSet charSet, CharSequence csq)
final boolean skip (char c, CharSequence csq)
final boolean skip (CharSet charSet, CharSequence csq)
final boolean skip (String str, CharSequence csq)
final CharSequence nextToken (CharSequence csq, char c)
final CharSequence nextToken (CharSequence csq, CharSet charSet)
final CharSequence head (CharSequence csq)
final CharSequence tail (CharSequence csq)
final Cursor increment ()
final Cursor increment (int i)
String toString ()
boolean equals (Object obj)
int hashCode ()
Private Attributes
int index
Detailed Description
A parsing cursor over the characters read. Cursor allows for token iterations over any CharSequence. [code] String str = "this is a test"; Cursor cursor = new Cursor(); for (CharSequence token; (token=cursor.nextToken(str, ' '))!= null;) System.out.println(token); [/code] Prints the following output:
       this
       is
       a
       test
Cursors are typically used with TextFormat instances. [code] // Parses decimal number (e.g. "xxx.xxxxxExx" or "NaN") public Decimal parse(CharSequence csq, Cursor cursor) throws IllegalArgumentException { TextFormat<LargeInteger> largeIntegerFormat = TextContext.getFormat(LargeInteger.class); if (cursor.skip("NaN", csq)) return Decimal.NaN; LargeInteger significand = LargeIntegerFormat.parse(csq, cursor); LargeInteger fraction = cursor.skip('.', csq) ? largeIntegerFormat.parse(csq, cursor) : LargeInteger.ZERO; int exponent = cursor.skip(CharSet.valueOf('E', 'e'), csq) ? TypeFormat.parseInt(csq, cursor) : 0; int fractionDigits = fraction.digitLength(); return Decimal.valueOf(significand.E(fractionDigits).plus(fraction), exponent - fractionDigits); } [/code]
Author
Jean-Marie Dautelle
Version
5.4, November 19, 2009
Definition at line 44 of file Cursor.java.
Constructor & Destructor Documentation
Cursor()
javolution.text.Cursor.Cursor ()
Default constructor.
Definition at line 54 of file Cursor.java.
 {}
Referenced by javolution.text.Cursor.equals().
Member Function Documentation
at() [1/3]
final boolean javolution.text.Cursor.at (char c, CharSequence csq)
Indicates if this cursor points to the specified character in the specified character sequence.
Parameters
c the character to test.
csq the character sequence iterated by this cursor.
Returns
csq.charAt(this.getIndex()) == c
Definition at line 93 of file Cursor.java.
{
         return index < csq.length() ? csq.charAt(index) == c : false;
     }
References javolution.text.Cursor.index.
Referenced by javolution.text.Cursor.skip().
at() [2/3]
final boolean javolution.text.Cursor.at (CharSet charSet, CharSequence csq)
Indicates if this cursor points to any of the specified character in the specified character sequence.
Parameters
charSet any of the character to test.
csq the character sequence iterated by this cursor.
Returns
csq.charAt(this.getIndex()) == c
Definition at line 105 of file Cursor.java.
{
         return index < csq.length() ? charSet.contains(csq.charAt(index))
                 : false;
     }
References javolution.text.CharSet.contains(), and javolution.text.Cursor.index.
at() [3/3]
final boolean javolution.text.Cursor.at (String str, CharSequence csq)
Indicates if this cursor points to the specified characters in the specified sequence.
Parameters
str the characters to test.
csq the character sequence iterated by this cursor.
Returns
true if this cursor points to the specified characters; false otherwise.
Definition at line 119 of file Cursor.java.
{
         int i = index;
         int length = csq.length();
         for (int j = 0; j < str.length();) {
             if ((i >= length) || (str.charAt(j++) != csq.charAt(i++)))
                 return false;
         }
         return true;
     }
References javolution.text.Cursor.index.
atEnd()
final boolean javolution.text.Cursor.atEnd (CharSequence csq)
Indicates if this cursor points to the end of the specified character sequence.
Parameters
csq the character sequence iterated by this cursor.
Returns
getIndex() >= csq.length()
Definition at line 81 of file Cursor.java.
{
         return index >= csq.length();
     }
References javolution.text.Cursor.index.
Referenced by javolution.text.TextFormat< FastCollection<?> >.parse(), javolution.text.TypeFormat.parseBoolean(), javolution.text.TypeFormat.parseByte(), javolution.text.TypeFormat.parseDouble(), javolution.text.TypeFormat.parseInt(), javolution.text.TypeFormat.parseLong(), and javolution.text.TypeFormat.parseShort().
currentChar()
final char javolution.text.Cursor.currentChar (CharSequence csq)
Returns the current character at this cursor position.
Parameters
csq the character sequence iterated by this cursor.
Returns
the current character this cursor points to.
Exceptions
IndexOutOfBoundsException if this.atEnd(csq)
Definition at line 136 of file Cursor.java.
{
         return csq.charAt(index);
     }
References javolution.text.Cursor.index.
equals()
boolean javolution.text.Cursor.equals (Object obj)
Indicates if this cursor is equals to the specified object.
Returns
true if the specified object is a cursor at the same index; false otherwise.
Definition at line 380 of file Cursor.java.
{
         if (obj == null)
             return false;
         if (!(obj instanceof Cursor))
             return false;
         return index == ((Cursor) obj).index;
     }
References javolution.text.Cursor.Cursor(), and javolution.text.Cursor.index.
getIndex()
final int javolution.text.Cursor.getIndex ()
Returns this cursor index.
Returns
the index of the next character to parse.
Definition at line 61 of file Cursor.java.
{
         return index;
     }
References javolution.text.Cursor.index.
Referenced by javolution.text.TypeFormat.parseBoolean(), javolution.text.TypeFormat.parseInt(), and javolution.text.TypeFormat.parseLong().
hashCode()
int javolution.text.Cursor.hashCode ()
Returns the hash code for this cursor.
Returns
the hash code value for this object
Definition at line 394 of file Cursor.java.
{
         return index;
     }
References javolution.text.Cursor.index.
head()
final CharSequence javolution.text.Cursor.head (CharSequence csq)
Returns the head of the specified character sequence until
this cursor position.
Returns
the corresponding sub-sequence.
Definition at line 329 of file Cursor.java.
{
         return csq.subSequence(0, index);
     }
References javolution.text.Cursor.index.
increment() [1/2]
final Cursor javolution.text.Cursor.increment ()
Increments the cursor index by one.
Returns
this
Definition at line 348 of file Cursor.java.
{
         return increment(1);
     }
Referenced by javolution.text.TypeFormat.parseBoolean(), javolution.text.TypeFormat.parseInt(), and javolution.text.TypeFormat.parseLong().
increment() [2/2]
final Cursor javolution.text.Cursor.increment (int i)
Increments the cursor index by the specified value.
Parameters
i the increment value.
Returns
this
Definition at line 358 of file Cursor.java.
{
         index += i;
         return this;
     }
References javolution.text.Cursor.index.
nextChar()
final char javolution.text.Cursor.nextChar (CharSequence csq)
Returns the next character at this cursor position.The cursor position is incremented by one.
Parameters
csq the character sequence iterated by this cursor.
Returns
the next character this cursor points to.
Exceptions
IndexOutOfBoundsException if this.atEnd(csq)
Definition at line 148 of file Cursor.java.
{
         return csq.charAt(index++);
     }
References javolution.text.Cursor.index.
nextToken() [1/2]
final CharSequence javolution.text.Cursor.nextToken (CharSequence csq, char c)
Returns the subsequence from the specified cursor position not holding the specified character. For example:[code] CharSequence csq = "This is a test"; for (CharSequence token; (token=cursor.nextToken(csq, ' '))!= null;) { System.out.println(token); // Prints one word at a time. }[/code]
Parameters
csq the character sequence iterated by this cursor.
c the character being skipped.
Returns
the subsequence not holding the specified character or null if none.
Definition at line 278 of file Cursor.java.
{
         int n = csq.length();
         for (int i = index; i < n; i++) {
             if (csq.charAt(i) != c) {
                 int j = i;
                 for (; (++j < n) && (csq.charAt(j) != c);) {
                     // Loop until j at the end of sequence or at specified character.
                 }
                 index = j;
                 return csq.subSequence(i, j);
             }
         }
         index = n;
         return null;
     }
References javolution.text.Cursor.index.
nextToken() [2/2]
final CharSequence javolution.text.Cursor.nextToken (CharSequence csq, CharSet charSet)
Returns the subsequence from the specified cursor position not holding any of the characters specified. For example:[code] CharSequence csq = "This is a test"; for (CharSequence token; (token=cursor.nextToken(csq, CharSet.WHITESPACE))!= null;) { System.out.println(token); // Prints one word at a time. }[/code]
Parameters
csq the character sequence iterated by this cursor.
charSet the characters being skipped.
Returns
the subsequence not holding the specified character or null if none.
Definition at line 307 of file Cursor.java.
{
         int n = csq.length();
         for (int i = index; i < n; i++) {
             if (!charSet.contains(csq.charAt(i))) {
                 int j = i;
                 for (; (++j < n) && !charSet.contains(csq.charAt(j));) {
                     // Loop until j at the end of sequence or at specified characters.
                 }
                 index = j;
                 return csq.subSequence(i, j);
             }
         }
         index = n;
         return null;
     }
References javolution.text.CharSet.contains(), and javolution.text.Cursor.index.
setIndex()
final void javolution.text.Cursor.setIndex (int i)
Sets the cursor current index.
Parameters
i the index of the next character to parse.
Definition at line 70 of file Cursor.java.
{
         index = i;
     }
References javolution.text.Cursor.index.
skip() [1/3]
final boolean javolution.text.Cursor.skip (char c, CharSequence csq)
Moves this cursor forward only if at the specified character. This method is equivalent to: [code] if (at(c, csq)) increment(); [/code]
Parameters
c the character to skip.
csq the character sequence iterated by this cursor.
Returns
true if this cursor has skipped the specified character;false otherwise.
Definition at line 211 of file Cursor.java.
{
         if (this.at(c, csq)) {
             index++;
             return true;
         } else {
             return false;
         }
     }
References javolution.text.Cursor.at(), and javolution.text.Cursor.index.
skip() [2/3]
final boolean javolution.text.Cursor.skip (CharSet charSet, CharSequence csq)
Moves this cursor forward only if at any of the specified character. This method is equivalent to: [code] if (at(charSet, csq)) increment(); [/code]
Parameters
charSet holding the characters to skip.
csq the character sequence iterated by this cursor.
Returns
true if this cursor has skipped any the specified character;false otherwise.
Definition at line 233 of file Cursor.java.
{
         if (this.at(charSet, csq)) {
             index++;
             return true;
         } else {
             return false;
         }
     }
References javolution.text.Cursor.at(), and javolution.text.Cursor.index.
skip() [3/3]
final boolean javolution.text.Cursor.skip (String str, CharSequence csq)
Moves this cursor forward only if at the specified string. This method is equivalent to: [code] if (at(str, csq)) increment(str.length()); [/code]
Parameters
str the string to skip.
csq the character sequence iterated by this cursor.
Returns
true if this cursor has skipped the specified string;false otherwise (e.g. end of sequence reached).
Definition at line 256 of file Cursor.java.
{
         if (this.at(str, csq)) {
             index += str.length();
             return true;
         } else {
             return false;
         }
     }
References javolution.text.Cursor.at(), and javolution.text.Cursor.index.
skipAny() [1/2]
final boolean javolution.text.Cursor.skipAny (char c, CharSequence csq)
Moves this cursor forward until it points to a character different from the specified character.
Parameters
c the character to skip.
csq the character sequence iterated by this cursor.
Returns
true if this cursor has skipped at least one character;false otherwise (e.g. end of sequence reached).
Definition at line 162 of file Cursor.java.
{
         int i = index;
         int n = csq.length();
         for (; (i < n) && (csq.charAt(i) == c); i++) {}
         if (i == index)
             return false; // Cursor did not moved.
         index = i;
         return true;
     }
References javolution.text.Cursor.index.
skipAny() [2/2]
final boolean javolution.text.Cursor.skipAny (CharSet charSet, CharSequence csq)
Moves this cursor forward until it points to a character different from any of the character in the specified set. For example: [code] // Reads numbers separated by tabulations or spaces. FastTable<Integer> numbers = new FastTable<Integer>(); while (cursor.skipAny(CharSet.SPACE_OR_TAB, csq)) { numbers.add(TypeFormat.parseInt(csq, cursor)); }[/code]
Parameters
charSet the character to skip.
csq the character sequence iterated by this cursor.
Returns
true if this cursor has skipped at least one character;false otherwise (e.g. end of sequence reached).
Definition at line 188 of file Cursor.java.
{
         int i = index;
         int n = csq.length();
         for (; (i < n) && charSet.contains(csq.charAt(i)); i++) {}
         if (i == index)
             return false; // Cursor did not moved.
         index = i;
         return true;
     }
References javolution.text.CharSet.contains(), and javolution.text.Cursor.index.
tail()
final CharSequence javolution.text.Cursor.tail (CharSequence csq)
Returns the tail of the specified character sequence starting at this cursor position.
Returns
the corresponding sub-sequence.
Definition at line 339 of file Cursor.java.
{
         return csq.subSequence(index, csq.length());
     }
References javolution.text.Cursor.index.
Referenced by javolution.text.TextFormat< FastCollection<?> >.parse(), javolution.text.TypeFormat.parseBoolean(), javolution.text.TypeFormat.parseByte(), javolution.text.TypeFormat.parseDouble(), javolution.text.TypeFormat.parseInt(), javolution.text.TypeFormat.parseLong(), and javolution.text.TypeFormat.parseShort().
toString()
String javolution.text.Cursor.toString ()
Returns the string representation of this cursor.
Returns
the index value as a string.
Definition at line 369 of file Cursor.java.
{
         return "Cursor: " + index;
     }
References javolution.text.Cursor.index.
Member Data Documentation
index
int javolution.text.Cursor.index private
Holds the index.
Definition at line 49 of file Cursor.java.
Referenced by javolution.text.Cursor.at(), javolution.text.Cursor.atEnd(), javolution.text.Cursor.currentChar(), javolution.text.Cursor.equals(), javolution.text.Cursor.getIndex(), javolution.text.Cursor.hashCode(), javolution.text.Cursor.head(), javolution.text.Cursor.increment(), javolution.text.Cursor.nextChar(), javolution.text.Cursor.nextToken(), javolution.text.Cursor.setIndex(), javolution.text.Cursor.skip(), javolution.text.Cursor.skipAny(), javolution.text.Cursor.tail(), and javolution.text.Cursor.toString().
The documentation for this class was generated from the following file:
Cursor.java